### ISSUE TITLE
Task launch with custom properties are not picked up

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1012]
As a user, I'm launching a task with deployment properties; however, they aren't being picked up at the runtime. 

**Sample:**
> task launch census_batch --properties "app.census_batch.spring.cloud.deployer.cloudfoundry.services='my-config,df-mysql',app.census_batch.spring.profiles.active=master,app.census_batch.spring.cloud.config.uri=http://my-config.local.pcfdev.io"

**Acceptance:**
I should be able to launch a task with deployment properties and they are applied to the task application at runtime.

**Comment by jvalkeal** [comment]
I'd say this is working as designed. `--properties` are passed to `TaskLauncher` as a `deploymentProperties` and those are implementation specific and never intended to be passed to tasks. `--arguments` are supposed to get passed to a task as `runtimeParams`.
