### ISSUE TITLE
Dataflow doesn't work as @SpringBootApplication

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#1026]
Initializr will create app using `@SpringBootApplication` which breaks DB config as `@EnableDataFlowServer` imports `DataFlowServerConfiguration`.

```
@SpringBootApplication
public class LocalDataFlowServer {}
```

So you need to fix it like `LocalDataFlowServer` and other impls define a main class.

```
@EnableDataFlowServer
public class LocalDataFlowServer {}
```

I made an attempt to create `DataFlowServerAutoConfiguration` to automate this:

```
@Configuration
@EnableDataFlowServer
public class DataFlowServerAutoConfiguration {
}
```

This them blows up because `DataFlowServerConfiguration` has:

```
@EnableAutoConfiguration(exclude=SessionAutoConfiguration.class)
```

And we get error:
```
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: A circular @Import has been detected: Illegal attempt by @Configuration class 'DataFlowServerConfiguration' to import class 'DataFlowServerAutoConfiguration' as 'DataFlowServerAutoConfiguration' is already present in the current import stack [DataFlowServerConfiguration->DataFlowServerConfiguration->DataFlowServerAutoConfiguration->LocalDataFlowServer]
```

Also `SessionAutoConfiguration` is not compatible for something else we do in a dataflow(there's some weird MBean error). Culprint is that auto-config class should not have `@EnableAutoConfiguration` in its import stack. Without fixing issues with `SessionAutoConfiguration` we can't have a simple app with `@SpringBootApplication`

**Comment by alokkulkarni** [comment]
Hi @jvalkeal  , please can you let us know the version been used for spring dataflow server

**Comment by ilayaperumalg** [comment]
It looks like this is the result of this [change](https://github.com/spring-cloud/spring-cloud-dataflow/commit/dc604f9da42bb3ba7b40240928ee40d6271972a0#diff-72ac1acbab19e2e5bf7ce68c82b6b503R71)

**Comment by jvalkeal** [comment]
Think we need to take `@EnableAutoConfiguration` out in favour of doing a real auto-config thus allowing user to create a real boot app. Library should not force feed auto-config.
