### ISSUE TITLE
Bring back docbook-based Maven tool-chain

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1027]
As a developer, I'd like to add the dockbook-based maven tool-chain, so we could support multi-page documentation format. We would have to undo what was addressed via: https://github.com/spring-cloud/spring-cloud-dataflow/pull/1009.

**Acceptance:**
- `/html` and `/htmlsingle` doc variants are available
- `/html` includes "multi-page" doc format
- `/htmlsingle` includes "single-page" doc format with TOC on the left pane

**Comment by ghillert** [comment]
Hopefully we can revisit that once the following Asciidoctor issue has been resolved: https://github.com/asciidoctor/asciidoctor/issues/626
