### ISSUE TITLE
Create documentation on using EnableDataFlowServer from Spring Initializr

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1040]
As a user I would like to have some documentation on how to have a custom `Data Flow Server` using `@EnableDataFlowServer`.

**Comment by sabbyanandan** [comment]
There have been a lot of discussion on this topic and the plans have been dropped. SCDF being a full-blown "server" similar to Zipkin and others, it doesn't fit the starter model like rest of the ecosystem hosted in Spring Initializr. 

To get started with SCDF, one can use [docker-compose](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-local/docker-compose.yml), [pcf-tile](https://network.pivotal.io/products/p-dataflow), or the [helm-chart](https://hub.kubeapps.com/charts/incubator/spring-cloud-data-flow) in the respective platforms.
