### ISSUE TITLE
Documentation: reference guide renders under ToC

### ISSUE THREAD

**Issue by simonbasle** [spring-cloud/spring-cloud-dataflow#1044]
At least in chrome, apparently not in Firefox. The body of the [reference guide](http://docs.spring.io/spring-cloud-dataflow/docs/1.1.0.RELEASE/reference/htmlsingle/#dataflow-documentation-about) appears partly underneath the ToC on the left:

![image](https://cloud.githubusercontent.com/assets/6986166/20702253/551146f2-b617-11e6-9b1a-6ff509cee1de.png)

**Comment by donovanmuller** [comment]
It seems to be a sizing issue. On larger resolutions it doesn't overlap:

![screen shot 2016-11-29 at 12 37 20 pm](https://cloud.githubusercontent.com/assets/1175891/20706591/b8956938-b630-11e6-9365-8e9aed19f66d.png)

---

![screen shot 2016-11-29 at 12 37 00 pm](https://cloud.githubusercontent.com/assets/1175891/20706592/b8cbf64c-b630-11e6-83b7-47de85a12dd3.png)

**Comment by sabbyanandan** [comment]
It does seem to be an issue with smaller resolution. It could be because of the wider images - we will investigate. Thanks for reporting!

**Comment by ericbottard** [comment]
I believe this is caused somehow by the searchbar our apache adds. The problem doesn't exist when rendering files directly from disk

**Comment by ghillert** [comment]
Yes, this was caused by the auto-injected search-bar. It was disabled, fixing the layout issue.
