### ISSUE TITLE
Provide and Document Cors Support

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#1048]
In _Spring XD_, users were able to configure Cross-origin resource sharing (CORS). This is currently not implemented in SCDF. This will be useful for instances where users use the REST API from 3rd party applications.

Relevant Spring XD documentation:

http://docs.spring.io/spring-xd/docs/1.3.1.RELEASE/reference/html/#_cross_origin_resource_sharing_cors

Also keep in mind that you may have to set the CORS config for the Spring Boot management endpoints:

```
endpoints:
  cors:
    allowed-origins:
      - "*"
```

**Comment by sabbyanandan** [comment]
This has been open for a while, and it hasn't been a pressing problem for the general users. We can revisit it if there are specific cors related requirements.
