### ISSUE TITLE
Add validation and configuration for supported resource types for registered apps

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1049]
Different server implementations support different types of resources, some support Maven and some only support Docker resources. We should have a way to configure the server with supported types and validate when resources are registered. That way we could provide an error when someone registers an unsupported resource type.

https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/issues/157

**Comment by markfisher** [comment]
Maybe we can just add a `supportsScheme(String scheme)` method to the `DelegatingResourceLoader`.

One thought on this though... we can validate the "type", but it's still completely possible that a user registers a bogus URI. We probably cannot eagerly validate anything more than the scheme, unless we want to provide a boolean flag for eager validation.

**Comment by sabbyanandan** [comment]
The core validation routines are applied via https://github.com/spring-cloud/spring-cloud-dataflow/issues/2345 and friends. They include for both maven and docker resource types.
