### ISSUE TITLE
Deployers asked for the Task status, only receive the first Task Id of multiple launches

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-dataflow#1051]
Using 1.1.0.RELEASE.

Following the reference guide, if you [launch](http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/index.html#_launching_a_task) `mytask` more than once and (using the Shell for example) list tasks with:

```
dataflow:>task launch mytask
Launched task 'mytask'
dataflow:>task launch mytask
Launched task 'mytask'
...
dataflow:>task list
╔═════════╤═════════════════════════╤═══════════╗
║Task Name│     Task Definition     │Task Status║
╠═════════╪═════════════════════════╪═══════════╣
║mytask   │timestamp --format="yyyy"│complete   ║
╚═════════╧═════════════════════════╧═══════════╝
```

the underlying deployer implementation only get's the *first* task Id passed to [`TaskStatus status(String id)`](https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/task/TaskLauncher.java#L72).

This could be misleading as tasks executed, using the same task definition, after the first run might have failed etc.

Issue originates in [`TaskDefinitionController`](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskDefinitionController.java) where based on the task's key a task Id is looked up with `TaskDefinitionController.this.deploymentIdRepository.findOne(key)`. This basically does a `select * from` and is non deterministic based on DB used, hence an arbitrary`id` returned.

Should the desired outcome be similar to how apps statuses in a stream are [calculated](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java#L274) for overall stream status? I.e. iterate over all task Ids for that task definition, getting the status of each run and then aggregating for overall status. See [`calculateStreamState`](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java#L274) and [`aggregateState`](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java#L298).

**Comment by cppwfs** [comment]
First off thanks for the issue!
I think the bigger question is, "Do we need a task status here in the first place?"  In that each a task execution is discreet and has a specific state of success or failure upon completion.  Versus a stream where the aggregation of all the apps' states of determines the state.   My vote is to remove this column because one failed task execution among X execution would cause the status to change to something like `partially failed` while correct doesn't really tell us anything.    The users should use `task execution list` to check the state of a specific task execution.

**Comment by donovanmuller** [comment]
Agreed! I'm happy to rip it out (PR) if everyone agrees 😄

**Comment by sabbyanandan** [comment]
This may have been already addressed, but let's review this on the 2.x foundation.

**Comment by sabbyanandan** [comment]
The status associated with a Task represents the status of the last execution. It is not an aggregate of all the executions that were ever run.
