### ISSUE TITLE
Create 1.1.x branch

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1058]
As a developer, I'd like to create a 1.1.x branch, so we could make the `master` default to 1.2.0 feature capabilities.

**Comment by markpollack** [comment]
only after these doc issues for 1.1.1.RELEASE are done (to avoid packporting and forgetting....)

**Comment by ilayaperumalg** [comment]
What version of `deployer` does `1.2.0` version of data flow server would depend on? Should we create `1.2.0.BUILD-SNAPSHOT` version for `spring-cloud-deployer` too?

**Comment by trisberg** [comment]
I think deployer is independent of this proeject's version, but at some point we'll most likely switch to use 1.2.0 of the deployer project
