### ISSUE TITLE
AppRegistry bean should not expect *Delegating*ResourceLoader

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow#1064]
In https://github.com/spring-cloud/spring-cloud-dataflow/blob/60bb7939d53231a3d18a94b40c9dca4d3dad4aae/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java#L102

`ResourceLoader` alone is sufficient. This prevents decoration of the `ResourceLoader`

**Comment by markfisher** [comment]
The problem is it does need some way to distinguish so that it picks up the `ResourceLoader` we've configured for it as opposed to the default `ResourceLoader` used by the application context itself. An alternative might be adding a `@Qualifier` to the bean we create.

**Comment by ericbottard** [comment]
Ah, good point. I thought we replaced the `ResourceLoader` of the app context

**Comment by sabbyanandan** [comment]
The `DataFlowControllerAutoConfiguration` and the `AppRegistry` instantiation have evolved significantly in the recent releases. This is not applicable anymore.
