### ISSUE TITLE
Provide Better Exception Handling When Registering Apps

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#1071]
Currently, several issues exist around the 2 App Registration REST endpoints:

**POST /apps/**

it is possible to trigger `500` Http statuses by using malformed request parameters when `POST`ing to the `/apps` endpoint using `uri` request parameter with a value of e.g. `???`, causing a:

```
org.springframework.cloud.deployer.resource.support.ResourceNotResolvedException: a scheme (prefix) is required
	at org.springframework.cloud.deployer.resource.support.DelegatingResourceLoader.getResource(DelegatingResourceLoader.java:140)
	at org.springframework.cloud.deploy
...
```

We should do proper validation of the passed-in parameter values and return appropriate Http status values, e.g. `Bad Request` instead of a `500` error.

**POST /apps/**

**QUESTION**: The `uri` and `apps`request parameters, while optional, should they be **mutually exclusive**? Currently, both parameters can be provided at the same time, which may seem awkward.

**POST /apps/ with the `apps` parameter**

We should do proper validation on the `apps` parameter. Each property key needs to be prefixed with the `ApplicationType`. Currently that is not validated.

**DELETE /apps/{type}/{name}**

Deleting a non-existing application results in NO ERROR. If the app does not exist, we should probably return a `404` Http status code.

**Comment by ericbottard** [comment]
> *POST /apps/task/taskname*
>
>The uri request parameter is mandatory. Failure to provide the correct parameter should not result in a 500 Http status code. We should return 400 Bad Request instead.

That first case is handled via https://github.com/spring-cloud/spring-cloud-dataflow/pull/1083

**Comment by ilayaperumalg** [comment]
@ghillert Verified the REST endpoints for `/apps` for the above cases you mentioned. 

Except `apps` parameter inputs, everything else look good with the recent changes on AppRegistry controller. For the `/apps` parameter input we don't seem to have the support from `Shell` command yet. Created https://github.com/spring-cloud/spring-cloud-dataflow/issues/1404 for this.

Closing this PR as we can track the `apps` related changes via #1404
