### ISSUE TITLE
REST JobInstanceController vs JobExecutionController 404 inconsistency

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#1074]
Some minor inconsistency - 

* GET `/jobs/instances?name=job-does-not-exist` returns an empty collection with HTTP status code `200`
* GET `/jobs/executions?name=job-does-not-exist` returns with HTTP status `404`

Name is a **mandatory** parameter. 

**What behavior should we standardize on in case the respective job does not exist?**

**Comment by ghillert** [comment]
Somewhat related - e.g. GET `/jobs/instances/123` returns a `404` if the instance does not exist.

**Comment by ilayaperumalg** [comment]
I think returning `404` for the non existent job would make this consistent across.
