### ISSUE TITLE
RuntimeAppsController - AppStatus Never Null

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#1077]
When invoking:
- **GET** `/runtime/apps/123/instances`  (`RuntimeAppsController.AppInstanceController#list()`)
- **GET** `/runtime/apps/123/instances/123` (`RuntimeAppsController.AppInstanceController#display()`)
- **GET** `/runtime/apps/123` (`RuntimeAppsController#display()`)

the controller handles a _NULL_ `AppStatus` but the `AppStatus` will never be _NULL_. In case of a non-existing application, an `AppStatus` with `DeploymentState.unknown` is returned.  

Therefore, for a non-existing application, a HTTP status of `200` is returned. **Wouldn't a status of `404` the more appropriate status?** The code section:

```java
throw new ResourceNotFoundException();
```
seems to never be executed and would in fact return a `404` HTTP status.

For `/runtime/apps/123/instances/456` the `ResourceNotFoundException` is actually triggered but not handled correctly - resulting in a `500` Http status to be returned.

**Comment by ilayaperumalg** [comment]
We could possibly throw `ResourceNotFoundException` for the DeploymentState `unknown`. Something like this:

```
if (status.getState().equals(DeploymentState.unknown)) {
				throw new ResourceNotFoundException();
}
else {
	AppInstanceStatus appInstanceStatus = status.getInstances().get(instanceId);
	if (appInstanceStatus == null) {
		throw new ResourceNotFoundException();
	}
	return new InstanceAssembler(status).toResource(appInstanceStatus);
}
```
