### ISSUE TITLE
Add support in shell to skip SSL validation

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1081]
As a user, I'd like to disable SSL cert validation when connecting to the server running in a cloud environment such as Cloud Foundry, where it is possible to have the DEV PCF instance deployed with self-signed certificates. 

This option would be similar to what we have in CF CLI (_i.e: `cf login ..... --skip-ssl-validation`_), but for SCDF shell.

**Acceptance:**
- SSL validation is enabled by default
- a new flag (eg: `skip-ssl-validation` ?) can be used to disable the validation on demand
- docs updated

**Comment by trisberg** [comment]
I think the additional concerns are handled in https://github.com/spring-cloud/spring-cloud-dataflow/issues/1114
