### ISSUE TITLE
Passing properties for undeploying a stream

### ISSUE THREAD

**Issue by frosenberg** [spring-cloud/spring-cloud-dataflow#110]
**Background**: I'm writing a Kubernetes deployer. One of the concepts of Kubernetes are namespace (logical separation of the cluster). This can be helpful to model various "organizations" on a cluster. 

Now, I want to leverage and deploy streams into different namespace. Deployment properties come in handy here. 

```
dataflow:>stream create --name deployment1 --definition "http --server.port=9999 | log"
Created new stream 'deployment1'
dataflow:>stream deploy --name deployment1 --properties "module.*.namespace=myorg"
Deployed stream 'deployment1'
```

This will now be deployed on Kubernetes in namespace `myorg`. When I'm trying to undeploy though, this information is lost because if have no way of defining extra properties on undeploy. 

What is the best way to deal with this? The idea I head was to enable the deployer SPI to add an extra bag of metadata to the `ModuleDeploymentId` that is returned in the `deploy(..)` function. Currently this return value is ignored in the admin but I think it should be persisted. This way I could return an instance of the `ModuleDeploymentId` as follows: 

```
@Override
public ModuleDeploymentId deploy(ModuleDeploymentRequest request) {
			
  ModuleDeploymentId id = new ModuleDeploymentId.fromModuleDefinition(request.getDefinition()); 

  // do my deploy to Kubernetes into the right namespace

  id.addMetadataProperty("namespace", request.getDeploymentProperties().get("namespace"));

  return id;
}		
```

Then later in the undeploy:
```
@Override
public void undeploy(ModuleDeploymentId id) {
  logger.info("Undeploying module: {}", id);

  // undeploy in kubernetes
  kubeClient.replicationControllers().
    inNamespace(id.getMetadataProperty("namespace"))
    withName(id.toString()).delete();	
  // ...
}
```
Or maybe the deployment properties should be persisted as part of the `StreamDefinition` class directly in the `StreamController` in the admin? Or a separate repository implementation for the Kubernetes deployer only.

Does this make sense? Any suggestions? I can submit a PR for this if desired and useful.

**Comment by ericbottard** [comment]
Hi Florian,

first of all thanks for your interest in Spring Cloud Stream/DataFlow!

I'm not familiar enough with Kubernetes, but for other deployers which do support a similar concept of namespace ([CloudFoundry](https://github.com/spring-cloud/spring-cloud-dataflow/blob/392bc95f4791ce4234e1228f98ce98f043fbbd6d/spring-cloud-dataflow-module-deployers/spring-cloud-dataflow-module-deployer-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/module/deployer/cloudfoundry/CloudFoundryModuleDeployerProperties.java#L45-L48) is a good example), this is typically not overridable on a per-deployment basis (at least for now).

It is expected that if users share a cluster/install, if they use s-c-s/s-c-d then they'd configure their deployer with their respective namespace/org. And hence have several s-c-d admin installations if they use several namespaces/orgs. You'll also want to make sure that the names/ids you come up with in your deployer implementation are segregated per namespace in kubernetes (this most certainly comes "for free" from that concept of namespace, again I'd have to look in detail to it). That is, two users using two distinct namespaces should be able to deploy a stream named "foo" made of "time | log" without interfering one with the other.

I wanted to have a look at implementing a kubernetes deployer, so I'm really glad you're interested in this. Don't hesitate to reach back to us, especially if you think my answer does not make sense.

**Comment by frosenberg** [comment]
Thanks @ericbottard 

I can definitely go with one Admin/Deployer instance per organization/namespace. That will definitely work without worrying about the namespace in the deployer. This is what I currently have. 

A shared Admin for more than one organization won't be doable with this though. I would argue to add capabilities to the deployer SPI to pass in "undeployment" properties. This would make such scenarios quite easy to implement.

**Comment by sabbyanandan** [comment]
The deploy() operation returns an ID and that is now used to undeploy() a stream, so this issue is not relevant anymore.
