### ISSUE TITLE
SCDF Dashboard Bulk Import Application Update Links

### ISSUE THREAD

**Issue by lseinc** [spring-cloud/spring-cloud-dataflow#1102]
When performing a bulk import of streams or tasks using the dashboard, it references older versions of the app streams, processes and tasks instead of using the same found in the documentation.  As an example, I am currently seeing off 1.1.1.BUILD-SNAPSHOT the use of http://bit.ly/1-0-2-GA-stream-applications-rabbit-maven and  http://bit.ly/1-0-1-GA-task-applications-maven .  Assuming the documentation is more current than the dashboard at this time, the dashboard should be using https://bit.ly/Avogadro-GA-stream-applications-rabbit-maven and https://bit.ly/Addison-GA-task-applications-maven .  As part of this change, perhaps there may need to be an automated process created to keep both documentation and dashboard in sync.

**Comment by sabbyanandan** [comment]
@lseinc: Thanks for reporting. We are addressing the core problem in SCDF-UI project via https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/146 -  we will account for dynamic inclusion of bit.ly versions going forward.

**Comment by lseinc** [comment]
Thanks !
