### ISSUE TITLE
SCDF app import fails when using redirect

### ISSUE THREAD

**Issue by lseinc** [spring-cloud/spring-cloud-dataflow#1103]
Using scdf shell and server local dashboard latest 1.1.1.BUILD-SNAPSHOT today, when importing streams using 
app import --uri https://bit.ly/Avogadro-GA-stream-applications-rabbit-maven
an errors happens and no apps are registered.
Same thing happens when trying to import via URL in dashboard.  

Example:
dataflow:>app import --uri https://bit.ly/Avogadro-GA-stream-applications-rabbit-maven
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: 1

However, taking the location of the redirect in the bit.ly link, the following works:
dataflow:>app import --uri http://repo.spring.io/libs-release-local/org/springframework/cloud/stream/app/spring-cloud-stream-app-descriptor/Avogadro.RELEASE/spring-cloud-stream-app-descriptor-Avogadro.RELEASE.stream-apps-rabbit-maven
Successfully registered 0 applications from [sink.task-launcher-yarn, source.tcp, sink.jdbc, source.http, sink.rabbit, source.rabbit, source.ftp, sink.gpfdist, processor.transform, source.loggregator, source.sftp, processor.filter, source.file, sink.cassandra, processor.groovy-filter, sink.router, source.trigger, sink.hdfs-dataset, processor.splitter, source.load-generator, sink.sftp, sink.file, processor.tcp-client, sink.tasklaunchrequest-transform, source.time, source.gemfire, source.twitterstream, sink.tcp, source.jdbc, sink.field-value-counter, sink.redis-pubsub, sink.hdfs, sink.task-launcher-local, processor.bridge, processor.pmml, processor.httpclient, sink.ftp, source.s3, sink.log, sink.gemfire, sink.aggregate-counter, sink.throughput, source.triggertask, sink.s3, source.gemfire-cq, source.jms, source.tcp-client, processor.scriptable-transform, sink.counter, sink.websocket, source.mongodb, source.mail, processor.groovy-transform, source.syslog]

Also, the count for successfully registered is 0 and the app list shows all of them registered.

Attached is the stack trace from the exception on the scdf server local.  
[exception.txt](https://github.com/spring-cloud/spring-cloud-dataflow/files/691215/exception.txt)

Here are the first several lines:

2017-01-06 21:46:13.783 ERROR 58676 --- [nio-9393-exec-1] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

java.lang.ArrayIndexOutOfBoundsException: 1
	at org.springframework.cloud.dataflow.registry.AppRegistry.createAppRegistration(AppRegistry.java:108) ~[spring-cloud-dataflow-registry-1.1.1.BUILD-SNAPSHOT.jar!/:1.1.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.registry.AppRegistry.importAll(AppRegistry.java:81) ~[spring-cloud-dataflow-registry-1.1.1.BUILD-SNAPSHOT.jar!/:1.1.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.controller.AppRegistryController.registerAll(AppRegistryController.java:177) ~[spring-cloud-dataflow-server-core-1.1.1.BUILD-SNAPSHOT.jar!/:1.1.1.BUILD-SNAPSHOT]

In the future (new card/issue?) consider adding the git commit id in the MANIFEST Implementation Version to get some additional information as to what BUILD-SNAPSHOT source generated the jar.  This jar was created around "Fri Jan 06 22:25:31 UTC 2017" based on the pom.properties file in the META-INF directory.

**Comment by trisberg** [comment]
Seems to be related to the use of "https://" for the bit.ly link. Using plain "http://" it works fine - `app import --uri http://bit.ly/Avogadro-GA-stream-applications-rabbit-maven`

**Comment by sabbyanandan** [comment]
Per @ericbottard on the slack conversation earlier this week. 

> By design, URLConnection doesn’t follow redirects from https to http (or vice versa), as this has security implications

We would still have to handle the exception regardless.

**Comment by trisberg** [comment]
We end up with this garbage in the properties file for registering apps:

```
<html>
<head><title>Bitly</title></head>
<body><a href="http://repo.spring.io/libs-release-local/org/springframework/cloud/stream/app/spring-cloud-stream-app-descriptor/Avogadro.RELEASE/spring-cloud-stream-app-descriptor-Avogadro.RELEASE.stream-apps-rabbit-maven">moved here</a></body>
```

**Comment by trisberg** [comment]
This is related to a spring-cloud-deployer issue https://github.com/spring-cloud/spring-cloud-deployer/issues/176

**Comment by markpollack** [comment]
Additional improvements in  6d58b157190f7750eeaf104ed872aa9bf1adde07

**Comment by lseinc** [comment]
Thanks everyone !
