### ISSUE TITLE
Shell - provide interactive login support

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#1106]
Instead of providing the login credentials via the command-line parameters:

* `--dataflow.username=bob`
* `--dataflow.password=bobspassword`

it would be nice if the shell automatically detected whether security is enabled (possible via the `security/info` REST endpoint), and if so, to prompt the user for credentials. That would provide a better user experience.

depends on https://github.com/spring-cloud/spring-cloud-dataflow/issues/810

**Comment by sabbyanandan** [comment]
This is now supported in v2.0; esp. when security is enabled.
