### ISSUE TITLE
Create generic shell/dsl infrastructure in spring-cloud-dashboard

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1122]
As a developer, I'd like to create the core Shell/DSL infrastructure in [`spring-cloud-dashboard`](https://github.com/spring-cloud/spring-cloud-dashboard) project, so that I can generalize it even further to support features such as "application groups."

Note: For more background on this split and the new project, please review the "application groups" [design proposal](https://docs.google.com/document/d/1-zN2j6dBD3HTzvowL7XceiNvDVm1Rk8mK84N3lJH2RI/edit?usp=sharing). 

**Acceptance:**
- Core shell/dsl infrastructure responsible for app and task orchestration moved to `spring-cloud-dashboard`
- Associated test infrastructure moved to `spring-cloud-dashboard`
- `spring-cloud-dashboard` turns into a dependency in SCDF 
- Core SCDF tests pass successfully after the split and new dependency inclusion

**Comment by hekonsek** [comment]
Do you have any estimates on when this feature is gonna be delivered?

**Comment by sabbyanandan** [comment]
We have taken a different approach to supporting "app-grouping" workflows in SCDF. [Spring Cloud Skipper](http://cloud.spring.io/spring-cloud-skipper/) will support the app-lifecycle primitives, and SCDF will use it as a companion server to accommodate "app-grouping" workflows. 

Skipper + SCDF integration can be tracked via `skipper-integration` label.
