### ISSUE TITLE
Fix RDBMSRegistry to handle IllegalArgumentException on find()

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1126]
Based on this https://github.com/spring-cloud/spring-cloud-deployer/issues/176, we need to fix the RDBMS registry find(key) method to throw `IllegalArgumentException` when there is no app found by the key

**Comment by cppwfs** [comment]
https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/RdbmsUriRegistry.java#L91  Needs to be able to handle the illegal argument exception.  Currently only checks for null.

**Comment by trisberg** [comment]
Or we should change the SPI since it doesn't allow for throwing an IllegalArgumentException when the search is passed an invalid app name.
