### ISSUE TITLE
spring cloud dataflow app http returns 401 unauthorized

### ISSUE THREAD

**Issue by cinqs** [spring-cloud/spring-cloud-dataflow#1130]
I am testing scdf with iris PA example which deployed "http | pmml | log" example

But when I post a request to the server, I always got:

    401 Unauthorized

like these:

```json
{
  "timestamp": 1484718462061,
  "status": 401,
  "error": "Unauthorized",
  "message": "Full authentication is required to access this resource",
  "path": "/"
}
```

when I added application.properties file with this configuration:

    security.basic.enabled=false

to the folder same with the local server jar file, it seemed not working...

I still saw the default password been set in the console:

    using default security password: ****-****....

Then I used the Basic Auth with username user and password ****-***

it gave:

```json
{
  "timestamp": 1484718712952,
  "status": 401,
  "error": "Unauthorized",
  "message": "Bad credentials",
  "path": "/"
}
```

Infos:

    plateform: docker-toolbox
    OS: debian:jessie
    SCDF version: 1.1.1.RELEASE

**Comment by sabbyanandan** [comment]
Hi, @cinqs: We have had to recently address the default security experience for `http-source` application. See this [commit](https://github.com/spring-cloud/spring-cloud-stream-app-maven-plugin/commit/f904ae8697848d6d5f2d002932370287d8e84b42) for more details. With this commit, only the `/management` endpoint needs security for `http-source` application. 

There has been a new release of `http-source` and you can download the latest [kafka-binder-variant](http://repo.spring.io/libs-release/org/springframework/cloud/stream/app/http-source-kafka-10/1.1.2.RELEASE/) of the release from Spring repo. Other binder variants can be downloaded from [here](http://repo.spring.io/libs-release/org/springframework/cloud/stream/app/). 

Please try it out and let us know if you have any other feedback.

**Comment by cinqs** [comment]
Yes, I checked the new version `1.1.2.RELEASE`. The unauthorized problem is solved.

But the `pmml processor` seems not be able to get `payload` from `http`

But this problem is solved, obviously

Thanks @sabbyanandan

**Comment by sabbyanandan** [comment]
@cinqs: The issue with `pmml-processor` is now addressed via: https://github.com/spring-cloud/spring-cloud-stream/commit/60862d25e247e99240b788a96786a78ca71b046b. You can download the latest SNAPSHOT of the pmml-processor from [http://repo.spring.io/libs-snapshot/org/springframework/cloud/stream/app/](http://repo.spring.io/libs-snapshot/org/springframework/cloud/stream/app/.). All the binder variants should be there for download.
