### ISSUE TITLE
DeploymentIdRepository usage in Task apps

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1134]
Based on the discussion [here](https://github.com/spring-cloud/spring-cloud-dataflow/pull/1132#discussion_r97289396), the task apps wouldn't need `DeploymentIdRepository` anymore. 

We need to cleanup code wherever `DeploymentIdRepository` is used for task apps.

**Comment by cppwfs** [comment]
Related issue: https://github.com/spring-cloud/spring-cloud-dataflow/issues/1051

**Comment by ilayaperumalg** [comment]
This is no longer valid as the `DeploymentIdRepository` was removed as part of https://github.com/spring-cloud/spring-cloud-dataflow/commit/23352835164eb710802a20e7738e8776ec15198d
