### ISSUE TITLE
Create maven plugin to create metadata artifact

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow#1135]
Creating this issue in SCDF core for now, even though the plugin may end up in a separate repo.

This maven plugin should gather the `/META-INF/spring-configuration-metadata.json` files from all deps of a project and gather them in a simple jar (either merging all the files in one, or stuffing them inside a dir from their original filename -- to be decided)

**Comment by ericbottard** [comment]
Repo is here: https://github.com/ericbottard/spring-cloud-app-starter-metadata-maven-plugin

**Comment by sabbyanandan** [comment]
This is now merged.
