### ISSUE TITLE
Starters / Spring Initializr support for non-local servers

### ISSUE THREAD

**Issue by sworisbreathing** [spring-cloud/spring-cloud-dataflow#1139]
[The documentation](http://docs.spring.io/spring-cloud-dataflow/docs/1.1.2.RELEASE/reference/htmlsingle/#_spring_boot_admin) for adding the [Spring Boot Admin Client](https://codecentric.github.io/spring-boot-admin/1.4.3/#register-clients-via-spring-boot-admin) library to the server instructs users to use Spring Initializr.

Currently, this only supports the local server implementation, and it is not possible to follow this approach for other server implementations (e.g. cloudfoundry or kubernetes).

Proposed user story: As a user of Spring Cloud Dataflow, I want the procedures for enabling additional functionality in the dataflow server to be consistent, regardless of which cloud provider I am using.

**Comment by sabbyanandan** [comment]
Hi, @sworisbreathing. Thanks for the feedback. 

Today, Spring Initializr includes _just_ the local-server. Given the differences in project dependency ordering when downloaded from Initializr, the final artifact is not consistent with what we deliver in our (uber-jar) releases. We are discussing options to have other implementations, though.

In the meantime, 

1) Download the compatible Boot application 
2) Add the runtime specific `autoconfig` dependency (_eg., cloud foundry_)
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-dataflow-server-cloudfoundry-autoconfig</artifactId>
	<version>VERSION</version>
</dependency>
```
3) Add `@EnableDataFlowServer` in the Boot application
```
@SpringBootApplication
@EnableDataFlowServer
public class DataFlowServer {

	public static void main(String[] args) {
		new SpringApplication(DataFlowServer.class).run(args);
	}
}
```
4) Add Spring Boot Admin dependencies
```
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-server</artifactId>
    <version>VERSION</version>
</dependency>
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-server-ui</artifactId>
    <version>VERSION</version>
</dependency>
```

**Comment by sabbyanandan** [comment]
Since we haven't heard back from the reporter, I'll close this for now.
