### ISSUE TITLE
Need to support task compose command for SCDF Shell

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#1142]
User wants the ability to create composed tasks via the SCDF Shell.  
The command should look like :
`task compose baz --definition “your definition”`

**Comment by sabbyanandan** [comment]
This is addressed via: https://github.com/spring-cloud/spring-cloud-dataflow/commit/b91b53836f7eb523163fe083b2c91fae6fe4f07a.
