### ISSUE TITLE
StreamOperations create method should be void

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-dataflow#1146]
StreamOperations currently has a signature to return `StreamDefinitionResource` at https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/StreamOperations.java#L41

The issue is that the server returns void for the create operation, and thus leaving this as  null value that clients using it could end up in NPE

**Comment by ericbottard** [comment]
Same applies to `TaskDefinitionController#save()`. Whatever the decision here, those should be aligned
