### ISSUE TITLE
Add server-side parser for composed task DSL

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1151]
As a user, I'd like to use composed task DSL, so I can use the DSL to build, define and orchestrate a collection of tasks defined as a DAG. 

**Acceptance:**
- DSL supplied to the composed task parser deciphers the DAG and its components for runtime orchestration
- Parser resides in the same package as the existing stream/task 
- Unit tests included

**Comment by aclement** [comment]
PR submitted: https://github.com/spring-cloud/spring-cloud-dataflow/pull/1194

Feel free to provide feedback. I've gone code blind and can't read it anymore :) I continue to be a little concerned with the complexity of the graphs users might have to work with in a UI, given the abilities the DSL enables.
