### ISSUE TITLE
Improve status messages from "stream list"

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow#1153]
We're currently displaying the raw AppDeploymentStatus enum in the shell when doing stream list / runtime apps.
This is worrisome now that we're returning `error` from some implementations. `error` means that we couldn't compute the status, **NOT** that the app is in error (that is `failed`).

We should map those codes to something more user friendly

**Comment by trisberg** [comment]
Not able to cherry-pick this commit to master branch: https://github.com/spring-cloud/spring-cloud-dataflow/commit/97bfd2ed7c29d6840d734985b02865e0217014d8

Seems there are some other changes made in the RuntimeAppsController that conflict with these changes. The tests fail after I apply the cherry-picked commit.

We need to create a separate PR for these changes and apply them to the master branch.

**Comment by trisberg** [comment]
Create new issue for master branch PR - 1174
