### ISSUE TITLE
Consider renaming `spring-configuration-metadata-whitelist.properties`

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-dataflow#1157]
As far as I can see, the whitelisting process of configuration properties is a Spring Cloud Dataflow concept (shell only?). 

IMO, that doesn't deserve a such a generic name (and can be confused with a lower-level feature, i.e. Spring Boot related). If it's shell specific, the name should probably say that.

child of #914.

**Comment by sabbyanandan** [comment]
Hi, @snicoll. Though this is specific to SCDF, we leverage this in SCDF's shell, dashboard, and Flo widgets. If you think it can _still_ be confused with something in Boot proper, we could revisit the naming.

**Comment by snicoll** [comment]
It really is. `META-INF/` is really a generic location and the current name implies it is a companion of `spring-boot-configuration-metadata` (and it isn't).

Thanks!

**Comment by snicoll** [comment]
@sabbyanandan any feedback about this improvement? It's been in the "next iteration" bucket for more than 3 months now.

**Comment by sabbyanandan** [comment]
Hi, @snicoll! This feature was introduced in 1.1 and I wanted to avoid this breaking change in 1.x/1.2 release line. We will revisit this in 2.0 M1.

**Comment by snicoll** [comment]
The longer the use of a file named `spring-configuration-metadata-whitelist.properties` is encouraged, the bigger the problem becomes. While I can understand the desire not to make a breaking change, I don’t think that means that doing nothing till 2.0 is the best we can do.

I’d like to see `spring-configuration-metadata-whitelist.properties` being deprecated as soon as possible in 1.x, with a better-named replacement being introduced alongside. The documentation can then be updated to recommend the use of the new file name, thereby limiting the size of the problem and also giving people plenty of time to migrate to the new name before the breaking change is made in 2.0 M1.

**Comment by sabbyanandan** [comment]
We are barely coming out of 1.2 and the change, if we were to do it, is not only in SCDF core, but it has to go in all the [stream](https://github.com/spring-cloud-stream-app-starters/) and [task](https://github.com/spring-cloud-task-app-starters) app-starters (~70 apps). Then the rabbit/kafka-binder specific app generation machinery needs to adapt to it as well. 

That said, your feedback is spot on; we will review this truly this time in the next iteration when we begin 2.0 work. 

cc:/ @markfisher @markpollack
