### ISSUE TITLE
Experiment split, move, and generalization of app and task orchestration

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1159]
In continuing the efforts to add app-grouping support in SCDF, we would like to experiment different generalization strategies. This is a prerequisite to formalize spring-cloud/spring-cloud-dataflow#1122 and spring-cloud/spring-cloud-dataflow#1123.

**Comment by jvalkeal** [comment]
I now have a base model to registe and launch boot apps without using hardcoded application types. Closing this spike as done.
