### ISSUE TITLE
Controll number of simultanous Tasks lunched using LocalTaskLauncher

### ISSUE THREAD

**Issue by shahbour** [spring-cloud/spring-cloud-dataflow#1162]
I am lunching tasks using spring-cloud-deployer-local but i would like to have a feature that can control how many simultaneous tasks can run together , kind of queue or taskExecutor .

I found that [LocalTaskLancher](https://github.com/spring-cloud/spring-cloud-deployer-local/blob/7a5449b12ed07ec2b54c2a517b5e1610d883ba33/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalTaskLauncher.java) is responsible for the lunching but nothing about queue or checking how many app is active

[stackoverflow](http://stackoverflow.com/questions/41912884/control-spring-cloud-task-luncher)
[spring-cloud-task](https://github.com/spring-cloud/spring-cloud-task/issues/275)

**Comment by sabbyanandan** [comment]
This feature was discussed in https://github.com/spring-cloud/spring-cloud-deployer-local/pull/18. We do not intend to support local-server for production deployments, so closing this as invalid.
