### ISSUE TITLE
Review and standardize checkstyle rules

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1167]
As a developer, I'd like to review and standardize checkstyle rules, so that I can apply the rules across all the SCDF ecosystem of projects for consistency.

**Acceptance:**
Categorize the current rules in the context of noise vs. usefulness. For example, any deprecated use of APIs should fail the build.

**Comment by markpollack** [comment]
There is a PR but out of date, so should not be merged for 1.2 RC.  (it has outdated files for one thing).   I believe we were going to do this house keeping either after 1.2 RC or after 1.2 GA.

**Comment by ilayaperumalg** [comment]
We need to discuss on the timeline to merge that PR (given the fact that the checkstyle changes require everyone to up-to-date with the IDE settings to conform to the style config changes). 

In any case, the PR is up to date now (rebased again with the fixes required for the recently changed files).
