### ISSUE TITLE
Port to master: Improve status messages from "stream list" #1153

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1174]
Need to create new PR for master branch with changes made for #1153

We are not able to cherry-pick this commit to master branch: 97bfd2e

Seems there are some other changes made in the RuntimeAppsController that conflict with these changes. The tests fail after I apply the cherry-picked commit.

**Comment by ericbottard** [comment]
Merged port as 02280bf4cde2987e2b9228c14e95b89bdb261038, while making the tests pass via 117d51399c1280ae0accef29ab4e8b65a45a4bf9 (also ported to 1.1.x)
