### ISSUE TITLE
Local dev server quickstart throws errors when in console analytics tab - no redis?

### ISSUE THREAD

**Issue by jldec** [spring-cloud/spring-cloud-dataflow#1197]
I followed the instructions in http://cloud.spring.io/spring-cloud-dataflow/#quick-start

(kafka setup was the most hairy - but seems to work if you follow step 1 and 2 on https://kafka.apache.org/quickstart)

Things appear to work (it took a while to figure out that the log to tail is in `/var/folders/tv/cr5r6whx5w923_hq8h0tggxh0000gn/T/spring-cloud-dataflow-76103589497385737/ticktock-1487701600632/ticktock.log/stdout_0.log` on my machine.)

But browsing to the analytics console at http://localhost:9393/dashboard/index.html#/analytics/dashboard causes a bunch of errors that appear to be due to missing redis.

`org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool`

[err.txt](https://github.com/spring-cloud/spring-cloud-dataflow/files/791142/err.txt)

**Comment by donovanmuller** [comment]
As per the reference docs (see [section 15. Feature Toggles](http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#enable-disable-specific-features)), Redis is required for the analytics feature. If you do not have a Redis instance running you can turn the analytics feature off with `spring.cloud.dataflow.features.analytics-enabled=false`, which should take care of the errors.

As for Kafka, the easiest way I've found for testing locally with the Kafka binder is using a [Docker image](https://github.com/wurstmeister/kafka-docker), if Docker is an option.

**Comment by jldec** [comment]
thanks for the info @donovanmuller ! 
(b.t.w i grew up in Johannesburg myself)

**Comment by sabbyanandan** [comment]
@jldec: I made some changes to [quick-start](http://cloud.spring.io/spring-cloud-dataflow/#quick-start) instructions. If something is still not clear, we could further iterate. 

As for Redis, as @donovanmuller pointed out, it is _only_ required when using any of the analytics counters. We could improve the UX by showing a user-friendly message on the Dashboard, though. 

Perhaps: "Spring Cloud Data Flow requires Redis for Analytics. An error occurred connecting to a Redis cluster."

**Comment by jldec** [comment]
Thanks @sabbyanandan  - that looks good - closing the issue.

i do agree that it would nice to do something more graceful in the dashboard if redis (or for that matter Kafka) are not available.
