### ISSUE TITLE
Fix spring-cloud-deployer dependency 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1198]
The 1.1.3.RELEASE of SCDF-core includes a [SNAPSHOT dependency](http://repo.spring.io/libs-release-local/org/springframework/cloud/spring-cloud-dataflow-parent/1.1.3.RELEASE/spring-cloud-dataflow-parent-1.1.3.RELEASE.pom) and it shouldn't. 

```
$ unzip -l spring-cloud-dataflow-server-local-1.1.3.RELEASE.jar |grep SNAP
    27795  2017-02-15 14:55   BOOT-INF/lib/spring-cloud-deployer-local-1.1.4.BUILD-SNAPSHOT.jar
    11691  2017-02-14 16:03   BOOT-INF/lib/spring-cloud-deployer-resource-support-1.1.4.BUILD-SNAPSHOT.jar
```

**Comment by trisberg** [comment]
Fixed via commit https://github.com/spring-cloud/spring-cloud-dataflow/commit/dbb6ffe72972b73bd9975c8ca0d456c2da7fc0e5

Released as 1.1.4
