### ISSUE TITLE
Launching older task versions creates additional row with EXTERNAL_EXECUTION_ID

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1201]
When launching a task that predates the 1.2.0.M1 version of the task-app-starters there are now two entries added to the TASK_EXECUTION table.

```
TASK_EXECUTION_ID  START_TIME           END_TIME             TASK_NAME  EXIT_CODE  EXIT_MESSAGE  ERROR_MESSAGE  LAST_UPDATED         EXTERNAL_EXECUTION_ID                        PARENT_EXECUTION_ID  
-----------------  -------------------  -------------------  ---------  ---------  ------------  -------------  -------------------  -------------------------------------------  -------------------  
1                  (null)               (null)               (null)     (null)     (null)        (null)         2017-02-24 17:22:36  mytime-2316122d-bda2-48c5-a761-6ae606b70b22  (null)               
2                  2017-02-24 17:22:39  2017-02-24 17:22:39  mytime     0          (null)        (null)         2017-02-24 17:22:39  (null)                                       (null)
```

We should avoid this since we don't have much control over what versions of apps are registered.

**Comment by sabbyanandan** [comment]
Based on the recent discussion with @mminella and @trisberg, we will address this by:

1) Add documentation that articulates Task-1.1 -> Task-1.2 schema changes and the task-execution inconsistencies when using Task-1.1 in SCDF 1.2
2) Link to Task-1.1 -> Task-1.2 migration path
3) Filter and don't show task-executions:
  - for rows that include start/end-times, but no "external task execution id" from the shell/ui
  - include a alter/warning message in the shell/ui
4) Sample message:
> Warning: We have discovered Task applications built with an older release of Spring Cloud Task framework. With the recent database schema changes in 1.2 release, we now persist external task execution info, and they don't apply to applications built with older Spring Cloud Task versions. We have filtered such incompatible rows from this page. It'd be advisable to migrate your Task applications to 1.2 and here's the migration guide for your reference.

**Comment by sabbyanandan** [comment]
The decision on this was to add task_name to empty task executions - see [here](https://github.com/spring-cloud/spring-cloud-task/issues/295#issuecomment-290133081). This would at least help us identify how the extra row in the database relates to a task.
