### ISSUE TITLE
Task deployment endpoint is missing

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1203]
As a user, I'm trying to launch the task via Local-server's REST-API and the task deployment fails with a 404. 

```
curl -target http://localhost:9393/tasks/deployments/foo\?arguments\=\&properties\= -H "Content-Type:text/plain"
{"timestamp":"2017-02-27T19:55:01.387Z","status":404,"error":"Not Found","message":"No message available","path":"/tasks/deployments/foo"}%
```

This [commit](https://github.com/spring-cloud/spring-cloud-dataflow/commit/b4c7b6937533d743e772702395ec93463db0a170) removed it - why? I don't have any other option to launch a task outside of SCDF.

**Comment by ericbottard** [comment]
See https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionController.java#L123-L137
