### ISSUE TITLE
Consider pre-fetching the metadata artifacts on register

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow#1214]
The metadata artifacts typically weigh ~50Kb for an OOTB app (compared to ~25Mb for the actual uberjar), but downloading them for the very first time still incurs a small delay which is noticeable when doing tab completion.

We may want to prefetch them on register, if 
1) metadata-uri is set
2) metadata-uri is different from main app uri

**Comment by markfisher** [comment]
This violates the assumption that the artifact need not be available at the time of registration. Could it be optional, based on a boolean flag provided with the `app register` command? (we could support an option for eagerly downloading the uberjar as well). If we do proceed with this as a default behavior, we should at least treat failures as non-fatal (log a warning perhaps).

**Comment by ericbottard** [comment]
Sorry, I should have made this more clear: of course this should be considered optional and any failure should be non fatal.

Pre-fetching the actual jars is
1) problematic as it could DL gigs of data (think CF)
2) not needed until we deploy the app now. So maybe we could do it at stream/task creation time (and obviously this only applies to runtimes that actually upload/need the main app, ie not in the pull model). Long story short: it's a bit more involved than what I consider this issue to be: a quick win ;)

**Comment by markfisher** [comment]
Agreed that downloading the full JAR should be a separate issue (IF we pursue it at all), and perhaps it could be a background operation anyways?

**Comment by ericbottard** [comment]
Yes, in my mind, all of this happens in the background

**Comment by markfisher** [comment]
well, in your mind is one thing... I was talking about the server ;)
