### ISSUE TITLE
Add REST-API to fetch real-time channel metrics

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1225]
As a user, I'd like to visualize real-time channel metrics between the applications in a stream.

**Acceptance:**
- A new API that interacts with the backend to query and retrieve persisted channel metrics
- The API can fetch metrics by a stream name
- The API can fetch metrics for multiple streams in a single call
- Unit test included
- API documented

Sub Tasks:
- [ ] https://github.com/spring-cloud/spring-cloud-dataflow/issues/1260
- [ ] https://github.com/spring-cloud/spring-cloud-dataflow/issues/1261

**Comment by jvalkeal** [comment]
Looks like we should split this work into more smaller bits as we need to create a new abstraction how to import stream metrics into other metric frameworks and then how to query those metrics from there to expose our own dashboard.

Not sure what was a plan for persisting metrics but one thing is sure, we should not try to create our own persistence solution as it is gigantic task and we're not in a business to create solutions of storing and visualising metrics. There's always other who do it better and whole product meant for it. We should leverage existing products like `Grafana`, `Graphite`, `Prometheus`, etc and come up with integrations. 

We had a chat with @markpollack about this at Boston so I think I could try to take a shot at it.
