### ISSUE TITLE
Status information about generated endpoint for the deployed stream

### ISSUE THREAD

**Issue by frosenberg** [spring-cloud/spring-cloud-dataflow#123]
How is the user of the shell supposed to understand where to send messages to and receive them from?

Let's assume I have this stream:

```
stream create --name foobar-extreme-super-long-string --definition "http --server.port=7788 | filter --script=foobar.groovy" | elasticsearch-sink --server.port=8192"
```

(Note: this might not be a correct string but you get the idea ;))

Let's assume now that the deployer is deploying this on the cloud (kubernetes cluster or cloudfoundry). How is the user supposed to know how the send message to the stream and receive them back?

I would assume the following:
For http source: `http://foobar-super-long-string-http.mydomain.org:7788/message`
For ES transport: `foobar-super-long-string-elasticsearch-sink.mydomain.org:8192`

My questions are:
1. How would the user know how "the deployer" deduces the string?
2. Is there a way for the user to query that in the Admin (from a users perspective)? If not, what is the though process on how and where to add that?
3. Let's say some deployers have restrictions on the names. For example, Kubernetes has the concept of a "service" that allows to expose URLs like the ones I show above. However the `foobar-super-long-string-http` needs to conform to RFC 952 DNS label (24 characters, etc). This means if the user passes in a very long stream name, it will fail to deploy it. This gets even worse, if the deployer pre- or postfix the ID with the name of the stream (`group`) and the  `label` as the string may easily exceed 24 char (just assume the module name is very long).

**Comment by ericbottard** [comment]
> 1. How would the user know how "the deployer" deduces the string?

He wouldn't (until he learns how the deployer behaves). He should ...

> 2. Is there a way for the user to query that in the Admin (from a users perspective)? If not, what is the though process on how and where to add that?

... use the `runtime info / runtime module` command (which I am supposed to work on this week). This command gives information about each deployed module instance and surfaces "attributes" about them. In those, there would typically be an attribute about location / NATed address where the module can be reached

> 3. Let's say some deployers have restrictions on the names. 

That's a bummer :( Two options there: keep it that way (forcing the user to reconsider his stream name until it's ok), or use shorter names and rely on the `runtime info` command above. This should be ok for your kubernetes implementation, given how the mapping from module to pod is done via "labels" and does not rely on the name itself.

**Comment by sabbyanandan** [comment]
The design has evolved since the early discussions in this thread. I will close it as "not applicable". For anything k8s specific, let's start a new thread at https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes.
