### ISSUE TITLE
composed-task-runner registered by default

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1230]
When I deploy a server implementation that build on the most recent snapshots of scdf-core I get a new `composed-task-runner` app registered:

```
composed-task-runner	task	maven://org.springframework.cloud.task.app:composedtaskrunner-task:1.0.0.BUILD-SNAPSHOT
```

Not sure why this is, but it certainly will not be useful running with the Kubernetes or Mesos servers.

**Comment by cppwfs** [comment]
The composed-task-runner is used to execute composed tasks for the Spring Cloud Data Flow server. 
The order of steps is a follows: 
1) Create a composed task using the task composed command.  i.e. `task compose --name myComposedTask --graph "AAA && BBB && CCC"
2) `task launch myComposedTask`

The task compose command creates a new task definition like: `composed-task-runner --graph="AAA && BBB && CCC"`

**Comment by trisberg** [comment]
Well, my question was more why do we register this app by default? This app doesn't seem to exists so I get an error trying to get some info - 

```
failed to resolve MavenResource: org.springframework.cloud.task.app:composedtaskrunner-task:jar:1.0.0.BUILD-SNAPSHOT. Configured remote repository: springRepo
```

Also, this maven resource isn't going to work for most server implementations AFAIK.

**Comment by trisberg** [comment]
Also, looks like we have part of the composed functionality already committed, but no way to realistically use this feature yet. Do we want to leave it like this for the M3 release?
