### ISSUE TITLE
/about should be secured

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow#1232]
With security on, the `/about` endpoint should not be freely accessible

**Comment by ghillert** [comment]
The question is - **Are we exposing right now too much information?** Possibly we have to make this endpoint authentication aware. E.g. sending more information to the client IF successfully authenticated for the same endpoint. Some information must be provided without authentication though:

* Security meta-information (Is security enabled, are you logged in etc.)
* Feature information (what features are available for the UI)
* Possibly some basic version information

**Comment by mminella** [comment]
I'd disagree that any of that information should be available outside of being authenticated to a secured application.  All of that list provides information for a potential attacker.

**Comment by ghillert** [comment]
@mminella Welcome to the world of SPA applications! No easy way around that with our architectural setup. For non-oauth scenarios the login-screen is part of the SPA app. Therefore, the app needs to know whether security is enabled or not (The app supports both scenarios). The situation is similar for feature information.

So you must know whether security is enabled or not and that information must be obtained before the AngularJS app has booted. You could do provide that info with a zero-payload (initial html payload) but that would just move the buck down the block (and causes other issues).

Similarly when using OAuth - you basically don't know if you are logged and have the property roles etc. you have to retrieve that info "after the fact". After the OAuth dance, the server knows that you're logged-in but not the client.

So, yes, we should probably reduce the amount of information being exposed in the un-authenticated state, but some basic information needs to be exposed.

**Comment by mminella** [comment]
Why wouldn't this be handled by just basic HTTP return codes?

**Comment by ilayaperumalg** [comment]
The current PR makes the `/about` page secure while making use of retrieving the basic security info (whether authenticated or not etc.,) via `/security/info` REST endpoint.
