### ISSUE TITLE
Providing long deployment property values hangs

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1235]
Trying to set a property and if the value is too long it seems to hang - saw this from both shell and UI

```
dataflow:>stream deploy --name ticktock --properties "app.log.foo=FOOOOOOOOOOOBaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaar"
```

doesn't complete in a reasonable time.

**Comment by trisberg** [comment]
Adding this method in DeploymentPropertiesUtilsTests

```
	@Test
	public void testLongDeploymentrProperties() {
		Map<String, String> props = DeploymentPropertiesUtils.parse("app.foo.bar=FoooooooooooooooooooooooooBar");
		assertThat(props, hasEntry("app.foo.bar", "FoooooooooooooooooooooooooBar"));
	}
```

takes 1 min 47s

**Comment by trisberg** [comment]
Seems to be this commit https://github.com/spring-cloud/spring-cloud-dataflow/commit/289576320ff15c7c4f209cf38f0de01ad7e48757 that introduces this behavior

**Comment by jvalkeal** [comment]
Not sure what happens as I tried it and my sts shows it takes 0.045s to run that test. Could you dump a stack?

**Comment by ericbottard** [comment]
All the more reason to go back to straight splitting on commas, now that we have https://github.com/spring-cloud/spring-cloud-dataflow/pull/1229
