### ISSUE TITLE
DeploymentIdRepository doesn't make sense for tasks

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow#1237]
A single task can be launched multiple times. Using `DeploymentIdRepository` doesn't make sense for apps, neither does the single-valued "status" column in `task list`.

We should remove or computed an aggregated / reduced (last? groupBy?) status.

**Comment by ericbottard** [comment]
@mminella @markfisher WDYT?

**Comment by mminella** [comment]
I agree on the status.  I don't know what the `DeploymentIdRepository` does so I can't speak if it makes any sense or not.

**Comment by ericbottard** [comment]
It's a one to one mapping from (unit name) to AppDeployer/TaskLauncher id.
This is taken care of for tasks by `externalId`

**Comment by mminella** [comment]
Gotcha.  Then I agree that neither makes sense.

**Comment by cppwfs** [comment]
It has been discussed here: https://github.com/spring-cloud/spring-cloud-dataflow/issues/1051

**Comment by sabbyanandan** [comment]
This is not applicable to Tasks. Marking it as invalid.
