### ISSUE TITLE
Show environment and version info in the shell

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1247]
We should add a `dataflow about` command for the shell to show environment info (from the /about endpoint) and the shell version.

**Comment by ericbottard** [comment]
There is already `dataflow config info`

**Comment by trisberg** [comment]
Yes, we can enhance what we show for `dataflow config info`, I've updated the title for this issue.

**Comment by trisberg** [comment]
why not add this to 1.2.0.RC1? Can't be that much work.
