### ISSUE TITLE
Deployed applications should have properties set to identify the server and stream from which it came.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1248]
When an application is deployed, the following properties should be set.

```
spring.cloud.dataflow.name  (server name)
spring.cloud.dataflow.stream.name  (stream name)
spring.cloud.dataflow.stream.app.name  (name of the registered app as used in the DSL)
spring.cloud.dataflow.stream.app.label  (name of the label as used in the DSL - optional - only if avail)
spring.cloud.dataflow.stream.app.type    (source, processor, or sink)
```

To integrate with Spring Cloud Stream metrics, the following properties needs to be set so that these values for the previously listed properties are sent in each metrics message.

```
spring.cloud.stream.metrics.properties=spring.cloud.dataflow.name,spring.cloud.dataflow.stream.**
```
where `spring.cloud.dataflow.name` is the name of the SCDF server.

Also, to give a useful default of primary key for Spring Cloud Stream metrics.  The SCDF server should compute a metrics key based on the following pattern the following property should be set.

```
<spring.cloud.dataflow.name>.<spring.cloud.dataflow.stream.name>.<spring.cloud.dataflow.stream.app.name || spring.cloud.dataflow.stream.app.label>.<spring.cloud.dataflow.stream.app.type>
```

This property would be the value for the property
```
spring.cloud.stream.metrics.metricsName
```
set for each app when it is deployed.  Note, this property name is likely to change to be `spring.cloud.stream.metrics.metricsKey`

**Comment by markfisher** [comment]
I think `spring.cloud.dataflow.server.name` would be better for `spring.cloud.dataflow.name`

**Comment by mminella** [comment]
Is this at an instance level?  Meaning if I have an SCDF cluster, the instance within the cluster can be identified?

**Comment by markfisher** [comment]
perhaps we should also add one more level (of highest precedence) to the following:
https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/ContextIdApplicationContextInitializer.java#L63

...e.g. `spring.cloud.stream.context.id` (or similar), and when deployed from dataflow that property itself could have a value set from a combination of these `${spring.cloud.dataflow}..` properties.

**Comment by markpollack** [comment]
@mminella Boot provides a decent default value for the instance

https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/ContextIdApplicationContextInitializer.java#L76

**Comment by markpollack** [comment]
@markfisher What you are suggesting with `spring.cloud.stream.context.id` was the idea behind setting `spring.cloud.stream.metrics.metricsName` as a combination of the `${spring.cloud.dataflow}`properties.  

@viniciusccarvalho would like to rename that to be `metricsKey` to indicate it is likely to be useful as a unique key in this specific metrics context.   I don't know how much we want to make higher level guarantees, for example another common prefix to uniquely identify a process would be region/datacenter, which we aren't taking into account now. 

So i sort of view the current `metricsName` as a useful default that will likely be unique enough, but there isn't a real guarantee.  Consumers that would forward the metrics data would have to provide the final context as to adding additional information to make the key unique for the target system.  

The metrics message would also contain individual key-value pairs so that consumers of the metrics data can pick out clearly identified values vs. being forced to handle compound key conventions.

**Comment by markfisher** [comment]
My point is that the key would be more generally useful. Making it the ID of the app's applicationContext seems like a good idea. The *default* `metricsName` value could be `${spring.cloud.stream.context.id}`.

**Comment by ericbottard** [comment]
Related to your first description @markpollack, you should assume that a label is always "set" (it defaults to the app name). The unique handle to an app within a stream is always the label, whether it has its default value or it has been explicitly overriden. I would not pass that value only if it is explicitly different from the app name (ie don't do an `if`)

**Comment by markpollack** [comment]
Maybe Vinicius can explain better, but the `metricsName` is meant to be unique - a sort of primary key - that can be passed into graphite or other systems.  That is why it is a compound name vs. only the context.id

**Comment by markpollack** [comment]
@ericbottard You want to invert what I wrote

```
spring.cloud.dataflow.stream.app.name  (name of the registered app as used in the DSL)
spring.cloud.dataflow.stream.app.label  (name of the label as used in the DSL - optional - only if avail)
```
and make the name optional?

as we have both pieces of information, it will be useful to retain because it will later enable queries that can ask for all processors that had the name 'transformer'.  We don't want to lose that information and can't infer that the label 't1' is a transformer.

**Comment by ericbottard** [comment]
Not exactly. I'm saying that the way SCDF works, the label is *always* available, as it defaults to the name.
So provide both and consider they're always available. Sometimes they will be equal, sometimes they won't. And more importantly, if a PK is needed, always take the label

**Comment by markpollack** [comment]
So the current thinking is that when deploying an application

1) SPRING_CLOUD_STREAM_METRICS_KEY will be set to <streamName>.<appLabel>.${spring.deployer.application.uniqueId}.

The deployer for each platform will have a GUID like value for uniqueId.

2) In RuntimeAppController the property `spring.deployer.application.uniqueId` will be added to the AppStatus property map.

3) The following environment variables will be set for each deployed stream

```
SPRING_CLOUD_DATAFLOW_SERVER_NAME
SPRING_CLOUD_DATAFLOW_STREAM_NAME
SPRING_CLOUD_DATAFLOW_STREAM_APP_LABEL
SPRING_CLOUD_DATAFLOW_STREAM_APP_TYPE
```

4) The following environment variable will be set to configure the properties contained in the metrics message

```SPRING_CLOUD_STREAM_METRICS_PROPERTIES=spring.cloud.dataflow.*,spring.deployer.*,spring.cloud.stream.instanceIndex
```

We can add others, but this looks to be a sufficient set for the collector to use for grouping and aggregating the metrics data.

**Comment by ericbottard** [comment]
> The deployer for each platform will have a GUID like value for uniqueId.

I'm not sure I understand the purpose of this property.
If it is used by the metrics library, which is eventually embedded in the running app, why not have the library generate it in a consistent manner (eg GUID).

If it needs to be know by SCDF, then why have the **deployer** generate it, rather than SCDF?

**Comment by markfisher** [comment]
I agree with @ericbottard. We should avoid requiring this in each deployer implementation if there's any possible way to compose a unique ID from information available in data flow core (which I believe should be the case).

**Comment by jvalkeal** [comment]
@ericbottard @markfisher value of `uniqueId` doesn't matter as it just needs to be unique within a current apps running. Reason why it has to be returned within attributes for every instance is that otherwise we don't have a way to backmap metrics to show in a correct place within UI.

This cannot be fully done on SCDF server side as then we'd need to be able set individual metric name per launched instance. It's a deployer which needs to set this uniquely.

**Comment by ericbottard** [comment]
As a matter of fact, if we consider CF, then there is no way to set a different, individual value per instance. This should be generated inside the running process of the app itself. I''d say in most platforms, there is no way to set per-instance properties (the same reason that forced @trisberg use a trick to pass the instance id in k8s).
So then really, the question is this: why do we need a new property if it can be derived from existing info?

**Comment by markpollack** [comment]
To clarify why we can't make our own GUID, we are trying to solve the following problem.   A user deployer time|log with 5 log instances.  The user is looking at the UI or runtime apps endpoint and observes one of the log instances is at 100%.  There should be a way for the user to look at our UI and then make a link to the native platforms tools to find that specific app so they can investigate deeper.   In the case of k8s, the GUID is in the hostname, so one would go to the management tool for k8s and find that host and start to dig deeper.  In CF if we know the instance index (which is determined at runtime) we can filter the logs in PCF Metrics bassed on the [app-<instanceId>] suffix.   There maybe a way to jump to the app via the GUID in CF, still looking into it.   It is misleading now in the current code base (say for CF) where we attach a suffix (0,1,2,3) in the runtime app endpoint and show cpu info, when that suffix has no relation (it seems) to the actual CF_INSTANCE_INDEX.  

So this can't be derived from existing info, we want to relay under a common name, the value of an environment variable that is set at runtime that uniquely identifies the specific app.  

```
PCF : CF_INSTANCE_GUID 
k8s : HOSTNAME
YARN : CONTAINER_ID
MESOS: MESOS_CONTAINER_NAME
```
the value on the righthand side is the env-var that is unique on each platform to the app and is created at runtime.

There might an issue here w/ docker & PCF, looking into that now.

**Comment by mminella** [comment]
This is the same thing as the SCT external execution id...

**Comment by markfisher** [comment]
How does this compare to the case where a stream app is pushed manually? (not via the Data Flow Server). In particular, IF we ever achieve the goal of having a Data Flow Server recognize existing stream apps that may have been pushed manually, how would this work in such a case? (i.e. could the ID somehow still be determined at the level of the stream app itself instead of having to be pushed to it by the server... all the necessary info is present within the app, right?)

**Comment by viniciusccarvalho** [comment]
@markfisher Well since the key could be anything unique (as we decided), it's up to the entity (a person or a CI pipeline) deploying that app to set it right? I think we may have issues grouping by if the app does not set some of the values on the metadata, but we could explicitly ask users to provide that metadata if they want to have their apps show message rates in the UI.

Probably the biggest issue for the collector would be the lack of stream name, as that app is not part of a stream.

**Comment by markpollack** [comment]
I was going to mention this before but forgot, we can also change the name of the env-var to be `SPRING_APPLICATION_GUID` so that a 'meet in the middle' approach of identifying a collection of apps to be a stream would not be tainted with the word 'deployer'.  ATM the use of this GUID is only relates to metrics functionality and in CF land, the instanceId - while not globally unique - is the more first class citizen to identify a given application.
