### ISSUE TITLE
Runtime streams UI displays only duplicates when over 10 streams are deployed

### ISSUE THREAD

**Issue by kniemann** [spring-cloud/spring-cloud-dataflow#1250]
I have about 15 streams deployed locally (running 1.1.4.RELEASE) and the runtime list in the Dataflow webapp UI seems to have a page max of 10 streams, but page two is a duplicate of page one. The remaining 5 deployed streams aren't visible to me unless I use the REST API or Shell.

See screenshots;

![image](https://cloud.githubusercontent.com/assets/8548844/24157916/0476f8b4-0e18-11e7-89e7-50d43669e1a9.png)

![image](https://cloud.githubusercontent.com/assets/8548844/24157922/0b2dab44-0e18-11e7-9910-fe5a51588a58.png)

**Comment by sabbyanandan** [comment]
Hi, @kniemann: Thanks for reporting this. This needs to be reviewed at [spring-cloud/spring-cloud-dataflow-ui](https://github.com/spring-cloud/spring-cloud-dataflow-ui/) project - I will move it there.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#176
