### ISSUE TITLE
Remove git-commit-id from  /about-details page

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1253]
Running the local server 1.2.0.M3 and accessing the `/about-details` page the commit id shown is `d10dfcd` while the actual commit id for the 1.2.0.M3 release is `c065c76`, the id shown is for the previous commit. Not sure what value this id provides but if we show it, it should be the one for the actual server release and not the commit before the release.

Here is the content of the releases `git.properties` file where the info seems to be coming from:

```
#Generated by Git-Commit-Id-Plugin
#Tue Mar 21 18:49:40 UTC 2017
git.build.user.email=buildmaster@springframework.org
git.build.host=bamboo-08
git.dirty=true
git.remote.origin.url=file\://nothing
git.closest.tag.name=v1.2.0.M2
git.commit.id.describe-short=v1.2.0.M2-30-dirty
git.commit.user.email=trisberg@pivotal.io
git.commit.time=2017-03-21T18\:33\:04+0000
git.commit.message.full=Update all SNAPSHOT dependencies\n\n- make updates to spring-cloud-dataflow-server-local
git.build.version=1.2.0.M3
git.commit.message.short=Update all SNAPSHOT dependencies
git.commit.id.abbrev=d10dfcd
git.branch=master
git.build.user.name=Spring Buildmaster
git.closest.tag.commit.count=30
git.commit.id.describe=v1.2.0.M2-30-gd10dfcd-dirty
git.commit.id=d10dfcd5626dfe38fdb6059af21430743e28f545
git.tags=
git.build.time=2017-03-21T18\:49\:40+0000
git.commit.user.name=Thomas Risberg
```

**Comment by trisberg** [comment]
My hunch is that the Bamboo build happens before the version changes are committed to Git, so it seems the `git-commit-id-plugin` is of no use here.

**Comment by ericbottard** [comment]
This is weird. When I tested this locally with no un-commited changes, the value was correct (my HEAD at the time).
Bamboo does 2 commits, one for the release and one for next-version.
Are you implying that it is publishing the result of a non-commited work version and *then* commiting those changes?

**Comment by trisberg** [comment]
That's what it looks like to me but I really have no idea of how it works internally
