### ISSUE TITLE
task execution list should return in ascending IDs order

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow#1254]
To be handled at shell or REST API level

**Comment by sabbyanandan** [comment]
The latest execution first seems like the logical order, which would be the descending order, and that's what is happening now in Shell, API, and Dashboard. On top of it, someone can sort the column in the Dashboard to derive the desired order - see below.

![image](https://user-images.githubusercontent.com/1562654/54049042-49c11f00-4190-11e9-9e8e-32f241efd277.png)

I don't see any valid reasons to change the current order. I am closing this as invalid.
