### ISSUE TITLE
Document how to use "jsonpath" in stream definitions

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1265]
As a user, I'd like to use `#jsonpath` in streams with apps that support SpEL expression.

**Acceptance:**
Include sample stream definition to demonstrate `#jsonpath` usage.

**Comment by javyzheng** [comment]
Nice feature. Read a lot materials and tried many times only to create the following stream:
```
:input-topic > transform --expression="'{\\\"id\\\":\\\"'.concat(#jsonPath(payload,'$.id')).concat('\\\",\\\"headline\\\":\\\"').concat(#jsonPath(payload,'$.headline')).concat('\\\",\\\"content\\\":\\\"').concat(#jsonPath(payload,'$.content')).concat('\\\"}')" | log
```
But feels it is inefficient to have so many string concatenations and it is ugly to have so many slashes(\\) to  just reserve the double quote(") in the JSON string.
