### ISSUE TITLE
Delete Child Tasks for Composed Task

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#1272]
When executing task destroy on a composed task.  The child tasks for that task should be destroyed.

**Comment by mminella** [comment]
Are we re-using definitions when a definition is parsed?  AKA, if we find a definition that matches one that already exists, do we re-use it?  If so, we wouldn't want to do this.

**Comment by cppwfs** [comment]
good point.  But this means that tasks that are created as a part of the _taskname_taskApp will remain.  Not quite an orphan, but untidy.

**Comment by mminella** [comment]
I'd vote for this to be an option.  Something like `task destroy --name=foo --cascade` that we could then warn the user that this may delete definitions that are in use.

**Comment by markfisher** [comment]
why would you ever want to preserve the generated definitions though?

**Comment by mminella** [comment]
@markfisher To my point above, if we are re-using definitions, you'd want to keep them.  If we are not, then I retract my concern (I'm asking...I honestly don't know).   @aclement would know...

**Comment by cppwfs** [comment]
@markfisher To Michael's point, a user can technically create a
composed_task_runner by hand using existing tasks.  And for this we would
not want to destroy the "child" tasks.

**Comment by mminella** [comment]
Wait... @cppwfs That is different than what I was implying.  I'm implying that if you had the following:
```
task create --name=foo --definition="AAA --a=1 && BBB"
task create --name=bar --definition="BBB && CCC"
```
Does the above result in three six definitions or five definitions?  Specifically, does the generated `BBB` definition get re-used between the two composed definitions?

**Comment by cppwfs** [comment]
in the case above you would get 6 (and an egg roll) ;-) :
_foo_AAA
_foo_BBB
foo
_bar_BBB
_bar_CCC
bar

**Comment by mminella** [comment]
If that's the case, then disregard my concern.
