### ISSUE TITLE
Add REST API revision to version info shown in server and shell

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1275]
Now that we enforce the revision for linking up the shell to the server it would be nice to show this revision on both sides.

We could add revision to the "versionInfo" portion of the `/about` page:

```
"versionInfo": {
  "implementation": {
    "name": "spring-cloud-dataflow-server-kubernetes",
    "version": "1.2.0.BUILD-SNAPSHOT"
  },
  "core": {
    "name": "Spring Cloud Data Flow Core",
    "version": "1.2.0.BUILD-SNAPSHOT",
    "apiRevision": "14"
  },
  "dashboard": {
    "name": "Spring Cloud Dataflow UI",
    "version": "1.2.0.M2"
  }
},
```

And for the shell we could add it to the "version" command:

```
dataflow:>version
1.2.0.BUILD-SNAPSHOT [apiRevision: 14]
```

**Comment by ericbottard** [comment]
I really see this revision number as a fail fast mechanism for us. It should not be exposed to users IMO.

**Comment by trisberg** [comment]
I keep hitting it recently, so it would be nice if there was a way to see what I had

**Comment by ericbottard** [comment]
This should be displayed in the error message (when you do `dataflow config server`).
The fact that it's not displayed on raw shell startup-and-connect is another issue that needs to be fixed altogether IMHO (the shell should either crash or give the same experience as if the user had typed `dataflow config server` himself)

**Comment by sabbyanandan** [comment]
Relates to #1758

**Comment by sabbyanandan** [comment]
The `dataflow config info` command from Shell provides all the insights.
