### ISSUE TITLE
Study the applicability of Concourse in SCDF

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1277]
As a developer, I'd like to explore the applicability of Concourse in the context of overall data pipeline orchestration.

**Acceptance:**
- Come up with the list of integration ideas
- Document the applicability in the context of deployer and orchestration mechanics 
- Design consideration to also include the applicability of stream-edits/versioning and the deployment lifecycle

**Comment by jldec** [comment]
As a developer, I'd like to
1. commit my code to a git feature branch
2. trigger suite of automated unit tests
3. (auto) deploy to a lab environment (on every commit) and run integrated tests
4. when ready, deploy feature to production with a single well-documented "deploy" step
5. merge my feature branch

**Comment by sabbyanandan** [comment]
A reference implementation of CD for data pipelines using SCDF, Skipper, and Concourse is [here](https://github.com/sabbyanandan/xfmr) ([slides](speakerdeck.com/sabbyanandan/devnexus-2018-continuous-delivery-for-data-pipelines)).
