### ISSUE TITLE
Document Metrics functionality

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1288]
As a user, I'd like to turn-ON metrics capability, so I can monitor the overall pipeline health.

**Acceptance:**
- a new section "Metrics and Monitoring" is added to the left-nav in the reference guide
- describe how to turn-ON metrics feature
- describe what metrics are supported
- add metrics architecture visual 
- add "runtime apps" screenshots
- add "flo" screenshots

**Comment by markpollack** [comment]
Initial PR https://github.com/spring-cloud/spring-cloud-dataflow/pull/1320 

* add metrics architecture visual
* add "runtime apps" screenshots
* add "flo" screenshots

to be added.  Can get arch visual from here https://docs.google.com/a/pivotal.io/presentation/d/1D1blpqouCVpk8tBCYX9JPB69MEXK-g0HwqiWiOgOjxE/edit?usp=sharing
