### ISSUE TITLE
Add INFO logging when downloading a jar

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1300]
When deploying a stream, if the jar file needs to be downloaded to the SCDF server since it isn't in the local maven cache, it can take a while, ~30-1min seconds on a slow Internet connection.  During this time the server appears to be not responding to the deployment request.  Adding a logging statement will help show that the deployment request has been received and in in the process of executing.

**Comment by markfisher** [comment]
For 2.0 should we consider adding either a flag for eagerly downloading upon registration (could happen in the background immediately after the `app register` is issued), or an additional command, e.g. `app resolve`. Often it would be better to pre-download than to wait upon the initial deployment.
