### ISSUE TITLE
Bulk Define Tasks doesn't work for composed tasks

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1314]
The validation fails saying "No valid task definitions detected"

**Comment by ilayaperumalg** [comment]
This requires `spring-cloud-dataflow-ui` changes on its DSL parser to validate the `composed` task DSL text [here](https://github.com/spring-cloud/spring-cloud-dataflow-ui/blob/master/ui/app/scripts/shared/services/parser.js#L314)

**Comment by sabbyanandan** [comment]
The bulk-define support is removed from the Dashboard in favor of composed-task canvas.
