### ISSUE TITLE
Task launch using app properties doesn't support "*" wildcard

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1328]
If I deploy a stream I can use "*" as a wildcard when defining app properties. When launching a task I can't , I have to use the actual app name like "app.timestamp.format=dddd-MMMM-yyyy".

**Comment by sabbyanandan** [comment]
Both the application and deployment properties are supported for Tasks now, so let's retest this on the 2.x foundation.

**Comment by sabbyanandan** [comment]
We support the following pattern for both app and deployment properties while launching a task.

> dataflow:>task launch mytask --properties "deployer.*.custom1=value1,app.*.custom2=value2"
