### ISSUE TITLE
Use existing halObjectMapper in MetricsStore

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1329]
Instead of creating the jackson mapper 'from scratch' in MeticsStore,can we reuse the existing bean in the context named halObjectMapper?

See https://github.com/spring-cloud/spring-cloud-dataflow/pull/1312 for additional context.

**Comment by markpollack** [comment]
Note that https://github.com/spring-projects/spring-hateoas/issues/333 is still open.

**Comment by sabbyanandan** [comment]
The `MetricsStore` is from the legacy Metrics Collector based implementation, and it has been deprecated in favor of Micrometer integration in SCDF.
