### ISSUE TITLE
AppRegistry exception throws checked IOException

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1341]
This is thrown in the registerAll method.

RestControllerAdvice does not do anything with that exception.

This is thrown due to trying to copy the contents of the java.util.Properties class to a ByteArrayOutputStream and in turn pass to a Spring ByteArrayResource.

Is there another way?

**Comment by tzolov** [comment]
@markpollack , @sabbyanandan, this issue is likely to have been resolved with the new SCDF 2.0 app refactoring.  
The `DefaultAppRegistryService#importAll` doesn't throw checked IOException but re-throws such runtime exceptions.  
So imo this should be closed with nothing to fix?

**Comment by sabbyanandan** [comment]
This has been already addressed.
