### ISSUE TITLE
NoSuchJobExecutionException is declared on many controller methods but never thrown

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1343]
Look for instantiation of NoSuchJobExecutionException and remove from all throws declarations where it is not relevant.

**Comment by cppwfs** [comment]
Checked the controllers that throw NoSuchJobExecutionException to see if any were not valid. What was found:
1) the method called a jobService that used a method that threw the exception
2) the method called a taskService implementation that ultimately used a jobService method that threw the exception.

**Comment by markpollack** [comment]
for example

```
	@RequestMapping(value = "", method = RequestMethod.GET, produces = "application/json")
	@ResponseStatus(HttpStatus.OK)
	public PagedResources<JobExecutionResource> list(Pageable pageable,
			PagedResourcesAssembler<TaskJobExecution> assembler) throws NoSuchJobExecutionException {
		List<TaskJobExecution> jobExecutions = taskJobService.listJobExecutions(pageable);
		Page<TaskJobExecution> page = new PageImpl<>(jobExecutions, pageable, taskJobService.countJobExecutions());
		return assembler.toResource(page, jobAssembler);
	}
```

and 

```
	public List<TaskJobExecution> listJobExecutions(Pageable pageable)
			throws NoSuchJobExecutionException{
		Assert.notNull(pageable, "pageable must not be null");
		List<JobExecution> jobExecutions = new ArrayList<>(
				jobService.listJobExecutions(pageable.getOffset(),
				pageable.getPageSize()));
```
But `jobService.listJobExecutions` does not throw that exception.

**Comment by markpollack** [comment]
same thing for `JobInstanceController.java:88:`.  Perhaps only the `list' methods are wrong and need to be updated by removing the throws clause.

**Comment by markpollack** [comment]
I came across this via filling in missing javadoc statements and didn't want to get sidetracked.  when removing those throws clauses, can you also run javadoc and fill in the missing stuff as well please?

**Comment by cppwfs** [comment]
In both cases above the need for the exception is required.

**Comment by markpollack** [comment]
ah, you are right.  so then it is just javadoc cleanup.  sorry about that.
