### ISSUE TITLE
Fix Javadoc warnings for DSL package

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1345]

**Comment by aclement** [comment]
I don't see any javadoc warnings for me to fix now, is that right? The only ones I see are on RestControllerAdvice.java now.

**Comment by sabbyanandan** [comment]
@markpollack: Is this at the build-level warning or maybe in the IDE?

**Comment by aclement** [comment]
I created a PR that addresses the only thing I could find, which was deprecation messages in core (in AbstractTokenizer.java).

https://github.com/spring-cloud/spring-cloud-dataflow/pull/1415

I don't see it as urgent for 1.2 final, in some ways let's not rock the boat and fix all the other deprecation warnings too post 1.2.
