### ISSUE TITLE
Analyse the use of Spring Batch admin manager in JobExecution controller

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1350]
There are some gaps when using Spring batch admin manager inside Spring Cloud Data Flow.

Retrieving step executions for composed tasks is one such issue.

We need to start some discussion on how to handle this dependency.

**Comment by mminella** [comment]
We really should remove this dependency all together.  It was added as an intent to merge the two projects which isn't going to happen.

**Comment by sabbyanandan** [comment]
This is not applicable anymore.
