### ISSUE TITLE
Add UI image for metrics documentation

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1357]
The docs describe a `time|log` stream with two instances each, show the UI for that stream with message rates.

**Comment by aclement** [comment]
![timelog](https://cloud.githubusercontent.com/assets/226298/25150674/933ffb7e-2437-11e7-9468-f498d08b5492.png)

is that ok? Crop as you like.

**Comment by aclement** [comment]
![foostream](https://cloud.githubusercontent.com/assets/226298/25151663/3dad2b24-243b-11e7-9b2b-e52edcc45118.png)

actually in the docs it might be called foostream, here is one where it is called that in the image, deployed with these properties:

stream deploy --name foostream --properties "app.*.spring.cloud.stream.bindings.applicationMetrics.destination=metrics,deployer.*.count=2"
