### ISSUE TITLE
Add section how to configure dataflow.server.uri for composed task runner

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1363]

**Comment by sabbyanandan** [comment]
Since it is automated via: https://github.com/spring-cloud/spring-cloud-dataflow/commit/41426532c49de9cd46f47579e2d80b62e57ad7ee, do we still need it?

**Comment by trisberg** [comment]
It's only automated if you provide `spring.cloud.dataflow.server.uri`, it's a chicken and egg thing, we can't assume the chicken is available.
