### ISSUE TITLE
DataFlow does not support composed task comprised of composed-task-runner applications

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#1374]
A user could have a composed task that contains a composed-task-runner as one of its tasks i.e.
`task create foo composed-task-runner --definition "graph=\"task1-def && task2-def\" && AAA-app"`
When attempting to create the child-tasks (in this example: `composed-task-runner` and `AAA-app`) for the applications in the foo composed task, the TaskDefinition identifies the composed-task-runner as a composed task definition, when in fact it should treat it as a standard task app.

**Comment by sabbyanandan** [comment]
We don't yet have a specific use-case where this might be useful, closing it for now.
