### ISSUE TITLE
Flo instance metric popup too tiny

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#1378]
On yarn `guid` will be something like `container_1492712105510_0003_01_000003` and I think it is causing `guid` and actual metric value to span outside of popup itself. 
![metric-ui-bug-report](https://cloud.githubusercontent.com/assets/50398/25247053/9711a0f6-2601-11e7-80f9-f57d49c15cf9.png)

Can we fit these a little better?

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#204
