### ISSUE TITLE
Shell: Support authentication using OAuth Access-Token

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#1379]
As the REST Api now supports Access-Token authentication when using OAuth2, it would be nice if the shell also supported the options to provide credentials via an access token.

See also: https://github.com/spring-cloud/spring-cloud-dataflow/issues/1279

**Comment by sabbyanandan** [comment]
The Shell currently provides `--dataflow.credentials-provider-command` option and that can accept an executable command, which in return could supply the OAuth Token (e.g., `--dataflow.credentials-provider-command=cf oauth-token`).
