### ISSUE TITLE
Task Executions Details exposes database password

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1381]
The data shown in `/tasks/executions/{executionid}` includes the database password as part of the arguments. We should show '****' instead.

**Comment by cppwfs** [comment]
hmm, testing against local SCDF server I'm not seeing that data show up in the task_execution_params.  How are you passing in the password?

**Comment by trisberg** [comment]
I think this only happens when you use a deployer that passes in the AppDefinition.properties as command line args. The k8s deployer does this when using the `exec` style entry-point.

**Comment by cppwfs** [comment]
It is.  We only store command line args to task execution param.  Is this the only param we need to redact ?  Or is it for any data source param?

**Comment by trisberg** [comment]
I'd redact anything containing `password` only, noo need for other connection params - should be similar to what `/env` endpoint does

**Comment by mminella** [comment]
I'd +1 going over the command line args and applying the same logic that Boot applies.
