### ISSUE TITLE
Pagination broken and causing runtime-apps and flo to fail

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#1397]
Looks like recent changes to pagination used by UI's stream definitions page goes to request loops and flo graph is not shown.
![flo-pagination-bug](https://cloud.githubusercontent.com/assets/50398/25397715/2ac5cd12-29e1-11e7-8723-f8b7d5cbc38c.png)

**Comment by trisberg** [comment]
@ilayaperumalg we are planning on reverting the commit for https://github.com/spring-cloud/spring-cloud-dataflow/commit/21840685925dc9272f86c0fc054f0c63e51208c4 and waiting until 1.2.0.RELEASE is out before making code changes. So lets put this fix on hold for now.

**Comment by ilayaperumalg** [comment]
This issue will be fixed once #1401 is addressed.
