### ISSUE TITLE
Add AppRegistry findAll(Pageable)

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1401]
Currently, AppRegistry `findAll(Pageable)` is not available but the `AppRegistryController` is [expected](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/AppRegistryController.java#L106) to return Paginated resources.

The Spring Cloud Data Flow UI is also built with the same [expectation](https://github.com/spring-cloud/spring-cloud-dataflow-ui/blob/master/ui/app/scripts/stream/services/metamodel.js#L284)

and, this causes issues like #1397

**Comment by sabbyanandan** [comment]
We support this in the backend already.
