### ISSUE TITLE
Add Shell command for app registerAll using apps parameter

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1404]
As a user I'd like to have `apps` parameter to be passed to `/apps` REST endpoint via `POST` request. Currently, we only have `uri` as the option.

**Comment by ericbottard** [comment]
I don't understand this. App import that reads the properties/yaml file on the shell side does exactly that, doesn't it?

**Comment by ilayaperumalg** [comment]
Yeah, that's right. I overlooked that part. Closing this as invalid.
