### ISSUE TITLE
Not able to run maven build from sub projects 

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1416]
Because of the way we refer the `checkstyle` files, running `build` from sub projects fails:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle-validation) on project spring-cloud-dataflow-core: Failed during checkstyle configuration: cannot initialize module RegexpHeader - illegal value 'src/checkstyle/checkstyle-header.txt' for property 'headerFile' of module RegexpHeader: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: src/checkstyle/checkstyle-header.txt -> [Help 1]
[ERROR]
```

**Comment by ilayaperumalg** [comment]
Even if we use something like:

```
 <propertyExpansion>basedir=${project.basedir}</propertyExpansion>
```
and refer it inside the checkstyle config, this requires to be fixed for parent vs sub projects.

**Comment by ilayaperumalg** [comment]
The one workaround to run the build from the `sub-projects` is to skip checkstyle validation like this: `-Dcheckstyle.skip=true`

**Comment by ddsharpe** [comment]
Any ETA on fixing this?  We would really like to enforce copyrights on files, but this bug makes it too annoying to use.

**Comment by jvalkeal** [comment]
Attempting to fix this when spring-cloud/spring-cloud-dataflow-build#9 is done.
