### ISSUE TITLE
Progress/contribution on standalone apps and application groups (#915)

### ISSUE THREAD

**Issue by dalsh** [spring-cloud/spring-cloud-dataflow#1417]
Hi,

I notice the proposal by @donovanmuller on standalone apps and application groups. I dug a little and noticed the progress started with #1122, #1123.

My team and I are very interested in these features, how can we proceed to contribute to it ?

**Comment by sabbyanandan** [comment]
Hi, @dalsh @joriscaloud @hekonsek: As you noticed, we have started working on it; however, we hit a roadblock with breaking changes in DSL/REST-APIs, which isn't ideal or acceptable in 1.x/1.2 release line.

The plan is to support this in 2.0, though. We are brainstorming internally on the design (again) and we will share an update along with the stories very soon.

Thanks for sharing your interest!

**Comment by hekonsek** [comment]
Noted. Many thanks for the information Sabby. Please keep me in the loop.

**Comment by dalsh** [comment]
Thanks @sabbyanandan for your answer. For information, we have designed something extremely similar to @donovanmuller's proposal (before we noticed his post about it). Do you have a rough timeline in mind for your plan (we are considering building this internally) ?

**Comment by sabbyanandan** [comment]
We have taken a different approach to supporting "app-grouping" workflows in SCDF. [Spring Cloud Skipper](http://cloud.spring.io/spring-cloud-skipper/) will support the app-lifecycle primitives, and SCDF will use it as a companion server to accommodate "app-grouping" workflows. 

Skipper + SCDF integration can be tracked via [`skipper-integration`](https://github.com/spring-cloud/spring-cloud-dataflow/labels/skipper-integration) label.
