### ISSUE TITLE
Prepare for release, update dependencies

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1420]
We need to update the dependencies for the following artifacts:

 - spring-cloud-dataflow-ui to version 1.2.0.RELEASE

 - spring-analytics to version 1.2.0.RELEASE

**Comment by ilayaperumalg** [comment]
`spring-cloud-dataflow-ui` version is already updated via https://github.com/spring-cloud/spring-cloud-dataflow/commit/9012bc48f7d6f65f24f634f68e87a1eddb5ead82

**Comment by ilayaperumalg** [comment]
Once `spring-analytics` 1.2.0.RELEASE is released, this PR #1419 can be updated/merged.

**Comment by sabbyanandan** [comment]
We can repurpose #1419 to tackle analytics update - this is not required anymore.
