### ISSUE TITLE
Improve checkstyle's reference of header.txt file

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1437]
The default location for the header text is given with the path `src/checkstyle/checkstyle-header.txt` and if one is building only a specific module of the project, this file is not found.  

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle-validation) on project spring-cloud-dataflow-docs: Failed during checkstyle configuration: cannot initialize module RegexpHeader - illegal value 'src/checkstyle/checkstyle-header.txt' for property 'headerFile' of module RegexpHeader: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: src/checkstyle/checkstyle-header.txt -> [Help 1]
```

A workaround wrt to building docs, is to build the project locally and install, then cd to the docs module and execute the doc build.

```
./mvnw clean install -DskipTests=true
 cd spring-cloud-dataflow-docs/
../mvnw package -Pfull -Dcheckstyle.skip=true -o
```

Referencing the header with the maven checkstyle plugin build properties in the parent pom did not work.  Maven properties are resolved inside the checkstyle.xml file, but it isn't obvious how to refer to the location where the root pom sits.

**Comment by trisberg** [comment]
You could also run

```
./mvnw clean install -DskipTests -Pfull -pl spring-cloud-dataflow-docs/
```

**Comment by ilayaperumalg** [comment]
This is same as https://github.com/spring-cloud/spring-cloud-dataflow/issues/1416

**Comment by sabbyanandan** [comment]
We never looked into it, and don't think we ever will.
