### ISSUE TITLE
Polish and double-check documentation links

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#1444]
The documentation contains 1 broken link and several links need polishing:

https://validator.w3.org/checklink?uri=http%3A%2F%2Fdocs.spring.io%2Fspring-cloud-dataflow%2Fdocs%2F1.2.0.BUILD-SNAPSHOT%2Freference%2Fhtmlsingle%2F&hide_type=all&depth=&check=Check#d1code_404

**Comment by markpollack** [comment]
There are many false positives in that.  Let's just fix the few that are really broken.
