### ISSUE TITLE
Cleanup default user role handling

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1472]
We need to revisit the class `DefaultBootUserAuthenticationConfiguration` that initializes the role for the default user with in-memory authentication.

Given we now use `MANAGE` role for the `management.security.roles`, this class can be simplified further.

**Comment by ghillert** [comment]
@ilayaperumalg The question (edge-case) I have - How do you create a single user with username `user` without the `MANAGE` role.

I see the following 2 scenarios: 

- user `user` (For single user authentication) will always has the `manage` role at least.
- user `user` will have always all Roles `manage`, `view`, `create`

**Comment by sabbyanandan** [comment]
The role management and the RBAC workflows have significantly changed since when this issue was logged. If there's a need to revisit this in the future, let's open a new story.
