### ISSUE TITLE
Measure current code coverage and generate reports

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1479]

**Comment by markpollack** [comment]
Initial pass

module | coverage
------------ | -------------
completion | Method: 94%, Line: 89%
configuration.metadata | Method:75%, Line: 73%
dataflow-core | Method: 76%, Line: 79%
dataflow-registry | No tests!
dataflow-rest-client | direct tests Method: 7%, Line: 14% , Usage via shell-core tests, rest.client method: 6% Line: 11% Rest.client.support Method: 16% Line 39%
dataflow-rest-resource | Method: 7%, Line: 15%
dataflow-server-core | Method: 73% , Line: 67%
dataflow-shell-core | Method:64%, Line: 60%

**Comment by sabbyanandan** [comment]
Created #1508, #1509, #1510 to address lack of coverage in "dataflow-registry", "dataflow-rest-client", and "dataflow-rest-resource" modules.
