### ISSUE TITLE
Support for dynamic destinations in DSL

### ISSUE THREAD

**Issue by hekonsek** [spring-cloud/spring-cloud-dataflow#1500]
Hi,

I'd like to deploy stream starting with HTTP source [1] and writing messages to dynamically resolved Kafka topic (relying on dynamic destination [2]). So for example HTTP request with header `TOPIC=foo` is written to Kafka topic `foo`. Let's also say that I modified HTTP starter to use `BinderAwareChannelResolver` to dynamically resolve output channel. 

This application works nice when deployed as a standalone application. However I'm not sure how to deploy it into Data Flow server. The reason is that the current version of data flow DSL doesn't allow me to create a stream definition without specifying sink app or explicit destination. I can't just say:

    create stream "http"

I need to specify sink:

    create stream "http | log"

Or static explicit destination:

    create stream "http > :myTopic"

I'm wondering what would be the best approach here. Maybe it should be possible to allow data flow DSL to create streams with source only assuming that in such case the output topic will be dynamically resolved by source app?

Or maybe the explicit channel notation should support dynamic expression? For example `create stream "http > :${headers.topic}" ` ?

@mbogoevici Marius, I'm taking a liberty of pinging you here, as this is really a continuation of our previous discussion :) .

Many thanks in advance!

[1] https://github.com/spring-cloud-stream-app-starters/http/tree/master/spring-cloud-starter-stream-source-http
[2] http://docs.spring.io/autorepo/docs/spring-cloud-stream-docs/Chelsea.SR1/reference/htmlsingle/#dynamicdestination

**Comment by markfisher** [comment]
Great to see this! The ability to deploy standalone apps (or "groups" of apps that are not necessarily data flow pipelines) is on our roadmap for 2.0. I would also say that the dynamic HTTP source starts to take on the role of a Gateway which is also on the roadmap for 2.0 (i.e. having that as a first class part of the ecosystem). Furthermore, in 2.0 we are considering ways to elevate the role of Topic destinations, e.g. providing REST endpoints and shell commands to view/create the available Topics. With that in place, I think we'd start promoting more stream definitions beginning with a Topic (e.g. `:someTopic > someProcessor | someSink`. It would be great if you're willing and able to contribute to these efforts.

In the meantime, you may choose to deploy the app outside of data flow, OR if it makes sense, you could use the explicitly bound output destination as a default? (when no header is present)

By the way, have you considered using a `@PathVariable` for the topic name instead of a header? We might ultimately want to provide some pluggable strategies for resolving the name (as well as providing options for whitelisting vs. fully dynamic... which is already supported at the router level).

**Comment by hekonsek** [comment]
Hi Mark,

Yes, actually I would prefer to use path variable instead of header to indicate a topic name, as it seems more natural for me to map URI to topic. I used header in an example to make it easier to understand the kind of behavior I'd like to achieve.

When it comes to your 2.0 roadmap - I love what I read here. And yeah, basically I'd like to achieve gateway-like behavior of external endpoints. Do you have a kind of 2.0 roadmap for Data Flow? Ideally a list of GitHub issues, so I could take a look at those and contribute to some of them?

**Comment by hekonsek** [comment]
BTW When do you expect 2.0 to be released? Any guestimate?

**Comment by sabbyanandan** [comment]
Hi, @hekonsek. We are brainstorming internally to finalize the design and the stories will land in the repo very soon. The 2.0 release is planned for early Q4-2017. Of course, there will be milestone releases for incremental use and feedback.

Once we have the stories defined, it'd be great to collaborate and have you contribute to the efforts.

**Comment by hekonsek** [comment]
Many thanks @sabbyanandan. Please keep me in the loop. I'd love to help.

**Comment by hekonsek** [comment]
Hi guys,

Any news? :)

**Comment by sabbyanandan** [comment]
Hello, @hekonsek. Our team is meeting f2f next week to brainstorm on 2.0 themes, which includes this feature, too. Coming out to these meetings, we anticipate to have clarity on next steps and the scope. Thanks for your patience.

**Comment by hekonsek** [comment]
Awesome! Many thanks for keeping me in a loop.

**Comment by sabbyanandan** [comment]
@hekonsek: This is a very old issue; unfortunately, we didn't share an update on this for a while. My apologies. 

Starting from v1.7.x and in the latest v2.0, it is possible to deploy apps either as a single entity or as a pipeline made of apps. See ["Stream Application DSL"](http://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.RELEASE/reference/htmlsingle/#spring-cloud-dataflow-stream-app-dsl) to learn more about it. The `App` type in SCDF can be any dockerized workload even, and not just Spring Boot (Stream/Task) apps.

Going back to your example, the following definitions are possible now.

```
dataflow:>app register --name httpapp --type app --uri maven://some.app:some:1.0.0.RELEASE
dataflow:>app register --name imageprocessor --type app --uri docker:sabby/image-processor:0.0.1-SNAPSHOT 
dataflow:>app register --name pyapp --type app --uri docker:sabby/pyapp:0.0.1-SNAPSHOT 

dataflow:>app list
╔══════════════╤══════╤═════════╤════╤════╗
║     app      │source│processor│sink│task║
╠══════════════╪══════╪═════════╪════╪════╣
║httpapp       │      │         │    │    ║
║imageprocessor│      │         │    │    ║
║pyapp         │      │         │    │    ║
╚══════════════╧══════╧═════════╧════╧════╝

dataflow:>stream create foo --definition "httpapp || imageprocessor || pyapp"
Created new stream 'foo'

dataflow:>stream create bar --definition "httpapp"
Created new stream 'bar'

dataflow:>stream create baz --definition "httpapp || pyapp"
Created new stream 'baz'

dataflow:>stream list
╔══════════╤═════════════════════════════════╤═══════════════════════════════════════════════════════════════════╗
║  Stream  │        Stream Definition        │                              Status                               ║
║   Name   │                                 │                                                                   ║
╠══════════╪═════════════════════════════════╪═══════════════════════════════════════════════════════════════════╣
║foo       │httpapp || imageprocessor ||     │The app or group is known to the system, but is not currently      ║
║          │pyapp                            │deployed                                                           ║
║bar       │httpapp                          │The app or group is known to the system, but is not currently      ║
║          │                                 │deployed                                                           ║
║baz       │httpapp || pyapp                 │The app or group is known to the system, but is not currently      ║
║          │                                 │deployed                                                           ║
╚══════════╧═════════════════════════════════╧═══════════════════════════════════════════════════════════════════╝

```

Hope this helps. Let us know if you have any feedback.
