### ISSUE TITLE
Unable to launch composed tasks with more than one value (csv) in composed-task-properties or composed-task-arguments

### ISSUE THREAD

**Issue by djgeary** [spring-cloud/spring-cloud-dataflow#1502]
I've raised a separate issue (https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/10) about how these properties are handled in the composed-task-runner and with the local fixes I have made to that I have the ability to pass a single item in composed-task-properties or composed-task-arguments. 

I mentioned in the other issue I was struggling to find the correct 'quote' mechanism to pass multiple (csv) values for composed-task-properties or composed-task-arguments ie I want to do something like (in the shell):
```
task launch test-compose-samplebatchtask --properties "app.composed-task-runner.composed-task-properties='app.test-compose-samplebatchtask-samplebatchtask1.app.sample-batch-task.samplebatchtask.item-count=2,app.test-compose-samplebatchtask-samplebatchtask2.app.sample-batch-task.samplebatchtask.item-count=4',app.composed-task-runner.composed-task-arguments='arg1=12,arg2=34'"`
```
But I get the error:
```
Command failed java.lang.IllegalArgumentException: Only deployment property keys starting with 'app.' or 'deployer.' allowed, got 'arg2'
```
If I change the command to use a properties file it gets further - ie I create the properties file 

```
app.composed-task-runner.composed-task-properties=app.test-compose-samplebatchtask-samplebatchtask1.app.sample-batch-task.samplebatchtask.item-count=2,app.test-compose-samplebatchtask-samplebatchtask2.app.sample-batch-task.samplebatchtask.item-count=4
app.composed-task-runner.composed-task-arguments=arg1=12,arg2=34
```

Then use
```
task launch test-compose-samplebatchtask --propertiesFile C:\\spring-cloud-dataflow-properties\\test-compose-samplebatchtask.properties
```

Now I get 
```
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Only deployment property keys starting with 'app.' or 'deployer.' allowed, got 'arg2'
```
So this time the command got to the server but there I got

```
java.lang.IllegalArgumentException: Only deployment property keys starting with 'app.' or 'deployer.' allowed, got 'arg2'
	at org.springframework.cloud.dataflow.rest.util.DeploymentPropertiesUtils.ensureJustDeploymentProperties(DeploymentPropertiesUtils.java:112) ~[spring-cloud-dataflow-rest-resource-1.2.0.RELEASE.jar!/:1.2.0.RELEASE]
	at org.springframework.cloud.dataflow.server.controller.TaskExecutionController.launch(TaskExecutionController.java:144) ~[spring-cloud-dataflow-server-core-1.2.0.RELEASE.jar!/:1.2.0.RELEASE]
```

Looking into this I think is a problem in DeploymentPropertiesUtils.parse which has been already looked at in https://github.com/spring-cloud/spring-cloud-dataflow/issues/1184 and https://github.com/spring-cloud/spring-cloud-dataflow/issues/1228 (but this was only for stream deployments?), the **entire** properties string is initially split by commas as described in the comment on the DeploymentPropertiesUtils.parse method.

In the first case this must be used somewhere in the shell, in the second case the `TaskExecutionController.launch` method contains the lines 

```
Map<String, String> propertiesToUse = DeploymentPropertiesUtils.parse(properties);
DeploymentPropertiesUtils.ensureJustDeploymentProperties(propertiesToUse);
```
which I think causes the problem making it impossible to pass values for composed-task-properties or composed-task-arguments that contain commas.

Also as I mentioned in the other issue it would be really useful to have some examples in the documentation of how to use these options.

**Comment by jvmlet** [comment]
Hello
Is there a solution or temporary workaround to pass multiple arguments via CTR `composed-task-arguments` ?

**Comment by cppwfs** [comment]
with the merge of PR https://github.com/spring-cloud/spring-cloud-dataflow/issues/1514 you can now use a properties file for comma delimited properties.  For example, if I have the following CTR definition: `task create bak --definition "AAA && BBB"`
and I launch it with the following task launch command : 
`task launch bak --propertiesFile /Users/glennrenfro/tmp/fun.props`  where the properties file contains:
```
app.bak.AAA.timestamp.format=yyyy
app.baz.AAA.csvvalues=XXX,YYY,ZZZ
```
the comma delimited list will work.
