### ISSUE TITLE
Revisit multi-binder section in the docs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1506]
As a user, I'm trying to replicate [multi-binder setup](http://docs.spring.io/spring-cloud-dataflow/docs/1.2.0.RELEASE/reference/htmlsingle/#dataflow-multiple-brokers) as described in the docs; however, I'm running into conflicting binder configurations for single-binder apps in this setup. 

**Acceptance:**
I should be able to use both single-binder and multi-binder apps in stream definitions.

**Comment by mborges-pivotal** [comment]
The workaround is to pass one binder information (preferable the one that is not the default binder used by the registered apps) as properties in the deploy step. 

The example below is processing messages from Kafka to Rabbit with Rabbit as the default binder used by all registered apps. 

**Here is the stream:**
`stream create kafka2rabbit --definition ":fooKafka > multiBinderBridge --spring.cloud.stream.bindings.output.binder=rabbit1 --spring.cloud.stream.bindings.input.consumer.headerMode=raw > :barRabbit"
`

**And here is the deployment of the stream:**
`stream deploy kafka2rabbit --properties "app.multiBinderBridge.spring.cloud.stream.defaultBinder=kafka1,app.multiBinderBridge.spring.cloud.stream.binders.kafka1.environment.spring.cloud.stream.kafka.binder.brokers=192.168.7.44:9092,app.multiBinderBridge.spring.cloud.stream.binders.kafka1.environment.spring.cloud.stream.kafka.binder.zkNodes=192.168.7.44:2181,app.multiBinderBridge.spring.cloud.stream.binders.kafka1.type=kafka"`

**Finally the stream that logs the messages:**
`stream create rabbit2log --definition ":barRabbit > log --expression='new java.lang.String(payload)'" --deploy`

**Comment by sabbyanandan** [comment]
Closing this since we already have a multi-binder section in the docs and microsite.
