### ISSUE TITLE
Improve test coverage in "dataflow-rest-client" module

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1509]
As a developer, I'd like to improve the test coverage in `dataflow-rest-client` module.

**Acceptance:**
Code coverage report indicates the improvement.

**Comment by ilayaperumalg** [comment]
Created https://github.com/spring-cloud/spring-cloud-dataflow/issues/1517 which can be addressed by adding tests for Completions operations.

Most of the `dataflow-rest-client` operations are explicitly used in `dataflow-shell-core` and testing via the `shell` indirectly tests the underlying REST client operations. If agreed, we can close this issue and only address #1517

**Comment by sabbyanandan** [comment]
Thanks for checking. If it just 1 specific issue, we could have repurposed this story. Yeah - let's close this and address #1517.
