### ISSUE TITLE
Improve test coverage in "dataflow-shell-core" module

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1510]
As a developer, I'd like to improve the test coverage in `dataflow-rest-resource` module.

Acceptance:
Code coverage report indicates the improvement.

Related stories:
- [x] #1515 
- [x] #1516

**Comment by ilayaperumalg** [comment]
Created https://github.com/spring-cloud/spring-cloud-dataflow/issues/1515 and https://github.com/spring-cloud/spring-cloud-dataflow/issues/1516 to improve the test coverage on Stream/Task/Job commands.  

While the above issues cover the major portions of the coverage, other left out commands that require tests can be covered as part of this story.

**Comment by sabbyanandan** [comment]
This is addressed via: https://github.com/spring-cloud/spring-cloud-dataflow/issues/825#issuecomment-309602034.
