### ISSUE TITLE
hateoas _links change to https

### ISSUE THREAD

**Issue by BLaurent** [spring-cloud/spring-cloud-dataflow#1512]
Hi,

The home page of the dataflow server is displaying http links even deployed in a https ready context, like CF.
Is there a way to change into https, having all href to https, will allow data flow shell to work with https only without redirection.

Thanks in advance
Ben

**Comment by sabbyanandan** [comment]
Hi, @BLaurent. Apologies for the delayed response.

The REST-APIs are unsecured by default, but you can configure the server by enabling HTTPS - see [docs](https://docs.spring.io/spring-cloud-dataflow/docs/1.2.3.RELEASE/reference/htmlsingle/#configuration-security). This should be applicable in CF as well and there is few other CF specific [authentication options](https://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.2.4.RELEASE/reference/htmlsingle/#getting-started-security). 

For any other CF specific questions, feel free to open a new issue in CF-server backlog.
