### ISSUE TITLE
Task Specific properties for CTR do not follow SCDF pattern

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#1514]
The current method of setting child app properties for a CTR launch does not match those of stream nor task.   i.e. 
```
task create foo --definition "AAA && BBB"`
task launch foo --properties "app.composed-task-runner.composed-task-properties=app.foo-AAA.app.AAA.format=yyyy"
```
it should read more like 
`task launch foo --properties "app.AAA.format=yyyy"`

**Comment by mminella** [comment]
I agree on this.  Just to be clear, we'll need to figure out how to handle the `AAA && AAA` use case as well.

**Comment by cppwfs** [comment]
In that case we can use labels.  Else it will be applied to both.

**Comment by cppwfs** [comment]
Refer to https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/12 for CTR based changes.
