### ISSUE TITLE
Improve test coverage on Stream/Task/Job commands

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1515]
As a developer, I'd like to improve the test coverage in stream and task commands (spring-cloud-dataflow-shell-core) 

Acceptance:
Code coverage report indicates the improvement.

**Comment by sabbyanandan** [comment]
The scope of this test-coverage story is complete via https://github.com/spring-cloud/spring-cloud-dataflow/issues/825#issuecomment-309602034.
