### ISSUE TITLE
Allow custom configuration for inbound/outbound destination names

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1519]
Currently, SCDF [assigns](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/StreamApplicationDefinitionBuilder.java#L88) the inbound/outbound destination names for the Stream Definition with the bound target (eg., channels)  names `input` and `output`. While this works for OOTB apps which have the bound target (eg., channels) names for inbound/outbound being `input` and `output` respectively, we also need to make it easier for users to allow configuring the inbound/outbound target names.

**Comment by sabbyanandan** [comment]
The "Streaming Application DSL" support in 1.7 will address this requirement.
