### ISSUE TITLE
Switch server version from 1.2.1.RELEASE to 1.2.2.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1520]
The local server build is at [1.2.1.RELEASE](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-local/pom.xml#L6); it needs to be at 1.2.2.BS.

**Comment by ilayaperumalg** [comment]
Not only this place, we also need to fix `spring-cloud-dataflow-dependencies` and the main POM for `dependencies` pointing to `1.2.1.RELEASE`. Hence those need to be fixed as well.
