### ISSUE TITLE
Custom Authentication using JDBC 

### ISSUE THREAD

**Issue by smajumder2017** [spring-cloud/spring-cloud-dataflow#1522]
Hi I have created one configuration to implement jdbc authentication inside spring-cloud-dataflow-server-core as i discussed with @Ilayaperumal Gopinathan he suggested me to post my issue here and i am attaching my code .

The issue is authentication is not working at all and i have no clue what is wrong with this code please check if anybody can help . Thanks in Advance

    package org.springframework.cloud.dataflow.server.config.security;
    import org.apache.tomcat.jdbc.pool.DataSource;
    import org.slf4j.LoggerFactory;
    import org.springframework.beans.factory.annotation.Autowired;
    import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
    import org.springframework.boot.autoconfigure.security.SecurityProperties;
    import org.springframework.boot.context.properties.ConfigurationProperties;
    import org.springframework.cloud.dataflow.server.config.security.support.OnSecurityEnabledAndJdbcAuthEnabled;
    import org.springframework.cloud.dataflow.server.config.security.support.OnSecurityEnabledAndOAuth2Enabled;
    import org.springframework.cloud.dataflow.server.config.security.support.SecurityStateBean;
    import org.springframework.context.annotation.Bean;
    import org.springframework.context.annotation.ComponentScan;
    import org.springframework.context.annotation.Conditional;
    import org.springframework.context.annotation.Configuration;
    import org.springframework.http.HttpHeaders;
    import org.springframework.http.MediaType;
    import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
    import org.springframework.security.config.annotation.authentication.configurers.GlobalAuthenticationConfigurerAdapter;
    import org.springframework.security.config.annotation.web.builders.HttpSecurity;
    import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
    import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
    import org.springframework.security.core.userdetails.UserDetailsService;
    import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
    import org.springframework.security.crypto.password.PasswordEncoder;
    import org.springframework.security.web.authentication.LoginUrlAuthenticationEntryPoint;
    import org.springframework.security.web.authentication.logout.HttpStatusReturningLogoutSuccessHandler;
    import org.springframework.security.web.authentication.www.BasicAuthenticationEntryPoint;
    import org.springframework.security.web.util.matcher.AnyRequestMatcher;
    import org.springframework.security.web.util.matcher.MediaTypeRequestMatcher; 
    import org.springframework.security.web.util.matcher.RequestMatcher;
    import org.springframework.web.HttpMediaTypeNotAcceptableException;
    import org.springframework.web.accept.ContentNegotiationStrategy;
    import org.springframework.web.accept.HeaderContentNegotiationStrategy;
    import org.springframework.web.context.request.NativeWebRequest;

    import java.util.Collections;
    import java.util.List;

    import static org.springframework.cloud.dataflow.server.controller.UiController.dashboard;

    @Configuration
    @ConditionalOnProperty("security.authentication.jdbc.enabled")
    @ConfigurationProperties(prefix = 
    JDBCAuthenticationConfiguration.CONFIGURATION_PROPERTIES_PREFIX)
    public class JDBCAuthenticationConfiguration extends WebSecurityConfigurerAdapter {

    public static final String CONFIGURATION_PROPERTIES_PREFIX ="security"
            + ".authentication.jdbc";
    private static final org.slf4j.Logger logger = LoggerFactory.getLogger(JDBCAuthenticationConfiguration.class);

    @Autowired
    private SecurityStateBean securityStateBean;

    @Autowired
    private SecurityProperties securityProperties;

    final RequestMatcher textHtmlMatcher = new MediaTypeRequestMatcher(new 
    JDBCAuthenticationConfiguration.BrowserDetectingContentNegotiationStrategy(),
        MediaType.TEXT_HTML);

    @Autowired
    private DataSource dataSource;

    final String loginPage = dashboard("/#/login");

   

    @Override
    public void configure(AuthenticationManagerBuilder auth) throws Exception {

         auth.jdbcAuthentication().dataSource(dataSource).usersByUsernameQuery("select username,password, enabled from users where username=?")
        .authoritiesByUsernameQuery("select username, role from user_roles where username=?");
        logger.info("JDBC Authenication Started");
        securityStateBean.setAuthenticationEnabled(true);
        securityStateBean.setAuthorizationEnabled(true);
    }
    @Override
    protected void configure(HttpSecurity http) throws Exception {

        final RequestMatcher textHtmlMatcher = new MediaTypeRequestMatcher(new JDBCAuthenticationConfiguration.BrowserDetectingContentNegotiationStrategy(),
                MediaType.TEXT_HTML);

        final BasicAuthenticationEntryPoint basicAuthenticationEntryPoint = new BasicAuthenticationEntryPoint();
        basicAuthenticationEntryPoint.setRealmName(securityProperties.getBasic().getRealm());
        basicAuthenticationEntryPoint.afterPropertiesSet();

        http.authorizeRequests()
                .antMatchers(
                        "/security/info**", loginPage, dashboard("/.html"),dashboard("*/logout*"),
                       dashboard("/scripts.**"), dashboard("/styles/**"), dashboard("/images/**"), dashboard("/fonts/**"), dashboard("/lib/**")
                ).authenticated().antMatchers(dashboard("/**"),"/authenticate", "/security/info", "/dashboard", "/features", "/assets/**" ,dashboard("/logout")).permitAll()
                .and().formLogin().loginPage(loginPage).usernameParameter("username").passwordParameter("password")

                .defaultSuccessUrl(dashboard("/")).permitAll().and()
                .logout().logoutUrl(dashboard("/logout"))
                .logoutSuccessUrl(dashboard("/logout-success.html"))
                .logoutSuccessHandler(new HttpStatusReturningLogoutSuccessHandler()).permitAll().and()

                .httpBasic().and()
                .exceptionHandling()

                .defaultAuthenticationEntryPointFor(basicAuthenticationEntryPoint, AnyRequestMatcher.INSTANCE);

    private static class BrowserDetectingContentNegotiationStrategy extends HeaderContentNegotiationStrategy {

    @Override
    public List<MediaType> resolveMediaTypes(NativeWebRequest request)
            throws HttpMediaTypeNotAcceptableException {
        final List<MediaType> supportedMediaTypes = super.resolveMediaTypes(request);

        final String userAgent = request.getHeader(HttpHeaders.USER_AGENT);
        if (userAgent != null && userAgent.contains("Mozilla/5.0")
                && !supportedMediaTypes.contains(MediaType.APPLICATION_JSON)) {

            return Collections.singletonList(MediaType.TEXT_HTML);
        }
        return Collections.singletonList(MediaType.APPLICATION_JSON);
    }
    }

    }

**Comment by sabbyanandan** [comment]
Hi, @smajumderaltimetrik. SCDF ships with traditional (e.g., basic, ldap, file-based) and OAuth security options and it is unclear why you're implementing this custom authentication layer. Can you describe the requirement and what you're trying to accomplish?

**Comment by sabbyanandan** [comment]
No response from the OP - closing it due to inactivity.
