### ISSUE TITLE
Consolidate feature toggle info from "/features" and "/about" into a single endpoint

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1526]
As a user, I'm trying to determine whether to use `/features` or `/about` endpoint to fetch feature toggle info. Both the endpoint seems to provide that and it'd be better to consolidate it under a single endpoint.

**Acceptance:**
- Remove feature toggle info from `/about` endpoint.
- Adapt UI to fetch feature toggle info from `/feature` endpoint.
- Update doc references.

**Comment by ilayaperumalg** [comment]
I believe having `features` properties served from `/about` REST endpoint is beneficial as it produces all the information **about** server including the `features`. 

If we want to move the features properties served only `/features` endpoint, then the REST client requires to make two separate requests to list values includes features properties.

**Comment by sabbyanandan** [comment]
Duplicate of spring-cloud/spring-cloud-dataflow#1753
