### ISSUE TITLE
User would to edit CTR Definition

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#1529]
User would like to add an “Edit” button to pull up the graph so user can make changes and then delete/replace the definitions on save

**Comment by sabbyanandan** [comment]
With the newly added CD support for tasks, it is now possible to evolve the CT graph with different versions for the graph nodes (aka: task apps), and their associated app/deployer/args on subsequent launches. Besides that, we haven't yet heard of someone wanting to edit the graph itself.
