### ISSUE TITLE
Stop an executing CTR application from shell

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#1530]
User wants the ability to stop a composed task in the shell.

**Comment by cppwfs** [comment]
Should the be in the form of job execution stop?  
Or should it be task execution stop?  If so then it either needs to be CTR specific (i.e. checks to see if task is a CTR).  Else all deployers will need to support a task stop command.

**Comment by sabbyanandan** [comment]
This might be covered via https://github.com/spring-cloud/spring-cloud-dataflow/issues/858.

**Comment by sabbyanandan** [comment]
We have the ability to stop it from the Dashboard. When we attempt at #858, we can revisit if something special needs to be done for CTs. As a standalone CT command won't be necessary, though.
