### ISSUE TITLE
Common Application Properties for tasks does not work

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#1531]
In this case when attempting to set the dataflowServerUri.
Works using properties i.e. task launch foo --properties "app.composed-task-runner.dataflowServerUri=http://bar" 
Works using properties.
But setting it with java -jar spring-cloud-dataflow-server-local/target/spring-cloud-dataflow-server-local-1.2.2.BUILD-SNAPSHOT.jar --spring.cloud.dataflow.applicationProperties.task.dataflowServerUri=http://foo.bar does not work.

**Comment by cah-ricksuggs** [comment]
I'm also experiencing the issue. Followed the instructions here: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_common_application_properties

Using spring-cloud-dataflow-server-cloudfoundry-1.2.4.RELEASE.jar
