### ISSUE TITLE
How to use mongoDB as sink, and what version of MongoDB server to have for it

### ISSUE THREAD

**Issue by prigya** [spring-cloud/spring-cloud-dataflow#1533]

**Comment by sabbyanandan** [comment]
Hi, @prigya. Please consider opening application specific issues in the respective repos. In this case, new feature requests and bugs should be reported in [mongodb](https://github.com/spring-cloud-stream-app-starters/mongodb/issues) repo. More details about the dependencies [here](https://github.com/spring-cloud-stream-app-starters/mongodb/blob/master/spring-cloud-starter-stream-sink-mongodb/pom.xml).

[StackOverflow](https://stackoverflow.com/questions/tagged/spring-cloud-dataflow) is a great avenue for questions like this.
