### ISSUE TITLE
Ensure REST endpoints are wired-up for infrastructure-controllers

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1536]
Controllers to check:
 - [x] AboutController.java
 - [ ] ~ToolsController.java~ (not part of the 'public' REST API)
 - [ ] ~FeaturesController.java~ (deprecated)
 - [x] RootController.java
 - [x] MetricsController.java

See https://github.com/spring-cloud/spring-cloud-dataflow/issues/825 for more details.

**Comment by ericbottard** [comment]
All controllers in this list meant to be documented are now documented
