### ISSUE TITLE
Ensure REST endpoints are wired-up for apps-controllers

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1537]
Controllers to check:

 - [x] RuntimeAppsController.java
 - [x] AppRegistryController.java

See https://github.com/spring-cloud/spring-cloud-dataflow/issues/825 for more details.

**Comment by ericbottard** [comment]
Added second part in https://github.com/spring-cloud/spring-cloud-dataflow/pull/1554

**Comment by jvalkeal** [comment]
ah ok, didn't pay attention when closing.
