### ISSUE TITLE
Ensure REST endpoints are wired-up for jobs-controllers

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1538]
Controllers to check:

 - [ ] JobExecutionController.java
 - [ ] JobInstanceController.java
 - [ ] JobStepExecutionController.java
 - [ ] JobStepExecutionProgressController.java

See https://github.com/spring-cloud/spring-cloud-dataflow/issues/825 for more details.

**Comment by cppwfs** [comment]
Broke up this story into the following stories:
#1601
#1602
#1603
#1604

**Comment by cppwfs** [comment]
Broke up this story into the following stories:
#1601
#1602
#1603
#1604
