### ISSUE TITLE
Add "stream update" command in shell

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#154]
As a user, I'd like to have direct shell commands to scale up/down a given module instance, so I can avoid SPI specific CLI commands that needs run outside of data flow.

**Acceptance:**
- `stream update ticktock --properties "app.log.count=3"`as a new command is available for use; where:
  - `--properties` relates to general set of properties applicable for the stream definition 
  - `app.log.count` relates to instance-count representation for the `log` application
- Upon execution of this command, I'm able to scale the log application to `3` instances

**Comment by kdunn-pivotal** [comment]
I'm very interested in this functionality as well. It'd be great to have control at create/deploy time how to allocate resources to a given stream.

**Comment by styjdt** [comment]
Are there any updates on this topic?

**Comment by sabbyanandan** [comment]
@styjdt: We are discussing the core design to scale apps up/down at the core deployer SPI level via spring-cloud/spring-cloud-deployer#57.

**Comment by sabbyanandan** [comment]
This depends on spring-cloud/spring-cloud-dataflow#583.
