### ISSUE TITLE
Upgrade to SCT 1.2.1 GA

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1547]
As a developer, I'd like to upgrade SCT dependency to 1.2.1.

**Comment by trisberg** [comment]
I don't see a SCT 1.2.1.BUILD-SNAPSHOT build in the repo, is 1.2.1 the correct version? @mminella

**Comment by sabbyanandan** [comment]
1.2.1 is the correct version; however, we need to release SCDe and SCDe-Local - SCT _requires_ it.

**Comment by trisberg** [comment]
There are 1.2.1.BUILD-SNAPSHOT builds of these projects to use for now until we release them
