### ISSUE TITLE
Add official support for OpenShift

### ISSUE THREAD

**Issue by Chnoch** [spring-cloud/spring-cloud-dataflow#1553]
OpenShift is being used more and more in public and private clouds by many enterprises. It would be great if Spring Cloud Dataflow would provide official support for its Server and Deployer for OpenShift. 

For the Spring Cloud Dataflow Server an unofficial version supporting OpenShift can be found here: https://github.com/donovanmuller/spring-cloud-dataflow-server-openshift

Also see https://github.com/spring-cloud/spring-cloud-deployer/issues/222

**Comment by sabbyanandan** [comment]
We don't have any plans to support it directly, but the community repo should be able to help you out. If there's a need in Core/Deployer to support for any primitives in OpenShift, please do let us know.
