### ISSUE TITLE
Update Travis CI to start with "sudo: required"

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1558]
As a developer, I'd like to update Travis CI to start with [`sudo: required`](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/.travis.yml#L1). 

Given that we have a paid account, the new environment (+ resources) might not kick-in unless we set this flag. See more details [here](https://docs.travis-ci.com/user/ci-environment/). 

**Acceptance:**
Re-run CI build after the modification.

**Comment by ericbottard** [comment]
Build seems to pass now :)
