### ISSUE TITLE
Deployed streams don't redeploy when the server restarts

### ISSUE THREAD

**Issue by bericoberin** [spring-cloud/spring-cloud-dataflow#1564]
Found in SCDF local server 1.2.1.RELEASE in a docker linux image using H2 database persisted to file system.

**Steps to reproduce:**

* Set up SCDF Server to use persistent configuration database (H2 to file system is OK)
* Configure stream, and deploy it
* Confirm the stream is working
* Stop server
* Start server
* Confirm the stream is not working

Even though the deployments table has data in it, it is not read at server initialization to see if it should redeploy.

At this point, if you go to the management console (or the SCDF shell) and deploy the stream again, you see duplicate key errors in the SCDF server logs.  The stream does deploy again after manually starting it.

**Expected behavior:**

After SCDF server initializes itself, it checks its deployments table and redeploys all the streams that were deployed at the time it shut down.

Also, no duplicate key errors.

**Comment by sabbyanandan** [comment]
Hi, @bericoberin. To be clear, we _do not_ recommend local-server for production deployments. It is strictly meant to be used _only_ in the incremental development phases. For production deployments, we recommend cloud foundry, kubernetes, yarn, or mesos. 

**Background:**

When you deploy a stream in SCDF, it is left to the target platform for lifecycle management. 

For example, if you deploy a stream in SCDF running on Cloud Foundry, even when the SCDF-server crashes or (manually) restarted, the stream apps continue to run. In this case, it is Cloud Foundry's responsibility to reliably run those apps regardless of the SCDF-server condition. 

Upon restart of the server, when you issue `stream list` in shell, the SCDF-server will query the latest status based on the persisted stream definitions and everything will operate as normal.
