### ISSUE TITLE
StreamNode toString does not showAccurate stream desl

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#1568]
currently when using the toString from the StreamNode it does not show an accurate representation of the stream.
1) the quoted values from properties are missing quotes .
i.e. `--foo='bar'` shows up as `--foo=bar `
2) the : in front of destination is missing i.e.
`> :foobar` shows up as `>foobar`

**Comment by cppwfs** [comment]
For issue #2.  Just update the DestinationNode. toString to read as follows:
```
 	@Override
  	public String toString() {
 		return ":" + getDestinationName();
  	}
```

**Comment by olegz** [comment]
It appears that the missing quotation issue is no longer present. PR will include test.
