### ISSUE TITLE
Fix Windows CI plan

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1586]
As a developer, I'd like to add a CI plan on Windows to continuously build and test the incremental commits.

**Acceptance:**
New CI plan listed under the [SCD project](https://build.spring.io/telemetry.action?filter=project&projectKey=SCD) in Bamboo and the tile page lists it.

**Comment by sabbyanandan** [comment]
@jvalkeal: The build seems to be still failing -> https://build.spring.io/browse/SCD-DEPMASTERWIN.

**Comment by jvalkeal** [comment]
@sabbyanandan streams and tasks run fine with local server when I tried those manually. Looks like we have two issues in CI
1. `testCommandLineArgumentsPassing` in streams fails which tests escaping. 
```

**Comment by jvalkeal** [comment]
It may be that `The directory name is invalid` comes if tmp path to get created is too long as `C:\Windows\system32\config\systemprofile\AppData\Local\Temp\SCD-DEPMASTERWIN-JOB1\spring-cloud-dataflow-4835351652475189815\testReLaunch-b9e79e59-fc6f-49eb-b152-a1508dc208f3-1500189166361\testReLaunch-b9e79e59-fc6f-49eb-b152-a1508dc208f3-6cafa69f-9a43-4c09-9760-bf3e31dfd648` is 275 and I event get error from command like with `mkdir` if path is longer than 248 chars.

**Comment by sabbyanandan** [comment]
@jvalkeal: According to @trevormarshall, we have a [Boot 2.0 plan](https://build.spring.io/build/admin/edit/editBuildTasks.action?buildKey=BOOT-WIN-JOB1) that runs on Windows successfully. However, this plan runs on Maven 3.2 and we are on 3.5 - perhaps there's something here to dig.

**Comment by trevormarshall** [comment]
I also suspected path length at first glance. Found some notes from Atlassian on running the service as the local user and have put that in place as well. 
https://confluence.atlassian.com/bamboo/running-bamboo-as-a-windows-service-as-the-local-user-416580754.html

**Comment by sabbyanandan** [comment]
@jvalkeal: With your recent fix to local-deployer [spring-cloud/spring-cloud-deployer-local#71] and a successful build of that project on Windows [[SCD-DEPMASTERWIN](https://build.spring.io/browse/SCD-DEPMASTERWIN)], I kicked-off the local-server build, but it _still_ seems to fail on Shell tests [[SCD-BMASTERWIN-JOB1-6.log](https://build.spring.io/download/SCD-BMASTERWIN-JOB1/build_logs/SCD-BMASTERWIN-JOB1-6.log)].

**Comment by jvalkeal** [comment]
I removed this from `1.2.3.RELEASE` as per https://build.spring.io/browse/SCD-BMASTERWIN/latest some more work has to happen with shell tests.

**Comment by sabbyanandan** [comment]
We have disabled this from Bamboo. More importantly, we have moved to the Git Actions + Workflows to build the project on each commit anyway.
