### ISSUE TITLE
Add support to load Hadoop distribution of choice

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#160]
As a s-c-d user, I'd like to have the option to choose Hadoop distribution of choice, so I can load the right Hadoop libraries in the CP.

**Acceptance:**
* *--hadoopDistro* is an available option to bootstrap *admin* with right Hadoop distribution libraries (will likely be *--include hadoop-phd30* when defining module)
* create BOMs for the major distributions we would want to support
* Integration tests included

**Comment by trisberg** [comment]
See https://github.com/trisberg/spring-cloud-dataflow-library for implementation suggestion. We should create a new `spring-cloud-dataflow-library` repo for this, I think.

**Comment by trisberg** [comment]
Library can be registered using:

```
module register --type library --name mybom --coordinates 'org.springframework.cloud.dataflow.library:hadoop-phd30:pom:1.0.0.BUILD-SNAPSHOT'
```

and then utilized in a stream like:

```
stream create hdfs-with-lib --definition "time | hdfs --includes='hadoop-phd30' --fsUri=hdfs://hawaii:8020 --directory=/tmp/test" --deploy
```

**Comment by trisberg** [comment]
We discussed keeping this in the current repo for now, and adding the pom files manually to the Spring repo milestone lib when we release M2

**Comment by sabbyanandan** [comment]
@trisberg: Let's mark this as done. We will address the module resolution along with relevant Hadoop distro inclusion via: spring-cloud/spring-cloud-dataflow#211.
