### ISSUE TITLE
registering a custom app jar giving gitHub link, but it fails to deploy

### ISSUE THREAD

**Issue by prigya** [spring-cloud/spring-cloud-dataflow#1605]
i'm registering a custom app jar giving gitHub  link, but it fails to deploy as SCDF caches it as metadata file and not as jar.

**Comment by sabbyanandan** [comment]
Hi, @prigya. Thanks for trying out! However, the issue does not include any details. If you could share some background based on the questions listed in this [wiki link](https://github.com/spring-cloud/spring-cloud-dataflow/wiki/Reporting-Issues), it might help troubleshoot it.

**Comment by sabbyanandan** [comment]
Closing this since we haven't heard back from the reporter.

**Comment by prigya** [comment]
updating on this issue :  i was probably giving a incorrect url link for the github jar, hence metadata file was getting downloaded and not the jar itself. Once i gave correct jar path on github ( i.e. the download link of the jar) ..it worked perfectly fine ! Thanks !
