### ISSUE TITLE
Update to Spring Cloud Dalston.SR2

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1610]
As a developer, I'd like to update the base Spring Cloud version to Dalston.SR2.

**Comment by trisberg** [comment]
Spring Cloud Dalston.SR2 depends on Spring Cloud Build 1.3.3.RELEASE which uses Boot 1.5.4.RELEASE. So, not sure we should bump the Boot version yet. @sabbyanandan @markpollack 

We might just want to bump to Dalston.SR2

**Comment by sabbyanandan** [comment]
Ah! In that case, let's just stick with 1.5.4 via Dalston.SR2.
