### ISSUE TITLE
App startup shouldn't require database is available

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1615]
When starting the server it connects and initializes the database. It would be better to only do this when the database is accessed the first time since in some deployments the database isn't necessarily fully available when the app starts but will be once it is accessed at a later point.

**Comment by cppwfs** [comment]
Just a thought. Wouldn't it be better to add code that will allow SCDF to  wait until the database is up before continuing startup?  It could confuse the user to see an available SCDF that fails as soon as they interact with it.

**Comment by sabbyanandan** [comment]
With SCDF v2.0 the DB requirement in SCDF and Skipper have evolved significantly. Now, we rely on Flyway to create the schemas at the startup time, so we do _require_ the DB more strictly now.
