### ISSUE TITLE
Add 1.2.x CI plan

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1616]
As a developer, I'd like to add a new CI plan for 1.2.x branch. 

**Acceptance:**
- `master` switched to `1.3.0.BUILD-SNAPSHOT`
- a new CI plan covers 1.2.x branch

**Comment by ilayaperumalg** [comment]
CI build plan is created: https://build.spring.io/browse/SCD-SCDF12X/ for the newly created branch `1.2.x`
