### ISSUE TITLE
Add search parameter to AppRegistryController.list()

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#1617]
Currently the `AppRegistryController` does not have the ability to filter the results. We should add the `search` parameter similar to the `StreamDefinitionController`.

**Comment by jvalkeal** [comment]
At a same time we should add filtering by dedicated fields as well, not just arbitrary search string which I never know what it does unless I go to sources. As we're probably getting a change to do column level filtering in UI it'd be nice if you can filter by name, type, uri, etc.

**Comment by jvalkeal** [comment]
What I mean is something i.e. outlined in http://www.baeldung.com/rest-api-search-language-spring-data-specifications
