### ISSUE TITLE
Add "runtime modules" shell command

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#162]
As a s-c-d user, I'd like to have *runtime modules* as shell command, so I can use this to list the details about the modules.

**Acceptance:**
Using *runtime modules* command in shell lists SPI agnostic module info

**Comment by ilayaperumalg** [comment]
Fixed in a170ed02213f0ac6d8d45948e9fcf0bf8190af37 via https://github.com/spring-cloud/spring-cloud-dataflow/pull/136
