### ISSUE TITLE
Move Java DSL bits from acceptance-tests project to SCDF

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-dataflow#1620]
Currently acceptance-tests project provides a Java DSL capable of constructing and executing the flow. The DSL itself may be useful to an everyday developer, since it would allow them to create, modify and execute flows without leaving their IDE. Further more it could also provide for a versioned artifact that represents executable flow as well as an artifact that could allow deployment options (local vs PCF) to be managed via configuration.

**Comment by sabbyanandan** [comment]
Depends on spring-cloud/spring-cloud-dataflow-acceptance-tests#121.

**Comment by viniciusccarvalho** [comment]
@markpollack Preliminary 
```java
Stream stream = Stream.Builder()
    .name("ticktock")
    .definition("time | log")
    .addProperty("key", "value")
    .addProperty("key", "value")
    .deploy() // wraps the builder returns the stream and invokes deploy on DataFlowTemplate

stream.status(); //Displays status of this stream
stream.undeploy();
stream.destroy();
```

Those were the simples mappings I figured we could add, I wonder if there's value on returning a `StreamDefinition` object if instead of `deploy()` the user invokes `register()`, thoughts?
