### ISSUE TITLE
Configure a new release process

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#1624]
We need to come up with a new release process, the current one using BinTray is sooo broken.

We should be able to build and release directly to Maven Central from a CI build instance.

**Comment by sabbyanandan** [comment]
The current Bamboo->Central model has been working for us for a while now. We have plans to switch to Spring Cloud release process, which builds on automation performed through Jenkins.

**Comment by sabbyanandan** [comment]
This is old and is not applicable anymore.
