### ISSUE TITLE
springboot admin Couldn't retrieve info for Application 

### ISSUE THREAD

**Issue by qq494679975** [spring-cloud/spring-cloud-dataflow#1632]
spring-boot-admin version 1.5.3 release
spring-cloud-dataflow-server-local   1.2.0 release
i use  @EnableDataFlowServer start , dataflow-server  register eureka success,but admin server Couldn't retrieve info for Application 

i set the config in my dataflow-server projet but it no work

endpoints:
  enabled: true   
  sensitive: false

**Comment by sabbyanandan** [comment]
Hi, @qq494679975. By following Spring Boot Admin (SBA) [guidelines](https://codecentric.github.io/spring-boot-admin/1.5.3/#set-up-admin-server), you should be able to make SCDF a [client](https://codecentric.github.io/spring-boot-admin/1.5.3/#register-clients-via-spring-boot-admin) to the SBA server just by adding `spring-boot-admin-starter-client` dependency. You'd then need to point to where SBA is running via `spring.boot.admin.url` property. 

It is unclear how you prepped this in your environment.

I've tried the 1.3.0.BUILD-SNAPSHOT of SCDF with SBA 1.5.3.RELEASE and everything appear to be working as expected. I will close this for now and based on your experiments, if you still see any other anomaly, please reopen with more details.
