### ISSUE TITLE
REST - Provide more user-friendly HTTP response in case of a Redis Failure 

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#1636]
Right now we return a `500` HTTP status when accessing the metrics endpoint with an off-line Redis instance. 

```
curl "http://localhost:9393/metrics/counters?page=0&size=10&detailed=true"
```

Resulting in:

```
    [
        {
            "logref": "RedisConnectionFailureException",
            "message": "Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool",
            "links":
            [
            ]
        }
    ]
```

We may decide that this is appropriate, but I thought a `500` error is a bit drastic, as Redis is analytics-specific and less critical. SCDF will run otherwise normal without Redis.

Would maybe returning a `503 Service Unavailable` combined with a more refined error message the better choice?

**Comment by sabbyanandan** [comment]
Since in v2.0, Redis is removed and not a dependency for SCDF anymore, I'm closing this as invalid.
