### ISSUE TITLE
For `metrics/counters` REST endpoint - standardize collection name for JSON response

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#1639]
A simple parameter change should not cause the JSON response to be structurally different. For the `metrics/counters` REST endpoint we return either *metricResourceList* or *counterResourceList* as the collection name just because the `detailed` parameter is either `true` or `false`.

`http://localhost:9393/metrics/counters?detailed=false`

Returns:

```json
{
    "_embedded":
    {
        "metricResourceList":
        [
            {
                "name": "glenncount11",
                "_links":
                {
                    "self":
                    {
                        "href": "http://localhost:9393/metrics/counters/glenncount11"
                    }
                }
            },
            {
                "name": "glenncount12",
                "_links":
                {
                    "self":
                    {
                        "href": "http://localhost:9393/metrics/counters/glenncount12"
                    }
                }
            },
...
```

`http://localhost:9393/metrics/counters?detailed=true`

Returns:

```json
{
    "_embedded":
    {
        "counterResourceList":
        [
            {
                "name": "glenncount11",
                "value": 9359,
                "_links":
                {
                    "self":
                    {
                        "href": "http://localhost:9393/metrics/counters/glenncount11"
                    }
                }
            },
            {
                "name": "glenncount12",
                "value": 9360,
                "_links":
                {
                    "self":
                    {
                        "href": "http://localhost:9393/metrics/counters/glenncount12"
                    }
                }
            },
...
```

**Comment by jvalkeal** [comment]
This is actually coming from `org.springframework.analytics.rest.controller.CounterController` in `spring-analytics` as detailed just uses different hal `ResourceAssembler`. Just looking how it's actually done, it doesn't make no sense to even use that detailed parameter as metric value is still queried from repository but it's not shows(thus using different model).

**Comment by jvalkeal** [comment]
@ghillert for now you should only use `metrics/counters?detailed=true` as that controller in analytics is just wrongly designed. Not sure if it has any other uses other than us but it is a breaking change there.

**Comment by jvalkeal** [comment]
@sabby I'm closing this as I created new issue to spring-analytics.
