### ISSUE TITLE
Add direct binding support for DSL and Shell 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#164]
As an s-c-d user, I'd like to directly bind stream modules, so I can allow co-located contiguous modules to communicate directly instead of a remote transport.

**Acceptance:**
- DSL / Shell support to directly bind modules is included in the deployment manifest
- Documentation on direct binding with samples is available in the reference guide

**Comment by mbogoevici** [comment]
I don't think that we have support for this at DSL level yet though, or do we?

**Comment by sabbyanandan** [comment]
@mbogoevici: You're correct; this is a new feature. Updated the issue to reflect new feature in scope.

**Comment by sabbyanandan** [comment]
[Aggregate apps](http://docs.spring.io/spring-cloud-stream/docs/current-SNAPSHOT/reference/htmlsingle/#_aggregation) is our solution to this situation. This is not applicable anymore.
