### ISSUE TITLE
Verify restarability of a composed task

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1644]
As a user, when I re-run a composed task that was "stopped" previously, it re-runs the entire task from the beginning, but not from where it was stopped. 

**Acceptance:**
The scope is to test and verify whether a stopped composed-task re-runs from where it got cut off.

**Comment by sabbyanandan** [comment]
I tried a quick experiment with 2 Tasks (`timestamp` and a custom `error` app - see below) with the CTR. 

Error App:
```
        public JobParameters getNext(JobParameters parameters) {
		if (parameters == null || parameters.isEmpty()) {
			logger.info("First time launching!");
			return new JobParametersBuilder().addLong("run.id", 1L).toJobParameters();
		}
		long id = parameters.getLong("run.id", 1L) + 1;
		logger.info("Incremented by 1; value = " + id);
		return new JobParametersBuilder().addLong("run.id", id).toJobParameters();
	}

	@Bean
	public Job job1() {
		return jobBuilderFactory.get("job1")
				.incrementer(new ErrorApplication())
				.start(stepBuilderFactory.get("job1step1")
						.tasklet(new Tasklet() {
							@Override
							public RepeatStatus execute(StepContribution contribution, ChunkContext chunkContext)
									throws Exception {
								logger.info("Job1 was run");
								return RepeatStatus.FINISHED;
							}
						})
						.build())
				.build();
	}

	@Bean
	public Job job2() {
		return jobBuilderFactory.get("job2")
				.incrementer(new ErrorApplication())
				.start(stepBuilderFactory.get("job2step1")
						.tasklet(new Tasklet() {
							@Override
							public RepeatStatus execute(StepContribution contribution, ChunkContext chunkContext)
									throws Exception {
								logger.info("Job2 was run");
								throw new IllegalStateException("NO LUCK!");
							}
						})
						.build())
				.build();
	}
```

DSL:
> foo = `timestamp && error`

Graph:
![image](https://user-images.githubusercontent.com/1562654/59276844-effb4580-8c13-11e9-8e5d-4e04fb82429c.png)

---

Notes:
1) The initial launch successfully launched 1. CTR 2. Timestamp 3. Error apps
2) As expected, 3rd app failed (throws an exception and it gives up)
3) I tried restarting the entire `foo` Job execution from the Dashboard; it reported error stating that `foo` is in "complete" state, so it cannot be restarted. The `foo` Task shows up as `Complete` also. Shouldn't `foo` include the aggregate status of all the jobs and its steps? When I expand to review the Job stats of `foo`, I see:

![image](https://user-images.githubusercontent.com/1562654/59277336-e45c4e80-8c14-11e9-98ef-b8f4b7b5eae5.png)

---

Further drilling into the Job executions, I see:

![image](https://user-images.githubusercontent.com/1562654/59277484-25546300-8c15-11e9-9501-95c9f71be56d.png)

---

Here, I see the failed job, and I restarted the failed execution (jobs in `error` app also implement `JobParametersIncrementer`, so they restart without running into jobparam being unique):

![image](https://user-images.githubusercontent.com/1562654/59277611-5df43c80-8c15-11e9-8408-3792ee11a988.png)

If we clarify, (3) bullet from above, we can then close this issue.

**Comment by sabbyanandan** [comment]
@cppwfs @mminella : ^^ Thoughts?

**Comment by cppwfs** [comment]
First we have to understand that the Error app actually completed successfully.   
Confusing right :-)
In Spring Boot just because a job fails during a batch execution the batch execution is still successful.  Meaning the batch ran successfully, it just happened that one of the jobs failed.   Thus since the batch execution was successful, the exit code of the application is zero.  
And since the the timestamp and error app returned a 0 exit code CTR considers the execution as a success.   
To have an application return a 1,  if one of the jobs fails you will need to set the `spring.cloud.task.batch.fail-on-job-failure` to true for the error app.   As discussed here: https://docs.spring.io/spring-cloud-task/docs/current/reference/htmlsingle/#batch-failures-and-tasks

**Comment by sabbyanandan** [comment]
It didn't work as expected - I still see it as `COMPLETE`. App -> https://github.com/sabbyanandan/error -- I tried it in Local (2.2 BS).

**Comment by sabbyanandan** [comment]
Actually, I take it back. I was on an old SCT release (2.0 BS) as opposed to 2.1 stack. I believe the `spring.cloud.task.batch.fail-on-job-failure` property was added in 2.1 and onwards. 

Anyway, on the latest stack, I see this:

![image](https://user-images.githubusercontent.com/1562654/59288518-d3b5d380-8c28-11e9-85b5-f672114f9078.png)

The overall Job/Task execution status is failed as expected. And, I can restart from this root execution instead of finding the particular Job execution that failed.
