### ISSUE TITLE
Document the available options for Maven "update-policy"

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1658]
As a user, I'd like to know all the `update-policy` options applicable for maven artifacts. Perhaps we could point to this link [here](https://maven.apache.org/ref/3.5.0/maven-artifact/apidocs/org/apache/maven/artifact/repository/ArtifactRepositoryPolicy.html)?

The current [docs](https://docs.spring.io/spring-cloud-dataflow/docs/1.3.0.M2/reference/htmlsingle/#getting-started-maven-configuration) on this subject only point to the steps to override.

**Comment by ilayaperumalg** [comment]
@sabbyanandan We need to refer to the aether repository policies instead of Maven core, though both align.

**Comment by sabbyanandan** [comment]
@ilayaperumalg: Thanks for the clarification.
