### ISSUE TITLE
Metrics REST structure inconsistent

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#1662]
We provide `3` metrics REST endpoints that produce inconsistent collection node names:

- `/metrics/counters` - Collection Node: `metricResourceList`
- `/metrics/field-value-counters` - Collection Node: `metricResourceList`
- `/metrics/aggregate-counters` - Collection Node: `aggregateCounterResourceList`

Either, we make all of them use `metricResourceList` (`aggregate-counters`being the odd one) or each node should have a metric-specific name.

**Comment by sabbyanandan** [comment]
All the things re: Analytics have been deprecated and removes in SCDF v2.0.
