### ISSUE TITLE
DataFlowClientException (Failed to resolve MavenResource) on all Stream Application Starter sinks when running in PCF

### ISSUE THREAD

**Issue by ritceynoah** [spring-cloud/spring-cloud-dataflow#1664]
I am running the Cloud Foundry 1.2.4.RELEASE version of Data Flow server on an instance of PCF Dev, and trying to make a simple stream (e.g. "http | log") using the Stream Application Starters. I have tried each bit.ly link given on https://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#spring-cloud-dataflow-register-stream-apps separately, and each time I try to deploy my streams I get an error similar to the following:

Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Failed to resolve MavenResource: org.springframework.cloud.stream.app:jdbc-sink-rabbit:jar:1.0.4.RELEASE. Configured remote repositories: : none

I have tried several different starter sinks (log, file, jdbc...) and they all seem to be giving me this same error. I tried the same thing on local server and it works fine.

**Comment by vivekd-see** [comment]
I am facing the similar issue for the PCF deployed apps. I see that you closed this issue... Could you please share the resolution?

Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Failed to resolve MavenResource: org.springframework.cloud.stream.app:time-source-rabbit:jar:1.3.1.BUILD-SNAPSHOT. Configured remote repository: : [repo1]

**Comment by ritceynoah** [comment]
It ended up being that I had not properly configured my remote repositories link in my properties file (or, in the ENV variables, if you do it that way).  

i.e. cf set-env <server-name> MAVEN_REMOTE_REPOSITORIES_REPO1_URL https://repo.spring.io/libs-snapshot (or whatever other repository/version of the repository you choose)

I also had the same error when the version of my repository did not match the version of the apps I was trying to add to my server.
