### ISSUE TITLE
UI regression 1.2.3 -> 1.3.0.M2

### ISSUE THREAD

**Issue by pawelantczak** [spring-cloud/spring-cloud-dataflow#1666]
Hello.

While on ```1.2.3``` UI looks and works like it should,
on ```1.3.0.M1``` some resources (styles?) are missing causing UI rendering issues.
![screenshot 2017-09-28 12 40 09](https://user-images.githubusercontent.com/171534/30962641-d7c5bf3e-a44a-11e7-9cd6-a166a35f794f.png)
![screenshot 2017-09-28 12 39 04](https://user-images.githubusercontent.com/171534/30962645-dca50ef6-a44a-11e7-9a96-c62076c77923.png)

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#499
