### ISSUE TITLE
Subtasks are created even when overall task definition is invalid

### ISSUE THREAD

**Issue by DanielJonesEB** [spring-cloud/spring-cloud-dataflow#1669]
Version: 1.2.4.RELEASE
What happens: Subtasks are created, and parent is not
What should happen: When an overall task definition is invalid, subtasks should not be created
Repro steps: 

1. In SCS: task create --name foo --definition "app1 && app2 'COMPLETED' -> $END"
2. Observe error message that no app called $END is registered
3. In SCS: task list
4. Observe foo-app1 and foo-app2 in list

**Comment by cppwfs** [comment]
closed by accident

**Comment by cppwfs** [comment]
Investigate using https://github.com/spring-projects/spring-retry to handle failed creation scenario.
