### ISSUE TITLE
Create easy to use distribution scripts to start admin and shell Boot applications

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#167]
As a user, I'd like to have shortcut scripts to start `admin` and `shell` applications, so I don't have to run `java -jar` on each of the artifacts.

**Comment by ericbottard** [comment]
What exactly are we trying to do here?
Contrary to XD, we don't have a 'dist' zip produced artifact (yet?)

The various admin jars, as well as the shell jar are boot über jars already.
We could make them truly executable via http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/deployment-install.html#deployment-install

**Comment by sabbyanandan** [comment]
We have versioned server and shell apps that are available for download from spring repo and maven central. That's the extent we would want to support.
