### ISSUE TITLE
Spring Data Flow Server Get Application List Pagination Not Working

### ISSUE THREAD

**Issue by siddheshtoraskar** [spring-cloud/spring-cloud-dataflow#1676]
When app listing endpoint is requested with paging parameters(page&size), these parameters are not considered, and full list returns every time. Response is always the same as no paging parameters are used.

Example case: To get 3rd app, page=2 and size=1 params are used:

Example request url: http://localhost:9393/DataFlowServer/**api/apps**?page=2&size=1

[Actual Result]: 7 list items (total app count for now), page object params size=0, number:0

[Expected Result]: 1 list item(3rd item), page object params size=1, number:2

**Comment by sabbyanandan** [comment]
Once we have more details, we can review it on our side - closing it for now.
