### ISSUE TITLE
Record stream deployments

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1681]
As a developer, I'd like to establish the core schema changes to persist stream deployments.

**Comment by markpollack** [comment]
Implement StreamDeploymentRepository using Spring Data.
------------------------------------------------------

CREATE TABLE STREAM_DEPLOYMENT  (
	STREAM_NAME VARCHAR(255) NOT NULL PRIMARY KEY,
	DEPLOYER_NAME VARCHAR(255)  NOT NULL
);

@Entity("STREAM_DEPLOYMENT")
public class StreamDeployment {

}

**Comment by markpollack** [comment]
Also should record the package name and release name that was used for the generated package that got created.  This will be needed later in upgrade commands.

**Comment by markpollack** [comment]
Should also record the repository name that was used when deploying.
