### ISSUE TITLE
Expose repository name and package version when deploying using skipper

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1686]
May want to only have these options when using `stream deploy` and not `stream create` , otherwise the stream create command gets too many options related to deployment.

The hardcoded package version (1.0.0) and repository name (local) used when deploying at stream creating time can maybe used and make configurable for `stream create`

**Comment by ilayaperumalg** [comment]
We need to address the similar thing at `stream update` as well.

**Comment by markpollack** [comment]
This looks like a way we can support stream topology changes, but it is a pretty advanced case and prob will confuse folks at the M1 level.   I can see us doing something like this.

```
 
s1 = time | filter | filter | hdfs
s1 deploy
s2 = time | flter |hdfs
stream export s2
skipper upload --package-name s2-exported --package-version=2.0.0
stream update --releaseName foo --packageName s2-exported package-version=2.0.0```
