### ISSUE TITLE
Support configurable prefix for release name when deploying stream using Skipper

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1688]
Currently, we set `my` as the prefix to the `streamName` for the release name when deploying the stream using Skipper. We need a configurable property for this prefix.

**Comment by ilayaperumalg** [comment]
This property should be aligned with the client side as well. For instance, `stream update` uses `releaseName` to create the StreamUpdateRequest.

**Comment by markpollack** [comment]
I don't understand the previous comment.  Maybe the default should be `scdf-` ?

**Comment by ilayaperumalg** [comment]
What I meant there was if we make a configuration property for the skipper release name prefix at the server side, the same needs to be brought to the shell side as well.

Now on a second thought, I think we may not need server-side property and just a prefix as a shell option. 

But, sticking to `scdf-` as the prefix would be a better option for now as well.
