### ISSUE TITLE
Spring Cloud Task can not wok on SCDF Kubernetes

### ISSUE THREAD

**Issue by larrying** [spring-cloud/spring-cloud-dataflow#1695]
i use SCDF Kubernetes Server to deploy the Spring Cloud Task. When i launch the Spring Cloud Task on SCDF Kubernetes Server,i find two strange problems, see below detail:

1. when deploying the Spring Cloud Task,the Pod with arguments will be produced on Kubernetes.  the problem is that arguments of the Pod can not pass to the Spring Cloud Task.

2. when i launch the Spring Cloud Task,if i want to add some properties that the format is app.mytask.test=aaa,i find the property can not pass to Spring Cloud Task, and even override all arguments.

am i missing something?,or bugs? please give me some advises, thanks

**Comment by dturanski** [comment]
It seems to be working fine. Answered here: https://stackoverflow.com/questions/46740197/spring-cloud-task-can-not-wok-on-scdf-kubernetes/46749533#46749533
