### ISSUE TITLE
Add support to specify platform name for stream deploy/update

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1698]
Currently, platform name for install/update requests is set to `default` which is for `local` app deployer. We need to get the `platform-name` option from the client.

**Comment by sabbyanandan** [comment]
See [here](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java#L192) for more details.
