### ISSUE TITLE
[question] File Source for GZ files

### ISSUE THREAD

**Issue by ljtfreitas** [spring-cloud/spring-cloud-dataflow#1716]
Hello,

In the company I work for, we are strongly considering using Spring Cloud DataFlow in our pipeline data projects. In our scenario, we need to start some streams from files in `gz` format. Before we start developing our own code, is there any app for this purpose in spring-cloud-dataflow?

Thanks!

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/file#7

**Comment by sabbyanandan** [comment]
This question relates to https://github.com/spring-cloud-stream-app-starters/file repo, so I moved it there.
