### ISSUE TITLE
Package version defaults to 1.0.0 during stream deploy if not specified

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1733]
We need to assert if the package version is specified when using Skipper stream deployment.

**Comment by markpollack** [comment]
We should have the default value there be `1.0.0`

**Comment by markpollack** [comment]
The code already did this, so not sure what was intended.  I've changed the issue to be about the default value.

https://github.com/spring-cloud/spring-cloud-dataflow/commit/eaf275b7e05e5310b76df3a18f51d90179125f31#diff-5d063becd68b288cb1adea9027ec9872
