### ISSUE TITLE
Runtime apps for skipper streams - handle pagination

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1742]
Since the Skipper server returns the stream status and the platform status is retrieved from it, we need to handle the pagination for it differently than how appDeployer status result is retrieved with pagination.

**Comment by sabbyanandan** [comment]
@ilayaperumalg: When you get a chance, could you verify if it is still the case? We can decide then how to clean this up.

**Comment by ilayaperumalg** [comment]
@sabbyanandan I believe this is something we addressed via https://github.com/spring-cloud/spring-cloud-dataflow/commit/040be672e933d73d3e247e0a80ba85f753c4c20b#diff-185492033df9625ca88f31a039104431 and hence closing this.
