### ISSUE TITLE
Duplicate code in Mocks

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1743]
TabOnTapCompletionProviderTests, StreamCompletionProviderTests, TaskCompletionProviderTests tests each have an almost identical copy of a private 'Mocks' class.  Look to consolidate into a single class.

**Comment by ilayaperumalg** [comment]
The `TabOnTapCompletionProviderTests` class is on `server-core` as it requires stream definition repository access. Hence, we can have the common Mocks for the classes: StreamCompletionProviderTests, TaskCompletionProviderTests which are in the same `completion` module.
