### ISSUE TITLE
Add shell build-version to versionInfo

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1758]
As a user, I'd like to extract the compatible SCDF-shell version from the `versionInfo` listed under `/about` endpoint.

**Acceptance:**
- Add a new object to [`versionInfo`](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/resource/about/VersionInfo.java) with the key being `shell` and the contents to include: `name`, `version`, and `url`
- Add the absolute `url` that includes the version of it. Currently, we [explicitly create](https://github.com/spring-cloud/spring-cloud-dataflow-ui/blob/7f663e04a78a467f1725deeee630540addcff0cc/ui/src/app/about/about.component.html#L32) that in the UI
- Add new attributes to the existing `implementation`, `core` and `dashboard` objects for consistency
- Adapt RESTDocs to include the new additions

**Sample:**
```
{
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server-cloudfoundry",
      "version": "1.3.0.BUILD-SNAPSHOT"
      "url": "http://....."
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "1.3.0.BUILD-SNAPSHOT"
      "url": "http://....."
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "1.3.0.M3"
      "url": "http://....."
    },
    "shell": {
      "name": "Spring Cloud Dataflow Shell",
      "version": "1.3.0.M3"
      "url": "http://....."
    }
  }
}
```

**Comment by glyn** [comment]
The implementation was reverted in https://github.com/spring-cloud/spring-cloud-dataflow/commit/b4c3835c77b88d2d04df49c019a08413ef556747.

**Comment by jvalkeal** [comment]
Re-opened due to #1829

**Comment by glyn** [comment]
Thanks @jvalkeal. Really helpful to keep the issue open until it's truly implemented.
