### ISSUE TITLE
REST: Disable HAL to provide better backwards compatibility with XD API

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#176]

**Comment by ghillert** [comment]
Required by: https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/9

**Comment by garyrussell** [comment]
Do we really want to do this? I recently fixed the shell to work with HAL: 

https://github.com/spring-cloud/spring-cloud-dataflow/pull/143

**Comment by ghillert** [comment]
@garyrussell @sabbyanandan @ilayaperumalg  Good for pointing this out. As the shell is already refactored to work with this, I would be in favor of closing this PR and rather refactor the UI to work with the new REST API. My concern was originally the substantial breaking change in the REST API but since there all kinds of other changes, that might be ok then.
