### ISSUE TITLE
Improve test coverage of StreamService

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1760]

**Comment by sabbyanandan** [comment]
Depends on spring-cloud/spring-cloud-dataflow#1868
Depends on spring-cloud/spring-cloud-dataflow#1872

**Comment by tzolov** [comment]
This depends on the on finishing the Skipper/Classic mode refactoring for the StreamService, StreamDeployer service and the StreamDeploymentController #1918
