### ISSUE TITLE
Add Skipper Java DSL support

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1770]
The Java DSL does not allow one to deploy stream using skipper, this should be supported.  The documentation should be updated to show example usage.

Design notes:
- Add a new "stream skipper deploy" equivalent DSL infrastructure.

- Following is the example of the DSL:

> streamDefinition.skipper().platformName("pcf2").deploy()

- Update, rollback, and other sub-commands are out of scope.

**Comment by sabbyanandan** [comment]
Based on the latest improvements to the core, we won't have `stream skipper ...` commands anymore. Instead, we will reuse the existing `stream ...` commands and on the skipper-mode, all the skipper specific subcommands will be automatically added to the list. 

With that said, we don't have to build an entirely new builder with skipper support anymore. The goal is to add `stream update ..` equivalent to the existing DSL.

**Comment by markpollack** [comment]
Updated design notes based off a quick discussion with @viniciusccarvalho .

The differences in deploying via skipper or not come down to setting of specific properties in the method `deploy(Map)`.  We had another story or comment in a PR regarding adding some support to help users more easily build up that map, since creating Maps in Java isn't very fluent.  

One possible design is 
```

PropertiesBuilder propsBuilder = new PropertiesBuilder()
 // handle generic map building 
  .put("foo", "bar")
  .putAll(java.util.Properties)
  .put(Map.Entry<String,String>)
 // properties that are in the AppDeployer interface
  .memory("1024")
  .count(2)
  .indexed()
// properties relating to skipper from SkipperStream abstract class
  .withSkipper()
  .platformName("pcf")
  .packageVersion("1.2.0")
```

There maybe can instead be two builders, `PropertiesBuilder` and `SkipperPropertiesBuilder` so that one doesn't have to have use `withSkipper` and the methods such as `platformName` and `packageVersion` would appear size by side with `indexed` and `memory`.
