### ISSUE TITLE
Correct documentation of --dataflow.credentials-provider-command

### ISSUE THREAD

**Issue by glyn** [spring-cloud/spring-cloud-dataflow#1776]
The dataflow shell documentation states:
```
--dataflow.credentials-provider-command=<COMMAND> Executes an external command which must return an OAuth Access Token [no default].
```
This is not accurate as the command is expected to return an authentication header value such as "bearer oauth-token" (as returned, for example, by `cf oauth-token`). Also, the documentation should clarify whether other authentication header values are acceptable.

**Comment by sabbyanandan** [comment]
This is addressed in https://github.com/ghillert/spring-cloud-dataflow/commit/1de0f368edf067ba65ceddbeda5ec6a68dbb0d3b.
