### ISSUE TITLE
Document launching a composed-task via a stream

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1780]
As a user, I'd like to refer to the docs on how a composed-task can be launched via a stream. 

Refer to the [SO thread](https://stackoverflow.com/questions/47250280/launching-composed-task-built-by-dsl-from-stream-application) for more details.

**Acceptance:**
- Include a new sub-section under `Launching Tasks from a Stream`
- Move the `Launching Tasks from a Stream` section after the `Composed Tasks DSL` 
- List an example via `time` or `trigger` be the source that launches the composed-task graph on a `fixed-delay`

This relates to spring-cloud/spring-cloud-dataflow#1752 from datasource standpoint.

**Comment by jvmlet** [comment]
Hello
I'm following the update documentation to trigger composed task from stream, my stream looks like this :

`http | tasklaunchrequest-transform | task-launcher-local`

Deployment properties :

```
app.http.port=81

app.tasklaunchrequest-transform.uri=maven://org.springframework.cloud.task.app:composedtaskrunner-task:1.1.0.RC1

app.tasklaunchrequest-transform.command-line-arguments='--graph=t&&t2 --increment-instance-enabled=true --spring.datasource.url=jdbc:postgresql://localhost/postgres?currentSchema=flow --spring.datasource.username=postgres --spring.datasource.password=**** --spring.datasource.driver-class-name=org.postgresql.Driver --logging.org.springframework.cloud=DEBUG'
```
and getting the below exception :

```
org.springframework.cloud.dataflow.core.dsl.CheckPointedParseException: 168E:(pos 6): arguments not allowed unless parser is in app mode
t&&t2 --increment-instance-enabled=true --spring.datasource.url=jdbc:postgresql://localhost/postgres?currentSchema=flow --spring.datasource.username=postgres --spring.datasource.password=****--spring.datasource.driver-class-name=org.postgresql.Driver --logging.org.springframework.cloud=DEBUG
     *^

	at org.springframework.cloud.dataflow.core.dsl.Tokens.raiseException(Tokens.java:276) ~[spring-cloud-dataflow-core-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at org.springframework.cloud.dataflow.core.dsl.TaskParser.eatTaskApp(TaskParser.java:215) ~[spring-cloud-dataflow-core-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at org.springframework.cloud.dataflow.core.dsl.TaskParser.parseTaskNode(TaskParser.java:163) ~[spring-cloud-dataflow-core-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at org.springframework.cloud.dataflow.core.dsl.TaskParser.parseFlow(TaskParser.java:173) ~[spring-cloud-dataflow-core-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at org.springframework.cloud.dataflow.core.dsl.TaskParser.parseTaskNode(TaskParser.java:166) ~[spring-cloud-dataflow-core-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at org.springframework.cloud.dataflow.core.dsl.T
```

**Comment by cppwfs** [comment]
Looks like there is an issue in how DataFlow is passing these command-line-args in the properties to the CTR.   At this time it looks more like a CTR issue than a DataFlow issue, so I'm opening the following issue: https://waffle.io/spring-cloud-task-app-starters/app-starters-release/cards/5a11f0ce65135400757baaa8 to investigate further.
