### ISSUE TITLE
Reference guide is partially rendering

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1809]
1.3 BS of the ref. guide includes only [3 sections](https://docs.spring.io/spring-cloud-dataflow/docs/1.3.0.BUILD-SNAPSHOT/reference/htmlsingle/#getting-started).

**Comment by cppwfs** [comment]
The problem is that there is a un matched triple "`" in the getting started adoc.

**Comment by markpollack** [comment]
Yep.  Removed another section on debugging the shell that seemed outdated and some more working around the options to deploy a stream w/ and w/o skipper.

Merged as f6b4b0a69d572f219f8304723c0622327ab0d709
