### ISSUE TITLE
SYNC control usage

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-dataflow#1823]
Hello
I'm trying to use 2 sync objects in composed task graph described below :

`<t1: sampleTask 'FAILED'->SYNC && SYNC || t2: sampleTask 'FAILED'->SYNC && SYNC> && sampleTask`
![image](https://user-images.githubusercontent.com/6664858/33545340-875e107a-d8e6-11e7-8f7a-408c6f7643c3.png)
Task creation fails with these errors:
```
 166E:(pos 34): duplicate app name. Use a label to ensure uniqueness
 166E:(pos 67): duplicate app name. Use a label to ensure uniqueness
 166E:(pos 75): duplicate app name. Use a label to ensure uniqueness
```
Another use case :

`<t2: sampleTask '*'->SYNC || sampleTask '*'->SYNC>`
![image](https://user-images.githubusercontent.com/6664858/33545400-c74977ec-d8e6-11e7-9b0e-cc87a786624c.png)

Error message I get when creating the task :
`166E:(pos 49): duplicate app name. Use a label to ensure uniqueness`

Looks like a bug/ unsupported  functionality.
Please advise.

**Comment by aclement** [comment]
The simple error is that `SYNC` was not being treated as special and thus erroring about requiring a label. That is simple to fix but there are still issues around the sync node. I think any split should have just one sync, at the end - that is the purpose of sync, and all references to sync within that split would take you there.

This likely means what you were trying to do "trying to use 2 sync objects in composed task graph described below" may not be allowed but I'm not sure what you are wanting to achieve. If you describe it we might be able to determine how that should look in the DSL/Graph.

**Comment by jvmlet** [comment]
OK, I'll provide simpler example: start,run task 1 and 2 in parallel, sync, run task 3 and  4 in parallel, sync, run task 5,end. You will get the same error.

**Comment by aclement** [comment]
When building that, you don't need two sync nodes, only one.  Sync nodes are required when a split is immediately followed by another split.  So your tasks 3 and 4 don't need to sync before 5 runs, like this: `<t1: sampleTask || t2: sampleTask> && <t3: sampleTask || t4: sampleTask> && t5: sampleTask`.  3 and 4 simply join to 5.  For me, creating that graph produces valid DSL.

In fact our discussion is making me feel like I won't rush into the `SYNC` fix, I'd rather work out the full set of use cases we want to support and make sure they work. I can make a testcase like this work:

  ``` @Test
   public void syncs1853() {
      String spec = "<t2: sampleTask '*'->SYNC || sampleTask '*'->SYNC> && t3: sampleTask";
      checkDSLToGraphAndBackToDSL(spec);
   }
```
But I don't think we've agreed that SYNC can be a transition target like that which makes the testcase odd.

**Comment by jvmlet** [comment]
I think the point here is that SYNC should be named/labeled to be distinguished.  I can add tasks 5 and 6 after 3 and 4 that join to task 7 and this will reproduce the problem. You can think about any other scenario that requires two SYNCs to reproduce the problem.

**Comment by cppwfs** [comment]
Closing this issue for now.   Unless there is an additional use case for labeling a sync.
