### ISSUE TITLE
How to pass task parameters to spring cloud data flow

### ISSUE THREAD

**Issue by rajprasadtarget** [spring-cloud/spring-cloud-dataflow#1825]
I am trying to create a task where the task requires initial values like list of order ids,

I was looking at the Spring Cloud data Flow UI screen, it shows that before launching we can  pass a property key  and a value pair.

So if I create a property key as app.studentjob.property
And give a property value as 11, 12, 13 

How to access this in the actual task in code ?

Also when we ae launching task from rest api, how to pass properties in the url http://localhost:9393/tasks/executions?name=studentjob

**Comment by jvalkeal** [comment]
I had a email conversation offline about this.
