### ISSUE TITLE
For every task a new java process ?

### ISSUE THREAD

**Issue by rajprasadtarget** [spring-cloud/spring-cloud-dataflow#1827]
I have a question, every time we launch a spring cloud task, it starts a new jvm (java.exe), so if 25 tasks are launched , then it will start 25 jvm.  So how do we manage this in real production environment .

So is there any kind of queuing provided by SCDF where we can queue the task launching ?
Or can we delay the start of actual task launch after the request for task launch is fired?

**Comment by mminella** [comment]
This question is better asked via StackOverflow and tagged with the tag `spring-cloud-dataflow` tag.  As for your question, there is no queueing.  Local (which does launch individual processes) will launch a new process for each task.  What specific use cases in production are you trying to accomplish?

**Comment by rajprasadtarget** [comment]
I want to know if scdf starts a seperate jvm with every task, d o we need to worry about resource crunch over consumption of CPU and Memory ? 

In the example above , if 25 tasks are launched , then it will start 25 jvm, so 25 JVM running at same time is a very resource intensive . So do you think this will cause issues in terms of memory usage or cpu usage?

**Comment by cppwfs** [comment]
To your first question, there are 2 parts.
1A)  Does it start a new JVM? Yes
1B)  The classic response applies, "It Depends".    i.e. it depends on your environment  and how process and memory intensive your tasks are.   If they are not memory intensive you can use the deployment properties you can adjust the memory to what the tasks need.

**Comment by sabbyanandan** [comment]
@rajprasadtarget: please consider asking questions like this in StackOverflow going forward. Since @cppwfs's response adequately answers the questions, I will close it.
