### ISSUE TITLE
Cannot create composed task via DSL when logging is on

### ISSUE THREAD

**Issue by magx2** [spring-cloud/spring-cloud-dataflow#1828]
I'm having this security configuration:

	security:
	  basic:
		enabled: true                                                     
		realm: Whatever
	  user:
		name: some-name
		password: super-secret
		role: VIEW, CREATE, MANAGE

When I try to create new composed task by pasting code into DSL view, I'm getting this error:

    {
      "timestamp":"2017-12-05T12:34:07.958Z",
      "status":403,
      "error":"Forbidden",
      "message":"Access is denied",
      "path":"/tools/parseTaskTextToGraph"
    }

Should I add some more roles for user? Of course if I'm not using security everything works.

Spring dataflow version is ```1.2.2.RELEASE```

**Comment by sabbyanandan** [comment]
Thanks for reporting. This is probably related to: spring-cloud/spring-cloud-dataflow-ui#565 - we will investigate it soon.

**Comment by magx2** [comment]
Yep you ate right. I'm closing this ticket
