### ISSUE TITLE
Add TaskExecution detail shell command

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#183]
As a user, I'd want to be able to view the details of a `TaskExecution` via the shell command.

**Acceptance:**
* Issuing `dataflow:> task execution view --id 1234` lists all task and execution specifics for the task-id `1234`
* Invoking shell command includes the following details
  - name
  - id
  - start time
  - end time
  - exit code

**Comment by cppwfs** [comment]
Also need to show parameters as well.
