### ISSUE TITLE
Dashboard > Batch Job Executions - NullPointerExcetion

### ISSUE THREAD

**Issue by nishkarma** [spring-cloud/spring-cloud-dataflow#1831]
I deployed batch job with stream create DSL. No task, only a stream.

dataflow:>stream create foo --definition "triggertask --triggertask.uri=maven://com.test.testjob-1.0.1.jar --trigger.cron='0/40 * * * * ?' triggertask.environment-properties=loader.config.location=file:///app/batch/common/properties/app.properties| task-launcher-local" --deploy

The job runs well, and I can query the BATCH_JOB_EXECUTION table with EXIT_CODE=COMPLETED.
But when I browse the Dashboard > Batch Job Executions, I get NullPointerExcetion.
and scdf log showes below.

RestControllerAdvice : Caught exception while handling a request

java.lang.NullPointerExcetion: null
at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskJobService.getTaskJobExecution(DefaultTaskJobService.java:240) ~[spring-cloud-dataflow-server-core-1.3.0.M3.jar!/:1.3.0.m3]

**Comment by cppwfs** [comment]
In this case did you Boot App include the @EnableTask annotation?  If not you will see this error when viewing the JobExecutions table.  
Regardless, Data Flow should be able to handle this and has already been reported here: https://github.com/spring-cloud/spring-cloud-dataflow/issues/1822.   So for now I will close this issue.
