### ISSUE TITLE
Exit status of task is not reflected in graph DSL

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-dataflow#1832]
Hello
I'm using the  latest 1.3.0_SNAPSHOT built and in below screenshot the transition from `1` to `2` is configured with exit status `COMPLETED` and from `1` to `3` with exit  status `FAILED`.
These configurations are not reflected in DSL.
 In `1.2.3.RELEASE` it was properly handled in generated graph DSL.
 
![image](https://user-images.githubusercontent.com/6664858/33871935-5d20fe66-df1d-11e7-849f-4eb362e437b5.png)

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#569
