### ISSUE TITLE
Stream Status changed from deployed to failed

### ISSUE THREAD

**Issue by nishkarma** [spring-cloud/spring-cloud-dataflow#1835]
I created stream with triggertask-source-rabbit:1.2.0.RELEASE and task-launcher-local-sink-rabbit:jar:1.2.0.RELEASE in SCDF M3 environment.

It' runs well, But some times later Stream Status changed from deployed to failed.
I want know the reason. And how can I fix this problem.

**Comment by sabbyanandan** [comment]
Hi, @nishkarma. This report is incomplete. Please take a moment to review the [README](https://github.com/spring-cloud/spring-cloud-dataflow#reporting-issues) and edit the description with all the details. It is impossible for us to comment what could be the cause for the behavior you're seeing.

**Comment by nishkarma** [comment]
Hi, I solved this issue.
It was memory deficit issue.

So I gaved th deploy option like this.

dataflow>stream deploy --name test1 --properties "deployer.triggertask.local.javaOpts=-Xms32m -Xmx128m, deployer.task-launcher-local.local.javaOpts=-Xms32m -Xmx128m"

And then the issue cleared.

**Comment by sabbyanandan** [comment]
Thanks for the update.
