### ISSUE TITLE
Add skipper to acceptance tests

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1840]
Add skipper into acceptance tests https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/

This involves creating new CI plans.

**Comment by tzolov** [comment]
- I've pushed the https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/pull/139
- Another PR will address the test failing in skipper mode due to app names check in different modes

**Comment by ilayaperumalg** [comment]
CI Plan is triggered as a child plan from the classic mode local acceptance test: https://build.spring.io/browse/SCD-ALSK

**Comment by sabbyanandan** [comment]
Local and CF are already addressed. We have a diff issue for K8S.
