### ISSUE TITLE
deleting a task does not seem to work

### ISSUE THREAD

**Issue by annasarte** [spring-cloud/spring-cloud-dataflow#1844]
We are on spring cloud data flow server version 1.2.3.
Running this on Linux.
We are able to create and launch tasks.
However, deleting a task via the REST API, I receive an http status code of 200 (OK) but the task still remains.
Steps:
1) launch a task  -- your response is a job / execution id
2) via REST api, you can list this task.  Ex:  GET http://localhost:9393/tasks/executions/1
3) delete this task via REST api:  DELETE http://localhost:9393/tasks/executions/1
4) You can look at the database tables and the table TASK_EXECUTION still lists this job
5) repeat getting/listing this task:  GET http://localhost:9393/tasks/executions/1  and again, you will see it listed.

Anything I need to be doing?
Thanks,
Anna

**Comment by mminella** [comment]
Deleting a task does not clear out the historic records.  It is only intended to delete the definition to prevent it from being run again.  This is expected behavior.

**Comment by annasarte** [comment]
Hello.
Please read my issue carefully.  It is deleting a TASK EXECUTION.  All the REST API calls I mentioned are for a task execution.  You have APIs for them.  They do not work.

**Comment by annasarte** [comment]
Please do not confuse my question with deleting a task.  The REST APIs I am complaining about are task execution.

**Comment by mminella** [comment]
That API still isn't intended to delete the records in the database.  It's intended to clean up any resources left behind.  While you are correct that it currently is a no-op for all implementations, it still won't do what you are asking (delete the execution records).  For CloudFoundry, I'd expect it to delete the droplet/staged application for example.  For local, I'd expect it to delete the directory that the app was run in or where the logs were written to.

**Comment by annasarte** [comment]
I see.  Can you give examples of "resources" it cleans up?

**Comment by mminella** [comment]
Right now, as I stated, it is a no-op for both the local deployer and CloudFoundry.  I'll admit that isn't right and we should create stories for what that behavior should be (cc @sabbyanandan ).  The implementation delegates to `TaskLauncher#cleanup(String id)`.  That is intended to do a platform specific cleanup of resources that were used during a task's execution.  For example, on CloudFoundry, it should delete the droplet/unstage the app.  On Local, it should delete any working directory that was created to run the task (thereby cleaning any of the working resources like input files that were downloaded to it).

So while I'll concede that that API shouldn't be a no-op, we probably still wouldn't be deleting those historic execution records from the db.

**Comment by sabbyanandan** [comment]
Yes; it's a no-op for local and cf right now. We could mimic what we are doing in K8S (we delete the pod upon the delete invocation) for consistency. I'm not aware of specific limitations to this on CF (spring-cloud/spring-cloud-deployer-cloudfoundry#232), but in local, we can cleanup the directory per @mminella's suggestion (spring-cloud/spring-cloud-deployer-local#83). 

> So while I'll concede that that API shouldn't be a no-op, we probably still wouldn't be deleting those historic execution records from the db.

+1; the task-execution are meant to be persistent to preserve the audit-trail/historical representation of task launches. 

Hi, @annasarte: If you have further feedback on the deployer implementations, feel free to share it in the respective issues linked above.

**Comment by annasarte** [comment]
Thanks for your comments.
