### ISSUE TITLE
Add support for composed apps

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#185]
Composed Module currently behave as "white boxes". As soon as a module is composed (say "http | filter") then all options of the children modules are available (as e.g. http.port and filter.expression in the example above).

Change this so that a composed module is a black box: user has to explicitly expose an option for it to be available (most certainly using a short name). Hardcoding of values would be retained (and possibly overridable).

Possible syntaxes :
1)

```
app compose foo --definition "http --port=${myport:1234} | filter"
```

2)

```
app compose foo --definition "http | filter" --expose port
```

2.1) in case of ambiguity (simulated in this particular example):

```
app compose foo --definition "http | filter" --expose http.port
```

2.2) for specifying a default:

```
app compose foo --definition "http | filter" --expose port=1234
```

3) allow both 1) and 2), using 1) mainly for cases where we don't map 1 to 1 with the underlying option, e.g.:

```
filter --expression=${expr}+'foo'
```

**Comment by ashwgupt** [comment]
Hi Sabby,

I am looking at the sample app - https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/double in order to build and deploy a self-contained stream application. 

I believe this issue, you raised, will help with deployment of the above app via the Dataflow server.

But are you aware of the way/work around to deploy composed applications as of today? My target is cloud foundry.

**Comment by donovanmuller** [comment]
@ashwgupt Sounds like you need this https://github.com/spring-cloud/spring-cloud-dataflow/issues/915 😁

Note: this is just a proposal be me and not an official feature.

**Comment by ashwgupt** [comment]
@donovanmuller thanks for the pointer. I will check that out.

**Comment by sabbyanandan** [comment]
[Aggregate apps](http://docs.spring.io/spring-cloud-stream/docs/current-SNAPSHOT/reference/htmlsingle/#_aggregation) is the solution to this situation for now. There will be support for application groups in future, but "app compose" as a feature is not in scope anymore.
