### ISSUE TITLE
AppRegistry default versioning: Use case when import overwrite

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1854]
We need to define the expected outcome when the apps are imported with overwrite set to `true`.

In this case, should we allow the new apps to be the default or the default versioning should always be done explicitly for each app?

It could be a convenient to allow users to override the default version (by default or via an option) for all the apps being imported via overwrite.

**Comment by sabbyanandan** [comment]
Since now we do not have the option to `--force` update the registry, this is not applicable anymore.
