### ISSUE TITLE
Encapsulate the ResourceUtils internals into a clean, stateful ResourceResolver class

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow#1873]
The `ResourceUtils` static utils (after #1843) exposing internals such as MavenProperties and ResourceLoaders instances through all applications layers. Later are used only to be passed as arguments to the static ResourceUtils methods. 
Instead a ResourceService @service should encapsulate the resource loading access and hide all the internals

depends on #1843

**Comment by sabbyanandan** [comment]
Also look into #1964.
