### ISSUE TITLE
Generate backing schema for App Registry

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1877]
Test against the supported databases: https://docs.spring.io/spring-cloud-dataflow/docs/1.3.0.BUILD-SNAPSHOT/reference/htmlsingle/#configuration-rdbms

Spring Cloud Data Flow supports the following RDBMS:

- [ ] H2
- [ ] HSQLDB
- [ ] MySQL/MariaDB
- [ ] Oracle
- [ ] PostgreSQL
- [ ] DB2
- [ ] SqlServer

**Comment by ghillert** [comment]
created https://github.com/spring-cloud/spring-cloud-skipper/issues/395
