### ISSUE TITLE
Set ResourceMetadata URI when generating Skipper package

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1880]
Depends on: https://github.com/spring-cloud/spring-cloud-skipper/issues/393

**Comment by markpollack** [comment]
Can add a new method to AppRegistrationRepository `findByURI` to look up the AppRegistration and get the resource metadata.  This would not handle the case of two apps that are registered with the same URI (but the chances of that are small).

**Comment by sabbyanandan** [comment]
This was added in Skipper a while ago.
