### ISSUE TITLE
SCDF shell disregards proxy settings

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-dataflow#1896]
Hi
Looks like the SCDF  **shell cli** disregards any proxy configuration, tried `-Dhttp.proxyHost=xxx -Dhttp.proxyPort=xx` and setting  environment variable `http_proxy=xxxx:ddd` without success to configure SCDF server deployed behind corporate proxy.
Please build the rest client with optional configured proxy.
Thanks

**Comment by markpollack** [comment]
We can enable a compatibility mode with JDK's system properties in the apache httpclientbuilder

http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html

by calling the `useSystemProperties` method prior to calling `build`
