### ISSUE TITLE
module info fails on library

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#191]
Running `module info` on a defined library fails to resolve artifact:

```
org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.springframework.cloud.dataflow.library:hadoop-phd30:pom:exec:1.0.0.BUILD-SNAPSHOT in repository 1 (https://repo.spring.io/libs-snapshot)
```

It looks like it automatically registers `exec` to the path even thought it was defined without it as:

```
module register --type library --name hadoop-phd30 --coordinates 'org.springframework.cloud.dataflow.library:hadoop-phd30:pom:1.0.0.BUILD-SNAPSHOT'
```

**Comment by trisberg** [comment]
This is related to https://github.com/spring-cloud/spring-cloud-dataflow/issues/160

**Comment by sabbyanandan** [comment]
This is not relevant anymore. 

The `app info` command has been overhauled a few times and there's also the pre-req to point to a remote maven repository prior to describing apps.
