### ISSUE TITLE
Convert the `skipper-enabled` feature into `mode` with two values: classic [default] and skipper

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow#1916]
Currently the `--spring.cloud.dataflow.features.skipper-enabled` property is used to start the SCDF in `classic` (skipper-enabled=false [default]) and `skipper` (skipper-enabled=true) modes

We should replace the boolean tribute by a `mode` enumerable such to allow future mode extensions. 

* Refactor the skipper-enabled property is exposed via the `FeaturesInfo` properties to expose the `mode` instead. If necessary we can keep `skipper-enabled` for backward compatibility  and add the mode a new feature attributed

**Comment by markpollack** [comment]
Not going to do this for 1.3 RC

**Comment by sabbyanandan** [comment]
The differentiation between skipper and classic mode is not a requirement in 2.x.
