### ISSUE TITLE
Add Tests for RootController Links

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1917]
As a developer, I'd like to add test coverage to validate the Shell -> Server connectivity. Currently, the Shell uses the Hateoas "links" (UI doesn't), so we need to verify to make sure this model continues to work as expected. 

Right now, it appears to be a problem on 1.3 M3 / 1.3 BS esp. when interacting with Hateoas links.

--

We need to ensure that the RootController links are appropriately tested:

- With/Without Security (OAuth)
- With different feature-flags enabled/disabled

**Comment by ghillert** [comment]
is related to https://github.com/spring-cloud/spring-cloud-dataflow/issues/1908

**Comment by ghillert** [comment]
The original issue was only when OAuth was enabled on the server-side. We do have decent Shell test coverage for non-OAuth usecases.

Issue https://github.com/spring-cloud/spring-cloud-dataflow/issues/1468 will add some OAuth-specific test-coverage.

However, the `RootController` was never tested appropriately. If that was tested issue https://github.com/spring-cloud/spring-cloud-dataflow/issues/1908 would never have occurred (we would have caught the issue in time).

Thus, changing the title to `Add Tests for RootController Links`.
