### ISSUE TITLE
Factor out the StreamDefinitionController#save() implementation into StreamService/AbstractStreamService

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow#1924]
Stream definition management is owned by the `StreamService` the controller shouldn't be allowed to mutate the stream definition state. 

- Also move also the `AppRegistryCommon` form the controller to the StreamService.

**Comment by tzolov** [comment]
Because this depends on #1963 PR, i can either merge this as part of the 1963 PR or wait until later is merged.

**Comment by tzolov** [comment]
Here is the code: https://github.com/tzolov/spring-cloud-dataflow/tree/gh-1924-refactor-stream-def-controller 
Can't  open PR due to the #1963 dependency.

**Comment by markpollack** [comment]
merged in 7b8a0b0c884c71d86430b8f609eb1adfe05228ca

**Comment by ilayaperumalg** [comment]
@tzolov Now that #1963 is merged, can we have your changes as PR?
