### ISSUE TITLE
Support shell completions for closed set of values in stream definitions

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#193]
When doing dsl completion in a stream definition and a module option accepts a value that has a closed set of possible values (_eg: booleans, enums_), we can provide completion for those.

Moved from [XD-1284](https://jira.spring.io/browse/XD-1284)

**Comment by ericbottard** [comment]
This is already implemented in s-d-f (although a recent failure on Bamboo was related to that, so we may want to keep open)

**Comment by sabbyanandan** [comment]
This has been addressed.
