### ISSUE TITLE
Prevent nulls in Shell response on classic-mode

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1949]
As a user, I'm deploying a stream to K8S in the classic-mode; while reviewing the application details, I see "null" in the output. This can be masked.

**steps:**
```
dataflow:>app import --uri http://bit.ly/Celsius-SR1-stream-applications-rabbit-docker --force
dataflow:>app list --id source:time
╔═════════╤═════════╤════╤════╗
║ source  │processor│sink│task║
╠═════════╪═════════╪════╪════╣
║time-null│         │    │    ║
╚═════════╧═════════╧════╧════╝
```

**Comment by viniciusccarvalho** [comment]
@sabbyanandan I noticed this is happening on other flavors of the server as well.

**Comment by sabbyanandan** [comment]
Yes, it happens on all servers implementations. Classic mode doesn't have the concept of versioning, so let's ignore the nulls altogether. No extra description necessary.
