### ISSUE TITLE
Add basic-auth support for CTR endpoints

### ISSUE THREAD

**Issue by VovaViter** [spring-cloud/spring-cloud-dataflow#1972]
I can't run the composed task, where counts of nested tasks more than one. I have next errors:
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'taskOperations' defined in class path resource [org/springframework/cloud/task/app/composedtaskrunner/DataFlowConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.dataflow.rest.client.TaskOperations]: Factory method 'taskOperations' threw exception; nested exception is org.springframework.web.client.HttpClientErrorException: 401 null
`

Here is application properties:
server:
  port: 9393
management:
  security:
    enabled: true
    roles: CREATE,MANAGE,VIEW

info:
  app:
    name: "@project.artifactId@"
    description: "@project.name@"
    version: "@project.version@"

security:
  basic:
    enabled: true
    realm: Spring Cloud Data Flow
  user:
    name: admin
    password: 123456
    role: VIEW, CREATE, MANAGE
maven:
  remoteRepositories:
    springRepo:
      url: https://repo.spring.io/libs-snapshot

spring:
  application:
    name: spring-cloud-dataflow-server-local
    admin:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  cloud:
    deployer:
      local:
        env-vars-to-inherit: ['TMP', 'LANG', 'LANGUAGE', 'LC_.*', 'Path']
    config:
      uri: http://localhost:9393
      name: spring-cloud-dataflow-server-local
      override-system-properties: false
      enabled: true
      fail-fast: true
    discovery:
      client:
        simple:
          local:
            service-id: config-service
    dataflow:
      features:
        analytics-enabled: false
        streams-enabled: false

**Comment by sabbyanandan** [comment]
Can you also share the http://localhost:9393/about endpoint output here?

**Comment by VovaViter** [comment]
I can't when I logged in this request redirect to the logout page. Using curl this uri responded unauthorized exception

**Comment by sabbyanandan** [comment]
You've secured server, so you'd have to supply user/pass in the CURL.

> curl -u<USER>:<PASSWORD> http://localhost:9393/about -H "Accept: application/json"

**Comment by cppwfs** [comment]
CTR can't run against a Secured SCDF Server.  I thought there was a issue on this.  I'll see if I can find it if not I'll add one.

**Comment by VovaViter** [comment]
{
   "featureInfo":{
      "analyticsEnabled":false,
      "streamsEnabled":false,
      "tasksEnabled":true,
      "skipperEnabled":false
   },
   "versionInfo":{
      "implementation":{
         "name":"spring-cloud-dataflow-server-local",
         "version":"1.3.0.BUILD-SNAPSHOT"
      },
      "core":{
         "name":"Spring Cloud Data Flow Core",
         "version":"1.3.0.BUILD-SNAPSHOT"
      },
      "dashboard":{
         "name":"Spring Cloud Dataflow UI",
         "version":"1.3.0.M4"
      },
      "shell":{
         "name":"Spring Cloud Data Flow Shell",
         "version":"1.3.0.BUILD-SNAPSHOT",
         "url":"https://repo.spring.io/libs-snapshot/org/springframework/cloud/spring-cloud-dataflow-shell/1.3.0.BUILD-SNAPSHOT/spring-cloud-dataflow-shell-1.3.0.BUILD-SNAPSHOT.jar"
      }
   },
   "securityInfo":{
      "authenticationEnabled":false,
      "authorizationEnabled":false,
      "formLogin":false,
      "authenticated":false,
      "username":null,
      "roles":[

      ]
   },
   "runtimeEnvironment":{
      "appDeployer":{
         "deployerImplementationVersion":"1.3.0.M2",
         "deployerName":"LocalAppDeployer",
         "deployerSpiVersion":"1.3.0.M2",
         "javaVersion":"1.8.0_112",
         "platformApiVersion":"Windows Server 2012 R2 6.3",
         "platformClientVersion":"6.3",
         "platformHostVersion":"6.3",
         "platformSpecificInfo":{

         },
         "platformType":"Local",
         "springBootVersion":"1.5.8.RELEASE",
         "springVersion":"4.3.12.RELEASE"
      },
      "taskLauncher":{
         "deployerImplementationVersion":"1.3.0.M2",
         "deployerName":"LocalTaskLauncher",
         "deployerSpiVersion":"1.3.0.M2",
         "javaVersion":"1.8.0_112",
         "platformApiVersion":"Windows Server 2012 R2 6.3",
         "platformClientVersion":"6.3",
         "platformHostVersion":"6.3",
         "platformSpecificInfo":{

         },
         "platformType":"Local",
         "springBootVersion":"1.5.8.RELEASE",
         "springVersion":"4.3.12.RELEASE"
      }
   },
   "_links":{
      "self":{
         "href":"http://localhost:9393/about"
      }
   }
}

**Comment by VovaViter** [comment]
Additional this is the first time running composed task.

**Comment by JLauzonG** [comment]
Hello, we are having the same problem. This is problematic as we intend to push the SCDF - CTR infrastructure into production environment in the upcoming weeks. Do you guys have an idea on when this issue will be fixed ?

**Comment by sabbyanandan** [comment]
Hi, @JLauzonG: We are going to strictly only explore SCDF's OAuth support for communication between microservice applications (eg: SCDF <-> CTR). Specifically, what security authentication/authorization mechanism are you using?

**Comment by JLauzonG** [comment]
We use basic authentication for our SCDF server. What is your recommendation regarding running a composed task in production environment, without any current compatibility with SCDF security?

**Comment by jvmlet** [comment]
@JLauzonG , we had the same problem (SCDF basic auth enabled).
Our solutiom was to repackage the CTR application and re-configure the `TaskOperations` bean :

```java
@Configuration
@Slf4j
@EnableConfigurationProperties(ComposedTaskProperties.class)
public class PatchedComposedTaskRunnerConfiguration {

    @Value("${vcap.services.scdf-credentials.credentials.username}")
    private String userName;

    @Value("${vcap.services.scdf-credentials.credentials.password}")
    private String password;

    @Autowired
    private ComposedTaskProperties properties;

    @Bean
    public TaskOperations taskOperations() {
        RestTemplate restTemplate =new RestTemplate();
        restTemplate.getInterceptors()
                .add(new BasicAuthorizationInterceptor(userName, password));

        DataFlowTemplate dataFlowTemplate = new DataFlowTemplate(
                this.properties.getDataflowServerUri(), restTemplate);

        return dataFlowTemplate.taskOperations();
    }


}
```

The application itself  looks like this :
```java
@SpringBootApplication
@Slf4j
@Import(ComposedTaskRunnerConfiguration.class)
public class PatchedComposedTaskRunnerApplication {
    public static void main(String[] args) {
        SpringApplication.run(PatchedComposedTaskRunnerApplication.class,args);
    }
}
```

Needless to mention that `PatchedComposedTaskRunnerApplication` and `PatchedComposedTaskRunnerConfiguration` should be in the same package.

The gradle build file :
```groovy
dependencyManagement {
    imports {

        mavenBom 'org.springframework.cloud.task.app:composedtaskrunner-task-app-dependencies:1.1.0.RELEASE'
    }
}
dependencies {
    compile('org.springframework.cloud.task.app:spring-cloud-starter-task-composedtaskrunner')
    compile 'org.springframework.cloud:spring-cloud-starter-stream-rabbit:1.3.3.RELEASE'

    testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

As you can see, we also got a bonus  : our CTR now publishes task events to Rabbit MQ exchange (`task-events` is the default)

@sabbyanandan , creating the `RestTemplate` used by operation beans via public api (`RestTemplateBuilder`) would allow users to configure the template the way they want using `RestTemplateCustomizer`

**Comment by jvmlet** [comment]
Forgot to mention that you will want to disable the `web-environment` in `application.yml`:
```yml
spring:
  main:
    web-environment: false
```

**Comment by sabbyanandan** [comment]
As next steps, we will add the facility in CTR to interact with a secured SCDF server. That would be CTR making REST calls against a (basic-auth) secured SCDF server, so it can trigger the launching of Tasks defined in the CT DSL/graph.

**Comment by sabbyanandan** [comment]
Closing this in favor of spring-cloud-task-app-starters/composed-task-runner#41.

**Comment by Rostish** [comment]
Guys, i have the same problem with LDAP.
Please, look at https://github.com/spring-cloud/spring-cloud-dataflow/issues/2452

**Comment by sabbyanandan** [comment]
Hi, @Rostish. There's basic-auth support between CTR <-> SCDF; however, we don't support LDAP. We would want to explore OAuth as the standard mechanism of the authentication between microservices, and by this standardization, there'll be support for [LDAP via UAA](https://docs.cloudfoundry.org/uaa/identity-providers.html#ldap) in the future. 

That said, if you can describe your use-case(s) in a new issue and the acceptance on how you'd like it working, that'd be good. Please refrain from commenting on closed issues.

**Comment by Rostish** [comment]
@sabbyanandan 
Sorry. I wont do it again. Could we continue our discus in my #2452 issue.
The main problem is that my company doesn't have infrastructure for Oauth2. I need to use LDAP, but when i enabled it, i couldn't to start my Spark-Runner task. SCDF starts composed-task-runner instead of my task. We use microservice that starts SCDF tasks via REST and this totally won't work(. In my issue i demonstrate some example.
