### ISSUE TITLE
Investigate using DataFlowTemplate to import apps

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1975]
It maybe failing via DataFlowTemplate, but passing in the shell.

**Comment by markpollack** [comment]
I guess you were observing the behavior in https://github.com/spring-cloud/spring-cloud-dataflow-samples/pull/47 ?

**Comment by viniciusccarvalho** [comment]
The issue really ain't the template, but instead on low resource environments (with disk size < minimum percentage) and by calling import and immediately follow a deploy, we ran in a race condition, where it appears that the resources on disk seems to be unavailable to be used. I've opened https://github.com/spring-cloud/spring-cloud-dataflow/issues/1992 to track it instead
