### ISSUE TITLE
RootController shows invalid value for AppInstanceController

### ISSUE THREAD

**Issue by PTomi002** [spring-cloud/spring-cloud-dataflow#1978]
Project: _spring-cloud-dataflow-server-core_

Billboard URL on **RootController**  `@RequestMapping("/")`:

`http://localhost:9393/`

The problematic part of it:

`{
"rel": "runtime/apps/instances",
"href": "http://localhost:9393/runtime/apps/interface%20org.springframework.web.util.UriComponents%24UriTemplateVariables/instances"
}`

According the code the **RootController** pass the **UriComponents.UriTemplateVariables.SKIP_VALUE** parameter to get the link for **AppInstanceStatusResource** class, but instead of it the `href` should be something like this:

`/runtime/apps/{appId}/instances`

This part `interface%20org.springframework.web.util.UriComponents%24UriTemplateVariables` is inserted into the placeholder for `{appId}`.

This problem appears in the following versions:
Local Dataflow Server: 1.2.3
Newer implementations and milestones: 1.3.0 M3
I did not try with older versions.

**Comment by sabbyanandan** [comment]
@PTomi002: Thanks for reporting. We will investigate why it is even leaking into the `RootController`. Just curious, how are you using the Runtime-Apps info?
