### ISSUE TITLE
CTR problems with sql server jdbc driver

### ISSUE THREAD

**Issue by VovaViter** [spring-cloud/spring-cloud-dataflow#1979]
I try to run composed tasks on local-cloud-server which use SQL server. CTR can't found dependencies for driver:
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration': Unsatisfied dependency expressed through field 'dataSources'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Tomcat.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.tomcat.jdbc.pool.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: com.microsoft.sqlserver.jdbc.SQLServerDriver
I cloned project and added dependencies in pom.xml after that I packed new CTR and registred it:
no main manifest attribute, in E:\SpringCloudDataFlow_demo\spring-cloud-starter-task-composedtaskrunner-1.1.1.BUILD-SNAPSHOT.jar

**Comment by cppwfs** [comment]
Based on the exception above you will need to add the SqlServerDriver dependency to your CTR's POM.xml.

**Comment by VovaViter** [comment]
Please read full comment, I cloned project and added dependencies in pom.xml after that I packed new CTR and registered it like task with uri file://pathToFile . When I run a composed task with new CTR I have next exception:
no main manifest attribute, in E:\SpringCloudDataFlow_demo\spring-cloud-starter-task-composedtaskrunner-1.1.1.BUILD-SNAPSHOT.jar

How do I need to pack it? I use mvn clean install.

**Comment by cppwfs** [comment]
. Next question:  Did you build based on the instructions below?
https://github.com/spring-cloud-task-app-starters/composed-task-runner/blob/master/spring-cloud-starter-task-composedtaskrunner/README.adoc#building-with-maven
. If Yes, then did you run the jar from the target in the apps/composedtaskrunner-apps subdirectory?
. If Yes what was your `spring_datasource_url` & `spring_datasource_driverClassName`?

**Comment by VovaViter** [comment]
1. No. But I rebuild it according instructions and have next error:
The POM for org.springframework.cloud:spring-cloud-dataflow-rest-client:jar:1.2.3.RELEASE is missing, no dependency information available

**Comment by cppwfs** [comment]
In this case it looks like spring-cloud-dataflow-rest-client didn't get propagated to maven central.  You can add:
```
 <repository>
    <id>spring-releases</id>
    <name>Spring Releases</name>
    <url>http://repo.spring.io/release</url>
    <snapshots>
        <enabled>false</enabled>
    </snapshots>
 </repository>
```
to your settings file.  I will create an issue for the the propogatin issue.

**Comment by cppwfs** [comment]
The original issue seems to be resolved.  The issue spring-cloud-dataflow-rest-client dependency has been recorded in https://github.com/spring-cloud/spring-cloud-dataflow/issues/1981.   If you identify another problem please feel free to open another issue.  Thanks for the feedback.
