### ISSUE TITLE
Consider refactoring ModuleDeployer api

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#198]
There seem to be numerous issues with `ModuleDeployer` especially when trying to use it with tasks.

## ModuleDeploymentRequest.getCount()
Clearly `ModuleDeployer` was designed for stream modules, not tasks. `Count` makes sense for streams but it has no default meaning in tasks and one should ask what a deployer should do with count other than `1`. We could silently discard it but that'd be wrong because it's part of a api contract.

## ModuleDeployer.undeploy(ModuleDeploymentId) and status(ModuleDeploymentId)
This is a big problem for tasks because `ModuleDeploymentId` has a group and a label. With `task create --name foo --definition timestamp` we'd get something like `foo.timestamp` for `ModuleDeploymentId`.

If we launch multiple task instances and only info in `undeploy()` and `status()` is `foo.timestamp`, thus making it impossible to match an tasks running in i.e. yarn if we have multiple instances. Let's assume we don't support multiple concurrent instances, we may have multiple existing instances which are already either succeed or failed. Which one we should pick up for `status()`.

There is #110 which also relates to these issues. It also clearly explains that for `undeploy()` we need more info passed than just what available from `ModuleDeploymentId`.

For example on yarn I can use submitted app instance `name` field to store some info about a running task. I currently use something like `scdtask:foo:timestamp` which I need to map back when either `undeploy()` or `status()` is called. During a `deploy()` I could pass more info to that `name` field, i.e. if some kind of unique id is available.

## Refactoring
We could either create a new `TaskDeployer` for stuff needed in tasks or fix `ModuleDeployer`.

**Comment by pperalta** [comment]
Handling tasks was not a design goal for the `ModuleDeployer` API. I suggest creating a `TaskLauncher` interface with the following methods to start with:

* `launch`
* `cancel`

It is possible that an SPI implementation will have a single class that implements both `ModuleDeployer` and `TaskLauncher`, but I think these should be split up at the interface level.

**Comment by sabbyanandan** [comment]
Spring Cloud Deployer project defines these contracts and `TaskLauncher` specs is part of it already. So, this is not applicable anymore.
