### ISSUE TITLE
stateful partitioning/sharding

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-dataflow#1980]
In chapter stream partitioning you desribe how to split data exchange packages using partitions on the message broker. For solution where you have to optimize heavy on the caching (local cache because of remote roundtrip overhead or memory cache because of massive DISK IO on the same datastore for all paralell running access operations resulting in perfoemance bottlenck) of data in your app/microservice/dataflow/function instances. The caching in terms of microservice architecture is part of the microservice/functions itself, so you result in having a statefull instance which is holding a portion of the cached datasource. Because of this partitioning on the data processor (neither source or sink which is the event broker layer ib between) you need to have partitioning aka sharding in front - a kind offacade that routes to the correct instance with the shard of cached data that is needed to process your request with optimal performance without read through.

There is no solution/pattern in spring dataflow till now, is there?
I like the the solution of metaparticle which creates a proxy facade using kubernetes services, calculate hash key from url pattern and route to that the instance holding the shard with the mathing partition.
https://metaparticle.io/tutorials/java-sharding/

**Comment by sabbyanandan** [comment]
Hi, @cforce. Have you looked at [Kafka Streams](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RC1/reference/htmlsingle/#_kafka_streams_binding_capabilities_of_spring_cloud_stream) binder implementation in Stream?  The said stateful computing could be done more _natively_ using the KStreams API from within the processor-application. 

KStreams comes with RocksDB as the default state-store (it can be pluggable). Apart from simple computing, you can also do stateful table-joins and interactive queries at this level. Here are a few [samples](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/kafka-streams) on this subject. KStreams support is evolving rapidly, and we hope to continue to improve the user experience.

Outside of this, we don't have other plans to explore stateful store implementations in Stream/SCDF.
