### ISSUE TITLE
Skipper reverse engineered stream definition DSL can skip implicit dataflow properties

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1982]
When the stream definition DSL is reverse engineered by parsing through the Skipper release manifest, we can filter out the implicit Data Flow properties such as the SCSt binding properties, metrics properties and some of the data flow properties from stream application properties list.

**Comment by sabbyanandan** [comment]
We should only remove stream specific properties binder, metrics, etc.
