### ISSUE TITLE
Update reference guide for all active SPIs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#200]
The [architecture section](http://docs.spring.io/spring-cloud-dataflow/docs/1.0.0.M1/reference/html/_spring_cloud_data_flow_architecture.html#_components) in the reference guide still includes old SPI links and it needs updated with the right SPI specific repos.

**Comment by trisberg** [comment]
The getting-started section in the reference guide needs to be updated for all relevant SPIs
