### ISSUE TITLE
Document setting freeDiskSpacePercentage

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2002]

**Comment by markpollack** [comment]
See if this fixes issue @viniciusccarvalho has running tests on machine that has disk space below the threshold.

Let's decide if we want to lower the default value, seems like we should.

**Comment by sabbyanandan** [comment]
1) In skipper-mode, overriding the % to 1 via `spring.cloud.skipper.server.platform.local.accounts[default].freeDiskSpacePercentage=1`; everything works as expected.

![image](https://user-images.githubusercontent.com/1562654/35529009-80d48962-04e4-11e8-9035-1ab66a2ffe4f.png)

2) In the classic mode, with `spring.cloud.deployer.local.freeDiskSpacePercentage=8`, it appears to take into account, too.

![image](https://user-images.githubusercontent.com/1562654/35529298-7a7174f8-04e5-11e8-8489-e0d8f9c81481.png)
