### ISSUE TITLE
Stream Details Page shows stream twice

### ISSUE THREAD

**Issue by wlund-pivotal** [spring-cloud/spring-cloud-dataflow#2004]
I'm checking to see if this has been fixed.  I'm seeing it in the PCF-SCDF console and I believe that's a version behind but you get two copies of the stream details when viewing the stream details page on the first time after deployment.  Subsequent views display fine.

<img width="1440" alt="screen shot 2018-01-26 at 3 54 26 pm" src="https://user-images.githubusercontent.com/5314240/35465681-9fa41e90-02b2-11e8-9b89-0d822fb1da59.png">

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#608
