### ISSUE TITLE
Test samples against 1.3 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2008]
Streams
- [x] Java DSL - @viniciusccarvalho 

- [x] HTTP to Cassandra - @viniciusccarvalho 

- [x] HTTP to MySQL - @viniciusccarvalho 

- [ ] HTTP to Gemfire - @tzolov 

- [ ] Gemfire CQ to Log Demo - @tzolov 

- [ ] Gemfire to Log Demo - @tzolov 

Custom Processor

- [ ] Task and Batch - @cppwfs 
- [ ] Batch Job on Cloud Foundry - @cppwfs 
- [ ] Batch File Ingest - @cppwfs 

Analytics
- [x] Twitter Analytics - @sabbyanandan 

Data Science
- [x] Species Prediction - @sabbyanandan 

Functions
- [x] Using Spring Cloud Function - @sabbyanandan

**Comment by sabbyanandan** [comment]
While testing [Spring Cloud Function sample](https://docs.spring.io/spring-cloud-dataflow-samples/docs/current/reference/htmlsingle/#_functions_in_spring_cloud_data_flow), I ran into the following error.

> Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: URL resource with version as part of its path is not supported.

The sample uses "http" resolution for the function-runner app; while parsing the Resource URI, given that the URL includes version in 2-places (1 in path; 1 in artifact name), this [logic won't accept](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/support/ResourceUtils.java#L61) it as a valid http-schema. Hence, it fails with the above error.

After discussing with @markpollack (also, @tzolov), we have concluded that it is a known design requirement. With that in mind, we will do the following.
1) Update the sample as alpha/experimental 
2) Cut 1.0 M1 for `function-runner` apps
3) Change the app registration command from "http" to "maven" URI
4) Verify the sample works on SCDF 1.3

**Comment by viniciusccarvalho** [comment]
PR fixing some doc instructions: https://github.com/spring-cloud/spring-cloud-dataflow-samples/pull/48

**Comment by sabbyanandan** [comment]
SCFn sample fixed via: spring-cloud/spring-cloud-dataflow-samples#49

**Comment by sabbyanandan** [comment]
While I was at it, I also verified "Species Prediction" and "Twitter Analytics". Looks good.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-samples#50
