### ISSUE TITLE
Prevent un-registration of an app-version if it is already in use

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2013]
As a user, I'd like for the un-registration routine to applies on unused App-versions. If the app-version is in use, the system should prevent me from deleting it.

**Notes:**
```
1) List versions:

dataflow:>app list --id processor:xfmr
╔══════╤══════════════════════════════════════╤════╤════╗
║source│              processor               │sink│task║
╠══════╪══════════════════════════════════════╪════╪════╣
║      │> xfmr-0.0.1.BUILD-20180129.011003-8 <│    │    ║
║      │xfmr-0.0.1.BUILD-20180129.015528-12   │    │    ║
║      │xfmr-0.0.1.BUILD-20180129.021451-13   │    │    ║
║      │xfmr-0.0.1.BUILD-20180129.200519-1    │    │    ║
╚══════╧══════════════════════════════════════╧════╧════╝

2) Create a stream with default version:

dataflow:>stream create foo --definition "time | xfmr | log"
Created new stream 'foo'

3) Unregister the default version:

dataflow:>app unregister --name xfmr --type processor
Successfully unregistered application 'xfmr' with type processor

4) List versions:

dataflow:>app list --id processor:xfmr
╔══════╤═══════════════════════════════════╤════╤════╗
║source│             processor             │sink│task║
╠══════╪═══════════════════════════════════╪════╪════╣
║      │xfmr-0.0.1.BUILD-20180129.015528-12│    │    ║
║      │xfmr-0.0.1.BUILD-20180129.021451-13│    │    ║
║      │xfmr-0.0.1.BUILD-20180129.200519-1 │    │    ║
╚══════╧═══════════════════════════════════╧════╧════╝
```

**Acceptance:**
- No-3 from above should not be allowed since it is already in use in the `foo` stream
- Return a user-friendly message (maybe: `The app you're trying to unregister is already in use on "Foo" stream`?) 
- Shell/UI should use the returned message to notify it to the user

**Comment by sabbyanandan** [comment]
Depending on what comes out of spring-cloud/spring-cloud-dataflow#1871, we may have to adapt the validation routine accordingly.

**Comment by ilayaperumalg** [comment]
I guess we need to keep this open until the issue discussed [here](https://github.com/spring-cloud/spring-cloud-dataflow/pull/2081#discussion_r172146528) is addressed or modify the scope of the story only for the stream that is `deployed`.
