### ISSUE TITLE
Inherit ENV variables in Windows OS

### ISSUE THREAD

**Issue by VovaViter** [spring-cloud/spring-cloud-dataflow#2017]
Hi All.

I spent much time when try finding problems with inheritance ENV variables such as PATH on Windows 10. 
Please fix this problem in LocalDeployerProperties and change envVarsToInherit array according to the OS. On  Windows 10 ENV variables written in camel case.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-deployer-local#95
