### ISSUE TITLE
Runtime Applications WebService - pagination error

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow#2037]
**Context**: have more than 2 runtime applications available

Call `/runtime/apps?page=0&size=1` should return the following pagination:

`"page":{"size":1,"totalElements":2,"totalPages":2,"number":0}`

instead of 

`"page":{"size":1,"totalElements":1,"totalPages":1,"number":0}`

**Comment by markpollack** [comment]
@oodamien @tzolov This wasn't backported to the 1.3.x branch
