### ISSUE TITLE
LocalDeployerProperties not using validation constrains

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2045]
Build produces this warning

```2018-02-14 03:20:04.482  WARN 1181 --- [           main] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.springframework.cloud.deployer.spi.local.LocalDeployerProperties contains validation constraints but had not been annotated with @Validated.```

**Comment by chandhu455** [comment]
@sabbyanandan  Is this issue still valid?

**Comment by ilayaperumalg** [comment]
@chandhu455 Maybe not. I don't see this validation warning anymore on the latest build.

Thanks for checking. Closing this out as invalid. 
But, feel free to comment or re-open if you see any issue with that.
