### ISSUE TITLE
SCDF needs ability to set table prefix for its repository tables.

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#2048]
Was unable to find a way to set the prefix for dataflow repository tables.  Task and batch have these out of the box.

**Comment by sabbyanandan** [comment]
Another hit from the community at [StackOverflow](https://stackoverflow.com/questions/54589126/how-can-spring-cloud-dataflow-server-use-new-tables-with-custom-prefix-create).
