### ISSUE TITLE
Unable to import apps

### ISSUE THREAD

**Issue by Sutty100** [spring-cloud/spring-cloud-dataflow#2063]
I'm running version 1.3.1.RELEASE of spring cloud dataflow for Kubernetes with Kafka as the broker (not running in Kubernetes) and using 1.3.1.RELEASE of the shell.

I can connect to the spring cloud data flow server via the shell or the gui without a problem. However when I try and import any apps I get the following error
`app import --uri http://bit.ly/stream-applications-kafka-docker`
`Error when registering applications from http://bit.ly/stream-applications-kafka-docker: Access is denied`

I have checked by running wget on the pod that is running the server and it can pull from the url so I do not think it is simple network connectivity. There is nothing in the log of the server either to suggest something went wrong or indeed that it even attempted to perform the action requested by the shell.

**Comment by sabbyanandan** [comment]
Hi, @Sutty100. Do you have security enabled? If so, does the user have `ROLE_CREATE` privilege set? It'd be good to review `/about` endpoint output, too (of course, you can mask all sensitive data from the output before posting).

**Comment by Sutty100** [comment]
Ah my bad! I missed that part in the docs and assumed admin would have all permissions! Working now I have assigned that role to the admin user! Thanks 👍
