### ISSUE TITLE
Stream deployment properties specific to volume and volume mounts not working in 1.3.1

### ISSUE THREAD

**Issue by bondalapati98** [spring-cloud/spring-cloud-dataflow#2075]
deployment properties specific to volume and volume mounts which worked with scdf 1.3.0 version are not working anymore with 1.3.1 version. how do we fit the same with Skipper in the play?

Streams are not getting deployed on kubernetes.

Here is the stream definition that I am using.

stream deploy SHInvDocStream --properties "deployer.retaildatasink.kubernetes.volumes=[{name: 'storehubnfs', persistentVolumeClaim: { claimName: 'storehubnfspvc'}}],deployer.retaildatasink.kubernetes.volumeMounts=[{name: 'storehubnfs', mountPath: \"/nfs/storehub\"}],deployer.retaildatasource.kubernetes.volumes=[{name: 'storehubnfs', persistentVolumeClaim: { claimName: 'storehubnfspvc'}}],deployer.retaildatasource.kubernetes.volumeMounts=[{name: 'storehubnfs', mountPath: \"/nfs/storehub\"}],deployer.retaildataprocessor.kubernetes.volumes=[{name: 'storehubnfs', persistentVolumeClaim: { claimName: 'storehubnfspvc'}}],deployer.retaildataprocessor.kubernetes.volumeMounts=[{name: 'storehubnfs', mountPath: \"/nfs/storehub\"}]"

**Comment by bondalapati98** [comment]
Looks like the issue is the request is routed to local deployer instead of kubernetes deployer.

Could you please provide instructions with deploying on kubernetes through skipper.

**Comment by sabbyanandan** [comment]
Hi, @bondalapati98. If you're using SCDF + Skipper, you'd have to configure the deployment platforms in Skipper and use the configured platform while deploying the stream in SCDF via `--platformName` property. 

Skipper comes out-of-the-box with Local-deployer configuration and that you can disable it (via `enableLocalPlatform` property). If nothing is selected, by default, Skipper uses the Local-deployer config to deploy app-packages. 

To use in Kubernetes, however, you _must_ provide Kubernetes configurations - see [here](https://docs.spring.io/spring-cloud-skipper/docs/1.0.1.RELEASE/reference/htmlsingle/#tour-kubernetes).b Here's an example in [SCDF](https://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.3.1.RELEASE/reference/htmlsingle/#streams-using-skipper).

**Comment by bondalapati98** [comment]
We have disable the local server and defined kubernetes config in yaml file and loaded when starting the skipper server. Still the deployment of streams are failing.

**Comment by bondalapati98** [comment]
Here is the yaml file
{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "skipper",
    "namespace": "default",
    "selfLink": "/apis/extensions/v1beta1/namespaces/default/deployments/skipper",
    "uid": "9e8cb353-1c0d-11e8-bcda-080027bc5b74",
    "resourceVersion": "18413788",
    "generation": 6,
    "creationTimestamp": "2018-02-27T22:29:05Z",
    "labels": {
      "app": "skipper"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "4"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "skipper"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "skipper"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "skipper",
            "image": "springcloud/spring-cloud-skipper-server:1.0.1.RELEASE",
            "ports": [
              {
                "containerPort": 80,
                "protocol": "TCP"
              }
            ],
            "env": [
              {
                "name": "SPRING_CLOUD_KUBERNETES_CONFIG_NAME",
                "value": "scdf-config"
              },
              {
                "name": "SPRING_APPLICATION_JSON",
                "value": "{\"spring.cloud.skipper.server.enableLocalPlatform\" : false, \"spring.cloud.skipper.server.platform.kubernetes.accounts.dev-admin.namespace\" : \"development\", {\"spring.cloud.skipper.server.platform.kubernetes.accounts.dev-admin.environmentVariables\" : \"SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=${KAFKA_SERVICE_HOST}:${KAFKA_SERVICE_PORT}, SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=${KAFKA_ZK_SERVICE_HOST}:${KAFKA_ZK_SERVICE_PORT}\"},\"spring.cloud.skipper.server.platform.kubernetes.accounts.dev-admin.memory\" : \"1024Mi\",\"spring.cloud.skipper.server.platform.kubernetes.accounts.dev-admin.createDeployment\" : true}"
              }
            ],
            "resources": {
              "limits": {
                "cpu": "1",
                "memory": "1Gi"
              },
              "requests": {
                "cpu": "500m",
                "memory": "640Mi"
              }
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": 1,
        "maxSurge": 1
      }
    }
  },
  "status": {
    "observedGeneration": 6,
    "replicas": 1,
    "updatedReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2018-02-27T22:29:05Z",
        "lastTransitionTime": "2018-02-27T22:29:05Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      }
    ]
  }
}

**Comment by bondalapati98** [comment]
when we query from skipper, platform list, it doesnt show the kubernetes. Not sure what else we are missing. Please let us know.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-server-kubernetes#263
