### ISSUE TITLE
Composed Task Runner needs to support executing a group of tasks when using a transition

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#2077]
Currently when using a transitional for example 
AAA  'COMPLETED'->BBB  'FAILED'->CCC && DDD && EEE. After AAA fires and the exit status is `COMPLETED` then fire BBB.  If the exit status is `FAILED` then fire CCC.   If the exit status is neither `COMPLETED` nor `FAILED` then DDD && EEE.
Could we create a grouping where on the `FAILED` case `CCC && DDD && EEE`.
something like :  AAA  'COMPLETED'->BBB  'FAILED'->(CCC && DDD && EEE)

**Comment by cppwfs** [comment]
Please refer to issue https://github.com/spring-cloud/spring-cloud-dataflow-server-yarn/issues/173.  While this issue will give the user a resolution, it just does it in a different way that is more in line with how CTR is designed.

**Comment by sabbyanandan** [comment]
Stale; closing.
