### ISSUE TITLE
Add support for mapping of LDAP groups to ROLES

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2084]
As a user, I'd like to configure the mapping of LDAP AD groups against the SCDF roles (VIEW, CREATE, and MANAGE), so I can define the authorization rules in SCDF at the LDAP group level.

See this [SO thread](https://stackoverflow.com/questions/49078256/ldap-authn-and-authz-for-spring-cloud-data-flow) for background.

**Acceptance:**
- I can configure an AD group for example `ROLE_APP_MYAPPLICATION_AUTHZ_VIEW` against SCDF's `ROLE_VIEW` role transparently as env-var or properties or in the YAML. Similarly, `ROLE_CREATE` and `ROLE_MANAGE` roles can also be mapped to the AD groups
- With LDAP turned-on and the above "group<->role" mapping, I shouldn't have to do anything else. The system interprets the mapping to determine the authorization boundaries automatically
- Shell, APIs, RESTTemplate, and the UI obey the authorization boundaries
- A sample configuration is included in the ref. guide

**Comment by ghillert** [comment]
Depends on https://github.com/spring-cloud/spring-cloud-common-security-config/issues/7
