### ISSUE TITLE
Mark AppRegistration repository as @Transactional

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2086]
As a developer, I'd like to mark the bulk app-unregistration control to run inside a transaction.

This is a pre-requisite for spring-cloud/spring-cloud-dataflow#2031, where we will have to first identify the root-cause and further refine the overall workflow.

**Comment by ilayaperumalg** [comment]
Looks like we already [have](https://github.com/spring-cloud/spring-cloud-dataflow/blob/533b753f0d26bdb8978e395d093435643cee2aa4/spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/repository/AppRegistrationRepository.java#L32) it as `@Transactional`.

**Comment by sabbyanandan** [comment]
@markpollack: Any other recommendations?

**Comment by sabbyanandan** [comment]
Since it is already `@Transactional` in [v2.0](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/repository/AppRegistrationRepository.java#L32), I'm marking this as invalid.
