### ISSUE TITLE
Enable trackHistory as a deployment property

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#209]
Related to the feature reported [here] (https://github.com/spring-cloud/spring-cloud-stream/issues/196), we would like to have a `trackHistory` as a deployment property that can be set via DSL.

**Comment by markfisher** [comment]
we need to ensure that any of the `BindingProperties` are passed along, so that there is no need to make changes on the dataflow side for each property that may be added in the future
