### ISSUE TITLE
Document docker-compose usage guide

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2093]
As a developer, I'd like to document the `docker-compose up` usage guide for the local-server.

This is a continuation of spring-cloud/spring-cloud-dataflow#2040.

**Acceptance:**
- Update the "Installation" section to have 2 sub-sections
   - *Manual Setup* - includes the current installation steps
   - *Docker Compose* - includes the Docker steps
- Under *Docker Compose*
  - List of prerequisites (java, docker, vm etc.)
  - Link the `docker-compose.yml` file
  - Explain the default components
  - Include steps to switch between Rabbit vs. Kafka
  - Include steps to switch RDBMS
  - Include steps to add Redis
- Explain how to get started
- Explain how to get to the app-logs with an example (possibly `ticktock` stream)
- Add note re: Docker images and local registry cache

**Comment by chrisjs** [comment]
documentation was rolled into: https://github.com/spring-cloud/spring-cloud-dataflow/pull/2053
