### ISSUE TITLE
Possibility to create a single processor kafka stream application without source and sink

### ISSUE THREAD

**Issue by orchesio** [spring-cloud/spring-cloud-dataflow#2096]
Since Spring cloud support Kafka stream, I'm wondering does it make sense to allow creating of a dataflow with a single kafka stream based processor, without having to create extra source and sink, given that kafka stream itself takes care of reading from source topic and dump to output topic?

**Comment by sabbyanandan** [comment]
Hi, @orchesio. In SCDF, you can use [named-destinations](https://docs.spring.io/spring-cloud-dataflow/docs/1.3.1.RELEASE/reference/htmlsingle/#spring-cloud-dataflow-stream-dsl-named-destinations) at the position of the source or sink and that could feed data in or out of your KStream processor respectively. 

For example:

> :dataFromTopic > kstream-processor > :dataToTopic

Here, `dataFromTopic` is the topic where you get the data from and the `kstream-processor` is your business logic and `dataToTopic` is the topic where the data is going downstream. 

Here's a [video](https://www.youtube.com/watch?v=l8SgHtP5QCI&feature=youtu.be) of the UI experience in action.

**Comment by orchesio** [comment]
That's what I'm looking for! Thanks!
