### ISSUE TITLE
Shell should validate module options used

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#210]
It seems that there is no validation of references of module options right now. I can mistype and option and the stream is still accepted and deployed. This makes it too easy to make a silly mistake when defining streams. We should at least validate all options that are directly defined for a module, if possible we should also validate spelling of other options like `--server.port`, `--spring.datasource.url` etc.

**Comment by ericbottard** [comment]
The problem is ... there is no way to know for sure that something is "an option". I think at best we should emit a warning, because just because something is not listed in the metadata json file, does not mean the app does not "use" it.

**Comment by sabbyanandan** [comment]
App properties and the orchestration specifics in shell have been completely overhauled. The app and the list of properties should now be fixed.

**Comment by markpollack** [comment]
I think there is more we can do here.  In a 80/20 case a user is most likely to enter whitelisted properties.  I think anything in the whitelist (so say server.port for http) is a candidate for validation since we know that is an option.

**Comment by sabbyanandan** [comment]
This is not relevant anymore.
