### ISSUE TITLE
Explore Micrometer + Elastic integration

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2106]
As a developer, I'd like to research the feasibility of Micrometer + Elastic backend, so we could use it as the foundation for data pipeline monitoring and observability.

**Acceptance:**
- Research Elastic + Kibana integration specifics for Boot apps
- Study the applicability of Kibana's Angular components
- Design and document REST controllers 
- Document the Metrics Collector vs. Elastic boundaries
- Sketch out security requirements (specifically, OAuth)

**Comment by jvalkeal** [comment]
New micrometer snapshots have integration to elastic. It has an issue micrometer-metrics/micrometer#506 I saw when I tried it, something what Jon is looking for. In a meanwhile I suppose we can try to look other things.

**Comment by sabbyanandan** [comment]
The scope of this spike is complete via: https://docs.google.com/document/d/1_MmyONzpQWAzOfoD4Utie7QgFKPgsLEFjWHaEE9M7ZM/edit#heading=h.p3q56u3cixi7
