### ISSUE TITLE
JS exception when trying to define transition in CTR

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-dataflow#2115]
I'm getting js error when trying to define the transition in CTR with `1.4.0.RELEASE`, `1.3.0.RELEASE` doesn't suffer from this...
![image](https://user-images.githubusercontent.com/6664858/37654550-36fc7442-2c4b-11e8-98a0-b079d6748cf5.png)

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#693
