### ISSUE TITLE
Oracle 11 Scripts Create Stream

### ISSUE THREAD

**Issue by guichafy** [spring-cloud/spring-cloud-dataflow#2117]
Hi guys, I had to make a script change to work on oracle 11
> spring-cloud-dataflow/spring-cloud-dataflow-server-core/src/main/resources/schemas/oracle/streams.sql 

VARCHAR(MAX) -> not working on Oracle 11.
![image](https://user-images.githubusercontent.com/9120686/37835515-19c7d1aa-2e8f-11e8-96f3-929f37b2a57e.png)

I changed to VARCHAR2 (4000) - Limit on oracle

**Comment by sabbyanandan** [comment]
H@guichafy: Thanks for reporting it! We will look into it.
