### ISSUE TITLE
manifest not found for server-local:1.4.0.RELEASE

### ISSUE THREAD

**Issue by mayboroda** [spring-cloud/spring-cloud-dataflow#2122]
In Cloud Data Flow Reference Guide in [getting started section](https://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started) on the step 2 (`docker-compose up`) I'm getting this:
```bash
➜  cloud-data-flow docker-compose up -d  
Pulling dataflow-server (springcloud/spring-cloud-dataflow-server-local:1.4.0.RELEASE)...
ERROR: manifest for springcloud/spring-cloud-dataflow-server-local:1.4.0.RELEASE not found
```

**Comment by sabbyanandan** [comment]
Hi, @mayboroda. Thanks for reporting! It looks like we missed promoting the 1.4.0.RELEASE tag. We are on it.

**Comment by sabbyanandan** [comment]
It should be complete now (see [here](https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server-local/tags/)). Please try it out and let us know if you see any other issues with it.

**Comment by sabbyanandan** [comment]
@mayboroda: If you see any other anomaly, feel free to open a new issue.  Thanks again!
