### ISSUE TITLE
CTR with joined branches

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-dataflow#2128]
Hi
We have complex CTR graph that should run branches in parallel and I can't define proper join DSL. The simplified sample that reproduces the error is `<3: timestamp || 1: timestamp && timestamp || 2: timestamp && timestamp>`. 
![image](https://files.gitter.im/spring-cloud/spring-cloud-dataflow/PIAM/image.png)

The error I'm getting is `Duplicate app name`.
 How do I join `1` and `2` to `timestamp` and run `3` in parallel?
Thanks

**Comment by sabbyanandan** [comment]
Hi, @jvmlet. In your case, 1 and 2 are made of two apps and the apps in them need to be explicitly labeled. 

Definition:
> <<1: timestamp && 4: timestamp || 2: timestamp && 5: timestamp> && timestamp || 3: timestamp>

Graph:
![image](https://user-images.githubusercontent.com/1562654/38253053-8a83a0c6-370a-11e8-96d7-e0bea393bdbc.png)

We have left a few messages in gitter on this matter, too. Let's continue there to avoid duplicate conversations. Also, for questions like this, it'd be great if you can post in StackOverflow/Gitter going forward.
