### ISSUE TITLE
Spring Batch 4 support?

### ISSUE THREAD

**Issue by PascalSchumacher** [spring-cloud/spring-cloud-dataflow#2141]
Can I use spring-cloud-dataflow 1.4 to run and monitor Spring Batch 4 jobs?

Sorry for raising an issue for a simple question, but I could not find this information anywhere.

**Comment by mminella** [comment]
In conjunction with Spring Cloud Task, yes you can.  Going forward, please ask these questions either in Gitter or on StackOverflow.  Thanks!
