### ISSUE TITLE
Improve skipper mode in dataflow shell

### ISSUE THREAD

**Issue by mv78** [spring-cloud/spring-cloud-dataflow#2142]
Currently, there are many issues regarding escaping characters in stream properties.
Currently, it looks like we need to double escape SpEL expressions in property files when shell is used in skipper mode. The escaping gets even more trickier since you need to escape it for dataflow shell and then since shell is passing property values to skipper via REST API calls it also needs to be escaped for http calls. It would be grate to simplify the escaping of expressions or at least provide better documentation on how to property escape expressions being passed from property file with skipper mode. Moreover, better error handling is needed. When deploying stream with property file the dataflow shell returns error saying unexpected character found; however the call to skipper is successful and stream gets deployed but the dataflow state is messed up since it shows as stream is not deployed. From this point, the stream is in bade state and can not be upgraded or deleted neither from dataflow shell or skipper and manual database cleanup is needed.

**Comment by sabbyanandan** [comment]
Hi, @mv78. This is great feedback. Thanks!

We can definitely revisit the escape-char semantics and see if we can bring consistency. I agree it is not a good experience right now, but we will improve it.

**Comment by markpollack** [comment]
It sounds like there maybe a bug we can fix - in  particular 


* you mention "dataflow shell returns error saying unexpected character found; however the call to skipper is successful and stream gets deployed but the dataflow state is messed up since it shows as stream is not deployed" 
* better documentation on how to property escape expressions being passed from property file with skipper mode

Does that mean it works correctly when not in skipper mode.  If you could cut-n-paste some sample stream usage that would help us greatly.

**Comment by mv78** [comment]
Command failed
org.springframework.cloud.dataflow.rest.client.DataFlowClientException:
115E:(pos 236): unexpected data in stream definition '#'
:some-events > filter
--spring.cloud.stream.bindings.applicationMetrics.destination=metrics
--spring.cloud.stream.instanceCount=1
--filter.expression=#jsonPath(payload,'$.partnerName') matches '^(Partner
One|Partner Two)$' && #jsonPath(payload,'$.prod') matches
'^(A-12345|B-12334)$' && #jsonPath(payload,'$.fileNumber') matches '^\S+$'
| header-enricher
--header.enricher.headers=entity=#jsonPath(payload,'$.parentEntityType')
 action=#jsonPath(payload,'$.actionType')
--spring.cloud.stream.bindings.applicationMetrics.destination=metrics
--spring.cloud.stream.instanceCount=1 | httpclient
--spring.cloud.stream.bindings.applicationMetrics.destination=metrics
--httpclient.http-method=GET --spring.cloud.stream.instanceCount=1
--httpclient.url-expression='
http://some-service:8080/product?id='+payload.id | custom-transformer
--spring.cloud.stream.bindings.applicationMetrics.destination=metrics
--spring.cloud.stream.bindings.output.contentType=application/json
--spring.cloud.stream.instanceCount=1 > :destination-events

The stream gets created in Kubernetes but state is broken in dataflow shell.

I am using SCDF 1.4 and same shell version with Skipper 1.0.2.

**Comment by mv78** [comment]
During deployment i am passing property file with this value:

app.filter.expression : #jsonPath(payload,'$.partnerName') matches
'^(Partner One|Partner Two)$' && #jsonPath(payload,'$.prod') matches
'^(A-12345|B-12345)$' && #jsonPath(payload,'$.fileNumber') matches
'^\\\\S+$'
app.header-enricher.headers :
entity=#jsonPath(payload,'$.parentEntityType') \\n
action=#jsonPath(payload,'$.actionType')
app.httpclient.url-expression : '
http://some-servicee:8080/product?id='+payload.id

**Comment by tzolov** [comment]
Following snipped can reproduce the issue:
In `skipper` mode create a stream `ec`:
```
stream create --name ec --definition "http --port=9000 | filter --expression=\"#jsonPath(payload,'$.name') matches '\\\d*'\" | log"
```
The deployment attempt 
```
stream deploy --name ec --properties "deployer.*.local.inheritLogging=true"
```
will show a error in the shell (due to escape chars issues in the StreamDefinitionToDslConverter::toDsl method) but Skipper will successfully deploy it. 

The solution though is not trivial, especially if we need to have the same expressions syntax for both `skipper` and non-skipper (e.g. classic) mode.

**Comment by tzolov** [comment]
Hi @mv78 , 

The PR, auto-escapes the single backslash characters in the properties send to Skipper. Only properties with the `expressions` keyword in their names are escaped. 

That means that you can use exactly the same expression syntax as for non-Skipper (e.g. Classic) mode.  Following example illustrates it:
1. Create `testBackslashExpressionProperties.yaml` with content like this:
```
app.filter.expression: "#jsonPath(payload,'$.partnerName') matches '^(Partner One|Partner Two)$' && #jsonPath(payload,'$.prod') matches '^(A-12345|B-12345)$' && #jsonPath(payload,'$.fileNumber') matches '^\\S+$'"
```
Note, that the matches reg. expressions are escaped only once!
Also mind the double-quotes around the expression properties!

2. Create and deploy `ec3` stream: 
```
dataflow:>app import --uri http://bit.ly/Celsius-SR1-stream-applications-rabbit-maven
dataflow:>stream create --name ec3 --definition "http --port=9000 | filter | log"
dataflow:>stream deploy --name ec3 --propertiesFile ../tmp/testBackslashExpressionProperties.yaml
dataflow:>stream list
╔═══════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╤══════════════════════╗
║Stream │                                                    Stream Definition                                                    │        Status        ║
║ Name  │                                                                                                                         │                      ║
╠═══════╪═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════════════════╣
║ec3    │http --server.port=9000 | filter --filter.expression="#jsonPath(payload,'$.partnerName') matches '^(Partner One|Partner  │The stream has been   ║
║       │Two)$' && #jsonPath(payload,'$.prod') matches '^(A-12345|B-12345)$' && #jsonPath(payload,'$.fileNumber') matches '^\S+$'"│successfully deployed ║
║       │| log                                                                                                                    │                      ║
╚═══════╧═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╧══════════════════════╝
```
3. Post a json message
```
dataflow:>http post --target http://localhost:9000 --data '{"partnerName":"Partner One", "prod":"A-12345", "fileNumber":"NOSPACES"}' --contentType application/json
```
Later yields log entry like this:
```
2018-05-01 10:33:47.086  INFO 5493 --- [c3.filter.ec3-1] log-sink                                 : {"partnerName":"Partner One", "prod":"A-12345", "fileNumber":"NOSPACES"}
```

**Comment by sabbyanandan** [comment]
Hi, @mv78. The issue is marked for 1.5 RC1. You can pull the PR (spring-cloud/spring-cloud-dataflow#2167) and validate it for us, though. That'd be helpful.
