### ISSUE TITLE
The StreamDefinitionController#aggregateState method should be moved to the Service layer

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow#2174]
Currently the `StreamDefinitionController#aggregateState` is a static method in the controller which is used inside the `AppDeployerStreamDeployer` and `SkipperStreamDeployer` services. 

This is a follow up of the #1892 refactoring story.

**Comment by sylank** [comment]
@sabbyanandan I think this issue is out of date. The `aggregateState` function is moved to `org.springframework.cloud.dataflow.server.stream.StreamDeployerUtil`

**Comment by ilayaperumalg** [comment]
@sylank Thanks for checking this out. We can close this.
