### ISSUE TITLE
Polish JPA Infrastructure

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2179]
- [ ] Ensure that `@transactional` is applied only on concrete implementations not interfaces
- [ ] On `@EnableJpaRepositories` set `enableDefaultTransactions=false`,  I think transaction demarcations should be on Services only. However, Spring Data JPA by default makes all repositories transactional
- [ ] Consider setting `spring.jpa.open-in-view=false`. While it is the default in Boot, I don't necessarily see the use in our app. In most/all? use-cases we should eagerly fetch all data needed for the REST controllers rather than lazily fetch them.

**Comment by sabbyanandan** [comment]
In v2.0, we have reworked the JPA components entirely. This is not applicable anymore.
