### ISSUE TITLE
REST: Retain default http access to '/' as opposed to '/messages'

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#218]
As a user, I'd like to access the `http` port at the default `/` path [as supported by Spring XD], so it is backward compatible. Currently, I'm expected to include `/messages` in order to post messages to `http` port.

**Acceptance:**
* I'm able to post data to `http` port with default `/` path
* Accessing `/messages` path results in 404; in other words, it should be unsupported
* Related samples/examples are updated to reflect this change

**Comment by ilayaperumalg** [comment]
@sabbyanandan Do you mean the `http` source module that exposes the path pattern `/message`?

**Comment by ilayaperumalg** [comment]
Created https://github.com/spring-cloud/spring-cloud-stream-modules/pull/123 in SCS modules.

**Comment by sabbyanandan** [comment]
@ilayaperumalg: Correct. Since this is already moved to SCSM, I'll close it.
