### ISSUE TITLE
app imported error use bit.ly

### ISSUE THREAD

**Issue by koumingming** [spring-cloud/spring-cloud-dataflow#2182]
I use the "bit.ly/Celsius-SR1-stream-applications-rabbit-maven", but it not work. The error "Error reading from URL [http://bit.ly/Celsius-SR1-stream-applications-rabbit-maven]". Is any change about link? thk

**Comment by sabbyanandan** [comment]
Hi, @koumingming. The latest GA release bit.ly's are listed in the table [here](http://cloud.spring.io/spring-cloud-stream-app-starters/#stream-app-starters-and-spring-cloud-data-flow-). Try doing a `wget` or open it in the browser to make sure it is resolvable. For questions like this, please use Stackoverflow or Gitter going forward.

**Comment by koumingming** [comment]
Thank you @sabbyanandan ,I already read the guide lists,but it still not working.I thought the link changed before.I will check other reasons,Thank you.
