### ISSUE TITLE
task app import error use bit.ly

### ISSUE THREAD

**Issue by koumingming** [spring-cloud/spring-cloud-dataflow#2183]
I use "http://bit.ly/Clark-GA-task-applications-maven",but it not work,the error "Connection reset,server returned error: HTTP/1.1 500". Is any change about the link?thk

**Comment by sabbyanandan** [comment]
Hi, @koumingming. The latest GA release bit.ly's are listed in the table [here](http://cloud.spring.io/spring-cloud-stream-app-starters/#stream-app-starters-and-spring-cloud-data-flow-). Try doing a `wget` or open it in the browser to make sure it is resolvable. For questions like this, please use Stackoverflow or Gitter going forward.

**Comment by koumingming** [comment]
Thank you, @sabbyanandan .I will check other reasons.
