### ISSUE TITLE
Stream deploy: App. deployment properties deletion

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow#2184]
Create the following stream:
`http --server.port=4000 | file`

Deploy the stream (OK):
Change the server.port to 5000 (freetext or form builder)
Deploy the stream
You can see the DSL text is updated (`http --server.port=5000 | file`)

Re-Deploy the stream (NOK):
You can see the property `server.port` in the form builder / free text
If you remove this properties and deploy the stream, the property is still present.
You can see the DSL text is not updated (`http --server.port=5000 | file`)

**Comment by sabbyanandan** [comment]
I haven't seen this scenario come up in any customer/community conversation so far. Closing it for now.
