### ISSUE TITLE
Cant pass pod annotation that contain ":" in the value.

### ISSUE THREAD

**Issue by mv78** [spring-cloud/spring-cloud-dataflow#2200]
Currently we can use property "deployer.kinesis-sink.kubernetes.podAnnotations" to pass pod spec annotations. We use this to pass AWS role ARN "iam.amazonaws.com/role:arn:aws:iam::12345678:role/role-name"
Due to get annotation code in deployer that looks if split annotation pares have 2 values by splitting using ":". This fails since we have more than one colon in the value.

**Comment by sabbyanandan** [comment]
Thanks, @mv78. We will review this in the k8s-deployer via spring-cloud/spring-cloud-deployer-kubernetes#226. It'd be nice if we can avoid cross-posting it going forward.
