### ISSUE TITLE
Not able to import apps when setting up from docker compose file

### ISSUE THREAD

**Issue by kswar06** [spring-cloud/spring-cloud-dataflow#2212]
Hi All, I am new to Spring Cloud Data Flow and was trying to set up dataflow server on my local system using the docker-compose.yml. But I am getting the below error and my dataflow server is unable to import the apps from the repo. Please find the error stack below:

Note: I was able to create and work on the dataflow server last week but since yesterday I am not able to see any default apps on my dataflow-server using the default URL:  **http://localhost:9393/dashboard**

 **java.lang.IllegalArgumentException: Invalid format for app key 'cancelPage'in file. Must be <type>.<name> or <type>.<name>.metadata**
dataflow-server    |    at org.springframework.util.Assert.isTrue(Assert.java:92) ~[spring-core-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
dataflow-server    |    at org.springframework.cloud.dataflow.registry.AppRegistry.toValidAppRegistration(AppRegistry.java:156) ~[spring-cloud-dataflow-registry-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
dataflow-server    |    at org.springframework.cloud.dataflow.registry.AbstractAppRegistryCommon.lambda$null$1(AbstractAppRegistryCommon.java:114) ~[spring-cloud-dataflow-registry-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
dataflow-server    |    at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[na:1.8.0_111-internal]
.....
.....
..... (omitted all the unwanted lines)
**app-import_1       | wget: server returned error: HTTP/1.1 500
app-import_1       | Task apps imported
springclouddataflow_app-import_1 exited with code 0**

**Comment by sabbyanandan** [comment]
Hi, @kswar06. I'm sorry you're having trouble with it. Could you share the steps and the bit.ly version in use? See [reporting-issues](https://github.com/spring-cloud/spring-cloud-dataflow#reporting-issues) wiki for some guidance.

**Comment by kswar06** [comment]
Hi @sabbyanandan I downloaded the docker-compose file from the below link:
**wget https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v1.4.0.RELEASE/spring-cloud-dataflow-server-local/docker-compose.yml,** 
As stated in the quick start guide of Spring Data Flow. 
It states the below two versions:

 **wget -qO- 'http://dataflow-server:9393/apps' --post-data='uri=http://bit.ly/Celsius-SR1-stream-applications-kafka-10-maven&force=true'**;
echo 'Stream apps imported'
**wget -qO- 'http://dataflow-server:9393/apps'  --post-data='uri=http://bit.ly/Clark-GA-task-applications-maven&force=true';**
echo 'Task apps imported'

I hope this information helps. Just wanted to inform you that this was till last week but now its not.

**Comment by sabbyanandan** [comment]
Ah, I forgot you did the docker-compose experience, but thanks for reiterating that. It is a bit odd, though. I just tried it locally and everything came up as expected. Maybe you can share the Docker and OS versions in use.

Also, we have released 1.5 GA recently. Feel free to try it with v1.5 [docker-compose.yml](https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v1.5.0.RELEASE/spring-cloud-dataflow-server-local/docker-compose.yml).

**Comment by kswar06** [comment]
Hi @sabbyanandan , Thanks for the quick reply,following are the details that you asked for:
Docker Version 18.03.1-ce-win65 (17513)
OS Version:  Windows 10.

I shall try the new v1.5 too and let you know about the details.

Also want to add here that i even tried doing the import of app using the below command but it failed with the below stated error for v1.4:

**dataflow:>app import --uri http://bit.ly/Avogadro-SR1-stream-applications-kafka-10-maven
Error when registering applications from http://bit.ly/Avogadro-SR1-stream-applications-kafka-10-maven: Invalid format for app key 'cancelPage'in file. Must be <type>.<name> or <type>.<name>.metadata**

**Comment by kswar06** [comment]
Hi @sabbyanandan , as asked just tried the v1.5 docker compose file as mentioned above, but no luck.
It gives the below error:

**WARNING: The DATAFLOW_VERSION variable is not set. Defaulting to a blank string.
Creating network "v15_default" with the default driver
ERROR: no such image: springcloud/spring-cloud-dataflow-server-local:: invalid reference format**

**Comment by kswar06** [comment]
Hi @sabbyanandan ,

Thanks for the reply, it seems to be working now. I can see all the apps imported on the dataflow-server using the v1.5 docker compose file. but that command didn't work, i manually edited the place holder with the value and ran the docker-compose up.

**Comment by sabbyanandan** [comment]
Ah, you're on Windows! I guess that'd be something like: `setx DATAFLOW_VERSION 1.5.0.RELEASE`. It is basically you setting it as an environment variable. 

Thanks for reporting it. If you have any other questions, feel free to reach out to us in [Gitter](https://gitter.im/spring-cloud/spring-cloud-dataflow) or [StackOverflow](http://stackoverflow.com/tags/spring-cloud-dataflow/).

**Comment by sabbyanandan** [comment]
Also, we will improve the docs on this matter via spring-cloud/spring-cloud-dataflow#2214. 😄

**Comment by kswar06** [comment]
Hi @sabbyanandan,

I am again facing the same issue, using new docker compose file for v1.5 as recommended earlier.
Following is the error:

**app-import_1       | wget: server returned error: HTTP/1.1 500
app-import_1       | Task apps imported
v15_app-import_1 exited with code 0**

I even restarted my docker and removed all my other containers, but it didn't work. Can you please provide me any other alternative to use Spring Cloud Data Flow server. I tried to set up manually on my local but once the dataflow server starts i am not able to import the apps. I was referring to the below doc for local installation.

https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#getting-started-deploying-spring-cloud-dataflow

Once the Dataflow server started i tried importing the apps using the below command:

**dataflow:>app import --uri http://bit.ly/Celsius-SR1-stream-applications-kafka-10-maven**

But no luck..
