### ISSUE TITLE
Fix Root REST link

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#222]
The `http://localhost:9393/streams` REST endpoint does not exist:

```
"streams":
        {
            "href": "http://localhost:9393/streams"
        },
```

It should point to `http://localhost:9393/streams/definitions`.

**Comment by ericbottard** [comment]
Correct. `/streams` alone is meaningless.
We should have `/streams/definitions` and `/streams/deployments` only
