### ISSUE TITLE
Improve Stream creation

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow#2220]
As a user, I want to create and deploy a stream with specific deployment properties (the platform for example if skipper is enable).

The REST service `Stream create` should accept the parameter `deploymentProperties`.
This parameter is: `Map<String, String>`, `optional`, `POST`

**Comment by ilayaperumalg** [comment]
By design we didn't allow the deployment properties to be associated with the `stream create` command when using `--deploy` option.

**Comment by markpollack** [comment]
Right, the separation is intentional - the `stream create` is the "what" and the `stream deploy` is the "how".

**Comment by sabbyanandan** [comment]
Closing this as invalid.
