### ISSUE TITLE
Update connector library to support configuration of Hikari CP

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2234]

**Comment by jvmlet** [comment]
For CF SCDF , It would be greate to have the ability to configure **everyting** that is supported by `cloud` namespace xml file - from **external** xml file resource, including the order of trying the connectors  matching.

**Comment by markpollack** [comment]
Hi.  I am not really sure how one can do this, I guess you would have to rebuild the server?  ATM I am upgrading the build to use 

```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-cloudfoundry-connector</artifactId>
            <version>2.0.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-spring-service-connector</artifactId>
            <version>2.0.2.RELEASE</version>
        </dependency>
```

and 

```
			<groupId>io.pivotal.spring.cloud</groupId>
			<artifactId>spring-cloud-services-starter-config-client</artifactId>
			<version>1.6.3.RELEASE</version>
```

I'm embarrassed to keep saying this, as it has taken way longer than I hoped to start working on it, but our intention is to remove the connector library dependency and use a smaller environment variable translation library to populate spring boot properties.  This way everything is managed/created via spring boot vs. having a completely different pathway to create connections.

**Comment by markpollack** [comment]
Closing this issue and creating one in the scdf-cf project.
