### ISSUE TITLE
Parsing deployment properties is unreliable

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#224]
Creating a stream as:
```
dataflow:>stream create --name foo --definition "time|log"
dataflow:>stream deploy --name foo --properties "module.time.dataflow.yarn.app.streamcontainer.memory=1024m,module.log.dataflow.yarn.app.streamcontainer.memory=512m,foo=bar"
```
is sending `deploymentProperties` as shown from logs:
```
YarnStreamModuleDeployer   : deploymentProperties: {dataflow.yarn.app.streamcontainer.memory=512m,foo=bar}
YarnStreamModuleDeployer   : deploymentProperties: {dataflow.yarn.app.streamcontainer.memory=1024m}
```

for `log` module key `dataflow.yarn.app.streamcontainer.memory` is getting value `512m,foo=bar` and not `512m` as expected.

1. We should do a correct parsing(it's using regex pattern which assumes presence of `module` keywork). I think contract is a comma delimited list.
2. I think properties not prefixed with`module.<id>` should be passed to all modules or silently discarded.
3. Properties work ok if I change `foo=bar` to `module.*.foo=bar`.

**Comment by ilayaperumalg** [comment]
I believe the `deployment` properties are expected to be specified with a `module.` prefix. If we want to add support for properties that don't use this prefix, we can look for a delimiter `,` and parse the individual properties. But this might get complex when the property value itself has a comma (say comma separated list as a value). I think it is better we add `module.*` prefix for the global properties like `foo=bar` above. what do you think? cc @markfisher @ericbottard

**Comment by ericbottard** [comment]
Yes, I too believe the original intent for deployment properties was to always target some module. Which, in retrospect, makes the `module.` prefix redundant (if not lengthy, at least).

**Comment by ilayaperumalg** [comment]
Though the prefix `module.` seems redundant, it makes it easier to parse through the list of all deployment properties without the need to parse based on a delimiter which makes it complex with the scenario I mentioned above.

**Comment by markpollack** [comment]
We have a long overdue issue to resolve which is to provide a yaml based alternative for providing deployment properties.  This reduces the verbosity but also ties into providing other properties related to resource usages which could be common across different providers, as well as reference provider specific configuration files, such as those for k8s which describe pods, replication controllers, etc where the metadata in those files is crucial.  it also ties into providing an 'deployable app/artifact' model for dataflow where a .jar could have stream/job defs in one resource and the deployment manifest in other resources in the jar.  We would then deploy the jar vs running scripts in production.  All said, let's sketch out what that yaml would look like, having the module prefix prob makes sense and we may limit what we want to support parsing via command line property files.

**Comment by ilayaperumalg** [comment]
Closing this as the outcome of this issue is being tracked here: #271
