### ISSUE TITLE
Task Definition status returns `unknown`

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2254]
When retrieving task definitions, the `status` property is alway `unknown`. 

http://localhost:9393/tasks/definitions

```json
{
  "_embedded": {
    "taskDefinitionResourceList": [{
      "name": "foo",
      "dslText": "timestamp-batch",
      "composed": false,
      "status": "unknown",
      "_links": {
        "self": {
          "href": "http://localhost:9393/tasks/definitions/foo"
        }
      }
    }]
  },
  "_links": {
    "self": {
      "href": "http://localhost:9393/tasks/definitions?page=0&size=20"
    }
  },
  "page": {
    "size": 20,
    "totalElements": 1,
    "totalPages": 1,
    "number": 0
  }
}
```

It turns out the *deployment key/id* is never persisted. Therefore, in `TaskDefinitionController` when executing:

```java
String id = deploymentIdRepository.findOne(key);
```

a `null` value is always returned.

Is this `status` for Tasks still relevant? Can it be removed? Shall we instead show/return the execution status of the last Task execution?

**Comment by mminella** [comment]
Status for tasks is not revelvant and should be removed.  The "status" of a task is dictated by the `TaskExecution` which is via the `TaskRepository` and have nothing related to the underlying platform.

**Comment by ghillert** [comment]
The status should be replaced with a property representing the last TaskExecution (if available) for the given TaskDefinition. The `TaskExecution` itself will then include also a `status` property.

We should also define a status for task executions: 

- 0 == SUCCESS
- !0 == FAILED
- no end time == RUNNING?

Requires: https://github.com/spring-cloud/spring-cloud-task/issues/424
