### ISSUE TITLE
shell command:app default error

### ISSUE THREAD

**Issue by mv78** [spring-cloud/spring-cloud-dataflow#2256]
I get error trying to set default version for registered app.
The error from the shell says: Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Access is denied

No log records in DataFlow Service or Skipper Server

I am running SCDF 1.5.0.RELEASE and Skipper 1.0.4.RELEASE using SHELL 1.5.0.RELEASE

**Comment by sabbyanandan** [comment]
Thanks for the report, @mv78. Is this on a secured server? Can you also share the configs and the exact commands that you tried?

**Comment by mv78** [comment]
We are using default helm chart that configures basic auth.
