### ISSUE TITLE
Batch job executions of streams not visible

### ISSUE THREAD

**Issue by simasch** [spring-cloud/spring-cloud-dataflow#2259]
I've created a stream that runs a task that contains a batch job.

When I run this batch job as task I see entries in the Jobs section of the dashboard. 
But when I run the task from a stream with a task-launcher I cannot see a job execution.

Is there a way that these executions also appear in the Jobs section?

**Comment by sabbyanandan** [comment]
As discussed in the [SO thread](https://stackoverflow.com/questions/50774895/when-running-a-task-with-a-batch-job-as-stream-there-is-no-entry-in-the-jobs-sec), you'd have to share a common `datasource` between Task/Job and SCDF. The Job executions will be automatically recorded and rendered in the Dashboard. Refer to the [relevant docs](http://docs.spring.io/spring-cloud-dataflow/docs/1.5.1.RELEASE/reference/htmlsingle/#sharing-spring-cloud-dataflows-datastore-with-tasks) from the ref. guide.

It'd be great if you can avoid cross-posting it in different forums. For questions, please continue to use StackOverflow. We use GitHub for feature requests/bugs.
