### ISSUE TITLE
Make Stream executions visible

### ISSUE THREAD

**Issue by simasch** [spring-cloud/spring-cloud-dataflow#2260]
Currently the only way to view if a stream is execution is to look at the log files.

It would be very useful to have these executions in the UI like the Job executions.
Or like hawt.io with Camel: http://hawt.io/

**Comment by sabbyanandan** [comment]
Hi, @simasch. 

A stream a continuous flow of data between Spring Cloud Stream Apps. There's no concept of tracking its execution in this domain when compared with Tasks/Jobs, where the start/end information is persisted given the transient nature of this workload. However, if you're interested in monitoring the streaming pipeline, please have a look at the following options.

- [Metrics Collector](https://github.com/spring-cloud/spring-cloud-dataflow-metrics-collector) | [Docs](http://docs.spring.io/spring-cloud-dataflow/docs/1.5.1.RELEASE/reference/htmlsingle/#configuration-monitoring-deployed-applications)
- Monitoring with [Prometheus](https://docs.spring.io/spring-cloud-dataflow-samples/docs/current/reference/htmlsingle/#_scdf_metrics_with_prometheus_and_grafana)
- Monitoring with [InfluxDB](https://docs.spring.io/spring-cloud-dataflow-samples/docs/current/reference/htmlsingle/#spring-cloud-data-flow-samples-micrometer-influx-overview)
