### ISSUE TITLE
Map to the HTTP source to a fixed route in PAS

### ISSUE THREAD

**Issue by fmarinelli** [spring-cloud/spring-cloud-dataflow#2265]
It would be nice to have the ability when defining a stream with an http source to be able to map a route when deploying in PAS.

So for example:
```
stream create --name rest-test --definition "http --route=rest.example.com  | log"
```
or something like:
```
stream create --name rest-test --definition "http | log"
stream deploy --name rest-test --map-route rest.example.com
```

**Comment by sabbyanandan** [comment]
This is already supported via deployment properties. Here's an [example](http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.5.1.RELEASE/reference/htmlsingle/#configuration-custom-routes). Also, for CF issue, please use [spring-cloud/spring-cloud-dataflow-server-cloudfoundry](https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues) going forward.
