### ISSUE TITLE
no main manifest attribute while running  streams spring-cloud-starter-stream component

### ISSUE THREAD

**Issue by promachos93** [spring-cloud/spring-cloud-dataflow#2273]
Hello,
I'm can't connect to outside network(as I'm in DMZ) 
 so i've imported the jar manually from my m2 repo (provide by the https://github.com/spring-cloud/spring-cloud-stream-app-starters)

app register --name  file --type source --uri  file:///<LocalPATH>spring-cloud-starter-stream-source-file-1.3.1.RELEASE.jar

while launching the stream definition I always got in the logs this error 
**no main manifest attribute**, in <localPATH>spring-cloud-starter-stream-source-file-1.3.1.RELEASE.jar

Can you check why there is no Spring boot or main class. Is there a specific run to be made ? 

thanks & regards

**Comment by sabbyanandan** [comment]
Hi, @promachos93. Have you gone through the [getting-started](http://docs.spring.io/spring-cloud-dataflow/docs/1.5.1.RELEASE/reference/htmlsingle/#getting-started-deploying-spring-cloud-dataflow) guide? 

Your pointer to `https://github.com/spring-cloud/spring-cloud-stream-app-starters` is wrong. That is an old repo - please see [README](https://github.com/spring-cloud/spring-cloud-stream-app-starters#announcement-as-of-110rc1--avogadrorc1-release-this-project-is-now-moved-to-spring-cloud-stream-app-starters-organization-and-each-of-the-spring-cloud-stream-app-starters-is-now-maintained-in-a-separate-repo-by-itself). How did you find and get to this site? _(we need to remove it, that's why I'm interested in knowing how you got there)_

Also, you're registering wrong coordinates for the App. `spring-cloud-starter-stream-source-file-1.3.1.RELEASE.jar` is not the uber-jar. If you had followed the getting-started guide, you would notice [`Register a Stream App`](http://docs.spring.io/spring-cloud-dataflow/docs/1.5.1.RELEASE/reference/htmlsingle/#spring-cloud-dataflow-register-stream-apps) section particularly helpful. 

If you have to download the Apps (uber-jar's) beforehand, we also provide the download links to the stable releases in the [project site](http://cloud.spring.io/spring-cloud-stream-app-starters/#http-repository-location-for-apps).

**Comment by promachos93** [comment]
Hello, 

i would like to have all the component in ... http://bit.ly/Celsius-SR2-stream-applications-rabbit-maven  but the access is forbideen by my company . How can I get the correct jar and deploy it manually using the command app register --name file --type source --uri file://<component>.jar

regards,

**Comment by sabbyanandan** [comment]
As discussed above, you can download the stable release versions from the project site. Here's an [example](https://repo.spring.io/libs-release/org/springframework/cloud/stream/app/spring-cloud-stream-app-descriptor/Celsius.SR2/spring-cloud-stream-app-descriptor-Celsius.SR2.rabbit-apps-maven-repo-url.properties). You can `wget` the required Apps from its HTTP coordinates. You'd have to download it outside of your restricted environment and (somehow) move the files over. 

It'd be great if you can answer:

> Your pointer to https://github.com/spring-cloud/spring-cloud-stream-app-starters is wrong. That is an old repo - please see README. How did you find and get to this site? (we need to remove it, that's why I'm interested in knowing how you got there)

**Comment by promachos93** [comment]
Hello,
Your requested URL has been blocked by the URL Filter database module of McAfee Web Gateway.
wget http://bit.ly/Celsius-SR2-stream-applications-rabbit-maven ### **is also blocked here** :( so how can I download it ?

regarding your question on google  you'll have it on 3rd result by searching spring-cloud-stream-app-starters .

I would like to know if you have a simple .yml without kafka dependency on it ...
regards

**Comment by promachos93** [comment]
file --directory=<LOCAL_DIRECTORY> | log --name=testing --level=DEBUG

I've got the following errors : 

> 
> 2018-06-19 18:22:03.315 ERROR 11420 --- [ask-scheduler-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.integration.amqp.outbound.AmqpOutboundEndpoint@c9b5c88]; nested exception is org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused: connect, failedMessage=GenericMessage [payload=byte[3867], headers={file_originalFile= <LOCAL PATH>   , id=4a672a84-2e7c-13dd-c186-7f2272f2a71b, contentType=application/octet-stream, file_name=rating-ws.xml, timestamp=1529425321297}]
> 	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:139)
> 	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler.handleMessageInternal(AbstractMessageChannelBinder.java:600)
> 	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
> 	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
> 	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:148)
> 	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:121)
> 	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:89)
> 	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:425)
> 	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:375)
> 	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
> 	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
> 	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
> 	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:360)
> 	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:271)
> 	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:188)
> 	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:115)
> 	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
> 	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
> 	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:148)
> 	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:121)
> 	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:89)
> 	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:425)
> 	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:375)
> 	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
> 	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
> 	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
> 	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:360)
> 	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:271)
> 	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:188)
> 	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:115)
> 	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)

**Comment by sabbyanandan** [comment]
Thanks for the update.

> I would like to know if you have a simple .yml without kafka dependency on it ...

I'm not sure I follow this comment. If you'd want to download full-blown Apps for Kafka, you can find the App combinations [here](https://repo.spring.io/libs-release/org/springframework/cloud/stream/app/spring-cloud-stream-app-descriptor/Celsius.SR2/spring-cloud-stream-app-descriptor-Celsius.SR2.kafka-10-apps-maven-repo-url.properties). For example, to download `http-source`, you'd do:

> $ wget http://repo.spring.io/release/org/springframework/cloud/stream/app/http-source-kafka-10/1.3.1.RELEASE/http-source-kafka-10-1.3.1.RELEASE.jar

And, for the following exception:

> 2018-06-19 18:22:03.315 ERROR 11420 --- [ask-scheduler-1] o.s.integration.handler.LoggingHandler : org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.integration.amqp.outbound.AmqpOutboundEndpoint@c9b5c88]; nested exception is org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused: connect, failedMessage=GenericMessage [payload=byte[3867], headers={file_originalFile= , id=4a672a84-2e7c-13dd-c186-7f2272f2a71b, contentType=application/octet-stream, file_name=rating-ws.xml, timestamp=1529425321297}]

It looks like you've managed to delpoy the Apps, but the Apps are failing to connect to Rabbit. Please double check whether Rabbit is running locally. 

----

All this said, once after you successfully download and register Apps, I'd recommend sticking to the [getting-started](http://docs.spring.io/spring-cloud-dataflow/docs/1.5.1.RELEASE/reference/htmlsingle/#getting-started-deploying-spring-cloud-dataflow) guide. 

Lastly, for questions like this, please use StackOverflow or Gitter going forward. We recommend GH for bugs and/or feature requests.

**Comment by promachos93** [comment]
i don't want to connect to rabbit MQ... i want to pull file content and log the payload (just for testing) so in the stream creation i've written file --directory=<LOCAL_DIRECTORY> | log --name=testing --level=DEBUG
is it regarding a wrong jar version fetching ?
regards

**Comment by promachos93** [comment]
is it possible not to have kafka or rabbimq...? just the component itself ?

**Comment by sabbyanandan** [comment]
Please have a look at how Spring Cloud Stream [works](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RELEASE/reference/htmlsingle/#_main_concepts). A message broker is an architecture level _requirement_ for SCSt and SCDF. If you have other questions, please start the conversation in gitter. We would appreciate if you don't comment on a closed issue.
