### ISSUE TITLE
Bulk import of default apps fails for SCDF local server behind an authenticated proxy

### ISSUE THREAD

**Issue by holger-stenzhorn** [spring-cloud/spring-cloud-dataflow#2274]
I am running SCDF local server behind a corporate firewall and therefore added - as mentioned in the reference guide - the Maven proxy settings at start-up, i.e. `java -jar spring-cloud-dataflow-server-local-1.5.1.RELEASE.jar --maven.proxy.host=some-proxy-host --maven.proxy.port=88 --maven.proxy.auth.username=some-proxy-username --maven.proxy.auth.password=some-proxy-password`.

When I now try to perform a bulk import of (external) apps from the dashboard or the command line using e.g. `wget -O- 'http://localhost:9393/apps' --post-data='uri=http://bit.ly/Celsius-SR1-stream-applications-kafka-10-maven'` then the import is triggered as I see `Initializing dispatcher servlet` in the SCDF log but after a while I get a stacktrace because of a connection timeout:

The reason is that in the called method `org.springframework.cloud.dataflow.registry.AbstractAppRegistryCommon.loadProperties` the method `org.springframework.core.io.support.PropertiesLoaderUtils.loadProperties` is called
which creates a regular `java.net.URLConnection` for reading from the given Bitly link that obviously does not consider the provided Maven proxy settings.

The problem cannot be directly fixed by providing the regular standard Java proxy settings, i.e. `java -Dhttp.proxyHost=some-proxy-host -Dhttp.proxyPort=88 -jar ...` since the standard Java proxy settings do not provide a means for an authenticated proxy, i.e. there is no additional `-Dhttp.proxyUser=some-proxy-username  -Dhttp.proxyPassword=some-proxy-password`.

Therefore, I guess the solution would be simply to use a HTTP client that supports proxy authentication when loading properties.

_Note:_ A doable workaround for me is to download the file `Celsius-SR1-stream-applications-kafka-10-maven` locally first and then use the file URI to that file instead, i.e. `wget -O- 'http://localhost:9393/apps' --post-data='uri=file:///tmp/Celsius-SR1-stream-applications-kafka-10-maven'`.

**Comment by sabbyanandan** [comment]
Hi, @holger-stenzhorn. Thank you for the interest in SCDF and the report. We will review to see what we can do here.

**Comment by sabbyanandan** [comment]
@holger-stenzhorn: A new SCDF-App-repo tool is now available at: [spring-cloud-stream-app-starters/scdf-app-repo](https://github.com/spring-cloud-stream-app-starters/scdf-app-repo) - see README for more details. If you have any other feedback, please do let us know.
