### ISSUE TITLE
Parallel tasks are executed consequentially

### ISSUE THREAD

**Issue by Rostish** [spring-cloud/spring-cloud-dataflow#2278]
I have a workflow:
`<tv: multiOperation --spring.application.name=tv--runner.localDate=2018-01-31 || web: multiOperation --spring.application.name=web --runner.localDate=2018-01-31>`

When i launch it, it executed consequentially:
tv starts firs
tv ends, engine sleeps for 10-15 seconds
web starts

Execution Id | Task Name | Start Date                            | End Date                             | Exit Code |  

#6 | ab-web       | 2018-06-21T11:57:40.151Z | 2018-06-21T11:57:53.058Z | 0              |  
#5 | ab-tv           | 2018-06-21T11:57:09.222Z | 2018-06-21T11:57:21.724Z | 0              |  
#4 |  ab              | 2018-06-21T11:56:58.623Z | 2018-06-21T11:58:00.066Z | 0              |

Why tasks are not executed both the same time?
It looks like an issue.

**Comment by sabbyanandan** [comment]
Thanks for the report, @Rostish. I'm able to reproduce it with the simple `timestamp` App. 

```
dataflow:>task create foo --definition "<t1: timestamp || t2: timestamp>"

dataflow:>task launch --name foo

dataflow:>task execution list
╔═════════╤══╤════════════════════════════╤════════════════════════════╤═════════╗
║Task Name│ID│         Start Time         │          End Time          │Exit Code║
╠═════════╪══╪════════════════════════════╪════════════════════════════╪═════════╣
║foo-t2   │3 │Thu Jun 21 07:32:49 PDT 2018│Thu Jun 21 07:32:49 PDT 2018│0        ║
║foo-t1   │2 │Thu Jun 21 07:32:39 PDT 2018│Thu Jun 21 07:32:39 PDT 2018│0        ║
║foo      │1 │Thu Jun 21 07:32:35 PDT 2018│Thu Jun 21 07:32:56 PDT 2018│0        ║
╚═════════╧══╧════════════════════════════╧════════════════════════════╧═════════╝
``` 

Indeed, it seems like the child tasks aren't starting in parallel. We will investigate.

**Comment by mminella** [comment]
A split in Spring Batch (which is how this is implemented) by default uses a Synchronous `TaskExecutor` (since there is no "sensible default" for how many threads to use).  My expectations are that this hasn't been changed in the CTR and we need to add that (as well as make the concurrency configurable in some capacity).

**Comment by cppwfs** [comment]
You can actually set the number of threads.  The default number of threads is one.

**Comment by jvmlet** [comment]
I can confirm this is **NOT** the issue, just run CTR with `--split-thread-core-pool-size=X` and you will get the desired concurrency (by default its 1, thats' why  it's executed sequentially). 
Keep in mind that pool size should be greater than the number of splits in the graph.

**Comment by sabbyanandan** [comment]
Ah, haa! I ran into a similar situation a long time ago, and I had @cppwfs educate me about `--split-thread-core-pool-size=X` in the past. It still slipped from the memory. 😞 

Thanks, @jvmlet for pointing it out. 

@Rostish: Please override `--split-thread-core-pool-size=X` while launching the composed-task. Where `X` would be the number of parallel paths that you'd have in your graph. In my previous example, I'd pass it as "2". 

```
dataflow:>task launch --name foo --arguments "--split-thread-core-pool-size=2"
```

In your example, it'd be "2" as well. 
Let us know if you see any other anomaly.

**Comment by Rostish** [comment]
Looks like it works, thank you for your comment.

║ab-tv           │21│Mon Jun 25 07:31:38 GMT 2018│Mon Jun 25 07:31:47 GMT 2018│0        
║ab-web       │22│Mon Jun 25 07:31:38 GMT 2018│Mon Jun 25 07:31:46 GMT 2018│0        
║ab               │20│Mon Jun 25 07:31:26 GMT 2018│Mon Jun 25 07:31:57 GMT 2018│0  

I think, it should be described in Composed-Tasks part in SCDF documentation. 
There is only one "split-thread-core-pool-size" coincidence in whole document.

**Comment by sabbyanandan** [comment]
Sure thing. We will address it via spring-cloud/spring-cloud-dataflow#2279. Thank you for the feedback.
