### ISSUE TITLE
Improve health-checks when starting SCDF via Docker Compose

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2280]
Ideally, when starting SCDF via Docker Compose, and Docker Compose is done, SCDF should be ready to accept incoming request. Currently, this is not the case and for https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/742 we employ some artificial wait-times.

See also:

* https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y
* https://github.com/spring-cloud/spring-cloud-dataflow/issues/2270

**Comment by sabbyanandan** [comment]
In the latest Docker Compose experience (2.2 and over), once when the Docker Compose bootstrap is complete, SCDF is fully ready to accept requests from any of the SCDF clients (dashboard, shell, api).
