### ISSUE TITLE
Add docker-compose support to point to host's Maven repository

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2286]
As a user, I'm attempting to register locally developed custom apps from my local repo and as well from the file system; however, the Docker daemon that's running SCDF/UI doesn't have access to the host directories and likewise the `/m2` folder in the host, too.

More details in SO thread [here](https://stackoverflow.com/questions/51058729/how-to-register-applications). 

**Acceptance:**
- Add support to mount the host directory (`./m2`) by default (refer to a solution [here](https://stackoverflow.com/questions/36234088/how-do-i-point-a-docker-image-to-my-m2-directory-for-running-maven-in-docker-on))
- Consider the mounting ability for both windows/linux users
- Explore options to mount other host directories (as a collection, so user's can register apps via `file://` protocol)
- Update getting-started guide

**Comment by tzolov** [comment]
We can mount the local `~/.m2/repository` folder as a docker volume and register application from there. Apps can be registered as files either automatically (extending the existing wget command) or through the common UI or shell tools. The `file:/` uri schema has to be used.  

For example we can mount the .m2/repository folder directly into our `docker-compose.yml`:
```yml
  dataflow-server:
    image: springcloud/spring-cloud-dataflow-server-local:${DATAFLOW_VERSION}
    ....
    volumes:
      - ~/.m2/repository:/m2repo

```
And then uses the wget to register the `pose-estimation` app:

`wget -qO- 'http://dataflow-server:9393/apps/processor/pose-estimation' --post-data='uri=file:/m2repo/org/springframework/cloud/stream/app/pose-estimation-processor-kafka/2.0.2.BUILD-SNAPSHOT/pose-estimation-processor-kafka-2.0.2.BUILD-SNAPSHOT.jar&metadata-uri=file://m2repo/org/springframework/cloud/stream/app/pose-estimation-processor-kafka/2.0.2.BUILD-SNAPSHOT/pose-estimation-processor-kafka-2.0.2.BUILD-SNAPSHOT-metadata.jar';`

Mind the use of the `file:/` prefix and we using both `uri` and `metadata-uir` parameters. Also notice that post path syntax: `http://dataflow-server:9393/apps/<APPT TYPE>/<APP NAME>`. 

I don't think though that we can specify the local folder in OS independent way. It can set will starting the docker-compose using the `-v` option or by introducing a new env variable like: `LOCAL_APPS_FLODER` and then inside the script define the volume as: `- ${LOCAL_APPS_FLODER}:/apps`

**Comment by chrisjs** [comment]
i have some thoughts on this that we can discuss in a few
