### ISSUE TITLE
Skipper REST API docs don't include any details

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2300]
As a user, I'm attempting to review the REST docs for the Skipper specific endpoints, but I only see bogus text and no details or examples.

See: http://docs.spring.io/spring-cloud-dataflow/docs/1.5.1.RELEASE/reference/htmlsingle/#api-guide-resources-stream-deployment

Specifically, the following guides are bogus.
![image](https://user-images.githubusercontent.com/1562654/42113328-cd58f282-7b9f-11e8-9685-5b6164e7e9e2.png)

**Comment by ilayaperumalg** [comment]
It looks like we never run the Test Data Flow server on skipper mode and hence, the corresponding Skipper related REST endpoints were never captured as part of the documentation generation.
