### ISSUE TITLE
Update Docker compose Kafka version

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow#2303]
In `https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-local/docker-compose.yml#L5`, update container version to latest (1.1.0)

**Comment by chrisjs** [comment]
additionally:

1 - In `spring-cloud-dataflow-docs/src/main/asciidoc/getting-started.adoc`:
* update kafka version in "To use RabbitMQ instead of Kafka" section of "Docker Compose Customization" yaml example
* update the text: `And finally, modify the `app-import` service definition `command` attribute to replace `http://bit.ly/Celsius-SR1-stream-applications-kafka-10-maven` with `http://bit.ly/Celsius-SR1-stream-applications-rabbit-maven`` to use `Darwin` ?

2 - Update to `Darwin` - https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-local/docker-compose.yml#L39  ?

3 - Task updates? - https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-local/docker-compose.yml#L41

**Comment by sabbyanandan** [comment]
>  update the text: "And finally, modify the app-import service definition command attribute to replace http://bit.ly/Celsius-SR1-stream-applications-kafka-10-maven with http://bit.ly/Celsius-SR1-stream-applications-rabbit-maven" to use Darwin ?

For now, let's stick with Celsius.SR3. We are going to release Darwin.SR1; when that is ready, we can switch over. 

> Task updates?

Same story here. Until Dearborn.GA is complete, let's stick with Clark.
