### ISSUE TITLE
Troubleshoot why JFrog Docs plugin has stopped working

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2307]
As a developer, I'd like to research why the artifactory Docs plugin is not working anymore. 

Observations:

- Roughly by the end of May Bamboo/Artifactory version upgrades, we have had the Docs plugin issue
- The plugin appears to generate the files with bogus extension; something like -> `spring-cloud-dataflow-docs-1.6.0.BUILD-SNAPSHOT.zip;zip.type=docs;zip.deployed=false`
- By manually editing the file extension from artifactory, the publish operation seems to load the docs correctly afterwards

**Comment by jvalkeal** [comment]
@sobychacko  Don't know who is talking to jfrog but figured out what they broke.

This works:
```
curl -u <username>:<password> -X PUT "https://repo.spring.io/test-libs-snapshot-local/test/test.txt;propertyA=valueA;propertyB=valueB" -T /tmp/xxx/test.txt

file name: text.txt
props: propertyA=valueA and propertyB=valueB
```

Breaks with url encoding:
```
curl -u <username>:<password> -X PUT "https://repo.spring.io/test-libs-snapshot-local/test/test.txt%3BpropertyA%3DvalueA%3BpropertyB%3DvalueB" -T /tmp/xxx/test.txt

file name: test.txt;propertyA=valueA;propertyB=valueB
props: none
```
When artifacts are uploaded, url is always encoded, thus why it breaks.

**Comment by sabbyanandan** [comment]
A new patch for Bamboo was applied and the Docs are generating correctly.
