### ISSUE TITLE
Better Error handling when Skipper is off-line

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2309]
This is not just relevant for Skipper but also Scheduler, Analytics etc. In cases of misconfiguration (maybe wrong environment variable) it is easily possible to trigger unintuitive behavior, e.g. the `About` endpoint returning a `404`:

```
https://gh-data-flow-server.apps.needles.cf-app.com/about
[{"logref":"HttpClientErrorException","message":"404 Not Found"}]
```

I suggest 2 solutions:

1) Rest endpoints that interact with other remote microservices should degrade gracefully / return proper exceptions, to give users a better understanding of what is going on.

and/or

2) During startup, SCDF should test and ensure that it is in a working condition, e.g. if it is configured for Skipper, Skipper should in fact be operable etc.

**Comment by ghillert** [comment]
@sabbyanandan This also affects the UI. E.g. only the `Apps` and `About` are visible without providing any visibility to the users that Skipper is `offline`.

**Comment by sabbyanandan** [comment]
We already validate Shell for when the server is in skipper mode and the connection to Skipper isn't successful.

```
➜ spring-cloud-dataflow ➤ 16edf43|master⚡
± java -jar spring-cloud-dataflow-shell/target/spring-cloud-dataflow-shell-1.7.0.BUILD-SNAPSHOT.jar --dataflow.mode=skipper
  ____                              ____ _                __
 / ___| _ __  _ __(_)_ __   __ _   / ___| | ___  _   _  __| |
 \___ \| '_ \| '__| | '_ \ / _` | | |   | |/ _ \| | | |/ _` |
  ___) | |_) | |  | | | | | (_| | | |___| | (_) | |_| | (_| |
 |____/| .__/|_|  |_|_| |_|\__, |  \____|_|\___/ \__,_|\__,_|
  ____ |_|    _          __|___/                 __________
 |  _ \  __ _| |_ __ _  |  ___| | _____      __  \ \ \ \ \ \
 | | | |/ _` | __/ _` | | |_  | |/ _ \ \ /\ / /   \ \ \ \ \ \
 | |_| | (_| | || (_| | |  _| | | (_) \ V  V /    / / / / / /
 |____/ \__,_|\__\__,_| |_|   |_|\___/ \_/\_/    /_/_/_/_/_/

1.7.0.BUILD-SNAPSHOT

Welcome to the Spring Cloud Data Flow shell. For assistance hit TAB or type "help".
server-unknown:>
```

error:
```
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:7577 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1, localhost/fe80:0:0:0:0:0:0:1%1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159) ~[httpclient-4.5.5.jar!/:4.5.5]
```

It'd be nice to follow this pattern in the UI for consistency. We could handle the exception with a user-friendly message and no-tabs even.

**Comment by sabbyanandan** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-dataflow/issues/2655.
