### ISSUE TITLE
Add new endpoint to retrieve the count of running Tasks

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2312]
As a developer, I'd like to add a new endpoint that returns the count of the number of Tasks under execution. 

**Acceptance:**
- The new endpoint can be listed under `/tasks/executions` with the name `/tasks/executions/count` (maybe?)
- List the new endpoint under RootController
- The new endpoint would invoke the query against `TASK_EXECUTION` and specifically the `END_TIME` column to determine the count of running Tasks
- Add RESTDocs 
- Verify to make sure the Docs show up under [Task Execution API](http://docs.spring.io/spring-cloud-dataflow/docs/1.5.2.RELEASE/reference/htmlsingle/#api-guide-resources-task-executions) docs

**Comment by dturanski** [comment]
Actually, I envision the endpoint to provide info about currently running tasks, `tasks/executions/current`.  This includes a count field and also the maximum number of concurrent tasks allowed (defined by a SCDF property).  The client can use this to determine if the limit has been reached but also access underlying values which could be useful for error reporting and other use cases.
