### ISSUE TITLE
Have scdf supported multi-tennacy?

### ISSUE THREAD

**Issue by tungntt** [spring-cloud/spring-cloud-dataflow#2324]
Hi all,

I have read document and only figure out security in sdcf.
However, the document have no indicated multi-tennacy.

Therefore, I would like to clarify that it may not support now, but is something going to change in the future?

Thanks

**Comment by sabbyanandan** [comment]
Hi, @tungntt. If you're running SCDF on cloud platforms like Cloud Foundry or Kubernetes, you will go about creating service-instances in an Org/Space combination in CF and provision SCDF components governed by a K8S namespace in Kubernetes respectively. We take advantage of the platform native capabilities and that should give you the isolation. This along with RBAC configuration would cover the general premise from multi-tenancy perspective.

For questions like this, please consider using StackOverflow going forward.
