### ISSUE TITLE
Remove all TODO's

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#233]
As a developer, I'd like to convert the TODO's as issues.

**Comment by ericbottard** [comment]
Created a bunch of issues in relevant projects. Leaving the TODO markers for now, for context (an alternative would be to link each issue to specific commit + line) and then have a PR that removes TODOs

**Comment by garyrussell** [comment]
My preference would be leave the TODOs in place.

If anything, I'd do the reverse - put the issue number in the TODO so a developer that "stumbles" across a TODO and decides to fix it, (s)he can easily find the issue to close.

But that's a lot of work :smile:

**Comment by sabbyanandan** [comment]
We should have had a discussion about the approach in general. I'll mark this story under *not-to-repeat-ever* category. :smile: 

Given our conversations in slack and the fact the damage is already done, I'll review the list of issues and update them as appropriate.
