### ISSUE TITLE
Explore options to support "stream validate" command

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2345]
As a user, I'd like to proactively validate to make sure the registered App artifacts are resolvable successfully before deploying a stream. 

The idea is to gain confidence that the stream would deploy without having to run into deploy-time App resolution concerns.

Relates to spring-cloud/spring-cloud-dataflow#287
Relates to spring-cloud/spring-cloud-dataflow#1049
Relates to spring-cloud/spring-cloud-dataflow#1497

child of spring-cloud/spring-cloud-dataflow#2344

**Comment by chrisjs** [comment]
merged in 4a8b0fb
