### ISSUE TITLE
Adding messaging middleware brokers

### ISSUE THREAD

**Issue by komushi** [spring-cloud/spring-cloud-dataflow#2348]
It will be nice to have additional messaging brokers such as:
Spring Cloud Stream Binder for AWS Kinesis

**Comment by sabbyanandan** [comment]
Hi, @komushi. It is unclear what you're referring to message brokers here and in what context, but we do have a [Kinesis binder implementation](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis), which you can use already to build the custom Spring Cloud Stream Apps or the out-of-the-box Apps can be packaged with it, too. For the latter, see the [patching procedure](https://docs.spring.io/spring-cloud-stream-app-starters/docs/Darwin.SR1/reference/htmlsingle/#customizing-binder) for more details.

For questions like this, it'd be great if you can post it in StackOverflow or Gitter going forward.
