### ISSUE TITLE
how to launch already defined task using streams?

### ISSUE THREAD

**Issue by prasad91** [spring-cloud/spring-cloud-dataflow#2352]
As a user I would like to launch the tasks which are already defined in data flow server instead of using a maven URL. Is there anyway to do it? for example; I have defined 2 tasks Task_1 and Task_2 for apps App_1 and App_2 which had maven URL as maven://com.example.app:app_1:jar:1.0.0 and maven://com.example.app:app_2:jar:1.0.0

Now if I want to schedule the task launching using the stream apps triggertask-source-rabbit and task-launcher-cloudfoundry-sink-rabbit I should use the maven URL for the option --triggertask.uri. Instead of using the maven uri can I use Task_1 and Task_2 directly as any option attribute.

instead of this triggertask --environment-properties=spring.profiles.active=user,JAVA_OPTS=-Duser.timezone=America/New_York --uri="maven://com.example.app:app_1:jar:1.0.0" --cron="0 0 0 * * MON-FRI" --application-name=app_1 | task-launcher-cloudfoundry

to this triggertask --environment-properties=spring.profiles.active=user,JAVA_OPTS=-Duser.timezone=America/New_York <<task_def=app_1>> --cron="0 0 0 * * MON-FRI" --application-name=app_1 | task-launcher-cloudfoundry

Thanks so much for your help here.

Prasad.

**Comment by sabbyanandan** [comment]
Hi, @prasad91. Have a look at [Composed Task Runner](https://github.com/spring-cloud-task-app-starters/composed-task-runner/blob/master/spring-cloud-starter-task-composedtaskrunner/README.adoc) and its capabilities. One of the key attributes of this application is to launch a set of Task Apps in sequence, parallel, or both as defined in the graph DSL.

You can continue to use the  `triggertask` to launch the graph in a stream, but you'd have to pass the graph DSL. Here's an example:

> stream create ctr-stream --definition "triggertask --environment-properties=spring.profiles.active=user,JAVA_OPTS=-Duser.timezone=America/New_York --fixed-delay=30 | tasklaunchrequest-transform --uri=maven://org.springframework.cloud.task.app:composedtaskrunner-task:2.0.0.RELEASE --command-line-arguments='--graph=extractData && cleanse && writeToOracle --increment-instance-enabled=true --spring.datasource.url=...' | task-launcher-cloudfoundry"

Here:
- `--command-line-arguments='--graph=extractData && cleanse && writeToOracle --increment-instance-enabled=true --spring.datasource.url=...'` - defines a graph made of 3 Task apps (`extractData`, `extractData`, and `writeToOracle`).
- All the 3 Apps are executed in sequence one aftrer the other; you can define it to be launched simultaneously as well.
- So, on every new trigger, this graphh runs in entirety as a set of Tasks.

With that said, I'd highly recommend that you use the [PCF Scheduler integration in SCDF for PCF](https://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.6.0.RELEASE/reference/htmlsingle/#spring-cloud-dataflow-schedule-launch-tasks). You don't need to launch a task via a Stream; in fact, it is expensive to do so unless you are targeting other benefits from this model. You can just schedule a composed-task graph via the Scheduler to launch it based on cron expression outcome.

Lastly, please ask questions like this in StackOverflow or Gitter going forward.
