### ISSUE TITLE
Runtime modules command returns wrong results

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#237]
As a user, I created the following stream but the `runtime modules` command is returning wrong results on both CF and YARN SPIs.

**stream:**
```
dataflow:>stream create foo --definition "time | log" --deploy
Created and deployed new stream 'foo'
```

**result:**
```
dataflow:>runtime modules
╔═══════════════════════╤═══════════╤═════════════════════════════╗
║Module Id / Instance Id│Unit Status│No. of Instances / Attributes║
╠═══════════════════════╪═══════════╪═════════════════════════════╣
║foo.log                │ deployed  │              1              ║
╟┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈╢
║foo.log                │ deployed  │                             ║
╚═══════════════════════╧═══════════╧═════════════════════════════╝
```

**Comment by ilayaperumalg** [comment]
@sabbyanandan Do you have a stack trace or more logs for the above command? also, are both the modules `time` and `log` deployed successfully in this case?

**Comment by ericbottard** [comment]
Also, if you know how to reproduce systematically, I'd be interested to track down that ugly table rendering problem :cry:

**Comment by sabbyanandan** [comment]
@ilayaperumalg: I tried this again in YARN and it returns as expected [:tired_face:]; however, I must say this isn't reliably working all the time. I've seen this intermittent behavior in CF SPI as well. In both the cases, the stream is successfully deployed; of course the modules, too. 

This behavior is usually spottable in the UI. Please refer to spring-cloud/spring-cloud-dataflow-ui#15 and spring-cloud/spring-cloud-dataflow-ui#16.

**Comment by sabbyanandan** [comment]
@ericbottard: The table looks clean on the terminal, so no worries.

**Comment by ericbottard** [comment]
:relief:

**Comment by sabbyanandan** [comment]
This is working as expected.
