### ISSUE TITLE
Boot2 - overhaul metrics

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#2379]
`org.springframework.boot.actuate.metrics.repository.MetricRepository` is gone, so need to port over micrometer.

Child of #914

**Comment by jvalkeal** [comment]
These are now gone from boot:
```
import org.springframework.boot.actuate.metrics.repository.MetricRepository;
import org.springframework.boot.actuate.metrics.repository.redis.RedisMetricRepository;
```
Need to think about what is a replacement for use wise. Metrics are now conceptually different as old boot metrics were about values and micrometer is about monitoring values and not about keeping metrics in a store, what comes for the concepts itself.

**Comment by sabbyanandan** [comment]
Cleanup: https://github.com/spring-cloud/spring-cloud-dataflow/blob/475fa89437b6d586d62ccb6b0478163e139f1e09/spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/CounterCommandsTests.java#L40.

**Comment by sabbyanandan** [comment]
Closing this in favor of https://github.com/spring-cloud/spring-cloud-dataflow/issues/2542.
