### ISSUE TITLE
spring cloud dataflow tasks launched via streams not being displayed under tasks or jobs tab

### ISSUE THREAD

**Issue by siddhantsorann** [spring-cloud/spring-cloud-dataflow#2391]
spring cloud dataflow tasks launched via streams not being displayed under tasks or jobs tab.
I have deployed the sample batch-job task in a stream with a delay of 10 seconds. The task is running as i can see in the logs but the executions and jobs are not being displayed under the jobs or tasks (execution) tab. how can I do this?

**Comment by siddhantsorann** [comment]
Had missed that, It works now. Thanks! Also, currently I am running the basic timestamp-batch-task in a stream. It gives the task execution and 2 batch jobs. Any idea how I can add a task for the same jar and link the batch jobs to the task?

**Comment by cppwfs** [comment]
Yes.   From the "Task Execution" Page in the UI you can click the "Magnifying Glass" to take you to the "Task Execution Detail" Page.  From there you will see a row containing the `Job Execution Ids`.   And from the "Batch Job Executions" page for each job you will see a column containing the `Task Id`.

**Comment by sabbyanandan** [comment]
Thanks, Glenn. 

@siddhantsorann: We will document it with screenshots via spring-cloud/spring-cloud-dataflow#2394. Also, for questions like this, please stick to StackOverflow. It'd be nice to avoid [duplicate posts](https://stackoverflow.com/questions/52002901/spring-cloud-dataflow-tasks-launched-via-streams-not-being-displayed-under-tasks).
