### ISSUE TITLE
Docs: Provide better docs on how to add Oracle JDBC Driver

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2392]
In chapter _19.2. Adding a Custom JDBC Driver_ we mention to add the Oracle JDBC driver to the `pom.xml` file but we don't elaborate on how to obtain the driver, e.g.:

#### Step 1

Download the driver from: https://www.oracle.com/technetwork/database/application-development/jdbc/downloads/index.html

#### Step 2

```bash
$ mvn install:install-file -DgroupId=com.oracle.jdbc -DartifactId=ojdbc18 -Dversion=18.3.0.0.0 -Dpackaging=jar -Dfile=/path/to/ojdbc8.jar -DgeneratePom=true
```

#### Step 3

Add Maven coordinates to `pom.xml`.

#### Step 4

Configure Data Flow:

```
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=dataflow
spring.datasource.password=dataflow
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
```

**Comment by gdubya** [comment]
See also #2489

**Comment by sabbyanandan** [comment]
Closing this in favor of #2489.
