### ISSUE TITLE
Need to increase maximumConcurrentTasks to a number greater than 20

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#2395]
We had a user working with our 1.7 snapshot and ask why they hit the current spring.cloud.dataflow.task.maximum_concurrent_tasks at such a low number.   This number needs to be set higher than the current 20.

**Comment by dturanski** [comment]
That's why I originally had it at Long.MAX_LONG. How do we know what a reasonable default is?  What did the user set it to? @markpollack

**Comment by sabbyanandan** [comment]
If someone wants >20, it is simple as changing the value to the desired count. It is flexible that way already. I don't think we would want to default to `Long.MAX_VALUE` or any other value. There's never going to be an ideal value that'll satisfy everyone.
