### ISSUE TITLE
SCDF Shell execute  multiple command files

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-dataflow#2398]
From the scdf shell documentation, it looks like multiple files execution ARE supported
````
--spring.shell.commandFile=...  //Data Flow Shell executes commands read from the file(s) and then exits.
````
but `spring.shell.commandFile` property maps to single file.
Please support execution of multiple files passed  via  property (comma separated string  or list )

**Comment by sabbyanandan** [comment]
Hi, @jvmlet! It appears to be a bug in the docs. In [code](https://github.com/spring-cloud/spring-cloud-dataflow/blob/503cc905109b8d636b72c9c77ba75e272bf21fb7/spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/ShellCommandLineParser.java#L60), we expect it to be a single file and not as a collection of them. 

As for multiple files enhancement, why do you see that as a need? Could you describe the requirement? In case you didn't know, we also have `script --file` command in the Shell, which can help with running a set of commands to create/deploy/launch streams and tasks. It might be all you need.

**Comment by jvmlet** [comment]
Thanks @sabbyanandan. I saw the `script - - file`option.
 We have gradle plugin that generates register/create/deploy command files and also adds task that executes them via `--spring.shell.command` argument. The implementation of this gradle execute task would be much simplier if the shell closes itself after executing all files. But if this was not the initial intention to support multiple files the issue can be closed as rejected.

**Comment by sabbyanandan** [comment]
Thanks for the update. 

Have you considered using the REST-APIs or Java DSL? If I read this correctly, I believe either of those options could work for your needs. It might also be a portable solution if in case you migrate them from one environment to another. Also, the Java DSL option gives you an opportunity to unit-test them before executing.

That said, we aren't opposed to multiple-files support, so I will keep this open. Feel free to submit a PR against the issue.

**Comment by jvmlet** [comment]
Would it be OK to pass multiple files as comma separated string  `--spring.shell.commandFile` argument  to be backward compatible ? 
Or you prefer new argument (`--spring.shell.commandFiles`) that binds to array list ?

**Comment by jvmlet** [comment]
PR #2418 , please review
