### ISSUE TITLE
Docs: Using Task App Starters - document how to use Task app starters with custom DB drivers

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2399]
We should provide better documentation on how to use the Task App Starters with custom database drivers, e.g. Oracle.

**Comment by cppwfs** [comment]
Not sure I understand. There is a section in the documentation that covers how to add a database to your task application located https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#task-dev-guide-building-timestamp-task-bonus-adding-mysql[here].  When creating an app from a starter the user would include the custom database dependency in their new application.   Instructions for creating your own app from a starter are discussed https://docs.spring.io/spring-cloud-task-app-starters/docs/Dearborn.RELEASE/reference/htmlsingle/#_creating_your_own_applications[here].

**Comment by sabbyanandan** [comment]
Both the server and apps' cover the documentation individually. Closing it as addressed.
