### ISSUE TITLE
Investigate whether the Task is downloaded more than once at the time of launch

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2409]

**Comment by ilayaperumalg** [comment]
It looks like we don't download the `task` app more than once. The only place I see the incorrect `Downloading` message is when we retrieve the `stream` app for Skipper update request. 

 In case we can reproduce this issue again on `task` app, we can re-open this issue. 

For now, going ahead with the PR to remove this incorrect log for stream app.
