### ISSUE TITLE
schedules-enabled get  error Interface is not implemented for list method.

### ISSUE THREAD

**Issue by benjamin555** [spring-cloud/spring-cloud-dataflow#2411]
I had enabled schedules feature.ref to :https://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#_enabling_scheduling.

But got error:
`java.lang.UnsupportedOperationException: Interface is not implemented for list method.
dataflow-server    |    at org.springframework.cloud.dataflow.autoconfigure.local.LocalDataFlowServerAutoConfiguration$1.list(LocalDataFlowServerAutoConfiguration.java:75) ~[spring-cloud-dataflow-server-local-autoconfig-1.6.1.RELEASE.jar!/:1.6.1.RELEASE]
dataflow-server    |    at org.springframework.cloud.dataflow.server.service.impl.DefaultSchedulerService.list(DefaultSchedulerService.java:165) ~[spring-cloud-dataflow-server-core-1.6.1.RELEASE.jar!/:1.6.1.RELEASE]
dataflow-server    |    at org.springframework.cloud.dataflow.server.controller.TaskSchedulerController.list(TaskSchedulerController.java:82) ~[spring-cloud-dataflow-server-core-1.6.1.RELEASE.jar!/:1.6.1.RELEASE]
dataflow-server    |    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111-internal]
dataflow-server    |    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111-internal]
dataflow-server    |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]
dataflow-server    |    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]
dataflow-server    |    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.18.RELEASE.jar!/:4.3.18.RELEASE]
dataflow-server    |    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.18.RELEASE.jar!/:4.3.18.RELEASE]
dataflow-server    |    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.18.RELEASE.jar!/:4.3.18.RELEASE]`

**Comment by sabbyanandan** [comment]
Hi, @benjamin555. The Scheduler SPI is implemented only for Pivotal Cloud Foundry (see [blog](https://content.pivotal.io/pivotal-blog/spring-cloud-data-flow-1-6-is-ga-pcf-scheduler-integration-kubernetes-1-10-and-spring-boot-2-0-compatibility-ci-cd-improvements-and-more)). It appears you're attempting it in the Local server, it is not supported yet. The next implementation in-flight is for Kubernetes - more details [here](https://github.com/spring-cloud/spring-cloud-scheduler-kubernetes/issues).

I will close this as invalid for now.
