### ISSUE TITLE
Need to add tests to SchedulerController for Security

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#2417]
When we have a local IMPL for Schedules we need to add a test for the secured the Schedules endpoints. Using the other controller security tests as a model. 
  i.e. a test like secureLocalServerSecurityRootWithUsersFileTestsWithTasksAndWithoutStreamsMetricsAndSchedules

**Comment by sabbyanandan** [comment]
We don't have a plan to support local-scheduler impl anyway, so we don't need this test locally.
