### ISSUE TITLE
Scripts to bootstrap databases

### ISSUE THREAD

**Issue by venkatasreekanth** [spring-cloud/spring-cloud-dataflow#2420]
I am following the documentation of spring cloud data flow to initialize the database in production database. https://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#_disabling_database_schema_creation_and_migration_strategies

However the scripts in the location mentioned above do not have scripts to create spring batch tables?
Do I run the scripts found in the location mentioned in the documentation and then pickup the batch schema scrips from spring batch?

Since we don't require High Availability as per our architect(Don't understand why), I am most likely going to standup a local server in prod.

**Comment by ilayaperumalg** [comment]
Hi @venkatasreekanth ,

The Spring Batch tables are created by the `BatchDatabaseInitializer` from Spring Boot auto-configuration. You can read how this gets initialized from [here](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-database-initialization)

The Spring batch scripts can be referred from [here](https://github.com/spring-projects/spring-batch/tree/master/spring-batch-core/src/main/resources/org/springframework/batch/core). When configured to initialize on startup his set of scripts are inferred from the classpath based on the database type.

**Comment by sabbyanandan** [comment]
Hi, @venkatasreekanth. Ilaya covered the background very well. For questions like this, please use StackOverflow or Gitter going forward.

**Comment by venkatasreekanth** [comment]
@sabbyanandan I am already aware of what @ilayaperumalg speaks of. When a batch job is set up as a task in Spring cloud data flow, it will rely on the db connection from data flow. My confusion was that I was looking in spring-dataflow-core-server/shell or something like that for the batch scripts. Now, I know that I need to hand of scripts from batch and dataflow.
