### ISSUE TITLE
Investigate options to stop a task/job from DashBoard and all its subprocess

### ISSUE THREAD

**Issue by Rostish** [spring-cloud/spring-cloud-dataflow#2422]
Good  day collegues.
I have found a problem.

I have a baseoperation(it is an usual Spark-Launcher application), i rigistered it as a Spring Cloud Dataflow Task:

Some code example:

` private void runSparkJobWithKerberos(String pathToJar, final LocalDate startDate, final LocalDate endDate) {
        if (executionInProgress.get()) {
            LOGGER.warn("Execution already in progress");
            return;
        }

        Process sparkProcess = null;
        try {
            LOGGER.info("Create SparkLauncher. SparkHome: [{}]. JarPath: [{}].", sparkHome, vmJarPath);
            executionInProgress.set(true);
            sparkProcess = new SparkLauncher()
                    .setAppName("SCDF_" + activeOperationProfile)
                    .setSparkHome(sparkHome)
                    .setAppResource(pathToJar)
                    .setMaster(master)
                    .setConf(SparkLauncher.DRIVER_EXTRA_JAVA_OPTIONS,
                            String.format("-Drunner.operation-profile=%1$s -Doperation.startDate=%2$s -Doperation.endDate=%3$s -Dspring.config.location=%4$s", activeOperationProfile, startDate, endDate,activeOperationConfigLocation))
                    .setConf(SparkLauncher.DRIVER_MEMORY, "24G")
                    .setConf("spark.yarn.keytab", keytab)
                    .setConf("spark.yarn.principal", principal)
                    .redirectToLog(LOGGER.getName())
                    .launch();

            sparkProcess.waitFor();
            int exitCode = sparkProcess.exitValue();
            if (exitCode != 0) {
                throw new RuntimeException("Illegal exit code. Expected: [0]. Actual: [" + exitCode + "]");
            }

        } catch (IOException | InterruptedException e) {
            LOGGER.error("Error occurred while running SparkApplication.", e);
            throw new RuntimeException(e);
        } finally {
            if (sparkProcess != null && sparkProcess.isAlive()) {
                LOGGER.warn("Process still alive. Try to kill");
                sparkProcess.destroy();
            }
            executionInProgress.set(false);
        }
    }`
If my subprocess is failed, i get an error message, my Spring Cloud Dataflow task failed.
But if i need to **kill** my spark-launcher and it subprocess, i try to destroy this task or push stop button in job section, task die, but subprocess not.

Does this application(SCDF) have some lifecycle API? I wanna kill subprocces from task code(Spark-Launcher Runner), when SCDF send stop message.

P.S. Could you expand the exite message section in "Task Execution Details"? Too little information is placed there.

**Comment by cppwfs** [comment]
[Stopping a task/batch app using Data Flow]
The stop button in SCDF tells the Spring Batch app to stop its execution after the current step completes.   But there are no features to stop a app that has a subprocess that isn't terminating.
Destroying a task, just removes the definition, any running task will continue till it completes.

You can set the exit message to whatever you like, I've included an example below that lets the user set the exit message for their task after the task is finished:
```
@AfterTask
public void afterMe(TaskExecution taskExecution) {
    taskExecution.setExitMessage("AFTER EXIT MESSAGE");
}
```

**Comment by Rostish** [comment]
So, am i right? There are no ways to stop any task/composed task "righ now"?
I read documentation once again and there were not any section about **kill**  single task too.

Will you implement something in the future(maybe SCDF could get info about pid of started task and kill signal)? This is critical feature i suppose. For example, my company has cluster calculations. We have developed a rest servise that sends a request to SCDF to start definite scheme. This service has kafka listener that gets json messages with two dates.  Sometimes SCDF starts task with wrong parameters and start cluster with wrong task. In our production i can't kill it manually, it has to do by SCDF.

P.S. About exit message. I meant in the section with the message does not fit enough characters, it is impossible to read the full stack trace.

**Comment by cppwfs** [comment]
True, SCDF does not offer a way to stop a non batch task.
However a Composed Task Runner is built using Spring Batch.  So you can stop its execution, thus preventing other un executed child tasks in the graph from running.   

@sabbyanandan Do we have a story for a hard stop feature for SCDF?  I know we have discussed it in the past.

To your PS question: I've created a story: https://github.com/spring-cloud/spring-cloud-task/issues/445

**Comment by sabbyanandan** [comment]
Hi, yes, we do have a story to stop all executions (`kill -9` equivalent) [see: spring-cloud/spring-cloud-dataflow#858]. 

@Rostish: What does the following mean?

> Sometimes SCDF starts task with wrong parameters and start cluster with wrong task

Are you describing that SCDF is launching Tasks with wrong params or are you saying the events receieved by a Stream includes wrong params, so the Task is laucnhed with wrong values?

**Comment by mminella** [comment]
@sabbyanandan Do we really want a `kill -9` approach instead of allowing for executions to stop gracefully like most platforms do?

**Comment by sabbyanandan** [comment]
Sure, let's handle it gracefully. You will have to bless the design anyway.

**Comment by Rostish** [comment]
@sabbyanandan 
Me and my team work with cluster calculations. Our task is a spark-runner app that starts another jar with operations. We don't have access to kill process manually in production enviroment. Sometime our operations could hang or got wrong input parameter or calculate data too long. To resolve this problem i have created a special SCDF task that kill app using yarn kill command(SCDF task to kill SCDF task...."workaround", because only who has started a yarn process could kill yarn process). 

I think there are many situations where you need to destroy the application without waiting for execution. Sometime we see that our operation calculate too slow, we need to kill it and allocate more resources, but we need to wait 5 hours before stage will be completed).

**Comment by Rostish** [comment]
@sabbyanandan 
@mminella 
Have found another kind of this problem.
The task hung due to memory problems on the server. It is impossible to kill a task, because job takes order to stop after the completion of the current step. As a result, by restarting the application itself, we get a task that is hung in the status"Running" and job in status "Running or Completed" so that the status becomes correct, we have to set the error code and  the current task status in the database manually.

**Comment by sabbyanandan** [comment]
The scope of the investigation to add+prove the functionality in Local, CF, and K8s is now complete. As next steps, we will:

- expose a new RESTful endpoint - https://github.com/spring-cloud/spring-cloud-dataflow/issues/858
- add shell support - https://github.com/spring-cloud/spring-cloud-dataflow/issues/3303
- add UI support - https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1223
