### ISSUE TITLE
Add error message when parsing comma delimited apps in a stream when there is no space around the comma

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2429]
e.g. `parse("foo --aaa=bbb, bar")`

**Comment by sabbyanandan** [comment]
@markpollack: Could you clarify what you'd like to be handled here? Also, is this a test coverage issue or a feature gap?

**Comment by markpollack** [comment]
I believe there were some cases in the first commit of the new parser that required some fine tuning to handle.  This seems to have been addressed.  I added more tests (some of which were commented out) and will check with @aclement .
