### ISSUE TITLE
Support stream validation for type=app

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2440]
The current implementation of validation for streams uses 

```
		for (StreamAppDefinition streamAppDefinition : definition.getAppDefinitions()) {
			ApplicationType appType = DataFlowServerUtil.determineApplicationType(streamAppDefinition);
```
DataFlowServerUtil is now deprecated and it does not support the type `app`.  

Switch to getting the app type from stream definition and getting it from the 

```
		for (StreamAppDefinition streamAppDefinition : streamDefinition.getAppDefinitions()) {
			final String appName = streamAppDefinition.getRegisteredAppName();
			ApplicationType applicationType = streamAppDefinition.getApplicationType();
```

Looks like `getRegistredAppName` should be used instead of just `getName`

**Comment by tzolov** [comment]
@markpollack is this resolved? the `DefaultStreamValidationService#validateStream` already resolves the app type via `streamAppDefinition.getRegisteredAppName();`

**Comment by markpollack** [comment]
Yes, I clean it up as part of some other work.  closing...
