### ISSUE TITLE
Add support for mapping multiple LDAP groups to ROLES 

### ISSUE THREAD

**Issue by wevans2018** [spring-cloud/spring-cloud-dataflow#2444]
As a user, I'd like to configure the mapping of multiple LDAP AD groups against the SCDF roles (VIEW, CREATE, and MANAGE), so I can define the authorization rules in SCDF at the LDAP group level.

See [Issue 2084](https://github.com/spring-cloud/spring-cloud-dataflow/issues/2084) for reference to 1-1 mapping of ldap group to role.

Acceptance:

I can configure an AD groups for example ROLE_APP_MYAPPLICATION_ADMIN_AUTHZ_VIEW and ROLE_APP_MYAPPLICATION_USER_AUTHZ_VIEWagainst SCDF's ROLE_VIEW in the YAML. 

Currently it appears this AD role can be mapped, however it is a 1-1 mapping.

ROLE_VIEW: admin
ROLE_MANAGE: admin
ROLE_CREATE: admin 

Appear to be possible, however

ROLE_VIEW: admin, user
ROLE_MANAGE: admin
ROLE_CREATE admin

Does not appear to be a valid configuration.

**Comment by sabbyanandan** [comment]
Hi, @wevans2018. Thanks for creating an issue. It appears to be a valid request. We will review it as part of the SCDF 2.0 themes and timeline.

In the meantime, please feel free to submit a PR to add this functionality. We would be happy to work with on this.

**Comment by sabbyanandan** [comment]
Hi, @wevans2018. This should now be possible in v2.0 GA release. Here are an example [screencast](https://www.youtube.com/watch?v=dn-1-YzBvMU) and a [code sample](https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/security-ldap-uaa-example) that you can use as a reference.  

Let us know if you have any further feedback.
