### ISSUE TITLE
Unable to add multiple parameters to task when deployed via a stream

### ISSUE THREAD

**Issue by siddhantsorann** [spring-cloud/spring-cloud-dataflow#2451]
I have a task which takes 3 different parameters to run it's batch jobs. When running from UI i pass them as task arguments and it works. Now I am trying to create a stream which deploys the task with these parameters every 5 mins. I'm using the triggertask source and task-launcher-local sink for this. 
The following stream definition is giving me an error and not adding the stream:
`triggertask --environment-properties=appnexus_seat=SEAT_MIQ_1,last_modified=2018/08/03,start_element=0 --uri=file:///home/MIQDIGITAL/siddhant/scdf-tasks/spring-cloud-task-aiq-batch-module/aiq-appnexus-batch-service/target/aiq-appnexus-batch-service-3.23.1.jar --time-unit=MINUTES | task-launcher-local`
Error: 
```
Caught exception while handling a request: 100E:(pos 75): Found unexpected data after stream definition: '='
triggertask --environment-properties=appnexus_seat=SEAT_MIQ_1,last_modified=2018/08/03,start_element=0 --uri=file:///home/MIQDIGITAL/siddhant/scdf-tasks/spring-cloud-task-aiq-batch-module/aiq-appnexus-batch-service/target/aiq-appnexus-batch-service-3.23.1.jar --time-unit=MINUTES --fixed-delay=2 | task-launcher-local
```
Then when i add them as command-line-args I get the same error:
`triggertask --uri=file:///home/MIQDIGITAL/siddhant/scdf-tasks/spring-cloud-task-aiq-batch-module/aiq-appnexus-batch-service/target/aiq-appnexus-batch-service-3.23.1.jar --time-unit=MINUTES --fixed-delay=2 --command-line-args=appnexus_seat=SEAT_MIQ_1,last_modified=2018/08/03,start_element=0 | task-launcher-local`

But when i run the same with only one command line argument it run perfectly:
`triggertask --uri=file:///home/MIQDIGITAL/siddhant/scdf-tasks/spring-cloud-task-aiq-batch-module/aiq-appnexus-batch-service/target/aiq-appnexus-batch-service-3.23.1.jar --time-unit=MINUTES --fixed-delay=2 --command-line-args=appnexus_seat=SEAT_MIQ_1 | task-launcher-local`
**So the issue is with passing multiple arguments. How can i do that?**
Update on this: The above stream in which i'm passing params as command line is getting accepted in scdf server 1.6.0.RELEASE:
`triggertask --uri=file:///home/MIQDIGITAL/siddhant/scdf-tasks/spring-cloud-task-aiq-batch-module/aiq-appnexus-batch-service/target/aiq-appnexus-batch-service-3.23.1.jar --time-unit=MINUTES --fixed-delay=2 --command-line-args=appnexus_seat=SEAT_MIQ_1,last_modified=2018/09/10 | task-launcher-local`
But when i deploy this the task is run with command line:
`Job: [FlowJob: [name=advertiserLoadJob]] launched with the following parameters: [{appnexus_seat=SEAT_MIQ_1,last_modified=2018/09/10}]`
Since there is no space added in between them it takes the value of appnexus_seat param as "SEAT_MIQ_1,last_modified=2018/09/10" instead of taking last_modified as another param. the same issue i had reported when launching from UI for 1.6.0.RELEASE which was resolved in 1.7.0.M1:
https://github.com/spring-cloud/spring-cloud-dataflow/issues/2445

**Comment by sabbyanandan** [comment]
Hi, @siddhantsorann. It'd be great if you could avoid duplicate posts in multiple forums. If it is a question, please stick to StackOverflow; o'wise, for feature requests/bugs, use GitHub. 

To pass multiple k/v pairs as application properties, you can supply them at the time of stream/task deployment/launches.

For the following Stream definition:

> stream create --name foo --definition "triggertask --uri=file:///home/MIQDIGITAL/siddhant/scdf-tasks/spring-cloud-task-aiq-batch-module/aiq-appnexus-batch-service/target/aiq-appnexus-batch-service-3.23.1.jar --time-unit=MINUTES | task-launcher-local"

You'd pass custom k/v pairs as:

> stream deploy --name foo --properties "app.triggertask.appnexus_seat=SEAT_MIQ_1,app.triggertask.last_modified=2018/08/03,app.triggertask.start_element=0"
