### ISSUE TITLE
Add scheduler support for Local server

### ISSUE THREAD

**Issue by aritzbastida** [spring-cloud/spring-cloud-dataflow#2454]
Currently, there is only support for PCF Scheduler in Spring Cloud Data Flow. As a result, using any other runtime will raise exceptions when trying to use the scheduler "feature toggle".

Are there any plans to add Local Server scheduler support to the mix? It would be fine either to integrate it with Spring Scheduler or Quartz. Currently, the only options for scheduling with the Local server are to do it externally (maybe a cron process launching through the shell) or using triggertask. But both options are quite convoluted, comparing to the "Schedule" button in the Dashboard...

**Comment by sabbyanandan** [comment]
Hi, @aritzbastida. We are currently working on [Kubernetes implementation](https://github.com/spring-cloud/spring-cloud-scheduler-kubernetes). There's plan to add a Local implementation in the future, though.

In the meantime, it'd be great if you can contribute it to the project. You can use the CF and K8s as reference implementations of the [SPI](https://github.com/spring-cloud/spring-cloud-scheduler/blob/master/spring-cloud-scheduler-spi/src/main/java/org/springframework/cloud/scheduler/spi/core/Scheduler.java). We would love to work with you by reviewing the PR and guide you in the process.

**Comment by aritzbastida** [comment]
Thanks for your feedback, @sabbyanandan! I'm on holidays for the next three weeks (honey moon!), but I'll try to contribute to the Local implementation when I come back. 

Just to be sure, Quartz integration is preferred over Spring's internal TaskScheduler, right? Quartz allows to persist the scheduling information, so that would make sense.

**Comment by Manokethan** [comment]
Hi @aritzbastida and @sabbyanandan.

i'am interessed by the project quartz integration.. I will try to start to contribute to the project this weekend. i got some ideas, do you advise to use the LocalTaskLauncher from spring-cloud-deployer or via rest api to launch the launch the scheduled task ?
Advance thanks

**Comment by sabbyanandan** [comment]
@aritzbastida / @Manokethan: Great! Thanks for the continued interest in SCDF.

I'd suggest looking at the K8s-scheduler implementation for reference. It uses the [Fabric8](https://github.com/spring-cloud/spring-cloud-scheduler-kubernetes/blob/master/pom.xml#L28-L32) client to perform the REST operations [see [example](https://github.com/spring-cloud/spring-cloud-scheduler-kubernetes/blob/master/src/main/java/org/springframework/cloud/scheduler/spi/kubernetes/KubernetesScheduler.java#L136)]. Likewise, the CF-scheduler implementation uses [PCF-java-client](https://github.com/pivotal-cf/pcf-java-client).

**Comment by Manokethan** [comment]
Hi,

As promised, I worked on quartz integration in SCDF. You can see the result in my repo: https://github.com/Manokethan/spring-cloud-scheduler-quartz

I am a beginner in the world of spring. It is also the first time I contribute on github. Could you review the code and guide me in the process?

Hoping that the implementation follows your ideas.

Thank you beforehand.

**Comment by sabbyanandan** [comment]
Great. Thanks for the update! Before we start to review the work, please make sure you follow the [contributor guide](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/appendix-contributing.adoc), so the subtle things are taken care of right away.

Once when you're ready with it, please submit a pull-request against [spring-cloud-scheduler-quartz](https://github.com/spring-cloud/spring-cloud-scheduler-quartz) repo.

**Comment by Manokethan** [comment]
Thanks for your quick answer. I tried to make a pull but he redirects me to the main page of the repo showing that it is empty...

**Comment by sabbyanandan** [comment]
Fixed that. Please retry.

**Comment by Manokethan** [comment]
thanks, it worked. I submit a pull request https://github.com/spring-cloud/spring-cloud-scheduler-quartz/pull/1

**Comment by rtrompier** [comment]
Hi guys,
Any news about this feature ? 
Thx ;)

**Comment by cppwfs** [comment]
Our team has discussed this addition to the Spring Cloud Data Flow project.  At this point we will not be supporting a local scheduler..

**Comment by deshanshehntha** [comment]
Hi, Are there any updates for this issues ? Still no scheduler for SCDF local ?

**Comment by f3l1xss** [comment]
I find it quite baffling for this seemingly basic feature to be missing

**Comment by sabbyanandan** [comment]
Hi, folks. As you might have read in the docs or StackOverflow threads, the local impementation of the SCDF is recommended for dev/sandbox experimentation, and there are no resiliency patterns backed into the local deployment experience. Scheduling happens to be one of the critical components that you'd expect to have non-functional requirements baked-in, and we didn't want to add support for it and not meet the expectations fully.

The Local experience is intentionally not built with HA/FT in mind. Instead, using a platform like Kubernetes (and its native cronjob spec) would help orchestrate the scheduled launches more efficiently and predictably — the platform here takes the responsibility of resilient operations. I hope this clarifies our position.

All that said, there are few options to build and wrap a scheduler implementation that matches your desired deployment model, and we have them listed in the [Microsite](https://dataflow.spring.io/docs/feature-guides/batch/scheduling/#scheduling-a-batch-job) for reference (see under `Local` tab).
