### ISSUE TITLE
Security exception details shall not leak to clients

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2459]
When an authentication error occurs, exception details shall not leak to clients. Instead a generic message shall be return and details shall be logged at warning level to the console only.

**Comment by markpollack** [comment]
This is an old issue, is it still valid?

**Comment by onobc** [comment]
I am unable to reproduce. Auth errors are just sending back 401 - not any exception details. Some reproduce steps for the specific case would have been helpful.
