### ISSUE TITLE
Add TaskDefinition support to `ArgumentSanitizer`

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2469]
On the task side the sanitization support is mostly not there, only `TaskExecutions` are sanitized in the `TaskExecutionController`.

We also need:

- Add support to sanitize Task Arguments to `ArgumentSanitizer`
- Add a TaskDefinition-specific `dslConverter`, similar to `StreamDefinitionToDslConverter`
- Add unit tests

Ensure sanitization works for composed tasks.

See also gh-2461

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-dataflow/commit/d679ea60fcc965b6594f8ccb5335d067504ad984 and https://github.com/spring-cloud/spring-cloud-dataflow/commit/120d10b55cb59a3f87e09a3871c61ebc189598ed.
