### ISSUE TITLE
Exit Message not displayed in Task execution page

### ISSUE THREAD

**Issue by aritzbastida** [spring-cloud/spring-cloud-dataflow#2474]
Even if the "exit message" is set in the Task execution, this is displayed as N/A. I guess it's a visualization error, because the REST endpoint is correctly providing such information in the JSON. 

I'm using SCDF Local 1.6.2.

![image](https://user-images.githubusercontent.com/2572295/46535774-af8d4000-c8ac-11e8-9cf8-3d56c2c95dea.png)

**Comment by aritzbastida** [comment]
Ok, I just guessed! The "Exit Message" does not correspond to the task exit message attribute, but the error message instead! 

It's quite confusing. Shouldn't both be included in the form data?

**Comment by sabbyanandan** [comment]
The UI appears to pull the [right model attributes](https://github.com/spring-cloud/spring-cloud-dataflow-ui/blob/9e7997008ca0569c28f80a3e0b81a2a9a18eca1a/ui/src/app/tasks/task-execution/task-execution.component.html#L68-L74), but maybe the mapping is wrong somewhere. I will move it to UI backlog. 

Thank you for reporting - we will investigate.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#928
