### ISSUE TITLE
Add Custom JDBC Driver to Spring Cloud Data Flow Server

### ISSUE THREAD

**Issue by mrbq** [spring-cloud/spring-cloud-dataflow#2489]
Hi,

In the documentation it is specified that to add a new JDBC driver it is necessary to change the pom.xml and rebuild the project.  I was not confortable with this approach, so I implemented an extension of the Spring Cloud Data Flow Server image:

```
FROM springcloud/spring-cloud-dataflow-server-kubernetes:1.5.2.RELEASE

#Get the oracle driver jar
COPY ojdbc8-12.2.0.1.jar /maven/lib/ojdbc8-12.2.0.1.jar

ENTRYPOINT ["java", "-cp", "/maven/spring-cloud-dataflow-server-kubernetes.jar", "-Dloader.path=/maven/lib", "org.springframework.boot.loader.PropertiesLauncher"]
```
Is this ok or could it have any side effect? In my opinion to implement an image extension is better than to change the project's dependencies.

Thanks!

**Comment by gdubya** [comment]
I was about to open a similar isssue / feature request then found this one.

I agree that the instructions could be improved. There's a bit of a discrepancy in the "Configuration" chapter of the reference guide between what to do depending on whether one is targeting local, cloud foundry, or kubernetes.

For "local", wouldn't it be enough to add the `-Dloader.path` option to the `java` command to specify the path to the third-party driver?

Similarly, for kubernetes / Docker there could be a 'standard location' inside the container image for third-party drivers, such that users can ensure that the required driver is copied to that location when the image is created.

**Comment by sabbyanandan** [comment]
Hi, @mrbq / @gdubya. My apologies for the delayed update. The good news is that we are going to look into options to come up with a simplified approach to patch the servers with proprietary drivers. If you have any additional thoughts or suggestions, feel free to leave as comments here. It'd be good also to know how have you managed to run SCDF/Skipper with special drivers today. Also, what database are you using?

**Comment by gdubya** [comment]
Hi @sabbyanandan, to keep things as 'close to documentation' as possible we decided to introduce a postgres database specifically for SCDF. This appears to be working fine so far, so we currently don't need to look further into supporting 'other' databases. But, should our situation change, we would be looking at using Oracle (12c SE2).

**Comment by mrbq** [comment]
Hi @gdubya ,

I had the same problem with an Oracle DB. I added the driver and configure the PropertiesLauncher as you can see in my first comment.

The only problem is that I have to build my own custom SCDF images but it worked fine.

Have you find any other solution to this issue?

Best regards
