### ISSUE TITLE
Perhaps address DSL parsing inconsistency for short arg values using special chars

### ISSUE THREAD

**Issue by aclement** [spring-cloud/spring-cloud-dataflow#2499]
Discovered whilst chatting with Mark P.

We have a number of special characters that terminate an arg value (if not in quotes):
```
"|"   ";"   " "   "\t"   "\n"   ">"   ","   "\r"
```

So this is fine:
`foo --aaa=bbb, bar`
the value of `aaa` is `bbb`, and there are two apps here `foo` and `bar`.

However, if you only have an arg value of a single character that is the special character, the special character fails to terminate the argument value:

`foo --aaa=| bbb`

What do you expect there? 

Currently you will get an error because `|` is not treated as terminating the arg value. and so it considers the first argument to be `aaa`=`|` and then it is looking for a special character or another argument but it immediately hits `bbb`.  This goes for all the special characters, we found this because of Marks test:

`foo --aaa=,, bbb`

Right now this parses as valid - for the first app `foo` the argument `aaa` is `,` and then there is a `,` then the second app `bbb`.

Strictly speaking if `,` should terminate an arg value unless quoted then it should fail to parse because there is no app specified between the two commas (and the value of `aaa` should be `""`)

I haven't jumped on fixing this ... because it is more widespread than I first thought. I initially thought it was a problem just for the new `,` but it is actually affecting all the special symbols. That means changes will affect anyone currently relying on this behaviour.  What do we think? Fix for consistency or is this ability to pass single special chars without quoting convenient?

**Comment by sabbyanandan** [comment]
Thank you for a thorough write-up and the examples. It was hard to grok at first, but on a repetitive read, I get it.

To this example: `foo --aaa=,`

It'd be better to simply expect the user to supply the value for `aaa` as "". That would be `foo --aaa="",`. If it is not provided, we can fail the parsing and let the users know about it. 

It could get complicated (even to read the DSL) if we allow values without quoting. It gets even harder if there are multiple k/v pairs for each app in the DSL.

**Comment by aclement** [comment]
That pull request above relates to addressing this server side. The pull request that additionally fixes the client side parser is here: https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/1030

**Comment by aclement** [comment]
They don't need integrating in a particular order or simultaneously - but both must be done to keep things consistent.
