### ISSUE TITLE
Provide some way to assess health status of composed task runner

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2503]
When using a **Composed Task Runner** in a secured SCDF environment and security of the CTR is not configured (properly), then you may see pending tasks that are never updated:

![image](https://user-images.githubusercontent.com/685363/47119206-bc435980-d205-11e8-8d70-6eaf1bc052cd.png)

This results in a bad user experience. Since it is SCDF that starts the CTR, we should be able to verify that security is properly configured (at least on a basic level).

**Comment by sabbyanandan** [comment]
Wrapped it in https://github.com/pivotal/scdf-pro-ui/issues/42.
