### ISSUE TITLE
Docs: Add Security section on how to configure composed task runner when security is enabled

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2504]
See also: https://github.com/ghillert/ldap-composed-task-runner-example

**Comment by sabbyanandan** [comment]
This has been addressed via https://github.com/spring-cloud/spring-cloud-dataflow/pull/2844/files, and an [example](https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/security-ldap-uaa-example#configure-and-run-a-composed-task) is available as well.
