### ISSUE TITLE
ExitCode for a task execution displays 0 for `null`

### ISSUE THREAD

**Issue by mminella** [spring-cloud/spring-cloud-dataflow#2510]
**Description:**
Before a task has completed, the exit code in the task repository is null.  However, in both the shell and UI for SCDF, we display 0.  The cause of this is that the `TaskExecutionResource` uses an `int` for the `exitCode` instead of an `Integer`.

**Release versions:**
1.7.0.RC1

**Custom apps:**
N/A

**Steps to reproduce:**
Run a task and view the execution data via SCDF before it completes.  Even though the value is `null` in the database, it is 0 in the UI and shell.

**Screenshots:**
```
dataflow:>task execution list
╔═══════════════════════════════╤══╤════════════════════════════╤════════════════════════════╤═════════╗
║           Task Name           │ID│         Start Time         │          End Time          │Exit Code║
╠═══════════════════════════════╪══╪════════════════════════════╪════════════════════════════╪═════════╣
║mys3jdbc_s3jdbc_load:partition1│1 │Wed Jun 20 13:31:59 CDT 2018│Wed Jun 20 13:32:09 CDT 2018│0        ║
║myFileImport                   │2 │                            │                            │0        ║
╚═══════════════════════════════╧══╧════════════════════════════╧════════════════════════════╧═════════╝
```
<img width="1204" alt="screen shot 2018-10-19 at 11 02 40 am" src="https://user-images.githubusercontent.com/630743/47229942-a0b78a80-d38e-11e8-9ca5-f52c01a58c21.png">

```
mysql> select * from task_execution;
+-------------------+---------------------+---------------------+---------------------------------+-----------+--------------+---------------+---------------------+---------------------------------------------------+---------------------+
| TASK_EXECUTION_ID | START_TIME          | END_TIME            | TASK_NAME                       | EXIT_CODE | EXIT_MESSAGE | ERROR_MESSAGE | LAST_UPDATED        | EXTERNAL_EXECUTION_ID                             | PARENT_EXECUTION_ID |
+-------------------+---------------------+---------------------+---------------------------------+-----------+--------------+---------------+---------------------+---------------------------------------------------+---------------------+
|                 1 | 2018-06-20 13:31:59 | 2018-06-20 13:32:09 | mys3jdbc_s3jdbc_load:partition1 |         0 | NULL         | NULL          | 2018-06-20 12:32:09 | mys3jdbc-bf829e44-5191-478b-9fec-4eb57bbb4a9c     |                   1 |
|                 2 | NULL                | NULL                | myFileImport                    |      NULL | NULL         | NULL          | 2018-10-18 17:21:10 | myFileImport-7ffa48f2-e16d-4de0-90e3-b1348d203ec3 |                NULL |
+-------------------+---------------------+---------------------+---------------------------------+-----------+--------------+---------------+---------------------+---------------------------------------------------+---------------------+
2 rows in set (0.00 sec)
```

**Additional context:**
N/A

**Comment by ilayaperumalg** [comment]
Along with `exitCode` being `Integer`, we also need to fix the `getExitCode` method [logic](https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-core/src/main/java/org/springframework/cloud/task/repository/TaskExecution.java#L125) in Spring Cloud Task as I believe we can't return the exit code `0` if it is null.

**Comment by ilayaperumalg** [comment]
Created PR for Spring Cloud Task changes: https://github.com/spring-cloud/spring-cloud-task/pull/460

**Comment by cppwfs** [comment]
Before making changes to Spring Cloud Task.   We need to revisit why this exitCode needs to be nullable.   Back in the 1.0.0 days we discussed having a null state, I even remember starting  it out as a Integer.  But we had discussions on the viability as to whether it was a good idea to have a TaskExecution with an exitCode of null.   It was determined that 0 meant that the task execution was still in a valid state until the exit of the application determined that it should be something else.

**Comment by ilayaperumalg** [comment]
Sure, let's discuss on this.

The changes on the Spring Cloud Task side are just to depict the overall changes required to get the correct exit code with the following scenario:

1) If the task execution is created, running but not completed, then the exit code is null
2) If the task execution is completed/terminated, then the `Integer` type exit code with a non-null value.

**Comment by cppwfs** [comment]
Also CTR will have to  be updated to support this.   It only checks for 0, it will have to be updated to check for Null and Zero as a valid case.
