### ISSUE TITLE
Composed-Tasks: Security arguments for tasks are printed in cleartext

### ISSUE THREAD

**Issue by Rostish** [spring-cloud/spring-cloud-dataflow#2516]
Description:
Spring cloud data flow users could see values of security arguments --dataflow-server-username and  --dataflow-server-password through WebUI or in Log of SCDF.

Release versions:
I have found this problem in 1.7.0, 1.7.0RC1 and earlier.

Steps to reproduce:
-Enable LDAP
-Create any Task
-Start composed task with arguments --dataflow-server-username and  --dataflow-server-password.
-Look at Job tab in WebUI or SCDF logs.

Screenshots:
![image](https://user-images.githubusercontent.com/15521647/47479761-ce8d4b00-d836-11e8-9bac-390a73401051.png)
![image](https://user-images.githubusercontent.com/15521647/47479791-e2d14800-d836-11e8-8747-46e08b563ab6.png)

But you couldn't see password in Tasks tab:
![image](https://user-images.githubusercontent.com/15521647/47479862-16ac6d80-d837-11e8-8e55-75f51482d992.png)

**Comment by sabbyanandan** [comment]
@Rostish: Thank you for reporting this. There's a gap in the `ArgumentSanitizer` for Tasks in general. And, we are tracking this at spring-cloud/spring-cloud-dataflow#2469.
