### ISSUE TITLE
Support registering application with specific SNAPSHOT version

### ISSUE THREAD

**Issue by ioben** [spring-cloud/spring-cloud-dataflow#2517]
Problem description:
We perform CI builds and tests on every PR made to the repository. After building snapshots, we'd like to be able to deploy them to SCDF for integration testing. Currently we can only deploy the latest SNAPSHOT version, which can cause issues if multiple buillds/tests are running in parallel.

Solution description:
Support registering applications with a specific SNAPSHOT version (example of [Gradle adding support](https://issues.gradle.org/browse/GRADLE-2784) for this).

Description of alternatives:
We could create patch versions, or alpha versions for each build of each PR, but this would get cumbersome. I'm not sure of any other alternatives that exist (if you can think of any let me know!).

Additional context:
We'd additionally need to modify [nulldriver's maven Concourse resource](https://github.com/nulldriver/maven-resource) or create our own resource to return the SNAPSHOT version, so it could be passed to SCDF during application registration. Maybe with a general Concourse resource for SCDF similar to [nulldriver's cf-cli-resource](https://github.com/nulldriver/cf-cli-resource)?

**Comment by sabbyanandan** [comment]
Hi, @ioben. Thank you for the interest in Spring Cloud Data Flow! 

1) > Support registering applications with a specific SNAPSHOT version

You can do that already. For Maven/Gradle artifacts, when you're in SNAPSHOTs, the build system would produce an artifact with a timestamp attached to it. Your CI pipeline could register the absolute (jar) artifact name as opposed to stopping at the artifact version. For example, if I've an application named `foo` at version `1.0.0.BUILD-SNAPSHOT`, for every code commit, build, and CI run, I'd see something like the following in artifactory.

```
...
...
foo-1.0.0.BUILD-20181024.212007-9.jar             24-Oct-2018 21:20  32.45 MB
foo-1.0.0.BUILD-20181025.142401-10.jar            25-Oct-2018 14:24  32.45 MB
foo-1.0.0.BUILD-20181025.223025-11.jar            25-Oct-2018 22:30  32.45 MB
```

You'd then be able to register the same application "n" number of times with different versions. 

```
dataflow:>app register --name foo --type sink --uri maven://org.example.com:foo:1.0.0.BUILD-20181024.212007-9
Successfully registered application 'sink:foo'
dataflow:>app register --name foo --type sink --uri maven://org.example.com:foo:1.0.0.BUILD-20181025.142401-10
Successfully registered application 'sink:foo'
dataflow:>app register --name foo --type sink --uri maven://org.example.com:foo:1.0.0.BUILD-20181025.223025-11
Successfully registered application 'sink:foo'
dataflow:>app list --id sink:foo
╔═══╤══════╤═════════╤═════════════════════════════════════╤════╗
║app│source│processor│                sink                 │task║
╠═══╪══════╪═════════╪═════════════════════════════════════╪════╣
║   │      │         │> foo-1.0.0.BUILD-20181024.212007-9 <│    ║
║   │      │         │foo-1.0.0.BUILD-20181025.142401-10   │    ║
║   │      │         │foo-1.0.0.BUILD-20181025.223025-11   │    ║
╚═══╧══════╧═════════╧═════════════════════════════════════╧════╝
```

You stream upgrade IT/acceptance-tests can then pick and choose a particular version as needed.

2) > Maybe with a general Concourse resource for SCDF similar to nulldriver's cf-cli-resource?

We have talked about it in the past, but we haven't had any particular interest around it so far. Here's an [example Concourse CI pipeline](https://github.com/sabbyanandan/xfmr/blob/master/ci/pipeline.yml) that demonstrates the CI/CD of a streaming application in SCDF; from code commit all the way to production. A lot of the pipeline configurations can be simplified if we had a SCDF Concourse-resource of some kind.

If you have familiarity in this space (unfortunately, we don't), please feel free to submit a PR. We would be happy to work with you and the Concourse team.

**Comment by ioben** [comment]
Thanks Sabby!

1. Turned out I was just writing the version out incorrectly. I was attempting to use `0.1.0.SNAPSHOT-<TIMESTAMP>` instead of `SNAPSHOT-0.1.0-<TIMESTAMP>`, thanks for the example!

2. Again, thanks for the link, it'll be a huge help for implementation. I'm really interested in starting a custom resource for SCDF, possibly based off [the concourse smuggler resource](https://github.com/redfactorlabs/concourse-smuggler-resource). I'll be sure to reach out once that gets underway!
