### ISSUE TITLE
Restarting a failed batch job gives an error as it adds 2 driver classes

### ISSUE THREAD

**Issue by siddhantsorann** [spring-cloud/spring-cloud-dataflow#2519]
Description:
When I restart a failed batch job it gives me an error as I think it's re-adding the driver class. 

Release versions:
1.7.0.RELEASE Kubernetes Server

Steps to reproduce:
1. Run a failing batch job
2. Restart it from UI 

Error:

`Cannot load driver class: org.mariadb.jdbc.Driver,org.mariadb.jdbc.Driver`

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private javax.sql.DataSource org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration.dataSource; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: org.mariadb.jdbc.Driver,org.mariadb.jdbc.Driver
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]

```

**Comment by sabbyanandan** [comment]
When reporting problems like this, you'd have to share more details. Did the job run successfully in the first run? What is the full stacktrace? Better yet, can you share the batch-job?

**Comment by siddhantsorann** [comment]
I purposely failed the job on the first run to test the restart job feature. When I restarted the failed job it didn't start the task only because I got the above error. Basically, the driver is not recognized as its been added twice. It's pretty much like this issue... https://github.com/spring-cloud/spring-cloud-dataflow/issues/1800

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-server-kubernetes#351
