### ISSUE TITLE
Review examples/snippits in reference docs

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2520]
Seems like we have a few that don't work, e.g. reference `x-spring-tuple` and `--outputType`.  Investigate why `--outputType` doesn't work, seems like it is a handy shortcut that got removed (perhaps unintentionally)

**Comment by sabbyanandan** [comment]
Specifically, also, let's review all the samples that include `--expression`.

**Comment by sabbyanandan** [comment]
Closing this in favor of #2555.
