### ISSUE TITLE
Cron Expression not being accepted

### ISSUE THREAD

**Issue by siddhantsorann** [spring-cloud/spring-cloud-dataflow#2521]
Description:
Cron expressions which have been used in Java are not being accepted. There seems to be an issue with the regex format uploaded to scdf kubernetes server. "0 0 0/1 * * ?" This particular expression represents every hour, every day. But its not being accepted in scdf server as the regex format added there is "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$" which doesnt allow spaces, decimals, fraction and "?", all of which are used to represent a cron expression. 
v1.7.0.RELEASE Kubernetes

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-server-kubernetes#350
