### ISSUE TITLE
Spring Cloud Data Flow UI SideMenu Style Bug

### ISSUE THREAD

**Issue by LoopSun** [spring-cloud/spring-cloud-dataflow#2524]
Description:

> runtime/apps
> streams
> tasks
> jobs
> analytics
These menu have a style 
```
element.style {
    display: none;
}
```

Release versions:

1.7.0.RELEASE

Custom apps:
None

Steps to reproduce:
None

Screenshots:
![image](https://user-images.githubusercontent.com/15653731/47726746-13314000-dc96-11e8-90e6-5709416f2295.png)

![image](https://user-images.githubusercontent.com/15653731/47726831-3a880d00-dc96-11e8-83b9-cd250a769d5e.png)

Additional context:
None

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#972
