### ISSUE TITLE
Docker compose app-import broken in master

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow#2528]
the `app-import` service image was updated to `springcloud/openjdk:latest`. when running with `DATAFLOW_VERSION=1.7.0.RELEASE` the `app-import` service will error with:

`app-import_1       | /bin/sh: 2: nc: not found`

looks like we need to update the `springcloud/openjdk:latest` image to include `nc`

edit: also need `wget`

**Comment by sabbyanandan** [comment]
I ran the [quick-start](http://cloud.spring.io/spring-cloud-dataflow/#quick-start) workflow just after the release. A `ticktock` deployed successfully, too. Are you sure?

**Comment by sabbyanandan** [comment]
Just tried the [quick-start](http://cloud.spring.io/spring-cloud-dataflow/#quick-start) experience again:

![image](https://user-images.githubusercontent.com/1562654/47795014-e05f6a00-dcde-11e8-91f9-344a779fc874.png)

**Comment by chrisjs** [comment]
sorry i was running out of master and just assumed that image update went out with 1.7 - that might be why

**Comment by chrisjs** [comment]
ah yea, im running out of master so while I'm bringing down 1.7.0.RELEASE for DF image, the compose-file on disk is being used which uses the new image

**Comment by chrisjs** [comment]
@sobychacko updated the image w/ `wget` and `nc` - LGTM now
