### ISSUE TITLE
Provide ModuleDeployer TCK

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow#253]
Provide (eg an abstract base class) with tests covering all ModuleDeployer lifecycle cases.

Subclasses should implement hooks (eg to forcefully mess with a module deployment via out-of-band) and be allowed to opt-out of operations that can't be achieved on a particular runtime.

Of particular interest is to test the deployment status computations.

**Comment by sabbyanandan** [comment]
Is this a duplicate of #292?

**Comment by ericbottard** [comment]
Yes, closing
