### ISSUE TITLE
Document all the fields returned by the RESTDocs

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2538]
Investigate fieldWithPath to subsectionWithPath replacements.

Look where we want to doc all the fields vs. a subset ( batch responses can be quite lengthy)

The goal is to make sure we are pulling all the fields returned by the RESTDocs, so nothing is missed in the final doc artifacts.

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-dataflow/commit/c2736fc421320ffe266c409f999423db812464c3.
