### ISSUE TITLE
Investigate use of RelaxedNames class copied from Boot

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2541]
Child of #914

**Comment by sabbyanandan** [comment]
Look for the following [hits](https://github.com/spring-cloud/spring-cloud-dataflow/search?q=RelaxedNames&unscoped_q=RelaxedNames). The `WhitelistProperties.java` in particular is more important to revisit.

**Comment by sabbyanandan** [comment]
Based on the discussion, it has been decided that we would continue to use it.
