### ISSUE TITLE
Investigate Boot 2 upgrade issue in ShellCommandsTests

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2543]

**Comment by jvalkeal** [comment]
This indeed seem to be caused by core/boot trying to send `ApplicationReadyEvent` after context has already been closed(due to boot app run finishing ok). Weird, don't really know if this is a real issue or just some testing issues as that test class is a bit odd.

**Comment by ilayaperumalg** [comment]
Isn't this what we fixed as https://github.com/spring-cloud/spring-cloud-dataflow/commit/34d746abf38095810d60d6e06703ae8be436f7d7 ?

**Comment by jvalkeal** [comment]
No, just realised that it's coming from our `ShellCommandLineRunner` which is then closing a context and only after that boot is trying to send that `ApplicationReadyEvent`. I now remember that there were some changes in boot what comes for a app lifecycle events.

**Comment by sabbyanandan** [comment]
@jvalkeal: What's your recommendation on this? Do we have to switch Shell to Boot 2.0?
