### ISSUE TITLE
Better handle duplicates in TaskController.

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow#255]
See https://github.com/spring-cloud/spring-cloud-dataflow/blob/dcaab25914c9f90d7bf2f42c60a632d8b5366c6a/spring-cloud-dataflow-admin-starter/src/test/java/org/springframework/cloud/dataflow/admin/controller/TaskControllerTests.java#L125

**Comment by cppwfs** [comment]
Now returns a 409 (conflict) error code.
