### ISSUE TITLE
Revisit copied batch admin feature

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#2550]
As batch admin is not maintained, relevant classes were copied under `org.springframework.cloud.dataflow.server.batch`. Mostly ok but i.e. no defaultSerializer(XStreamExecutionContextStringSerializer) in SimpleJobServiceFactoryBean. 

Child of #914

**Comment by jvalkeal** [comment]
For example:

https://github.com/spring-cloud/spring-cloud-dataflow/blob/475fa89437b6d586d62ccb6b0478163e139f1e09/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/batch/SimpleJobServiceFactoryBean.java#L218-L224

**Comment by cppwfs** [comment]
More detail can be found here: https://github.com/spring-cloud/spring-cloud-dataflow/issues/2665

**Comment by sabbyanandan** [comment]
Closing this in favor of #2665.
