### ISSUE TITLE
Delete a task execution is not working

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow#2552]
**Description:**
Delete a task execution is not working.
After create and launch a task execution, the API provides a service to delete the execution.
Perform the delete request returns a success response (`200`) but the execution is not deleted.

**Release versions:**
- Implementation Version: 1.7.1.BUILD-SNAPSHOT (spring-cloud-dataflow-server-local)
- Core: 1.7.1.BUILD-SNAPSHOT (Spring Cloud Data Flow Core)
- Dashboard: 1.7.0.RELEASE (Spring Cloud Dataflow UI)
- Shell: 1.7.1.BUILD-SNAPSHOT (Spring Cloud Data Flow Shell

**Steps to reproduce:**
- Create a task (timestamp)
- Launch the task
- Delete the execution using the REST API (`curl 'http://localhost:9393/tasks/executions/{{ID}}' -i -X DELETE`)
- Success response but the task execution is not deleted

**Comment by jvalkeal** [comment]
@cppwfs well, `TaskExecutionController` has a `DELETE` mapping?

**Comment by cppwfs** [comment]
Dug into this a little bit.   It leads to the Spring Cloud Deployer's resource cleanup:
https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/task/TaskLauncher.java#L75-L85

It looks like this method needs to be moved to a new/different controller or renamed.

**Comment by cppwfs** [comment]
Looks like its a Restful API doc hiccup.   This bug goes against the DELETE on TaskExecutions in the API-GUIDE.  Instead of `The task executions endpoint lets you delete a task execution. The following topics provide more detail`.   It should say, `The task executions endpoint lets you cleanup the resources created for the deployment of a task execution`.

**Comment by cppwfs** [comment]
Thanks @oodamien for finding this!
