### ISSUE TITLE
Refactor classic and skipper class names

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow#2559]
Refactor and unify all class and configurations names referring to Skipper or Classic mode. 

Consider using just `Stream` as a convention.    

Child of #2548
Depends on #2553

**Comment by markpollack** [comment]
Review the class hierarchy of 
```public class DefaultAppRegistryService extends AbstractAppRegistryCommon implements AppRegistryService```

since it used to accommodate differences between skipper and classic mode. More methods can be moved up into the interface.

**Comment by markpollack** [comment]
Merge StreamDeploymentController with SkipperStreamDeploymentController

**Comment by markpollack** [comment]
Revisit StreamCommandTemplate.verifyExists implementation and associated test
