### ISSUE TITLE
Refactor children of DataFlowAppDefinition

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#2597]
child of #914

**Comment by ilayaperumalg** [comment]
Though it might look better to have a common base class for both `StreamDefinition` and `TaskDefinition` , refactoring `DataflowAppDefinition` is complex and may not be necessary as the current design considers `StreamAppDefinition` and `TaskDefinition` in the same hierarchy. Closing this for now.
