### ISSUE TITLE
Implement flyway migration structure

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#2599]
Design migration structure for existing 1.7.x schema vs. starting from scratch with 2.0.x.

child of #914.

**Comment by DasBratin** [comment]
How to launch SCDF 2.0. version because its giving flyway errors,older version of SCDF was installed in the evironment & has the related tables,new version 1.7 could be installed but major version 2 is giving flyway issues while installation

**Comment by ovolkovskyi** [comment]
We also have the same problem, is there any documentation on how to migrate existing schemma to 2.5.1. 

Is there an easy way ?
