### ISSUE TITLE
Add Grafana Dashboard for Streams in Prometheus

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow#2603]
Child of #2601

**Comment by tzolov** [comment]
Quick start: 
1. Go into `spring-cloud-dataflow/src/grafana/prometheus/docker`
2. set `export SCDF_HOST_IP=<your host IP>` environment.  You can use `source ./find_host_ip.sh` script to set it for you.
3. Run
```
docker-compose up -d --build
```
later provisions and configures pometheus, grafana and discovery containers and and registers the dashboards.  

Grafana can be accessed at `http://localhost:3000` with `admin`:`admin` credentials.

4. The The SCDF server has to be started with:
```
--spring.cloud.dataflow.applicationProperties.stream.management.metrics.export.prometheus.enabled=true 
--spring.cloud.dataflow.applicationProperties.stream.spring.cloud.streamapp.security.enabled=false 
--spring.cloud.dataflow.applicationProperties.stream.management.endpoints.web.exposure.include=prometheus
```

**Comment by markpollack** [comment]
http://localhost:3000/d/scdf-streams/scdf-streams?var-stream_name=ticktock2

**Comment by markpollack** [comment]
http://localhost:3000/d/scdf-streams/scdf-streams?var-stream_name=ticktock2&var-application_name=btime
