### ISSUE TITLE
Update SCDF docs to reflect the micrometer based metrics collection

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow#2605]
Child of #2601

**Comment by sabbyanandan** [comment]
This is addressed via: https://github.com/spring-cloud/spring-cloud-dataflow/commit/9b7267b89ee11668eb5fd55f9bc560a4abf51edb, https://github.com/spring-cloud/spring-cloud-dataflow/commit/c29717b2bbbc3d25eb0a24095610d5db01e98b68, and https://github.com/spring-cloud/spring-cloud-dataflow/commit/e4c1590530e538b550536a0770f92f13dbed53d3
