### ISSUE TITLE
Cleanup ref. guide to toggle between Local, CF, and K8s platform specific docs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2614]
child of spring-cloud/spring-cloud-dataflow#2613

**Comment by Buzzardo** [comment]
I pushed a PR that has a single, simple file in it. It is an Asciidoc file that uses the multi-file linking arrangement that Framework has adopted and that we're pushing into the entire document set.

At present, the links are placeholders. Once the three files have been created, we can fix the links. Please let me know how else I can help.

**Comment by Buzzardo** [comment]
DO NOT MERGE

I chatted a bit with Mark Pollack, and he wants to hold off on this work until the consolidated documentation work is done. So, please don't merge this one just yet. We'll get to it later.

**Comment by sabbyanandan** [comment]
@markpollack: As an FYI, we have cleaned up to remove classic mode references from v2.0 docs of CF and K8s. 

Here are the following areas to revisit and cleanup.

1) We will have to remove cross-linking of "core" docs in CF and K8s

2) When we remove the cross-links, we have to make sure they don't disturb 1.x docs in any capacity

3) Ultimately, we want the platform-specific docs to be migrated over from the individual repos into "core" docs' folder directly

4) This PR needs to then amend the links to point to core docs' instead of CF and K8s repos

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-dataflow/commit/b972c9057a84817a619213a09e9094f25f4e0bbd.
