### ISSUE TITLE
@AfterTask annotation and setExitMessage stops execution of the graph after Sync point.

### ISSUE THREAD

**Issue by Rostish** [spring-cloud/spring-cloud-dataflow#2619]
**Description:**
I have a big scheme with 32 tasks.
All this tasks are inherited from a single task(the same jar).
I am using the annotation @Aftertask to set new exit message:

Example:

```
    @Override
    public void run(String... args) throws Exception {
        initDataBusRestClient(this.dataSourceDataBus, this.port, this.userNameDataBus, this.passwordDataBus);
        if (isDataSavedAlready(this.dataBusRestClient)) {
            this.exitMessage = "Operations data has saved already.";
        } else {
            initOperation(this.operationProperties);
            setOperationDate(this.operationDate);
            setArgs(this.pointProperties);
            execOperation(this.operation, this.mode, this.dataBusRestClient, this.pointProperties);
            this.exitMessage = "Task completed normally.";
        }
    }

@AfterTask
public void putExitInformation(TaskExecution taskExecution){
      taskExecution.setExitMessage(this.exitMessage);
 }
```
My graph:

![image](https://user-images.githubusercontent.com/15521647/49153622-529b8c80-f327-11e8-8541-c34720581e3c.png)

When i start it only the first three parallel task are executed. Composed Task Runner said all steps are completed and CTR finish it work. But job status is failed. The rest part of graph won't even start. When i remove @AfterTask annotation then graph execution going well to the end. I put screenshot to the end of bug report/

**Steps to reproduce:**
1. Create graph with SYNC parts and parallel tasks.
2. Have to use @AfterTask annotation and set new exit message
3. Run and watch

**Screenshots:**
Composed task runner log.
Where applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/15521647/49154065-83c88c80-f328-11e8-8cf9-cee3d76991a2.png)

**Additional context:**
I do not use anything unusual. I use spring boot for main task app.

**Comment by cppwfs** [comment]
Can you provide the versions for the following?
* Spring Cloud Data Flow Version (and platform)
* Spring Cloud Task
* Composed Task Runner

Thanks!

**Comment by Rostish** [comment]
Is it enought?
![image](https://user-images.githubusercontent.com/15521647/49155745-c68c6380-f32c-11e8-8d02-2e7c01fa75bc.png)

additionally I added CTR 2.0.0 to apps.

**Comment by cppwfs** [comment]
What version of task are you using for your task apps?

**Comment by Rostish** [comment]
if we speak about CTR so i use 2.0.0
![image](https://user-images.githubusercontent.com/15521647/49156179-c345a780-f32d-11e8-9b68-56cd11ce1e87.png)

**Comment by cppwfs** [comment]
In this case its the actual task apps that the CTR is running.    i.e the task version you are using for `Viewing-Download`.

**Comment by Rostish** [comment]
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-task</artifactId>
            <version>2.0.0.RELEASE</version>
        </dependency>

**Comment by cppwfs** [comment]
CTR utilizes Spring Batch as its model for executing a Graph.   The source of the issue is that CTR uses the ExitMessage as one of its factors to determine what will be the next step (Task Application) to execute.   As discussed here: https://github.com/spring-cloud-task-app-starters/composed-task-runner/blob/master/spring-cloud-starter-task-composedtaskrunner/README.adoc#traversing-the-graph . We see that CTR uses the ExitMessage of the Task to determine the ExitStatus of each step.   This Exit Status can be either COMPLETE, FAILED, or used in a Transition (https://github.com/spring-cloud-task-app-starters/composed-task-runner/blob/master/spring-cloud-starter-task-composedtaskrunner/README.adoc#transitions).   In the case of the `Split` the ExitStatus of the step (Task Application) must be either COMPLETED or FAILED to get the expected `split` result.

**Comment by cppwfs** [comment]
However, this level of detail is not in the documentation as to what the expected ExitStatus of a step that is contained in a split.   I will update the documentation.

**Comment by Rostish** [comment]
@cppwfs 
Glenn, could you help me&
I just wanna provide some additional info After task or Before task and maybe you could give me advice about right field of TaskExecution class?

**Comment by cppwfs** [comment]
Also updated README for CTR https://github.com/spring-cloud-task-app-starters/composed-task-runner/pull/54

**Comment by cppwfs** [comment]
@Rostish We can chat on your request in the Spring Cloud Task Gitter Channel.
