### ISSUE TITLE
Simplify/refactor HATEOAS resource requirements

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#2622]
We use the HATEOAS ResourceSupport implementation of the domain classes for the REST controller response entities.

GIven we start using the Spring Data JPA for repositories and can expose the REST resource from them, we can simplify and possibly remove the duplication of ResourceSupport classes.

child of #914

**Comment by sabbyanandan** [comment]
Based on the discussion, we cannot use the JPA entities because they are too heavy (eg: Stream deployment's state calculation).
