### ISSUE TITLE
Refactor Resource assembler implementations

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#2623]
On REST controller response entities, we have custom PagedResource assemblers to convert the domain entities into REST response HATEOAS resources. We also add some custom functionalities during this conversion (for example: Stream deployment state calculation). We can refactor is further to make use of #2622

child of #914

**Comment by sabbyanandan** [comment]
Based on the discussion, we cannot use the JPA entities because they are too heavy (eg: Stream deployment's state calculation).
