### ISSUE TITLE
SCDF. Couldn't use another network port at startup config.

### ISSUE THREAD

**Issue by Rostish** [spring-cloud/spring-cloud-dataflow#2630]
**Description:**
Sorry for my today activity). I tried to find some information in documentation but couldn't.
I have found next bug. I use next bash script to start my test SCDF:

```
#!/usr/bin/env bash
export spring_datasource_url=jdbc:postgresql://192.168.21.70:5432/data_flow
export spring_datasource_username=*****
export spring_datasource_password=*****
export spring_datasource_driver_class_name=org.postgresql.Driver
java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 \
-Djavax.net.debug=ssl:handshake:verbose \
-jar /opt/databus_newfusion/scdf_multirating/spring-cloud-dataflow-server-local-1.7.2.BUILD-SNAPSHOT.jar \
--spring.cloud.dataflow.task.maximum-concurrent-tasks=300 \
--server.port=9494 \
```

As you see i change default port. All is ok, SCDF starts. But! When i try to start my big graph(i try to start main task, not specific step), i have found next error(the same errors apear for all steps):

```
"exitDescription": "org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Could not find task definition named MRF_20180924_EXEC_combine-infosys_1-web-index-download

```

A half hour ago i deleted line with:

--server.port=9494 \

And all started to work well.

**Release versions:**
1.7.2

**Custom apps:**
not connected with custom app.

**Steps to reproduce:**
1. start SCDF with some different port.
2. create graph
3. run main task(not step!)

**Comment by cppwfs** [comment]
I don't think this is a bug.  Have you set your `dataflowServerUri` on CTR launch?
By default the CTR has `dataflowServerUri` set to `http://localhost:9393`.  So if you are launching a CTR you will need to set the `dataflowServerUri` to your new location i.e. `http://localhost:9494`.

**Comment by cppwfs** [comment]
More information can be found here: https://github.com/spring-cloud-task-app-starters/composed-task-runner/blob/master/spring-cloud-starter-task-composedtaskrunner/README.adoc#options

**Comment by Rostish** [comment]
@cppwfs thank you for answer!
I have been working with SCDF about 6 month and find something new everyday)
I just wanna to say that i found only one place about port changing in DOC:
https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#configuration-security-enabling-https
"As the default port is 9393, you may choose to change the port to a more common HTTPs-typical port."
For me, unfortunately, it was not obvious that changing the port at the start of the application, I need to use other settings when running the scheme. Documentation has become my reference book, if you add a little information then it will become easier for beginners.

**Comment by cppwfs** [comment]
Actually there is a section on it here :-) :
https://docs.spring.io/spring-cloud-dataflow/docs/1.7.1.RELEASE/reference/htmlsingle/#_registering_the_composed_task_runner
