### ISSUE TITLE
Add Stream Rollback integration tests

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#2638]
_From @ilayaperumalg on December 3, 2018 12:21_

Add integration tests for Stream rollback 

_Copied from original issue: spring-cloud/spring-cloud-skipper#747_

**Comment by sabbyanandan** [comment]
Done: https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java#L449.
