### ISSUE TITLE
Add REST resource to filter Jobs by name and status

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow#2649]
**Problem description:**
As a user, there is no option to filter the jobs.

**Solution description:**
As a user, I would like to filter the jobs by TaskName and/or status.

**Comment by sylank** [comment]
Hi @oodamien,

Currently, you can filter jobs by job name:
http://localhost:9393/jobs/executions?name=job%

I had job1 and job2 and it returned with two JobExecutionResource.

Would you like to filter jobs by task name as well?
