### ISSUE TITLE
Provide example application that shows LDAP authentication in action

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2650]
Provide example application that shows LDAP authentication in action using the UAA.

child of spring-cloud/spring-cloud-dataflow#2574

**Comment by sabbyanandan** [comment]
This was addressed via https://github.com/spring-cloud/spring-cloud-dataflow-samples/commit/b981dff2cbdb52def8a77a975f5e5a8f7ae60612.
