### ISSUE TITLE
SCDF behavior on missing Skipper

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow#2655]
When Stream Features are enabled SCDF requires Skipper for managing the Stream pipelines. Consider the SCDF behavior on missing Skipper: 

* At the time SCDF starts
* If Skipper disappear/reappear at runtime 

When the Stream Feature is disabled then SCDF should operate without Skipper present.

**Comment by sabbyanandan** [comment]
Thanks for the thorough rundown of all the various scenarios.

For (1), it'd be good to classify that as wrong configuration issue and warn the user with a message like:

> The Skipper HOST/URI is not reachable. Please check the value of `SKIPPER_SERVICE_HOST` for correctness. 

For (2), if it is possible to capture Skipper's transient state consistently, we could only just highlight the fact with:

> The Skipper HOST/URI is not reachable. Please check the value of `SKIPPER_SERVICE_HOST` for correctness. 

For (3.1), we should continue to treat it as a no-error state, but it'd be good to log a WARN message about the fact with:

> The Stream feature is disabled. To enable it, you'd have to set the `spring.cloud.dataflow.features.streams-enabled` to true and make sure Skipper-server is available and configured in SCDF.

For (3.2), I don't see any action here. 

For (3.3), we have to handle the NPE. Maybe the same msg:

> The Stream feature is disabled. To enable it, you'd have to set the `spring.cloud.dataflow.features.streams-enabled` to true and make sure Skipper-server is available and configured in SCDF.

**Comment by chrisjs** [comment]
just re-tested the NPE when trying to use stream commands via shell when the stream feature is disabled, it actually works as expected -- i must have botched the property during testing.

when setting `spring.cloud.dataflow.features.streams-enabled` to `false`, the shell does not present the `stream` command in tab completion and if you try to type a stream command, your greeted with the expected "friendly" message:

```
`Command 'stream list' was found but is not currently available (type 'help' then ENTER to learn about this command)`
```

that message seems to come from the `spring-shell` project and doesn't appear customizable at first glance, maybe in later versions. 

either way, i think the resulting message is fine as-is given somebody would need to explicitly disable streams to begin with.

closing as works as expected
