### ISSUE TITLE
Overhaul security with boot 2.1.x

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#2661]
As `spring-cloud-common-security-config` is about to line up changes to support only oauth, we need to do same dance on a dataflow side.

Child of #2574

**Comment by sabbyanandan** [comment]
Shouldn't https://github.com/spring-cloud/spring-cloud-dataflow/pull/2644 already take care of this?

**Comment by sabbyanandan** [comment]
This is addressed in https://github.com/spring-cloud/spring-cloud-dataflow/commit/782eb82940417943aa655e4e19eca895541d748d.
