### ISSUE TITLE
Improve Stream, Task and Scheduler Feature handling

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow#2663]
Currently most of the `Stream`, `Task` and `Scheduler` feature configurations are spilled over the `DataFlowControllerAutoConfiguration`. 

To improve the Feature handling logic the related feature configurations should be moved under the `StreamConfiguration`, `TaskConfiguration` and `SchedulerConfiguration`.

**Comment by sabbyanandan** [comment]
Depends on #2693.

**Comment by sabbyanandan** [comment]
StreamConfiguration, TaskConfiguration and SchedulerConfiguration exist now.
