### ISSUE TITLE
Does CTR ends his work correct? insufficient memory for the Java Runtime Environment appears.

### ISSUE THREAD

**Issue by Rostish** [spring-cloud/spring-cloud-dataflow#2667]
**Description:**
Today i tried to launch my graph what contains about 30 task for 90 days.
I noticed that the server gradually runs out of memory, and then in one of the tasks next error was appeared:

> # There is insufficient memory for the Java Runtime Environment to continue.
> # Native memory allocation (mmap) failed to map 238551040 bytes for committing reserved memory.
> # An error report file with more information is saved as:
> # /tmp/MRF_20181201_EXEC_END_18537052664308845656/17457070341406264/MRF_20180908_EXEC_END_1-average-genre-statistic-calculation-online-web-0b144d13-7aee-41ba-aab1-774948f384d4/hs_err_pid6755.log

I checked memory state using "htop" command and saw next:

![image](https://user-images.githubusercontent.com/15521647/49808961-c5b4f200-fd6e-11e8-9978-55567b542b4c.png)

On screenshot you could see about 20% of messages. There are more of them. In the begining there were about 25GB of free space, after about 30 executions become 3-4GB of free space. After dataflow-server reboot  memory is back.

I checked logs of CTR, last line says:

![image](https://user-images.githubusercontent.com/15521647/49809040-fbf27180-fd6e-11e8-9b5d-7a2633b755ee.png)

There are no words about shutdown.I can not be sure that CTR will report about shutdown as Spring Boot, but with insufficient of memory it look likes smt going wrong.

**Release versions:**
Local Server - 1.7.2 Snapshot
CTR-2.0.2

**Custom apps:**
My apps end their work coorectly, dataflow server says  all jobs has completed status. In logs i can see shutdown messages.

**Steps to reproduce:**
1) Construct a big graph that contain a lot of fast tasks.
2) Launch them one by one.
3) Watch how your memory is gone.

**Additional context**
My server has 48GB of RAM. There are a docker with about 10 running container. Dataflow-server is working locally not via container. I run it from my ssh session.

**Comment by cppwfs** [comment]
If you run jps on the server, what java apps are running?

**Comment by Rostish** [comment]
@cppwfs 
Good day for you.
I need some time to reproduce this behavior. i am waiting while new batch of days will be collected to start calculation for a long period. I am going to provide the results of jps command in a few days.

**Comment by Rostish** [comment]
I ran one day several times in a row today. Jps show next:
![image](https://user-images.githubusercontent.com/15521647/50085121-32663b80-020a-11e9-8914-42f8d1422e67.png)

All jobs have status COMPLETED, all task are ended.

**Comment by Rostish** [comment]
Good day for you @sabbyanandan.
As i said i start Composed Task pipelines one by one. I start next one only then previous one is ended with status "COMPLETED". In my first post there is a CTR logs, they are all the same:
https://user-images.githubusercontent.com/15521647/49809040-fbf27180-fd6e-11e8-9b5d-7a2633b755ee.png
There are no exceptions or something else. Only a line with words "Job ... completed with follow parameters" and zero words about shoutdown.
P.S.After two days of work with CTR:
![image](https://user-images.githubusercontent.com/15521647/50206883-e50adb00-037d-11e9-801e-c65876aabaae.png)

**Comment by sabbyanandan** [comment]
That seems like a bug (in 2.0.2). We are in the middle of 2.0 M1 release of SCDF, so please bear with us, and we will get back to you. 

We will also use https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/60 to troubleshoot it.

**Comment by cppwfs** [comment]
Was able to resolve this issue with the closeContextEnabled flag.  For more information please review:  spring-cloud-task-app-starters/composed-task-runner#60
