### ISSUE TITLE
Multiple streams competing with the same queue

### ISSUE THREAD

**Issue by zhuwenjie11** [spring-cloud/spring-cloud-dataflow#2685]
hello , I want to define such a stream：
stream1 = time > :queue
stream2 = :queue > log
stream3 = :queue > log

deploy in :
stream1 in server1 to running
stream2 in server2 to running
stream3 in server3 to running

I expect stream2 and stream3 to get message through competition。(like queue)

but，But the reality is that stream2 and stream3 get the same data at the same time.(like topic)

I tried to set the parameters of these three streams at the same time when deploying as 'deploy.*.group=group1' ， parameters does not work。

Can someone help me solve this problem, thank you！！

**Comment by zhuwenjie11** [comment]
The problem is solved, I set it up ：
`“app.*.spring.cloud.stream.bindings.input.group=queue_group”`
in the three stream，when deploy.

**Comment by sabbyanandan** [comment]
Hi, @zhuwenjie11. Glad you were able to solve it. 

As far as the consumers, in the case `log-sink`, if they are configured to start with `spring.cloud.stream.bindings.input.group` property, all the consumers in the defined group will compete for messages.
