### ISSUE TITLE
Need to commit TaskExecution table entry prior to task launch

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#2692]
Spring Cloud DataFlow 1.6.x-1.7.3 
spring-boot-version:2.0.4.RELEASE
spring-cloud-task.version:2.0.0.RELEASE
mysql.version:5.1.44

The scenario:
User launches applications once every 5 minutes using SCDF's RESTful API.  Occasionally the application fails to start with the following exception: 
```
[WARN ] 2018-12-12 07:30:03.862 [main] o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'; nested exception is java.lang.IllegalArgumentException: Invalid TaskExecution, ID 91 not found
[WARN ] 2018-12-12 08:00:04.838 [main] c.l.s.i.e.tasklet.CheckTicketTasklet - FTP服务器上暂时没有待处理的tar！
```
However in the database we can see the entry.   

Issue:
While I have not been able to replicate this using my current instance of MySQL or Postgres, it looks like the task is launched prior to the TaskExecution entry in the TaskExecution table has been committed.   

More information can be found here:
https://github.com/spring-cloud/spring-cloud-task/issues/496

child of #2720

**Comment by cppwfs** [comment]
I will attempt to replicate by installing the version of mysql that the user is reporting.   And see if I can replicate.

**Comment by vincent6533** [comment]
Thank you for your help. sorry,the mysql version is 5.7.24

**Comment by cppwfs** [comment]
Followed @mminella 's advice and added a sleep(5000) following the deployer's execution of the task in the DefaultTaskService.executeTask method.   And the behavior enumerated above occurred.   So we need to restructure how transactions are managed in this method.

**Comment by vincent6533** [comment]
Thank you for your help.Which version will be fixed this problem?This problem has caused me a lot of trouble.

**Comment by steellee** [comment]
I schedule SCDF REST API every 30 minutes by quartz . SCDF  REST API :  Task Executions.
Sometimes the issues above occurred. But I don't know the rules. Can't be repeated all the time.
Before fixing the issue, do you have any other temporary solutions?

Spring Cloud Data Flow Server Local 1.6.2
Spring Cloud Task App using Boot 2.0.4 and Task 2.0.0
Quartz 2.3.0
Mysql 5.7

**Comment by cppwfs** [comment]
Spiked out a solution, but before we can proceed we will need to merge #2466.
