### ISSUE TITLE
Overhaul structure of autoconfiguration classes

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2693]
The maven module is still called, `spring-cloud-dataflow-server-local-autoconfig`, should rename. to `spring-cloud-dataflow-autoconfig`.  Also revisit the names of classes that are listing in `spring.factories` and ensure they all have the suffix `AutoConfig`.

**Comment by sabbyanandan** [comment]
Stale; closing.
