### ISSUE TITLE
Backport issues from 2.0.x to 1.7.x

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#2703]
~- [ ] https://github.com/spring-cloud/spring-cloud-dataflow/pull/2651~
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/2835
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/2763
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/2695
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/commit/44e80a6dfe85c91f57fde9857851c47726d3d6e9

**Comment by ilayaperumalg** [comment]
@cppwfs We need a separate PR for https://github.com/spring-cloud/spring-cloud-dataflow/pull/2651 on `1.1.x`

**Comment by ilayaperumalg** [comment]
#2835 is being tracked by the PR https://github.com/spring-cloud/spring-cloud-dataflow/pull/2841

**Comment by sabbyanandan** [comment]
@ilayaperumalg: https://github.com/spring-cloud/spring-cloud-dataflow/pull/2651 is moved to v1.7.5; tracking it via https://github.com/spring-cloud/spring-cloud-dataflow/issues/2864.

**Comment by ilayaperumalg** [comment]
Closing this as all scoped issued are back ported.
