### ISSUE TITLE
Update from SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM/TASK to new format

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2712]
SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_USE_SPRING_APPLICATION_JSON: false` and `SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_USE_SPRING_APPLICATION_JSON

is not relevant anymore, need to provide different config samples for different servers.

**Comment by ilayaperumalg** [comment]
The prefix `SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM` is no longer valid as we only have task deployment properties to manage at the SCDF single server and the `stream` deployment properties are managed by `Skipper` via its CF platform deployment properties  (e.g: SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[default]_DEPLOYMENT_MEMORY)
