### ISSUE TITLE
Monitoring and metrics for Tasks

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2719]
As a developer, I'd like to study the possibilities of monitoring and metrics for Tasks through the lens of Micrometer.

The goal of this spike is to investigate what more we would want to track apart from the foundation already available via Task and Job Repositories and the corresponding native UI integration in SCDF.

**Comment by nWidart** [comment]
I'd very interested in this feature.

Some things related to our use-case:

- Monitoring http calls in tasks (most important)
   - response codes
   - timing
- having 'generic' counters, gauges, etc

**Comment by sabbyanandan** [comment]
The core of the work is happening in Spring Cloud Task via https://github.com/spring-cloud/spring-cloud-task/issues/608. Since SCT is not in the combined ZH board, it cannot be directly listed under this epic, though.

Once when https://github.com/spring-cloud/spring-cloud-task/issues/608 is complete, we may have to adjust https://github.com/spring-cloud-task-app-starters/core/issues/14, to adapt the support for Micrometer in the OOTB Task app-starters. 

Ultimately, we will hook them up in the Docker-compose and the UI experiences through the associated stories in this epic.

**Comment by sabbyanandan** [comment]
All the scoped efforts towards the epic are complete, except for Prometheus integration, which is blocked due to Prometheus RSocket Proxy issues. More details [here](https://github.com/spring-cloud/spring-cloud-dataflow/issues/3296#issuecomment-509667230).
