### ISSUE TITLE
Minor issue: typo in documentation section 5.1.3 (deploying with kubectl)

### ISSUE THREAD

**Issue by gdubya** [spring-cloud/spring-cloud-dataflow#2729]
Section 5.1.3 "Deploying with kubectl" states in the console section:

> $ git clone https://github.com/spring-cloud/spring-cloud-dataflow
> $ cd spring-cloud-dataflow-server
> $ git checkout v2.0.0.M1

I think the second line should actually be:
> $ cd spring-cloud-dataflow

**Comment by sabbyanandan** [comment]
Hi, @gdubya. Thanks for catching that! When we moved K8s-server docs to a single ref. guide (in v2.0 - see [blog](https://spring.io/blog/2018/12/21/spring-cloud-data-flow-and-skipper-2-0-m1-released#single-server-that-runs-on-all-supported-platforms)), we definitely overlooked it.
