### ISSUE TITLE
REST-API returns 100s of k/v pairs as module properties

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#273]
As a user, I'm trying to use the REST-API to retrieve module specific properties; however, the returned document includes 100s of options that are not directly associated with the module, but inherited from Boot itself. 

This is related to spring-cloud/spring-cloud-dataflow#187. Though we partially fixed it with incremental tab notion in `shell`, this is still a problem for anyone who's directly using the REST-API. 

The immediate candidate impacted by this is `Flo`. The tool-tip for the `modules` listed in the palette loads very slow due to this behavior. It does eventually load though. Tracker story: [#110520316](https://www.pivotaltracker.com/n/projects/1266326/stories/110520316).

cc:/ @BoykoAlex

**Comment by sabbyanandan** [comment]
@dsyer: We'd love to hear if you've other ideas how to filter application specific property overrides. There are three areas in SCDF with UX issues.

1. Shell: when you issue `module info source:time`, you'll see 100s of module options. We'd rather want to see only `time` specific metadata options
2. Flo: palette is loaded with all OOTB applications and the associated metadata options; it takes 10-20 seconds to load the page
3. Job/Task deployment page in `admin-ui` is dynamically created based on the job/task properties as form-fields with respective defaults pre-populated. Given all these options, >95% of the form-field elements in the UI are irrelevant for the job/task application itself

cc:/ @ghillert @ericbottard

**Comment by dsyer** [comment]
The "time" module has a `TimeProperties`. I would think that might be a good source of minimal properties that are applicable. Some other modules piggy back on existing Spring Boot conventions (which is a good thing), but you could still support that by just having the module author list the "properties beans" in a config file (e.g. /META-INF/module.properties or something). If there is no explicit declaration it should be easy to scan for `@ConfigurationProperties` in the module, either at build tiume or run time.

**Comment by dsyer** [comment]
Scanning the available modules I'd say the biggest problem is still the flat namespace - how are we going to ensure that there is no clash in an environment that wants to run 2 file sources, for instance? I think it's really quite important that we wean the modules off that stage of their development somehow. Probably there's another issue open somewhere for that?

**Comment by ericbottard** [comment]
There is no clash. Modules get their own Environment

**Comment by dsyer** [comment]
Maybe in Data Flow? Not sure what you mean otherwise because (for example) there is a plain vanilla `@EnableConfigurationProperties` in all modules.

**Comment by ericbottard** [comment]
Yes, I meant DataFlow, but also (although some things may have changed and I'm not aware of the latest state) when we do composition via the ModuleLauncher. Just to clarify, we're talking about clashes when doing composition, right? Where else would there be a clash otherwise?

**Comment by dsyer** [comment]
I was thinking generally about using a module as a library. I guess if that's not a goal then we can defer the conversation (but it seems a shame since they might make quite good utility libraries), and schedule for some future time when users have to switch to using proper prefixes.

**Comment by markfisher** [comment]
I think using a module as a library is completely valid, and will be much more common once we refactor each module to be a `starter` (with the ones we distribute out-of-the-box simply pulling in that starter and providing a main class).

**Comment by dsyer** [comment]
Then I think my original moan is still valid. Modules should be designed as well-behaved libraries (including a prefix for config properties) and can get special treatment from data flow if they are ever deployed as apps. They also need some more documentation in the source code if they are going to be used as libraries (see https://github.com/spring-cloud/spring-cloud-stream-modules/issues/193).

**Comment by markpollack** [comment]
There is an issue for this in a Google doc that may not have yet gotten added into github issues.  Long story short, we need to have prefixes as the app level that are scoped to something like time.source.  This is important also for use of config server.  

We do have common application properties that we have been using across applications to keep them consistent.  Without the prefix these are easy to import, but need a different mechanism for this once we have prefixes.  

Also dataflow servers themselves do not have prefixes in some cases or are not clears.  --remoteRepositores should have spring.cloud.dataflow as a prefix and for CF/k8s we have a 'naked' cloudfoundry/kubernetes prefix, so a bunch of stuff to clean up on this front.
