### ISSUE TITLE
how to config if there's a password in Redis

### ISSUE THREAD

**Issue by liaoxu** [spring-cloud/spring-cloud-dataflow#2731]
My current kubernetes cluster do not have enough support for stateful Pod so I have to deploy a redis server in public cloud enviornment where a password is mandatory. However, the existed demo seems only set redis host and port, I wonder how to connect to a redis server with auth.

**Comment by sabbyanandan** [comment]
Hi, @liaoxu. If you have a password enabled external Redis cluster, all you'd have to do is to make sure that the SCDF-server and the [Analytics applications](http://docs.spring.io/spring-cloud-dataflow/docs/1.7.3.RELEASE/reference/htmlsingle/#arch-analytics) receive the Redis-connection creds including the password. To do that, depending on the binder in use, you'd have to add the password _(i.e., `SPRING_REDIS_PASSWORD`; for all the supported properties, see Spring Boot's [RedisProperties](https://github.com/spring-projects/spring-boot/blob/v2.1.1.RELEASE/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/RedisProperties.java))_ property alongside the host/port combination, to both the [SCDF-server](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/src/kubernetes/server/server-config-kafka.yaml#L37-L38) and [env-vars](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/src/kubernetes/server/server-config-kafka.yaml#L28) to be assigned for the Analytics applications. 

These two changes are specific to when Kafka is used as the binder; for Rabbit, you'd do a similar change to [server-config-rabbit.yaml](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/src/kubernetes/server/server-config-rabbit.yaml).

For questions like this, please use StackOverflow in the future.
