### ISSUE TITLE
Add Micrometer meter-registries in SCDF

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2740]
As a developer, I'd like to add top-3 Micrometer autoconfiguration's to SCDF, so we can use it to expose internal stats such as CPU, Memory, Disk and among other stats that we get out-of-the-box from Micrometer.

Likewise, we will have to apply a similar set of changes to Skipper, as well.

**Comment by sabbyanandan** [comment]
This would be an incremental improvement to what comes out of #2601.

**Comment by tzolov** [comment]
For the purpose of the #3973, the SCDF server need to produce a metrics with prefix `spring.cloud.dataflow.*`. 
Related to #3937 
Related to #4016
