### ISSUE TITLE
Need to commit TaskExecution table entry prior to task launch (This is the backport for 1.7)

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#2744]
writing this update so that it will work for 1.7.x

**Comment by ilayaperumalg** [comment]
This is addressed in both 2.0.x https://github.com/spring-cloud/spring-cloud-dataflow/commit/c1c0de9170d7f4f41bc725bae5ee752811144929 as well as 1.7.x https://github.com/spring-cloud/spring-cloud-dataflow/commit/d092a68dfae6b455a6c2405f95631c359611d6e8
