### ISSUE TITLE
Verify CI plan that generates 2.0 Docker image for correctness

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2758]
As a user, while attempting to use the `latest` tag of the single-server, I notice that the image-tag is at least 1 month old (see [here](https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server/tags)). Let's verify the CI plan to make sure the `BUILD-SNAPSHOT` image is generated and pushed for every upstream commit.

**Comment by chrisjs** [comment]
the docker stage of the `master` plan was disabled. its been re-enabled and both the `latest` and `2.0.0-BUILD-SNAPSHOT` images are now [being pushed](https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server/tags)
