### ISSUE TITLE
Investigate usage of Harbor

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow#2765]
Look into how Harbor can be used on k8s to resolve artifacts. PKS also has integration with Harbor. Probably not any SCDF specific changes, but valid use case that was attempted to be used with a SCDF deployment. 

Outcome may just be documentation

**Comment by sabbyanandan** [comment]
Harbor is [one of the container registries](https://dataflow.spring.io/docs/feature-guides/general/application-metadata/#using-metadata-container-image-labels) that we experiemented with to resolve application images.
