### ISSUE TITLE
Refactor Constructor in DefaultTaskExecutionService

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2768]
Refactor the constructor so that `ApplicationConfigurationMetadataResolver`, `String dataflowServerUri` and `CommonApplicationProperties commonApplicationProperties` can be moved into a class like the current `AppDeploymentRequestCreator` but for Tasks.

Since curing AppDeploymentRequest creation, there needs to be a write to the database, we can create a `TaskAppDeploymentRequestService` and use @Transactional annotation support.

This will also make that part of the code more easily testable.

**Comment by sabbyanandan** [comment]
We may have addressed it, but @markpollack will review it to be sure.
