### ISSUE TITLE
Task launch using specific platform name

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#2770]
When launching the task, the `task launch` command's `platform-name` needs to be used. Currently, the TaskTemplate is not updated with this.

Child of #2720

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-dataflow/commit/7ac9823c23c5cf1fe98e3f9ab896f9930acf7e50.
