### ISSUE TITLE
Add Micrometer+Prometheus setup for Kubernetes deployment

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2776]
Depends on #2900.

**Comment by chrisjs** [comment]
for the time being i've pushed the configs created for grafana & prometheus to: https://github.com/chrisjs/spring-cloud-dataflow/tree/gh_2776

currently these configs are using a grafana image out of @tzolov 's docker hub account. this image is based off the existing docker-compose experience setup and includes the stream & applications dashboard. before these configs can be merged, we need to decide if rolling a docker image that includes everything is what we want and how it will be published / maintained

this image is being used in `src/kubernetes/grafana/grafana-deployment.yaml` (`tzolov/spring-cloud-dataflow-grafana-prometheus:v1`)

the setup can be tested from this branch and everything should work end-to-end out of the box. some notes on doing so:

* apply:

```
kubectl create -f prometheus/
kubectl create -f grafana/
```

* deploy dataflow & test app:

```
app import --uri http://bit.ly/Einstein-BUILD-SNAPSHOT-stream-applications-rabbit-docker

stream create --name ticktock --definition "time | log"
stream deploy --name ticktock --properties "deployer.log.kubernetes.podAnnotations=prometheus.io/path:/actuator/prometheus,prometheus.io/port:8080,prometheus.io/scrape:true"
```

* get & visit grafana URL:

```
$ minikube service --url grafana
```

* login:

```
username: admin
password: password
```

* view stream / application dashboards

* cleanup if desired:

```
kubectl delete all,cm,svc,clusterrole,clusterrolebinding,sa -l app=prometheus
kubectl delete all,cm,svc,secrets -l app=grafana
```

**Comment by sabbyanandan** [comment]
Depends on #2900.
