### ISSUE TITLE
Question: Can SCDF 2.0.0-SNAPSHOT run apps built on Java 11?

### ISSUE THREAD

**Issue by bleurubin** [spring-cloud/spring-cloud-dataflow#2788]
**Problem description:**
My application uses Java 11 and our stream apps are built using Java 11.  I see class compatibility errors that point to Java compiler version issues deploying the stream apps on SCDF 2.0.0-SNAPSHOT. 

**Solution description:**
My devops team will be using Kubernetes for deployment, it would be nice if there was a Java 11 compiled artifact in the official maven repositories we could use.

**Description of alternatives:**
I am able to successfully run Java 11 compiled stream apps if I download the SCDF source and compile it with Java 11.  We can upload that artifact to our local maven repository and use it for deployment.  

*Edit- I just realized this could just be an artifact of running the SCDF server on localhost since it probably runs the streams in the same jvm.  Does the java version of the SCDF server matter in the cloud relative to the java version of the stream apps?

**Comment by sabbyanandan** [comment]
Hi, @bleurubin. As you stated, Apps and SCDF are separate entities. They run on independent JVMs, so there's no correlation or dependency in any capacity between both. They can be in mixed versions, too. All that said, SCDF v2.0 builds upon the latest Boot/Cloud foundation (v2.1.x), so technically SCDF is Java 11 compatible as well.
