### ISSUE TITLE
If adding -DremoteRepositories modules are not auto discovered

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#279]
Running the local-admin.  Only the modules in the spring-cloud-stream-modules are populated even though there are 'simple-source' and 'simple-sink' modules in my custom remote repo that was published before starting the admin.

**Comment by trisberg** [comment]
Don't you have to register them?

**Comment by ericbottard** [comment]
I'd vote to label this as 'invalid' indeed. Modules need to be registered, as Thomas said.

**Comment by sabbyanandan** [comment]
You need to register them, indeed. :smile: Closing this.
