### ISSUE TITLE
Streams search results are incomplete

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2793]
_From @oodamien on January 25, 2019 15:18_

The stream search is not returning the expected result.
Create a stream `foo` (file | log)

**Tests search:**
fo: no result
foo: 1 result
oo: no result

**The search should be return:**
fo: 1 result
foo: 1 result
oo: 1 result

**Note: Other tests**
fo%: 1 result
foo: 1 result
%oo: 1 result

_Copied from original issue: spring-cloud/spring-cloud-dataflow-ui#1040_

**Comment by sylank** [comment]
We could use:
`Page<StreamDefinition> findByNameContains(String name, Pageable pageable);`
Instead of:
`Page<StreamDefinition> findByNameLike(String name, Pageable pageable);`

It will resolve the issue. I will write some test and send a PR if it is OK. 

https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#_supported_query_keywords

**Comment by sabbyanandan** [comment]
@sylank: Thank you for the suggestion and the help in solving it.

Here are some experiments in Shell and UI.

Streams:
```
dataflow:>stream list
╔═════════╤══════════════╤═══════════════════════════════════════════════╗
║ Stream  │    Stream    │                    Status                     ║
║  Name   │  Definition  │                                               ║
╠═════════╪══════════════╪═══════════════════════════════════════════════╣
║foo      │file | log    │The app or group is known to the system, but is║
║         │              │not currently deployed                         ║
║foz      │time | log    │The app or group is known to the system, but is║
║         │              │not currently deployed                         ║
║faoz     │time | log    │The app or group is known to the system, but is║
║         │              │not currently deployed                         ║
║fooz     │time | log    │The app or group is known to the system, but is║
║         │              │not currently deployed                         ║
╚═════════╧══════════════╧═══════════════════════════════════════════════╝
```

Shell: (type `f` and hit tab button)
```
dataflow:>stream info --name f
faoz   foo    fooz   foz
```
At least Shell was able to retrieve all the streams that start with the letter `f`; however, there's no such concept as searching by other characters from the shell, but the UI does.

UI: (type `f` and hit enter button)
![image](https://user-images.githubusercontent.com/1562654/52064859-494abe00-252a-11e9-8bb9-a629c7ef208c.png)

When I search for `f` from the UI, I get nothing. It is likely that the Shell is adding `%` for all the incremental search requests. As an alternative solution, we could do the same from the UI as well. Otherwise, we could attempt to fix it with what Spring Data has to offer. 

@jvalkeal / @ilayaperumalg: Do you have any opinions re: `findByNameContains` vs. `findByNameLike` switch?

**Comment by ilayaperumalg** [comment]
@sylank @sabbyanandan We seem to [use](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamService.java#L519) `findByNameLike` already when searching for the `stream`.

**Comment by sylank** [comment]
@linzhaoming I have seen it already but we could use `Contains` keyword instead of `Like`. I rather use `Contains` because we do not use wildcards at this moment.
