### ISSUE TITLE
add spring-cloud-dataflow-shell to spring-cloud-dataflow-server Docker image

### ISSUE THREAD

**Issue by dsw9742** [spring-cloud/spring-cloud-dataflow#2795]
As a matter of convenience, I'd like to be able to access the spring-cloud-dataflow-shell from the same Docker container running spring-cloud-dataflow-server.

The docs reference shell usage quite a bit as well so this could also aid those learning the platform.

Proposed solution is to add a single new RUN directive to the Dockerfile generated by the Fabric Maven plugin to `wget -q https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-dataflow-shell/${project.version}/spring-cloud-dataflow-shell-${project.version}.jar -O /shell.jar`, so that a user can run `docker exec -it dataflow-server java -jar shell.jar` and be dropped right into the spring-cloud-dataflow-shell.

**Comment by markpollack** [comment]
interesting.  Seems reasonable to me.  @chrisjs thoughts?

**Comment by chrisjs** [comment]
@markpollack seems useful, but cpl things to resolve in review comments
