### ISSUE TITLE
Add `@EnableDataflowAdminServer` and `@EnableDataflowShell`

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-dataflow#280]
imagine going to the [Spring Initializr](http://start.spring.io) and selecting _Local Admin_ from the _Data Flow_ column, then clicking _Generate_. From there, you can add `@EnableDataflowAdminServer` on top of `@SpringBootApplication`, start it up, and get the effect of runnning the admin jar itself. Plus, if someone wants to customize the admin server's behavior (perhaps by plugging in substitutes for one of the many `@ConditionalOnMissingBean`auto-configured beans) then they could do that, or change properties in `application.properties`, as well.

this experience is in keeping w/ how lots of other services are deployed with Boot + Cloud: the oauth server, eureka server, config server, CraSH shell, hystrix dashboard, etc.

**Comment by sabbyanandan** [comment]
Though in a different context, we were recently discussing Spring Intializr experience where you'd be able to select the components (_ex: binder, libraries, hadoop distro_) to assemble the `admin` in variety of ways, which will by default also include `shell` in it as well. We have #211 to specifically tackle this as a spike in the next iteration.

**Comment by joshlong** [comment]
i'm not entirely sure i understand how, currently, the decision on where modules are resolved from is made right now. I imagine that there is the _admin_ and then some bean, in play somewhere, that knows to look in CF or in a Maven repo or.. whatever.. and another bean that knows how to start a module (either locally or using the CF API, or whatever) given a set of coordinates. In other Spring Boot projects, this sort of differentiation at runtime is handled through dynamic auto-configurations based on availability of types / properties. 

It'd be cool if I could choose "Admin" and then specify whatever Maven deps or select whatever checkboxes would be needed to 'activate' the right strategy: if the CF client is on the CLASSPATH and the right spring.cloudfoundry.* properties are set, for example, or - absent all that but assuming a remoteRepository URL is specified  - it defaults to local deployment. This way, when i deploy to CF, i just store the right properties in the application-cloud.properties file which gets read when the `cloud` profile is activated. If those properties aren't there, it does the right thing and jus runs locally.

I'd _LOVE_ to see the ability to resolve modules statically, at build time, without having to stand up a HTTP endpoint in front of my Maven repository. 

i'm not sure how including the shell would work, though? That is when I select Admin, i'm planning on adding one annotation to a `@SpringBootApplication` class and then `cf push` 'ing it. The shell can't run on CF (and wouldn't do me a whole lot of good even if it could) (I suspect I'm not understanding something here..)

**Comment by sabbyanandan** [comment]
There have been a lot of discussion on this topic and the plans have been dropped. SCDF being a full-blown "server" similar to Zipkin and others, it doesn't fit the starter model like rest of the ecosystem hosted in Spring Initializr. 

To get started with SCDF, one can use [docker-compose](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-local/docker-compose.yml), [pcf-tile](https://network.pivotal.io/products/p-dataflow), or the [helm-chart](https://hub.kubeapps.com/charts/incubator/spring-cloud-data-flow) in the respective platforms.
