### ISSUE TITLE
Investigate why we don't pass task deployment properties when restarting the job execution

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#2807]
The related discussion is [here](https://github.com/spring-cloud/spring-cloud-dataflow/pull/2803/files#r252081277)

Depends on #2733

**Comment by sabbyanandan** [comment]
A community report on the same problem posted [here](https://stackoverflow.com/questions/54521651/composed-task-arguments-are-not-passed-after-job-restart).

**Comment by sabbyanandan** [comment]
This will be addressed in https://github.com/spring-cloud/spring-cloud-dataflow/issues/3121 in the context of https://github.com/spring-cloud/spring-cloud-dataflow/issues/3407.
