### ISSUE TITLE
create "starter" dependencies 

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-dataflow#281]
it should be possible to choose `spring-cloud-dataflow-starter-admin-local` from the [the Spring Initializr](http://start.spring.io) to have both the core Admin engine and the auto-configuration (perhaps a separate dependency with its own auto-config) for local deployment. Similarly, there should be starters for CF, Mesos, k8, etc. 

Each of these starter dependencies should only contain the requisite dependencies to activate functionality paths, but no code in of itself (e.g: `spring-boot-starter-web`). These would ultimately land as checkboxes on the [Spring Initializr](http://start.spring.io)

Also, perhaps the existing _admin-starter_, which is really just the admin functionality and prebaked main method could be refactored to be an `@Enable*` annotation plus associated auto-configuration and the module name itself could be renamed to `spring-cloud-dataflow-admin` or something, as _starter_ in the Boot + Cloud worlds imply something different than a prebaked static void main entry point.

**Comment by sabbyanandan** [comment]
There have been a lot of discussion on this topic and the plans have been dropped. SCDF being a full-blown "server" similar to Zipkin and others, it doesn't fit the starter model like rest of the ecosystem hosted in Spring Initializr. 

To get started with SCDF, one can use [docker-compose](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-local/docker-compose.yml), [pcf-tile](https://network.pivotal.io/products/p-dataflow), or the [helm-chart](https://hub.kubeapps.com/charts/incubator/spring-cloud-data-flow) in the respective platforms.
