### ISSUE TITLE
Remove use of world 'local' in poms and classes

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2810]
`	<artifactId>spring-cloud-dataflow-server-local-autoconfig</artifactId>` should change to `single-autoconfig`

and classes prefixed with `local` should be changed to `single`.

**Comment by sabbyanandan** [comment]
Mostly only renaming and moving to different packages.

**Comment by sabbyanandan** [comment]
Also, remove `spring-cloud-dataflow-classic-docs`.
