### ISSUE TITLE
Add support to launch tasks to multiple platforms

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#2813]
Currently, the same task cannot be launched on multiple platforms. We can add support for this as it can help use cases like launching a task in `staging` platform and then move on to launch on `production` platform.

**Comment by sabbyanandan** [comment]
This is also applicable to CTR (and its child tasks), and the Scheduled Tasks, as well.

**Comment by sabbyanandan** [comment]
We have this supported for plain task launches already.
