### ISSUE TITLE
Ensure CI plan correctness

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow#2814]
For each CI plan, ensure for example:

* correct versions are being used (project, apps, etc)
* projects that should be kicked off after build (ie: servers after deployers)
* docker stages are not disabled

**Comment by sabbyanandan** [comment]
Perhaps,
@ilayaperumalg could check PAS plans
@chrisjs could help with K8s plans
@jvalkeal could review the Local plans

**Comment by ilayaperumalg** [comment]
Reviewed all the acceptance plans except CF master (as we need to plan things for maria DB version compatible environment for some of them).

**Comment by chrisjs** [comment]
* ensured / updated:
[x] deployers kick off appropriate server deps for 1.7 & master, only the 1.11 build plan for master publishes mvn artifacts
[x] dataflow 1.7 kicks off rebuilds of k8s server 1.7
[x] AT's for 1.7 & master point to correct dep versions

i think everything looks good for the k8s related builds

**Comment by jvalkeal** [comment]
Went through local tests, found wrong versions in one plan.

**Comment by chrisjs** [comment]
seems like we all have taken a pass, so closing
