### ISSUE TITLE
Create Flexible StringToInstant converter for Controllers

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2815]
It would be nice to have a flexible converter for Java Time's Instant class, to be used as search parameters.

Currently, we define temporal search parameters as:

```java
@RequestParam(required = false) @DateTimeFormat(iso = ISO.DATE_TIME) ZonedDateTime fromDate
```

Interestingly, Spring does not seem to support `Instant` in conjunction with `@DateTimeFormat`: https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/format/datetime/standard/Jsr310DateTimeFormatAnnotationFormatterFactory.java#L51)

While this allows for a maximum of flexibility, it also means that users have to provide full ISO date-times as request parameters, e.g `2019-01-31T09:30:51.807+01:00`.

In many situation, this level of detail may not be needed and we should also allow simpler parameters such as `2019-01-31` (And also specify the corresponding offset rule, such as which default off-set shall be used for a date `2019-01-31`, client-side or UTC)

**Comment by ilayaperumalg** [comment]
This was addressed via #2869
