### ISSUE TITLE
Graph picture and full scheme definition are absent inside root task summary.

### ISSUE THREAD

**Issue by Rostish** [spring-cloud/spring-cloud-dataflow#2833]
**Description:**
Today i updated all my projects which use SCDF to ver 1.7.3 RELEASE and find strange problem in WEB UI part. Previously i could see my full graph and scheme definition if i click to root task. 

But now i am not able to do it.
Example:
job field in web-u(you could see it contains 28 tasks inside job):
inside job summary:
![image](https://user-images.githubusercontent.com/15521647/52139692-e6f4d900-2661-11e9-8be8-9f54d3c512e7.png)
![image](https://user-images.githubusercontent.com/15521647/52139734-ff64f380-2661-11e9-838e-807e982320d8.png)
This task summary:
![image](https://user-images.githubusercontent.com/15521647/52139404-1f47e780-2661-11e9-9553-cdcec74fd262.png)
Graph picture:
![image](https://user-images.githubusercontent.com/15521647/52139421-2cfd6d00-2661-11e9-8cc0-c387d3f271db.png)

**Release versions:**
1.7.3.RELEASE

**Custom apps:**
My own baseoperation for graph.

**Steps to reproduce:**
Create scheme definition with 10-20 task. Lauch it. Check Root task, there are will be only one task and no full graph image.

**Comment by sabbyanandan** [comment]
Hi, @Rostish! Sorry that you ran into this. We recently identified it and it has been fixed via: https://github.com/spring-cloud/spring-cloud-dataflow/issues/2763 -- we plan to release 1.7.4 with the fix next week.

**Comment by Rostish** [comment]
@sabbyanandan 
Execuse me too. I tried to find issue connected with this problem, but coudn't. Thank you for fast answer.

**Comment by sabbyanandan** [comment]
@Rostish: Quick update. The bug-fix has been [cherry-picked to 1.7.x branch](https://github.com/spring-cloud/spring-cloud-dataflow/commit/462a2d439b68cab654e34efce9eda0299fb1658b), so the [1.7.4.BUILD-SNAPSHOT](http://docs.spring.io/spring-cloud-dataflow/docs/1.7.4.BUILD-SNAPSHOT/reference/htmlsingle/#getting-started-deploying-spring-cloud-dataflow) should have the fix and is available if you want to give that go.

**Comment by sabbyanandan** [comment]
Please leave a comment here if you run into any issues.

**Comment by sabbyanandan** [comment]
Addressed via https://github.com/spring-cloud/spring-cloud-dataflow/commit/462a2d439b68cab654e34efce9eda0299fb1658b.
