### ISSUE TITLE
Use json path matcher in controller test classes

### ISSUE THREAD

**Issue by sylank** [spring-cloud/spring-cloud-dataflow#2836]
**Problem description:**
It would be nice if we could use json path matcher in `AppRegistryControllerTests`, `RuntimeAppsControllerTests`, ` RuntimeStreamsControllerTests`, `StreamControllerTests`, `TaskPlatformControllerTests`. Check `AuditRecordControllerTests` for more information.

**Solution description:**
Check the controller test classes and the others where we use `mockMvc.perform(...)` and change the assertion to `jsonPath` assertion if it is possible. I think the test code could be cleaner. For more information and example implementation check `AuditRecordControllerTests` class.

- [x] AppRegistryControllerTests
- [x] RuntimeAppsControllerTests
- [x] RuntimeStreamsControllerTests
- [x] StreamControllerTests
- [x] TaskPlatformControllerTests
- [x] StreamDefinitionControllerTests

**Comment by sabbyanandan** [comment]
Hi, @sylank. Please feel free to take a stab at it; we can collaborate on the PR.
