### ISSUE TITLE
Remove references to Redis/Analytics in docs

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2838]
There still are references, in particular in getting started guides.

**Comment by sabbyanandan** [comment]
The remaining "Redis" hits are K8s-specific, mostly related to `kubectl` output. @chrisjs will address them in https://github.com/spring-cloud/spring-cloud-dataflow/issues/2830.

As for "Analytics", there are 2 hits in total. 1 is in reference to "Predictive Analytics", it'd be better to retain that. And the 2nd hit is a [RESTDocs sample output](http://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#api-guide-resources-server-meta-request-structure) - most likely a unit-test code change.
