### ISSUE TITLE
Add description to docker image on dockerhub

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2842]
The main dataflow server https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server is where 2.x work is happening.  The other server (cf/k8s) pages should be updated to indicate they are part of the previous release generation.

Page should simply link to the project page.

**Comment by sobychacko** [comment]
Updated the docker hub pages with the notice and the links to project pages. 

https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server
https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server-kubernetes
https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server-local

@markpollack Can you take a look?
/cc @sabbyanandan

**Comment by sabbyanandan** [comment]
Thanks, @sobychacko.
