### ISSUE TITLE
Audit records: parsing fromDate/toDate issue

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow#2869]
**Description:**
Filtering audits by date is not working.

**Release versions:**
SCDF: master
Skipper: master

**Steps to reproduce:**
1. Start Skipper / SCDF
2. Import the latest apps starters (http://bit.ly/Einstein-BUILD-SNAPSHOT-stream-applications-kafka-maven) and create audit records.

**Tests:**
http://localhost:4200/audit-records?page=0&size=30&sort=createdOn,DESC&fromDate=2019-02-03T00:00:00.000+01:00&toDate=2019-02-05T23:59:59.999+01:00

**Error:**
```[{"logref":"MethodArgumentTypeMismatchException","message":"Failed to convert value of type 'java.lang.String' to required type 'java.time.ZonedDateTime'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.web.bind.annotation.RequestParam @org.springframework.format.annotation.DateTimeFormat java.time.ZonedDateTime] for value '2019-02-03T00:00:00.000 01:00'; nested exception is java.lang.IllegalArgumentException: Parse attempt failed for value [2019-02-03T00:00:00.000 01:00]"}]```

**Note:**
http://localhost:4200/audit-records?page=0&size=30&sort=createdOn,DESC&fromDate=2019-02-03T00:00:00.000-01:00&toDate=2019-02-05T23:59:59.999-01:00 works.

**Comment by sylank** [comment]
I think this issue is related to #2815

**Comment by sabbyanandan** [comment]
This appears to have been addressed via https://github.com/spring-cloud/spring-cloud-dataflow/issues/2815, indeed.
