### ISSUE TITLE
Streams with commas in definition not displaying on dashboard

### ISSUE THREAD

**Issue by djgeary** [spring-cloud/spring-cloud-dataflow#2875]
This started happening after upgrading from 1.5.0 to 1.7.3.
The streams still work and deploy / undeploy from the shell. 

However if the definition contains a comma that is not already in quotes it will not display in the dashboard and hence cannot be managed or monitored there.

An example is
```
rabbit --queues=logs --outputType=text/plain | filter --expression=!#jsonPath(payload,'$.type').equals('test') | mongodb --mongodb.database=logs --collection=responses
```
If we make sure the part with the comma is within quotes eg
```
stream create --name newlogs --definition "rabbit --queues=logs --outputType=text/plain | filter --expression=!#jsonPath(payload,'$.type').equals('test') | mongodb --mongodb.database=logs --collection=responses"
```
it works OK.

This seems to be a dashboard bug - in the web console we get 
`
TokenizationError: Unexpected character
ERROR TypeError: "t.lines[0].nodes is undefined"
`
This means its possible to set up and deploy working streams from shell and not realise there is an issue until you go to the dashboard to monitor the metrics.

See discussion on gitter https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5c59640b975714406b99c920

**Comment by sabbyanandan** [comment]
@djgeary: Thanks for reporting it. I will move it to the UI project since we will have to fix it at that level.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#1071
