### ISSUE TITLE
Tasks not launching after upgrade to 1.7.3

### ISSUE THREAD

**Issue by djgeary** [spring-cloud/spring-cloud-dataflow#2876]
After upgrading from 1.5.0 to 1.7.3 we were initially were unable to launch tasks (with the error message 'The maximum concurrent task executions [20] is at its limit.') 

After investigation we found this was due to the new concurrent task executions limit functionality. SCDF calculates the number of running tasks to be the number of tasks in the execution table with a null end_time. For various reasons (eg tasks that died or were killed by Kubernetes) we had a few hundred entries in here with null end_times. We've worked around this for now by setting spring.cloud.dataflow.task.maximum-concurrent-tasks to a very high value effectively disabling this feature.

I'm not sure using end_time=null is a reliable way to determine the number of concurrent tasks? Maybe there is some way to label the tasks and query kubernetes directly to see how many are running?

See gitter discussion here https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5c59640b975714406b99c920

This may be related to https://github.com/spring-cloud/spring-cloud-dataflow/issues/2600

**Comment by sabbyanandan** [comment]
We have had a few hits on this subject, and this is yet another validation. There's https://github.com/spring-cloud/spring-cloud-dataflow/issues/2855 to look into other reliable solutions specifically. 

I will close this as a duplicate.
