### ISSUE TITLE
Study the YAML file approach for deployment properties

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#288]
As a developer, I'd like to study the YAML file approach to resolve deployment properties, so I don't have to send the properties as inline params, which is very verbose and error prone.

Refer to #224 and #271 for more details.

**Comment by sabbyanandan** [comment]
`--propertiesFile` as an option is already supported while deploying a stream, so this is not relevant anymore.

**Comment by markfisher** [comment]
This issue was to explore adding *YAML* support, in addition to the current `.properties` file support. Reopening.
