### ISSUE TITLE
Run Applications as Non Root

### ISSUE THREAD

**Issue by allanmoso** [spring-cloud/spring-cloud-dataflow#2881]
**Problem description:**
We are trying to get Spring Cloud Data Flow to run in Kubernetes. Our organization's Kubernetes cluster has a `PodSecurityPolicy` configured such that the pod containers must run as non-root users. However, I have not found a way to configure the stream applications to run as non-root user.

**Solution description:**
It would be great to have a way to set the Kubernetes pod's `spec.securityContext.runAsUser` configuration. Or even the container level securiryContext (`spec.containers[].securityContext.runAsUser`).  The `spec.securityContext.fsGroup` configuration should probably be configurable as well.

**Description of alternatives:**
It's probably a good idea to have applications deployed to run as non-root as the default behavior for the Spring Cloud Dataflow server/skipper.

**Additional context:**
Running as non-root is a security best practice for Kubernetes/containers. I was able to configure the Kubernetes definition files (for server, skipper, mysql, kafka) to run the different SCDF components as non-root in Kubernetes.  I had to switch Kafka to a different image from what is currently defined in your repo. The Kafka image that is currently there now (wurstmeister/kafka:1.1.0) creates files as root during the image creation but it then needs to modify it after startup. 
I wonder if running as non-root is something that is worth pursuing as a default configuration for your Kubernetes implementation.

**Comment by chrisjs** [comment]
given you have made changes to support this locally, might you consider creating a PR ?

**Comment by allanmoso** [comment]
@chrisjs  Sorry, I'm afraid my "Additional Context" might have been misleading.

I have made some changes to the kubernetes definition files (https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/src/kubernetes) to make them run locally (with Kafka) with non-root user. However, those are just the components of SCDF itself.  I can certainly create a pull request for this if you would like. 

I still have the issue where I could not make the stream applications to run as non-root.

**Comment by chrisjs** [comment]
@allanmoso sure, making a PR for what you have is fine - i can take a look as well as the deployed apps mentioned and go from there

**Comment by allanmoso** [comment]
@chrisjs  I have made a PR for running as non-root but only with RabbitMQ: https://github.com/spring-cloud/spring-cloud-dataflow/pull/2911

The Kafka manifest that I had is generated off the helm charts for Kafka and it is drastically different from what is currently in master (e.g., it is using StatefulSets). I was not sure if you want that.

**Comment by chrisjs** [comment]
its been decided not to merge the config file changes in as we can't apply these changes everywhere, specifically to dependencies that we use but don't have control over or any custom stream apps people may write.

rather this will be called out in documentation, with an issue created here: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3123

in regards to passing securityContext info down to deployed apps, I've opened an issue in the k8s deployer to track that here: https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/291
