### ISSUE TITLE
Document Micrometer-based analytics support using Twitterstream as a sample

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2882]
As a developer, I'd like to document the newly improved micrometer-based Analytics support with an example.

**Acceptance:**
- Include before and after experience of the current Twitter Analytics [sample](https://docs.spring.io/spring-cloud-dataflow-samples/docs/current/reference/htmlsingle/#_building_and_running_the_demo_13).
- Discuss the counter, field-value-counter, and aggregate-counter responsibilities in the context of the new "analytics" [applications](https://github.com/spring-cloud-stream-app-starters/analytics).
- Discuss the behavior changes.
- Highlight the improvements
  - same application can now compute multiple metrics (compared to: an app for "each metric")
  - analytics computation can be both processor and sink (compared to: only as sink in 1.x)
  - highlight grafana plugins, customizations, and ad-hoc metrics computation possibilities
- Update to Einstein.RELEASE coordinates in the ref. guide wherever applicable.

Depends on spring-cloud-stream-app-starters/app-starters-release#179

**Comment by tzolov** [comment]
Related PR is here: https://github.com/spring-cloud/spring-cloud-dataflow-samples/pull/85
