### ISSUE TITLE
Parser/Graph Updates for CTR and Task

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#2885]
Issue 1: Parser needs to support transitions to splits in Composed Tasks
https://github.com/spring-cloud/spring-cloud-dataflow/blob/01056363b0c7fc55ca977867ed7038d4516aa184/spring-cloud-dataflow-core/src/test/java/org/springframework/cloud/dataflow/core/dsl/TaskParserTests.java#L681

Issue 2: TaskNode needs to support inAppMode
 https://github.com/spring-cloud/spring-cloud-dataflow/blob/503cc905109b8d636b72c9c77ba75e272bf21fb7/spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/TaskNode.java#L60

To support what can be handled on this node.

Issue 3: TaskValidatorVisitor needs to valid secondary sequences
https://github.com/spring-cloud/spring-cloud-dataflow/blob/503cc905109b8d636b72c9c77ba75e272bf21fb7/spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/TaskValidatorVisitor.java#L162

Issue 4: Need ability to throw exception if in infinite loop. 
or is this even a case.
https://github.com/spring-cloud/spring-cloud-dataflow/blob/503cc905109b8d636b72c9c77ba75e272bf21fb7/spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/GraphGeneratorVisitor.java#L145

**Comment by sabbyanandan** [comment]
Cycles were tested out via: https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/issues/323
