### ISSUE TITLE
Missing Actuator endpoints in SCDF v2.0 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2888]
As a user, while attempting to gain access to `/configprops` and `/env`, I get a 404. In Boot v2.1, only `/info` and `/health` endpoints are enabled by default, and others aren't. These endpoints are particularly useful when troubleshooting for global configuration overrides at runtime.

Per @markpollack, adding `--management.endpoints.web.exposure.include=*` to the server can enable them, so it'd be good to set it as a default in Local, CF and K8s-servers.

**Comment by sabbyanandan** [comment]
Update: With `management.endpoints.web.exposure.include=*`, I can gain access to http://localhost:9393/management/env and http://localhost:9393/management/configprops

**Comment by jvalkeal** [comment]
While it's useful to have more endpoints enabled we need to think what we want/can enable by default. Boot2 started to secure more and then let users to conditionally enable more. To continue that story, I'd prefer to keep `configprops` and `env` disabled and if user needs those, let them enable needed endpoints. Anyway those are the ones potentially exposing something what should not get exposed?

**Comment by sabbyanandan** [comment]
It is decided to leave it as an option for end-users as opposed to enabling it by default.

**Comment by markpollack** [comment]
I agree that in this case we should not differ from boot defaults.  It would be good to document it though in scdf docs even though it is well documented in boot.
