### ISSUE TITLE
Basic Authentication Exceptions do not return a VndError

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2898]
At present basic authentication error do not return `VndErrors` and are handled somewhat inelegantly in the `VndErrorResponseErrorHandler`. 

see also: https://github.com/spring-cloud/spring-cloud-dataflow/issues/781

**Comment by jvalkeal** [comment]
Vnd stuff is deprecated and we're moving away from it so this is now invalid.
