### ISSUE TITLE
REST Documentation: Response structure description

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow#2899]
**Problem description:**
The REST documentation display only the JSON response without the description of the structure

**Solution description:**
Like the Request Parameters are described, the response should be also describe in a table.

**Comment by sabbyanandan** [comment]
We have both the request and response captured in the table format. See: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources
