### ISSUE TITLE
v2.0 Docker image in the registry is old

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2902]
As a user, while trying to use SCDF on K8s, I see that the new commits are not picked up in the `2.0.0.BUILD-SNAPSHOT` image. It turns out the image is [8 days old](https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server/tags).

**Comment by chrisjs** [comment]
i noticed it was disabled this morning and clicked re-enable

**Comment by sabbyanandan** [comment]
New images are available [now](https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server/tags). Thanks, @chrisjs.
