### ISSUE TITLE
Migration 2.x: Document how we handle the deployed streams/tasks from previous classic mode SCDF versions

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#2905]

**Comment by sabbyanandan** [comment]
@jvalkeal: If there's any specific guidance, it would be good to add a new section in the [Behavior-Changes-from-SCDF-1.x-to-2.0](https://github.com/spring-cloud/spring-cloud-dataflow/wiki/Behavior-Changes-from-SCDF-1.x-to-2.0) wiki.
