### ISSUE TITLE
Add logging for downloading of task jars/docker images

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2909]
I am deploying some tasks and it appears as if the dataflow server is hanging, but it is really downloading tasks.

i think we have the same issue in skipper - prob a deployer library issues.

**Comment by cppwfs** [comment]
It is in the deployer.  And we will need to add a story for each deployer for example in Local you will need to add the logging here: https://github.com/spring-cloud/spring-cloud-deployer-local/blob/master/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/JavaCommandBuilder.java#L103 for maven jar resolution.   And You will probably want to add a message for docker urls here: https://github.com/spring-cloud/spring-cloud-deployer-local/blob/master/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/DockerCommandBuilder.java#L86

**Comment by dturanski** [comment]
The 2.0.x backport is just a matter of upgrading all the deployer dependences to `2.0.2`

**Comment by sabbyanandan** [comment]
Cf/K8s is done. We still have a PR for Local via https://github.com/spring-cloud/spring-cloud-deployer-local/pull/157.

**Comment by sabbyanandan** [comment]
The Local PR is merged.
