### ISSUE TITLE
remove some hystrix config

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2910]
on startup there is a warning
```
Endpoint ID 'hystrix.stream' contains invalid characters, please migrate to a valid format.
```

We should not be including anything relating to hystrix.... investigate.

**Comment by ilayaperumalg** [comment]
This comes from the dependency `spring-cloud-starter-netflix-hystrix` which acts as an implementation for Circuit Breaker annotation we have in the Data Flow controller auto configuration [here](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java#L140).

Does this mean we no longer need `circuit breaker` configuration from the SCDF server? @markpollack @sabbyanandan
