### ISSUE TITLE
Rename CF task launcher 

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#2918]
With the changes from https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/commit/ebeb18abaf65bcf846c50d9f8abe71d3962f7a49 , the CF deployer name needs to be changed.

**Comment by sabbyanandan** [comment]
Somehow this was missed in 2.0 GA; hopefully, we can clean this up in 2.0.1.

**Comment by sabbyanandan** [comment]
We need to also change Scheduler to adapt to it.

**Comment by sabbyanandan** [comment]
Closing this in favor of https://github.com/spring-cloud/spring-cloud-dataflow/issues/3416.
