### ISSUE TITLE
Update "DEPLOYMENT_PROPS" column to a maximum acceptable limit for MySQL

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2922]
As a user, I'm attempting to deploy a stream with MySQL as the database, and I notice the following database error.

```
PreparedStatementCallback; SQL [insert into STREAM_DEPLOYMENTS (STREAM_NAME, DEPLOYMENT_PROPS) values (?, ?)]; (conn=101) Data too long for column 'DEPLOYMENT_PROPS' at row 1 ...
```

See more details at: spring-cloud/spring-cloud-dataflow-server-kubernetes#379

**Comment by jvalkeal** [comment]
We don't use this table in 2.x anymore so it'd be just a 1.7.x fix.

**Comment by sabbyanandan** [comment]
Stale; closing.
