### ISSUE TITLE
Docs: Define single doc variable for the app registration URIs, versions etc.,

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#2923]
As a developer, I'd like to have a single place to modify the corresponding app registration URIs to use throughout the docs. Currently, we go to change several places for edits.

We can come up with something like:

- latest.streams.uri
- snapshot.streams.uri
- latest.tasks.uri
- snapshot.tasks.uri

and the same is applicable for version, metadata uri etc.,

**Comment by sabbyanandan** [comment]
I believe this is addressed now since we are pointing to "latest" links served from the Microsite. We still list the SRx links from the older release trains, but that table is in 1 place, and we will have to continue that model.
