### ISSUE TITLE
Dashboard: Add Docs Section on Creating Jobs

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#294]
Currently there is no documentation for creating a job. This is needed for the SCDF UI. The anchor name should be `#creating-a-job`

e.g.:

http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#creating-a-job

**Comment by sabbyanandan** [comment]
A section on Task creation is already in the docs and it also includes jobs, so we don't need explicit mention.
