### ISSUE TITLE
Remove the deprecated file-based authentication from K8s deployment

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2940]
As a developer, I'd like to remove the file-based authentication and the demo-users from K8s deployment since it is not supported anymore.

**Acceptance:**
- remove file-based auth section from `server-config-kafka.yaml` and `server-config-rabbit.yaml`
- remove [`18.6. Security`](http://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#configuration-kubernetes-security) from the ref. guide
- update [`18.4.1. Using ConfigMap and Secrets`](http://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#configuration-kubernetes-security) with a YAML sample that doesn't include the file-based auth configurations
- remove security callout in the [configuration](http://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#configuration-kubernetes) docs

**Comment by sabbyanandan** [comment]
We will revisit the security for SCDF v2.0 on K8s with an example via spring-cloud/spring-cloud-dataflow#2941.

**Comment by daviddelamo** [comment]
Hi, with those last commits the files `server-config-rabbit.yaml` and `server-config-kafka.yaml` doesn't exist anymore but the kubectl installation guide for version 2.1.0.RELEASE ( https://dataflow.spring.io/docs/installation/kubernetes/kubectl/ )  still mention those files. I assume that the installation guide is outdated and the files aren't needed anymore. Is this correct?

**Comment by chrisjs** [comment]
thanks, this will be addressed in: https://github.com/spring-io/dataflow.spring.io/pull/82

**Comment by sabbyanandan** [comment]
Hi, @daviddelamo. Thank you for reporting this!
