### ISSUE TITLE
Dashboard: Add Docs Section on Removing Jobs

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#295]
Reference by the Admin UI we need a section `Removing Batch Jobs`. Preferred anchor `removing-batch-jobs`.

e.g.: `http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#removing-batch-jobs`

**Comment by ghillert** [comment]
XD reference: http://docs.spring.io/spring-xd/docs/current/reference/html/#_removing_batch_jobs

**Comment by sabbyanandan** [comment]
A job can be deleted via Task representation and there's a screenshot of it.
