### ISSUE TITLE
Dashboard: Add Docs Section for launching a job

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#296]
We need a docs section for launching a job, e.g.:

http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#launching-a-job

Preferred anchor: `launching-a-job`

XD reference:

http://docs.spring.io/spring-xd/docs/current/reference/html/#_launching_a_job

**Comment by sabbyanandan** [comment]
Launching section is already [listed](https://docs.spring.io/spring-cloud-dataflow/docs/1.4.0.RC1/reference/htmlsingle/#dashboard-jobs).
