### ISSUE TITLE
Shell Commands unavailable when starting with no security details

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2964]
Let say security is enabled and I start the shell with:

`java -jar spring-cloud-dataflow-shell-2.0.0.RC1.jar`

The shell interactively asks for the credentials, however, once successfully logged in, the commands are not available.

![image](https://user-images.githubusercontent.com/685363/53560824-6060d980-3af1-11e9-91c2-f22ef568ca56.png)

When I start the shell with:

`java -jar spring-cloud-dataflow-shell-2.0.0.RC1.jar --dataflow.username=marlene --dataflow.password=supersecret`

everything works fine.

**Comment by tzolov** [comment]
Merged with commit 7c66072
