### ISSUE TITLE
UI + Shell: Bulk imports do not handle HTTP redirects (302) with changing scheme gracefully

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2967]
Spring Cloud Data Flow has an issue with bulk imports in case where the HTTP scheme changes between HTTP and HTTPs when encountering HTTP redirects (`301 Moved Permanently`).

We should not support a redirect from HTTPs to HTTP at all due to severe security implications. But we should **possibly** support a redirect from HTTP to HTTPs.

Nevertheless, we should explicitly handle this situation and provide a meaningful error message.

This works http://bit.ly/Einstein-GA-stream-applications-rabbit-maven:

![image](https://user-images.githubusercontent.com/685363/53599595-a3e83180-3b4b-11e9-9748-48f6624dfa12.png)

This fails https://bit.ly/Clark-GA-task-applications-maven:

![image](https://user-images.githubusercontent.com/685363/53599667-d4c86680-3b4b-11e9-8c63-b49abc5849ba.png)

**Comment by sabbyanandan** [comment]
I believe this is now addressed since we are serving all the URIs through the redirects set up in the Microsite. There's still a gap in "staging" vs. "production" build, but in production version always redirects to HTTPs anyway.
