### ISSUE TITLE
update PCF getting started guide to reference postgresql instead of mysql

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2977]
mysql (paid or free) does not work for data flow on PCF.

free - too few connections
paid - 5 year old version of mysql that doesn't like our schema.

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-dataflow/commit/5bd87b97d0a470af6fa7adbd5436a86092f1b2cd.
