### ISSUE TITLE
Docs: In cloudfoundry-security section bad link + outdated wording

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2978]
There is a bad link in the CF related docs. Plus the wording seems to have been taken from the old docs:

http://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#configuration-cloudfoundry-security

**Comment by sabbyanandan** [comment]
The CF security docs have been revised in 2.3.x.
