### ISSUE TITLE
Config-server binding in CF results with a 401

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2981]
As a user, when I attempt to bind SCDF against a config-server instance coming out of Spring Cloud Services, I get a 401 error.

It turns out Spring Cloud Services connector library is missing from the classpath. A fix could either come from Java CFEnv project or the relevant dependencies can be included directly in SCDF.

**Comment by markpollack** [comment]
Fixed by updating to java-cfenv 1.0.1.BUILD-SNAPSHOT
