### ISSUE TITLE
unable to pull springcloud/spring-cloud-dataflow-server-local:2.0.0.RELEASE from docker registry

### ISSUE THREAD

**Issue by kevinhamon** [spring-cloud/spring-cloud-dataflow#2988]
Much sadness.

**Comment by sabbyanandan** [comment]
Hi, @kevinhamon. 

In v2.0, we ship a single uber-jar/binary for all the supported platforms (i.e., local, cf and k8s). See blog [here](https://spring.io/blog/2019/03/06/spring-cloud-data-flow-and-skipper-2-0-ga-released#single-server-that-runs-on-all-supported-platforms).

Anyway, you'd have to pull the v2.0 image from [springcloud/spring-cloud-dataflow-server](https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server). Alternatively, you could use the docker-compose experience (see docs [here](http://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.RELEASE/reference/htmlsingle/#getting-started-local-deploying-spring-cloud-dataflow-docker)), which will use the same image internally as well.

**Comment by kevinhamon** [comment]
Stupid mistake. I must have had the wrong docker compose file. My bad. Much happiness.
