### ISSUE TITLE
Remove "spring-boot-starter-data-redis" dependency

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2989]
As a user, while deploying the server to K8s with health-checks enabled, I get the health-check status returned as "DOWN". It turns out, we are still explicitly including `spring-boot-starter-data-redis` dependency in the `spring-cloud-dataflow-registry` module.

See:
https://github.com/spring-cloud/spring-cloud-dataflow/blob/7a8d639c299c9228d6cd41ea4e910de59807aea5/spring-cloud-dataflow-registry/pom.xml#L35

**Acceptance:**
- The dependency should be removed. 
- Make sure there's no Redis dependency whatsoever in the classpath; confirm it with `java -tvf ...` command.

**Comment by sabbyanandan** [comment]
Also, clean up the [Redis references](https://github.com/spring-cloud/spring-cloud-dataflow/search?utf8=%E2%9C%93&q=redis&type=) from the project.

**Comment by chrisjs** [comment]
`mvn dependency:tree` comes up clean, jar contents:

```
$ jar tvf spring-cloud-dataflow-server/target/spring-cloud-dataflow-server-2.0.1.BUILD-SNAPSHOT.jar| grep redis
$
```

health check now appears correct:

```
$ java -jar spring-cloud-dataflow-server/target/spring-cloud-dataflow-server-2.0.1.BUILD-SNAPSHOT.jar
...
...
$ curl localhost:9393/management/health
{"status":"UP"}
$
```

additionally, all the redis references are now gone with the exception of `link:{scs-app-starters-docs-htmlsingle}/#spring-cloud-stream-modules-redis-sink[redis-pubsub]` in `spring-cloud-dataflow-docs/src/main/asciidoc/applications.adoc` as discussed
