### ISSUE TITLE
Failed to bind properties under 'spring.redis.port' to int:

### ISSUE THREAD

**Issue by durgadevikarthikeyan** [spring-cloud/spring-cloud-dataflow#2991]
**Description:**
I have tried to setup Spring cloud data flow for kuberenetes. Followed below documentation 
[(https://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.RELEASE/reference/htmlsingle/#getting-started-kubernetes)]
and setup 
mysql-scdf-55d7bbcd7-z8shl , rabbitmq-76df66dc8c-2jjv8 , scdf-server-55d7546f84-bt7r6 and skipper-6c7cccc797-dk95f

**Release versions:**
[https://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.RELEASE/reference/htmlsingle/#getting-started-kubernetes]

**Custom apps:**
NA

**Steps to reproduce:**
Followed the documention, the link is pasted already except kafka, promethus and grafana

**Screenshots:**
SCDF-Server pod is running but i am not able to access the service
`2019-03-07 09:43:32.540 ERROR 1 --- [           main] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healthEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Unsatisfied dependency expressed through method 'healthEndpoint' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthIndicatorRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthIndicatorAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthIndicatorRegistry]: Factory method 'healthIndicatorRegistry' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.redis.RedisReactiveHealthIndicatorAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.data.redis.LettuceConnectionConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'spring.redis-org.springframework.boot.autoconfigure.data.redis.RedisProperties': Could not bind properties to 'RedisProperties' : prefix=spring.redis, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.redis.port' to int
2019-03-07 09:43:32.635  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-03-07 09:43:32.650  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
2019-03-07 09:43:32.696 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.redis.port' to int:

    Property: spring.redis.port
    Value: ${REDIS_SERVICE_PORT}
    Origin: "spring.redis.port" from property source "bootstrapProperties"
    Reason: failed to convert java.lang.String to int

Action:

Update your application's configuration
`
**Additional context:**

**Comment by sabbyanandan** [comment]
Hi, @durgadevikarthikeyan. Thank you for reporting. We noticed this after the GA release yday and we are tracking the fix via spring-cloud/spring-cloud-dataflow#2989. A v2.0.1 release with the fix will go out soon.

**Comment by chrisjs** [comment]
@durgadevikarthikeyan while the system is running and you are getting that exception, can you paste the contents of the following command:

`kubectl get cm scdf-server -o yaml`

**Comment by durgadevikarthikeyan** [comment]
> Hi, @durgadevikarthikeyan. Thank you for reporting. We noticed this after the GA release yday and we are tracking the fix via #2989. A v2.0.1 release with the fix will go out soon.

Thanks @sabbyanandan

**Comment by chrisjs** [comment]
@durgadevikarthikeyan it would be helpful to provide the output of `kubectl get cm scdf-server -o yaml` as mentioned above as references to `${REDIS_SERVICE_PORT}` were previously removed

**Comment by durgadevikarthikeyan** [comment]
`Durgadevi.ramadoss@jenkinstest001:~$ kubectl get cm scdf-server -o yaml
apiVersion: v1
data:
  application.yaml: |-
    security:
      basic:
        enabled: true
        realm: Spring Cloud Data Flow
    spring:
      cloud:
        dataflow:
          security:
            authentication:
              file:
                enabled: true
                users:
                  admin: admin, ROLE_MANAGE, ROLE_VIEW
                  user: password, ROLE_VIEW, ROLE_CREATE
        deployer:
          kubernetes:
            environmentVariables: 'SPRING_RABBITMQ_HOST=${RABBITMQ_SERVICE_HOST},SPRING_RABBITMQ_PORT=${RABBITMQ_SERVICE_PORT},SPRING_REDIS_HOST=${REDIS_SERVICE_HOST},SPRING_REDIS_PORT=${REDIS_SERVICE_PORT}'
      datasource:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysql
        username: root
        password: ${mysql-root-password}
        driverClassName: org.mariadb.jdbc.Driver
        testOnBorrow: true
        validationQuery: "SELECT 1"
      redis:
        host: ${REDIS_SERVICE_HOST}
        port: ${REDIS_SERVICE_PORT}
kind: ConfigMap
metadata:
  creationTimestamp: "2019-03-04T14:50:51Z"
  labels:
    app: scdf-server
  name: scdf-server
  namespace: default
  resourceVersion: "1465169"
  selfLink: /api/v1/namespaces/default/configmaps/scdf-server
  uid: e7ebf5cd-3e8c-11e9-925c-42010a8a0100
Durgadevi.ramadoss@jenkinstest001:~$

**Comment by durgadevikarthikeyan** [comment]
Durgadevi.ramadoss@XXX:~$ kubectl get cm scdf-server -o yaml
apiVersion: v1
data:
  application.yaml: |-
    security:
      basic:
        enabled: true
        realm: Spring Cloud Data Flow
    spring:
      cloud:
        dataflow:
          security:
            authentication:
              file:
                enabled: true
                users:
                  admin: admin, ROLE_MANAGE, ROLE_VIEW
                  user: password, ROLE_VIEW, ROLE_CREATE
        deployer:
          kubernetes:
            environmentVariables: 'SPRING_RABBITMQ_HOST=${RABBITMQ_SERVICE_HOST},SPRING_RABBITMQ_PORT=${RABBITMQ_SERVICE_PORT},SPRING_REDIS_HOST=${REDIS_SERVICE_HOST},SPRING_REDIS_PORT=${REDIS_SERVICE_PORT}'
      datasource:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysql
        username: root
        password: ${mysql-root-password}
        driverClassName: org.mariadb.jdbc.Driver
        testOnBorrow: true
        validationQuery: "SELECT 1"
      redis:
        host: ${REDIS_SERVICE_HOST}
        port: ${REDIS_SERVICE_PORT}
kind: ConfigMap
metadata:
  creationTimestamp: "2019-03-04T14:50:51Z"
  labels:
    app: scdf-server
  name: scdf-server
  namespace: default
  resourceVersion: "1465169"
  selfLink: /api/v1/namespaces/default/configmaps/scdf-server
  uid: e7ebf5cd-3e8c-11e9-925c-42010a8a0100
Durgadevi.ramadoss@XXX:~$

**Comment by durgadevikarthikeyan** [comment]
updated it. It is looking for REDIS_PORT & REDIS_HOST

**Comment by chrisjs** [comment]
looks like your not using a recent configmap (and possibly other) configuration(s), for example given you referenced `2.0.0.RELEASE` - the one that ships with that version is:

https://github.com/spring-cloud/spring-cloud-dataflow/blob/v2.0.0.RELEASE/src/kubernetes/server/server-config-rabbit.yaml

if you do not intend to use prometheus/grafana you can find info on removing the relevant sections from the config in the documentation under the section `Deploy Prometheus and Grafana`

**Comment by durgadevikarthikeyan** [comment]
@chrisjs , I have not deployed prometheus and Grafana, so removed that from config file

> `Durgadevi.ramadoss@xxx:~/spring-cloud-dataflow/src/kubernetes/server$ cat server-config-rabbit.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-server
  labels:
    app: scdf-server
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
      datasource:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysql
        username: root
        password: ${MYSQL_ROOT_PASSWORD}
        driverClassName: org.mariadb.jdbc.Driver
        testOnBorrow: true
        validationQuery: "SELECT 1"

Durgadevi.ramadoss@xxx:~/spring-cloud-dataflow/src/kubernetes/server$
`

**Comment by chrisjs** [comment]
then you would likely want to use something like the following (the above yaml is missing the kubernetes account settings):

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-server
  labels:
    app: scdf-server
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    limits:
                      memory: 1024Mi
      datasource:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysql
        username: root
        password: ${mysql-root-password}
        driverClassName: org.mariadb.jdbc.Driver
        testOnBorrow: true
        validationQuery: "SELECT 1"
```

apply that, confirm the old config map is replaced with the new one, redeploy SCDF and you should be on your way providing there aren't any other configs outdated.

info on checking out the proper branch based on the selected docs can be found at:

https://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.RELEASE/reference/htmlsingle/#_deploying_with_code_kubectl_code

along with all the steps to apply files as well as delete ones that may be hanging around if needed.

**Comment by durgadevikarthikeyan** [comment]
@chrisjs followed the same documentation, mentioned in case also

**Comment by durgadevikarthikeyan** [comment]
will try this and confrim

**Comment by durgadevikarthikeyan** [comment]
The above configmap resolves redis exception. Thanks for it
But i am not sure why this issues comes, i also shared my configmap in the issue

**Comment by chrisjs** [comment]
good to hear it's working. as far as why the issue came up, given the contents of the ConfigMap that you pasted, it would seem likely that its one that may have existed previously from another version of dataflow and wasn't deleted. obviously just a guess, but the contents do not reflect the current version layout.
