### ISSUE TITLE
Typo 16.1 feature toggles

### ISSUE THREAD

**Issue by wxlund** [spring-cloud/spring-cloud-dataflow#2995]
16.1. Feature Toggles
**Sprig** Cloud Data Flow Server offers specific set of features that can be enabled/disabled when launching. 
Simple typo on Spring Cloud Data Flow server I found while reviewing 2.0 docs. I saw that its also in 1.7.4's docs as well.

**Comment by ilayaperumalg** [comment]
@wxlund Thanks for reporting. Fixed in 1.7.x as 20d1ce7a and 2.x as e6afdf9
