### ISSUE TITLE
Adding Kafka support to stable/spring-cloud-data-flow Helm chart

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow#2996]
_From @vxavictor513 on March 7, 2019 9:37_

The current official Helm chart, [stable/spring-cloud-data-flow](https://github.com/helm/charts/tree/master/stable/spring-cloud-data-flow) only supports RabbitMQ integration. It'd be great if Kafka integration is added.

_Copied from original issue: spring-cloud/spring-cloud-dataflow-server-kubernetes#387_

**Comment by chrisjs** [comment]
moving to https://github.com/spring-cloud/spring-cloud-dataflow/ as development from 2.x on is done there

**Comment by sabbyanandan** [comment]
Relates to spring-cloud/spring-cloud-dataflow#2689.

**Comment by chrisjs** [comment]
added support for this + updated docs

**Comment by sabbyanandan** [comment]
I tried the Chart-PR from the branch locally. I switched between Rabbit and Kafka-based SCDF components in like 5mins or less. Incredible!

**Comment by chrisjs** [comment]
I've updated https://github.com/spring-cloud/spring-cloud-dataflow/issues/2689 to include the addition of kafka so closing this issue
