### ISSUE TITLE
Do we want to continue using codecov.io in our builds

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#3004]
if not, how should we easily enable finding out this metric - maven plugin, just use the IDE?

**Comment by sabbyanandan** [comment]
It appears there is a variety of unexpected reasoning to which CodeCov would report as "changes" to test and complexity coverage. 

```
There are a number of reasons Codecov staff has found to cause line coverage to change. These can be due to:

Adding or removing tests.
Failing to upload coverage reports.
Time sensitive tests .
Missing coverage reports or failed builds.
Dependencies changed resulting in a different execute plan.
Encrypted variables may prevent some execution paths.
```

While reviewing [spring-cloud/spring-cloud-dataflow/pull/3122/diff](https://codecov.io/gh/spring-cloud/spring-cloud-dataflow/pull/3122/diff), I notice there's _addition_ of test coverage, but the overall change is reported (unexpectedly) as a decrease in coverage. 

Though adding new tests could cause this anomaly (see reasons above), but in this commit, however, there seem to be changes in code that doesn't have corresponding test coverage. Those changes are highlighted in red on left-margin. So this is a legitimate decrease from an overall project code coverage perspective.
