### ISSUE TITLE
Remove H2 configs for tasks

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#3019]
As we don't support running H2 as non-embedded mode, `H2ServerConfiguration` and `NoH2ServerConfiguration` should go away.

**Comment by cppwfs** [comment]
The PR looks LGTM (haven't kicked the tire s on it).   The only issue I see is that our documentation still states that we support external H2 (Non-Production).  Found here: https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/configuration-local.adoc .  Do we need to update the docs to explicitly state we don't support external H2?

**Comment by ilayaperumalg** [comment]
I think this needs to be backported into 2.0.x.

**Comment by cppwfs** [comment]
Backported
