### ISSUE TITLE
Filter OOTB modules by Admin SPI type

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#303]
As a user, I'd like to see the filtered list of OOTB modules supported by each Admin SPI, so I don't tend to use a module that is not supported by the Admin. 

**Acceptance:**
* List of registered modules are filtered by the type of Admin SPI
* For example: Cloud Foundry's [Loggregator](https://github.com/spring-cloud/spring-cloud-stream-modules/pull/154) module will be listed only for Admin CF and ignored for Local, YARN, Mesos, and Kubernetes variants

**Comment by joshlong** [comment]
wha - no the Loggregator can be used in any env, I'd imagine? in theory you could want to manipulate CF from a Mesos deployment? IDK.. maybe not.. but at least make it so that i can disable the filtering and show everything if im sure i know what im doing

**Comment by sabbyanandan** [comment]
Given the new direction, all the deployers bootstrap with empty registry and it is up to the user to register apps that are relevant for their use-case(s). So, this is not applicable anymore.
