### ISSUE TITLE
Support global component selection and overrides

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#305]
As a developer, I'd like to explore options to support global system/component selection and overrides, so I can make the necessary configuration changes to deploy the admin with new opinions.

The notion of `servers.yml` as the global config location in Spring XD allowed us to select the binder type and override binder specific options. Not just for the binders, but this was the central location for all other system/component level overrides. 
* What would be an equivalent in SCDF model?
* Could Spring Intializr like [experience](https://github.com/spring-cloud/spring-cloud-dataflow/issues/211) for SCDF be the solution?

**Comment by ericbottard** [comment]
I don't really get this. The admin is a boot app, and as such benefits from everything boot has to offer, including configuration via commandLine flags, env vars, config server, etc?

**Comment by trisberg** [comment]
@ericbottard I think that's exactly the point, multiple ways to achieve this, but no documentation stating how to do it in a production or a standalone test environment. We need a documented way for users to persist their config choices so they can deploy Data Flow in a predictable and  consistent manner.

**Comment by sabbyanandan** [comment]
This story has some correlation with `ModuleLauncher` replacement and as well as the `start.dataflow.io` equivalent workstreams. We would want simpler dev-experience in regards to how we switch binders, database (for tasks), or for that matter the hadoop distro, while using the `hdfs` sink. This is much larger in scope, so we have it as a spike. 

As @trisberg says, we also need the recommended best practices (for central configurations) documented in the reference guide.

**Comment by sabbyanandan** [comment]
This is not relevant anymore.
