### ISSUE TITLE
Serve bulk-registration URIs from the Microsite route in PWS

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3093]
As a developer, I'd like to come up with a design to serve the bulk-registration application URIs from the Microsite.

**Background:**
- The goal is to drop it and move away from bit.ly dependency completely.
- At a given point, it may be _required_ to serve at least 2 minor previous releases along with the latest GA release coordinates.

**Acceptance:**
- Today, we follow `<TRAIN>-<VERSION>-stream-applications-rabbit-maven` as the format for new URIs; we could use `stream-applications-rabbit-maven` as the format for latest releases always - backing URL can be updated since it will be in our control.
- For past releases, we still need the ability to have the shortened link with the train and version included in it similar to `<TRAIN>-<VERSION>-stream-applications-rabbit-maven`.
- The delivery mechanism could be a table hosted in the Microsite similar to how we render them in the Apps project sites [eg: http://cloud.spring.io/spring-cloud-stream-app-starters/].
- All the references in the docs, tests, UI/About, and the other places should update to point to the new Microsite URLs (ATs don't use it; they rely on absolute path from the Spring Repo already).

**Comment by markpollack** [comment]
CloudFlare Manages 6 variations for 'latest', redirect to artifactory.

https://dataflow.spring.io/rabbitmq-maven-latest

https://dataflow.spring.io/rabbitmq-docker-latest

https://dataflow.spring.io/kafka-maven-latest

https://dataflow.spring.io/kafka-docker-latest

https://dataflow.spring.io/task-maven-latest

https://dataflow.spring.io/task-docker-latest

===================

Gatsby Manages For Releases and Snapshots

https://dataflow.spring.io/Darwin-SR3-stream-applications-kafka-docker

https://dataflow.spring.io/Darwin-BUILD-SNAPSHOT-stream-applications-kafka-docker

etc...

https://dataflow.spring.io/Elston-GA-task-applications-maven

**Comment by sabbyanandan** [comment]
All the scope of work in this epic is complete - closing it.
