### ISSUE TITLE
Develop Batch Developer Guide for Microsite

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3105]
Goal:
Walkthrough the various facets of a day in the life of a developer developing task/batch applications.

Define:

- Programming model and the choices
- SCT property overrides
- Testing options
- Role of the datasource
- Deployment experience in the cloud (cf / k8s)
- SCT and SCDF semantics
- Launching tasks from streams or through other methods (eg: Task Launch vs. CTR vs. Scheduler vs. External Triggers)

**Comment by dturanski** [comment]
@sabbyanandan  - I have a demo that composed the `time` source with the dataflow task launch request function https://github.com/spring-cloud-stream-app-starters/core/blob/master/common/app-starters-task-launch-request-common/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/DataFlowTaskLaunchRequestAutoConfiguration.java#L71 . In fact, with minimal customization,  devs can compose any source with this function to use the `tasklauncher-dataflow` sink.  This is much easier IMHO than using the standalone `tasklaunchrequest-transformer` and also supports spel expressions, so inbound message content can be used in the launch request, which the transformer doesn't do.  Anyway, I think we need to include this in the guide.

**Comment by sabbyanandan** [comment]
All the associated stories in this epic are complete. Thank you, @cppwfs @dturanski @ghillert!
