### ISSUE TITLE
Persist stream/task definitions in DB

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#311]
As a developer, I'd like to add an option to persist stream/task definitions in the existing `datasource`, so I can retrieve  (from the underlying DB) and redeploy the definitions under fault scenarios. This is dependent on spring-cloud/spring-cloud-dataflow#307.

**Acceptance:**
* Ability to persist the definitions can be turned ON; default is OFF
* `datasource` can be backed by variety of DB options 
* Documentation available for reference

**Comment by markpollack** [comment]
Note, will need to test and also update documentation for various admin impls, e.g on CF having the admin bind to mysql and not to redis.

**Comment by trisberg** [comment]
Would also be convenient to have additional JDBC drivers in the build, similar to - https://github.com/spring-cloud/spring-cloud-stream-modules/issues/167

**Comment by markpollack** [comment]
I guess it doesn't hurt i guess - how big are they?  However there isn't a t ask schema that can be automatically created for most of those databases listed.  

Generally speaking, how would the admin get the additional .jar file for a database driver such as oracle?  There is the java -u0f approach or this would be a case for "Josh's" @EnableAdminServer annotation to create a new uberjar with the required dep.

**Comment by trisberg** [comment]
Yeah, we only need the drivers for the supported databases - PostgreSQL (650KB), MySQL (Maria DB driver, 358K), H2 (already included as default) and HSQLDB (1.5MB). So adds ~2MB to the size of the jar. For Oracle, they would have to either inject the jdbc-jar file into the uber-jar or build a new app either putting the Oracle jdbc-jar in `src/main/resources/lib` or adding it to a local Maven repo and referencing that in the pom.

**Comment by markpollack** [comment]
The current repo impls do a check on save to see if an entity already exists.  This is different than the spring data jpa save contract (persist if new, merge if not).  The logic for this check will need to move into the task/stream controllers or into a service layer.  controller is prob enough...  See this related PR for some background. https://github.com/spring-cloud/spring-cloud-dataflow/pull/588

**Comment by sabbyanandan** [comment]
Duplicate of #606 and #589
