### ISSUE TITLE
Monitoring: With Prometheus, Grafana dashboard shows error when clicking applications

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#3111]
After setting up docker-compose up and deploy streams, when I click on the applications from the Grafana dashboard, I see the following:
```
Templating init failed
parse error at char 16: vector selector must contain at least one non-empty matcher
```

**Comment by tzolov** [comment]
@ilayaperumalg i can not reproduce above error? 
I found another problem caused but changing grafana's url from http to https by the Operator. So i will revert back to http

**Comment by sigint76** [comment]
Hi,

I still have this error. I configured everything with the docker-compose files provided in officiale documentation. The version of SCDF is 2.3.1.RELEASE (SKIPPER = 2.2.1.RELEASE).
