### ISSUE TITLE
manual installation of spring-cloud-dataflow-shell is not resolved in the docs

### ISSUE THREAD

**Issue by wlund-pivotal** [spring-cloud/spring-cloud-dataflow#3119]
**Description:**
In the [Getting Started with Manual Installation]( http://docs.spring.io/spring-cloud-dataflow/docs/2.0.1.RELEASE/reference/htmlsingle/#getting-started-local-deploying-spring-cloud-dataflow) section of the docs the template is not replaced by a version for wget to work with even though all of the other versions are.  See this:

[Download the Spring Cloud Data Flow Shell](wget https://repo.spring.io/{version-type-lowercase}/org/springframework/cloud/spring-cloud-dataflow-shell/{project-version}/spring-cloud-dataflow-shell-{project-version}.jar
)

**Release versions:**
I'm trying to use this with scdf-2.0.1.RELEASE

**Steps to reproduce:**
See the doc link

**Comment by sabbyanandan** [comment]
Thanks. Closing this in favor of https://github.com/spring-cloud/spring-cloud-dataflow/issues/3117.
