### ISSUE TITLE
Documentation chapter "3.8. Viewing Stream Logs" missing a return

### ISSUE THREAD

**Issue by andrea-sdl** [spring-cloud/spring-cloud-dataflow#3120]
Hi there, I'm trying out SCDF and I saw a small glitch on this page
https://docs.spring.io/spring-cloud-dataflow/docs/2.0.1.RELEASE/reference/htmlsingle/#getting-started-local-deploying-spring-cloud-dataflow-docker-viewing-stream-logs

Basically you're missing the return before the "=== Deleting a stream" part 
![Spring Cloud Data Flow Reference Guide](https://user-images.githubusercontent.com/668251/55395025-082e5480-5541-11e9-8c6d-9087aa97e251.png)

I didn't know if you preferred a PR or an issue, so I started with the simple one ;) 

In case I find some extra errors and you're open to PR's for the docs part I can go that route if that helps you :)

Thanks for the great work you're doing!

**Comment by sabbyanandan** [comment]
@andrea-sdl: Thanks for spotting that! 👏 

I pushed a commit to resolve the formatting issue via: https://github.com/spring-cloud/spring-cloud-dataflow/commit/bdc6d6671cda8a2ea6ae88053c240ceabc31be5f.

If you see any other anomaly in the docs/code, please, by all means, feel free to submit a PR.
