### ISSUE TITLE
Add deployer properties to LauncherRepository

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3121]
A continuation of what we did via https://github.com/spring-cloud/spring-cloud-dataflow/issues/3057. To do this, we will have to revisit the overall Task/Batch lifecycle management semantics in SCDF. CI/CD for Tasks is one of the goals when we revisit the topic.

**Comment by jvalkeal** [comment]
Now done as master is using skipper snapshots.

**Comment by jvalkeal** [comment]
Ups, closed wrong one as this was for tasks.

**Comment by venkatasreekanth** [comment]
Attaching real world use case as requested. We pass kerberos auth properties through deployer  javaOpts options. The batch jobs write to a kafka topic which requires kerberos authentication. The deployer javaOpts are passed through the API call to start the batch job as different batch jobs have different memory requirements and different configuration for the JVM. As of today, all of our batch jobs cannot be restarted unless the SCDF server is stopped and deployer configuration added to SCDF properties and then restarting SCDF and then restarting jobs. It would nice to avoid this headache by having SCDF record the deployer properties and pass them to the jobs when restarted.
