### ISSUE TITLE
Add doc section on k8s securityContext

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow#3123]
Add a section to the docs with some info on running data flow components as non-root user using `securityContext` in deployment configs

**Comment by chrisjs** [comment]
likely these docs would include any changes in deployer such as https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/291

**Comment by sabbyanandan** [comment]
This was addressed in https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/306 and https://docs.spring.io/spring-cloud-dataflow/docs/2.2.0.RELEASE/reference/htmlsingle/#_pod_security_context.
