### ISSUE TITLE
Write docs for k8s tolerations support

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow#3124]
Add docs for tolerations support added in https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/266

**Comment by sabbyanandan** [comment]
Hi, @JStrittmatter. Thank you for contributing the support for K8s tolerations! It'd be nice to close the loop with the addition of corresponding docs on this matter. Here are all the deployer properties [described in the ref. guide](http://docs.spring.io/spring-cloud-dataflow/docs/2.0.2.BUILD-SNAPSHOT/reference/htmlsingle/#_application_and_server_properties) with examples. The docs code lives [here](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-kubernetes.adoc#application-and-server-properties). 

Feel free to take a stab at it; o'wise, one of us will add it to the docs. No rush. 😄
