### ISSUE TITLE
Demonstrate Python-native application as a app-type with Kafka running on K8s

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3126]
`k8s, python, kafka, app` - document the combination in a case where there are multiple input/output topics.

**Comment by tzolov** [comment]
- Resolved with an example: https://github.com/tzolov/scdf-polyglot-experiments/tree/master/scdf_python_app
- Doc: [Google Doc](https://docs.google.com/document/d/1sDxKO4qN9FSEA8LoPfhdbD82LF1MRYVKZQTTGZ0VqQA/edit?usp=sharing)
