### ISSUE TITLE
Demonstrate a Python-native Task application on K8s

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3127]
`k8s, python, task` - document how to write the task to scdf database (eg: postgress), so execution status appears in SCDF dashboard.

**Comment by tzolov** [comment]
Resolved:
* The [google doc](https://docs.google.com/document/d/1qov3qU4CjwqE9ZbZywpl6vMdpJsxvWXP9E_vXS3o6fM/edit?usp=sharing) example for the Docker/Python task with self managed status:
* Related [code](https://github.com/tzolov/scdf-polyglot-experiments/tree/master/python_task_with_status)
