### ISSUE TITLE
How to swap binder implementation

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#313]
As a user, I'd like to refer to docs on how to switch from the default `redis` as the binder to `rabbit`, `kafka`, or others. 

**Acceptance:**
* Documentation available for reference
* Sample stream definitions included

**Comment by mbogoevici** [comment]
We should probably postpone it until we decide on the future of Module Launcher, IMO.

**Comment by sabbyanandan** [comment]
Binder specific apps can be registered or overwritten with `--force` flag while registering apps. There's also support to override binder coordinates at the stream deploy time.
