### ISSUE TITLE
Publish SCDF Helm Chart v2.0.1

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3138]
As a developer, I'd like to submit the v2.0.2 release of SCDF as a v2.0.1 version to the Helm chart repository.

**Comment by chrisjs** [comment]
https://github.com/helm/charts/pull/12951

**Comment by sabbyanandan** [comment]
This is now merged/published -> https://hub.helm.sh/charts/stable/spring-cloud-data-flow
