### ISSUE TITLE
Add DSL taps support

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#314]
As a user, I'd like to tap an existing stream via DSL syntax, so I can get a copy of the primary pipeline data for ad-hoc analysis. 

**example:**
```
stream create tweets --definition "twitterstream | log"
stream deploy tweets --properties "module.*.includes=org.springframework.cloud:spring-cloud-stream-binder-rabbit:1.0.0.M3,module.*.excludes=:*-redis"

stream create tweetlang  --definition "tap:stream:tweets > log"
stream deploy tweetlang --properties "module.*.includes=org.springframework.cloud:spring-cloud-stream-binder-rabbit:1.0.0.M3,module.*.excludes=:*-redis"
```

**Acceptance:**
* Decide whether we need `tap:stream..`, `topic:stream..` or `<streamName>.0`
* `tweetlang` stream taps `tweets` stream successfully
* Documentation along with samples included for reference

**Comment by ilayaperumalg** [comment]
Here is my branch [commit](https://github.com/ilayaperumalg/spring-cloud-dataflow/commit/65d0e841c1990ab5455451fe266c16284849de3c) that has the following changes:

- After the binder refactoring on SCS to use pub/sub model and the consumer groups, this PR provides a simplistic approach
    to support tap DSL.

      - Add consistent syntax for assigning the binding `destination` name
       - This turns out to be the module `label` instead of `index`
      - For the tap support, the DSL would look like this:

    ```
     stream create a1 --definition "http | transform | log" --deploy
     stream create tap-http --definition "a1.http > jdbc" --deploy
     stream create tap-transform --definition "a1.transform > counter" --deploy
    ```
    All the named channel syntaxes such as `queue:`, `tap:` and `topic:` are removed.
