### ISSUE TITLE
Describe troubleshooting flows in the Microsite

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3152]
The goal of this epic is to capture all the various options available for troubleshooting.

It has to begin with the applications. What all someone can do to test/debug the stream/task apps locally and what options are available when running the apps in the platform.

Move onto SCDF/Skipper deployment and the specifics as to how to troubleshoot in this setup; again locally and in the cloud.

Move onto Task Launcher and CTR - discuss the specific techniques.

**Comment by chrisjs** [comment]
all set
