### ISSUE TITLE
Demonstrate Stream deployment experience using SCDF in K8s

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3155]

**Comment by sabbyanandan** [comment]
This is already done. Marking it as complete.

**Comment by sabbyanandan** [comment]
This is not really done-done. There's TODO for this item in the site right now.

**Comment by chrisjs** [comment]
LGTM - minor mods, will make on merge

**Comment by chrisjs** [comment]
merged
