### ISSUE TITLE
Unable to deploy stream containing scriptable-transform-processor

### ISSUE THREAD

**Issue by AddaxT** [spring-cloud/spring-cloud-dataflow#3169]
After creating any stream definition containing scriptable-transform-processor-kafka:2.1.0.RELEASE using python as the language deployment is failing at YAML validation (it seems is failing when generating deployment descriptor for K8s). 

We are using SCDF server 2.0.0.RELEASE, Skipper 2.0.0.RELEASE and GKE 1.11.7-gke.12. Please see the image below. Same script worked fine on SCDF 1.7.3 local deployer.

![image](https://user-images.githubusercontent.com/5182016/56184363-5af71a00-5fdf-11e9-89ad-6f7eaf0c3f09.png)

**Comment by sabbyanandan** [comment]
This appears to be a discussion to have at the app level as opposed to in SCDF. Moved it to: Unable to deploy stream containing scriptable-transform-processor #3169
