### ISSUE TITLE
Scheduled Task does not recognize multiple profiles

### ISSUE THREAD

**Issue by jsa4000** [spring-cloud/spring-cloud-dataflow#3187]
**Description:**
Creating a scheduled task using kubernetes Spring Cloud Dataflow server, it does not parse correctly the arguments with commas. for example `--spring.profiles.active=k8s,master`. It seems to interprete the profile composition as two arguments.

`2019-04-24 07:38:12.456 DEBUG 1 --- [           main] o.s.c.t.r.support.SimpleTaskRepository   : Creating: TaskExecution{executionId=0, parentExecutionId=null, exitCode=null, taskName='batch-uploader-task', startTime=Wed Apr 24 07:38:12 GMT 2019, endTime=null, exitMessage='null', externalExecutionId='null', errorMessage='null', arguments=[--spring.datasource.username=postgres, --spring.datasource.url=jdbc:postgresql://eks-lab-dev-db.cwekrnapay4v.eu-west-2.rds.amazonaws.com:5432/dataflow, --spring.datasource.driverClassName=org.postgresql.Driver, --spring.cloud.task.name=batch-uploader-task, --version=0.0.1, --spring.datasource.password=password, --spring.profiles.active=k8s, master]}`

In this case the second profile is not recognized for the application.

This happens only creating scheduled tasks, since launching the tasks normally it work as expected.

**Release versions:**
Used docker version from docker hub.

- image: springcloud/spring-cloud-dataflow-server
- version: 2.0.2.RELEASE

**Custom apps:**
A custom App with a partitioner that needs two profiles to work.

**Steps to reproduce:**

1. Register the app

`app register --type task --name batch-uploader-app --uri docker:jsa4000/dataflow-batch-uploader-k8s:0.0.1-SNAPSHOT`

2. Create the task

`task create batch-uploader-task --definition "batch-uploader-app --version=0.0.1"`

3. Create a schedule task:

Task Name: `batch-uploader-task`
Schedule name: `myschedule`
Cron Expression: `*/1 * * * *`
Arguments:  `--spring.profiles.active=k8s,master` or `--spring.profiles.active="k8s,master"`

**Comment by sabbyanandan** [comment]
@jsa4000: Thanks for the report. That seems like a disconnect between a manual launch vs. launching on a recurring schedule. We will have a look.

**Comment by chrisjs** [comment]
when `TaskSchedulerController.save` is called, `arguments` contain multiple entries, based on how many `,`'s it splits on, rather than a single value

**Comment by chrisjs** [comment]
Issue moved to [spring-cloud/spring-cloud-dataflow-ui #1178](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1178) via [**ZenHub**](https://www.zenhub.com/)

**Comment by chrisjs** [comment]
Issue moved to [spring-cloud/spring-cloud-dataflow-ui #1179](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1179) via [**ZenHub**](https://www.zenhub.com/)
