### ISSUE TITLE
Docs: Yaml Options don't match example

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#3189]
The description: `You need to fill in <org>, <space>, <email>, <password>, <middlewareServiceName> (RabbitMQ or Apache Kafka) and <services>`

Does not match the provided yaml file: 

![image](https://user-images.githubusercontent.com/685363/56701844-b76fce80-669c-11e9-8202-4c942621ffd2.png)

**Comment by sabbyanandan** [comment]
This section is now moved to the Microsite and the placeholder is now pointing to the correct replace tokens. See: https://dataflow.spring.io/docs/installation/cloudfoundry/cf-cli/#manifest-based-installation-on-cloud-foundry
