### ISSUE TITLE
Support external databases in helm chart

### ISSUE THREAD

**Issue by lwj5** [spring-cloud/spring-cloud-dataflow#3191]
**Problem description:**
Unable to use external databases when deploying from helm chart as SCDF deploys its own MySQL db, and RabbitMQ or Kafka queue engine. 

**Solution description:**
To allow the option of specifying the following in deployment yaml.
For MySQL:
- host
- port
- username
- password
- database (for skipper and for server)

RabbitMQ:
- host
- erlang-cookie
- password

which will be placed in a secret, and prevent deployment of these databases if host field is not empty.

**Description of alternatives:**
Deleting automatically deployed databases and manually changing the secrets and services to point to external deployed databases.

**Additional context:**
Decouple SCDF deployment from databases.
Allow sharing of databases with other apps.
Allow the use of HA database deployments.

**Comment by lwj5** [comment]
I will contribute, should I make a PR to https://github.com/helm/charts?

**Comment by lwj5** [comment]
PR submitted

https://github.com/helm/charts/pull/13697

**Comment by lwj5** [comment]
@sabbyanandan could you follow up to get the chart approved. It would be good if there is an owners file in the chart listing some of the developers here.

**Comment by sabbyanandan** [comment]
Hi, @lwj5. Thank you for your contribution! We have plans to host the helm-chart in our repo, but still, also list the chart at https://hub.helm.sh. [see: https://github.com/spring-cloud/spring-cloud-dataflow/issues/2894]

Until then, though, we will have to continue to follow the current contribution pattern. @chrisjs and I will look into what it would take to get this PR merged.

**Comment by lwj5** [comment]
That’s good to hear!

If you guys have any comment or need any clarification on the modifications feel free to let me know. 

Thanks for the follow up.

**Comment by chrisjs** [comment]
merged
