### ISSUE TITLE
Password Parameter should be masked

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#320]
If a user executes a restful request for task details i.e. `task view --id` the password contents currently shows up.  This data needs to be redacted or masked.

**Comment by mminella** [comment]
This should follow the same conventions for masking values as Spring Boot Acuator's `/env` endpoint does (any property with `password`, `secret`, or `key` should be masked).

**Comment by cppwfs** [comment]
This pertains to both stream and task modules.

**Comment by sabbyanandan** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-dataflow/issues/1546 and https://github.com/spring-cloud/spring-cloud-dataflow/issues/1542.
