### ISSUE TITLE
Investigate removal of DATAFLOW_VERSION & SKIPPER_VERSION vars from compose

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow#3201]
Currently the vars `DATAFLOW_VERSION` and `SKIPPER_VERSION` need to be manually defined when using the docker compose quick start. These were required as templating wasn't available when pulling a file from github raw content. Possibly this could be hosted/templated via microsite templating functionality and the requirement on these variables needing to be defined can go away

**Comment by tan31989** [comment]
I have tried to provide conditional arguments rather than removing the flow versions in the docker-compose. Which is keeping the default as `latest`.

@chrisjs / @sabbyanandan would you be able to review it?

**Comment by sabbyanandan** [comment]
Thank you, @tan31989. We recently discussed this in a team meeting to address this problem also. @tzolov is having a look at automatic property resolution for version-tags as part of our future release tagging.

Once when that is done, users won't have to muck around with the environment variables anymore. 

I will request @tzolov to review your PR anyway.

**Comment by tan31989** [comment]
Thanks, @sabbyanandan for the update!

**Comment by tan31989** [comment]
Hi @tzolov, do let me know if this needs further discussion for whatever you folks had planned. Appreciate your time.
