### ISSUE TITLE
Show sample in data partitioning guide

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3209]

**Comment by chrisjs** [comment]
doc ref: http://docs.spring.io/spring-cloud-dataflow/docs/2.1.0.M1/reference/htmlsingle/#arch-streams-partitioning

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-io/dataflow.spring.io/commit/f072b5ed334f9cb4ff0d427c62fd2bd93d43632d.
