### ISSUE TITLE
Add Stream Application DSL guide

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3210]

**Comment by chrisjs** [comment]
http://docs.spring.io/spring-cloud-dataflow/docs/2.1.0.M1/reference/htmlsingle/#spring-cloud-dataflow-stream-app-dsl

direct content port / screenshot could be something like:

for screenshot register an app, in screenshot just show canvas

`orderGeneratorApp: something-registered-as-app || baristaApp: something-registered-as-app || hotDrinkDeliveryApp: something-registered-as-app || coldDrinkDeliveryApp: something-registered-as-app`
