### ISSUE TITLE
Show sample in Composed Functions guide

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3213]

**Comment by chrisjs** [comment]
doc ref: https://spring.io/blog/2019/01/09/composed-function-support-in-spring-cloud-data-flow

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-io/dataflow.spring.io/commit/ee9a9e965b7531b0a43b59fee1418a8709713933.
