### ISSUE TITLE
Epic: Feature Guides for the Microsite

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3214]
Add the feature guides for:
Streams:
![image](https://user-images.githubusercontent.com/1562654/57238772-0abc1800-6fdf-11e9-8a65-e4a19c472f8f.png)
Batch:
![image](https://user-images.githubusercontent.com/1562654/57699298-4b81e580-760c-11e9-88bd-ccb96d0939d5.png)

NOTE:
Remove polyglot from the feature guides; they are already in the Recipes.

**Comment by markpollack** [comment]
polyglot will go under `./documentation/master/recipes/polyglot/` so can be removed from here.

**Comment by sabbyanandan** [comment]
All the scope of this epic is complete. I am closing it.
