### ISSUE TITLE
Discuss TL vs. CTR vs. Tasks

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#3218]
Add a document to the batch section of the Microsite that discusses the difference between 
* Task Launcher
* Task 
* Composed Task

**Comment by sabbyanandan** [comment]
The platform-specific task-launcher model is deprecated, though. I think Task and CTR options are already covered in individual sections. What do we want to cover here?

**Comment by sabbyanandan** [comment]
Even if we want to cover any of it, it would be better to drop it in the Features guide as opposed to in the Batch guide. See: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3214

**Comment by cppwfs** [comment]
Makes sense to me .
