### ISSUE TITLE
Issue while getting step counts with Oracle

### ISSUE THREAD

**Issue by ssatyan** [spring-cloud/spring-cloud-dataflow#3227]
**Description:**
While using SCDF with Oracle database for batch processing, the query used to get steps execution count fails. On checking found that the class JdbcSearchableJobExecutionDao uses "AS" for alias on table (in FIELDS_WITH_STEP_COUNT) which is syntactically an error in Oracle. 

**Release versions:**
Observed while migrating from SCDF 1.7.4 to SCDF 2.0.x

Is there any solution for this issue?

**Comment by jvalkeal** [comment]
@mminella @cppwfs Is this in schema generation or how db is used?

**Comment by jvalkeal** [comment]
Ah `JdbcSearchableJobExecutionDao` is in dataflow and not in task/batch classes.

**Comment by cppwfs** [comment]
Took the keystrokes from my keyboard :-D

**Comment by ssatyan** [comment]
Thank you for fixing, will wait for 2.1.0.GA
