### ISSUE TITLE
Refactor reference-guide to point to the doc fragments in the Microsite

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3229]
As a developer, I'd like to refactor the reference guide to remove the following sections to instead point to the Microsite sections.

- [x] Getting Started
  - [x] Local
  - [x] K8s
  - [x] CF

- [x] Stream developer guide _(remove the entire section in favor of content in the Microsite)_

- [x] Batch developer guide _(remove the entire section in favor of content in the Microsite)_

- [x] Stream Features 
![image](https://user-images.githubusercontent.com/1562654/57642496-54bb7580-756c-11e9-8b17-094715af29b3.png)
  - [x] remove polyglot from streams 
  - [x] we still want to retain the sections in the ref. guide incuding the left-nav - replace content in the body with Microsite links to specific sections

- [x] Batch Features 
![image](https://user-images.githubusercontent.com/1562654/57642544-6dc42680-756c-11e9-8a6b-5b932e3c836c.png)
  - [x] remove polyglot from batch
  - [x] we still want to retain the sections in the ref. guide including the left-nav - replace content in the body with Microsite links to specific sections

- [x] Troubleshooting

- [x] FAQ

- [x] Architecture (depends on: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3094) - moved to `Followup Issues` per comment below

**Comment by chrisjs** [comment]
* `Forcing the Upgrade of a Stream` should be ported to microsite
* nothing to do for "batch features -> deployment properties"
* nothing to do for "batch features -> data partitioning"
