### ISSUE TITLE
Create deployment/service YAML in standalone stream developer guide

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#3232]
ATM, using a bare Pod.  For comparison with what k8s resources are created with a data flow deployment, perhaps showing a service/deployment yaml is more appropriate?

This applies in to the standalone-stream-rabbitmq.md and strandalone-stream-kafka.md guides.

**Comment by sabbyanandan** [comment]
Moved to https://github.com/spring-io/dataflow.spring.io/issues/114.
