### ISSUE TITLE
Replace manually installation step of Kafka with docker based instructions.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#3233]
In standalone-stream-kafka.md

**Comment by eskuai** [comment]
Please, upgrade kafka install into non local k8s environment using a stateful deployement
I think it is a nonsense to use k8s with standalone kafka zk

**Comment by sabbyanandan** [comment]
Hi, @eskuai. What we ship out-of-the-box configuration is not meant to be used as-is in a production setting. You'd, of course, switch to use an HA Kafka cluster, and that's the expectation. The K8s deployment YAML's can be directly modified to fit your needs - we see the rest of the community using it that way. 

In fact, the Helm chart recently received a contribution to adapt to an HA Rabbit cluster (see: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3191). A similar thing is possible for Kafka as well - feel free to contribute the customization.

All the said, please consider being courteous when opening/commenting on issues. 

> I think it is a nonsense to use k8s with standalone kafka zk

The use of "nonsense" here is not cordial and it is not appreciated.

**Comment by eskuai** [comment]
So sorry, my mistake, I thoughtthat this word has not the meaning you refer.  
i am going to change it

**Comment by eskuai** [comment]
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-hs
  labels:
    app: kafka
spec:
  ports:
  - port: 9093
    name: server
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
 name: kafka-cs
 labels:
   app: kafka
spec:
 ports:
 - port: 9393
   name: client
 selector:
   app: kafka
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
spec:
  selector:
    matchLabels:
      app: kafka
  maxUnavailable: 1
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-hs
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      affinity:	
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
             - weight: 1
               podAffinityTerm:
                 labelSelector:
                    matchExpressions:
                      - key: "app"
                        operator: In
                        values: 
                        - zk
                 topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:  
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - kafka
              topologyKey: "kubernetes.io/hostname"				 		 
      terminationGracePeriodSeconds: 10000
      containers:
      - name: k8skafka
        imagePullPolicy: Always
        image: gcr.io/google_containers/kubernetes-kafka:1.0-10.2.1
        ports:
        - containerPort: 9093
          name: server
        command:
        - sh
        - -c
        - "exec kafka-server-start.sh /opt/kafka/config/server.properties --override broker.id=${HOSTNAME##*-} \
          --override listeners=PLAINTEXT://:9093 \
          --override zookeeper.connect=zk-cs.default.svc.cluster.local:2181 \
          --override logs.dir=/var/lib/kafka \
          --override auto.create.topics.enable=true \
          --override auto.leader.rebalance.enable=true \
          --override background.threads=10 \
          --override compression.type=producer \
          --override delete.topic.enable=false \
          --override leader.imbalance.check.interval.seconds=300 \
          --override leader.imbalance.per.broker.percentage=10 \
          --override log.flush.interval.messages=9223372036854775807 \
          --override log.flush.offset.checkpoint.interval.ms=60000 \
          --override log.flush.scheduler.interval.ms=9223372036854775807 \
          --override log.retention.bytes=-1 \
          --override log.retention.hours=168 \
          --override log.roll.hours=168 \
          --override log.roll.jitter.hours=0 \
          --override log.segment.bytes=1073741824 \
          --override log.segment.delete.delay.ms=60000 \
          --override message.max.bytes=1000012 \
          --override min.insync.replicas=1 \
          --override num.io.threads=8 \
          --override num.network.threads=3 \
          --override num.recovery.threads.per.data.dir=1 \
          --override num.replica.fetchers=1 \
          --override offset.metadata.max.bytes=4096 \
          --override offsets.commit.required.acks=-1 \
          --override offsets.commit.timeout.ms=5000 \
          --override offsets.load.buffer.size=5242880 \
          --override offsets.retention.check.interval.ms=600000 \
          --override offsets.retention.minutes=1440 \
          --override offsets.topic.compression.codec=0 \
          --override offsets.topic.num.partitions=50 \
          --override offsets.topic.replication.factor=3 \
          --override offsets.topic.segment.bytes=104857600 \
          --override queued.max.requests=500 \
          --override quota.consumer.default=9223372036854775807 \
          --override quota.producer.default=9223372036854775807 \
          --override replica.fetch.min.bytes=1 \
          --override replica.fetch.wait.max.ms=500 \
          --override replica.high.watermark.checkpoint.interval.ms=5000 \
          --override replica.lag.time.max.ms=10000 \
          --override replica.socket.receive.buffer.bytes=65536 \
          --override replica.socket.timeout.ms=30000 \
          --override request.timeout.ms=60000 \
          --override socket.receive.buffer.bytes=102400 \
          --override socket.request.max.bytes=104857600 \
          --override socket.send.buffer.bytes=102400 \
          --override unclean.leader.election.enable=true \
          --override zookeeper.session.timeout.ms=60000 \
          --override zookeeper.set.acl=false \
          --override broker.id.generation.enable=true \
          --override connections.max.idle.ms=600000 \
          --override controlled.shutdown.enable=true \
          --override controlled.shutdown.max.retries=3 \
          --override controlled.shutdown.retry.backoff.ms=5000 \
          --override controller.socket.timeout.ms=30000 \
          --override default.replication.factor=1 \
          --override fetch.purgatory.purge.interval.requests=1000 \
          --override group.max.session.timeout.ms=300000 \
          --override group.min.session.timeout.ms=60000 \
          --override inter.broker.protocol.version=0.10.2-IV0 \
          --override log.cleaner.backoff.ms=15000 \
          --override log.cleaner.dedupe.buffer.size=134217728 \
          --override log.cleaner.delete.retention.ms=86400000 \
          --override log.cleaner.enable=true \
          --override log.cleaner.io.buffer.load.factor=0.9 \
          --override log.cleaner.io.buffer.size=524288 \
          --override log.cleaner.io.max.bytes.per.second=1.7976931348623157E308 \
          --override log.cleaner.min.cleanable.ratio=0.5 \
          --override log.cleaner.min.compaction.lag.ms=0 \
          --override log.cleaner.threads=1 \
          --override log.cleanup.policy=delete \
          --override log.index.interval.bytes=4096 \
          --override log.index.size.max.bytes=10485760 \
          --override log.message.timestamp.difference.max.ms=9223372036854775807 \
          --override log.message.timestamp.type=CreateTime \
          --override log.preallocate=false \
          --override log.retention.check.interval.ms=300000 \
          --override max.connections.per.ip=2147483647 \
          --override num.partitions=1 \
          --override producer.purgatory.purge.interval.requests=1000 \
          --override replica.fetch.backoff.ms=1000 \
          --override replica.fetch.max.bytes=1048576 \
          --override replica.fetch.response.max.bytes=10485760 \
          --override reserved.broker.max.id=1000 "
        env:
        - name: KAFKA_HEAP_OPTS
          value : "-Djava.security.egd=file:/dev/./urandom -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xmx2G -Xms2G"
        - name: JAVA_OPTS
          value: "-Djava.security.egd=file:/dev/./urandom -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"	          
        - name: LOG_DIR
          value : "/var/lib/kafka"        
        - name: KAFKA_OPTS
          value: "-Dlogging.level=INFO"
        volumeMounts:
        - name: datadir
          mountPath: /tmp/kafka-logs
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
		  
		  		  
apiVersion: v1
kind: PersistentVolume
metadata:
 name: kafka-pv-volume-kafka-0
 labels:
   type: local
spec:
 capacity:
   storage: 10Gi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: /data01/kafka/kafka-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: kafka-pv-volume-kafka-1
 labels:
   type: local
spec:
 capacity:
   storage: 10Gi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: /data01/kafka/kafka-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: kafka-pv-volume-kafka-2
 labels:
   type: local
spec:
 capacity:
   storage: 10Gi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: /data01/kafka/kafka-2		  
   
   
   
kafka/bin/kafka-console-producer.sh     --broker-list  zk-cs.default.svc.cluster.local:2181    --topic test
kafka-0.kafka-hs.default.svc.cluster.local 

echo "test 1" | bin/kafka-console-producer.sh --broker-list kafka-hs.default.svc.cluster.local:9093 --topic test

cat file.txt | bin/kafka-console-producer.sh --broker-list kafka-hs.default.svc.cluster.local:9093 --topic test

   
   
   
apiVersion: v1
kind: PersistentVolume
metadata:
 name: kafka-zk-0
 labels:
   type: local
spec:
 capacity:
   storage: 10Gi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: /data01/zk/zk-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: kafka-zk-1
 labels:
   type: local
spec:
 capacity:
   storage: 10Gi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: /data01/zk/zk-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: kafka-zk-2
 labels:
   type: local
spec:
 capacity:
   storage: 10Gi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: /data01/zk/zk-2

**Comment by sabbyanandan** [comment]
@eskuai: Thank you for the details. While this seems legitimate, it may not be a feasible deployment model for folks who are trying to experiment with SCDF + Streams + Kafka in the laptop. For example, provisioning a 3-node cluster with 10G disk each is heavy, and it may break the Minikube and Docker for Desktop deployments. That's why it is left as an exercise for uses, who can determine what works best for their needs. 

That said, what you shared above could be a good recipe for folks who want to try with a stateful HA cluster - I think it'd be generally useful for the community. Please consider contributing to the `Recipes` page in [SCDF Microsite](https://dataflow.spring.io/docs/recipes/). The docs and code are written in Markdown (see: code [here](https://github.com/spring-io/dataflow.spring.io/tree/master/content/documentation/pages/6-recipes) and syntax [here](https://github.com/spring-io/dataflow.spring.io/blob/master/content/documentation/pages/8-markdown/1-syntax.md)).

**Comment by sabbyanandan** [comment]
Running Kafka via Docker Compose though trivial to change in the Microsite instructions [see: https://dataflow.spring.io/docs/stream-developer-guides/streams/standalone-stream-kafka/#local], it doesn't bring anything new to the table from SCSt/SCDF perspective.
