### ISSUE TITLE
Stream Application version is deployed with a URI that does not match with what was registered

### ISSUE THREAD

**Issue by allanmoso** [spring-cloud/spring-cloud-dataflow#3241]
**Description:**
When deploying a stream, 
  and a _version_ is specified for a stream application that is different from the _default version_, 
  and the  _specified version_ and the _default version_ is registered with different docker image names on their URIs,
then the application is deployed in K8s with a _docker image name_ of the _default version_ but with the _docker image tag_ of the _specified version_,
  and this will result in an image pull failure.

**For example,**
If an application has the following versions and their corresponding URIs:
`0.1.0` -  `docker:prefix1/my-source:0.1.0` 
`0.2.0` -  `docker:prefix2/my-source:0.2.0` 
_Notice the different prefixes on the docker image names_

And I deploy a stream with version `0.1.0` of `my-source`, the result is that it will deploy `prefix2/my-source:0.1.0`.
It should have deployed `prefix1/my-source:0.1.0` because that is the URI registered for that version.

It looks like Skipper is assuming that all versions of a registered application have similar URI to the default version and it's just switching the version tag.

**Release versions:**
```
{
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.0.0.RELEASE"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.0.0.RELEASE"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "2.0.0.RELEASE"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.0.0.RELEASE",
      "url": "https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/2.0.0.RELEASE/spring-cloud-dataflow-shell-2.0.0.RELEASE.jar"
    }
  },
  "featureInfo": {
    "streamsEnabled": true,
    "tasksEnabled": true,
    "schedulerEnabled": true,
    "grafanaEnabled": true
  },
  "securityInfo": {
    "isAuthenticationEnabled": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "2.0.0.RELEASE",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.0.0.RELEASE",
      "javaVersion": "1.8.0_192",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformType": "Skipper Managed",
      "springBootVersion": "2.1.2.RELEASE",
      "springVersion": "5.1.4.RELEASE"
    },
    "taskLaunchers": [
      {
        "platformSpecificInfo": {},
        "deployerImplementationVersion": "2.0.0.RELEASE",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.0.0.RELEASE",
        "javaVersion": "1.8.0_192",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformType": "Kubernetes",
        "springBootVersion": "2.1.2.RELEASE",
        "springVersion": "5.1.4.RELEASE"
      }
    ]
  },
  "grafanaInfo": {
    "url": "http://grafana:3000",
    "token": "",
    "refreshInterval": 15
  }
}
```

**Comment by sabbyanandan** [comment]
Hi, @allanmoso. It is not clear what you're trying to do with the description that you shared. It'd help if you can share the exact commands as to what you have tried so that we can relate to the problem better. Specifically, please share the registration, app-default, and the stream-deploy/update commands - basically, all the applicable commands. 

I'm also curious why you'd want to change the application name identity whereas the fixes/updates to an application can be updated just with a version bump? 

In your example, why wouldn't you want to bump the version of "same" application from `docker:prefix1/my-source:0.1.0` to `docker:prefix1/my-source:0.1.1` or `docker:prefix1/my-source:0.2.0`, etc.,?

In the current design, we expect the artifact-id (aka: name) of the application; in the Docker case, the org/image name will be retained even when multiple entries are registered in the app registry.

**Comment by allanmoso** [comment]
We found this issue somewhat because of an accident. We had an issue where we ended up tagging the docker images of our custom built stream applications with different prefixes between versions.  We didn't think it was a big deal because we we can set the docker image URI on each version of the application. Unfortunately, we found that wasn't quite true; because of this issue.

I reproduced this issue using the `spring-cloud-dataflow-shell ` tool as well. Below are the commands I used to reproduce it. Unfortunately, I can only give you fake docker image names as an example. But, hopefully you'll get the idea.

```
app register --name my --type source --uri docker:prefix1/my-source:0.1.0
app register --name my --type source --uri docker:prefix2/my-source:0.2.0
app default --id source:message-generator --version 0.2.0
stream create --name my-stream --definition 'my > :my-topic'
stream deploy --name my-stream --properties 'version.my=0.1.0'
```

`kubectl get po` will show that an `ErrImagePull` status for the created pod.

If you look at the created pod (`kubectl describe po <pod_name>`) the image is wrong. For this fake example it would be `prefix2/my-source:0.1.0`. It should have been `prefix1/my-source:0.1.0`.

You are right. Most of the time the docker image name (`prefix/artifact-id`) should not change between versions.  In fact, to get around this issue, we went ahead and just retagged our docker images.  But, I thought, that the ability to explicitly set the docker image URI exists but it is not being used by the deployer might have been a bug.

**Comment by sabbyanandan** [comment]
Thanks for the clarification, @allanmoso. There seems to be a disconnect somewhere - we will have a look.

**Comment by tzolov** [comment]
Hi @allanmoso, 

can you please clarify this statement:
> For this fake example it would be `prefix2/my-source:0.1.0`. It should have been `prefix1/my-source:0.1.0`.

Where the `prefix2/my-source:0.1.0` comes from? Shouldn't it be `prefix2/my-source:0.2.0` instead?

**Comment by jvalkeal** [comment]
@tzolov I think it depends which one is a default app. Currently that resource comes from there and then only actual version part is changed. It breaks like this even with initial installation.

**Comment by allanmoso** [comment]
@tzolov Exactly what @jvalkeal  said.  Just based on my observations when testing this, it looks like it is taking it always uses the URI from the default app version (minus the version tag) and appends the version tag of the selected version from the deploy properties.

**Comment by jvalkeal** [comment]
Right we triaged features around this and chose to throw an error if this kind of registration is attempted. While it'd be possible to fix behaviour when initial installation is done so that a correct version would be picked up, we'd still end up same issue with upgrading a app(where you can only change version in an uri). This would then be compliant with i.e. helm in kubernetes where versions works in a same way.

I'm PR'in this shortly.

**Comment by jvalkeal** [comment]
Actual behaviour in a shell would then look like:
```
dataflow:>app register --name test --uri docker:docker:prefix1/my-source:0.1.0 --type sink
Successfully registered application 'sink:test'
dataflow:>app register --name test --uri docker:docker:prefix1/my-source:0.2.0 --type sink
Successfully registered application 'sink:test'
dataflow:>app register --name test --uri docker:docker:prefix3/my-source:0.3.0 --type sink
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Existing default application [docker:docker:prefix1/my-source:0.1.0] can only differ by a version but is [docker:docker:prefix3/my-source:0.3.0]
```
