### ISSUE TITLE
local.inheritLogging doesn't work for tasks

### ISSUE THREAD

**Issue by bleurubin** [spring-cloud/spring-cloud-dataflow#3243]
**Description:**

`task launch --name test-task --properties 'deployer.*.local.inheritLogging=true'`

does not redirect logs to the localhost scdf console, they are still in /tmp.  I also tried 

`task launch --name test-task --properties 'scheduler.*.local.inheritLogging=true'`

with the same result.  Logs end up in a working directory in /tmp as if the inheritLogging property is ignored.

```
2019-05-16 18:26:48.016  INFO 23605 --- [nio-9393-exec-2] o.s.c.d.spi.local.LocalTaskLauncher      : Command to be executed: /home/dev/.sdkman/candidates/java/11.0.1-open/bin/java -jar /home/dev/.m2/repository/com/sample/test-task/0.0.1-SNAPSHOT/test-task-0.0.1-SNAPSHOT.jar --spring.cloud.task.executionid=3
2019-05-16 18:26:48.017  INFO 23605 --- [nio-9393-exec-2] o.s.c.d.spi.local.LocalTaskLauncher      : launching task test-task-96703e85-6f47-4c4b-9843-a47f4d9445d0
   Logs will be in /tmp/test-task14047027335179569477/5355754484392/test-task-96703e85-6f47-4c4b-9843-a47f4d9445d0
```

**Release versions:**
{
  "featureInfo": {
    "analyticsEnabled": true,
    "streamsEnabled": true,
    "tasksEnabled": true,
    "schedulerEnabled": false,
    "grafanaEnabled": false
  },
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.0.1.RELEASE"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.0.1.RELEASE"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "2.0.1.RELEASE"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.0.1.RELEASE",
      "url": "https:\/\/repo.spring.io\/libs-release\/org\/springframework\/cloud\/spring-cloud-dataflow-shell\/2.0.1.RELEASE\/spring-cloud-dataflow-shell-2.0.1.RELEASE.jar"
    }
  },
  "securityInfo": {
    "authenticationEnabled": false,
    "authenticated": false,
    "username": null,
    "roles": [
      
    ]
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "deployerImplementationVersion": "2.0.0.RELEASE",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.0.0.RELEASE",
      "javaVersion": "11.0.1",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformSpecificInfo": {
        "default": "local"
      },
      "platformType": "Skipper Managed",
      "springBootVersion": "2.1.3.RELEASE",
      "springVersion": "5.1.5.RELEASE"
    },
    "taskLaunchers": [
      {
        "deployerImplementationVersion": "2.0.0.RELEASE",
        "deployerName": "LocalTaskLauncher",
        "deployerSpiVersion": "2.0.0.RELEASE",
        "javaVersion": "11.0.1",
        "platformApiVersion": "Linux 4.13.0-45-generic",
        "platformClientVersion": "4.13.0-45-generic",
        "platformHostVersion": "4.13.0-45-generic",
        "platformSpecificInfo": {
          
        },
        "platformType": "Local",
        "springBootVersion": "2.1.3.RELEASE",
        "springVersion": "5.1.5.RELEASE"
      }
    ]
  },
  "grafanaInfo": {
    "url": "",
    "refreshInterval": 15
  },
  "_links": {
    "self": {
      "href": "http:\/\/localhost:9393\/about"
    }
  }
}

**Steps to reproduce:**

Launch a task using either of the below commands in the scdf shell on localhost and check the output of the scdf console.

`task launch --name test-task --properties 'deployer.*.local.inheritLogging=true'`

`task launch --name test-task --properties 'scheduler.*.local.inheritLogging=true'`

**Comment by sabbyanandan** [comment]
Hi, @bleurubin. Currently, we only support `inheritLogging` in Streams (via `LocalAppDeployer`), and for Tasks, we could implement the same functionality in `LocalTaskLauncher`. It should be straightforward to do it, though.

I've added spring-cloud/spring-cloud-deployer-local#158 for tracking. Feel free to take a stab at it if you have cycles; we could collaborate on a PR and subsequently also release a patch to include the enhancement in it.

Thanks for bringing it up!

**Comment by sabbyanandan** [comment]
Hi, @bleurubin. Quick update. We added support for Tasks now, please give it a go. The SNAPSHOT builds the fix already.

> wget https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-dataflow-server/2.2.0.BUILD-SNAPSHOT/spring-cloud-dataflow-server-2.2.0.BUILD-SNAPSHOT.jar

Also, since the ["Deployer Properties"](https://docs.spring.io/spring-cloud-dataflow/docs/2.1.0.RELEASE/reference/htmlsingle/#configuration-local-deployer) section already describes `inheritLogging ` and its purpose, we don't have to document anything for Tasks explicitly. What we have is generic enough.
