### ISSUE TITLE
Spring Cloud Dataflow - Schedule a task for local deployment

### ISSUE THREAD

**Issue by adsingh20** [spring-cloud/spring-cloud-dataflow#3249]
Based on link, there is no support for scheduling task on local deployment for spring cloud data flow. Is there a estimated date on when this feature will be available?

**Comment by sabbyanandan** [comment]
Hi, @adsingh20. The Local implementation of SCDF is recommended for development, and we do not have plans to add a scheduler implementation to support it in development mode. 

We have seen folks create a quartz-based Boot application to then invoke the SCDF's Task-launch REST API to launch the tasks (defined in SCDF) based on cron-expressions.
