### ISSUE TITLE
Version 2.1.0 .jar link is broken on manual local installation guide

### ISSUE THREAD

**Issue by bencalegari** [spring-cloud/spring-cloud-dataflow#3250]
**Description:**
[On the download page](https://dataflow.spring.io/docs/installation/local/manual/) the links provided to get the jar are broken.

I get 404 responses when I try to `wget` 
- `https://repo.spring.io/2.0.2.RELEASE/org/springframework/cloud/spring-cloud-skipper-server/2.0.2.RELEASE/spring-cloud-skipper-server-2.0.2.RELEASE.jar`
- `https://repo.spring.io/2.1.0.RELEASE/org/springframework/cloud/spring-cloud-dataflow-server/2.1.0.RELEASE/spring-cloud-dataflow-server-2.1.0.RELEASE.jar`
- `https://repo.spring.io/2.1.0.RELEASE/org/springframework/cloud/spring-cloud-dataflow-shell/2.1.0.RELEASE/spring-cloud-dataflow-shell-2.1.0.RELEASE.jar`

**Release versions:**
2.1.0.RELEASE

**Custom apps:**
N/A

**Steps to reproduce:**
Run `wget` on the above links.

**Comment by sabbyanandan** [comment]
Hi, @bencalegari. Thank you for bringing it to our attention! The `\release\` path is wrongly replaced with release-version in the URLs. I just [fixed it](https://github.com/spring-io/dataflow.spring.io/commit/e43fc5400baa620e0727fd0af685dea7a921a2b6) -  we will rolling deploy the fix soon.

In the meantime, please use the following URLs.
https://repo.spring.io/release/org/springframework/cloud/spring-cloud-dataflow-server/2.1.0.RELEASE/spring-cloud-dataflow-server-2.1.0.RELEASE.jar
https://repo.spring.io/release/org/springframework/cloud/spring-cloud-dataflow-shell/2.1.0.RELEASE/spring-cloud-dataflow-shell-2.1.0.RELEASE.jar
https://repo.spring.io/release/org/springframework/cloud/spring-cloud-skipper-server/2.0.2.RELEASE/spring-cloud-skipper-server-2.0.2.RELEASE.jar

I will leave an update when it is deployed. Closing it for now. Thanks again!

**Comment by sabbyanandan** [comment]
Hi, @bencalegari. We deployed the fix earlier this morning - please let us know if you find any other anomalies.
