### ISSUE TITLE
task execution cleanup does not delete kubernetes pods

### ISSUE THREAD

**Issue by scompmc** [spring-cloud/spring-cloud-dataflow#3259]
**Description:**
We are running the Spring Cloud Dataflow version 2.0.1.RELEASE in kubernetes cluster.  I set up a simple hello-world app in a docker image.  The task execution creates a pod that correctly prints the hello-world message and the pod moves to the completed state.  

According to the documentation, “task execution cleanup” should cleanup that completed kubernetes pod. When I tried that, the pod is NOT cleaned up. The server prints out a message from DefaultTaskDeleteService “Did not find TaskDeployment for taskname….”  “Nothing to clean up”.  

Looking at the DefaultTaskDeleteService, it appears there may be a bug in the cleanupExecution method.  It takes the execution id to get the TaskExecution. From there it calls getExternalExecutionId and names it launchId. That launchId is the name of the pod. It looks like that launchId should be used to look up the TaskDeployment as the task_deployment_id in the database is the name of the pod.  However, the task execution id is used instead.  The lookup therefore finds nothing.

If line 101 is changed from this:
TaskDeployment taskDeployment = this.taskDeploymentRepository.findByTaskDeploymentId(String.valueOf(id));

to this:
  TaskDeployment taskDeployment = this.taskDeploymentRepository.findByTaskDeploymentId(launchId);

then the TaskDeployment is found and the pod is deleted.

**Comment by sabbyanandan** [comment]
Hi, @scompmc. Thanks for the detailed write-up! It does seem like a bug. Please feel free to submit a PR with the proposed change, and we can collaborate to fix it together.

**Comment by eskuai** [comment]
I got some issues with this, and firsts, k8s pods naming for status differs from the real pod status. For example, you might expect that a pod with error got "error, evicted",  but, many times is "terminated". In pods with errors, all k8s config around it , it is not deleted, as services, relates pvc pv etc-.... is is a mesh

i recommend use crontab process to "relax" the k8s pods burden,

for example, 
0 0-23/2 * * * kubectl get pod --all-namespaces | awk '{if ($4 == "Terminating") system ("kubectl -n " $1 " delete pods " $2 " --grace-period=0 " " --force ")}' > /var/log/messages 2>&1

change for all status you need, "evicted2, etc

clean up your docker containers as you as you can

#/bin/bash
docker ps -f "status=exited" -f "status=dead"
check=$(docker ps -q  -f "status=exited" -f "status=dead")
if [ -n "$check" ]; then
        docker container rm $(docker ps -q  -f "status=exited" -f "status=dead")
fi
echo "fend.."
