### ISSUE TITLE
Is there a way to configure docker network for Spring data flow apps?

### ISSUE THREAD

**Issue by rhishirajnema** [spring-cloud/spring-cloud-dataflow#3261]
**Problem description:**
I have a spring data flow app which is deployed using docker, when I inspect the container the IP address is "172.17.0.5". Due to this my docker app is not able to connect to localhost services as they are running on different IP (10.0.x.x). I know this can be setup by using network configuration for docker but I am not sure how to do this while deploying the app in Spring data flow.

This is my current dockerFile:

```
# Base Alpine Linux based image with OpenJDK JRE only
FROM openjdk:8-jdk-alpine
# copy application WAR (with libraries inside)
ARG ARTIFACT_NAME
ADD target/${ARTIFACT_NAME}.jar /sftp-source.jar
RUN apk --update add curl

# specify default command
CMD ["/usr/bin/java", "-jar", "-Dspring.profiles.active=dataflow", "/sftp-source.jar"]

```

**Comment by sabbyanandan** [comment]
Hi, @rhishirajnema. Questions like are better discussed at StackOverflow. And, it appears you already opened one. I am closing this as a duplicate.
