### ISSUE TITLE
Relaunching the same task/job appears to append the job-parameters/args repetitively

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3275]
As a user, while attempting to relaunch the same task/job on a schedule, I notice that the job params/args are continuing to append repetitively. 

For instance, if I launch the job on 1st execution with `foo=bar` as arguments, I notice that it gets appended repetitively on every subsequent run. The 3rd run of the same job would result with `foo=bar foo=bar foo=bar` in the "Job Parameters" portion of the details page in the Dashboard. 

All that said, it could be an anomaly either in,
- how we are persisting this information (are we persisting or relying on scheduler/runtime?)
- how the UI is populating the field - may be a bug in content manipulation on the client side?

**Acceptance:**
- Verify the consistency of job param/args in all the Dashboard views.
- Perhaps also check to see how the Shell/REST-APIs are reacting to the job details `GET` operation.
- Update docs where appropriate to further clarify functionality 

Relates to https://github.com/spring-cloud/spring-cloud-scheduler-cloudfoundry/issues/44

**Comment by cppwfs** [comment]
After digging into the issue I was able to identify the scenario that creates the problem.   I created issue: https://jira.spring.io/browse/BATCH-2825 for further investigation.
