### ISSUE TITLE
Add asciidoc extension

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#328]
As a developer, I'd like to create a `asciidocs` extension for SCDF and the family, so we don't have to manually maintain relevant docs.

**Comment by ericbottard** [comment]
Spent quite some time on this already, and seems we'll need to wait for AD 1.6.x (see http://discuss.asciidoctor.org/Emitting-lists-in-AsciidoctorJ-extension-td4213.html).

I have a branch with the logic for populating the props documentation available

**Comment by sabbyanandan** [comment]
Ah - let's keep a close eye on 1.6.x release then. Thanks @ericbottard.

**Comment by ericbottard** [comment]
Replaced by old-school text generation, as we used to do in XD. Does the job, closing for now
