### ISSUE TITLE
Hello, when I use jdbc-source to extract data from log-sink, Chinese display "?", how to solve this problem?

### ISSUE THREAD

**Issue by wojiaojsjzs** [spring-cloud/spring-cloud-dataflow#3281]
Hello, when I use jdbc-source to extract data from log-sink, Chinese display "?", how to solve this problem?

**Comment by sabbyanandan** [comment]
Hi, @wojiaojsjzs. Questions like this are better suited for StackOverflow. When opening a new forum discussion in StackOverflow, please include as many details as possible. The report, as-is, is not easy to understand.
