### ISSUE TITLE
Bump kubernetes-client version to 4.1.0

### ISSUE THREAD

**Issue by rnorden** [spring-cloud/spring-cloud-dataflow#3289]
**Problem description:**

- Dataflow Server fails to start when envvar NO_PROXY is set to non-empty string and default kubernetes master URL can't be resolved.
Related build problem on fabric8-maven-plugin: https://github.com/fabric8io/fabric8-maven-plugin/issues/1389

- With spring-cloud-dataflow-parent:2.2.0.BUILD-SNAPSHOT ${kubernetes-client.version} 4.0.4 overwrites the versions declared in its dependencies.

**Solution description:**
Bump ${kubernetes-client.version} to 4.1.0 in spring-cloud-dataflow-parent to match the version used in (e.g.) spring-cloud-kubernetes-core:1.0.1.RELEASE

**Additional context:**
The default SCDF build ships with the KubernetesApplicationContextInitializer which gets picked up and executed even though I don't want to deploy to Kubernetes. Debugging this issue was pretty confusing since I didn't expect it to fail on unrelated features.

The problem has been fixed in https://github.com/fabric8io/kubernetes-client/pull/1209 and was released with https://github.com/fabric8io/kubernetes-client/releases/tag/v4.0.5

**Comment by sabbyanandan** [comment]
Hi, @rnorden. Thank you for the background and the findings! We will review it on our side from a compatibility perspective, and upgrade it then.
