### ISSUE TITLE
Problem managing streams after scdf sever/skipper version upgrades 1.7 - 2.0

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#3292]
**Description:**
Seems to be some issue managing streams that were deployed with dataflow/skipper 1.7.4/1.1.4 (pcf tile 1.3) and then managing them after upgrading to dataflow/skipper 2.0.2/2.0.1 (pcf tile 1.4)

This are the steps I took so far to investigate.
* Used postgresql via `docker run --rm   --name pg-docker -e POSTGRES_PASSWORD=docker -d -p 5432:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data  postgres` and then created a  `mydb`

* Running the versions of dataflow/skipper as indicated above on the local platform, set environment variables to point to postgres

```
export spring_datasource_url=jdbc:postgresql://localhost:5432/mydb
export spring_datasource_username=postgres
export spring_datasource_password=docker
export spring_datasource_driver_class_name="org.postgresql.Driver"
```
* deploy stream
```
dataflow:>app register --name time --type source --uri maven://org.springframework.cloud.stream.app:time-source-rabbit:1.3.1.RELEASE
Successfully registered application 'source:time'
dataflow:>app register --name log --type sink --uri maven://org.springframework.cloud.stream.app:log-sink-rabbit:1.3.1.RELEASE
Successfully registered application 'sink:log'
dataflow:>stream create --name ticktock --definition "time --server.port=9000 | log" 
```

* Upgrade scdf/skipper servers

* look at the stream def

```
dataflow:>stream list
╔═══════════╤═════════════════════════════╤══════════════════════════════════════════════════════════════════════╗
║Stream Name│      Stream Definition      │                                Status                                ║
╠═══════════╪═════════════════════════════╪══════════════════════════════════════════════════════════════════════╣
║ticktock   │time --server.port=9000 | log│The app or group is known to the system, but is not currently deployed║
╚═══════════╧═════════════════════════════╧══════════════════════════════════════════════════════════════════════╝
```
* Did not try to upgrade the stream with a different versions of time or log (which was reported as an issue coming from a kryo deserialization problem).  Stream list did not give a status, though the apps were still running on the machine.

```
dataflow:>stream destroy --name ticktock
Destroyed stream 'ticktock'
dataflow:>stream list
╔═══════════╤═════════════════╤══════╗
║Stream Name│Stream Definition│Status║
╚═══════════╧═════════════════╧══════╝
```

Will try again but this time attempt to upgrade either time or log to versions
```
sink.log=maven://org.springframework.cloud.stream.app:log-sink-rabbit:2.1.1.RELEASE
source.time=maven://org.springframework.cloud.stream.app:time-source-rabbit:2.1.0.RELEASE
```

**Comment by sabbyanandan** [comment]
This is addressed in Skipper 2.0.3.
