### ISSUE TITLE
Stop a running job

### ISSUE THREAD

**Issue by svesch84** [spring-cloud/spring-cloud-dataflow#3297]
Hi there, 

I know this topic was discussed a couple of times and I saw that there is a open feature request to stop a running SCDF task. I know that there is a stop action in the SCDF dashboard that can be invoked on a running job, which was spawn by a SCDF task. If I trigger this action I expect that my running job is canceled, or that I can gracefully stop the job in my user code. 

The job runs my own tasklet which executes a long running transaction. Now I want to cancel this transaction, but I don't have any idea how to implement that. I saw that there is a StoppableTasklet interface which offers a stop() method. Unfortunately the stop() method is never called if I implement the StoppableTasklet. 

I figured out that the problem is in the SimpleJobService of the dataflow-server-core. The implementation of the stop() method only invokes jobExecution.stop() which only sets a boolean in the background. 
So I don't have any idea how I can get the signal that my long running transaction should be stopped. I didn't find any documentation about that nor was I unable to provide an own implementation of JobService. I tried to provide a custom SimpleJobServiceFactoryBean which instantiates the SimpleJobService but neither this wasn't successful. 

Does anybody can give me a hint what I need to implement to get control in my tasklet to stop a long running job? 

Many thanks,
Sven

BTW: I use a local dataflow server in version 2.0.0.M2

**Comment by sabbyanandan** [comment]
Hi, @svesch84. Great timing! We are investigating options to come up with a design for Tasks/Jobs across all the supported platforms. With what we have learned so far, it is much complicated to implement than what we anticipated initially. It requires changes and additions to Deployer SPI and the implementations; eventually, of course also in SCDF, and then in the Dashboard, etc. 

More of those details need to be flushed out; however, we will write the epic+stories describing how we will handle the semantics for both Tasks and Jobs, which should cover what you're attempting to do, too.

All that said, I'm going to close this as a duplicate to https://github.com/spring-cloud/spring-cloud-dataflow/issues/2422 - feel free to share your use-case requirements at 2422.

Lastly, 2.0.0.M2 is a milestone release! Please switch to the latest GA release instead (2.0.3.RELEASE or 2.1.2.RELEASE).
