### ISSUE TITLE
Bump the application version in the helm-chart to 2.1.2

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3302]
As a developer, I'd like to update the helm-chart to point to the latest 2.1.2 GA release images. While we are at it, let's also update the logo to point to the right file. Current [logo-link](https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/master/spring-cloud-dataflow-docs/src/main/docbook/images/logo.png) 404s.

**Comment by chrisjs** [comment]
what is the link to the right file?

**Comment by sabbyanandan** [comment]
It appears to have been deleted from the project as and when we moved to the new UI/UX for the docs/ref. guide. The logo is in the [1.7.x branch](https://github.com/spring-cloud/spring-cloud-dataflow/blob/1.7.x/spring-cloud-dataflow-docs/src/main/docbook/images/logo.png) - we could forward port it to `master` [maybe at: [asciidoc/images](https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/spring-cloud-dataflow-docs/src/main/asciidoc/images)], and then link to it.

**Comment by sabbyanandan** [comment]
Ignore the previous comment, let's pull it from [Microsite](https://github.com/spring-io/dataflow.spring.io/blob/master/src/images/dataflow-icon.png). 💥

**Comment by chrisjs** [comment]
merged
