### ISSUE TITLE
Add "task execution stop <id>" command in the Shell

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3303]
As a developer, I'd like to amend `task execution stop <id>` command in the Shell, so I can stop either a CTR or standalone tasks that are currently running.

**Acceptance:**
- Integrate with the endpoint delivered via https://github.com/spring-cloud/spring-cloud-dataflow/issues/858 
- Unit tests added
- Docs updated

**Comment by cppwfs** [comment]
Wouldn't this be a `task execution stop <task execution id> `   since I may want to stop a specific task execution.

**Comment by sabbyanandan** [comment]
Makes sense. Updated.
