### ISSUE TITLE
Add installation of kafka for travis build

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#333]
The travis builds for PR do not currently run Kafka, so we miss some coverage.   Update travis scripts to install and run Kafka.

https://github.com/yanatan16/haskell-kafka/blob/master/.travis.yml
https://github.com/wvanbergen/kafka/blob/master/.travis.yml
https://github.com/Excelian/Mache/blob/master/config/travis-scripts/prepare-kafka.sh

show the basic approach.

**Comment by mbogoevici** [comment]
Nice! This should probably would be best a Spring Cloud Stream issue though?

**Comment by markpollack** [comment]
Crap.  Yea

**Comment by markpollack** [comment]
Actually, it applies to both...
