### ISSUE TITLE
Add support to search by "By version(s)" in the App Registry

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow#3355]
**Problem description:**
As a user i imported a differents versions of apps.
I want to search apps by version

**Solution description:**
Add into applications web page a filter named , for example, "by version", to select all apps with this values.

**Description of alternatives:**
Into the table, column "Versions", a little switch showing all versions allowed.

**Comment by eskuai** [comment]
It seems is not interesting ... closed

**Comment by sabbyanandan** [comment]
Hi, @eskuai. This can be a good enhancement. I don't see anything wrong with it; it's just about time as to when we can get to it since we are a small team. If you've cycles, please feel free to start a PR, we can collaborate with you.

**Comment by eskuai** [comment]
Hi @sabbyanandan 

I understand that you have a list of priorities into scdf 2.3.0 and more and I think it is more important to improve the "server" side ...  
I've never done a PR, actually my role is unix/aws system administrator, but i can write java, spring, i could wirte spring data repositories, etc..
if you send me more info , i will try., but client side is not my favour (i cant wrike nodejs)

**Comment by siddhantsorann** [comment]
Hey, @sabbyanandan I'd like to pick this ticket up if this enhancement is still needed.

**Comment by siddhantsorann** [comment]
Also, since we have multiple filters here have we thought about using predicates for this case?

**Comment by siddhantsorann** [comment]
Since there are multiple filters and AppRegistration is a JPA entity here is how I think we can implement this without having too many if-else conditions - 
```
public Page<AppRegistration> findAllByTypeAndNameIsLikeAndVersionAndDefaultVersion(ApplicationType type,
      String name, String version, boolean defaultVersion, Pageable pageable) {
    CriteriaBuilder cb = entityManager.getCriteriaBuilder();
    CriteriaQuery<AppRegistration> cq = cb.createQuery(AppRegistration.class);
    Root<AppRegistration> appRegistrationRoot = cq.from(AppRegistration.class);
    final List<Predicate> predicates = new ArrayList<>();
    if (type != null) {
      predicates.add(cb.equal(appRegistrationRoot.get("type"), type));
    }
    if (StringUtils.hasText(name)) {
      predicates.add(cb.like(cb.lower(appRegistrationRoot.get("name")), name.toLowerCase()));
    }
    if (StringUtils.hasText(version)) {
      predicates.add(cb.equal(cb.lower(appRegistrationRoot.get("version")), version.toLowerCase()));
    }
    if (defaultVersion) {
      predicates.add(cb.isTrue(appRegistrationRoot.get("defaultVersion")));
    }
    cq.where(predicates.toArray(new Predicate[0]));
    cq.orderBy(QueryUtils.toOrders(pageable.getSort(), appRegistrationRoot, cb));
    TypedQuery<AppRegistration> query = entityManager.createQuery(cq);
    query.setFirstResult((int) pageable.getOffset());
    query.setMaxResults(pageable.getPageSize());
    final List<AppRegistration> resultList = query.getResultList();
    return new PageImpl<>(resultList, pageable, getTotalCount(cb, predicates.toArray(new Predicate[0])));
  }
```

**Comment by sabbyanandan** [comment]
This seems like a pretty straightforward case of including extra search criteria. I am in favor of enhancing this indeed. 

Let's please submit a PR with the proposal. cc: @tzolov

**Comment by sabbyanandan** [comment]
Addressed via: https://github.com/spring-cloud/spring-cloud-dataflow/pull/4395.
