### ISSUE TITLE
Revise the use of `queue:` and `topic:` prefixes for named channels

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-dataflow#336]
Since we do not support the distinction between queues and topics anymore (see https://github.com/spring-cloud/spring-cloud-stream/issues/263 and related), the prefixes do not serve any real purpose anymore. However, we might want to keep them (or at least `topic:` to be more exact) for backwards compatibility with Spring XD within the DSL.

**Comment by markfisher** [comment]
We should also add a `--group` option when using the channel syntax in the DSL, e.g.:

```
stream create example --definition "foo --group=bar > log"
```

Then if no group is provided, we could use the stream name as a default?

**Comment by sabbyanandan** [comment]
This is related to spring-cloud/spring-cloud-dataflow#314

**Comment by mbogoevici** [comment]
Obsolete now, after https://github.com/spring-cloud/spring-cloud-dataflow/issues/314 and https://github.com/spring-cloud/spring-cloud-dataflow/pull/370
