### ISSUE TITLE
Add new Task/Batch features into DB ATs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3366]
- [ ] Task execution deletes
- [ ] Task execution stop
- [ ] Task search

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-dataflow-acceptance-tests #272](https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/issues/272) via [**ZenHub**](https://www.zenhub.com/)

**Comment by dturanski** [comment]
Currently task executions are cleaned up after every task test. This uses the REST API as DataFlowTemplate does not currently support this operation.  So we can maybe check off `clean`
