### ISSUE TITLE
Wrong message when bulk importing apps from Shell

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3368]
As a user, while bulk registering stream and task applications back-to-back, I see the return message with wrong count for Tasks.

**Commands:**
```
dataflow:>app import --uri https://dataflow.spring.io/rabbitmq-maven-latest
Successfully registered 66 applications from [source.sftp, source.mqtt.metadata, sink.mqtt.metadata, source.file.metadata, processor.grpc.metadata, processor.tcp-client, so
....
....
....
....
....

dataflow:>app import https://dataflow.spring.io/task-maven-latest
Error when registering applications from https://dataflow.spring.io/task-maven-latest: 404 Not Found

....
....

dataflow:>app import https://dataflow.spring.io/task-maven-latest
Successfully registered 69 applications from [task.composed-task-runner, task.timestamp.metadata, task.composed-task-runner.metadata, task.timestamp-batch.metadata, task.timestamp-batch, task.timestamp]
```

**What is wrong?**

> Successfully registered 69 applications from [task.composed-task-runner, task.timestamp.metadata, task.composed-task-runner.metadata, task.timestamp-batch.metadata, task.timestamp-batch, task.timestamp]

**Notes:**
Also, I intermittently get the `404 Not Found` - perhaps something to do with SCDF or Microsite running in PWS/AWS?

**Comment by jvalkeal** [comment]
Think 404's are just issues with artifactory as it time to time fails like that.
