### ISSUE TITLE
Can the Data Flow server be configured running alone? 

### ISSUE THREAD

**Issue by t873529** [spring-cloud/spring-cloud-dataflow#3378]
I see the Spring Cloud Data Flow [local installation manual][1], Spring Cloud Data Flow server is started after Skipper server started. I tried shutdown the Skipper, and refresh the Data Flow Dashboard UI in browser then I can see Data Flow server begin to throw exceptions, pasted below. 

My question is : Can the Data Flow server be configured running alone?  and How?

By far I only have spring batch job application running in PR. what I want is a dashboard UI which our team can see Job/Task execution history, like Spring Batch Admin does. Spring Batch Admin is deprecated. I want the replacement - Data Flow Server. I don't have Streams application yet. I don't need Skipper function. 

Thanks,
Chen

  [1]: https://dataflow.spring.io/docs/installation/local/manual/

--
2019-07-24 21:48:22.889  WARN 12384 --- [nio-9393-exec-4] s.c.d.s.controller.AboutController: **Skipper Server is not accessible**
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:7577/api/about": Connect to localhost:7577 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] **failed: Connection refused**: connect; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:7577 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
---

**Comment by ilayaperumalg** [comment]
Hi @t873529 ,

> Can the Data Flow server be configured running alone? and How?

Yes, the Spring Cloud Data Flow server can be configured to run alone to manage task/batch applications. All you need is to specify the task platform configurations.

As you pointed out, the Skipper server is only needed for managing the streaming applications and you can ignore the above stack trace as it tries to connect to Skipper when finding information about the SCDF server.

**Comment by ilayaperumalg** [comment]
Since you are not going to use streams, you can disable streams configuration by setting the property `spring.cloud.dataflow.features.streams-enabled` to `false` when starting the SCDF server:

For instance,
```
java -jar spring-cloud-dataflow-server/target/spring-cloud-dataflow-server-2.2.0.BUILD-SNAPSHOT.jar --spring.cloud.dataflow.features.streams-enabled=false
```

This way, you won't run into the above exception as well.

**Comment by t873529** [comment]
Hi Ilayaperumal,
It works!   Thanks very much for your quick response. 
Chen.

**Comment by ilayaperumalg** [comment]
@t873529 Thanks for trying out Spring Cloud Data Flow! Feel free to connect on any feedback/questions and contributions.
