### ISSUE TITLE
Cannot stop a remote partitioned job on the platform where it was launched 

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#3382]
In this scenario a user launches a Spring Cloud Task outside of SCDF and they populate the external-execution-id with the correct platform execution id  ( Spring Batch Partition app).  When the user attempts to stop a task execution that was launched outside of dataflow and has an external-execution-id it will fail with a null pointer exception when attempting to get the platform name from the taskDeploymentRepository.   This because the external deployer or external execution does not insert the entry into the taskDeploymentRepository.

**Comment by sabbyanandan** [comment]
> This because the external deployer or external execution does not insert the entry into the taskDeploymentRepository.

A similar symptom seems to surface in #3403.
