### ISSUE TITLE
Cannot delete task/app/... from the dashboard with ROLE_DESTROY - Missing button/links

### ISSUE THREAD

**Issue by Tetradeus** [spring-cloud/spring-cloud-dataflow#3384]
**Description:**
Delete links/buttons are missing from the dashboard when security is enabled even with role ROLE_DESTROY. 

**Release versions:**
2.1.2

**Screenshots:**

<img width="283" alt="image" src="https://user-images.githubusercontent.com/1665874/61959095-edd22800-afc2-11e9-857b-18cf734efc6f.png">

**Comment by sabbyanandan** [comment]
This might be a UI bug, so I will move it there, and we can review it.

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-dataflow-ui #1249](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1249) via [**ZenHub**](https://www.zenhub.com/)
