### ISSUE TITLE
Specific task deployer/scheduler properties via configuration

### ISSUE THREAD

**Issue by Tetradeus** [spring-cloud/spring-cloud-dataflow#3385]
**Problem description:**
Is is possible to set deployer and scheduler properties for a specific task directly in the server configuration properties in order to not add it every time we launch a task manually ?

example: 
```
deployer.[TASK_NAME].kubernetes.default.environmentVariable=SPRING_PROFILES_ACTIVE=dev
```

I am not sure to clearly find it in the documentation.

Thanks,

**Comment by sabbyanandan** [comment]
Hi, @Tetradeus. Questions like this are better to be discussed in either StackOverflow or Gitter. We use GitHub for bugs and feature requests.

**Comment by Tetradeus** [comment]
I agree with you but it is possibly a feature request it is just that I don't know if it already exists or not ;)
