### ISSUE TITLE
CannotSerializeTransactionException when launching multiple composed tasks through SCDF API

### ISSUE THREAD

**Issue by mkandefer** [spring-cloud/spring-cloud-dataflow#3386]
**Description:**

We have a service that can launch tasks through the SCDF REST API, when launching two or more composed-tasks  (roughly) simultaneously the composed-task-runner application (version 2.0.2.RELEASE) will report a CannotSerializeTransactionException. We are running SCDF Server 2.1.0 in local mode with postgres as the database for definitions. 

The task definitions launched are not the same. We are launching using a post to the /tasks/executions end point with the following values:

name: _name-of-composed-task_
arguments: --increment-instance-enabled=true --random=_some-random-value_

The _name-of-composed-task_ is different for the two composed-tasks being launched roughly simultaneously. Our use case is that on file drop we launch different pipelines based on the directory the file drop occurs. Sometimes the files may land in two or more directories roughly at the same time and thus two or more different composed-task pipelines are launched. 

[stacktrace.txt](https://github.com/spring-cloud/spring-cloud-dataflow/files/3436867/stacktrace.txt)

**Comment by sabbyanandan** [comment]
Hi, @mkandefer. Though we have some information that we could use to reproduce the reported issue; however, I'd appreciate if you can update the description with more details including the RESTful endpoint(s) that you're invoking, and how. The version of CTR in use is a critical piece of information.

A reproducible sample showcase would be helpful, as well.

Perhaps also include some background of your use-case, so we can better relate to why you'd want to launch the same Task "concurrently".

**Comment by mkandefer** [comment]
Updated with more details.

**Comment by cppwfs** [comment]
@mkandefer Are the child apps being launched by the CTR also Spring Batch Apps?

**Comment by cppwfs** [comment]
Also @mkandefer what version of Postgres are you running along with what driver/version are you using.   Haven't been able to reproduce yet.

**Comment by mkandefer** [comment]
The child apps being launched are spring boot task apps using @EnableTask. They don't use any batch related annotations. 

Postgres Version is 10.4

**Comment by cppwfs** [comment]
Hello @mkandefer,
Still can't seem to get it to occur. 
1)  I installed Postgres 10.10 image on docker (closest one available on dockerhub.
2) Created the following task definition: `task create bctr --definition "1: timestamp && 2: timestamp"`
3) Launched the task definition with the following script
```
curl 'http://localhost:9393/tasks/executions' -i -X POST \
    -d 'name=bctr&arguments=--increment-instance-enabled%3Dtrue+foo%3Dbaa' &
curl 'http://localhost:9393/tasks/executions' -i -X POST \
    -d 'name=bctr&arguments=--increment-instance-enabled%3Dtrue+foo%3Dbaz' &
curl 'http://localhost:9393/tasks/executions' -i -X POST \
    -d 'name=bctr&arguments=--increment-instance-enabled%3Dtrue+foo%3Dbag' &
curl 'http://localhost:9393/tasks/executions' -i -X POST \
    -d 'name=bctr&arguments=--increment-instance-enabled%3Dtrue+foo%3Dbal' &
```
What is your test scenario can you provide the following?
* Task Defintion
* Scripts to reproduce the problem

**Comment by cppwfs** [comment]
Closing this story here and moving it to ComposedTaskRunner.   New issue # is https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/93
