### ISSUE TITLE
Not able to create stream

### ISSUE THREAD

**Issue by goyalnitin784** [spring-cloud/spring-cloud-dataflow#3401]
I am using spring cloud data flow with Kubernetes.Using 1.2 version of spring cloud data-flow.

While making a stream I am getting below exceptions:

dataflow:>stream destroy --name teststream
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: I/O error on GET request for "http://localhost:7577/api": Connect to localhost:7577 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused); nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:7577 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)

**Comment by sabbyanandan** [comment]
Hi, @goyalnitin784. Oddly, you're on a _very-old_ release of SCDF. The 1.2 version is >1yr old, and it is not being maintained actively. The latest on 1.x is at .x, and that version is strictly only also on maintenance mode. Please switch to the latest 2.x GA release.

All that said, you'd see the listed error if and when Skipper-server is not running on the expected host/port. Perhaps you didn't start the Skipper-server locally. Make sure you follow the [getting-started](https://dataflow.spring.io/docs/installation/local/manual/) guide in entirety. Alternatively, you can use the Docker Compose to provision all the related components automatically.

**Comment by xerZV** [comment]
I am a problem here with `spring-cloud-dataflow-server-2.5.1.RELEASE.jar` too.
When I try to access `Streams` from the dataflow dashboard it throws:
```
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:7577/api/release/states": Connect to localhost:7577 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:7577 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
```

Running locally on Windows OS :
```shell script
java -jar spring-cloud-dataflow-server-2.5.1.RELEASE.jar
```
