### ISSUE TITLE
Revisit RootControllerTests

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#3412]
`RootControllerTests` broke during boot/hateoas upgrades. Looking original test class it doesn't even test anything what makes sense. Output from a root what only test is asserting is not even something what a real server outputs.

**Comment by ilayaperumalg** [comment]
We can just assert the response from the REST controller's `/` path and I think that would suffice in this test class. At least we know if there are any changes in the RootController, this test would require changes as well.
