### ISSUE TITLE
Hyperlinks not working

### ISSUE THREAD

**Issue by rakrvptl** [spring-cloud/spring-cloud-dataflow#3415]
Hi, 
I am not able to open any link on this page? is this still a work in progress?
https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/api-guide.adoc

I get 404 for most of the links I clicked thru. 

Sample Link 
https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/%7Bsnippets%7D/about-documentation/get-meta-information/http-response.adoc

**Comment by rakrvptl** [comment]
As well as on 
https://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#api-guide-resources-app-registry-post-request-structure

**Comment by ilayaperumalg** [comment]
Hi,

Thanks for trying out Spring Cloud Data Flow. 

The files you see above in the Github repository are the markdown files used by the `spring-cloud-dataflow-docs` module to generate the SCDF documentation. The links in these markdown files are replaced as the documentation is generated. Please see the generated documentation [here](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide) for the REST API guide.

Thanks!

**Comment by rakrvptl** [comment]
Thanks for the response. It could just be my browser issue, i am not able to see them properly in chrome but works fine in IE. 

I am good with this request and can be closed. Thanks for quick turn around.
