### ISSUE TITLE
Provide Access Token to the CTR

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#3418]
- Provide the OAuth Access Token as a command-line argument to the CTR (if available)
- Move OAuth2AccessTokenProvidingClientHttpRequestInterceptor to Common Security
  - This will allow for re-use of this class in the Composed Task Runner

Depends on:

https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/62
https://github.com/spring-cloud/spring-cloud-common-security-config/issues/58

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-dataflow/commit/42f5b17b3e6ff4cf08ca1266e7f6497c843986db.
