### ISSUE TITLE
RESTFul API Docs not being generated for Reference guide

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#3421]
Starting at build https://build.spring.io/browse/SCD-BMASTER-3165 the RESTFUL-API docs stopped producing results.

You can add 
```
		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
			<version>5.2.0</version>
			<scope>test</scope>
		</dependency>
```
to the spring-cloud-dataflow-classic-docs as a workaround.

**Comment by jvalkeal** [comment]
Not sure how this would make any difference as `junit-vintage-engine.5.5.1.jar` is already in deps for that subproject.

**Comment by jvalkeal** [comment]
Right this might be issue with maven surefire plugin:
```
Aug 09, 2019 8:17:05 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
java.lang.NoSuchMethodError: org.junit.platform.commons.util.ReflectionUtils.tryToReadFieldValue(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/Object;)Lorg/junit/platform/commons/function/Try;
	at org.junit.vintage.engine.support.UniqueIdReader.apply(UniqueIdReader.java:47)
```
We have correctly aligned versions from junit5 bom but I think surefire still pulls older junit5 classes.
