### ISSUE TITLE
Add description to stream and task definitions with CLI

### ISSUE THREAD

**Issue by sylank** [spring-cloud/spring-cloud-dataflow#3425]
**Problem description:**
As stream creator, I should be able to provide a description for a stream & task definition with a CLI command.

There is a backend related PR: #3388

**Comment by sylank** [comment]
This issue is a duplication #3430

**Comment by sabbyanandan** [comment]
Janne might have overlooked this, sorry about that. Thanks, @sylank! If you have cycles, please feel free to try out #3430.

**Comment by sylank** [comment]
@sabbyanandan It takes nothing :). I have created some shell specific implementations, but I was waiting for the PR. I will make a shell specific PR in next weeks :)
