### ISSUE TITLE
Merge K8s-deployer and K8s-schedulers

### ISSUE THREAD

**Issue by Tetradeus** [spring-cloud/spring-cloud-dataflow#3445]
**Problem description:**
Version: 2.2.0.RELEASE
Kubernetes Scheduler properties are missing a lot of options offered by Kubernetes Deployer properties (secretsKeyRef, tolerations, nodeSelector, ...). Everytime one evolves, changes need to be duplicated (and tested) on the other one. 

**Solution description:**
Merge both of them so properties must be the same (inherits the same parent ?) as well as the ContainerCreator and ContainerFactory (that should be a bean overridable ?)

**Comment by sabbyanandan** [comment]
Hi, @Tetradeus. Please refer to https://github.com/spring-cloud/spring-cloud-deployer/issues/310 - we have recently already merged them. As an FYI, the following chores were involved in the migration.

![image](https://user-images.githubusercontent.com/1562654/63288943-c47b8380-c272-11e9-95d3-b79c4ac83ab0.png)

The SCDF 2.3 BS version should give you a unified experience. 

This is a significant effort, so feel free take it for a spin and help us with any issues that you may find.

**Comment by Tetradeus** [comment]
@sabbyanandan great news! I will give it a try. Thanks.
