### ISSUE TITLE
Make ArtifactRegistryPopulator flexible for `admin` properties

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#346]
As a developer, I'd like to update `ArtifactRegistryPopulator` to use a resolver strategy that takes into account `admin` properties such as the default `repoUrl` and OOTB available application version numbers.

**Acceptance:**
- I'm able to pass binder type, maven repo and desired application version as overridable options

**Comment by ericbottard** [comment]
FYI, the maven repo information is irrelevant here. A registration only knows about artifact coordinates (lookup / download is not attempted at that point)

**Comment by sabbyanandan** [comment]
This is already addressed.
