### ISSUE TITLE
document ddl

### ISSUE THREAD

**Issue by imod** [spring-cloud/spring-cloud-dataflow#3460]
**Problem description:**
I'm trying to create a [custom build of scdf-server](https://github.com/spring-io/dataflow.spring.io/issues/119) and would like to deploy it to our cloudfoundry installation. Unfortunate the only DB available is a MariaDB-10.1.38. Although MariaDB is mostly compatible with MySQL, I get the following exception during startup:

```
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: MariaDB 10.1
	at org.flywaydb.core.internal.jdbc.DatabaseType.fromDatabaseProductNameAndPostgreSQLVersion(DatabaseType.java:168) ~[flyway-core-5.2.4.jar:na]
	at org.flywaydb.core.internal.jdbc.DatabaseType.fromJdbcConnection(DatabaseType.java:117) ~[flyway-core-5.2.4.jar:na]
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:90) ~[flyway-core-5.2.4.jar:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:1670) ~[flyway-core-5.2.4.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356) ~[flyway-core-5.2.4.jar:na]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:65) ~[spring-boot-autoconfigure-2.1.7.RELEASE.jar:2.1.7.RELEASE]

```

**Solution description:**
To get around this issue, I would like to create the tables by myself - but I need to know which tables and other db objects need to be created.

**Additional context:**
To get around the issue for now, I defined `spring.jpa.hibernate.ddl-auto=update` and have now a set of DB objects. I now use these objects as a reference to create the same definitions in all environments and also disable `FlywayAutoConfiguration.class`.

**Comment by jvalkeal** [comment]
I believe workaround for this error(probably the `useMysqlMetadata=true` trick) is documented here https://docs.spring.io/spring-cloud-dataflow/docs/2.2.0.RELEASE/reference/htmlsingle/#_mariadb. This story around mysql/mariadb is relatively complex as they are now separate db's and you really can't expect things to be compatible. It probably takes a year or so for everything around whole ecosystem to be ready for full separation of these two db's.

What comes for a DDL's, we currently don't have any. We knew(when we took full schema route with flyway) that this question probably pops up. We currently have acceptance tests for postgres, mysql, maria, sqlserver, oracle and db2, and I've been thinking if we should allocate some time to extract DDL structure out from a schema created by flyway.

This is something what you could do now assuming that you get scdf running with your mariadb version. AFAIK, if we choose to do that for all DB's, we also need to export structure out from a real DB.

**Comment by imod** [comment]
thanks @jvalkeal `useMysqlMetadata` got me running and I now have SCDF, Skipper, Task and Batch tables created. But now looking at all the tables that have been created for infrastructure stuff only, I count **40 tables** - the naming is inconsistent and will give our DBA a hard time to understand what belongs to what. And unfortunate I'm not even yet able to deploy this stuff because all the tables will be created with the wrong row_format and therefore some of the indices will fail to be created (default for `innodb_default_row_format` on our instances is not DYNAMIC, but COMPACT).
All I really wanted was to move from our old spring batch infrastructure to the new UI of SCDF because the old spring batch admin is not supported anymore...

**Comment by jvalkeal** [comment]
@imod We don't enforce any specific engine or its internal settings(what potentially could be set via sql). Wouldn't you then need to enforce those settings globally in a database instance?

**Comment by imod** [comment]
@jvalkeal it is possible to define the row format in the DDL. 
If the database does not have `innodb_default_row_format` set to `DYNAMIC`, then I must create the table myself as 

```
CREATE TABLE `audit_records` (
  `id` bigint(20) NOT NULL,
  `audit_action` bigint(20) DEFAULT NULL,
  `audit_data` longtext,
  `audit_operation` bigint(20) DEFAULT NULL,
  `correlation_id` varchar(255),
  `created_by` varchar(255),
  `created_on` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ROW_FORMAT=DYNAMIC;
```

On our environment this is the case, `innodb_default_row_format` is set to `COMPACT`, therefore I do need to create the tables myself with the correct `ROW_FORMAT` defined. If I don't do this, then the creation of the indices fails with `Index column size too large. The maximum column size is 767 bytes.`. The whole problem is also documented here: https://community.pivotal.io/s/article/Apps-are-down-due-to-the-Maximum-Column-Size-is-767-bytes-Constraint-in-MySQL 

Anyway, the whole thing comes down to the fact that there are situations where SCDF users need to create the tables by them self. :)

**Comment by jvalkeal** [comment]
I know but what I meant is that we can't be opinionated of those types as we can't force feed any settings. If you need that setting, shouldn't it get enforced on a DB level so that row format would be dynamic if you don't define it in ddl?

**Comment by imod** [comment]
@jvalkeal in general I agree, but these settings are defined for the whole galera cluster running many many DB instances as a service. The operator has chosen some settings and these might or might not work for a specific project. 
I also fully agree that you can't set all possible options, therefore I come back to the point where one only needs a proper documented DDL which he then can adapt to his needs.
