### ISSUE TITLE
/management/logfile endpoint returns 500 http code

### ISSUE THREAD

**Issue by Manokethan** [spring-cloud/spring-cloud-dataflow#3479]
**Description:**
while attempting to access to /management/logfile I get a 500 with:
[{"logref":"HttpMediaTypeNotAcceptableException","message":"Could not find acceptable representation","links":[]}]

**Release versions:**
2.2.X

**Steps to reproduce:**
Open in a browser http://{IP}:9393//management/logfile

**Comment by ilayaperumalg** [comment]
Hi @Manokethan , Thanks for reporting. This looks like a bug. We'll have an update on this soon.
