### ISSUE TITLE
Add a BOM

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-dataflow#348]
Spring Cloud Data Flow doesn't (at the moment) provide any dependency management for users building on top of its code base. The pattern adopted (recently) in the other Spring Cloud projects is recommended, where there is a separate spring-cloud-dataflow-dependencies project at the top level and the parent uses it as an import.

**Comment by joshlong** [comment]
as you raised earlier, wouldn't we need to ultimately also manage the other Server impls as well? So, would this live in the Spring Cloud Data Flow project or should it be a separate repo?

**Comment by dsyer** [comment]
It would be nice for users to have a place to manage all dataflow dependencies. We can decide how to structure that later (part of Spring Cloud general release train, or a separate Data Flow release train, or both). For now, we only need `spring-cloud-dataflow-dependencies` to get this project into line with the others.
