### ISSUE TITLE
Rename or merge spring-cloud-dataflow-admin-starter

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-dataflow#349]
I noticed we have `spring-cloud-dataflow-admin-starter` and `spring-cloud-starter-dataflow-server-local`. I think the former needs to be renamed and/or merged into one of the other libraries. N.B. using "starter" in a project name is discouraged by the Spring Boot naming conventions, unless it's actually a starter (it's obviously a bit confusing as shown by this example).

**Comment by markfisher** [comment]
We are planning to do this as soon as some existing PRs are merged (so we don't generate too many conflicts for those). The current idea is to rename to `spring-cloud-dataflow-server-core` as part of a general trend to move away from "admin" in favor of "server".

**Comment by dsyer** [comment]
OK, I figured as much and vaguely remember you saying this was all WIP. Just a marker for the follow up I guess. We are still trying to get the initializr changes in and naming is holding it up really.
