### ISSUE TITLE
Dependency management should use boms not parents

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-dataflow#350]
In the top level POM we are using spring-boot-starter-parent and spring-cloud-starter-parent as BOMs. This may cause issues if they diverge in their shared dependencies (e.g. Spring FW versions etc.). It is recommended to use the `spring-boot-dependencies` and `spring-cloud-dependencies` for dependency management. The choice of the parent POM is also significant though, so #348 is more important for users.

**Comment by dsyer** [comment]
See #359 for a fix (and general hygeine update).

**Comment by sabbyanandan** [comment]
This was addressed a long time ago; closing it now.
