### ISSUE TITLE
Deleting Task Definition Stops Executing Tasks

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#3504]
**Problem description:**
When a task definition is destroyed on the local and Cloud Foundry platforms, any launched tasks are left executing till they are complete.   However any launched tasks on the K8's platform will be terminated when the task definition is deleted.   This is because all pods associated with the  task definition are deleted, including the ones that are still executing.

Do we need to document this difference or is this a bug?

**Comment by sabbyanandan** [comment]
This is not applicable anymore.
