### ISSUE TITLE
Update springcloud/spring-cloud-dataflow-server docker image to Java 11

### ISSUE THREAD

**Issue by gdubya** [spring-cloud/spring-cloud-dataflow#3507]
The version of Java used by the spring-cloud-dataflow-server docker image appears to be Java 8.

Is this a restriction imposed by the Pivotal platform, or can this be upgraded to Java 11?

**Comment by markpollack** [comment]
The policy is basically - build on bionic.

https://hub.docker.com/r/springcloud/openjdk/dockerfile

I'll have to find out what a minimal docker file for openjdk 11 looks like, hopefully it is just a matter of changing the version of the openjdk .tar.gz file that is downloaded.

**Comment by markpollack** [comment]
Using https://java-buildpack.cloudfoundry.org/openjdk-jdk/bionic/x86_64/openjdk-jdk-11.0.4_11-bionic.tar.gz in that docker file should be all you need if you want to give it a try.

**Comment by gdubya** [comment]
Thanks @markpollack ! Yeah, we solved it internally by replacing the /opt/openjdk directory with the one from https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz.  I created this issue in case others are also interested in having the baseline JDK version for the springcloud image upgraded to JDK 11 since 8 is EOL.

**Comment by sabbyanandan** [comment]
@gdubya: We haven't run through the compatibility tests on our end; besides that, we cannot switch to a major Java version in a point release. The Docker images that we ship are tagged against a particular release version - currently, we are on a minor release line (i.e., v2.3.0). 

I will keep this issue in the backlog and use it as the placeholder for our test harness for the next release. In the meantime, feel free to upgrade Java locally on the disk files.

**Comment by CheeseE** [comment]
Is there anyone who recompiled and has a docker image for java 11?

**Comment by gdubya** [comment]
@CheeseE there's no need to recompile. Just create your own Dockerfile with the newer JDK.

See https://gist.github.com/gdubya/eec3517ac18ce70538acc3cfa00e8a5a

**Comment by sabbyanandan** [comment]
We have several incoming changes that pertain to SCDF/Skipper being compatible with JDK11 (but, still compiled against JDK8). Likewise, the OOTB apps are verified to be compatible with JDK11, as well.

**Comment by dturanski** [comment]
I'm going to close this.  We have one outstanding task to set up CI for the docker image.
