### ISSUE TITLE
Enhance 'task execution status' results in Shell with task manifest values

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3508]
As a continuation from https://github.com/spring-cloud/spring-cloud-dataflow/issues/3406, we would want to enhance the `task execution --id ..` results to also include the extra details including properties, params, args, etc.

Depends on https://github.com/spring-cloud/spring-cloud-dataflow/issues/3498.

**Comment by markpollack** [comment]
The shell is currently missing the equivalent of `job execution display --id` for tasks.  So this story will be to 

1) implement a new shell command `task execution display --id` to return the same information as in the dashboard (e.g. http://localhost:9393/dashboard/#/tasks/executions/2)
2) Add to the the table information stored in the manifest relating 1) application properties 2) deployment properties and 3) resource url.
