### ISSUE TITLE
Support flyway 6.x

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#3513]
Boot now supports flyway 6 which should have better features for mysql/maria issues.

Note:
Flyway 6.x removes support for MySQL 5.6. Let's double check what's supported in PCF MySQL, and decide whether or not we can upgrade to 6.x already.

**Comment by jvalkeal** [comment]
At least it looks like flyway 6 will bail out if mysql is lower than 5.7. Not sure if with CF we'd still need to support 5.6.

**Comment by sabbyanandan** [comment]
The scope of what we wanted to accomplish in 2.5 is complete.
