### ISSUE TITLE
Too many redirects after oauth authorize call

### ISSUE THREAD

**Issue by historus** [spring-cloud/spring-cloud-dataflow#3514]
**Description:**
After the call to SECURITY_OAUTH2_CLIENT_USER_AUTHORIZATION_URI it redirects properly to https://scdf-server.domain.com/login?code=\<code\>&state=dA8C5p. However, afterwards this URL redirects to https://scdf-server.domain.com/login various times and results in an error (too many redirects.)

**Release versions:**
Taken from authentication disabled
<code>
{
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.2.1.RELEASE"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.2.1.RELEASE"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "2.2.2.RELEASE"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.2.1.RELEASE",
      "url": "https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/2.2.1.RELEASE/spring-cloud-dataflow-shell-2.2.1.RELEASE.jar"
    }
  },
  "featureInfo": {
    "streamsEnabled": true,
    "tasksEnabled": true,
    "schedulesEnabled": true,
    "grafanaEnabled": true
  },
  "securityInfo": {
    "isAuthenticationEnabled": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "2.1.2.RELEASE",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.1.2.RELEASE",
      "javaVersion": "1.8.0_192",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformType": "Skipper Managed",
      "springBootVersion": "2.1.6.RELEASE",
      "springVersion": "5.1.8.RELEASE"
    },
    "taskLaunchers": [
      {
        "platformSpecificInfo": {},
        "deployerImplementationVersion": "2.0.5.RELEASE",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.0.4.RELEASE",
        "javaVersion": "1.8.0_192",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformType": "Kubernetes",
        "springBootVersion": "2.1.6.RELEASE",
        "springVersion": "5.1.8.RELEASE"
      }
    ]
  }
}
</code>

**Steps to reproduce:**
Configure oauth backend and try to login to the dashboard. Trying the curl commands with basic auth or bearer token result in 401.
<code>
        - name: SECURITY_OAUTH2_CLIENT_CLIENT_ID
          value: 'app-ingest-oauth-1'
        - name: SECURITY_OAUTH2_CLIENT_CLIENT_SECRET
          value: "$(APP_IMS_OAUTH_CLIENT_SECRET)"
        - name: SECURITY_OAUTH2_CLIENT_USER_AUTHORIZATION_URI
          value: 'https://oauth-backend.login.com/oauth/authorize/v1'
        - name: SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI
          value: 'https://oauth-backend.login.com/oauth/token/v1'
        - name: SECURITY_OAUTH2_RESOURCE_USER_INFO_URI
          value: 'https://oauth-backend.login.com/oauth/profile/v1'
        - name: SECURITY_OAUTH2_RESOURCE_TOKEN_INFO_URI
          value: 'https://oauth-backend.login.com/oauth/validate_token/v1'
</code>
Is there anything I can help with troubleshooting the issue?

[trace.har.zip](https://github.com/spring-cloud/spring-cloud-dataflow/files/3646637/trace.har.zip)

**Comment by bguessaoui** [comment]
Hello historus,

I'm facing the same issue here, did you find any solution?

**Comment by historus** [comment]
It was a misconfiguration, the URLs of our backend differ from the example in an unfortunate way so we had to find out the correct mapping. Once we have found the right endpoints it was working. Another thing we found out is that we have to add the following query parameters to the URLs as our backend requires them to be part of the request:
- SECURITY_OAUTH2_CLIENT_USER_AUTHORIZATION_URI: add ?scope=...
- SECURITY_OAUTH2_RESOURCE_TOKEN_INFO_URI: add ?client_id=...

**Comment by bguessaoui** [comment]
Hi,
Thank you historus for your answer
 It only worked for me when I added "key-set-uri" parameter (Also work with environment variables)
here is the configmap part to add **(w/o indentation sorry)**
  application.yaml: |-
    security:
      oauth2:
        client:
          client-id: XXXX
          client-secret: YYYY
          scope: "correct scope"              
          access-token-uri: correct access token delivery uri
          user-authorization-uri: correct user authz uri
        resource:
          user-info-uri: correct userinfo openid uri                
          token-info-uri: correct introspect uri
          **key-set-uri:  uri with .well-known of the Authorization server**
