### ISSUE TITLE
SchedulerTaskLauncher needs to support OAuth

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#3524]
Needs to support OAuth .

**Comment by cppwfs** [comment]
Can also  refer to #3812

**Comment by sabbyanandan** [comment]
Based on the internal discussion and the decision to revert to the original behavior of how scheduling worked until SCDF 2.2.x, we do not need to explicitly add the support of OAuth+OIDC in this soon-to-be-remove module (i.e., `SchedulerTaskLauncher`).

The reversion effort is tracked via the epic: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3793.
