### ISSUE TITLE
Helm install SCDF on Kubernetes failed with parameter --set mysql.enabled=false

### ISSUE THREAD

**Issue by zhaojunjie163** [spring-cloud/spring-cloud-dataflow#3525]
**Description:**
I'm trying to install SCDF on Kubernetes with Helm. I'm trying to disable MySql to use H2.

**Instruction:**
https://dataflow.spring.io/docs/installation/kubernetes/helm/#external-database-configuration
SCDF version: v2.2.1.RELEASE
Kubernetes version: 1.14
![image](https://user-images.githubusercontent.com/882981/65813627-80cd4f80-e20a-11e9-9eea-9f4303e5db74.png)

$ helm version
![image](https://user-images.githubusercontent.com/882981/65813614-57acbf00-e20a-11e9-9125-c304ea9dc966.png)

**Steps to reproduce:**
**Commad:**
helm install --name my-release --set mysql.enabled=false stable/spring-cloud-data-flow

**Error**
![image](https://user-images.githubusercontent.com/882981/65813635-99d60080-e20a-11e9-9cc0-a01788154afb.png)

I have tried with AWS EKS, also got the same issue.

**Comment by sabbyanandan** [comment]
@zhaojunjie163: My apologies for the delay. I don't see where and how you're passing the external database credentials. It is not apparent from the helm commands that you have listed in the description. Could you please clarify?

**Comment by zhaojunjie163** [comment]
Hi @sabbyanandan, thanks for your reply, I thought if disable MySql will H2 by default. After searching I found if I disable MySQL with "--set mysql.enabled=false", the helm will not use H2 by default, hence this issue may be related to the helm.

**Comment by sabbyanandan** [comment]
Correct, if you intend to disable `mysql`, you're expected to pass external datasource credentials. That's how the chart is templated. If you do intend to use H2, perhaps you could use the deployment YAMLs that we ship to customize it to the desired behavior (eg: H2 database). Please note it is not reliable to use H2 in a production setting.
