### ISSUE TITLE
Assembly.xml in the dataflow-server module refer to the shell.jar in its section

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#3527]
As seen here:
https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server/src/main/docker/assembly.xml#L15-L22

Shouldn't it refer to the dataflow server app jar instead?

**Comment by sabbyanandan** [comment]
Hi, @cppwfs. We bundle both the Server and Shell JARs as part of the Docker Compose experience, so you can launch the Shell via `docker exec -it dataflow-server java -jar shell.jar` command.

As for they server coordinates, they are pulled directly from the [Fabric8 plugin section](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server/pom.xml#L139-L143) in the pom.xml.
