### ISSUE TITLE
Request parameters in API documentation for "listing applications" has "name" instead of "search"

### ISSUE THREAD

**Issue by gdubya** [spring-cloud/spring-cloud-dataflow#3531]
The [documentation for listing applications](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-app-registry-request-parameters) is incorrect. 

The "name" request parameter is incorrect. The correct key is "search" (similar to [listing task definitions](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-task-definitions-list))

The page, size, and sort parameters are also missing from the "list applications" documentation.

(Sorry, realise this only a minor thing. I'll spend a bit more time to send a PR next time instead of raising an issue).

**Comment by sabbyanandan** [comment]
Thank you for bringing this up, @gdubya. Appreciate it. We will revise the RESTDocs for the `app list` API.
