### ISSUE TITLE
Kubenetes deployed Tasks which contain Spring Batch do not correlate status in the same execution database entry.

### ISSUE THREAD

**Issue by AdVirMachina** [spring-cloud/spring-cloud-dataflow#3536]
I am running SCDF 2.1.2.RELEASE on Minikube version: v1.3.1.

I defined an Application which refers to a Docker container which contains the billrun-0.0.1-SNAPSHOT.jar from the DataFlow batch samples. I then created a Task for which refers to it. My server-config.yaml file is set up to force Kubernetes to execute the container with an entrypoint style of shell. This is a client requirement forced upon me.

When I launch that task, I get two executions for it. The first looks like this:
![image](https://user-images.githubusercontent.com/8268353/66158729-19d5df00-e5ec-11e9-8266-69ae96775fc1.png)

And the second looks like:
![image](https://user-images.githubusercontent.com/8268353/66159244-33c3f180-e5ed-11e9-946a-a0a596319450.png)

This happens with ALL of my Tasks configured like this (Docker image containing Spring Batch application). Why is there no correlation occurring with the External Execution ID (in this case billrun-ql16jxy7d2)? Am I responsible for making this occur somehow within the container itself? I can't find any documentation which states how to do so. In fact, the documentation surrounding the External Execution ID itself is pretty scarce and not very informative.

I'm asking because when using the REST API for launching the task, I receive the ID of the first entry (which only has the External Execution ID). This makes it difficult to track the status of the job via scripting unless I start interrogating all of the Executions associated with a given Task looking for some other marker (starttime, etc). Or to mine previous executions for timing data.

**Comment by sabbyanandan** [comment]
Hi, @AdVirMachina. My apologies for the delay. Could you clarify how you have provisioned SCDF on Minikube? Helm chart of the deployment YAMLs? More details about your setup would help troubleshoot it locally.

**Comment by AdVirMachina** [comment]
I followed the directions on the SCDF Kubernetes installation
documentation. I made a few tweaks to mimic the environment my client is
using (mostly just entryPointStyle:shell). Attached is an extract from my
Minikube cluster.

**Comment by AdVirMachina** [comment]
Basically, you register a Docker image in SCDF as an Application. Within
that image is a Spring Batch .jar which executes. Define a Task using that
application and launch it. SCDF creates the Execution ID for the launch
when it deploys to Minikube. However, once the Spring Batch jar within the
Docker image starts, it creates a new Execution ID for itself it does not
re-use the one created for Deployment. Ideally, all the information would
be kept together.

**Comment by sabbyanandan** [comment]
Thanks. If it is a fully compliant Spring Cloud Task application, it will indeed launch as part of a single deployment execution, and you shouldn't see any duplicates. 

Possible to share your sample Task/batch-job that you're attempting to launch from SCDF?

**Comment by sabbyanandan** [comment]
@AdVirMachina: Possible to share the sample?

**Comment by sabbyanandan** [comment]
Another hit from a Gitter user [here](https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5dc336549c39821509f60a7e).

**Comment by sabbyanandan** [comment]
Based on the discussion with the Gitter user, the reason for duplicates was determined to be extra CLI args in the user's custom `Dockerfile`. Once when that was removed from the file, upon relaunching the new task image (without the extra args) from SCDF, the user was able to run the Tasks with only one execution as expected.
