### ISSUE TITLE
When using pipe delimiter for composed functions a user can't update a stream

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#3538]
For example if you set deployment properties as app.myhttp.spring.cloud.stream.function.definition=upper|suffix.  But when you try to update the stream to something like app.myhttp.spring.cloud.stream.function.definition=upper|suffix|reverse, the parser fails stating that `upper` is not a valid application.   The workaround is to use commas instead of pipes.

**Comment by sabbyanandan** [comment]
There's the use of `|` and `;` as delimiters. I wasn't aware of `,`, however. Let's confirm the recommended approach that we want to promote in SCDF. cc:/ @olegz

**Comment by olegz** [comment]
Yes, that is correct. Coma is another delimiter with the same meaning as pipe for precisely the cases where piper may not work (e.g., HTTP URi)

**Comment by dturanski** [comment]
@olegz - You recently discouraged the use of `,` .  SCSt currently replaces with `|`. Is this something that might go away? 
Another alternative is to use single quotes on the definition. But that passes through to SCSt, and would also have to be handled.

**Comment by cppwfs** [comment]
Retested and was unable to reproduce.
