### ISSUE TITLE
Add CICD infrastructure for Composed Tasks

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3557]
As a continuation from https://github.com/spring-cloud/spring-cloud-dataflow/commit/9d12e492d3c04d9e79b7d00a1faaa5d669b73ff4, we would have to add the foundation bits to support CICD feature for Composed Tasks.

**Comment by sabbyanandan** [comment]
Depending on how much time we have for 2.3 RC1, it is possible to push this enhancement to the next minor release.

**Comment by ilayaperumalg** [comment]
This turned out to be a testing only task and have tested the changes for CTR on local, CF and K8s. They look good! Closing this.
