### ISSUE TITLE
Add filter of jobs by task, timeduration etc.

### ISSUE THREAD

**Issue by venkatasreekanth** [spring-cloud/spring-cloud-dataflow#3564]
**Problem description:**
When issue occur and we have to track where things went wrong, it is almost impossible to use the Web UI since on a given day we have close to 900 job executions. The only recourse is to query the database. It would be nice if filtering functionality were added to the jobs page.

**Solution description:**
Add job name, time duration based filtering, and a link to download the generated log by the job.

**Description of alternatives:**
Right now I have to query the DB.

**Additional context:**
Add any other context or explanation about the feature request here.

**Comment by sabbyanandan** [comment]
@venkatasreekanth: Thanks for the feedback. I can see how filtering on the job-executions would be useful, but not sure of the log downloads, however. We don't store them; it is up to the underlying platforms. We added the log streaming functionality in 2.2, though. From streams/task deployment views, you could see the real-time log streaming.

If you'd want to start a PR with the suggested filtering modes, we would love to collaborate with you.

**Comment by venkatasreekanth** [comment]
I am not familiar with open source development, could you expand on what you mean by PR?

**Comment by sabbyanandan** [comment]
@venkatasreekanth: My apologies for the delay. If you've cycles, feel free to open a pull request to add the desired filtering capability that you described in the issue. More details about contributions and the guidelines [here](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/appendix-contributing.adoc).

**Comment by venkatasreekanth** [comment]
I will try get started on this in the next two weeks.

**Comment by sabbyanandan** [comment]
That's awesome. Looking forward to the PR!

**Comment by cppwfs** [comment]
These PRs should resolve the issue:
https://github.com/spring-cloud/spring-cloud-dataflow/pull/4159
https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/1571

Closing for now.  Re-open if they don't resolve your issue.  Thanks!
