### ISSUE TITLE
Add support within the Helm chart to deploy and/or configure Prometheus/Grafana

### ISSUE THREAD

**Issue by koundinyabs** [spring-cloud/spring-cloud-dataflow#3565]
**Problem description:**
It appears if Prometheus/Grafana is to be used for Stream Monitoring, one cannot use Helm. Please add support within the Helm chart to deploy and/or configure Prometheus/Grafana

**Solution description:**
Users may either have their own Prometheus/Grafana or want it to be deployed as well. It would be good to at a minimum allow configuring SCDF to use an existing Prometheus/Grafana or deploy it (and the RSocket Proxy) automatically and auto-configure SCDF to use it.

**Description of alternatives:**
Do nothing ... ask users to use kubectl instead of helm.

**Comment by sabbyanandan** [comment]
We have this supported in the [Helm Chart](https://hub.helm.sh/charts/stable/spring-cloud-data-flow) now, and the feature can be enabled via `--set features.monitoring.enabled=true`. _(default = `false`)_
