### ISSUE TITLE
Documentation for the Prometheus/Grafana  kubectl based install assumes 'default' namespace

### ISSUE THREAD

**Issue by koundinyabs** [spring-cloud/spring-cloud-dataflow#3566]
**Description:**
The documentation for the Prometheus/Grafana kubectl based install assumes 'default' namespace. If SCDf is being installed in a different namespace, some of the individual yml files under src/kubernetes need to be updated. This should be documented.

**Release versions:**
This is documentation bug/enhancement and is seen in the latest 2.2.x doc: https://dataflow.spring.io/docs/installation/kubernetes/kubectl/#deploy-prometheus-and-grafana

**Custom apps:**
N/A

**Steps to reproduce:**
- Create a namescape, e.g. scdf: kubectl create namespace scdf
- Set current namespace to 'scdf': kubectl config set-context $(kubectl config current-context) --namespace=scdf
- Go through the install steps here: https://dataflow.spring.io/docs/installation/kubernetes/kubectl/#deploy-prometheus-and-grafana
- Observe Prometheus/Proxy/Grafana are all installed in the default namespace and nto 'scdf'. This also causes problems in getting SCDF to work with Prometheus/Grafana but I will have to reproduce this at another time.

**Screenshots:**
N/A

**Additional context:**
N/A

**Comment by sabbyanandan** [comment]
Hi, @koundinyabs. Any customizations outside of the happy-path are probably better to leave it as a user experiment as opposed to attempting to describe any hypothetic environment-specific chore. It is very common for folks to separate various components with namespaces, so it is a well-understood concept nowadays, anyway.

For instance, here's a [hacked up script](https://github.com/sabbyanandan/SpringOne2020/blob/master/scripts/deploy-scdf.sh) of how to customize helm install various components on different namespaces.
