### ISSUE TITLE
Add support for non-default CF identity providers. 

### ISSUE THREAD

**Issue by shalomyasap** [spring-cloud/spring-cloud-dataflow#3576]
**Problem description:**
Exposes a new config property named login hint, which allows supporting non-default IDPs (#316).
The new property (loginHint) should include a URL-Encoded JSON Object, containing the field origin with value as origin_key of an identity provider (e.g. %7B%22origin%22%3A%22uaa%22%7D).

**Solution description:**
To support this feature in Spring data flow a fix already merged to master at 
spring-cloud-deployer-cloudfoundry
see https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/317

**Comment by dbahatSAP** [comment]
The issue is to enable SCDF to support CF deployments with multiple identity providers, where the CF connection user belongs to a non-default identity provider.
Aside from upgrading the CF cloud deployer version (once a new one is available), there's also a need for a small code fix in both SCDF and Skipper, since both explicitly create an instance of PasswordGrantTokenProvider.

Related issue: https://github.com/spring-cloud/spring-cloud-skipper/issues/916

**Comment by dbahatSAP** [comment]
@sabbyanandan, @tzolov Since applying this fix in Skipper/SCDF depends on the new property added to CloudFoundryConnectionProperties, any chance to squeeze an earlier release of spring-cloud-deployer-cloudfoundry? (so this fix can make it to SCDF 2.3.0.RC1?)

**Comment by sabbyanandan** [comment]
Hi, @dbahatSAP. We are tracking to pull 2.1 RC1 release of the CF-deployer in SCDF's 2.3 RC1. Both SCDF and Skipper would update to CF-deployer's 2.1 RC1, too, which will include your fix already (Thanks for the contribution!).

That said, we would still have to include the new property in the [SCDF docs](https://docs.spring.io/spring-cloud-dataflow/docs/2.3.0.BUILD-SNAPSHOT/reference/htmlsingle/#configuration-cloudfoundry-deployer), though. Here's the docs' source code: https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/configuration-cloudfoundry.adoc -- please feel free to submit a PR.

**Comment by dbahatSAP** [comment]
No problem.
I just noticed SCDF uses a snapshot build of the cf deployer, so I also added the required code change inside CloudFoundryPlatformTokenProvider

**Comment by sabbyanandan** [comment]
Ah, good catch. Thanks, @dbahatSAP.
