### ISSUE TITLE
Document user actions to manage dependencies for data flow apps

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-dataflow#358]
The use of the BOM and the interactions with other BOMs needs to be documented. For the short term the user should use spring-cloud-dataflow-dependencies _and_ spring-cloud-dependencies in addition to spring-boot-dependencies (the latter might be included automatically in Gradle or in Maven when using the Boot parent pom). Later on, when data flow joins the Spring Cloud release train, only the cloud BOM will be needed.

**Comment by sabbyanandan** [comment]
Hi, @dsyer. This is an old issue and unfortunately, we didn't talk about it for a long time - my apologies. 

From reading the description though, it is not clear whether if you're referring this in the context of the servers or the OOTB apps. For the latter, we have full-blown documentation on customizing [existing](https://docs.spring.io/spring-cloud-stream-app-starters/docs/Celsius.SR1/reference/htmlsingle/#_patching_pre_built_applications) and as well [creating new apps](https://docs.spring.io/spring-cloud-stream-app-starters/docs/Celsius.SR1/reference/htmlsingle/#_creating_custom_artifacts). However, for the former, the most relevant bits would be the use of SCDF autoconfiguration module, which for example, is used in the [PCF tile](https://github.com/pivotal-cf/scs-dataflow/blob/master/dataflow-server/pom.xml#L26). 

If I'm misinterpreting, I'd be happy to clarify and/or add docs on that matter. Let me know.

**Comment by dsyer** [comment]
It was the latter I cared about. The docs you link to look good, but didn’t actually mention BOMs or dependency management at all. (Also noticed a spelling error in “appliation”.)

**Comment by sabbyanandan** [comment]
Thanks, Dave. I should have pointed to the SCDF's [stream-developer-guide](https://docs.spring.io/spring-cloud-dataflow/docs/1.4.0.RC1/reference/htmlsingle/#streams-dev-guide), which is actually in the main ref. guide. Apart from selecting Boot + Binder from Initializer, there's nothing more to adjust the dependencies manually. Everything should be automatically set.

We will revisit the content (including the typo) in app-starters docs via spring-cloud-stream-app-starters/core#33.
