### ISSUE TITLE
Auditing for Authentication / Authorization events

### ISSUE THREAD

**Issue by dbahatSAP** [spring-cloud/spring-cloud-dataflow#3583]
**Problem description:**
Currently security related events (e.g. login events, authorization events) aren't getting logged, reducing the ability of the SCDF operator to investigate security issues.

**Solution description:**
We can leverage the existing SCDF Audit service to also log security events. 

**Additional context:**
Some enterprise standards require all security events to be audited. Adding this will help SCDF to comply with these standards and become more enterprise ready.

Thanks,
-David

**Comment by ilayaperumalg** [comment]
Hi @dbahatSAP, Thanks for reporting this. 

Currently, all the security events are managed by the common library [Spring Cloud Common Security Config](https://github.com/spring-cloud/spring-cloud-common-security-config) and the audit logging needs to be done at the SCDF side using some extension mechanisms from this common library. This is indeed a good feature to add to SCDF Audit logs.

**Comment by deepak5127** [comment]
@ilayaperumalg  Shall I look into this ?

**Comment by ilayaperumalg** [comment]
Sure, thanks for looking into this!

**Comment by deepak5127** [comment]
@ilayaperumalg  Can we use EventListener in DataflowOAuthSecurityConfiguration and trace the Oauth success or failure events and use existing AuditService to log it ?

**Comment by deepak5127** [comment]
@ilayaperumalg  I have created a Event listener for InteractiveAuthenticationSuccessEvent and able to successfully create an Audit entry.
Shall I
![ss](https://user-images.githubusercontent.com/360576/101589313-0915bb80-399d-11eb-9738-1539aec41b51.jpg)
 create a pull request ?

**Comment by ilayaperumalg** [comment]
Hi @deepak5127 

>Can we use EventListener in DataflowOAuthSecurityConfiguration and trace the Oauth success or failure events and use existing AuditService to log it ?
Sorry, I missed this. Not sure what approach you have taken now. Looking forward to see your PR.

>  I have created a Event listener for InteractiveAuthenticationSuccessEvent and able to successfully create an Audit entry.
Yes, please go ahead and submit a pull request. Thank you for your contribution and patience!
