### ISSUE TITLE
Backport issues for 2.2.2.RELEASE

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3587]
List of issues/commits to review and decide if it needs to be backported:

- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3458
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3367
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3515
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3558
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/pull/3503
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3585 (update just the kafka version, that's all)
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3495
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3482
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3479
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3483
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/pull/3607
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3576

**Spring Cloud Deployer Cloud Foundry**

 - [x] https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/317

**Spring Cloud Deployer Local**

 - [x] https://github.com/spring-cloud/spring-cloud-deployer-local/issues/168

**Spring Cloud Skipper**

 - [x] https://github.com/spring-cloud/spring-cloud-skipper/issues/906
 - [x] https://github.com/spring-cloud/spring-cloud-skipper/commit/10ef9219b9aaf084666e267fa15be7b9cfc206f8
 - [x] https://github.com/spring-cloud/spring-cloud-skipper/issues/899
 - [x] https://github.com/spring-cloud/spring-cloud-skipper/issues/916

**Comment by ilayaperumalg** [comment]
Backporting task is complete
