### ISSUE TITLE
Feature Toggles to disable skipper via Helm chart

### ISSUE THREAD

**Issue by janamailzuu** [spring-cloud/spring-cloud-dataflow#3594]
**Problem description:**
when we tried to use SCDF just for Task/Batches via Helm chart locally, we don't have a way to disable the skipper all together since we are not using it for streams. Due to this, it throws errors in dataflow server pods and causing lot of restarts. (We are not getting the status of Job execution as well, though the task pods are showing successful logs.Not sure of this one being related to the unavailability of feature toggle, worth checking it)

**Solution description:**
Providing feature toggles to disable stream or tasks similar to the toggles present through Kubernetes deployment ymls. Providing a way to configure the toggles through values.yaml will actually  help the end user.

**Description of alternatives:**
Since there is no way currently to disable the stream or tasks, we are going to use the deployment yamls to deploy to Kubernetes.

**Comment by sabbyanandan** [comment]
Thanks for adding it, @janamailzuu. 

(See Gitter conversation [here](https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5db8723914d55a378599e8ce) for context)

**Comment by chrisjs** [comment]
PR @ https://github.com/helm/charts/pull/18611

**Comment by sabbyanandan** [comment]
The feature-toggles is now added to the Helm Chart. Look for `Feature Toggles` section: https://hub.helm.sh/charts/stable/spring-cloud-data-flow.
