### ISSUE TITLE
Update Helm Deployment to include Prometheus and Grafana

### ISSUE THREAD

**Issue by derrick-solstice** [spring-cloud/spring-cloud-dataflow#3597]
**Problem description:**
Current Helm Chart on Stable does not include either Prometheus or Grafana as part of it's deployment, making Helm deployments not monitored.  This is a different experience when attempting to deploy with docker-compose as the deployment structure.

**Solution description:**
We should include the current tested versions of Prometheus Rsocket Proxy and Prometheus as well as Grafana with all necessary bindings to the Helm Chart so that kubernetes deployments automatically mirror the experience when deploying from docker-compose.  These steps are already included when following the `kubectl` installation instructions

**Description of alternatives:**
This can be achieved by referencing the `kubectl` installation instructions and manually deploying all services.  This is quite error prone and difficult to understand

**Additional context:**
I personally am not a Kubernetes developer or i would suggest a Pull Request.  Additionally, I'm not familiar enough with Helm to be able to update the chart myself locally to change the deployment.  

I will gladly accept suggestions and verify functionality myself as part of this issue.

**Comment by chrisjs** [comment]
work is stashed in a branch until release time

**Comment by derrick-solstice** [comment]
@chrisjs For my knowledge, what is the tentative release date for `2.3.0.GA`?  I would love to early adopt that.

**Comment by sabbyanandan** [comment]
@derrick-solstice: We have a tentative plan for the release next week. Feel free to watch the repo for release/release-tag notifications.

**Comment by sabbyanandan** [comment]
Merged via https://github.com/helm/charts/pull/19431.

**Comment by sabbyanandan** [comment]
@derrick-solstice: The 2.3 GA release is complete, and the Helm Chart is ready for you -> https://hub.helm.sh/charts/stable/spring-cloud-data-flow
