### ISSUE TITLE
Improve tasklauncher-dataflow sink to launch tasks using --URI (without creating task definition manually)

### ISSUE THREAD

**Issue by majorisit** [spring-cloud/spring-cloud-dataflow#3599]
We have successfully implemented **tasklauncher-dataflow sink** in **K8S** environment. But, it required to have task to be created first in order for us to either launch or schedule it.
Since we have humongous SCDF tasks (> 5000 tasks), we are looking for a solution to deploy and launch tasks automatically (without creating task definition manually) at runtime using **tasklauncher-dataflow sink** by sending **Task Launch Request**.

**Important: FYI**, we already have a solution in place using **TaskLauncher Kubernetes Sink** for dynamically create and launch SCDF tasks using _--uri_ parameter.  It's working fine as per our requirement, but this Sink module is no longer recommended by Pivotal because it is not maintained with upstream version upgrades anymore.

Since **tasklauncher-dataflow sink** is the replacement, however if this sink doesn't meet our requirements, we could collaborate to improve it together.

Please treat this case as high priority

**Comment by sabbyanandan** [comment]
Thanks, @majorisit. I'm going to move this to `tasklauncher-dataflow` repo since most of the work would be on the sink application itself. Depending on how we design/solve for it, there might be changes in SCDF, but we will revisit it when we get there.

**Comment by sabbyanandan** [comment]
Closing this in favor of https://github.com/spring-cloud-stream-app-starters/tasklauncher-dataflow/issues/24.
