### ISSUE TITLE
CommandLine args of task is passed to Scheduler task launcher

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#3608]
With the new Scheduler task launcher in effect, the command line arguments passed for the underlying task definition are also passed to the scheduler task launcher application as well.

**Comment by cppwfs** [comment]
Created branch with fix.  https://github.com/cppwfs/spring-cloud-dataflow/tree/SCDF-3608A .
Tested it on Kubernetes but not CF.  Waiting till internet is fixed at home before testing.    Once CF test is complete I'll submit a PR.
