### ISSUE TITLE
Refactor DefaultTaskExecutionService's executeTask

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#3610]
The [executeTask](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java#L173) method in `DefaultTaskExecutionService` needs to be refactored as it gets growing with the number of underlying operational changes.

We need to consider setting the AppDeploymentRequest at the final place of the method as well.

**Comment by deepak5127** [comment]
Hi @ilayaperumalg  Shall i work on this issue ? If so, can you please share some more details on the task.

**Comment by ilayaperumalg** [comment]
Hi @deepak5127, Sure, thanks for your interest in working on this.

The main idea is to split the `executeTask` into multiple smaller methods so that it is easy to understand the flow (especially how the `AppDeploymentRequest` is updated with the properties).

Feel free to submit a initial PR and we can go from there. Thanks again!

**Comment by deepak5127** [comment]
Sure, Thanks @ilayaperumalg . I will start looking into this and submit a PR when my initial version is ready.

**Comment by deepak5127** [comment]
@ilayaperumalg  I have refactored AppDeploymentRequest creation part alone. Please let me know if the approach looks good, so that I can continue refactoring the whole method.

**Comment by ilayaperumalg** [comment]
This was addressed via c23ac5d

**Comment by ilayaperumalg** [comment]
@deepak5127 Thank you for your contributions.
