### ISSUE TITLE
If user deletes droplet  and then tries to relaunch task from dataflow Task fails to launch

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#3627]
Found in 2.3.0.BUILD-SNAPSHOT

Steps to reproduce 
1) From dataflow:  Create a task definition
2) From dataflow: Launch task definition with no command line args 
3) From command line: Delete the droplet using `cf delete <app>`
4) From dataflow: launch task definition with new command line args and properties
Dataflow will not start the application saying droplet does not exist.

Work around:
Launch the app with no properties nor command line args and it will recreate the droplet.   Then you can launch with new parameters.

**Comment by sabbyanandan** [comment]
A lot of optimizations were done around this workflow in 2.8.x through https://github.com/spring-cloud/spring-cloud-dataflow/pull/4576, https://github.com/spring-cloud/spring-cloud-dataflow/pull/4577, https://github.com/spring-cloud/spring-cloud-dataflow/pull/4534, and likely many others.
