### ISSUE TITLE
Two Kafka Server with Spring Cloud Data Flow

### ISSUE THREAD

**Issue by txy362922388** [spring-cloud/spring-cloud-dataflow#3633]
Suppose there are two Kafka servers, one is for Spring Cloud Data flow and the other is for data source. I create a SpringBoot based application with Kafka dependency and use @KafkaListener as source and output the message. However, when I deploy the jar file to Spring Cloud Data Flow server and deploy the stream, the message was sent to Kafka that for data source but no the Kafka with Spring Cloud Data flow. The sample code gives like
```
@EnableBinding(Source.class)
public class TestSource {

    @Autowired
    private Source source;

    @KafkaListener(topics = "topic.datasource")
    public void source(ConsumerRecord<String, GenericRecord> record) throws InterruptedException {

        logger.info("recv {} : {}", record.offset(), record.value());
        // some data pre processing
        source.output().send(MessageBuilder.withPayload(message).build());
    }
```
My question is how we can get the data from one Kafka server and send the message to another Kafka server with Spring Cloud Data Flow.

**Comment by sabbyanandan** [comment]
I see a duplicate post at: https://stackoverflow.com/questions/58851656/two-kafka-server-with-spring-cloud-data-flow. For questions like this, please stick to SO going forward. Someone from the team would share thoughts on the SO post.

**Comment by sabbyanandan** [comment]
Please also review the multi-binder configuration from the [ref. guide](https://docs.spring.io/spring-cloud-dataflow/docs/2.2.2.RELEASE/reference/htmlsingle/#spring-cloud-dataflow-stream-multi-binder). Though it describes a Rabbit + Kafka scenario, the approach is relevant for 2 Kafka binders also.

**Comment by edudar** [comment]
@sabbyanandan not sure that I follow how multibinder addresses this issue. I might be mistaken but I think the question is how to create a Kafka source similar to the [RabbitMQ](https://github.com/spring-cloud-stream-app-starters/rabbit/tree/main/spring-cloud-starter-stream-source-rabbit) one. It's rather surprising that it does not exist in Spring Cloud Stream App Starters already. Spring Integration has support for both `AmqpInboundChannelAdapter` + Ampq DSL and `KafkaMessageDrivenChannelAdapter` + Kafka DSL.
