### ISSUE TITLE
Allow "loadBalancerIP" in Deployer properties

### ISSUE THREAD

**Issue by xetra11** [spring-cloud/spring-cloud-dataflow#3645]
**Problem description:**
We want to access the Source Stream via external IP. Creating a LoadBalancer via the Deployer properties works to an extend. If we redeploy the Stream the IP is changing. That is a problem since we want to apply a internal domain name to that source. Without being able to attach an static IP this is not possible.

**Solution description:**
Allow the `loadBalancerIP` property in the Deployer properties

**Description of alternatives:**
Maybe deploying an Ingress besides the LoadBalancer and giving having `ingressAnnotations` (similar to podAnnotation properties) might work, too.

**Additional context:**
```apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    app: hello
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: "YOUR.IP.ADDRESS.HERE"
```

**Comment by sabbyanandan** [comment]
@xetra11. We recommend handling this with the help of an explicit LoadBalancer (LB) configuration that remains static regardless of whatever happens to your application. Along with the label selector support we have in the K8s-deployer, you'd then be able to use the `deployer.<yourapp>.kubernetes.deploymentLabels` property to pass the label included in the LB, so the traffic can be routed predictably.

I described the configuration with an example on the [duplicate post of this topic in StackOverflow](https://stackoverflow.com/questions/58951914/how-to-apply-a-static-ip-for-spring-scdf-stream-that-has-a-loadbalancer-in-kube/58957923#58957923).

I hope this helps.
