### ISSUE TITLE
Remove component scan from DataFlowServerConfiguration

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#365]
It is simply a bad practice to use component scanning in a shared framework config class, so it should go away in favor of defining needed controllers and repositories manually. This way we have a full predictable control over what gets created and what doesn't.

```
@ComponentScan(basePackageClasses = {
        StreamDefinitionController.class,
        StreamDefinitionRepository.class
})
```

**Comment by sabbyanandan** [comment]
There's no more `@ComponentScan` in [DataFlowServerConfiguration](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowServerConfiguration.java).
