### ISSUE TITLE
Add option to pass "executionId" and "platformName" either as cmd-line arguments or plain environment variables

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#3651]
Currently the executionId and platformName are passed to the task to be launched via the command line args.  i.e. 
```
--spring.cloud.dataflow.platform_name: default
--spring.cloud.task.executionid: 91
``` 
If a user uses the shell entry point for launching tasks on kubernetes these values can't be passed as command line args (they are ignored by the entrypoint).   We need to have a  boolean flag `passDefaultExecutionArgsAsProperties` in data flow that allows users to set this flag to `true` if they want these values passed as properties.  It defaults to false.

**NOTE:**
In the docs, further clarify that when `shell` option is selected, the command line arguments from the deployment request _are not converted_ into environment variables.

**Comment by ilayaperumalg** [comment]
Issue moved to [spring-cloud/spring-cloud-deployer-kubernetes #365](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/365) via [**ZenHub**](https://www.zenhub.com/)
