### ISSUE TITLE
Splits in Composed Task Pipelines Cause Issues with Task Definition Rendering

### ISSUE THREAD

**Issue by SofaRabbit** [spring-cloud/spring-cloud-dataflow#3660]
When creating a composed task in the Spring Cloud Data Flow (SCDF) interface, if you specify a split, the portion of the split not using the COMPLETE exit status will not render in the UI.

**Steps to Reproduce:**
1) Select the **Tasks** tab.
2) Click the **Create Task(s)** button.
3) Drag a task from beneath the task section onto the canvas and configure the properties.  Be sure to attach it to the START block.
![Screen Shot 2019-11-27 at 10 36 15 AM](https://user-images.githubusercontent.com/58263952/69737103-cb335580-1101-11ea-9135-b9c639b3e4cf.png)
4) Drag two new tasks from beneath the task section onto the canvas and attach them to the first task, being sure to have one task being configured with an exit status of **FAILED**.  Connect both tasks to the END block.
![Screen Shot 2019-11-27 at 10 40 18 AM](https://user-images.githubusercontent.com/58263952/69737420-5dd3f480-1102-11ea-834c-7c6fd31e7d13.png)
5) Configure the properties of the task associated with the default exit status of **COMPLETE**.  Note how the properties are attached to the task definition portion of the page above with no issues.
![Screen Shot 2019-11-27 at 10 42 05 AM](https://user-images.githubusercontent.com/58263952/69737604-a7244400-1102-11ea-918b-1833b01856fe.png)
6) Attempt to configure the properties of the other task.  Note how the properties are not appended to the task definition in the section above.  The properties will be displayed on hover, but will not actually be appended to the task definition.
![Screen Shot 2019-11-27 at 10 47 25 AM](https://user-images.githubusercontent.com/58263952/69738013-62e57380-1103-11ea-97f1-aa3747dd5a8b.png)

The composed task created from this process will pass validation by the interface, so you will actually be able to create this task.  However, if you look at the Tasks section, you will see that definition for that individual task is blank.
![Screen Shot 2019-11-27 at 10 49 27 AM](https://user-images.githubusercontent.com/58263952/69738396-0d5d9680-1104-11ea-90d3-a5b784253f37.png)

**Comment by sabbyanandan** [comment]
Hi, @SofaRabbit. Thank you for the thorough report and screenshots! This is helpful. It appears to be a bug, specifically when configuring the task and its properties on a transition path. We will have to review it on the UI side first.

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-dataflow-ui #1333](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1333) via [**ZenHub**](https://www.zenhub.com/)
