### ISSUE TITLE
Upgrade required dependency to MySql Chart to version 1.4.0

### ISSUE THREAD

**Issue by CrystalMethod** [spring-cloud/spring-cloud-dataflow#3666]
Current Kubernetes version (1.16) has removed some APIs so the installation of the required dependency MySql version 1.1.0 fails. These APIs have been deprecated for some time.

https://github.com/helm/charts/blob/master/stable/spring-cloud-data-flow/requirements.yaml

MySql Helm Chart version < 1.4.0
`apiVersion: extensions/v1beta1`

MySql Helm Chart version >= 1.4.0
`apiVersion: apps/v1`

See https://git.k8s.io/kubernetes/CHANGELOG-1.16.md#deprecations-and-removals

**Comment by sabbyanandan** [comment]
Hi, @CrystalMethod. The v2.3.0 RC2 release of SCDF had already switched to support K8s 1.16 - see [mysql-deployment.yaml](https://github.com/spring-cloud/spring-cloud-dataflow/blob/v2.3.0.RC2/src/kubernetes/mysql/mysql-deployment.yaml#L1). 

When we ship v2.3.0 GA, the helm chart, of course, will be switched to the latest MySQL chart as well. And, that is tracked via https://github.com/spring-cloud/spring-cloud-dataflow/issues/3622. In the meantime, feel free to try out the 2.3.0 RC2 deployment files, and let us know if you see any issues with it.
