### ISSUE TITLE
Prepare for Helm 3.0 compatibility

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3669]
As a developer, I'd like to study, prepare, and upgrade the SCDF helm chart to be compatible with Helm 3.0. 

**Acceptance:**
- The chart should be both backward and forward compatible, so it needs to align with Helm 3.0 guidelines if there's any
- If it is not possible to retain a single chart from a compatibility perspective, research and decide if there's a need to maintain two parallel versions of the chart
- Revisit the getting-started docs in the Microsite
- Document findings

**Comment by chrisjs** [comment]
see "Helm 3" google doc
