### ISSUE TITLE
Remove @EnableAutoConfiguration from AdminConfiguration

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#367]
As mentioned in #364 we may get into trouble:

```
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: A circular @Import has been detected: Illegal attempt by @Configuration class 'AdminConfiguration' to import class 'LocalDeployerAutoConfiguration' as 'LocalDeployerAutoConfiguration' is already present in the current import stack [AdminApplication->LocalDeployerAutoConfiguration->AdminConfiguration->AdminConfiguration]
Offending resource: class path resource [org/springframework/cloud/dataflow/admin/config/AdminConfiguration.class]
    at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:70) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
```

in case when `AdminConfiguration` is for any reason imported into context directly from autoconfiguration.

If something needs to be excluded from auto-config, it should be done in a class which enables autoconfiguration. Typically this is a app main class and all admin/server impls may actually have different needs. Doing this from a shared config class is just wrong.

As `@EnableAutoConfiguration(exclude = OAuth2AutoConfiguration.class)` it to be removed, if oauth has to go away, all admin impls need to explicitly exclude it.

**Comment by sabbyanandan** [comment]
We have refactored all of this already.
