### ISSUE TITLE
Logs missing for scheduled task executions

### ISSUE THREAD

**Issue by mackoftrack** [spring-cloud/spring-cloud-dataflow#3678]
**Description:**
Tasks that are launch manually via the UI show logs on the Task Execution Details page, but the same task launched via the scheduler do not.

SCDF deployed on kubernetes via helm chart

**Release versions:**
2.2.2.RELEASE

**Steps to reproduce:**
- Deploy SCDF to kubernetes using helm chart
- Create task
- Launch manually, see execution logs
- Schedule task, no execution logs

**Screenshots:**
with logs
![image](https://user-images.githubusercontent.com/3811209/70261635-b2512280-1747-11ea-8607-fc4c3d82fa03.png)
without logs
![image](https://user-images.githubusercontent.com/3811209/70261654-bf6e1180-1747-11ea-866b-76c640c5d609.png)

**Comment by mackoftrack** [comment]
@ilayaperumalg any idea?

**Comment by mackoftrack** [comment]
@ilayaperumalg

**Comment by ilayaperumalg** [comment]
Hi @mackoftrack, Sorry about the delay in responding to this. This looks like a bug in 2.2.x but apparently this got fixed in 2.3.x and above. Could you give it a try on 2.3.x ?

**Comment by mackoftrack** [comment]
@ilayaperumalg Yes I can confirm it is fixed in 2.3.0. Thanks

**Comment by gry77** [comment]
hi, i have exactly same issue with 2.5.0.RELEASE - docker kubectl installation, shall i open new issue since this is exactly same thing ?
