### ISSUE TITLE
local scheduler support

### ISSUE THREAD

**Issue by hopfensp** [spring-cloud/spring-cloud-dataflow#3680]
Are there plans to implement backend scheduler functionality for the local implementation?  I see there is a feature toggle and when enabled, the front end is there, but the backend is not implemented.

**Comment by sabbyanandan** [comment]
Hi, @hopfensp. There are currently no plans for a standalone local implementation of the scheduler. A few in the community have built a Quartz-based implementation - see [spring-cloud-scheduler-quartz](https://github.com/spring-cloud/spring-cloud-scheduler-quartz/issues). 

For questions like this, please use StackOverflow going forward.
