### ISSUE TITLE
Unable to schedule Tasks in SCDF Chart v2.5.0

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3684]
As a user, while attempting to schedule Tasks on the SCDF 2.5.0 Helm Chart (SCDF 2.3.0), I get the following error and the scheduled launch fails.

```
Message:  Failed to apply default image tag “//org.springframework.cloud:spring-cloud-dataflow-scheduler-task-launcher:jar:2.3.0.RELEASE”: couldn’t parse ││image reference “//org.springframework.cloud:spring-cloud-dataflow-scheduler-task-launcher:jar:2.3.0.RELEASE”: invalid reference format                           │
│        Reason:   InvalidImageName
```

It turns out the new [scheduler-tasklauncher](https://github.com/spring-cloud/spring-cloud-dataflow/blob/v2.3.0.RELEASE/src/kubernetes/server/server-deployment.yaml#L44-L45) configuration to include the `spring-cloud-dataflow-scheduler-task-launcher` image+tag reference in the SCDF deployment is missing in the [SCDF's Helm template](https://github.com/helm/charts/blob/master/stable/spring-cloud-data-flow/templates/server-deployment.yaml).

**Comment by chrisjs** [comment]
merged https://github.com/helm/charts/pull/19473
