### ISSUE TITLE
SCDF 2.3.0.RELEASE helm chart doesn't work on K8s 1.16 or above

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#3685]
Since the external dependencies of the SCDF 2.3.0.RELEASE helm chart still uses some of the removed API metadata (like extensions/v1beta1 etc.,), the helm install of the 2.3.0.RELEASE throws the following error:

```
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

```

We need to update the the helm chart versions of the external dependencies in [this](https://github.com/helm/charts/blob/master/stable/spring-cloud-data-flow/requirements.yaml) file.

**Comment by chrisjs** [comment]
which deps are causing this?

**Comment by chrisjs** [comment]
found them..

**Comment by chrisjs** [comment]
closing in favor of https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/issues/289
