### ISSUE TITLE
Port remaining stream ATs as ITs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3689]

**Comment by tzolov** [comment]
Comparison of the AT and Docker Compose IT stream tests:

| ATs        | DockerCompose ITs          |
| ------------- |:-------------|
| `AnalyticsTests` - testing the Redis analytics - long gone and not supported feature | The new `DockerComposeTestStream#analyticsCounter` - testing SCDF integration for `micrometer`, `prometheus`, `influx` and `Counter` analytics |
| `HttpSourceTests `     | This functionality is tested as part of `DockerComposeTestStream#streamTransform`  and  `DockerComposeTestStream#streamPartitioning` | 
| `NamedChannelTests` | `DockerComposeTestStream's` `#namedChannelDestination`, `#namedChannelTap`, `#namedChannelManyToOne`, `#namedChannelDirectedGraph` - Note that the namedChannelDirectedGraph is disabled in ATs but running in IT!    |  
| `TickTockTests'` `#tickTockTests` and `#tickTockUpdateRollbackTests`| Covered by `DockerComposeTestStream's` `#streamLifecycle (DEPLOY, UPDATE, ROLLBACK)` | 
| *NOT TESTED* | `DockerComposeTestStream#streamLifecycle (UNDEPLOY, DESTROY)` | 
| `TickTockTest#tickTockTestsFromConfigServer` (run only for CF) | *NOT TESTED* - decision not to port | 
| `TransformTests`  |  `DockerComposeTestStream#streamTransform` |
| `WoodChuckTests`  |  `DockerComposeTestStream#streamPartitioning` |
| *NOT TESTED*  |  `DockerComposeTestStream#streamScaling` |

* With exception of the Config Server tests, the Docker Compose ITs provides a broader test coverage compared to ATs. 
* DockerCompose ITs also tests `stream scaling` and `Prometheus/Influx metrics&analytics` which is not covered by the ATs at the moment.
* Default `DockerComposeIT` test suite tests `SCDF`+`Skipper`+`Kafka`+`Mysql`+`Prometheus-monitoring`.
* The additional `DockerComposePostgresRabbitInfluxIT` test suit runs the same tests but for `SCDF`+`SKIPPER`+`Rabbit`+`Postgres`+`Influx-monitoring` setup.
* Every tests suit (e.g. DockerComposeIT and DockerComposePostgresRabbitInfluxIT) takes approximately 15 min to complete.

One can run only the DockerCompose IT test suits like this:
```
./mvnw clean test-compile failsafe:integration-test -pl spring-cloud-dataflow-server -Pfailsafe
```
*note that you need to enable the `failsafe` profile to run the IT tests*
