### ISSUE TITLE
Add debug capabilities to LocalAppDeployer

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow#369]

**Comment by aclement** [comment]
A pair of PRs now enable debugging with local deployer. Works for me but there are open questions. I raised the PRs to drive the discussion:
PR on deployer: https://github.com/spring-cloud/spring-cloud-deployer/pull/35
PR on dataflow: https://github.com/spring-cloud/spring-cloud-dataflow/pull/502

Info I included in those PRs:

Created two pull requests (one on dataflow, the other on local deployer), these are for github issue #369 "Add debug capabilities to LocalAppDeployer".

With these two in place you can turn on debug by specifying "module.foo.debug-port=8800" as a deployment property.

The first pull request (on the deployer) recognizes a debug-port property and uses it to add a debug agent to the configuration for the Process it launches.

The second pull request (on dataflow) recognizes the deployment pattern module..debug-port=XXX and maps that to the debug-port property in the deployer.

This works but are the properties in the right place? Is it ok to have this as a deployment config property? (It is quite nice that turning debug on/off does not require meddling with the stream definition). What do we do for other deployers? Do we need a simpler 'debug=true/false' option alongside this for any that don't need a port, or do we need a deployer specific namespace subsection for this?

**Comment by jvmlet** [comment]
Would be great to  be able to debug the **task** launched by SCDF as well, see `listen` debugger mode  approach described in [SO](https://stackoverflow.com/questions/47102545/how-to-remote-debug-a-spring-cloud-data-flow-task/47637252#47637252)

**Comment by sabbyanandan** [comment]
This was addressed in spring-cloud/spring-cloud-deployer-local#85; docs [here](https://docs.spring.io/spring-cloud-dataflow/docs/1.3.0.RC1/reference/htmlsingle/#_remote_debugging).
