### ISSUE TITLE
Can't launch same task definition with different arguments concurrently in 2.3.0

### ISSUE THREAD

**Issue by djgeary** [spring-cloud/spring-cloud-dataflow#3695]
In SCDF 2.2.1 (Kubernetes) we launch tasks with the same definition and different argument/properties frequently.
Properties that don't commonly change we would put in the definition and those that do we supply at launch time.
Some of these executions may overlap.

After updating to SDCF 2.3.0 when launching tasks (through the rest API) with different arguments to ones already running we get a 500 status code and the message body 
`[ { "logref": "IllegalStateException", "message": "Unable to update application due to currently running applications" } ]`

As discussed on gitter (https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5df0fa540995661eb8c923d3) this is due to the new CD functionality in 2.3.0.

The seems like a serious restriction in functionality, as it seems its now not possible to launch a task definition with different arguments or properties from one already running.

In our case this would result in 'random' failures. Surely changing a launch property is nothing to do with CI or updates/upgrades (which I assume is related to the task application version only?).
Also there may be the odd failed/aborted execution in the history with no end time that could impact launches too.
The exception thrown is a 500 and mentions 'update application' which isn't very meaningful either - as we aren't trying to update an application.

It would be useful if there was a way to turn this off or simulate the previous behaviour - running a task definition concurrently with different arguments doesn't seem like an unusual thing to do?

**Comment by sabbyanandan** [comment]
Hi, @djgeary. As discussed in Gitter (and clarified by @mminella), the CLI-args aren't included in the CD flows, so you should be able to launch/re-launch with dynamic arguments. There's currently support to persist the CLI-args in SCDF 2.3, but we will decouple that in #3694. With this change, you should be able to _concurrently_ launch the _same_ task-definition _with_ different CLI-args.

We will also [update the docs](https://docs.spring.io/spring-cloud-dataflow/docs/2.3.0.RELEASE/reference/htmlsingle/#_task_launch_lifecycle) to describe the App Properties, Deployer properties, and CLI Arguments and its applicability on CICD flows.

Let us know if you see any anomaly.

**Comment by djgeary** [comment]
Hi @sabbyanandan, I'm not sure I follow 

> There's currently support to persist the CLI-args in SCDF 2.3

Is this something that would currently prevent us launching the same task concurrently with different arguments?

Ie do we have to wait for #3694 before we can launch tasks concurrently even if we switch our code to use arguments instead of properties? This would prevent us from upgrading to 2.3.0

**Comment by sabbyanandan** [comment]
#3694 is specific to when the task is "scheduled". You can launch/re-launch outside of the scheduling with different arguments already. Either way, a fix for scheduling is coming in a point release anyway.

You were going to try out 2.3 in your environment — it'd be good to get the validation.

**Comment by djgeary** [comment]
OK, we use scheduling too so it may be an issue, but will try to test out running manually with different arguments.

**Comment by gdubya** [comment]
Same problem affected us. We worked around it by downgrading to 2.3.0.M1

**Comment by cppwfs** [comment]
Had a discussion with @mminella on this topic.   To resolve this issue, we will check to see if the platform type  is Kubernetes or Local, if so we will not implement this logic. (Logic meaning : to prevent a launch of a task definition if it has different properties from a running instance of the same task definition)   This logic is still required for Cloud Foundry since the it keeps the same app across multiple executions, while kubernetes creates a new pod for each launch.
The line to apply the check is here: https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java#L273

**Comment by djgeary** [comment]
Hi @sabbyanandan, sorry for the delay in feedback here but I've done some testing on 2.3.0 to see if we could switch to using arguments instead of properties. 
I've included our findings below:

**Properties or Arguments?**

I initially said that we were using properties in our task code as we bind spring boot properties of the form 'target.url'. 
Additionally we set these properties either in the task definition eg 
`task create myexampletask --definition "exampletask --target.url=\"http://test\""`
or pass them as properties when we launch the task via the rest api eg 
launch `name=myexampletask&properties=app.exampletask.target.url="http://test"`

However it seems these 'properties' are also available as 'arguments' in our code - I added a log line immediately inside the CommandLineRunner run method ie 

```
@Override
public void run(final String... args) throws Exception {
     logger.info("Running with arguments {}", Arrays.toString(args));
....
```

From this i can see all our properties as well as standard spring ones appearing as 'arguments' eg (sample)

```
Running with arguments [
--spring.datasource.username=postgres, 
--target.url=http://test, 
--spring.cloud.task.name=myexampletask, 
--spring.cloud.data.flow.platformname=default, 
--spring.cloud.task.executionid=3339
...
] 
```

So it appears all the properties are also arguments (adding to my confusion over the difference between them) 

To test further I added sample arguments and properties from the SCDF task launch screen, literally 

Arguments `--myarg=myargvalue`

Parameters (should this be properties?) `app.myparam=myparamvalue`

Now I see `--myarg=myargvalue` appearing in the arguments log message but don't see `app.myparam=myparamvalue` anywhere

This may be because we are running on Kubernetes - looking at the pod in the K8S dashboard we see 
```
Args:
--spring.datasource.username=postgres, 
--target.url=http://test, 
--spring.cloud.task.name=myexampletask, 
--spring.cloud.data.flow.platformname=default, 
--spring.cloud.task.executionid=3339
--myarg=myargvalue
.....
```
Ie it appears that the same mechanism is used to pass arguments and properties into the task pod and they can be read either way from inside the code?

**Try to use arguments instead**

With this in mind we thought maybe we only needed to change the client application to pass in arguments instead of properties (to get around the issues we are trying to solve here ie 
so SCDF would not complain about the properties changing). However when we test this, lets say we have the task 

`myexampletask --definition "exampletask --target.url=\"http://test\""`

and we launch with an argument `target.url="http://test_2"` (in SCDF launch screen)

K8S and the arguments log now show 
```
--spring.datasource.username=postgres, 
--target.url=http://test, 
--spring.cloud.task.name=myexampletask, 
--spring.cloud.data.flow.platformname=default, 
--spring.cloud.task.executionid=3339
--target.url=http://test_2, 
```
(ie both values are present)

However our code (binding the property) gets this 

`target.url=http://test,http://test_2`

which is obviously unusable (and throws an exception for number properties)

**Change argument keys?**

We then considered using different keys for arguments checking for the argument and if its not present fall back to the property key etc, but this seems like work we shouldn't really have to do. 
In addition we saw instances in testing where old test arguments were showing up (eg `--myarg=myargvalue`) even if we hadn't included that value for that launch which makes moving to arguments seem like it could introduce other issues (I'm not sure if this is https://github.com/spring-cloud/spring-cloud-dataflow/issues/3694 or not but we weren't using scheduled, just launching tasks manually)

**Conclusion**

With all this in mind we intend to wait for 2.3.1 or 2.4.0 instead trying to get it to work now.

**Comment by robinsomarajv** [comment]
How to run multiple instances of same cloud task(by using labels) with different properties/arguments in the same samSCDF task definition?
