### ISSUE TITLE
Only one partition for Kafka topic gets created

### ISSUE THREAD

**Issue by mshalak-nix** [spring-cloud/spring-cloud-dataflow#3703]
Using:
- minikube
- Kafka 
- Kubernetes v1.15.4
- spring-cloud-dataflow-server 2.3.0.RELEASE

Created a simple stream from trigger and log starters, it will just put a message every second to a log:
`trigger --management.metrics.export.prometheus.enabled=true --management.metrics.export.prometheus.rsocket.port=7001 --management.metrics.export.prometheus.rsocket.enabled=true --management.metrics.export.prometheus.rsocket.host=10.106.235.227 --trigger.source.payload=SCHEDULER-TEST | log --spring.cloud.stream.instanceCount=3 --management.metrics.export.prometheus.enabled=true --management.metrics.export.prometheus.rsocket.port=7001 --management.metrics.export.prometheus.rsocket.enabled=true --management.metrics.export.prometheus.rsocket.host=10.106.235.227`

Launched 3 instances of the log sink:
`deployer.log.count=3`
I see following log message in log sink pods:
`o.s.c.s.b.k.p.KafkaTopicProvisioner      : The number of expected partitions was: 3, but 1 has been found instead.There will be 2 idle consumers`

As result, messages get consumed by one pod only, other two stay idle.

**Comment by sabbyanandan** [comment]
Hi, @mshalak-nix.  The `instanceCount` and `instanceIndex` are automatically set and pre-populated by SCDF depending on the deployment properties passed in the stream deployment. In your case, the `deployer.log.count=3` is sufficient to let SCDF populate these properties automatically. In other words, you do not have to set these properties explicitly.

Few ideas:
1) First, I'd check to make sure the Kafka that you're using allows you to auto-add partitions to a given topic at runtime. Outside of SCDF, try creating a topic+partitions using the Kafka CLI.
2) Alternatively, you could run `trigger` and `log` locally as standalone applications (`java -jar`) against the same Kafka, to validate the behavior.
3) As well, you can confirm the overridden Spring Cloud Stream properties by accessing each of the consumer instance's actuator endpoint at `http://<app>/actuator/configprops`. 

This should give enough visibility into what might be different in your environment. If anything, we need to troubleshoot it from Spring Cloud Stream + Kafka perspective — this has nothing to do with SCDF, though.

If you continue to see issues with it, please open a StackOverflow thread with your observations.
