### ISSUE TITLE
Follow the applicable naming conventions for K8s resources

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#3704]
Given we append the task name as part of the scheduler name, the K8s scheduler name validation fails on certain cases. We either need to validate the task name (using the K8s scheduler name format) or use a different approach for appending the scheduler name.

For instance, if I have a task definition name `A1` then, the creation of the schedule would fail on K8s.

**Comment by sabbyanandan** [comment]
See: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names

**Comment by cppwfs** [comment]
check for capitalization also for length. i.e. helloworld-task-schedule-test1-scdf-foo-some-wonderful-schedule-name is too long.   Needs to be 50 or less characters
