### ISSUE TITLE
Difference in behavior between SCSt and SCDF for dynamic partition adjustments when using Kafka

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3706]
As a user, while attempting to demonstrate scaling + partition adjustment with Kafka, I notice the following differences between a standalone SCSt run vs. when deployed via SCDF (for the same application).

_SCSt:_ 
- Start the consumer with 3 instances aka 3 partitions with `autoAddPartitions` set to "true"
- Notice the partitions are automatically created for the given topic by Kafka via Kafka CLI
- Notice also the 3 partitions are automatically assigned to 3 consumer instances, again by Kafka
- Start 4th consumer instance; a 4th partition is automatically created in Kafka
- Notice that the partition rebalance is automatically triggered in Kafka
- Notice the 4 partitions are automatically assigned to 4 consumer instances, again by Kafka — all 4 consumer instances are participating in the data processing

**-VS-**

_SCDF:_
- Deploy a stream with the consumer count set to 3 (eg: `deployer.appender.count=3`) along with `autoAddPartitions` set to "true"
- Notice that `spring.cloud.stream.bindings.output.producer.partitionCount` is set to "3" at the source; likewise, `spring.cloud.stream.instanceCount` is at "3" and `spring.cloud.stream.instanceIndex` is set individually to each of the 3 consumer app instances 
- Notice the partitions are automatically created for the given topic by Kafka via Kafka CLI
- Notice also the 3 partitions are automatically assigned to 3 consumer instances, again by Kafka
- Scale the consumer app to "4" (eg: `http post http://localhost:9393/streams/deployments/scale/fooz/appender/instances/4`)
- Notice that the 4th partition is **_not_** automatically created in Kafka
- Notice also that the 4th consumer is sitting idle and not participating in the data processing yet
- Now, when you rolling-update the producer with `"updateProperties":{"app.fruits.producer.partitionCount":4,"app.appender.spring.cloud.stream.instanceCount":4}`, you will see that 4th partition is created for the  given Kafka topic, and likewise, the 4th consumer is now participating in data processing

_Observations / Notes:_
- This set up works beautifully in SCDF + Kafka when there is no partitioning characteristics is applied
- However, when `partitionKeyExpression` is used at the source, SCDF treats the partitioning scenario by setting `partitionCount` at the producer — it might be required for Rabbit (since we handle the partitioning logic in spring-amqp+rabbit binder), but do we need it for Kafka also?
- If `partitionCount` is set at the producer, it appears to be treated almost like a "static partitions" setup in Kafka binder. So, unless this is also updated to reflect the 4th consumer (i.e. `"app.fruits.producer.partitionCount":4`), the desired behavior cannot be achieved
- Let's review why the behavior is different between SCSt and SCDF. See what needs to be changed in SCDF/Deployers to make them behave consistently for the given use-case

**Comment by garyrussell** [comment]
I am not sure I follow; there are two types of partitioning - natural partitioning in some brokers (Kafka) and application-level partitioning (using `partitionKeyExpression`). In the case of natural partitioning the partition selected depends on the client configuration; Kafka uses the following algorithm by default:

**kafka 2.4.0**
```java
/**
 * The default partitioning strategy:
 * <ul>
 * <li>If a partition is specified in the record, use it
 * <li>If no partition is specified but a key is present choose a partition based on a hash of the key
 * <li>If no partition or key is present choose the sticky partition that changes when the batch is full.
 * 
 * See KIP-480 for details about sticky partitioning.
 */
```

**earlier versions**
```java
/**
 * The default partitioning strategy:
 * <ul>
 * <li>If a partition is specified in the record, use it
 * <li>If no partition is specified but a key is present choose a partition based on a hash of the key
 * <li>If no partition or key is present choose a partition in a round-robin fashion
 */
```

I would expect the behavior you see with SCDF in SCSt alone if you specify a `partitionKeyExpression`.

This is because the partition is selected at the application level, not by the broker or its client infrastructure.

>This set up works beautifully in SCDF + Kafka when there is no partitioning characteristics is applied

That scenario is what you are comparing to SCSt above.

When a partition key expression is supplied Kafka's first default is used because the binder specifically chooses the partition.

**Comment by sabbyanandan** [comment]
I have the detail I needed on this subject. Thanks, Gary.

**Comment by pari205** [comment]
> As a user, while attempting to demonstrate scaling + partition adjustment with Kafka, I notice the following differences between a standalone SCSt run vs. when deployed via SCDF (for the same application).
> 
> _SCSt:_
> 
> * Start the consumer with 3 instances aka 3 partitions with `autoAddPartitions` set to "true"
> * Notice the partitions are automatically created for the given topic by Kafka via Kafka CLI
> * Notice also the 3 partitions are automatically assigned to 3 consumer instances, again by Kafka
> * Start 4th consumer instance; a 4th partition is automatically created in Kafka
> * Notice that the partition rebalance is automatically triggered in Kafka
> * Notice the 4 partitions are automatically assigned to 4 consumer instances, again by Kafka — all 4 consumer instances are participating in the data processing
> 
> **-VS-**
> 
> _SCDF:_
> 
> * Deploy a stream with the consumer count set to 3 (eg: `deployer.appender.count=3`) along with `autoAddPartitions` set to "true"
> * Notice that `spring.cloud.stream.bindings.output.producer.partitionCount` is set to "3" at the source; likewise, `spring.cloud.stream.instanceCount` is at "3" and `spring.cloud.stream.instanceIndex` is set individually to each of the 3 consumer app instances
> * Notice the partitions are automatically created for the given topic by Kafka via Kafka CLI
> * Notice also the 3 partitions are automatically assigned to 3 consumer instances, again by Kafka
> * Scale the consumer app to "4" (eg: `http post http://localhost:9393/streams/deployments/scale/fooz/appender/instances/4`)
> * Notice that the 4th partition is **_not_** automatically created in Kafka
> * Notice also that the 4th consumer is sitting idle and not participating in the data processing yet
> * Now, when you rolling-update the producer with `"updateProperties":{"app.fruits.producer.partitionCount":4,"app.appender.spring.cloud.stream.instanceCount":4}`, you will see that 4th partition is created for the  given Kafka topic, and likewise, the 4th consumer is now participating in data processing
> 
> _Observations / Notes:_
> 
> * This set up works beautifully in SCDF + Kafka when there is no partitioning characteristics is applied
> * However, when `partitionKeyExpression` is used at the source, SCDF treats the partitioning scenario by setting `partitionCount` at the producer — it might be required for Rabbit (since we handle the partitioning logic in spring-amqp+rabbit binder), but do we need it for Kafka also?
> * If `partitionCount` is set at the producer, it appears to be treated almost like a "static partitions" setup in Kafka binder. So, unless this is also updated to reflect the 4th consumer (i.e. `"app.fruits.producer.partitionCount":4`), the desired behavior cannot be achieved
> * Let's review why the behavior is different between SCSt and SCDF. See what needs to be changed in SCDF/Deployers to make them behave consistently for the given use-case

I am facing the same challenges, Are there any fixes around this?

**Comment by pari205** [comment]
I am referring the solution provided here...https://dataflow.spring.io/docs/recipes/scaling/autoscaling/

We used SCALE API to increase the number of instances of a customer ( Processor App), however the number of partitions remains unchanged even if the number of instances is more than the currently available partitions. I have even tried removing PartitionKeyExpression from producer.

Could you help us in understanding what I am missing here to achieve auto Add Partitions based on the consumer load? Why kafka binder is not creating the partitions?

Just to add, I am able to create partitions manually directly in kafka, so not an issue on the kafka configuration side
