### ISSUE TITLE
Test SCDF/Skipper security infrastructure on K8s using Azure Active Directory

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3712]
As a developer, I'd like to study and integrate SCDF/Skipper with Azure's AD service, so the SCDF client's running in K8s can be set up for authentication and authorization workflows using OAuth+OIDC.

**Acceptance:**
- Study how security is generally set up and used between the microservice applications running in K8s
- Determine the OAuth client credentials to integrate with Azure AD, and document it
- Determine the best approach to configure SCDF and Skipper with the OAuth credentials — it is in the deployment YAMLs directly or as Config Maps?
- Derive a strategy to implement pluggable security in SCDF's Helm Chart

**Comment by chrisjs** [comment]
spike docs in "Azure Active Directory Spike" document of gdocs

**Comment by robinsomarajv** [comment]
@sabbyanandan does the bitnami helm charts supportoauth configuration
