### ISSUE TITLE
Translate scheduler properties as deployer properties for underlying task application

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#3714]
When scheduling a task application, one can specify scheduler properties and these scheduler properties are applied to the platform scheduler options (For K8s, they will be applied as cronjob configuration). Given we only schedule the `scheduler-task-launcher` and the `scheduler-task-launcher` eventually sends the task launch request to the SCDF server, some of the scheduler properties (such as RestartPolicy, TaskServiceAccountName in case of K8s) need to be applied to the task that is being launched as well.

Depends on https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/331.

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/331.
