### ISSUE TITLE
Connecting to database via an encrypted connection using SSL

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow#3715]
**Problem description:**
As a user, into production environment,  I must to run the connections to databases using SSL connections.

I cannot find a way to configure the datasources to scdf and skipper to do this config.

**Solution description:**

A option could be to add into datasource url , some params like 
`` verifyServerCertificate=false&useSSL=true&requireSSL=true ``

I think that java source something like,

```
try 	{
String url = "jdbc:mysql://127.0.0.1:3306/sample"+ "?verifyServerCertificate=false"+
		"&useSSL=true"+
		"&requireSSL=true";
	String user = "testuser";
       String password = "testpass";
	Class dbDriver = Class.forName("com.mysql.jdbc.Driver");
	con = DriverManager.getConnection(url, user, password);
```
But, if I need to use ssl client certificates, the url jdbc connection is more complicated:

```
jdbc:mysql://10.1.2.3:3306/dbname?useSSL=true&requireSSL=true&trustCertificateKeyStoreUrl=file:///path/to/mysql-ca-truststore.p12&trustCertificateKeyStoreType=PKCS12&trustCertificateKeyStorePassword=pwd&enabledTLSProtocols=TLSv1.2
```
Then, I need more parameters into the datasource for skipper and scdf

- useSSL
- requireSSL
- trustCertificateKeyStoreUrl
- trustCertificateKeyStoreType
- trustCertificateKeyStorePassword
- enabledTLSProtocols
 
Tx

**Comment by ilayaperumalg** [comment]
Hi @eskuai ,

The configuration properties you mentioned above are part of the `spring.datasource.url` property itself and hence you need to supply them via `spring.datasource.url` as specified in [here](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_mysql) Did you try setting the property `spring.datasource.url` with all those ssl configuration properties?

**Comment by ilayaperumalg** [comment]
Hi @eskuai , Closing this issue for now (hoping the default way of setting `spring.datasource.url` works). Please feel free to re-open if you still see the issue. Thanks!

**Comment by eskuai** [comment]
Hi @ilayaperumalg 
Ok no problem. I'll test as soon as possible. 
Working in a problem with a database upgrade and ssl replicaton stop working.
Tx

**Comment by eskuai** [comment]
Ok, testing using --spring.datasource.url  i got a problem related with mariadb (certs v1 vs v3 I suppose) , because, i can login using only ca.cert into the uri connection

Tx
