### ISSUE TITLE
customize the dnsPolicy properties

### ISSUE THREAD

**Issue by xdxiaodao** [spring-cloud/spring-cloud-dataflow#3725]
Can i customize the task, flow, and scheduler job's dnsPolicy and hostNetwork properties on the kubernetes platform in src/kubernetes/server/server-config.yaml

**Comment by sabbyanandan** [comment]
@xdxiaodao: Questions like this are better suited for StackOverflow or Gitter discussion. Please share as much information about your use-case as possible, and start a thread in the forums.
