### ISSUE TITLE
Task launch fails due to currently running applications even when app is not running

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-dataflow#3733]
**Description:**
When a task fails internally, the TASK_EXECUTION table is not updated to show the task completed. SCDF thinks the task is running even if the app/pod is deleted.  It would be more accurate to use the TaskLauncher to query the platform to see what is actually running. 

Related to #3695

**Comment by dturanski** [comment]
Note the taskLauncher currently provides  `LaunchState status(taskId)` however, the `task id` is returned by `launch()`, typically generating a unique id that starts with the task name. In this case, we only have the task name, so we would  require a similar method that can query the platform  by the (base) task name.

**Comment by dturanski** [comment]
We can use the `TaskExplorer.findRunningTasks()` as we do currently. If any entries are returned, check the launch status to confirm.

**Comment by dbahatSAP** [comment]
Won't the tasks that failed to launch always be returned by findRunningTasks()?
If the plan is to always query the TaskLauncher (which I highly recommend, as I also encountered many cases were the platform got out of sync with the TaskExecutions), maybe it's better to instead use TaskExplorer.getLatestTaskExecutionForTaskName()?

**Comment by dturanski** [comment]
@dbahatSAP - This is generally the case if a runtime exception is thrown.  Per the discussion on  #3695, The plan is to disable this check except for cloudFoundry. Once that is done, we can review the logic.

**Comment by dbahatSAP** [comment]
Sound good.
If the app creation/re-creation logic is indeed cf only, perhaps a better idea would be to completely extract the logic into the CloudFoundryTaskLauncher? For comparing the previous task definition, perhaps the data be stored somewhere inside the cf app? (maybe in an env variable?)
