### ISSUE TITLE
Add support to autoconfigure Java DSL's RestTemplate for OAuth

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3736]
As a user, while using the Java DSL against an OAuth secured SCDF backend, there's no direct automation that exists to configure the SCDF client to be OAuth compliant automatically. 

Thought I can manually pass my own `RestTemplate`, which knows OAuth, I would instead prefer to use the standardized approach that could come with SCDF's Java DSL proper.

**Comment by jvalkeal** [comment]
Now that I actually tried out javadsl sample and poked a code I realised that all these works in a same way that shell does as they share a same base classes.

Created spring-cloud/spring-cloud-dataflow-samples#129 which I verified against my dataflow/uaa sample env.
