### ISSUE TITLE
High CPU rabbitmq in k8s deployment

### ISSUE THREAD

**Issue by mackoftrack** [spring-cloud/spring-cloud-dataflow#3743]
**Description:**
I noticed that rabbitmq uses high CPU in a default SCDF deployment 

**Release versions:**
2.3.0-RELEASE

**Custom apps:**
None. Default install.

**Steps to reproduce:**
Install SCDF via helm to k8s

**Screenshots:**
![image](https://user-images.githubusercontent.com/3811209/72554828-51416200-3850-11ea-8122-c9d97f9d797f.png)

**Additional context:**

**Comment by sabbyanandan** [comment]
Hi, @mackoftrack. The SCDF Helm Chart depends on the existing stable versions of the charts of RabbitMQ, Kafka, Prometheus, and others. In other words, we do not handcraft the deployment manifest for any of the middleware or database services; they are reused from the existing chart repositories. See: [helm/spring-cloud-data-flow/requirements.yaml#L6-L13](https://github.com/helm/charts/blob/master/stable/spring-cloud-data-flow/requirements.yaml#L6-L13).

That said, if the default configurations on the dependent charts reveal a spike in CPU/Memory, you may want to reach out to the chart owners for specific tuning recommendations. Alternatively, if you're familiar with what to optimize, you could either fork the chart to influence with the desired settings, or you could use the [deployment YAMLs](https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/src/kubernetes/rabbitmq) that we ship to apply similar changes, outside of Helm.

And, the obvious another thing to check is the number of producer+consumer's participating in the broker when there's a spike in CUP/Memory resources. Depending on the number of streams, you would have to adjust your Rabbit cluster topology accordingly.

**Comment by sabbyanandan** [comment]
For questions or general observations like this, please use StackOverflow or Gitter going forward.

**Comment by mackoftrack** [comment]
Fair enough. Just seems odd for rabbitmq to be consuming so much CPU on a fresh SCDF install, with no tasks, jobs, or streams running.
