### ISSUE TITLE
SCDF tasks on kubernetes not terminating

### ISSUE THREAD

**Issue by mackoftrack** [spring-cloud/spring-cloud-dataflow#3745]
**Description:**
Tasks that are manually run via the SCDF UI do not "complete" even though the have completed. i.e. the pods remain in the "running" state. This does not seem to happen with scheduled runs of the same task.

See the output of `kubectl get pods`:

```
watchworthy-buckets-scdf-watchworthy-buckets-task-15790464w549l   0/1     Completed   0          2d19h
watchworthy-buckets-scdf-watchworthy-buckets-task-15791328q67mm   0/1     Completed   0          43h
watchworthy-buckets-scdf-watchworthy-buckets-task-15792192p59nc   0/1     Completed   0          19h
watchworthy-buckets-task-4233gjz2wz                               1/1     Running     0          17m
watchworthy-buckets-task-8oze8065ek                               1/1     Running     0          19h
watchworthy-buckets-task-e1d4voz55w                               1/1     Running     0          43h
```

These are the same tasks. The top 3 were scheduled. The bottom 3 were launched via the UI.

They all end with the same log output:
`2020-01-14 16:00:51.175  INFO 1 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [FlowJob: [name=Watchworthy Bucket Job]] completed with the following parameters...`

**Release versions:**
2.3.0-RELEASE

**Steps to reproduce:**
Create a task, and launch it manually via the UI.

**Comment by mackoftrack** [comment]
I'm wondering if this is related to https://github.com/spring-projects/spring-boot/issues/16164 , although seems odd that the scheduled tasks are not having the same issue.

**Comment by mackoftrack** [comment]
Is this related? https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/292

**Comment by cppwfs** [comment]
Give it a try.   Setting `--spring.cloud.task.closecontextEnabled=true` as a command line arg may resolve the issue if you have a thread that was allocated and still running.

**Comment by sabbyanandan** [comment]
@mackoftrack: What does the `watchworthy-buckets-task` do, business-logic wise? I was going to also suggest setting `spring.cloud.task.closecontext_enabled` to "true", but it is unclear why the same task would complete when scheduled vs. when launching it manually.

So, let's see if something in the business logic is different or whether if you're setting extra configurations for schedules.

**Comment by mackoftrack** [comment]
> @mackoftrack: What does the `watchworthy-buckets-task` do, business-logic wise? I was going to also suggest setting `spring.cloud.task.closecontext_enabled` to "true", but it is unclear why the same task would complete when scheduled vs. when launching it manually.

I tried setting both of these in the properties (not sure which is correct):
```
spring:
  cloud:
    task:
      closecontext:
        enable: true
      closecontext_enabled: true
```
Same behavior.

> So, let's see if something in the business logic is different or whether if you're setting extra configurations for schedules.

There is no difference in logic. It is the same exact task, and they are both launched with the same exact arguments.

**Comment by mackoftrack** [comment]
Setting the following properties (not sure which is correct):

```
spring:
  cloud:
    task:
      closecontext:
        enable: true
      closecontext_enabled: true
```

Seems to have resolved the issue.
