### ISSUE TITLE
Replace RestTemplate with WebClient

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3758]
As the [framework will be deprecating](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/client/RestTemplate.java#L75-L81) the `RestTemplate` in the future, we would want to adapt to the `WebClient` pattern in SCDF RESTful clients, including the Java DSL.

All of the [RESTful resources](https://github.com/spring-cloud/spring-cloud-dataflow/search?q=RestTemplate+restTemplate&unscoped_q=RestTemplate+restTemplate) use `RestTemplate` today. Outside of the clients in the SCDF repo, we may have to review the integration possibilities done in the following client applications.

- CTR
- TaskLauncher Dataflow
- TaskLauncher Schedules
- Security Commons (utility used by both scdf and skipper)

**Comment by cppwfs** [comment]
We will need to update the `DataflowTemplate` to use WebClient instead of RestTemplate.   This is a precursor that has to be done before updating CTR, SchedulerLauncher

**Comment by sabbyanandan** [comment]
Based on the discussion with the Spring Framework team, we conclude that `RestTemplate` is in maintenance-only mode, and it is not slated for deprecation anytime soon. 

The corresponding `RestTemplate` javadocs has been updated with the clarification — see spring-projects/spring-framework#24503.

There's nothing more to do from SCDF's use of `RestTemplate` at this time of writing.
