### ISSUE TITLE
Stream deployment does not support application properties specified as a list

### ISSUE THREAD

**Issue by rj93** [spring-cloud/spring-cloud-dataflow#3767]
When I am creating my stream deployment I am trying to set `spring.cloud.kubernetes.config.sources[0].name` property, but when I enter this I get an error saying `The field "property" is not valid`.

Tasks have the ability to set this using specifying the `--spring.cloud.kubernetes.config.sources[0].name=my-configmap` argument, so would be good to get this added to Streams as well.

**Comment by ilayaperumalg** [comment]
Hi @rj93, My apologies for the delay. Missed this completely. 

You can specify this via `app.<app-name>.spring.cloud.kubernetes.config.sources[0].name` when deploying the stream. 

Closing this issue for now. But, feel free to re-open if you see any issues. Thanks!
