### ISSUE TITLE
Change in behaviour of task definition and launch properties between 2.2 and 2.3

### ISSUE THREAD

**Issue by djgeary** [spring-cloud/spring-cloud-dataflow#3773]
This is on Kubernetes where all properties and arguments seem to be passed as 
command line arguments of the form `--timestamp.format=yyyy`

**2.2 Behaviour:**

`task create my-timestamp --definition "timestamp --format=\"yyyy\""`

`task launch my-timestamp `
task launched with argument --timestamp.format=yyyy

`task launch my-timestamp --properties "app.timestamp.format=\"ddMMyyyy\""`
task launched with argument --timestamp.format="ddMMyyyy"

`task launch my-timestamp `
task launched with argument --timestamp.format=yyyy

ie in version 2.2 we can override a definition property for a specific launch which is functionality we have been using. If we don't supply that property the one in the definition is used.

**2.3 Behaviour:**

`task create my-timestamp --definition "timestamp --format=\"yyyy\""`

`task launch my-timestamp `
task launched with argument --timestamp.format=yyyy

`task launch my-timestamp --properties "app.timestamp.format=\"ddMMyyyy\""`
task launched with argument --timestamp.format="ddMMyyyy"

`task launch my-timestamp `
task launched with argument --timestamp.format="ddMMyyyy"

ie in version 2.3 once a definition property is specified on a launch it is changed **PERMANENTLY** and will be used for all subsequent launches unless specifically set to something else.

From what I can tell this change has been made on purpose and is linked to CI/CD functionality (which we have no current plans to use).
However it seems counter-intuitive to me: What's the point of the definition if a specific launch can change it permanently and its not obvious this has happened?

To get round this we are planning to use 'override' arguments to the 'default' properties.

**Comment by cppwfs** [comment]
This issue was identified in issue https://github.com/spring-cloud/spring-cloud-dataflow/issues/3695 and has been resolved.  
Upgrading to Spring Cloud Data Flow 3.1 or 4.0 will resolve this issue.

**Comment by sabbyanandan** [comment]
What @cppwfs meant were 2.3.1 or 2.4.0 GA releases. 😄

**Comment by djgeary** [comment]
#3695 refers to arguments not properties and was to do with concurrent launches. The '2.3' behaviour I documented above is whats happening in **2.3.1** and I'm sure 2.4 is the same as this seems to be the intended behaviour. My point is it seems to conflict with the purpose of the task definition and is not expected behaviour.

**Comment by cppwfs** [comment]
@sabbyanandan thanks for the correction.   
@djgeary You are correct.   This behavior was added  for Task CI/CD as it pertains to properties.  I can see you point on how the task definition properties not being used for subsequent task executions once they were overridden.  Let me chat with @mminella .   I'm not sure this is would facilitate a documentation update or a code update.

**Comment by cppwfs** [comment]
After some discussions, as a starting point we are going to show the properties from the previous task executions on the "Launch Tasks" page in the `parameters` text box (when the user re-executes the task).  This way the user can see what will be set.  This will be similar to what we do for the streams.

**Comment by cppwfs** [comment]
After researching the issue there seems to be no back-end update required for this issue.  Moving the issue to SCDF-UI:   https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1387
Also added notes on how to retrieve deployment information.

**Comment by djgeary** [comment]
Adding information in the UI doesn't help if you are using the shell or API.

We have client processes that launch tasks that can now produce unreliable task launches if someone else launched a the same task manually with a property in between.

I really don’t see the reasoning of 'resurrecting' properties from the execution history as it seems go against the documented functionality of task definitions and launch properties - its a breaking change to support new feature.

Even on the concept of CI/CD which we don't currently need (and seems to be the reason for this functionality change) I fail to see how managing task versions is related to properties in the execution history, although I get the impression it may be to do with the way CloudFoundry caches tasks which is not relevant to Kubernetes which we are using.

This is a major blocker for us and is preventing us upgrading to version 2.3 (without some unsustainable hacks to the dataflow installation).

Would there be a possibility of adding a flag to enable / disable this functionality? Ie where it checks the task manifest history.

**Comment by mminella** [comment]
@djgeary It's our general recommendation that when executing tasks, values that change should be passed as command line arguments and values that don't should be passed as properties.  

With that in mind, if you use arguments to do your override, the results should be the same behavior as in 2.2 since Spring Boot gives precedence to command line arguments over environment variables or `SPRING_APPLICATION_JSON` (https://docs.spring.io/spring-boot/docs//current/reference/html/spring-boot-features.html#boot-features-external-config) and arguments are not re-hydrated from launch to launch as properties are.  To be specific, I would expect the following to work:

`task create my-timestamp --definition "timestamp --format=\"yyyy\""`

`task launch my-timestamp`
task launched with argument --timestamp.format=\"yyyy\"

`task launch my-timestamp --arguments "--timestamp.format=\"ddMMyyyy\""`
task launched with argument --timestamp.format="ddMMyyyy"

`task launch my-timestamp`
task launched with argument --timestamp.format=\"yyyy\"

Let us know how this works for you.

**Comment by djgeary** [comment]
Hi @mminella. The problem is this is just a recommendation - even if the aim by both dev and ops was to abide by that someone can still launch a task that changes a property that represents a value 'that should not change' and this then interferes with subsequent launches - there is no way to prevent someone doing this.

Despite this what you suggest would go some way towards addressing the issue as we could try to enforce a rule to never use properties when launching tasks.

However we have already tried this approach and it doesn't seem to work the way you suggest. The problem I think is that with SCDF on Kubernetes all arguments and properties are passed to the task as 'command line arguments' so the Spring Boot precedence you mention doesn't seem to work.

For the timestamp example you proposed:

`task launch my-timestamp`

In both SCDF and K8S dashboards we can see the arguments being passed to the task as:

```
--timestamp.format: yyyy
--spring.datasource.username: ******
--spring.datasource.url: ******
... other arguments
```

This works as expected, but then for 

`task launch my-timestamp --arguments "--timestamp.format=\"ddMMyyyy\""`

we see the following arguments being passed:

```
--timestamp.format: yyyy
--spring.datasource.username: ******
--spring.datasource.url: ******
... other arguments
--timestamp.format: "ddMMyyyy"
```

ie BOTH the 'definition property' and the 'launch argument' are passed to the Boot app the same way. 

These two then seem to get combined into a single comma separated property `yyyy,"ddMMyyyy" `

(we did some logging in our own task to determine this - I think it may be due to the use of `StringUtils.collectionToCommaDelimitedString` in the `String getProperty(String name)`
method in https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/env/CommandLinePropertySource.java)

For for the timestamp example you actually get this line in the log 
`
2020-02-28 14:12:13.300  INFO 1 --- [           main] TimestampTaskConfiguration$TimestampTask : 2020,"28022020"`

as it sort of manages to use the `yyyy,"ddMMyyyy"` value, but obviously in general this is unusable (eg if it was a number you were trying to use if would just be unparseable)

So from what I can see the override doesn't work as you expect? Or is there some way we can get the property precedence you mention to work?

**Comment by djgeary** [comment]
I've looked into this a little more based on your comment about the Spring Boot precedence of environment variables or SPRING_APPLICATION_JSON

It looks like this is related to the deployer entry point configuration (https://docs.spring.io/spring-cloud-dataflow/docs/2.4.0.RELEASE/reference/htmlsingle/#_entry_point_style). We seem to be using `exec` which is the default. `shell` doesn't seem to make sense as it doesn't pass the command line args, so presumably `boot` would make this work?

I tried 
`task launch my-timestamp --properties "deployer.timestamp.kubernetes.entryPointStyle=boot" --arguments "--timestamp.format=\"ddMMyyyy\""`
and this seems to pass the arguments and properties separately and correctly use the argument as an override. 

So we can set `kubernetes.entryPointStyle=boot` as the default for all tasks so get this to work as expected.

Maybe this should be the default instead of `exec`, its not an obvious thing to have to configure.

**Comment by mminella** [comment]
@djgeary Thank you for doing that extra due diligence.  You are correct on the behavior and after talking to some of the rest of the team, I'd say the following:

* **Short term:** Yes, moving to an entry point style of boot should address your issue.
* **Long term:** I think that SCDF should honor the order of precedence that Boot honors when passing in configurations.  To that end, if you have a property of some kind that has been configured both as a property and a command line arg, SCDF should not pass them both as command line args and the property should be removed in a de-duping operation.  An alternative implementation for this exercise would be to pass in the properties via a `SPRING_APPLICATION_JSON` argument which would then allow for overriding of options in the way I suggested without the need to de-dupe.  Let me get with the team and figure out the best way to handle this long term.  I'd expect a new issue to be opened based on our conversations so stay tuned.

**Comment by chrisjs** [comment]
precedence filtering is in https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/commit/d49cd80d7f77b3697e3158e4f505952345b387c0 and removal of CD is covered in https://github.com/spring-cloud/spring-cloud-dataflow/issues/3843
