### ISSUE TITLE
Having more than 1000 entries in the table `app_registration` causes different errors

### ISSUE THREAD

**Issue by xetra11** [spring-cloud/spring-cloud-dataflow#3787]
**Description:**
We had more then 1000 apps registered. It seems that the SCDF frontend is only fetching 1000 and no more. We truncated the table and the issue was resolved.

**Release versions:**
springcloud/spring-cloud-dataflow-server:2.3.0.RC1

**Comment by sabbyanandan** [comment]
Hi, @xetra11. That's incredible to hear that you have had >1000 apps in the registry. Curious whether if they were are all unique apps and what do the majority of the applications do from the business perspective? Anything that you can share would help reason through the requirement.

As for the limit, there's probably a hardcoded limit around, and that is not a good thing. We can look into loosening it up to make it dynamic, though.

I am looking forward to hearing your use-case requirements.

**Comment by jvalkeal** [comment]
This is kind of a design flaw how apps are shown. Theoretically we should have designed every location in UI to use proper paging or not use paging on a rest api at all. Some part of an UI don't use paging and thus original workaround was to request one with size 1000.

It might be even better to fetch less and do multiple queries. We probably have this issue in other parts of an UI as well.

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-dataflow-ui #1381](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1381) via [**ZenHub**](https://www.zenhub.com/)
