### ISSUE TITLE
Scheduled task pods not cleaned up

### ISSUE THREAD

**Issue by mackoftrack** [spring-cloud/spring-cloud-dataflow#3793]
**Description:**
k8s pods from tasks that are started via the scheduler are not cleaned up, while the task scheduler pods themselves are limited to 3.

```
# kubectl get pods

myschedule-mytask-1581238800-c27q9   0/1     Completed   0          2d13h
myschedule-mytask-1581325200-cf9pg   0/1     Completed   0          37h
myschedule-mytask-1581411600-86xjp   0/1     Completed   0          13h

mytask-5lkm7v75j5   0/1     Completed   0          6d13h
mytask-68dldpxllq   0/1     Completed   0          4d13h
mytask-gxezp98dmz   0/1     Completed   0          3d13h
mytask-jv4eq6yqe3   0/1     Completed   0          7d21h
mytask-l48vxzng32   0/1     Completed   0          2d13h
mytask-n8dqgrp82x   0/1     Completed   0          5d13h
```

**Release versions:**

2.4.0.RELEASE 

**Steps to reproduce:**
Create task. Create schedule. View created pods.

**Expected behavior:**
Task pods are limited to 3 runs like the launcher is, or there should be some mechanism to clean up old completed pods.

**Comment by chrisjs** [comment]
should be in k8s deployer. looks like a dup of https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/363

**Comment by chrisjs** [comment]
i don't think tasks pods where ever cleaned up automatically (https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/363). not sure how this plays into the new task launcher stuff tho @cppwfs @ilayaperumalg

**Comment by to-wi** [comment]
also confirming/adding some information for further clarification:
Scheduled tasks create two pods per execution:
- a 'scheduling' pod (named after the task schedule) -> `myschedule-mytask`
- a 'worker' pod (named after the scheduled task) -> `mytask`
The 'scheduling' pod gets cleaned up as configured via `jobsHistoryLimit`, but the 'worker' pod does not. Therefore the 'worker' pods pile up (in a finished state) in Kubernetes.
