### ISSUE TITLE
Update entrypointstyle docs

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow#3797]
https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/366 changes the behavior of entrypointstyle property, the docs at: https://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#_entry_point_style should be updated to account for this change

Let's also verify the Microsite references are updated.

**Comment by chrisjs** [comment]
merged https://github.com/spring-cloud/spring-cloud-dataflow/pull/3807/files in DF but keeping open for changes in microsite

**Comment by chrisjs** [comment]
re-opening for microsite changes

**Comment by ilayaperumalg** [comment]
https://github.com/spring-io/dataflow.spring.io/pull/204

**Comment by chrisjs** [comment]
merged
