### ISSUE TITLE
Align dependencies with BOMs in Spring Cloud

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#381]
To allow users to manage dependencies in application projects
for data flow and the rest of Spring Cloud independently, we
need to clean up the BOM a bit and use the Cloud BOMs individually
in the libraries in data flow.

**Comment by sabbyanandan** [comment]
@markpollack: I think this is a duplicate of spring-cloud/spring-cloud-dataflow#350; please reopen it if you think otherwise.
