### ISSUE TITLE
Passing java opts containing multiple '=' signs

### ISSUE THREAD

**Issue by yrobert** [spring-cloud/spring-cloud-dataflow#3817]
**Description:**
I'm able to pass java opts arguments during task launching through the UI: 
`deployer.<app>.local.javaOpts=-agentpath:/tmp/jprofiler11.1.1/bin/linux-x64/libjprofilerti.so=port=5005,nowait`

But it doesn't accept this:
`deployer.<app>.local.javaOpts=-agentpath:/tmp/jprofiler11.1.1/bin/linux-x64/libjprofilerti.so=port=5005,offline,id=123`

**Release versions:**
Version: 2.4.0.RELEASE

**Screenshots:**
![image](https://user-images.githubusercontent.com/3584191/75864756-c964e680-5e02-11ea-9491-b33fefd955e7.png)

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-dataflow-ui #1398](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1398) via [**ZenHub**](https://www.zenhub.com/)
