### ISSUE TITLE
Passing multiple environment variable when launching task for kubernetes

### ISSUE THREAD

**Issue by umutcann** [spring-cloud/spring-cloud-dataflow#3818]
Hi,

We want to deploy our application to Openshift.

We need to set environment variable. When we set one env variable, we could see ENV= DEV

deployer.myapp.kubernetes.environmentVariables=ENV=dev

![image](https://user-images.githubusercontent.com/18632831/75887747-4dd35b80-5e3b-11ea-9817-764454c8b757.png)

But we tried to add 2 more environment variable, we got error like below.

deployer.myapp.kubernetes.environmentVariables=ENV=dev,CONFIG_SERVER_HOST=<url>,CONFIG_SERVER_PORT=8080

![image](https://user-images.githubusercontent.com/18632831/75887587-12d12800-5e3b-11ea-86c5-ec5664b762a2.png)

I investigate to DeploymentPropertiesUtils.java. Comma is used as delimeter. 

https://github.com/spring-cloud/spring-cloud-dataflow/blob/15ca56d8afb982dcab82fbc70a4c60fb39557fb7/spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/DeploymentPropertiesUtils.java#L77

I think we are getting error because of that. Application is waiting a prefix like app or deploy.

But environment variable parser of Spring Cloud Deployer Kubernetes library is using comma as delimeter.

https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/daf4f41708e47d91cf6109472cc59b6649bc4ae8/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DefaultContainerFactory.java#L376 

How can we set multiple env variable as Parameters?

Thanks in advance.

**Comment by cppwfs** [comment]
I believe that this scenario is discussed here: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_environment_variables

**Comment by umutcann** [comment]
@cppwfs 

I looked it. But our values of environment variable already has no comma. 

It explains that If your value has comma. 

I updated my question just a second ago after your response.

Could you please review it?

I think there is a bug.

Umut.

**Comment by cppwfs** [comment]
I agree.   After looking through the code it does not support single `'` to prevent the parsing of the value as shown below.
deployer.timestamp.kubernetes.environmentVariables='ENV=dev,CONFIG_SERVER_HOST=,CONFIG_SERVER_PORT=8080'

**Comment by filibor** [comment]
It doesn't work even if I specify 2 environment variables like this:
deployer.app.kubernetes.environmentVariables=ENV1=VAL1, deployer.app.kubernetes.environmentVariables=ENV2=VAL2

Only last one environment variable is applied (ENV2=VAL2).

**Comment by cppwfs** [comment]
I just retested this issuewith 2.5.RC1 release and this issue is resolved.  Please retest on your side.  Thanks!

**Comment by sabbyanandan** [comment]
Oh, btw, 2.5 GA is also available now. Please let us know if you see any anomalies.
