### ISSUE TITLE
Add Scheduler in Local Deployment

### ISSUE THREAD

**Issue by duyetphamm** [spring-cloud/spring-cloud-dataflow#3823]
As a developer, I want to use Scheduler feature on local server for testing. Please support adding this feature.

**Comment by sabbyanandan** [comment]
@duyetphamm: Please follow the various recommendations listed under the scheduling support for `Local`: https://dataflow.spring.io/docs/2.5.0.SNAPSHOT/feature-guides/batch/scheduling/#scheduling-a-batch-job
