### ISSUE TITLE
Upgrade Tomcat 9.0.31

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#3824]
As this is done via boot deps we simply need to go through this process.

- 2.4.x
  - [x] spring-cloud-dataflow-build 2.4.1
  - [x] spring-cloud-dataflow 2.4.2
  - [x] spring-cloud-skipper 2.3.2
  - [x] spring-cloud-deployer 2.2.2
  - [x] spring-cloud-deployer-local 2.2.2
  - [x] spring-cloud-deployer-cloudfoundry 2.2.2
  - [x] spring-cloud-deployer-kubernetes 2.2.2
- 2.3.x
  - [ ] spring-cloud-dataflow 2.3.2
  - [ ] spring-cloud-skipper 2.2.3
  - [ ] spring-cloud-deployer 2.1.2
  - [ ] spring-cloud-deployer-local 2.1.2
  - [ ] spring-cloud-deployer-cloudfoundry 2.1.3
  - [ ] spring-cloud-deployer-kubernetes 2.1.3

**Comment by sabbyanandan** [comment]
Stale; closing.
