### ISSUE TITLE
Passing java opts containing multiple '=' signs

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#3831]
@sabbyanandan commented on [Thu Mar 12 2020](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1398)

@yrobert commented on [Wed Mar 04 2020](https://github.com/spring-cloud/spring-cloud-dataflow/issues/3817)

**Description:**
I'm able to pass java opts arguments during task launching through the UI: 
`deployer.<app>.local.javaOpts=-agentpath:/tmp/jprofiler11.1.1/bin/linux-x64/libjprofilerti.so=port=5005,nowait`

But it doesn't accept this:
`deployer.<app>.local.javaOpts=-agentpath:/tmp/jprofiler11.1.1/bin/linux-x64/libjprofilerti.so=port=5005,offline,id=123`

**Release versions:**
Version: 2.4.0.RELEASE

**Screenshots:**
![image](https://user-images.githubusercontent.com/3584191/75864756-c964e680-5e02-11ea-9491-b33fefd955e7.png)

---

@oodamien commented on [Thu Mar 12 2020](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1398#issuecomment-598219269)

@sabbyanandan It's not a validation on the UI side but on the server side.

Request send to the server:
![image](https://user-images.githubusercontent.com/487067/76531998-4a148a00-6476-11ea-82ff-87cecd5bde45.png)

Parameter in the request header:
![image](https://user-images.githubusercontent.com/487067/76531936-3537f680-6476-11ea-8520-f1dba0479ba9.png)

---

@ilayaperumalg commented on [Mon Mar 16 2020](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1398#issuecomment-599509730)

The value at the HTTP request body with the multiple `=` sign gets truncated by the HTTP message converter. We need to investigate it further to see why the message converter behaves this way.

**Comment by ilayaperumalg** [comment]
Cherry-picked and pushed into 2.4.x as eed3c71

**Comment by yrobert** [comment]
Thx you all! I can now perform offline profiling of my batches

**Comment by ilayaperumalg** [comment]
Great to hear and thank you for the confirmation!
