### ISSUE TITLE
Add support to launch composed tasks to different platform accounts

### ISSUE THREAD

**Issue by antoniosantacruz** [spring-cloud/spring-cloud-dataflow#3832]
Hi collegues.

I am using dataflow server 2.3.1.RELEASE with CTR 2.1.3.RELEASE.

Trying to execute a composed task that extracted directly from documentation [here](https://dataflow.spring.io/docs/2.3.x/batch-developer-guides/batch/data-flow-composed-task/), the next error happens.

`java.lang.IllegalStateException: No Launcher found for the platform named 'default'.  Available platform names are [localDevDebug, localDev]
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService.findTaskLauncher(DefaultTaskExecutionService.java:637) ~[spring-cloud-dataflow-server-core-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService.executeTask(DefaultTaskExecutionService.java:271) ~[spring-cloud-dataflow-server-core-2.3.1.RELEASE.jar:2.3.1.RELEASE]`

The problem happens because in my configurartion I have two accounts for local platform, but neither of them is the default one. 

In order to execute it from dataflow dashboard, I choosen in the combo one of the available platforms expecting it was used to execute both tasks in my composed task. As below

![image](https://user-images.githubusercontent.com/12963916/76788759-dba83280-67bb-11ea-9e03-c215596f7576.png)

But it doesn't work.

More tests that I did with no success:

- launch de composed task with the property: deployer.spring.cloud.dataflow.task.platformName=localDev

- launch de composed task with the argument:
composed-task-properties=spring.cloud.dataflow.task.platformName=localDev

- specify a deployment property for each one of the tasks (very tedious), and I've discovered that:
   TaskServiceUtils class is used by DefaultTaskExecutionService, to create the request that CTR must to process, adds deployer properties using this code:
`result += String.format("%s%s.%s.%s=%s", subTaskName, prefix,
					subTask.getName(),
					taskProperty.substring(subTaskName.length()),
					taskDeploymentProperties.get(taskProperty));`

So in my case I've insert  `deployer.ct-statement.billsetuptask.spring.cloud.dataflow.task.platformName=localDev`. Using the code above this parameter is transformed into this one `deployer.ct-statement-billsetuptask.deployer.billsetuptask.spring.cloud.dataflow.task.platformName=localDev` and send to the CTR as an app property using this key `app.composed-task-runner.composed-task-properties`.

Effectively seems that this `composed-task-properties` are used by CTR, actually by StepBeanDefinitionRegistrar to configure the steps to be executed. This one eliminate just the prefix relative to the composed task so in my case the deployment property that ends up in the step is `deployer.billsetuptask.spring.cloud.dataflow.task.platformName=localDev` but the DefaultTaskExecutionService on the server is specting a deployment property just named `spring.cloud.dataflow.task.platformName` to find out what platform
must to be used on launching.

So for me the SCDF server and CTR seems to be discoordinated in order to pass the platform to each task.

I am asking for being capable to inform just once the platform one way or another in the composed task, and use it to execute all the tasks in the composed one.

In the documentation I was not capable to find information about how the platform should be specified at composed tasks. Maybe I've missed something.

**Comment by sabbyanandan** [comment]
@antoniosantacruz: Thank for the thorough details. It'd help with the analysis — which we will soon. 

As an FYI, when we merge CTR in SCDF as an integral component (it has always been treated that way but it is delivered as a separate app today) (see: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3778), we have the opportunity to eliminate extra layers of configurations and property overrides. In other words, the platform selection in SCDF is sufficient to be able to instruct CTR to do its launch against the chosen platform automatically. Like this, we see more benefits merging them.

**Comment by cppwfs** [comment]
This issue requires us to do 2 things:
1) Composed Task Runner needs to be able to support the ability to allow the user to specify a specific platform for all tasks that are launched by CTR.
2)  Composed Task Runner needs to be able to support the ability to allow the user to specify a specific platform for each of the tasks launched by CTR with a default if not specified for a specific task.
3) SCDF needs to be able to send the platform to CTR as a parameter that it can parse.

**Comment by cppwfs** [comment]
After talking with mminella, we decided to have an MVP where a each task in the workflow will use the same platform from which the CTR was launched.   If users request a individual platform launch for specific tasks in the workflow, that will be a new issue.
