### ISSUE TITLE
spring.cloud.task.tablePrefix=yourPrefix does not create Tables on its own

### ISSUE THREAD

**Issue by gargpune** [spring-cloud/spring-cloud-dataflow#3844]
As per the instructions, I was trying to change the prefix for Spring Cloud Task Tables using property spring.cloud.task.tablePrefix. But this does not create tables on its own with a custom prefix. However, there are DB Specific SQL files. Am I missing anything or in case of a custom prefix, we need to create tables explicitly and to refer those we have to use "spring.cloud.task.tablePrefix".

https://docs.spring.io/spring-cloud-task/docs/current/reference/#features-table-prefix

**Steps to reproduce:**
- Follow hello world example
- Add this property in application.properties spring.cloud.task.tablePrefix=TEST_

**Screenshots:**
<img width="1392" alt="Screen Shot 2020-03-23 at 1 51 20 PM" src="https://user-images.githubusercontent.com/5604353/77346978-7dc0a100-6d0d-11ea-9000-bcadd062a771.png">

**Additional context:**
If we need to create tables explicitly, Could you please update the documentation ?

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-task #653](https://github.com/spring-cloud/spring-cloud-task/issues/653) via [**ZenHub**](https://www.zenhub.com/)
