### ISSUE TITLE
Single Jar : Selction to user to run which job if more than one jobs have @EnableTask

### ISSUE THREAD

**Issue by hbutalia** [spring-cloud/spring-cloud-dataflow#3847]
**Problem description:**
I have three jobs have @EnableTask in the same jar. I want to run one at a time from cloud-dataflow-ui is it possible?
if the feature is already there can you please let me know how can I use it with some pointers to example.

This feature will really be helpful if already not there

**Comment by sabbyanandan** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-dataflow/issues/3848.
