### ISSUE TITLE
Arm64 docker version

### ISSUE THREAD

**Issue by kjellmoens** [spring-cloud/spring-cloud-dataflow#3855]
Hi,

Are there any plans to release a ARM64 Docker image ?
Or can I help in providing one ?

**Comment by sabbyanandan** [comment]
Hi, @kjellmoens. We do not have any plans to maintain multiple variants of container images with different OS layers. We haven't heard much of this as a requirement coming from the broader community. 

Generally, though, I have noticed most of the community folks build their own images (with our binary), to not only use a different OS, but also to include the licensed JDK (e.g. Oracle), and other security compliance layers as defined by their Central IT.

Please feel free to build + maintain your images with the official binaries that we ship to Maven central.
