### ISSUE TITLE
NPE thrown when a user attempts to cancel a partitioned worker task

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#3857]
A user will get a NPE at line https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java#L707
when attempting to cancel a partitioned worker through dataflow.   This is because the worker was not launched by dataflow but rather the deployer of the manager task.   So to resolve the issue, if we find that there is no platform associated with a task, see if the task has a parent and then use the parent's platform instead.   If the task does not have a parent, then throw a new exception other than NPE.

**Comment by sabbyanandan** [comment]
@cppwfs: Maybe we already handled this in 2.8.x; perhaps you can help review the latest code and confirm. If the NPE exists, let's please handle/clean it up.

**Comment by cppwfs** [comment]
@sabbyanandan this is still a gap.

**Comment by jvalkeal** [comment]
lgtm
