### ISSUE TITLE
Study packaging options for K8s deployment

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3858]
As a developer, I'd like to study the packaging options for SCDF on K8s.

Today, we have the following 2 provisioning options, and they are both widely adopted.
1) [Deployment YAMLs](https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/src/kubernetes)
2) [Helm chart](https://hub.helm.sh/charts/stable/spring-cloud-data-flow) (_Helm 3.0 compatibility is underway; see: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3850_)

The goal of this spike is to explore the following tooling and do a feasibility study.
1) Deployment YAMLs + [kapp](https://get-kapp.io/) + [kbld](https://get-kbld.io/)
2) Deployment YAMLs + [kapp](https://get-kapp.io/) + [sheaf](https://github.com/bryanl/sheaf)
3) Helm + [kapp](https://get-kapp.io/) + [kbld](https://get-kbld.io/)
4) Helm + [kapp](https://get-kapp.io/) + [sheaf](https://github.com/bryanl/sheaf)

**Acceptance:**
- The combination as described ^^ may not be valid, so let's find the right set that we need for packaging
- See if any of these tools support anything around day-2 (eg: version upgrades)
- Document findings

**Comment by markpollack** [comment]
Kustomize should be on the list, so that provided yaml can be easily setup for consumption via this tool.

**Comment by markpollack** [comment]
There has been some progress in replicated since last we looked - would be nice to try it again.

**Comment by glyn** [comment]
Replicated kots has some nice features, but also some weaknesses:
* the [detection](https://github.com/replicatedhq/kots/blob/c68b21bd301e680444a4d4dc237ae54af622b25a/pkg/image/builder.go#L238) of images in YAML files is quite primitive and inextensible: 
* image copying relies on github.com/containers/image which doesn’t _appear_ to preserve (repo) digests
* images in `.airgap` files are stored as docker tar files. These are docker proprietary, they don’t help to preserve (repo) digests (since `docker push` doesn't guarantee to preserve repo digests), and the layers aren't deduplicated.

`kbld` and `sheaf`, by comparison, depend (transitively) on [ggcr](https://github.com/google/go-containerregistry) which preserves digests when copying images between registries and which supports storing images in OCI image layouts.

**Comment by markpollack** [comment]
seems like there are many more features/functionality in replicated wrt to overall day-2 mgmt, licensing, etc than command line tools.  Perhaps it is worth to bring up these points with the folks at replicated since the weakness you mention are concentrated in one specific functional area.

**Comment by marccampbell** [comment]
Thanks for checkout out kots. Great feedback. A few things to add to this conversation:

- Agreed. While KOTS scans the manifests for images and extracts them this isn't very flexible or extensible. This works in many use cases, but there are definitely some that this system won't pick up (CRDs, new object types, etc). KOTS does support enumerating images by including a `apiVersion: kots.io/v1beta1, kind: Application` that includes a `spec.additionalImages` array (https://github.com/replicatedhq/kots/blob/a9311d339e0a342c8f83e14d76d00e8b13fb19e2/kotskinds/apis/kots/v1beta1/application_types.go#L56).

-  github.com/containers/image: agreed completely here. There are some nice utilities exposed here (like copy from x -> y where x and y can be reg->reg or tar->reg).  containers/image does support the OCI format, and I wonder if there's a way to make this preserve the repo digest.  I don't have an answer here, but this is a great point.

- again, agreed completely. In the currently .airgap file format, we aren't doing anything to minimize file size. Layers will be duplicated, and this is inefficient. When updating a package with the smallest update, the entire airgap bundle is regenerated, which is not ideal.

We should take a look at `kbld` and `sheaf` in KOTS to address these problems. If KOTS can lose the dependency on docker-proprietary format and improve the airgap package size, I don't see any downsides.

(I'm going to open an issue in the replicatedhq/kots repo to explore what it would take to do this)

**Comment by chrisjs** [comment]
added "Kubernetes Packaging Options Spike" document to gdocs
