### ISSUE TITLE
Unify docker maven plugins

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow#3868]
- Currently the Data Flow Server is using https://github.com/fabric8io/docker-maven-plugin 
- Currently Skipper is using https://github.com/spotify/dockerfile-maven
- App starters are using https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin
- CI plans should be verified & updated as needed

**Comment by trisberg** [comment]
I don't see Skipper using the Spotify plugin, looks like same plugin as SCDF.

https://github.com/spring-cloud/spring-cloud-skipper/blob/master/spring-cloud-skipper-server/pom.xml#L101-L103

https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server/pom.xml#L116-L118

**Comment by trisberg** [comment]
Looks like @ilayaperumalg just changed it some days ago

**Comment by trisberg** [comment]
This was the issue: https://github.com/spring-cloud/spring-cloud-skipper/issues/950

Commits were:

https://github.com/spring-cloud/spring-cloud-skipper/commit/9c59a101937bb7ba8f3965bef263ecba854167dd

and

https://github.com/spring-cloud/spring-cloud-skipper/commit/165990b366fed6a1e38b3014e14076671272f062

**Comment by sabbyanandan** [comment]
Correct; we recently switched for consistency.
