### ISSUE TITLE
Add TAP support for task apps (including batch jobs)

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#387]
As a user, I'd like to tap a task application (including batch job), so I can collect `TaskExecutionListener` events in real-time through a streaming pipe.

**Example:**
```
dataflow:>task create --name myHttpJob --definition "httpJob" --deploy
dataflow:>stream create --name aggregatedEvents --definition ":job:myHttpJob >log" --deploy
dataflow:>task launch myHttpJob
```

**Acceptance:**
- DSL support to tap `TaskExecutionListener` events is available
- DSL semantics for tapping a task application is documented
- Examples included

**Comment by sabbyanandan** [comment]
Depends on spring-cloud/spring-cloud-task#11

**Comment by ilayaperumalg** [comment]
Once the PR https://github.com/spring-cloud/spring-cloud-task/pull/117 is merged, all we need is to add instruction on how to create a tap on task execution events as we need to create a stream that connects to a named destination `task-events`.

For instance, when a task application (with `spring-cloud-task-stream` in its classpath) is launched, the task execution events are published to the destination specified as `spring.cloud.stream.bindings.task-events.destination` (for example: events-destination) in the broker. At the data flow side, all we need is:

```
stream create task-events-consumer --definition ":events-destination > mySink" --deploy
```
to create a tap on the events.
