### ISSUE TITLE
Move applications section to Microsite

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3883]
See: https://docs.spring.io/spring-cloud-dataflow/docs/2.4.2.RELEASE/reference/htmlsingle/#supported-apps-and-tasks

**Comment by ilayaperumalg** [comment]
This is merged into microsite via https://github.com/spring-io/dataflow.spring.io/commit/3207cec1e2cbf683a24160940376cb0665b95f1e
