### ISSUE TITLE
Contribute bitnami/spring-cloud-data-flow Helm chart

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3886]
Adding this to track https://github.com/bitnami/charts/issues/2346, so we could scope the relevant adjustments to core infra if anything comes up.

**Comment by chrisjs** [comment]
"Bitnami Chart Notes" gdoc has info on current findings

**Comment by chrisjs** [comment]
AT's can be run against the chart, so i think we are good here. https://github.com/bitnami/charts/pull/3102 needs to be applied for kafka, but otherwise works OOTB
