### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Cannot load driver class: org.mariadb.jdbc.Driver

### ISSUE THREAD

**Issue by javaHelper** [spring-cloud/spring-cloud-dataflow#3887]
I've posted the complete issue here: https://stackoverflow.com/questions/61268288/caused-by-java-lang-illegalstateexception-cannot-load-driver-class-org-mariad.

Please guide.

**Comment by sabbyanandan** [comment]
Duplicates StackOverflow post/question.
