### ISSUE TITLE
Add support to cleanup task executions

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3902]
As a user, I'd like the ability to clean up all the task executions, so when I'm in an active dev mode on CF, I have the ability to clean slate the task footprint quickly.

Currently, we have the support to clean up the execution by a particular task execution ID.
> dataflow:>task execution cleanup --id

It would be useful to expose the following option:
> dataflow:>task execution cleanup --all

**Acceptance:**
- Issuing `--all` would clean up all the task executions that aren't actively running or in use by some other state in SCDF. 
- Attempt to clean up any and all and not terminate if any of the executions are not in an inconsistent state or if it is not deletable.
- Show the resulting cleanup count in the response.
- If something fails, show the stacktrace as part of the resulting response.

**Comment by sabbyanandan** [comment]
This option would be a highly risky command to run in a higher-level environment like production. Especially, with the tasks as scheduled, and when you attempt to do this across all executions, things could get really bad, very fast.

**Comment by sabbyanandan** [comment]
Likewise, we could also open up an option to optionally delete the associated executions when the task is destroyed.

> dataflow:>task destroy foo --cleanupExecutions

**Comment by sabbyanandan** [comment]
We already support optionally also deleting task executions when destroying the task definition via https://github.com/spring-cloud/spring-cloud-dataflow/issues/3903 — available since v2.6.1.

**Comment by mminella** [comment]
@sabbyanandan Do we have a confirmation step for these deletes? I think if we did it, running a count query and presenting the user with how many task executions are about to be deleted would be a good compromise. Something like:
```
dataflow:>task execution cleanup --id
dataflow:> About to delete 1 task executions and related records, are you sure (Y/n)? Y
dataflow:> 1 task executions deleted
...
dataflow:> task execution cleanup --all
dataflow:> About to delete 14293 task executions and related records, are you sure (Y/n)? Y
dataflow:> 14293 task executions deleted.
```

**Comment by sabbyanandan** [comment]
Oh, that sounds like a great idea. I believe there's that option in Shell to be able to ask for user's confirmation. We could derive the count and build the experience around it. Thanks, @mminella!

**Comment by sabbyanandan** [comment]
cc: @cppwfs @ilayaperumalg — let us know if you have any additional recommendations / concerns.

**Comment by cppwfs** [comment]
I think this is a great addition for those folks in development and testing.   IIIIII like it!
