### ISSUE TITLE
Update to using buildpacks to create container image.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#3906]
Investigate using the spring boot maven plugin to create a container image.  For 2.5, we are on boot 2.2x, but see if we can use a 2.3 milesteone/rc version of the boot plugin.  if not, would need to invoke pack cli tool in some way.

**Comment by sabbyanandan** [comment]
Closing in favor of  https://github.com/spring-cloud/spring-cloud-dataflow/issues/3890.
