### ISSUE TITLE
Prepare the helm chart for v2.5

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3911]
As we close the 2.5 release tag this week, let's prep and get the chart ready for PR submission.

- Check if there are any new K8s configs that we need to port it over
- Review the metadata labeling requirement and if any of that applies to the chart
- Finalize the required changes; test it on the supported distros

**Comment by sabbyanandan** [comment]
As part of this effort, let's also adjust the chart to accept a optional `Ingress` resource, so the prom+graf stack is accessible as part of the getting-started experience.

cc:/ @trisberg

**Comment by sabbyanandan** [comment]
Example:

```
helm install --name scdf \
  --set features.monitoring.enabled=true \
  --set server.service.type=ClusterIP \
  --set grafana.service.type=ClusterIP \
  --set ingress.enabled=true \
  --set ingress.server.host=scdf.192.168.64.200.xip.io \
  --set ingress.grafana.host=grafana.192.168.64.200.xip.io \
  ./spring-cloud-data-flow
```

**Comment by trisberg** [comment]
The [22254 PR](https://github.com/helm/charts/pull/22254) adds the ingress.

When the PR is merged you can:

1. Install NGINX ingress controller:

```
helm install --name nginx-ingress --namespace nginx-ingress stable/nginx-ingress --wait
```

2. Look up the ingress IP

```
ingress=$(kubectl get svc nginx-ingress-controller -n nginx-ingress -ojsonpath='{.status.loadBalancer.ingress[0].ip}')
```

3. Deploy Data Flow into a `scdf-system` namespace

```
helm install --name scdf --namespace scdf-system \
  --set features.monitoring.enabled=true \
  --set server.service.type=ClusterIP \
  --set grafana.service.type=ClusterIP \
  --set prometheus.proxy.service.type=ClusterIP \
  --set ingress.enabled=true \
  --set ingress.protocol=http \
  --set ingress.server.host=scdf.${ingress}.xip.io \
  --set ingress.grafana.host=grafana.${ingress}.xip.io \
  stable/spring-cloud-data-flow
```

**Comment by sabbyanandan** [comment]
Addressed via https://github.com/helm/charts/pull/22313.
