### ISSUE TITLE
Document SCSt 3.x interop expectations in SCDF

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3916]
As a continuation from https://github.com/spring-cloud/spring-cloud-dataflow/issues/3865, it'd be good to document the expectations in SCDF in the context of custom applications.

_See also a report from SO for [background](https://stackoverflow.com/questions/61484547/wrong-kafka-topic-names-for-spring-cloud-function-app-deployed-as-part-of-spring)._

**Acceptance:**
- Add a new recipe or a guide in Microsite with a sample
- Cross-link the Microsite URL in ref guide under the Appendix
- Perhaps also drop it under GH Wiki, too

**Comment by ilayaperumalg** [comment]
We can update the documentation once https://github.com/spring-io/dataflow.spring.io/pull/236 is merged.
