### ISSUE TITLE
Backport commits to 2.4.x

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3925]
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/commit/2c25b39bf6ce96dcfee6e3be3cb857704c7ddac1
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/commit/9f6d3a9008b84b2efceed9dab6deeb467babacab
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/commit/d8ba5ea643f011b57b5797206db8e899f53656d6
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/commit/268bb3c87353f005ab3879ea20c873260ff58fd4
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/commit/6babe68aa92036528bbcafb1d9d76d5504c03795
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/commit/7d0cce3931b66acc844f3ef845078df66dd4353e
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/commit/6b99550b068ddec1a5eb871683a82dd44d7e5732

**Comment by ilayaperumalg** [comment]
For some of the security fixes, we need to have similar back-porting changes into spring cloud common security config as well.

**Comment by ilayaperumalg** [comment]
Pushed the [change](https://github.com/spring-cloud/spring-cloud-common-security-config/commit/0aedc02c046d9628d6af669155ec302e189cc916) into Spring Cloud Common Security Config 1.2.x

**Comment by ilayaperumalg** [comment]
Updated few other commits required along with the original commits.

Pushed the changes into 2.4.x: https://github.com/spring-cloud/spring-cloud-dataflow/tree/2.4.x
