### ISSUE TITLE
Docker Compose fails to instantiate Skipper successfully

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3926]
As a user, while starting Docker Compose on 2.5 BS release, I run into the following error.

> dataflow-server    | 2020-05-04 20:39:34.058  WARN 1 --- [nio-9393-exec-7] o.s.c.d.s.controller.AboutController     : Skipper Server is not accessible
dataflow-server    |
dataflow-server    | org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://skipper-server:7577/api/about": skipper-server: Name or service not known; nested exception is java.net.UnknownHostException: skipper-server: Name or service not known

Steps:
```
docker system prune

wget https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/master/spring-cloud-dataflow-server/docker-compose.yml

export DATAFLOW_VERSION=2.5.0.BUILD-SNAPSHOT
export SKIPPER_VERSION=2.4.0.BUILD-SNAPSHOT
docker-compose up
```

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-dataflow/commit/01cdafc1039bdd8e39e11d2008fb6e8aab3e6af5.

**Comment by fonio** [comment]
Hi
I am having this problem in 
DATAFLOW_VERSION=2.5.0.RELEASE/SKIPPER_VERSION=2.4.0.RELEASE

Are you planning on releasing a  hotfix for that on this relase or should I wait for 
DATAFLOW_VERSION=2.6.0.RELEASE/SKIPPER_VERSION=2.5.0.RELEASE

BTW Do you konw what is the LKG version for this issue?
10X

**Comment by sabbyanandan** [comment]
Hi, this has been addressed in the `master` version of the `docker-compose.yml`, but today, we also release [2.5.1](https://github.com/spring-cloud/spring-cloud-dataflow/blob/v2.5.1.RELEASE/spring-cloud-dataflow-server/docker-compose.yml) — please use the latest.

Going forward, please consider questions like this in StackOverflow and not on closed issues. No one in the team monitors the closed issues.

**Comment by fonio** [comment]
Great to hear. 10X.
Will do
