### ISSUE TITLE
Task monitoring with RSocket + Boot 2.3.0 RCx fails with a variety of errors

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3929]
As a user, while attempting to launch tasks and observe the metrics from SCDF using Boot 2.3.0 RCx + RSocket (Prometheus+Grafana), I run into a variety of errors.

1) Task/Apps based on Boot up to version 2.3.0.M4  (rsocket RC5)  work with prometheus-rsocket-client 0.9.0 and 0.10.3 (also using RSocket RC5 internally)
Task/Apps based on Boot version 2.3.0.RC1  ( RC7 )  DON’T work with prometheus-rsocket-client 0.9.0 and 0.10.3 (using rsocket RC5 internally) - fails with netty error 

> [actor-tcp-nio-1] io.netty.util.ResourceLeakDetector  : LEAK: ByteBuf.release()

2) Task/Apps based on Boot version 2.3.0.RC1  (RC7)  DON’T work with prometheus-rsocket-client 0.10.4 and 0.10.6 (using RSocket RC7-SNAPSHOT internally) - fails with:

> java.lang.IncompatibleClassChangeError: Found io.rsocket.RSocketFactory$ClientRSocketFactory, but interface was expected

3) Task/Apps based on Boot up to version 2.3.0.M4  (RC5 )  DON’T work with prometheus-rsocket-client 0.10.4 and 0.10.6 (using RSocket RC7-SNAPSHOT internally) - fails with:

> java.lang.IncompatibleClassChangeError: Found io.rsocket.RSocketFactory$ClientRSocketFactory, but interface was expected

---

The only combination that works is based on Boot 2.3.0.M4  (RSocket RC5) with prometheus-rsocket-client 0.9.0 and 0.10.3   (also using RSocket RC5 internally)

**Comment by tzolov** [comment]
The `prometheus-rsocket-proxy` master had just fixed the incorrect rsocket:RC7-SNAPSHOT dependency to the correct RC7, that matches the Spring Boot 2.3.0.RC1+ version: 
https://github.com/micrometer-metrics/prometheus-rsocket-proxy/commit/90421563fe0fcc267722e5bc6dacef2ba526fcc9
