### ISSUE TITLE
Composed Task Runner: Consequent task launch fails

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#3933]
Since composed task is now launched as batch job, when launching after the first launch, the batch job fails with:

```
Caused by: org.springframework.batch.core.repository.JobInstanceAlreadyCompleteException: A job instance already exists and is complete for parameters={...}.  If you want to run this job again, change the parameters.

```

We need to handle this by introducing a custom logic inside the composed task runner to make the job instance unique.

**Comment by cppwfs** [comment]
This feature already exists for composed tasks:
Information on how to pass the variable to support this feature can be found here: 
  https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_configuring_the_composed_task_runner_2
An example of its use can be found here: 
https://dataflow.spring.io/docs/feature-guides/batch/composed-task/#task-arguments-and-parameters

**Comment by ilayaperumalg** [comment]
That's true. Given the CTR is now registered implicitly and I believe we can make this implicit so that the composed task runner task can be launched consecutively without having to add that flag explicitly. Perhaps, we could simply set the `increment-instance-enabled` to `true` by default. Do you see any issue with that?

**Comment by ilayaperumalg** [comment]
Now I see the misunderstanding from my original question:

> Since composed task is now launched as batch job, when launching after the first launch, the batch job fails with:

Since composed task is now launched as batch job **within SCDF**, when launching after the first launch, the batch job fails with:

**Comment by sabbyanandan** [comment]
@ilayaperumalg: It seems something still missing in your update?

**Comment by cppwfs** [comment]
@ilayaperumalg I chatted with Michael about this and we are in agreement, this is a feature we want to add.    Sorry I forgot to add a comment.   Thanks @sabbyanandan for commenting to remind me :-D
