### ISSUE TITLE
Wavefront monitoring

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3937]
Epic to track the overall scope of work and the integration with Wavefront for Streams/Tasks.

Notes:
- [Micrometer Docs](https://micrometer.io/docs/registry/wavefront)
- [Josh's walkthrough](https://spring.io/blog/2020/04/29/spring-tips-the-wavefront-observability-platform)
- [Wavefront value-adds](https://twitter.com/VMwareTanzu/status/1258412583670996994)

**Comment by ilayaperumalg** [comment]
Marking the features added into this epic as complete for 2.6.0 GA
