### ISSUE TITLE
Create Streams/Task dashboard for Wavefront

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3939]

**Comment by tzolov** [comment]
Here are links to the dashboards on vmware.wavefront.com: 

* Streams dashboard:  https://vmware.wavefront.com/u/Xz9qBl4fj3?t=vmware
* Stream apps dashboard: https://vmware.wavefront.com/u/vDZ37pbdQw?t=vmware
* Task Dashboard: https://vmware.wavefront.com/u/n8LnJR10tB?t=vmware

Same dashboards as JSON docs are available here: 

[wavefront-scdf-dashboards.zip](https://github.com/spring-cloud/spring-cloud-dataflow/files/4689587/wavefront-scdf-dashboards.zip)

Those needs to be used for building the SCDF Wavefront template (e.g. integration) #3970
