### ISSUE TITLE
Backport and prepare for 2.5.1

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3958]
Cherrypick the items that aren't already backported yet:

- [x] https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/commit/db33836b00d85a2db67fe0805f2645513aeb00a6
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/commit/08af2c87bbe6875645a41c6b438018a7d12e2faa
- [x] Upgrade to Boot 2.2.7 (see: https://github.com/spring-cloud/spring-cloud-skipper/issues/952#issuecomment-628873195)
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/commit/8b50a603945eb60d840c242d862575d3f2f47c24
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3921

**Comment by ilayaperumalg** [comment]
Removed https://github.com/spring-cloud/spring-cloud-dataflow/pull/3931 as it is related to CTR inside SCDF.

**Comment by ilayaperumalg** [comment]
Backporting is complete.

**Comment by sabbyanandan** [comment]
Done: https://github.com/spring-cloud/spring-cloud-dataflow/releases/tag/v2.5.1.RELEASE
