### ISSUE TITLE
Not an issue. Need to know software which was used to generate the gif in docs

### ISSUE THREAD

**Issue by afrancis-incomm** [spring-cloud/spring-cloud-dataflow#3959]
Hi,
I want to know what software was used to generate the animated sequences in this gif file I found in the dataflow microsite.
https://dataflow.spring.io/7becd438c73b41d68a6793b1f19cfa08/SCDF-application-dsl.gif

![Animated diagram](https://dataflow.spring.io/7becd438c73b41d68a6793b1f19cfa08/SCDF-application-dsl.gif)

**Comment by sabbyanandan** [comment]
@afrancis-incomm: 😄 — diagrams/animations were built on Google Slides, and the gif is generated by [LICEcap](https://www.cockos.com/licecap/).

Good luck!
