### ISSUE TITLE
Add SCDF template for Wavefront

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3970]
Here is the PR on the Wavefront GitHub https://github.com/sunnylabs/integrations/pull/523
and Jira ticket: https://wavefront.atlassian.net/browse/INT-679

**Comment by tzolov** [comment]
Use the dashboards created in #3939

**Comment by sabbyanandan** [comment]
Addressed via https://github.com/sunnylabs/integrations/pull/522.

**Comment by sabbyanandan** [comment]
https://github.com/sunnylabs/integrations/pull/523

**Comment by ilayaperumalg** [comment]
Marking this as complete. Closing.
