### ISSUE TITLE
SCDF UI issue - 

### ISSUE THREAD

**Issue by aharonmu** [spring-cloud/spring-cloud-dataflow#3972]
**Description:**
when deploying a new stream , even when all apps has those green squares which indicate all is deployed, the Stream is still in status deploying.
scdf 2.5.1 skipper 2.4.1
<img width="1411" alt="Screen Shot 2020-05-27 at 13 49 22" src="https://user-images.githubusercontent.com/5726968/83010483-fea75c00-a020-11ea-9560-171a504bdda6.png">

**Comment by oodamien** [comment]
Hi @aharonmu,
If you refresh the page (or click on the `refresh` action), is the status changed to deployed?
When deploying a stream, the stream will be in `deploying` status for a while. The UI doesn't update automatically the stream status.

**Comment by aharonmu** [comment]
hi @sabbyanandan 
Yes if i refresh the page all is fine.
I was just wondering if it is a bug since , those 3 green squares are refreshed automatically.
And once all of them are green... it means the stream is deployed , and hence change it status automatically also....

**Comment by sabbyanandan** [comment]
Yeah, we don't automatically refresh the status; we used to do that in the previous releases, but that turned out to be a very expensive operation to perform periodically. 

Thank you for reporting anyway.
