### ISSUE TITLE
Unable to define custom port for apps

### ISSUE THREAD

**Issue by tabish527112** [spring-cloud/spring-cloud-dataflow#3973]
How do I start an application with SCDF in a defined port. I tried passing the property "deployer.myapp.local.javaOpts":"-Dserver.port=11111", but the pipeline stays in deploying state

**Comment by sabbyanandan** [comment]
If it is a custom app, you can whitelist `sever.port` and override that property when defining or deploying the stream. 

For questions like this, please use StackOverflow going forward.
