### ISSUE TITLE
Permit "/management/info" for runtime probe evaluation

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3974]
As a user, when integrating SCDF/Skipper 2.5.x against an IDP, I'm seeing probe failures on SCDF and Skipper because the `/management/info` endpoint is protected, and it returns 401 instead of 200.

Today, we are permitting only the `/management/health`, but we need to also include `/management/info` to cleanly address this.

See:
https://github.com/spring-cloud/spring-cloud-dataflow/blob/43247faf52bd48c5e51ece6fdb72520e1c286b01/spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml#L89

**Comment by jvalkeal** [comment]
Backported to 2.5.x
