### ISSUE TITLE
Not able to create stream using the dataflow dashboard

### ISSUE THREAD

**Issue by xerZV** [spring-cloud/spring-cloud-dataflow#3980]
**Description:**
I am facing a problem here with `spring-cloud-dataflow-server-2.5.1.RELEASE.jar`.
I want to create a simple Stream and when I try to access Streams from the dataflow dashboard it throws:
```
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:7577/api/release/states": Connect to localhost:7577 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:7577 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
```

**Release versions:**
`spring-cloud-dataflow-server-2.5.1.RELEASE.jar`

**Screenshots:**
![image](https://user-images.githubusercontent.com/23699044/83487150-2a0fc800-a4b3-11ea-869c-bfe59faa2c65.png)

**Additional context:**
Running locally on Windows OS :
```shell script
java -jar spring-cloud-dataflow-server-2.5.1.RELEASE.jar
```

And I do have config server which has `spring-cloud-dataflow-server-local.properties` and there is only `server.port=9393`.

Do I need to download Skipper  `- wget https://repo.spring.io/release/org/springframework/cloud/spring-cloud-skipper-server/2.4.1.RELEASE/spring-cloud-skipper-server-2.4.1.RELEASE.jar` as well?

**Comment by ilayaperumalg** [comment]
Hi,

You are missing the Skipper server installation here. You also need to start Skipper server which is needed for continuous deployment of Streaming applications. The Skipper server listens on port 7577 by default.

**Comment by xerZV** [comment]
@ilayaperumalg Yeah I just have realized I do not run the Skipper server and modified the issue description. Thank you, let me try it now.
