### ISSUE TITLE
Move the Security docs out from Local configuration

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3989]
All of the security configurations, recommendations, and the samples are embedded inside the [Local's Security section](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#configuration-local-security). That is wrong! 

Let's move and promote `Security` to a top-level section on the left-nav. It applies to all the platforms that we support.

Let's also make sure any references to the security section within the ref. guide and/or the Microsite is fixed to point to the new URI.

**Comment by ilayaperumalg** [comment]
Pushed the similar change into 2.5.x as b599f2fd2
