### ISSUE TITLE
Anonymous authentication for docker registries

### ISSUE THREAD

**Issue by jameswynn** [spring-cloud/spring-cloud-dataflow#3994]
**Problem description:**
When DataFlow Server pulls metadata from a docker registry there are a few authentication mechanisms provided in DefaultContainerImageMetadataResolver. Our internal repository (and many public) have anonymous read access. This is not currently supported.

**Solution description:**
Altering the authentication process to not insert authentication headers if no authentication-type is selected.

**Comment by sabbyanandan** [comment]
@jameswynn: This seems like a reasonable request; we will review to see what we can do. If you have thoughts on how to go about addressing it, feel free to submit a PR.

**Comment by tzolov** [comment]
Thanks for the contribution @jameswynn !

I was wondering if we should define a dedicated anonymous authorizer + type or extend the semantics of the basic authorizer.  But now i think an explicit type would cause less confusions and left the code as it is ;)
