### ISSUE TITLE
Missing `deploymentProperties` in `lastTaskExecution` on retrieving task details

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow#4007]
**Description:**
`tasks/definitions/{name}` return an incomplete `lastTaskExecution`.
The platform property (`deploymentProperties`) should be populate.

**Release versions:**
Latest

**Steps to reproduce:**
1. Create a task `foo` (timestamp)
2. Launch `foo` with the following platform property: `app.timestamp=foo`
3. Compare http://localhost:9393/tasks/definitions/foo and http://localhost:9393/tasks/executions/1

**Screenshots:**

Task details:
![image](https://user-images.githubusercontent.com/487067/85149635-cf67c180-b251-11ea-9f46-f60d07bfecb7.png)

Execution details:
![image](https://user-images.githubusercontent.com/487067/85149607-c545c300-b251-11ea-88eb-32ab9187cc96.png)

**Comment by ilayaperumalg** [comment]
Hi @oodamien, This isn't a bug as we recently added a request parameter `http://localhost:9393/tasks/definitions/foo?manifest=true`  to retrieve the deployment properties as retrieving the deployment properties involves other calls and we want it to be optional.

**Comment by ilayaperumalg** [comment]
Please re-open if you think you still think the deployment properties should be set when retrieving the task definitions by default.
