### ISSUE TITLE
[Question] Is dataflow possibile to pass changable arguments with scheduling batch job

### ISSUE THREAD

**Issue by parksjin01** [spring-cloud/spring-cloud-dataflow#4011]
Hi im newbie of spring-cloud-dataflow and search docs to use.  
I want to manage batch job with this project (I think it's pretty good tools to manage batch)  

Now I have a question with using this.  
In my batch, I need current date information to process data and I wonder if spring-cloud-dataflow web dashboard support this.  
Can I pass current timestamp to my batch application with arguments or parameters in web dash board?

**Comment by cppwfs** [comment]
The UI does not pass this information as a property to the task to be launched.   
Other options:
* Your app could look at the `task_execution` table to get the `start_time`.
* You can enter this information as a command line property or task parameter (property) on the task execution page manually.
* You could launch your task using SCDF's RESTful API and add the start time  as a command-line-arg or a property.

**Comment by sabbyanandan** [comment]
@parksjin01: For questions like this, please use StackOverflow going forward.
