### ISSUE TITLE
Queue task executions instead of refusing them if maximumConcurrentTasks is reached

### ISSUE THREAD

**Issue by svesch84** [spring-cloud/spring-cloud-dataflow#4012]
**Problem description:**
The parameter _maximumConcurrentTasks_ refuses task executions if no slots are free. New tasks executions will fail, because the specified limit of concurrent tasks is reached. 

**Solution description:**
I would prefer to queue the tasks executions so that the will be processed after a slot becomes available. 

**Additional context:**

We have a data flow server that runs in the local mode (not on kubernetes, nor cloud foundry). We execute tasks on this server that invoke a spring batch job in the background. Now we have the problem that we want / need to limit the number of parallel running tasks, e.g because of hardware limitations. 

Is there any chance for me to limit the number of concurrent tasks and queue tasks if all slots are busy, or what is the reason why task executions fail? Could not imagine a use case where "work" that should be processed fails if the server is currently busy. 

Thanks for giving me any hints about my problem. 

Best regards,
Sven

**Comment by cppwfs** [comment]
Have you looked at launching tasks via stream as shown [here](https://docs.spring.io/spring-cloud-dataflow-samples/docs/current/reference/htmlsingle/#_stream_launching_batch_job)?

**Comment by svesch84** [comment]
Thanks for the quick response. 

I know that a stream can launch a task, however I never played around with that. Currently the SCDF is used without the messaging middleware in our shop. So with our configuration we are currently not able to use streams. 

Anyway if we would switch to use the stream launching approch would it be possible to limit the number of concurrent task? Currently I don't understand it so far how that might solve my problem?
Is the queing issue delegated to the messaging middleware somehow so that it will process only X streams and new incomming requests are on-hold?

**Comment by cppwfs** [comment]
It will pause polling the queue if the MaxConncurrentTasks is reached.   More can be read about it here: https://github.com/spring-cloud-stream-app-starters/tasklauncher-dataflow/blob/master/spring-cloud-starter-stream-sink-task-launcher-dataflow/README.adoc

**Comment by svesch84** [comment]
Many thanks, now I got it. 
From my side we can close that issue. I will try to implement that using the TaskLauncher example. 

Have a nice day. 
Sven
