### ISSUE TITLE
[Question] Is there way to print log with scheduling?

### ISSUE THREAD

**Issue by parksjin01** [spring-cloud/spring-cloud-dataflow#4018]
I'm newbie of the SCDF and i'm studying many features SCDF provides for.

I found that when I execute Spring Batch manually with launch button (▶️ button), log is printed.  
But when I run same Spring Batch with scheduler, Log doesn't printed...

I want to know how to print log when running Spring Batch with scheduler.  
If it is impossible then can you suggest which is the proper way to left log (somewhere like Exit Message or else)

Thanks!

**Comment by sabbyanandan** [comment]
@parksjin01: There's currently no support to retrieve logs for a scheduled task (see: [Scheduler.java](https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/scheduler/Scheduler.java)); however we have an API to fetch the logs for a task that was launched manually (see: [TaskLauncher.java#L132](https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/task/TaskLauncher.java#L132)). 

I created https://github.com/spring-cloud/spring-cloud-deployer/issues/342 — feel free to contribute it. Once when you have the API in the Deployer SPI, you'd then have also to implement the API in the K8s-deployer, as well. You can use [KubernetesTaskLauncher.java#L189](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesTaskLauncher.java#L189) as a reference when implementing it.
