### ISSUE TITLE
Switch to Gradle build system

### ISSUE THREAD

**Issue by donbeave** [spring-cloud/spring-cloud-dataflow#4020]
Actually it's just a question, not really feature request. I want to know if there will be any planned changes in the future or not.

It looks like Spring itself already migrating from Maven to Gradle, most of the popular projects already did this migration:

1) Spring Boot: https://github.com/spring-projects/spring-boot
2) Spring Framework: https://github.com/spring-projects/spring-framework
3) Spring Security: https://github.com/spring-projects/spring-security
4) Spring Session: https://github.com/spring-projects/spring-session
5) Spring AMQP: https://github.com/spring-projects/spring-amqp
...

So how about cloud projects? Will Spring Cloud Data Flow will also follow this trend or not?

I found myself in a position where using Maven as a build system is not very convenient, that's why I'm asking this question.

**Comment by jvalkeal** [comment]
For a whole dataflow ecosystem it would be a big change as we have a bit too much build time dependencies to various maven plugins, parent poms, etc. Personally I like gradle more than maven as gradle makes so many things much more easier. Boot and framework itself are monorepos so move to gradle was a relatively easy process, not so much in spring-cloud where we have such a complex project structure.

At some point we probably need to think about this as pom structure is a bit complex and deep and is already causing some issues when i.e. dataflow itself is used as an library either in a maven/gradle project.

**Comment by mminella** [comment]
The Cloud piece of the portfolio has no plans to move to Gradle at this time. The Spring team leaves that decision to each project's maintainers. I'd be interested in hearing more about how `using Maven as a build system is not very convenient`. Given the wrapper, I'm interested in hearing more about what the actual inconveniences are.

**Comment by donbeave** [comment]
Nothing is impossible of course, mostly Maven can do all things what can do with Gradle, but in some cases using Gradle much move comfortably, for example, when I need to customize smth, I always can use Groovy/Kotlin. IDEA support also looks better (probably some bug in the latest IDEA), but it shows some classes with red color, but classes are available and when I run Maven cmd directly will not get any compilation issue:

<img width="990" alt="image" src="https://user-images.githubusercontent.com/139017/86153526-69721880-bb34-11ea-909a-ec0c7632f996.png">

Another, actually, the most inconvenient is dependency download speed. Gradle using multiple threads to download dependencies and store them in one cache, Maven is using another way to store cache, which leads to re-download actually already downloaded dependencies. I mean already downloaded by Gradle. Gradle daemon is also quite fast, recompilation is super fast with all enabled caches.

**Comment by donbeave** [comment]
I think can close this issue, it's just a question. Thank you @jvalkeal @mminella for your answers!
