### ISSUE TITLE
Stream status is UNDEPLOYED but SCDF would not allow deploying or destroying the stream

### ISSUE THREAD

**Issue by HaoTanAtMLB** [spring-cloud/spring-cloud-dataflow#4025]
On SCDF version `2.1.0.RELEASE`

A stream has a status of `UNDEPLOYED`.  When clicking on the deploy stream from the Data Flow UI, it would respond with an error.

```
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Failed to upload the package. Package [my-stream:1.0.0] in Repository [local] already exists.
```

When trying to destroy the stream, the following exception occurs:

```
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Can not delete Package Metadata [my-stream:1.0.0] in Repository [local]. Not all releases of this package have the status DELETED. Active Releases [my-stream]
```

Is there anyway to reset the stream's state so that SCDF can properly deal with the broken stream?

**Comment by sabbyanandan** [comment]
Hi, @HaoTanAtMLB. Sorry you're having trouble with it. The release that you're using is >1yr old —  hard to relate to the error and reproduce it. I'd check to make sure Skipper is using the persistent database, and repeat the exercise on a latest and stable GA release (currently at 2.5.2 GA).

If you continue to see issues, feel free to start a post in StackOverflow with more details and stacktrace's.

**Comment by HaoTanAtMLB** [comment]
Hi @sabbyanandan,

Hate to revive this thread.  We've upgraded our cluster since our last conversation and this issue continues to happen.  Somehow Skipper loses the state of a stream due to a failed deployment on K8 and the stream is stuck in an undeployed status.  When trying to delete the stream, an error is thrown by dataflow server:

```dataflow:>stream destroy submission-service-complete-1
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Can not delete Package Metadata [submission-service-complete-1:1.0.0] in Repository [local]. Not all releases of this package have the status DELETED. Active Releases [submission-service-complete-1]
Can not delete Package Metadata [submission-service-complete-1:1.0.0] in Repository [local]. Not all releases of this package have the status DELETED. Active Releases [submission-service-complete-1]
```

We've found that the only way to fix the situation is to delete the Skipper database from Postgres.  Is there a less destructive way to fix this issue?

Thanks,
Hao

**Comment by sabbyanandan** [comment]
Don't see something jumping out; we used to have an issue around the state in Skipper but that has been resolved in one of the recent releases, so if you're on the latest, you would be fine.

If this is reproducible, perhaps share the versions in use and steps in their entirety, we can try it out on our side. The more the details, the better it'd be to review or troubleshoot.

**Comment by HaoTanAtMLB** [comment]
@sabbyanandan I've found the answer to the issue with the stuck streams on Stackoverflow.  Here's the link in case someone else lands on this and has similiar issues:

https://stackoverflow.com/questions/54063208/cannot-delete-a-stream-because-package-metadata-in-repository-say-not-all-releas

**Comment by sabbyanandan** [comment]
Thanks for the update. Repaving Docker/K8s environment or deleting rows from the DB is not a good solution. If you know of reproducible scenarios, we would be glad to review what can be improved.
