### ISSUE TITLE
SCDF About Info's Maven Repo URL Configuration option for SCDF dependencies

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#4026]
Currently, we have hard coded repo values for SCDF dependencies when retrieving About info as follows:

```
final String REPO_SNAPSHOT_ROOT = "https://repo.spring.io/libs-snapshot";
		final String REPO_MILESTONE_ROOT = "https://repo.spring.io/libs-milestone";
		final String REPO_RELEASE_ROOT = "https://repo.spring.io/libs-release";
		final String MAVEN_ROOT = "https://repo1.maven.org/maven2";
```

This needs to be configurable as this won't work in private network setup.

**Comment by sabbyanandan** [comment]
The support to enable/disable this is already included (see: https://github.com/spring-cloud/spring-cloud-dataflow/issues/1829). We use this in the tile today — see here.

Docs: https://docs.spring.io/spring-cloud-dataflow/docs/2.6.0-M1/reference/htmlsingle/#_about_configuration
