### ISSUE TITLE
Add new REST endpoint for retrieving stream applications for a stream

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#4036]
It would be handy to have a new REST endpoint to retrieve AppRegistry resources that are part of a stream.

**Comment by deepak5127** [comment]
Hi @ilayaperumalg  , please let me know if I can work on this

**Comment by deepak5127** [comment]
Hi @ilayaperumalg  . please let me know if I can pick this to work on

**Comment by ilayaperumalg** [comment]
Hi @deepak5127, Apologies for the delay. I missed to see your earlier comment. This was already addressed and we have a new REST endpoint `/streams/definitions/{name}/applications` which gets all the applications of a given stream.

Please let me know if you would like to contribute on SCDF and we'd be happy to help you get started with some of the issues. 
Especially, you can go through [this](https://github.com/spring-cloud/spring-cloud-dataflow/issues?q=is%3Aopen+is%3Aissue+label%3A%22contributions+welcome%22) list. 

Thank you for your interest!

**Comment by ilayaperumalg** [comment]
This was addressed via https://github.com/spring-cloud/spring-cloud-dataflow/commit/582fb52deb0031e520e368f5df7520843857e021#diff-e7fdbc0bfc59f8563119b736355cd9dd33e37f3e1819ee0c26f05b143e73c881 

Missed to link this issue with that.

**Comment by deepak5127** [comment]
Thanks @ilayaperumalg . I will go through the list
