### ISSUE TITLE
Using newer Java versions fails RBAC auth on k8s v1.17 and later

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#4039]
**Description:**

On Kubernetes data flow server fails to launch task when using Java version 1.8.0_252. The deployment fails on RBAC auth.

**Release versions:**

2.5.2.RELEASE

**Custom apps:**

N/A

**Steps to reproduce:**

**Screenshots:**

**Additional context:**

This happens when server is running with a JDK version of 1.8.0_252 which is later than the version shipped with the springcloud/spring-cloud-dataflow-server:2.5.2.RELEASE image

The cause seems to be an issue with okhttp used by fabric8 client

See:
square/okhttp#5971
fabric8io/kubernetes-client#2176

Need to update to the latest deployer once the spring-cloud/spring-cloud-deployer-kubernetes#390 is fixed

**Comment by trisberg** [comment]
Should be resolved via #4038

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-dataflow/commit/5f5507ba63f17dff30d8d15c4dbf7d2d383b9e91.
