### ISSUE TITLE
Getting a Page of TaskExecutionResources Using the DataFlowTemplate's taskOperations.

### ISSUE THREAD

**Issue by JustinLiAtSBU** [spring-cloud/spring-cloud-dataflow#4051]
**Problem description:**
If I wanted to implement some pagination for TaskExecutionResources, I have to use the methods in the DataFlowTemplate, such as  `executionListByTaskName().getContent()`. Then I would use Page, Pageable, and PageImpl to create a page out of the Collection<TaskExecutionResource> that was returned from the function. However, since PageImpl requires a list, I would have to convert the collection into an ArrayList. This is very inefficient and could get extremely slow if there was a lot of task executions. What's more inefficient is that what I have to do to get a page is to 
1. Pull ALL of the task executions from the database
2. Convert a collection into an array list
3. Getting a sublist of them to return as a "page"
However, this seems to be the only way of implementing pagination.

**Solution description:**
A solution that I would like to see is another function in the DataFlowTemplate that is similar to `DataFlowTemplate.taskOperations().executionListByTaskName(taskName)`. However, this new function would have additional parameters for page size and page number, or a Pageable object. The goal of this new function would be to allow the user to easily and efficiently implement pagination on TaskExecutionResources so that they can be displayed on a dashboard or something.

**Description of alternatives:**
My alternative solution was described above. 

**Additional context:**
If anything I wrote was unclear, I also made a StackOverflow post [here ](https://stackoverflow.com/questions/62904584/how-to-get-a-specific-page-of-task-executions-from-spring-cloud-data-flow-server?noredirect=1#comment111282652_62904584) that might describe this better.

**Comment by sabbyanandan** [comment]
@JustinLiAtSBU: Thanks for reporting! All this sounds like a reasonable enhancement request. If you have cycles, please feel free to take a stab at it and start the dialog with the pull request — we could collaborate to get this improved.

**Comment by JustinLiAtSBU** [comment]
Hi Sabby. To be completely honest I’m not familiar with the source code of
spring, but I’ll take a look at the code and see if there’s anything I can
do. I have just cloned it on my local.

**Comment by sabbyanandan** [comment]
@JustinLiAtSBU: Thanks for considering. I am going to tag @cppwfs and @ilayaperumalg to help guide you with the relevant changes.

**Comment by JustinLiAtSBU** [comment]
@sabbyanandan  Great. Thank you.

**Comment by cppwfs** [comment]
Hello @JustinLiAtSBU ,
There are 3 class that require an update:
* TaskOperations.java (Interface)
* TaskTemplate.java (Impl) 
* TaskTemplateTests.java (Test)

1.  You would want to add a new function to the TaskOperations for the `executionListByTaskName` found here: https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskOperations.java#L109-L115
 that would pass in page sizes and page.
2. Add the implementation to the TaskTemplate for the `executionListByTaskName` https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskOperations.java#L109-L115 but with the parameters required.   
3. Update the tests : https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-rest-client/src/test/java/org/springframework/cloud/dataflow/rest/client/TaskTemplateTests.java

If you can submit a PR for this that would be awesome!   
If not you can still hit the RESTful api directly as discussed here: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-task-executions-list-by-name

**Comment by JustinLiAtSBU** [comment]
Thanks for sharing this. I’m going to start working on this once I get off
work.

**Comment by siddhantsorann** [comment]
@sabbyanandan Can I start work on this ticket? Seems doable.

**Comment by sabbyanandan** [comment]
Yes, please! Any help is appreciated.

**Comment by siddhantsorann** [comment]
Hey @sabbyanandan @cppwfs I have raised a draft PR for this issue, could you please check if I'm on the right track there? Might not have exactly understood the issue. Can't find where the exposed method in DataFlowTemplate will be used. Thanks.
