### ISSUE TITLE
Deploy Task(Docker Image) different namespaces in Openshift

### ISSUE THREAD

**Issue by umutcann** [spring-cloud/spring-cloud-dataflow#4055]
Hi,

We have SCDF running Openshift. Defined docker tasks are deploying to same namespace which is set environment variables of SCDF pod as KUBERNETES_NAMESPACE. 

But we want to deploy docker images different namespaces. 

Is there any way to do that while launching task?

Thanks in advance.

**Comment by cppwfs** [comment]
THis should be helpful: https://dataflow.spring.io/docs/2.6.0.SNAPSHOT/recipes/multi-platform-deployment/multi-platform-task/
