### ISSUE TITLE
Persist stream deployment settings

### ISSUE THREAD

**Issue by donbeave** [spring-cloud/spring-cloud-dataflow#4058]
**Problem description:**
Sometimes we want to stop streams for a while and re-deploy them on the particular dates. Right now we are using deploy/undeploy features together. So we can deploy some stream on Monday, and undeploy it the next day, without destroying it, so the stream will stay in Data Flow, just without any running pods. The next Monday we want to deploy it again, but at that time we always need to provide "Generic Deployer" and "Deployment Platform" settings again. But "Applications Properties" will be stored in the database, do not need to enter them again.

**Solution description:**
It will be nice to store "Generic Deployer" and "Deployment Platform" settings as well as "Applications Properties". Some of the applications are using environment variables, and not application arguments, these envs only available in the "Deployment Platform" section.

If you guys agree with the needs of this feature, I can make a pull request.

**Comment by sabbyanandan** [comment]
Hi, @donbeave. Persistence for application/deployment properties is already available. The following stream is deployed with an altered application count, and it then reflects in the Skipper manifest as follows.

1- Stream:
> dataflow:>stream deploy --name foo --properties "deployer.log.count=2"

2- Manifest:
```
dataflow:>stream manifest --name foo
"apiVersion": "skipper.spring.io/v1"
"kind": "SpringCloudDeployerApplication"
"metadata":
  "name": "log"
"spec":
  "resource": "maven://org.springframework.cloud.stream.app:log-sink-kafka:jar"
  "resourceMetadata": "maven://org.springframework.cloud.stream.app:log-sink-kafka:jar:jar:metadata:2.1.4.BUILD-SNAPSHOT"
  "version": "2.1.4.BUILD-SNAPSHOT"
  "applicationProperties":
    "spring.cloud.dataflow.stream.app.label": "log"
    "spring.cloud.stream.kafka.streams.binder.zkNodes": "zookeeper:2181"
    "spring.cloud.stream.metrics.properties": "spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*"
    "management.metrics.export.wavefront.api-token": "8bf93f64-c758-4d4d-bdcf-89fab7edefe5"
    "spring.cloud.dataflow.stream.name": "foo"
    "spring.cloud.stream.kafka.streams.binder.brokers": "PLAINTEXT://kafka-broker:9092"
    "spring.metrics.export.triggers.application.includes": "integration**"
    "spring.cloud.stream.instanceCount": "2"
    "spring.cloud.stream.metrics.key": "foo.log.${spring.cloud.application.guid}"
    "spring.cloud.stream.bindings.input.group": "foo"
    "management.metrics.export.wavefront.source": "scdf-docker-compose"
    "spring.cloud.stream.kafka.binder.zkNodes": "zookeeper:2181"
    "spring.cloud.dataflow.stream.app.type": "sink"
    "spring.cloud.stream.bindings.input.destination": "foo.time"
    "management.metrics.export.wavefront.uri": "https://nimba.wavefront.com"
    "management.metrics.export.wavefront.enabled": "true"
    "spring.cloud.stream.kafka.binder.brokers": "PLAINTEXT://kafka-broker:9092"
  "deploymentProperties":
    "spring.cloud.deployer.count": "2"
    "spring.cloud.deployer.group": "foo"
```

However, after an undeploy, and on re-deploy if we don't continue to indicate we want the same scale-out setup, it will be flagged as if you are intending to alter the previous deployment, so the deployment count gets updated to the default number, that is 1.

3- Undeploy:
> dataflow:>stream undeploy --name foo

4- Deploy:
> dataflow:>stream deploy --name foo

5- Manifest:
```
dataflow:>stream manifest --name foo
"apiVersion": "skipper.spring.io/v1"
"kind": "SpringCloudDeployerApplication"
"metadata":
  "name": "log"
"spec":
  "resource": "maven://org.springframework.cloud.stream.app:log-sink-kafka:jar"
  "resourceMetadata": "maven://org.springframework.cloud.stream.app:log-sink-kafka:jar:jar:metadata:2.1.4.BUILD-SNAPSHOT"
  "version": "2.1.4.BUILD-SNAPSHOT"
  "applicationProperties":
    "spring.cloud.dataflow.stream.app.label": "log"
    "spring.cloud.stream.kafka.streams.binder.zkNodes": "zookeeper:2181"
    "spring.cloud.stream.metrics.properties": "spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*"
    "management.metrics.export.wavefront.api-token": "8bf93f64-c758-4d4d-bdcf-89fab7edefe5"
    "spring.cloud.dataflow.stream.name": "foo"
    "spring.cloud.stream.kafka.streams.binder.brokers": "PLAINTEXT://kafka-broker:9092"
    "spring.metrics.export.triggers.application.includes": "integration**"
    "spring.cloud.stream.instanceCount": "2"
    "spring.cloud.stream.metrics.key": "foo.log.${spring.cloud.application.guid}"
    "management.metrics.export.wavefront.source": "scdf-docker-compose"
    "spring.cloud.stream.bindings.input.group": "foo"
    "spring.cloud.stream.kafka.binder.zkNodes": "zookeeper:2181"
    "spring.cloud.dataflow.stream.app.type": "sink"
    "spring.cloud.stream.bindings.input.destination": "foo.time"
    "management.metrics.export.wavefront.uri": "https://nimba.wavefront.com"
    "management.metrics.export.wavefront.enabled": "true"
    "spring.cloud.stream.kafka.binder.brokers": "PLAINTEXT://kafka-broker:9092"
  "deploymentProperties":
    "spring.cloud.deployer.group": "foo"
```

_(note: `"spring.cloud.deployer.count": "2"` is gone)_

There are nuances here in regards to determining what is intended vs. an implicit decision point. Maybe we could introduce another flag (eg: `--inherit-properties` or something like that) when re-deploying (a previously deployed stream), so we could repurpose what is already persisted to kick off a new deployment. 

The devils in the details, though. 

@markpollack @ilayaperumalg @jvalkeal: Do you have any other recommendations?

**Comment by donbeave** [comment]
Probably I understand it wrong, please correct if it is, it looks like applications properties are stored in the Data Flow database, that's why UI can show them after the stream was undeployed, but deployment properties are stored only in the manifest file, which will post to Kubernetes during the deployment, that's why after un-deploy, the manifest file, of course, deleted also and UI can not retrieve deployment properties.

**Comment by ilayaperumalg** [comment]
Hi @donbeave ,

I'll try to explain what's going on here with the stream deployment properties during deploy -> undeploy -> re-deploy.

 - First, you deploy a stream with a set of application/deployment properties. 
By design, the `application properties` are persisted along with the stream DSL and hence everytime you try to re-deploy the stream the overridden application properties always come back up. The Stream DSL you see the at the `Stream List` page is the original DSL you provided when you first created the stream where as the DSL you see at the `Stream Summary` page after clicking the given Stream link has the actual DSL with all the application properties in it. We can definitely do better in terms of what we can show there between Stream List/Summary page. Your feedback is appreciated.
The `deployment properties` you specify at the time of `Stream Deploy` are meant for a specific **version** of the deployment **only**. We persist the deployment properties at `Skipper` server as deployment manifest in case if the Stream gets rolled back into the specific **version**. 

It is by design that the deployment properties were never meant to be replicated for the subsequent deployment.

But, when Skipper was designed we had discussion around providing options to re-use the deployment properties when the stream gets re-deployed. We decided to wait for the community feedback on this. 

Since this has come up now, as @sabbyanandan suggested, we can have an explicit flag to make the deployment properties available for the stream update.
