### ISSUE TITLE
Deprecate Helm Hub chart

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4063]
Epic to track all the moving parts involved in deprecating the Helm Hub's OSS chart in favor of the recently published [Bitnami OSS chart](https://github.com/bitnami/charts/tree/master/bitnami/spring-cloud-dataflow).

- [x] Deprecate the Helm Hub chart
- [x] Highlight the deprecation in the ref. guide / microsite
- [x] Revise the Helm chart installation steps
- [ ] Revise any CI plans that are tied to the deprecated chart + infra
- [ ] Announce the deprecation in the 2.6/2.7 release blogs

**Comment by sabbyanandan** [comment]
This cannot be done until when the existing capabilities in the OSS Helm chart are entirely ported. At least Prometheus + Grafana stack doesn't come up; there are likely others missing also.

**Comment by sabbyanandan** [comment]
Depends on https://github.com/bitnami/charts/issues/3363.

**Comment by chrisjs** [comment]
need to get CTR image rolled / integrated into the 2.6 chart - https://github.com/bitnami/charts/issues/3571

**Comment by chrisjs** [comment]
@ilayaperumalg once https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/pull/320/files is merged that should wrap up the functional changes and we can close this issue. can you move the item `Announce the deprecation in the 2.6/2.7 release blogs` in the description above to any release tracking document/notes you may have?

**Comment by sabbyanandan** [comment]
Looks like all of it is done except the blog update, which we can address in the 2.7 M1 blog. @ilayaperumalg: If you are cool with it, please close this issue.

**Comment by ilayaperumalg** [comment]
Sure, We'll make sure to add in our release blog about this.

**Comment by beltran-rubo** [comment]
Hi @ilayaperumalg @sabbyanandan, is there anything else we can help with from Bitnami to deprecate the previous Helm Chart?

**Comment by ilayaperumalg** [comment]
@beltran-rubo Thanks for reaching out and I believe we are good here.  @chrisjs What do you think?

**Comment by chrisjs** [comment]
i don't believe there are any outstanding items so good for now
