### ISSUE TITLE
Missing indexes in SCDF database tables

### ISSUE THREAD

**Issue by djgeary** [spring-cloud/spring-cloud-dataflow#4068]
We are seeing poor performance when retrieving information from the dataflow APIs or dashboards. We use dataflow to regularly (eg every half hour) run tasks that test our APIs and services and so have a large amount of history in the dataflow DB and it looks like the lack of indexes on the history tables may be the cause of the problem.

It looks like this has been discussed before for example here https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5b295ec2ce3b0f268d2ab919, and there were some indexes added around 2 years ago here spring-cloud/spring-cloud-dataflow#2330. But it seems this was removed when going to the 2.0.0 version (see https://github.com/spring-cloud/spring-cloud-dataflow/pull/2947). I can't see anywhere in the code now that creates the relevant indexes on the execution tables and we don't have them in our standard install (version 2.5.1).

**Comment by cppwfs** [comment]
Hello @djgeary ,
What queries are negatively impacting you?   Is it JobExecution, TaskExecution, or both?    Are there any that are particularly slow?

**Comment by djgeary** [comment]
I think its mainly around job executions and steps eg

https://scdf-server/jobs/executions/114891/steps/306619/progress

We did some analysis and found one of the endpoints was executing SQL of the form

```
SELECT S.STEP_EXECUTION_ID, S.STEP_NAME, S.START_TIME, S.END_TIME, S.STATUS, S.COMMIT_COUNT, S.READ_COUNT, S.FILTER_COUNT, S.WRITE_COUNT, S.EXIT_CODE, S.EXIT_MESSAGE, S.READ_SKIP_COUNT, S.WRITE_SKIP_COUNT, S.PROCESS_SKIP_COUNT, S.ROLLBACK_COUNT, S.LAST_UPDATED, S.VERSION
from BATCH_STEP_EXECUTION S, BATCH_JOB_EXECUTION J, BATCH_JOB_INSTANCE I
where JOB_NAME = 'my-task' and S.STEP_NAME = 'my step'
```

This would be slow without indexes on the names?

We have a layer on top of the dataflow API that makes several calls and combines the results so the delays add up.

**Comment by cppwfs** [comment]
The indexes that were in the PR enumerated above are present in the form of primary or foreign keys (so they don't need to be expressly created).    The performance issue that was identified by you (in the query) comes from the acquisition of 
 the Step Execution History.  i.e. the following endpoint http://localhost:9393/jobs/executions/<jobExecutionId>/steps/<stepExecutionId>/progress.   Looking into how to resolve this scenario.

**Comment by cppwfs** [comment]
@djgeary Are you executing these queries via the UI or from the restful API.
