### ISSUE TITLE
volumeMounts in k8s through composed task runner

### ISSUE THREAD

**Issue by ab48917** [spring-cloud/spring-cloud-dataflow#4078]
Trying to pass the below deployer properties to a composed task properties while launching the task and expecting that same volume mount is cascaded across the all child tasks initiated by same composed task but It's not happening. This is mounting the volume only for composed task and other launched child tasks not getting the volume mounts.

Deployer properties - 

deployer.*.kubernetes.volumes=[{name: devvolume, persistentVolumeClaim: { claimName: cmndev }}]
deployer.*.kubernetes.volumeMounts=[{name: 'devvolume', mountPath: '/mnt/cmn'}]

However, Tried passing the below to bootstrap.yml of child tasks to consider the volume mount but It is also not working. 

spring:
  cloud:
     deployer:
       kubernetes:
         environmentVariables:deployer.*.kubernetes.volumes=[{name: devvolume, persistentVolumeClaim:{ claimName:cmndev }}],deployer.*.kubernetes.volumeMounts=[{name:'devvolume', mountPath:'/mnt/cmn'}]

**Comment by ab48917** [comment]
@chrisjs  Do we have any suggestions/update on this?

**Comment by cppwfs** [comment]
In this case you would need to pass the volume mounts to each child in the Composed Task. 
i.e. if I had a timestamp in my composed task it owuld look something like:
`deployer.myctr.timestamp.kubernetes.volumeMounts=...`

**Comment by ab48917** [comment]
@cppwfs  how can we pass thise configuration to child task while running though the composed task runner as CTR will be auto triggering these tasks from SCDF.? is there a way where we can setup these properties through application.yml (deployer.myctr.timestamp.kubernetes.volumeMounts=...)of child task itself?

**Comment by cppwfs** [comment]
Yes.   You can read about it here: https://dataflow.spring.io/docs/feature-guides/batch/composed-task/#setting-property-at-composed-task-launch-time

**Comment by ab48917** [comment]
@cppwfs - Thanks and It is working. Only challenge is I have to pass the same properties to all my apps with in a composed task runner. 
Example - I need to pass the same below property to all the apps(5 apps in a ctr) associated to task1
deployer.tasks1.app-edi1.kubernetes.imagePullPolicy=Always
deployer.tasks1.app-edi2.kubernetes.imagePullPolicy=Always
deployer.tasks1.app-edi3.kubernetes.imagePullPolicy=Always
deployer.tasks1.app-edi4.kubernetes.imagePullPolicy=Always
deployer.tasks1.app-edi5.kubernetes.imagePullPolicy=Always
Is there a way to avoid this and can be pass something like this -
deployer.tasks1.*.kubernetes.imagePullPolicy=Always

I tried but didn't work. Any thoughts please?

**Comment by ab48917** [comment]
@cppwfs  - Any update on above comment please?

**Comment by chrisjs** [comment]
@ab48917 per https://github.com/spring-cloud/spring-cloud-dataflow/issues/4078#issuecomment-684924497 @cppwfs already has indicated you need to pass props to each task therefor a wildcard is not supported.
