### ISSUE TITLE
Investigate how to compose applications using Spring Initialzr

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#408]
As a user, I'd like to use Spring Initialzr to create a composite application, so I can generate an application that uses inter-app connectivity to avoid message hop between the applications embedded in it.

**Acceptance:**
- I can compose any combination of source, processor, or sink applications
- Embedded set of applications do not use messaging middleware for payload hops between them

**Comment by ghillert** [comment]
Provide workable draft implementation. This implementation will be a fork of Spring Initializr customized for the SCS requirements and provide a UI. Deploy to CF.

**Comment by garyrussell** [comment]
In Spring XD, composite modules (`module info source:foo`) show default property values for the underlying child modules.

`module compose foo --definition "time --fixedDelay=5 | transform --expression=payload+'xx'"`

`module info source:foo` shows the default value for time.fixedDelay as 1, not 5.

Whatever the solution ends up being in SCDF, the "composed" app should override the child module defaults with the configured property.

**Comment by sabbyanandan** [comment]
This is not relevant anymore.
