### ISSUE TITLE
Restart Task IllegalStateException

### ISSUE THREAD

**Issue by umutcann** [spring-cloud/spring-cloud-dataflow#4080]
Hi,

We're facing IllegalStateException when restarting task step. We have two different kubernetes namespaces. We can launch job on specified namespace. But when we tried to restart task, we are getting error like below.

   _{
        "logref": "IllegalStateException",
        "message": "Did not find platform for taskName=[abcdef] , taskId=[2923]"
    }_

We could see platformname environment variable on Openshift. But we couldn't see it on Spring Cloud Data Flow Task Execution Dashboard. 

SCDF couldn't store spring.cloud.data.flow.platformname variable in properties section.

It may be a bug. Can you review it?

SCDF version is 2.5.0. We could see platformName in local SCDF . But we couldn't see SCDF which is running on Openshift.

Thanks.

![image](https://user-images.githubusercontent.com/18632831/89503621-763af980-d7cf-11ea-9a32-e7d1f1a55b93.png)

![image](https://user-images.githubusercontent.com/18632831/89503480-44c22e00-d7cf-11ea-90ef-0c13454fb109.png)

![image](https://user-images.githubusercontent.com/18632831/89650711-82a47c80-d8cb-11ea-84d8-85cd75d149e8.png)

https://github.com/spring-cloud/spring-cloud-dataflow/blob/85e6f761e006b0201f6a66bdfb8e921724dd6d38/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobService.java#L194-L204

**Comment by umutcann** [comment]
Hi,

I could add spring.cloud.data.flow.platformname in job parameters implementing org.springframework.batch.core.JobParametersIncrementer interface.

![image](https://user-images.githubusercontent.com/18632831/89770304-3f365200-db07-11ea-8240-501f63a73dad.png)

Now, I'm getting error from SCDF restart endpoint like below.

[
    {
        "logref": "ConstraintViolationException",
        "message": "must match \"^[-._a-zA-Z][-._a-zA-Z0-9]*$\""
    }
]

The platfromname which I set is matching that regex.

Why am I getting that error.?

Thanks.

**Comment by cppwfs** [comment]
The platform is not sent as a jobparameter.   From a cursory view we need to get this from the task execution.

**Comment by umutcann** [comment]
Thanks @cppwfs .

I think cause of ConstraintViolationException is that variable type(Long,String) is suffixed to variable Name with brackets. So it was not matching Kubernetes environment variable regex.

I just want to subjoin it.

**Comment by umutcann** [comment]
Hi,

I upgraded SCDF to latest master version(2.7.0). But I'm still getting error during restart task execution step. 

_{"message":"Did not find platform for taskName=[hopeTask] , taskId=[3645]","logref":"IllegalStateException"}_

**Comment by cppwfs** [comment]
Can you provide the steps and a full stack trace of the error.
I was unable to see the error you are reporting with a fresh code pull and build on my local machine.
Here are my steps
1) Register a task app that contains a batch job that will fail.
2) Launch the task app that contains the failing job.
3) Go to the Job page and verify that the job failed.
4) Restart the job.   
At this time on the 2.7-Snapshot I'm not seeing and exception thrown.
