### ISSUE TITLE
Documentation should describe the behavior of applications with "--type app"

### ISSUE THREAD

**Issue by johnlinp** [spring-cloud/spring-cloud-dataflow#4081]
**Problem description:**
When I was trying to create a new application, I was able to create applications with "--type sink" or "--type processor". However, when I realize that I can also create an application with "--type app", I was confused. I thought that an application can only be either "source", "sink", "processor" or "task", but it seems that it can also be simply "app".

**Solution description:**
After some trial-and-errors, I feel that a "--type app" can be used as a "source", "sink" or "processor", but not as a "task". I think it would be better to describe these behavior in the documentation. Thank you.

**Comment by ilayaperumalg** [comment]
@johnlinp Thanks for the feedback.

We currently have the following content in our [documentation](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#spring-cloud-dataflow-register-stream-apps):

```
Registering an application using --type app is the same as registering a source, processor or sink. Applications of the type app are only allowed to be used in the Stream Application DSL, which uses a comma instead of the pipe symbol in the DSL, and instructs Data Flow not to configure the Spring Cloud Stream binding properties of the application. The application that is registered using --type app does not have to be a Spring Cloud Stream app, it can be any Spring Boot application. See the Stream Application DSL introduction for more information on using this application type.
```

I think we can probably highlight as a **NOTE** or something. Please feel free to submit a documentation PR if you would like to.

**Comment by johnlinp** [comment]
Thank you! I wasn't aware of that section exists. I think it's good enough for me. I'm closing this issue.
