### ISSUE TITLE
Derive "dataflow-server-uri" to setup CTR configuration automatically

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4088]
In 2.6, we optimized by [automatically propagating security configurations](https://github.com/spring-cloud/spring-cloud-dataflow/issues/3956) to CTR from SCDF. It'd be one less thing to manually configure if we can also derive the SCDF URI and populate the `dataflow-server-uri` property in CTR.

**Comment by cppwfs** [comment]
Looks like @markpollack has a solution for CF here: https://github.com/spring-cloud/spring-cloud-dataflow/tree/ctr-fix

**Comment by sabbyanandan** [comment]
Likely addressed in https://github.com/spring-cloud/spring-cloud-dataflow/commit/002715a9617912b396dd7a5b2f1cf7e36fd4f220.
