### ISSUE TITLE
Application name should not contain colon symbol

### ISSUE THREAD

**Issue by johnlinp** [spring-cloud/spring-cloud-dataflow#4090]
**Description:**
Colon symbol has a special meaning in both Stream DSL and Composed Task DSL, which is used for labeling. Therefore, when an application has a name that containing colon symbols, it cannot be used in Stream DSL or Composed Task DSL.

**Release versions:**
2.6.0

**Steps to reproduce:**
1. Register an application with the name "a:b".
```
dataflow:>app register "a:b" --type source --uri maven://some-group:some-artifact:some-version
Successfully registered application 'source:a:b'
```
2. Expected to see the registration fail, but it was successful.

**Comment by sabbyanandan** [comment]
@johnlinp: Good catch! If you have cycles, please consider adding the validation for it. One of us can collaborate with you to get this wrapped both in the Shell and UI.

**Comment by siddhantsorann** [comment]
@sabbyanandan Do you think this would be a good contribution to start off with? I've been looking into the filter one as well but I felt like maybe this would be a good ticket to ease into the code base?

**Comment by ilayaperumalg** [comment]
The validation needs to happen at the [AppRegistry REST controller](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/AppRegistryController.java#L223) where a new app registration is created.

**Comment by siddhantsorann** [comment]
Thanks, @ilayaperumalg Yes, that is where I have added it. Is the current master unstable? I was unable to build it.

**Comment by ilayaperumalg** [comment]
> Is the current master unstable? I was unable to build it.

I don't think so: https://build.spring.io/browse/SCD-BMASTER-4243

**Comment by siddhantsorann** [comment]
It built now, was having an issue yesterday. Thanks.

**Comment by siddhantsorann** [comment]
@ilayaperumalg Can you also let me know if we need to validate anything other than `Application Name cannot contain ':'` ?
