### ISSUE TITLE
Destroying a task definition won't delete related execution records

### ISSUE THREAD

**Issue by johnlinp** [spring-cloud/spring-cloud-dataflow#4091]
**Description:**
When destroying a task definition, I expect the related execution records to be deleted too. However, it seems that's not the case.

**Release versions:**
2.6.0

**Steps to reproduce:**
1. Create a task definition
```
dataflow:>task create --name some-task --definition timestamp
Created new task 'some-task'
```
2. Launch the task
```
dataflow:>task launch --name some-task
Launched task 'some-task' with execution id 4
```
3. See the task completed
```
dataflow:>task list
╔═════════╤═══════════════╤═══════════╤═══════════╗
║Task Name│Task Definition│description│Task Status║
╠═════════╪═══════════════╪═══════════╪═══════════╣
║some-task│timestamp      │           │COMPLETE   ║
╚═════════╧═══════════════╧═══════════╧═══════════╝
```
4. Destroy the task
```
dataflow:>task destroy some-task
Destroyed task 'some-task'
```
5. Re-create the task with the same name
```
dataflow:>task create --name some-task --definition timestamp
Created new task 'some-task'
```
6. See the task is already completed
```
dataflow:>task list
╔═════════╤═══════════════╤═══════════╤═══════════╗
║Task Name│Task Definition│description│Task Status║
╠═════════╪═══════════════╪═══════════╪═══════════╣
║some-task│timestamp      │           │COMPLETE   ║
╚═════════╧═══════════════╧═══════════╧═══════════╝
```

**Comment by sabbyanandan** [comment]
Hi, @johnlinp. The behavior you're seeing is a design decision by choice. The primary reason being able to traverse through and explore the historical executions for auditing purposes. It is more relevant for batch-job executions, too. 

We have an [open issue](https://github.com/spring-cloud/spring-cloud-dataflow/issues/3902) (contributions welcome!) to add the on-demand option to clean up the executions either individually or as a whole. There are, of course, repercussions to doing it if someone accidentally cleans them up. 

All that said, the fact that you're seeing the task status for a re-created task definition, that seems odd. @mminella: Perhaps the CD flow is wrongly connecting to the previously executed task's status?

**Comment by mminella** [comment]
All of the statuses are based on name, so if the name is recycled, then that is a risk. We could explore making names globally unique but what would have wide ranging impacts (CTR, properties, etc).

**Comment by sabbyanandan** [comment]
Addressed via: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3902.
