### ISSUE TITLE
Question - SCDF 2.6.0 - Openshift deployment

### ISSUE THREAD

**Issue by gry77** [spring-cloud/spring-cloud-dataflow#4097]
**Description**
I can verify DB schema is updated successfully, but seems like the Tomcat failed to start : 

> Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
> Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
> Caused by: java.net.SocketException: Permission denied

**Release versions**
2.6.0

**Steps reproduce**
Use MariaDB, then import the *.yaml in below sequence

1. server-roles.yaml
2. server-rolebinding.yaml
3. service-account.yaml
4. server-config.yaml (make sure to change the DB connection here )
5. server-svc.yaml
6. server-deployment.yaml

I uploaded all the yml and full log file in my repo : 
https://github.com/gry77/app-issue-repo/tree/master/Openshift-SCDF-issue/k8s-config

**Comment by sabbyanandan** [comment]
Hi, @gry77. For questions, it'd be better if you can post it in StackOverflow. One of us can review and respond to it there. We use GH for bugs and feature requests.
