### ISSUE TITLE
Add SCDF/Skipper monitoring configuration to the K8s installation instructions, docs, manifests.

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow#4103]
Dependes on #4099

**Comment by sabbyanandan** [comment]
Looks like at least the SCDF configmap related changes are already included in https://github.com/spring-cloud/spring-cloud-dataflow/pull/4118/files.

**Comment by tzolov** [comment]
This is [resolved](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/src/templates/kubernetes/server/server-config.yaml) for the `master` (e.g. 2.7.x branch) but can be backported to 2.6.x given that the metrics replication post processor is already available there.
