### ISSUE TITLE
Provide a live example for multiple input/output applications

### ISSUE THREAD

**Issue by johnlinp** [spring-cloud/spring-cloud-dataflow#4106]
**Problem description:**
In the [17.2. Stream Application DSL](https://docs.spring.io/spring-cloud-dataflow/docs/2.6.0/reference/htmlsingle/#spring-cloud-dataflow-stream-app-dsl) of the documentation, it provides an example of app-type application `Barista` and some setup steps. However, I was expecting that there is a live example for me to really try it on my own, but there's none. This is especially troublesome because there are no built-in app-type applications.

**Solution description:**
Please put the example code of `Barista` in https://github.com/spring-cloud-stream-app-starters/ and build it into a Maven artifact so that I can register it as a application.

**Comment by sabbyanandan** [comment]
Here's an example -> https://docs.pivotal.io/scdf-k8s/1-2/pro-features/multi-io-support.html
