### ISSUE TITLE
Metrics for Boot 2.3.x based apps aren't instrumented in Prometheus

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4109]
I built a few custom Kafka/Kstream apps on the Boot 2.3.x foundation. The applications successfully deploy on K8s; however, the metrics from the apps aren't instrumented in Prometheus, and likewise, no stats show up in Grafana.

The core dependencies in my app are:
```
              <dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud.stream.app</groupId>
			<artifactId>stream-applications-micrometer-common</artifactId>
			<version>3.0.0-M2</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud.stream.app</groupId>
			<artifactId>stream-applications-security-common</artifactId>
			<version>3.0.0-M2</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud.stream.app</groupId>
			<artifactId>stream-applications-postprocessor-common</artifactId>
			<version>3.0.0-M2</version>
		</dependency>
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-prometheus</artifactId>
		</dependency>
		<dependency>
			<groupId>io.micrometer.prometheus</groupId>
			<artifactId>prometheus-rsocket-spring</artifactId>
			<version>0.9.0</version>
		</dependency>
            </dependencies>
```

Enabled actuators:
> management.endpoints.web.exposure.include=health,info,bindings

Not sure what to look and where to start debugging. The monitoring samples in the repo are based on the older Spring Boot foundation, and they aren't useful for this exercise.

----

For the tease, I deployed the OOTB 3.0 M2 applications from `https://dataflow.spring.io/kafka-docker-milestone`. Once again, the `time | log` apps deploy successfully, but no metrics are scraped and the dashboard shows bogus charts.

To reproduce:
0) Provision SCDF 2.5.3 or 2.6.0 on K8s (same behavior on both versions)
1) Bulk import https://dataflow.spring.io/kafka-docker-milestone
2) Deploy `foo = time | log` stream
3) Go to Grafana from the Dashboard

**Comment by tzolov** [comment]
Please upgrade `prometheus-rsocket-spring` to version `1.0.0`. 

The Boot 2.3.0 in its path from M1, RC to GA had updated its `RSocket` version from `1.0.0-RC5`,`1.0.0.RC6`, `1.0.0.RC7` and `1.0.0`. (latest Boot 2.3.3 is at Rsocket `1.1.0`). 
The `prometheus-rsocket-proxy` as a Boot application had followed those changes having its own versioning schema: e.g. 0.9.0 and 0.10.0 corresponds to rsocket 1.0.0-RC5, the 0.11.0 moved to RC7 and so on.
Unfortunately, RSocket had the tendency to introduce not backward compatibility changes between minor versions and even between RC candidates.  For example an RSocket:RC5 is not compatible with RC7. 
This requires carefully selecting the versions working with the old and new OOTBB apps and the version used by the prometheus-rsocket-proxy.

**Comment by sabbyanandan** [comment]
I can confirm that with the following dependency upgrade, everything works as expected.

```
<dependency>
  <groupId>io.micrometer.prometheus</groupId>
  <artifactId>prometheus-rsocket-spring</artifactId>
  <version>1.0.0</version>
</dependency>
```
