### ISSUE TITLE
Deployment of app using kafka binder fails

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#411]
When deploying the sink app that uses `Kafka` binder, the following error occurs:

```
MessageChannelBinder does not support consumer property: durableSubscription
```

Since the `durableSubscription` is always set as the consumer property for the sink app and `Kafka` binder doesn't support this property, this error occurs.

**Comment by ilayaperumalg** [comment]
It turns out that the fix is required at Spring Cloud Stream to filter out the unsupported producer/consumer properties based on the binder being used: https://github.com/spring-cloud/spring-cloud-stream/issues/355

**Comment by mbogoevici** [comment]
Explicitly setting the `durable` flag should not be necessary, grouped subscriptions are durable by default if the binder supports it.
