### ISSUE TITLE
Metadata not included anymore for docker apps bulk import

### ISSUE THREAD

**Issue by jtrussart** [spring-cloud/spring-cloud-dataflow#4112]
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/13479921/90750117-a8bb1b00-e2d4-11ea-8682-58a17c0b57f8.png">

When doing a bulk import from the URL https://dataflow.spring.io/rabbitmq-docker-latest, the apps metadata are not included anymore. This only occurs for Docker version. Everything fine for the maven versions.

As a workaround, I selected the metadata lines from https://dataflow.spring.io/rabbitmq-maven-latest, but would be much more easier to get it back directly from the "Docker" URL.

**Comment by ilayaperumalg** [comment]
Hi @jtrussart , 

What version of SCDF are you using? We recently removed the maven metadata from Einstein SR8 docker apps as they have their labels set with the metadata. 

But, I see this could be an issue for the SCDF version that doesn't read the metadata from image labels. Thanks for reporting this! We'll get back to this shortly.

**Comment by jtrussart** [comment]
I'm running version 2.3.1.RELEASE

**Comment by ilayaperumalg** [comment]
> I'm running version 2.3.1.RELEASE

ok, thanks and that clarifies the issue as well. The support for metadata retrieval from container image labels was added since SCDF 2.5.x. But, we need to support the out of the box apps with maven metadata for SCDF versions before 2.5.x.

**Comment by sabbyanandan** [comment]
@sobychacko @tzolov: Could we add the metadata URIs to the next Einstein SRx? That way we will be backward compatible for folks who are using SCDF pre-2.5.x release versions.

**Comment by sobychacko** [comment]
@jtrussart Updated both RabbitMQ and Kafka docker apps bulk import files to include the maven links for metadata jars.
