### ISSUE TITLE
spring-cloud-dataflow-build 2.7.0-SNAPSHOT is missing in mvn global repository

### ISSUE THREAD

**Issue by umutcann** [spring-cloud/spring-cloud-dataflow#4115]
Hi,

I tried to build SCDF source code. But I'm getting error due to missing version of spring-cloud-dataflow-build 2.7.0-Snapshot.

https://github.com/spring-cloud/spring-cloud-dataflow/blob/180be06ebf0d3ab5f630aaefffa8b4cc3560077a/pom.xml#L15

I checked mvn Global Repository. It's missing.

![image](https://user-images.githubusercontent.com/18632831/90856958-c4352d00-e38b-11ea-9e93-bc0db9b192c3.png)

Thanks.

**Comment by ilayaperumalg** [comment]
Hi @umutcann ,

The snapshot builds aren't published into global maven repository instead they are published into Spring maven repository [here](https://repo.spring.io/libs-snapshot/org/springframework/cloud/spring-cloud-dataflow-build/2.7.0-SNAPSHOT/).

You can configure Spring snapshot repo in your maven to download the snapshots:

```
<repository>
                                        <id>spring-snapshots</id>
                                        <name>Spring Snapshots</name>
                                        <url>https://repo.spring.io/libs-snapshot</url>
                                        <snapshots>
                                                <enabled>true</enabled>
                                        </snapshots>
                                </repository>
```

**Comment by umutcann** [comment]
Hi  @ilayaperumalg ,

It's solved as you mentioned. Thanks for support.
