### ISSUE TITLE
User guide quick start doesn't mention redis

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-dataflow#412]
But it is a pre-requisite (admin app crashes on start up with no redis instance). Probably if people are running it using docker-compose they will need to set a property for the host as well?

**Comment by markpollack** [comment]
It is listed here. 

http://docs.spring.io/spring-cloud-dataflow/docs/1.0.x-SNAPSHOT/reference/htmlsingle/#getting-started-system-requirements

Prob should just move down into the other section.

**Comment by sabbyanandan** [comment]
Redis is not a mandatory requirement anymore. It is required only when the counter-sink applications are used in a stream and it is documented.
