### ISSUE TITLE
Long task name can not be launch

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow#4127]
**Description:**
A task name has a constraint of 250 chars max. Launch a task has a constraint of 100 chars max on the task name.

**Release versions:**
Latest

**Steps to reproduce:**
Create a task foo_12u8calathxeuyixljr38q3ekljgjfcvl2a7332uq5ah3ldys6431nyl5tifmw77vuyxnhpno9t9jjadwqzr4bkajkf0el5crfkecnj0sut99kzmft2cstbrq1nz9azfaay0sz4y6zzx256fxjbjelp92xjgohnk13a6ayzrkisx8wqb4hmub73oex1l3a64ej6kj9zg

Try to launch the created task.

**Comment by sabbyanandan** [comment]
While fixing this, let's also do an inventory of any other freeform "name fields" that are UI configurable (without the maxlength), and adjust the length also for those at the same time. 

@oodamien: Would you be able to do the first pass at it? If you can help with the inventory, we can adjust the backend schema accordingly. We can also restrict the UI fields with maxlenght proactively, as well.

**Comment by cppwfs** [comment]
Here is what we discovered when looking up maximum length for tasks and application names.
* Application names: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4189
* Task Names: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4190
* Documentation: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4191

UI: 
* Platform sensitivity when creating tasks definitions where platforms may have only 63 char max: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1575
* Stream task names with a maximum 255 chars for a task name: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1574

**Comment by sabbyanandan** [comment]
It looks all except the #4191 (doc story) is complete/merged. I approved the doc story, too. Nicely done!
