### ISSUE TITLE
Unable to change task's spring.datasource.driverClassName

### ISSUE THREAD

**Issue by dcguim** [spring-cloud/spring-cloud-dataflow#4128]
Despite changing the application.propeties driverClassName of the registered jar, and adding  `--spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver` as an argument in the Dataflow interface, when lauching a task, still I get:
![Screenshot 2020-08-30 at 17 22 06](https://user-images.githubusercontent.com/4180822/91662862-5c968480-eae5-11ea-81dc-8693021c8331.png)

Indeed dataflow-server (DATAFLOW_VERSION=2.6.0 SKIPPER_VERSION=2.5.0) is running as a docker container that was booted with a `docker-compose.yml` file environment set with `SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver`.

Nevertheless, I think it should be quite clear that if I am overriding the argument before lauching a specific task, that, well it should be overridden. 

This behaviour is easily reproducible by following:
https://dataflow.spring.io/docs/installation/local/docker/
to set up the environment, and for the Java application, this:
https://dataflow.spring.io/docs/batch-developer-guides/batch/spring-task/

**Comment by cppwfs** [comment]
I'm not sure why you would want to override the `spring.datasource.driverClassName` that is provided by SCDF and still expect SCDF to be able to track the results of the task execution.   I think you would rather have 2 datasources within your application, one that allows your task to record its information to the task execution table and the other for the business logic your app needs to work.  Here is an example of Spring Cloud Task that uses 2 datasources.   https://github.com/spring-cloud/spring-cloud-task/tree/master/spring-cloud-task-samples/multiple-datasources

**Comment by dcguim** [comment]
Because it was not correctly set, we have a mysql 5.7 database but the `driverClassName` is set to mariadb, and they are not the same: https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/#incompatibilities-between-mariadb-101-and-mysql-57
Although the dataflow tutorials treat them as interchangeable, hence the missleading settings. 
I appreciate the reference to multiple datasources but I am indeed trying to change `spring.datasource.driverClassName` .

**Comment by cppwfs** [comment]
Thank you for the clarification.

**Comment by dcguim** [comment]
I am just curious if in the [documentation](https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v2.6.0/spring-cloud-dataflow-server/docker-compose.yml) had indeed a driver mismatch between mysql 5.7 and mariadb ? And if it should still be corrected?
