### ISSUE TITLE
User guide quick start http POST fails

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-dataflow#413]
```
$ java -jar spring-cloud-dataflow-shell-1.0.0.M2.jar
...
Welcome to the Spring Cloud Data Flow shell. For assistance hit TAB or type "help".
dataflow:>stream create --name httptest --definition "http --server.port=9000 | log" --deploy
Created and deployed new stream 'httptest'
dataflow:>http post --target http://localhost:9000 --data "hello world"
> POST (text/plain;Charset=UTF-8) http://localhost:9000 hello world
Failed to access http endpoint http://localhost:9000
```

There's no error in the admin server console.

**Comment by dsyer** [comment]
This works though:

```
$ curl -H "Content-Type: text/plain" localhost:9000 -d 'hello'
```

so the problem seems to be in the `http post` command in the shell.

**Comment by dsyer** [comment]
Actually that works too now. So it was just a delay in getting the modules running? Maybe the docs should just say that a delay is expected and you might need to try again a few times?

**Comment by ilayaperumalg** [comment]
yeah, the app might just report it is `UP` based on the deployer SPI implementation while the binding might still be happening. It depends on which deployer you use. In your case, is this a `local` deployer (out of process - which is default) ? 

and yes, we need to have the doc updated for it. Marked this issue as `documentation`.

**Comment by dsyer** [comment]
I'm just following instructions in the user guide. I don't even know what a deployer is yet.

**Comment by ilayaperumalg** [comment]
ok, I see it uses `local` and for some reason it has `M2` version in there. I believe we need to fix that to the corresponding version of the doc as well.

**Comment by markpollack** [comment]
I'll add something to indicate you should wait to look at the logs and see if it the app has fully started. I've ran into this as well but thought it was a 'just me` kind of issue.
