### ISSUE TITLE
Stream definition view broken if using OAuth authorization

### ISSUE THREAD

**Issue by chringwer** [spring-cloud/spring-cloud-dataflow#4130]
The dataflow UI calls a `/streams/definitions/*/applications` endpoint which has no corresponding mapping in the authorization rules. The request fails with a 403 for this reason and the screen won't show.

https://github.com/spring-cloud/spring-cloud-dataflow/blob/2f425a1f850a6bfddc54415696b3b08d54134246/spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml#L158-L165

**Comment by ilayaperumalg** [comment]
Hi @chringwer , 

Thanks for reporting this issue. This is indeed a bug.
We'll get this fixed soon.
