### ISSUE TITLE
Bad Substitution Deploying Stream With Custom Processor

### ISSUE THREAD

**Issue by naderkhalid** [spring-cloud/spring-cloud-dataflow#4134]
**Overview**
_(Please let me know if I need to include other info and how I can get it as I'm not experienced in SCDF)_

I replicated the starter Filter processor (named it extractor) from github and used the docker Maven plug-in to create a Docker image. I then created a simple stream (testprocessor as "file | extractor | log") in SCDF running in Minikube locally with local Docker inside Minikube using "eval $(minikube docker-env)". Upon deployment, I get the following errors from kubectl logs (2 long lines in JSON format):

**_{line: 1, text: "--spring.cloud.dataflow.stream.app.label=extractor: --spring.cloud.stream.metrics.key=demo.extractor.${spring.cloud.application.guid}: bad substitution"}
{line: 2, text: "--spring.cloud.dataflow.stream.app.label=extractor: --spring.cloud.dataflow.stream.app.label=extractor: command not found"}_**

**Notes**
Before using SCDF, I deployed my Maven-built Docker image of the custom processor as a stand-alone pod/container and called /actuator/health from cURL successfully - no issues there.

**Versions**
Host: CentOS 8.2.2004 with 12 cores and 16gb RAM
Minikube: v1.12.3
Docker: Client 19.03.12 Server 19.03.8 containerd v1.3.3-14-g449e9269
SCDF: 2.6.1

**pom.xml**
[pom.xml.txt](https://github.com/spring-cloud/spring-cloud-dataflow/files/5175559/pom.xml.txt)

**dataflow:>runtime apps**
![dataflow-runtime-apps](https://user-images.githubusercontent.com/14103253/92253311-40209080-eec7-11ea-808d-063e88d4ca90.png)

**Comment by naderkhalid** [comment]
Running extractor maven-built docker image as a stand-alone pod/container:

**_[nader@nimir ~]$ curl http://$(getpodip.sh extractor):8080/actuator/health
{"status":"UP","groups":["liveness","readiness"]}_**

**Comment by naderkhalid** [comment]
I now know that I can get scdf-server and skipper pods logs. Hopefully, I'll gain more experience soon enough:

**scdf-server logs**
[scdf-server.log](https://github.com/spring-cloud/spring-cloud-dataflow/files/5175813/scdf-server.log)

**skipper logs**
[skipper.log](https://github.com/spring-cloud/spring-cloud-dataflow/files/5175815/skipper.log)

**Comment by ilayaperumalg** [comment]
Hi @naderkhalid ,

A few questions:

- Are you sure you have the docker image available as `public`? If not, make sure they are accessible.

- If these images belong to private container registries, make sure you configure your registry config as mentioned [here](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_private_docker_registry)

- I am also not sure why you wanted to set the `image-pull-policy` deployment property for your app. Even if you want to set one, that needs to be set at the `deployment` time **not** at the time of stream `creation` time. When deploying, you need to specify the properties as `deployer.extractor.kubernetes.image-pull-policy`.

**Comment by naderkhalid** [comment]
I appreciate your response and feedback.
I'm not using a public docker repo. It's in the same minikube cluster used by my SCDF.
I'll check the other 2 points in your feedback and post my findings.

-Regards

**Comment by ilayaperumalg** [comment]
If you are using `minikube`, then this maybe something you would find useful:

```
eval $(minikube -p minikube docker-env)
docker push <your image>
`
and,

When deploying the app, set the `image-pull-policy` to `Never` using `deployer.extractor.kubernetes.image-pull-policy`

**Comment by naderkhalid** [comment]
Thank you.
Where exactly do I set deployer.extractor.kubernetes.image-pull-policy ?

**Comment by ilayaperumalg** [comment]
When you do the `stream deployment`. If you are using the SCDF shell, then it is when you run `stream deploy` command. If you use the web UI, then you can set this as a deployment property from `Stream Deploy` page.

As a side note, please ask your questions on StackOverflow while we keep GH for reporting issues and feature requests. Thank you for the understanding!

**Comment by naderkhalid** [comment]
Since this seem to be an issue with me setting up SCDF and not a bug, I'll continue with your recommendations and close the issue.
Much appreciated!
