### ISSUE TITLE
Set Deployment config for Batch Application which is running on Openshift

### ISSUE THREAD

**Issue by umutcann** [spring-cloud/spring-cloud-dataflow#4135]
Hi,

Is there any feature or parameter to set deployment config name while launching task for app which is running on Openshift?

Thanks.

**Comment by ilayaperumalg** [comment]
Hi @umutcann, 

There is no such feature specific to OpenShift on SCDF yet.

**Comment by umutcann** [comment]
Hi @ilayaperumalg 

Maybe I express my own wrongly.

I joined Spring One event. I saw that we can set config map while launching task. I though that we may set deployment config while launching task. 

If there is no feature like I express, I think It would be usefull feature.

**Comment by ilayaperumalg** [comment]
@umutcann I might have misunderstood as well. 

SCDF provides a way to launch your task with a set of K8s specific deployment config irrespective of whether you run on OpenShift or not. In my earlier response, I meant to say, SCDF doesn't have any OpenShift specific deployment config.

**Comment by umutcann** [comment]
@ilayaperumalg Thank you.

So how can we set deployment config for kubernetes? Is there any document to set that?

**Comment by cppwfs** [comment]
Here is the basics for deployment properties for a task: https://dataflow.spring.io/docs/feature-guides/batch/deployment-properties/#how-to-set-these-properties
Here are some of the properties you can set for kubernetes: https://docs.spring.io/spring-cloud-dataflow/docs/2.6.1/reference/htmlsingle/#configuration-kubernetes-deployer

**Comment by umutcann** [comment]
As I see, we couldn't set deployment config via SCDF :(

Thanks for help.

**Comment by umutcann** [comment]
Hi,

Actually I need to upload some files(certificate, cacert vs) into volume. 

In the document you [share](https://docs.spring.io/spring-cloud-dataflow/docs/2.6.1/reference/htmlsingle/#configuration-kubernetes-deployer), SCDF enables us to set volume as I understand. 

But I couldn't get it how can I upload files to that volume.

Do you have any idea regarding this issue?

Thanks.
