### ISSUE TITLE
Notification for AppAlreadyRegisteredException

### ISSUE THREAD

**Issue by MariusKl** [spring-cloud/spring-cloud-dataflow#4139]
**Problem description:**
Register an application via browser. Afterwards register another application with the same name.
An exception is thrown
`09:30:07.373 ERROR [https-jsse-nio-9393-exec-20] [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.cloud.dataflow.server.controller.AppAlreadyRegisteredException: The 'task:yyy' application is already registered as maven://xxx] with root cause
org.springframework.cloud.dataflow.server.controller.AppAlreadyRegisteredException: The 'task:yyy' application is already registered as maven://xxx
`

**Solution description:**
An additional notification/popup in the browser would be nice.

**Additional context:**
Not sure if this is a bug or a feature request. Tested with latest version of Brave and Firefox and spring-cloud-dataflow version 2.6.1

**Comment by sabbyanandan** [comment]
Thanks for the report, @MariusKl. It'd be nice to gracefully handle it and show a user-friendly message in the Dashboard. I will move it to the UI repo.

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-dataflow-ui #1550](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1550) via [**ZenHub**](https://www.zenhub.com/)
