### ISSUE TITLE
Order executions by execution id

### ISSUE THREAD

**Issue by MariusKl** [spring-cloud/spring-cloud-dataflow#4140]
**Problem description:**
We have a couple of executions for a batch task. Due to an issue some of these executions failed, resulting in no start date in the database. It seems that in the frontend the executions are ordered by start date by default, resulting in the failing executions in the first rows.

![image](https://user-images.githubusercontent.com/4563238/92925885-803dc100-f43b-11ea-888e-3bed8ffa280a.png)

**Solution description:**
I suggest to order by execution id (newest first) by default. Or is there any good reason to use the start date?

**Additional context:**
Version 2.6.1

**Comment by sabbyanandan** [comment]
I can't think of any reasons other than intending to show the latest executions first. However, sorting by start date would indeed fail with non-date values. @oodamien: Can you think of any other reasons? Perhaps better to sort by execution-id in descending order, after all.

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-dataflow-ui #1560](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1560) via [**ZenHub**](https://www.zenhub.com/)
