### ISSUE TITLE
Clean up and stop task execution commit

### ISSUE THREAD

**Issue by dcguim** [spring-cloud/spring-cloud-dataflow#4150]
As a SCDF user, I find it easier to create SCDF scripts that `register`, `unregister` apps; `create`, `launch` tasks; and `stop`, `clean up` task executions automatically as opposed to clicking around the GUI. Therefore, I am often using the SCDF DSL, I realized that one can only _request_ a `clean up` or `stop` of a task execution, and often it takes a long time until the task execution and it's respective jobs are indeed deleted from specified SCDF metadata database. 
For this reason, I would like to request for the feature of commiting such "_requests_".

**Comment by sabbyanandan** [comment]
Hi, @dcguim. Glad to hear you're more fluent and are finding the DSL/APIs more natural to use. It'd come handy for CI/CD automation, as well. Please continue to push the capabilities, and let us know if there are any improvements you'd benefit from the APIs proper. 

As for the "committing such requests", could you expand on what you mean by it? Is that meaning, you'd like to submit the request to queue-up for cleaning and asynchronously respond when the operation is complete?

**Comment by dcguim** [comment]
By commiting I mean to execute the request for stopping and cleaning up task executions.

**Comment by sabbyanandan** [comment]
Thanks, @dcguim. Curious what you're going to gain from stoppping such requests, though. If it is just the matter of forcibly wanting to interrupt the request, so you can perform other operations, then I don't think the current system is preventing you from running other parallel requests.

@mminella: Do you have any thoughts on whether we have the flexibility to stop the running transaction and roll it back cleanly?

**Comment by dcguim** [comment]
There are 2 main motivations behind it:
1) Pragmatically, while implementing SCDF batch tasks;
1.1) I launch an SCDF task, 
1.2) they crash at some point, and 
1.3) I fix the errors and loop again.
Nevertheless, if I launch a task with a job name equal to an existing job name, SCDF won't start. Not to mention, this issue https://github.com/spring-cloud/spring-cloud-dataflow/issues/4142 .
Therefore I would like to automatically or programatically have a clean SCDF environment before each loop again.
2) I have the _feeling_ that this functionality is not the same between the GUI and SCDF DSL, i.e. when I stop and clean tasks on the GUI, these tasks are instantaneously removed from the GUI, and I can run a new task with the same job name as the removed task. If I, however, request `stop` and `clean up` with the DSL I don't have this desired instantaneous quality.

**Comment by sabbyanandan** [comment]
Thanks for the additional details, @dcguim. We will review it to see if there are any differences, and that can be tightened up. If you have cycles, too, feel free to start the dialog with a PR with what you see improvements to this workflow.

**Comment by sabbyanandan** [comment]
Hi, @dcguim, it is now possible to also clean up the associated task executions via a few new APIs: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1710#issuecomment-842989062 -- see if that helps with your automation.

If you still see areas of improvement, feel free to comment and reopen.
