### ISSUE TITLE
SCDF keep jar which I want to replace with new version

### ISSUE THREAD

**Issue by szopal** [spring-cloud/spring-cloud-dataflow#4157]
If I have app based on jar file (SpringBatch app) and I would like to update some of code and redeploy it on SCDF I can't replace old jar without stopping SCDF.

**Comment by ilayaperumalg** [comment]
Hi @szopal , 

You need to register a new version of the app that has the updated code and re-launch that batch job.
More on this here: https://dataflow.spring.io/docs/batch-developer-guides/continuous-deployment/cd-basics/

**Comment by ilayaperumalg** [comment]
Please use StackOverflow to ask questions around SCDF: https://stackoverflow.com/questions/tagged/spring-cloud-dataflow  while we use GH issues to report issues and enhancements. Thanks!
