### ISSUE TITLE
Deployment page in dashboard fails to parse stream definition using composed functions

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-dataflow#4161]
**Description:**

Given the following stream definition: 

```
s3 --spring.cloud.function.definition='s3supplier|taskLaunchRequestFunction' .... | tasklauncher --spring.cloud.dataflow.client.server-uri=http://dataflow-server:9393
```

The deployment screen interprets `taskLaunchRequestFunction` as a processor.  

![image](https://user-images.githubusercontent.com/886859/93889553-5300d680-fcb7-11ea-8edf-bec14e8f5748.png)

**Release versions:**
2.6.1

**Comment by dturanski** [comment]
Dataflow doesn't try to deploy the "processor" but fails, "taskLaunchRequestFunction is not a registered app",  if you try to update the stream.

**Comment by dturanski** [comment]
Also unable to deploy again after undeploy.

**Comment by sabbyanandan** [comment]
@dturanski @ilayaperumalg: Is this still an issue?

**Comment by dturanski** [comment]
AFAIK yes
