### ISSUE TITLE
Add RESTful endpoint to allow users to query job execs by task exec id

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#4165]

**Comment by siddhantsorann** [comment]
Hey @cppwfs So I was going through the code for this feature. Currently, in the JdbcSearchableJobExecutionDao we don't have access to the task execution id. One idea I had was that... 
in DefaultTaskJobService we get the task execution id for our job executions so until here we can fetch all job executions, once we have the task execution id for each of them we can filter the list to filter out the job executions which match the task execution id specified in the API. 
Would this make sense?

**Comment by siddhantsorann** [comment]
Hey @cppwfs Yeah, that would make sense, I'll submit a PR for that.
