### ISSUE TITLE
Container image repository name validation when using image digest instead of tag

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#4169]
When the container image of a stream/task application is registered with SCDF, it could have image digest or tag. For instance,

I can have an app like follows:

`docker:mydevapps.io/p-scdf-for-kubernetes/spring-cloud-dataflow-composed-task-runner:<tag>`

`docker:mydevapps.io/p-scdf-for-kubernetes/spring-cloud-dataflow-composed-task-runner@sha256:<hash>`

When the image metadata is retrieved, the container image's repository name is currently parsed with the assumption of having a `tag` in the image name and this breaks when I have an app with the image digest in it.

**Comment by tzolov** [comment]
What the `@sha256:<hash>` is nor where it comes form and why it is in the image name? 

According tot docker specs an image name is made up of slash-separated name components, prefixed by a registry hostname and optional port number. The name components define a namespace followed by a repository-name and a tag. The repository name needs to be unique in that namespace.

The container image has following structure:

```
registry-hostname : port / repo-namespace / repo-name : tag
|     REGISTRY-HOST      |          REPOSITORY        | TAG |
```
 
 - The repository namespace is made up of zero or more slash-separated path components (eg. '/ns1/ns2/.../nsN/'). [Find more the namespace allowed format](https://docs.docker.com/registry/spec/api/#overview)
 - The registry hostname (or IP) and the optional port parts together form the REGISTRY HOST. Later is used as a unique identifier of the Container Registry hosting this container image. If not explicitly specified, a default registry host value is used.
 - The repository namespace together with the repository name form a unique REPOSITORY identifier, unique  within the REGISTRY HOST.
- The TAG represents a particular REPOSITORY instance within the REGISTRY HOST.

Furthermore:
- The repository name needs to be unique in that namespace, can be two to 255 characters, and can only contain lowercase letters, numbers or` -` and` _`  : https://bit.ly/2Vz8kev
- A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters: https://dockr.ly/3chhQZF

Most of the the above Docker Image name spec are implemented and validated in the [ContainerImage](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-configuration-metadata/src/main/java/org/springframework/cloud/dataflow/configuration/metadata/container/ContainerImage.java) class

So according to the spec **@** is not allowed in the repo name.

**Comment by tzolov** [comment]
Apparently the @digest is a [supported reference](https://github.com/docker/distribution/blob/master/reference/reference.go) :
`reference                       := name [ ":" tag ] [ "@" digest ]`
