### ISSUE TITLE
Improve documentation on how to configure container registry config

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#4180]
We can improve our existing documentation on configuring the container registry properties especially by adding how one can mount the config/secret in [this](https://dataflow.spring.io/docs/2.7.0.SNAPSHOT/installation/kubernetes/helm/#volume-mounted-secretes) section of the document.

**Comment by sabbyanandan** [comment]
Should this be in ref. guide or a recipe in Microsite?

**Comment by ilayaperumalg** [comment]
What we have here: https://dataflow.spring.io/docs/feature-guides/general/application-metadata/#container-registry-support is sufficient and hence closing.
