### ISSUE TITLE
DefaultAppRegistryService.save needs to verify that app name is less than 255

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#4189]
Currently if a user creates a name that is greater than 255 chars in length the message that is returned does not tell them what happened.  We need to check the app name is greater than 255 and return a meaningful message.   This will occur if using RESTful API or shell.

**Comment by siddhantsorann** [comment]
Hey @cppwfs can I pick this up?

**Comment by cppwfs** [comment]
Its yours!!!!   
Thanks @siddhantsorann !

**Comment by siddhantsorann** [comment]
Thanks @cppwfs 
Can we have the check in AppRegistryController? We have a function there that validates the application name, can add this check there.

**Comment by cppwfs** [comment]
sure.
