### ISSUE TITLE
Need to verify that task def name < 64 char when launching on CF or K8s

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#4190]
When user launches a task definition and the user selects a platform that is CF or K8s be sure to verify that the task definition name is less that 64 characters.   If not return a meaningful error message vs. the one returned from the platform.

**Comment by siddhantsorann** [comment]
Hey @cppwfs Which file would this validation need to be in? At which point do we know the platform a task is being launched in?

**Comment by cppwfs** [comment]
DefaultTaskExecutionService.java   
After the method has retrieved the launcher: https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java#L225, you can add the check.   Look at line https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java#L291 to see how check which platform type has been selected.
