### ISSUE TITLE
Authentication for Spring Cloud Data Flow Server

### ISSUE THREAD

**Issue by Anumolm** [spring-cloud/spring-cloud-dataflow#4192]
I would like to add authentication to Spring Cloud Data Flow Server application. I see articles regarding Cloud Foundry UAA with LDAP support. I tried the basic authentication snippet as well which is not working.

I see lot of references to the link https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/security-ldap-uaa-example In that, the ldap server code is using Apache DSContainer which is deprecated and not working in my local. Is there any other approach? It's greatly appreciated if someone can provide a sample code for the same.

**Comment by sabbyanandan** [comment]
Hi, @Anumolm. We have a few auth-n/auth-z samples at https://github.com/jvalkeal/randomstuff. For questions like this, please use StackOverflow, we use GitHub for bugs/feature requests. I notice that you are posting the same question in multiple forums. It'd help if you can stick with just one forum going forward.
