### ISSUE TITLE
AppRegistryController should not throw 5xx errors

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#4196]
Part of a PR #4195 realised that we should throw something else than `IllegalArgumentException` as that is not handled with `RestControllerAdvice` thus 5xx is send to client. Server errors are kinda meant for errors what user could not fix by changing request.

**Comment by siddhantsorann** [comment]
Hey, @jvalkea @cppwfs I'd be happy to pick this up if you can provide me the above detail.

**Comment by siddhantsorann** [comment]
Hey, @jvalkeal @ilayaperumalg I would like to pick this ticket up. Let me know if there is anything I need to know before starting work on this. Thanks.

**Comment by ilayaperumalg** [comment]
@siddhantsorann Sure, thanks! Your above suggestion on keeping the custom exception in RestControllerAdvice seems reasonable. Please go ahead and let's see how that evolves.
