### ISSUE TITLE
Synchronize Kafka version in Docker Compose and Kubernetes deployments

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4209]
For 2.7, the docker-compose and the K8s deployment YAML (for Kafka) needs to upgrade to the latest/supported release.

**Comment by chrisjs** [comment]
what is the specific version we are looking to use here? there are various "vendors" (`confluent`, `wurstmeister`, etc) as well as versions.

**Comment by sabbyanandan** [comment]
Today, we are using these versions of Confluent images: https://github.com/spring-cloud/spring-cloud-dataflow/blob/4b77f221d83519c34da95915d52757ba6f6bb675/spring-cloud-dataflow-server/docker-compose.yml#L33-L54

It'd be good to use the same stack in K8s, but let's upgrade to the latest GA version of the broker/zk.

**Comment by chrisjs** [comment]
thanks, k8s uses other images so wasn't sure which to prefer. looks like `5.4.3` would be the most recent for kafka & zk when using confluent images

**Comment by sabbyanandan** [comment]
Yep, let's switch to the Confluent stack and the latest version available.
