### ISSUE TITLE
Remove explicit java-cfenv version

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#4221]
Due to hardcoded version in https://github.com/spring-cloud/spring-cloud-dataflow/blob/64e8918f6dabebe2f284ae5bac4ada83b216c735/spring-cloud-dataflow-platform-cloudfoundry/pom.xml#L15

it may leak to dependant builds. Should rely on parent pom.

**Comment by ilayaperumalg** [comment]
Backported into 2.6.x as 09158d42d40beb23b6246caf264ad1c73f0fa90a
