### ISSUE TITLE
Deploy Spring cloud dataflow server on docker 

### ISSUE THREAD

**Issue by Mwea** [spring-cloud/spring-cloud-dataflow#423]
The question is in the title, is there a way to deploy a container on docker to run SCDF server and connect it to a redis server ( also launched by docker ) ? 

If not, can someone sent me a link explaining how to develop a such thing and propose this on the repo ? Thanks :+1:

**Comment by sabbyanandan** [comment]
HI, @Mwea: Sorry for the delayed response. We use the [`docker-maven-plugin`](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/blob/master/spring-cloud-dataflow-server-kubernetes/pom.xml#L55) to generate the docker image for k8s-server. Perhaps you could follow a similar approach to generate the local-server image, too. 

Also, we do not support `redis` as the default binder anymore. You could either use kafka or rabbit instead.
