### ISSUE TITLE
SCDF UI stream status is UNDEPLOYED but the stream is up and running (when checking via CLI)

### ISSUE THREAD

**Issue by aharonmu** [spring-cloud/spring-cloud-dataflow#4235]
SCDF Version 2.6.3
Skipper Version: 2.5.2
Env: cloudfoundry deployment
I created a stream via the UI , left it on for a day.
The next day , the UI showed the stream in UNDEPLOYED state but when checking the apps via the cf cli , they are all started and fully functional.
SCDF UI Runtime tab also shows nothing is running.

Have you observed such issue?

**Comment by sabbyanandan** [comment]
Hi, @aharonmu. This is strange. Are the runtime aspects of the apps looking good, health-wise? Also, is this continuing to be as UNDEPLOYED or flips back again? We would love to look into it if there are reproducible steps, though.

**Comment by aharonmu** [comment]
Yeah the runtime aspects look good and the stream is running as expected....
- It stays as UNDEPLOYED
It happen to me more than once....i will try to get the exact steps....

**Comment by aharonmu** [comment]
Steps to reproduce:
1. create a stream with a source and sink
2. deploy it
3. once the stream has status DEPLOYED , restage the skipper

The stream will have the status UNDEPLOYED although the cf cli shows all apps are up and running.

**Comment by sabbyanandan** [comment]
Thanks, @aharonmu. If it is using a persistent DB, the state should reflect correctly even after a restage, though. What database does Skipper use?

**Comment by aharonmu** [comment]
A really large postgress

**Comment by aharonmu** [comment]
BTW....if i destroy the steam via the UI....the apps are not deleted from the cf cli...but are deleted only in the UI....
Which means i now have apps which are not reflected at all in the SCDF UI....

**Comment by sabbyanandan** [comment]
Unfortunately, I am unable to reproduce it in H2 and MySQL. Unless the state between SCDF and Skipper are significantly different on restages, I don't see this happening. We will give it a go with Postgres.

**Comment by jvalkeal** [comment]
It would be good to see skipper logs when it's started to see that everything looks ok.

**Comment by aharonmu** [comment]
Skipper is up and running and i am able to create new streams.

I am not sure i can share the logs as they might have some confidential data
But i can say that this command:
cf logs skipper-server --recent | grep error

has no special errors , except maybe this:
 2020-11-11T21:23:28.28+0200 [APP/PROC/WEB/0] OUT 2020-11-11 19:23:28.283  WARN 7 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/skipper-server/cloud": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)

**Comment by jvalkeal** [comment]
Well I wanted to see full startup logs to see that everything looks good, especially for configured db. ConfigServicePropertySourceLocator warning is just a noise as cloud libs tries to see if config server is available.

**Comment by aharonmu** [comment]
Ok i think i understand the issue
While looking at the logs i saw that it is working with H2 and not my postgress DB
Then i realised that in bound only the SCDF server to a postgress and not the skipper...

Database: jdbc:h2:mem:testdb (H2 1.4)

So i guess this is the issue....right?
Now i wonder how come the stream itself  still appears in the UI?

**Comment by jvalkeal** [comment]
Yes that's the issue. This happens because dataflow itself knows that there's supposed to be a stream definition and skipper manages a stream lifecycle itself as it's a one talking to platforms like cf. When embedded db goes away with a restart, skipper doesn't know anything about those streams anymore.

**Comment by aharonmu** [comment]
great , thx!
