### ISSUE TITLE
Implement Local deployer in spring-cloud-deployer

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#424]
As a developer, I want to explore the implementation of `OutOfProcessModuleDeployer` in `spring-cloud-deployer` project.

**Acceptance:**
- Existing `stream` and `task` unit tests run successfully

**Comment by markfisher** [comment]
added `LocalAppDeployer` and `LocalTaskLauncher` in this sub-project of `spring-cloud-deployer`: https://github.com/spring-cloud/spring-cloud-deployer/tree/master/spring-cloud-deployer-local

(modeled after `OutOfProcessModuleDeployer`)
