### ISSUE TITLE
SCDF Dashboard Step Details can not show details - TypeError: r is not iterable

### ISSUE THREAD

**Issue by GizemYILMZ** [spring-cloud/spring-cloud-dataflow#4242]
Hello,
We are using SCDF on Kubernetes enviroment.
I'm having an issue with showing step execution details from job executions page on SCDF dashboard.
When I Click on the on step details getting "TypeError: r is not iterable" error.  I've looked into the problem a little deeper, saw that if Instance_id and Execution_id in the job execution list are different from each other, it gives an error. If not it works correctly.

**Release versions:**
SCDF version: 2.7.0-SNAPSHOT
Kubernetes version: v1.17.1+9d33dd3

**Steps to reproduce:**
The problem can be seen if the same job instance is run with different executions.

**Screenshots:**
We can see step details in the execution of job "4893", but not in other runs.
![image](https://user-images.githubusercontent.com/18364696/98666694-6c8cd900-235e-11eb-8e99-bdc4e5d529d8.png)

This is the error;
![image](https://user-images.githubusercontent.com/18364696/98666779-8f1ef200-235e-11eb-8356-74b0e28a82cb.png)

**Comment by cppwfs** [comment]
I was unable to reproduce your issue.  Here are the steps take:

1. Ran pausedemo job multiple times
2. Restarted a couple of the failed pausedemo jobs to mix up the batch instance and batch executionids.  Results are shown below:
![image](https://user-images.githubusercontent.com/695673/98688633-10638e00-2339-11eb-8c3c-7cb452b164ff.png)

3. In each case the step execution detail was accessible.

* Can you see if there is a missing step in the scenario above that may reproduce the problem?
* Can you provide the SCDF Log that shows the exception?

**Comment by GizemYILMZ** [comment]
Hi,

We did not do anything different from what you did.

Maybe responses can give idea. 

These are requests and responses when I click on step; 

http://scdf-server-backend-architecture.apps.fw.garanti.com.tr/jobs/executions/4873

{"_embedded":{"errors":[{"message":"There is no JobExecution with id=4873","logref":"NoSuchJobExecutionException","_links":{"self":{"href":"/"}}}]}}

http://scdf-server-backend-architecture.apps.fw.garanti.com.tr/jobs/executions/4873/steps/5932

![image](https://user-images.githubusercontent.com/18364696/98775801-e07ebe00-23fe-11eb-81f0-7f8aeef2c1e7.png)

http://scdf-server-backend-architecture.apps.fw.garanti.com.tr/jobs/executions/4873/steps/5932/progress

![image](https://user-images.githubusercontent.com/18364696/98775808-e379ae80-23fe-11eb-80d2-a92f64a5350a.png)

Thank you.

**Comment by GizemYILMZ** [comment]
Hi,

We did not do anything different from what you did.

Maybe responses can give idea.

These are requests and responses when I click on step;

/jobs/executions/4873

{"_embedded":{"errors":[{"message":"There is no JobExecution with id=4873","logref":"NoSuchJobExecutionException","_links":{"self":{"href":"/"}}}]}}

/jobs/executions/4873/steps/5932

image

/jobs/executions/4873/steps/5932/progress

image

And these are more details about job.

image

image

image

Thank you.

**Comment by jvalkeal** [comment]
Just to confirm something, when you're on `jobs executions` page and click `4892`, on what address UI navigates you? That table is generated from `/jobs/thinexecutions`.

**Comment by jvalkeal** [comment]
One thing worth to check is that you're actually on a latest snapshots. We just realised that a month ago we had a relevant fix for around this issue:

https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/33bc92f9bb003ecbac9545fa11ad118c9947ad71#diff-6d2cec3955e825d567ad25ec24ff617b5abf4d47a6691250ff9625ef916119c4

**Comment by cppwfs** [comment]
You can refer to issue https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1568 to read more.

**Comment by GizemYILMZ** [comment]
> Just to confirm something, when you're on `jobs executions` page and click `4892`, on what address UI navigates you? That table is generated from `/jobs/thinexecutions`.
> 
> Almost looks like it takes you to `/dashboard/#/tasks-jobs/job-executions/4873` while it should go to `/dashboard/#/tasks-jobs/job-executions/4892`

Hi,

When i click on the job '4892', processes happening orderly below, 
/jobs/executions/4892
/tasks/executions/2707

**Comment by GizemYILMZ** [comment]
> Just to confirm something, when you're on `jobs executions` page and click `4892`, on what address UI navigates you? That table is generated from `/jobs/thinexecutions`.
> 
> Almost looks like it takes you to `/dashboard/#/tasks-jobs/job-executions/4873` while it should go to `/dashboard/#/tasks-jobs/job-executions/4892`

Hi,

When i click on the job '4892', the following actions happening;

/jobs/executions/4892
/tasks/executions/2707
/tasks/definitions/retail-sme-proactive-loan-batch-v0-TNAAVSPR?manifest=false
/tools/parseTaskTextToGraph

So, it doesnt take me to  "4873".  But, if I click on step take to "4873" ( job_instance_id).

**Comment by GizemYILMZ** [comment]
> One thing worth to check is that you're actually on a latest snapshots. We just realised that a month ago we had a relevant fix for around this issue:
> 
> [spring-cloud/spring-cloud-dataflow-ui@33bc92f#diff-6d2cec3955e825d567ad25ec24ff617b5abf4d47a6691250ff9625ef916119c4](https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/33bc92f9bb003ecbac9545fa11ad118c9947ad71#diff-6d2cec3955e825d567ad25ec24ff617b5abf4d47a6691250ff9625ef916119c4)

We will get the latest version and try it. I'll let you know after trying :) . Thank you

**Comment by GizemYILMZ** [comment]
Hi,
We are able to see execution details  with new version. 
Thank you.

**Comment by ilayaperumalg** [comment]
Thanks for checking and confirming!
