### ISSUE TITLE
Task execution cleanup initiated via the shell needs to remove task exec data

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#4247]
Currently when a user executes a `task execution cleanup --id 1`, the pod is removed as expected.   However the user is not given the option to delete the associated task execution entry from the task_execution table via the shell.   

We need to offer an optional `--remove-data` flag that will delete the task execution entry in the task_execution table along with the pods.

**Comment by sabbyanandan** [comment]
Relates to https://github.com/spring-cloud/spring-cloud-dataflow/issues/3902.
