### ISSUE TITLE
Grafana console does not display in Firefox

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4253]
@dturanski commented on [Fri Nov 13 2020](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1597)

From the Streams page, with Grafana/Prometheus configured. Press Grafana button.  Blank page

![image (2)](https://user-images.githubusercontent.com/886859/99096117-ea8df180-25a3-11eb-8d1e-f181b3a95ba7.png)

Same install works as expected in Chrome

---

@oodamien commented on [Mon Nov 16 2020](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1597#issuecomment-728151489)

@tzolov

**Comment by tzolov** [comment]
Just tested with SCDF 2.7.0-SNAPSHOT (and related `springcloud/spring-cloud-dataflow-grafana-prometheus:2.7.0-SNAPSHOT` image) and Firefox `83.0 (64-bit)` and it works perfectly fine:

<img width="1388" alt="Screen Shot 2020-11-19 at 6 27 36 PM" src="https://user-images.githubusercontent.com/1351573/99701709-196d0180-2a95-11eb-820b-61ff0f9a4d9a.png">

**Comment by tzolov** [comment]
@sabbyanandan can we close this issue?

**Comment by sabbyanandan** [comment]
Thanks for checking!
