### ISSUE TITLE
When a scheduled task is fired, all defined arguments/properties are not transmitted 

### ISSUE THREAD

**Issue by scizeron** [spring-cloud/spring-cloud-dataflow#4260]
**Description:**
I defined a task. 
When I manually launch the task including some args and properties, everything is ok, all  args/properties are well transmitted.
If I take the same task and if I define it as a scheduled task with the same set of props/args, when the task is fired, no props/args are transmitted and the task fails because some of them are mandatory in my case

**Release versions:**
Version: 2.6.3

**Custom apps:**
Not applicable

**Steps to reproduce:**
Define a spring boot property in your app and display it. Use Arguments to override it. It works perfectly with manual launch but fails with scheduling

**Screenshots:**
Not applicable

**Additional context:**

**Comment by cppwfs** [comment]
Are you deploying to Kubernetes or to Cloud Foundry?    
What properties and command line args are you passing to the Schedule?

**Comment by scizeron** [comment]
I deploy in K8s. I put Kubernetes logs in DEBUG, all is transmitted in both ways (Using command args: ...) but it doesn't work.
The args contain some values like "--spring.cloud.kubernetes.config.name=... --spring.cloud.kubernetes.secrets.name=... " because my application uses configMaps/secrets. 
When I launch manually, I specify a service account with the good rolebinding and it get info from configMaps/Secrets but in the cases, it is probably the issue, i see nothing about "deployer" properties

**Comment by scizeron** [comment]
> Are you deploying to Kubernetes or to Cloud Foundry?
> What properties and command line args are you passing to the Schedule?


I deploy in Kubernetes . I put Kubernetes deployer logs in DEBUG, all is transmitted in both ways (Using command args: ...) but it doesn't work.
The args contain some values like "--spring.cloud.kubernetes.config.name=... --spring.cloud.kubernetes.secrets.name=... " because my application uses configMaps/secrets.
When I launch manually, I specify a service account with the good rolebinding and it get info from configMaps/Secrets but in the cases, it is probably the issue, i see nothing about "deployer" properties

**Comment by scizeron** [comment]
I have checked and the difference between both is the service account.
When I launch the task, I use "deploy.my_task..kubernetes.deploymentServiceAccountName=..." and it workds
When I schedule the task with the same props, the pod is laucnhed with the default service account

**Comment by scizeron** [comment]
probably because in one case it is a regular pod and on the other side it was fired by a K8s Cron job

**Comment by scizeron** [comment]
yes, I have just seen there is a diff with deployer.* and scheduler.* for props but in the UI, when clicking on ? for properties, it talks about deployer.

**Comment by cppwfs** [comment]
It  looks like you have resolved your issues.  Should we close this issue?

On the use of `scheduler.` or `deployment.<appname>.` as a prefix, I've created issues to resolve the ambiguity.
https://github.com/spring-cloud/spring-cloud-dataflow/issues/4262 & https://github.com/spring-cloud/spring-cloud-dataflow/issues/4261.
Thanks for bringing it up.

**Comment by scizeron** [comment]
yes, closed for me, Thanks for support
