### ISSUE TITLE
Update docs to remove the use of scheduler. for deployment properties.

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#4261]
Update docs to remove the use of the `scheduler.` prefix for setting deployment properties.   Users can use the `deployment.<taskname>.` prefix.

**Comment by ilayaperumalg** [comment]
Re-opening to see if we need to backport the changes.

**Comment by cppwfs** [comment]
Sure!

**Comment by jvalkeal** [comment]
Closed issue can be marked to get backported, no need to re-open.
