### ISSUE TITLE
No logging in Task Execution Details when starting task by scheduler

### ISSUE THREAD

**Issue by rallepalle** [spring-cloud/spring-cloud-dataflow#4268]
**Description:**
Running SCDF-Server 2.6.3:
No logging output in UI when starting a task with scheduler.
Starting the task manually via UI the logging is in dashboard/#/tasks/executions/{executionId}
Same problem as in former version (2.2.x). Was solved after introducing the scheduler-task-launcher.
Now with latest release (2.6.3) without scheduler-task-launcher there is no log info again!
Same issue, see spring-cloud/spring-cloud-dataflow#3678

**Release versions:**
Running SCDF-Server 2.6.3:

**Additional context:**
Same issue, see spring-cloud/spring-cloud-dataflow#3678

**Comment by ilayaperumalg** [comment]
@rallepalle The reason for this behavior is explained [https://github.com/spring-cloud/spring-cloud-dataflow/issues/3992#issuecomment-640587347](here).

Let us know if you see a different issue.

**Comment by rallepalle** [comment]
I deployed Release 2.7 now. Working fine but still without logging when executing task by scheduler. 
Thank you!
