### ISSUE TITLE
[help-wanted]Any way to extract semi-structured data in spring-cloud-dataflow

### ISSUE THREAD

**Issue by gomathykailas** [spring-cloud/spring-cloud-dataflow#427]
Hi,
Is there a way to extract **semi-structured data** from a file in spring-cloud-dataflow ?

Consider an example below :

_919266728292|20.0|COREBALANCE|1&**Core**&0.0040&1&+&2&0&102&LOCAL_MINS_BALANCE&0.0000&2&+&2&0&342|70.0_

Eg: If I need to extract the value _"**Core**"_ from line above , 
then we need to do extraction as 

Extract the line using pipe symbol ( | ) ,take 4th one to get value as _1&**Core**&0.0040&1&+&2&0&102&LOCAL_MINS_BALANCE&0.0000&2&+&2&0&342_
Split above result obtained with **+** , to get value as _1&**Core**&0.0040&1&_
Split above result obtained with **&**, to get value as _**Core**_

If we can do any extractions , please suggest way of how to do extraction in this example given above.

**Comment by sabbyanandan** [comment]
Hi @gomathykailas,

- use the `file` [source application](https://github.com/spring-cloud/spring-cloud-stream-modules/tree/master/file-source) to read the file content
- use the `transform` [processor application](https://github.com/spring-cloud/spring-cloud-stream-modules/tree/master/transform-processor) and take advantage of Spring's [SpEL](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/expressions.html) support exposed via _--expression_ [property](https://github.com/spring-cloud/spring-cloud-stream-modules/blob/master/spring-cloud-stream-modules-docs/src/main/asciidoc/processors.adoc#transform-with-spel-expression). However, the best option would be to create a custom processor, so you can add unit tests to incrementally test your business logic
- alternatively, you could also accomplish the same in Groovy using `groovy-transform-processor` [processor application](https://github.com/spring-cloud/spring-cloud-stream-modules/tree/master/groovy-transform-processor)

Note: Module specific questions belong in spring-cloud/spring-cloud-stream-modules repo - please close this here.

**Comment by sabbyanandan** [comment]
Questions like this are better preferred to be discussed in stackoverflow. Please try out the suggestions listed in the previous comment.
