### ISSUE TITLE
Use correct ctr uri property 

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#4272]
`dataflow-server-default.yml` uses `spring.cloud.dataflow.task.composed-task-runner-uri` which is deprecated and new one is `spring.cloud.dataflow.task.composedtaskrunner.uri`.

**Comment by savghade** [comment]
Hi My name is Shankar  I am new contributor, can I start my first contribution by fixing this bug under your guidance.

**Comment by jvalkeal** [comment]
Sure thx, I assigned this to you.

**Comment by jvalkeal** [comment]
Just a note here where that old deprecated property is still getting used(after we stop supporting it at some point)

https://github.com/spring-cloud/spring-cloud-dataflow/blob/b8a4b04b0a6fa7bb921ba2bdf34bc8a68e3eafab/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/TaskConfigurationProperties.java#L71-L78

**Comment by savghade** [comment]
Hi 
I can see just single reference of composedTaskRunnerUri in /spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml

....
....
task:
        composed-task-runner-uri: "maven://org.springframework.cloud:spring-cloud-dataflow-composed-task-runner:@project.version@"

As per above discussion It should have as below,
....
task:
       composedtaskrunner.uri: "maven://org.springframework.cloud:spring-cloud-dataflow-composed-task-runner:@project.version@"

Please guide me,  if any another reference of this URI used in project also correct me if I am missing anything.

**Comment by jvalkeal** [comment]
Well yes, this is a simple change of that one property:
```
spring:
  cloud:
    dataflow:
      task:
        composedtaskrunner:
          uri: xxx
```
