### ISSUE TITLE
Set Rabbit and gpfdist modules

### ISSUE THREAD

**Issue by Mwea** [spring-cloud/spring-cloud-dataflow#428]
I didn't find a way to set properties ( hostname, dbUser, dbPassword) for the stream rabbit module, and the sink gpfdist modules, is there any ?

**Comment by sabbyanandan** [comment]
- all the supported application properties for `gpfdist` are listed in [`GpfdistSinkProperties`](https://github.com/spring-cloud/spring-cloud-stream-modules/blob/master/gpfdist-sink/src/main/java/org/springframework/cloud/stream/module/gpfdist/sink/GpfdistSinkProperties.java#L28). We will be adding docs for this soon via spring-cloud/spring-cloud-stream-modules#171. 

- `rabbit` docs are [here](https://github.com/spring-cloud/spring-cloud-stream-modules/blob/master/spring-cloud-stream-modules-docs/src/main/asciidoc/sources.adoc#rabbitmq). 

Note: anything module related should be discussed in: spring-cloud/spring-cloud-stream-modules repo. Please close this and open a new issue in the other repo, if you still have other questions.
