### ISSUE TITLE
Retire deprecated dataflow property metadata file names

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-dataflow#4289]
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/4053 

Code and documentation

**Comment by dturanski** [comment]
@sabbyanandan - At the standup, we confirmed the decision to not retire any previous file names since it would break user apps when they upgrade to 2.8.

**Comment by sabbyanandan** [comment]
@dturanski: The goal is to deprecate and announce it, and remove it in the next minor or later, right? Curious why it is not possible.

**Comment by dturanski** [comment]
They old file names are already deprecated since 2.6 (I think). Currently there is a log message.   Removing completely. it would mean that some users would need to change the filename in their apps or else properties completion, validation, etc. would behave differently.  We should update the reference docs though.

**Comment by sabbyanandan** [comment]
Thanks, @dturanski. Let's wrap the documentation update as part of this issue then.

**Comment by sabbyanandan** [comment]
Addressed by https://github.com/spring-cloud/spring-cloud-dataflow/pull/4321.
