### ISSUE TITLE
Add HDFS source

### ISSUE THREAD

**Issue by gomathykailas** [spring-cloud/spring-cloud-dataflow#429]
Hi,

Is there a way to provide **hadoop** as **Source** in spring-cloud-dataflow ?

I have read the documentation of spring-cloud-dataflow and found that it supports **hadoop** as **Sink**  only.
But I need to run a map-reduce job that will read data from hdfs , do aggregation and transformations upon data and finally store data to hdfs.
So , kindly provide a way to handle the above situation.

**Comment by ilayaperumalg** [comment]
Hi,

The `map-reduce` job is typically run as batch job. In spring-cloud-dataflow, you can try setting up a custom [spring-cloud-task-module] (https://github.com/spring-cloud/spring-cloud-task-modules) that runs hadoop map-reduce job.

To get an idea how this was handled in Spring XD, you can refer [here](https://github.com/spring-projects/spring-xd-samples/tree/master/batch-wordcount). The similar task module needs to be created based out of `spring-cloud-task-module`.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-app-starters#179
