### ISSUE TITLE
Spike: Explore SCGw <-> SCDF Interop

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4290]
As we continue to see requirements for request/reply-based API trigger kicking-off a data pipeline for downstream data processing, it'd be good to explore the options as to how to support the following use-cases.

- users would like to set up an API call in SCGw, which would kick-off a streaming data pipeline (in SCDF) that would publish the received data to a topic
- users would like to set up an API call in SCGw, which would kick-off a streaming data pipeline (in SCDF) that needs to do some transformation/data-munging on the received data and then publish the transformed data to a topic
- users would like to set up an API call in SCGw, which would kick-off a composed-task data pipeline in SCDF. The composed task may have to further invoke a few more APIs to aggregate and then write the aggregated data to a destination

For all the above scenarios, we would also have to return a response to the requester. 

The response can be returned either via an `http-sink` or equivalent in the context of streaming data pipeline, and perhaps a direct RESTful call from composed-task data pipeline (ie: a last step in the composed task).

Aside: There has been a lot of interest/chatter to support something similar in SCSt via https://github.com/spring-cloud/spring-cloud-stream/issues/815 — a few solutions are included in the comments, too. It'd be good to also review and consider them as part of spiking.

**Comment by chrisjs** [comment]
ive put initial findings / items to followup on into a gdoc called "SCDF-SCGw Spike"  /cc @cppwfs @sobychacko
