### ISSUE TITLE
[help-wanted] Can we provide complex aggregations to data values from file in spring-cloud-dataflow ?

### ISSUE THREAD

**Issue by gomathykailas** [spring-cloud/spring-cloud-dataflow#430]
Hi,

Can we provide **complex aggregations** to data values from file in spring-cloud-dataflow ?
Complex aggregations in the sense **"Aggregtions grouped by key"** , **"Selections grouped by key"**

Eg: 

Consider an example below of 2 sample lines having mobile-number , balance and mrp :

**_1. Aggregations grouped by key_**

_mobile-number|balance|mrp_
_919266728292|20.0|30.0
919266728292|50.0|60.0_

I need to add balance and mrp grouped by mobile-number.

So output must be 

_919266728292|70.0|90.0_ 

(Here , we have mobile-number 919266728292 having 2 balance values 20.0 and 50.0 , which needs to be aggregated as 70.0.
Similarly 919266728292 having 2 mrp values 30.0 and 60.0 , which needs to be aggregated as 90.0)

_**2. Selections grouped by key**_

_mobile-number|balance|mrp|date_
_919266728292|20.0|30.0|23/01/2016
919266728292|50.0|60.0|29/01/2016_ 

(Here, we have mobile-number 919266728292 having 2 date values ( 23/01/2016 and 29/01/2016 ).
When comparing 2 date values, we found 29/01/2016 as latest date and hence update only 2nd )

I need to get latest balance and mrp for latest date grouped by mobile-number.

So output must be

_919266728292|50.0|60.0|29/01/2016_

Can spring-cloud-dataflow handle these type of aggregations?

**Comment by sabbyanandan** [comment]
This is a duplicate from StackoverFlow.
