### ISSUE TITLE
can't use task last execution for restart task via api

### ISSUE THREAD

**Issue by ebezdomnikov** [spring-cloud/spring-cloud-dataflow#4300]
**Description:**
It's not possible use TaskExecutionResource data in order to launch task via api, because of masked credentials. 

**Release versions:**
{
  "versions": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.7.0"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.7.0"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "3.0.0"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.7.0",
      "url": "https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.7.0/spring-cloud-dataflow-shell-2.7.0.jar"
    }
  },
  "features": {
    "streams": true,
    "tasks": true,
    "schedules": true,
    "monitoringDashboardType": "GRAFANA"
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "deployerImplementationVersion": "2.6.0",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.6.0",
      "javaVersion": "11.0.8",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformSpecificInfo": {
        "default": "kubernetes"
      },
      "platformType": "Skipper Managed",
      "springBootVersion": "2.3.5.RELEASE",
      "springVersion": "5.2.10.RELEASE"
    },
    "taskLaunchers": [
      {
        "deployerImplementationVersion": "2.5.0",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.5.0",
        "javaVersion": "11.0.8",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformSpecificInfo": {
          "namespace": "default",
          "master-url": "https://10.96.0.1:443/"
        },
        "platformType": "Kubernetes",
        "springBootVersion": "2.3.5.RELEASE",
        "springVersion": "5.2.10.RELEASE"
      }
    ]
  },
  "monitoringDashboardInfo": {
    "url": "https://grafana:3000",
    "source": "default-scdf-source",
    "refreshInterval": 15
  },
  "security": {
    "isAuthentication": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  }
}

**Steps to reproduce:**
- install spring dataflow server using docs (local, k8s doesn't matter)
- add sample task application 
- create task with one application "timestamp" for instance
- launch the task, so as result you will have task exection
- get application using scale example https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/dataflow-website/recipes/scaling/scdf-alert-webhook
- add the code
`	@Bean
	public CommandLineRunner commandLineJobRunner(DataFlowOperations operations) {
    return (args) -> {
			TaskExecutionResource taskExecution = operations.taskOperations()
					.taskExecutionStatus(100L); // 100L the id of task execution, which I would like to restart via api
			operations.taskOperations().launch(
					taskExecution.getTaskName(),
					taskExecution.getDeploymentProperties(),
					taskExecution.getArguments(), null);
    };
	}
`
all attribute from taskExecution.getDeploymentProperties() or taskExecution.getArguments() where any credentials exists, will be masked, which is expected, but it would be great reuse this information as is.

Here just a request is it possible to get this information not masked, but I guess then UI will have unmasked data as well. Probably here the best option use k8s config map and don't pass any of attributes with sensitive data, but still even if I will provide on secure way, like spring.datasource.password=${environment_variable_from_k8s_secrets}, it will be masked.

Just want to ask about your opinion here.

Thank you.

**Comment by cppwfs** [comment]
Another option would be to consider using config server.  Thoughts?

**Comment by ebezdomnikov** [comment]
@cppwfs hi, 
thank you for reaching me. 

Yes, you're right, that is way to go with sensitive data:)

Thanks.
