### ISSUE TITLE
During the task launch SCDF merge all deployment properties with also deleted properties

### ISSUE THREAD

**Issue by ebezdomnikov** [spring-cloud/spring-cloud-dataflow#4305]
**Description:**
During the task launch the deployment properties can be provided, but system merge them (org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java):
```java
// Get the previous manifest
TaskManifest previousManifest = this.dataflowTaskExecutionMetadataDao.getLatestManifest(taskName);
		// Analysing task to know what to bring forward from existing
		TaskAnalysisReport report = taskAnalyzer
				.analyze(
						previousManifest != null
								? previousManifest.getTaskDeploymentRequest() != null
										? previousManifest.getTaskDeploymentRequest().getDeploymentProperties() : null
		                : null,
                DeploymentPropertiesUtils.qualifyDeployerProperties(
		                taskExecutionInformation.getTaskDeploymentProperties(),
		                taskExecutionInformation.isComposed() ? "composed-task-runner"
				                : taskExecutionInformation.getTaskDefinition().getRegisteredAppName()));
		logger.debug("Task analysis report {}", report);

		// We now have a new props and args what should really get used.
		Map<String, String> mergedTaskDeploymentProperties = report.getMergedDeploymentProperties(); <<--- 

		// Get the merged deployment properties and update the task exec. info
		taskExecutionInformation.setTaskDeploymentProperties(mergedTaskDeploymentProperties); <<---
```
The problem is what the system also merge the deleted properties:
```java
public Map<String, String> getMergedDeploymentProperties() {
		Map<String, String> props = new HashMap<>();
		props.putAll(getTaskManifestDifference().getDeploymentPropertiesDifference().getCommon());
		props.putAll(getTaskManifestDifference().getDeploymentPropertiesDifference().getAdded());
		props.putAll(getTaskManifestDifference().getDeploymentPropertiesDifference().getRemoved()); <---- here, why?
		for (Map.Entry<String, PropertyChange> entry : getTaskManifestDifference().getDeploymentPropertiesDifference()
				.getChanged().entrySet()) {
			props.put(entry.getKey(), entry.getValue().getReplaced());
		}
		return props;
	}
```
I have two questions:
- why the merge functionality was implemented on such way? Maybe just a flag on UI, aka "Default properties" make more sense.
- why removed properties also merged? as the result if I try to delete some properties in my task for the next launch they just appear again in next one and task will be launched with those deleted parameters.

I can assume it was implemented on this way to be sure what all attributes will stay forever and no one can delete it, but in case if I want to delete some properties I need
- delete task
- create task but with different(!) name (because system search by task-name)
The last part of it not very convenient from my point of view:-)  

I hope it make sense:-)
   
**Release versions:**
```json
{
  "versions": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.7.0"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.7.0"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "3.0.0"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.7.0",
      "url": "https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.7.0/spring-cloud-dataflow-shell-2.7.0.jar"
    }
  },
  "features": {
    "streams": true,
    "tasks": true,
    "schedules": true,
    "monitoringDashboardType": "GRAFANA"
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "deployerImplementationVersion": "2.6.0",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.6.0",
      "javaVersion": "11.0.8",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformSpecificInfo": {
        "default": "kubernetes"
      },
      "platformType": "Skipper Managed",
      "springBootVersion": "2.3.5.RELEASE",
      "springVersion": "5.2.10.RELEASE"
    },
    "taskLaunchers": [
      {
        "deployerImplementationVersion": "2.5.0",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.5.0",
        "javaVersion": "11.0.8",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformSpecificInfo": {
          "namespace": "default",
          "master-url": "https://10.96.0.1:443/"
        },
        "platformType": "Kubernetes",
        "springBootVersion": "2.3.5.RELEASE",
        "springVersion": "5.2.10.RELEASE"
      }
    ]
  },
  "monitoringDashboardInfo": {
    "url": "https://grafana:3000",
    "source": "default-scdf-source",
    "refreshInterval": 15
  },
  "security": {
    "isAuthentication": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  }
}
```

**Steps to reproduce:**
- create a task
- launch a task  and provide deployment parameters
- wait for execution
- launch the same task but remove all deployments parameters
- wait for execution
- try to launch the same task, you will see deleted deployment parameters.

**Comment by jvalkeal** [comment]
There is a difference between `deleted` and `removed`. We always bring everything from existing manifest as otherwise user would always need to define full set of properties. From diff point of view `removed` mean this and `deleted` means that user wants to removed it and way deletion works is that user needs to set that value effectively to null/empty.

This idea was basically copied from kubernetes/helm yml merging where empty value means user wants to remove it.

**Comment by jvalkeal** [comment]
You'll better see that logic from this test:

https://github.com/spring-cloud/spring-cloud-dataflow/blob/7e36ca0b90b4e5a2ecf788dc64adf040ad77c377/spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/diff/PropertiesDiffTests.java#L71

**Comment by ebezdomnikov** [comment]
@jvalkeal hi,
You're right, indeed in case if I will provide empty value, it will remove a property, sorry I wasn't aware about it:)
Thank you!

**Comment by jvalkeal** [comment]
Did create #4307 as I noticed that this is not clear.

**Comment by mailtoyasi** [comment]
Hi Gents,  I was also facing same issue. Thanks a lot for excellent clarification. 
Just a suggestion, will it be good if the task launch request has any overridden properties then apply otherwise take the default configuration given in SCDF service.?

**Use case:** 

- Task will be launched for N number of times. For example 1000 times,
- If one particular task run, requires more memory to survive the request then when launching the task include the 'limits.memory' property with some **large memory size** .  For example if this run comes at 100th time then subsequent run for ramining 900 task lunch, do we need to include 'limits.memory' property with **blank value**.
