### ISSUE TITLE
Add better docs task manifest handling

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#4307]
Currently our docs are unclear how various manifest operations actually work like adding/remove/deleting properties work, improve that!

**Comment by sabbyanandan** [comment]
@jvalkeal: Should this be in Microsite docs instead?

**Comment by sabbyanandan** [comment]
Close this in favor of https://github.com/spring-cloud/spring-cloud-dataflow/issues/4382.
