### ISSUE TITLE
Task status shows as "failed" when there was only one successful execution

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-dataflow#431]
I don't know why (shell bug maybe):

```
dataflow:>task list
╔═════════╤═══════════════╤═══════════╗
║Task Name│Task Definition│Task Status║
╠═════════╪═══════════════╪═══════════╣
║test     │job            │failed     ║
╚═════════╧═══════════════╧═══════════╝
```

but

```
dataflow:>task execution list 
╔═════════╤══╤════════════════════════════╤════════════════════════════╤═════════╗
║Task Name│ID│         Start Time         │          End Time          │Exit Code║
╠═════════╪══╪════════════════════════════╪════════════════════════════╪═════════╣
║test     │1 │Wed Mar 02 11:07:36 GMT 2016│Wed Mar 02 11:07:36 GMT 2016│0        ║
╚═════════╧══╧════════════════════════════╧════════════════════════════╧═════════╝
```

The logs look clean too.

**Comment by dsyer** [comment]
There was a previous failure that I couldn't explain, but that was in a different run of the server process, so maybe it saves the status in redis? The previous failure said it couldn't find an "exec" jar (I registered my own task without the "-exec" classifier). It worked when I restarted though (no idea why).

**Comment by dsyer** [comment]
I started with an empty redis and got the same sequence, so I think the exec thing is a red herring.

**Comment by cppwfs** [comment]
It is a red herring.  The current implementation for launching tasks uses the same launcher as the one used for stream apps and doesn't know how to handle an app that terminates successfully.  @jvalkeal & @markfisher are working on the spring cloud deployer that has  process deployer and task launcher.

**Comment by sabbyanandan** [comment]
@dsyer: We have a separate launcher for tasks now, so when you get a chance, please try and let us know if you're still seeing this anomaly.
