### ISSUE TITLE
Allow mulitple task execution on a transition conditional branch

### ISSUE THREAD

**Issue by nightswimmings** [spring-cloud/spring-cloud-dataflow#4327]
**Problem description:**
When defining a flow with composed task syntax, I miss a way to define the execution of 2 tasks for the same conditional branch. I could not find any alternative on different official docs

**Solution description:**
Allowing () syntax to group &&'s

**Additional context:**
Example:
  A && B 'STATUS1' -> C 'STATUS2' -> D && E && F 
If I want to execute D and D' on the STATUS2 branch, I would do something like A && B 'STATUS1' -> C 'STATUS2' -> (D && D') && E && F

**Comment by cppwfs** [comment]
You could use labels for example A && B 'STATUS1' -> C 'STATUS2' -> Label1: D && Label2: D && E && F
Here is quick read through on labels https://dataflow.spring.io/docs/feature-guides/streams/labels/#labeling-applications

**Comment by nightswimmings** [comment]
Hi Glenn! Thanks for the answer. In that very example of yours, I understand than neither status1 branch nor status2 branch is gonna execute Label2: D, is it like that? If so, then it's not my case. I picked bad naming for the tasks, D and D' are completely unrelated, they were 'D' because of the branch D

**Comment by cppwfs** [comment]
We have an existing issue for this scenario located here: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3654.   
We need to put a milestone to it.   I'll bring it up in the next standup.

**Comment by cppwfs** [comment]
You can leave additional notes on that issue.

**Comment by cppwfs** [comment]
Thanks for opening this issue.

**Comment by nightswimmings** [comment]
Exactly. That is my exact situation thanks!!
