### ISSUE TITLE
SCDF and Cloud task app execution id are different

### ISSUE THREAD

**Issue by robinsomarajv** [spring-cloud/spring-cloud-dataflow#4329]
**Description:**
Two execution id are generated one by SCDF and one by Cloud Task app even when the task is triggered manually.

The SCDF runs on AKS platform using azure sql as task repository.

**Comment by sabbyanandan** [comment]
There's not much information here to dig. 

What versions are you using? How have you provisioned SCDF on AKS? What is the task definition, and how are you launching it? If it is a reproducible case, please share the task app, as well.

**Comment by robinsomarajv** [comment]
The version of SCDF is 2.7.0 Installed from Bitnami charts repo.  
The SCDF is configured to use an external DB in AzureSQL, deployed in AzureKubernetesServices with helm just overrided the basic values in the configuration.
I have a simple Springboot application with cloud task enabled and I see  it gets invoked from SCDF and runs successfully but the tasks always has different execution id and start/end times are not synced.

Will attach a screenshot for ref.

I have ONE more IMP question if you can help pls.
How to run multiple instances of same cloud task(by using labels) with different properties/arguments in the same samSCDF task definition? Needs to run same task app with different properties on same SCDF task flow/definition. Secondly, When ran with different label the second instance fails with imagepullbackoff error with a 401 unauthorized. however first instances pulls image successfully with the same secret and runs successfully.

**Comment by robinsomarajv** [comment]
![SCDF-Debug](https://user-images.githubusercontent.com/14326222/104993009-c3123580-59e7-11eb-90b9-e2c26e379aed.jpg)

**Comment by cppwfs** [comment]
Spring Cloud DataFlow passes the `spring.cloud.task.executionid` property to the task to tell the task what execution id it should use.   If the task execution id isn't present the task wil create one for itself.    I don't see `spring.cloud.task.executionid` being passed to your task application.   Using the default entry point style of `exec` this property should appear in the arguments. 
It could be your container is not passing this property to the task application.   In that case you will probably want to change you entry point style.  More can be read here: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_entry_point_style_2

**Comment by cppwfs** [comment]
For the second question.  Please create a new issue.

**Comment by robinsomarajv** [comment]
> Spring Cloud DataFlow passes the `spring.cloud.task.executionid` property to the task to tell the task what execution id it should use. If the task execution id isn't present the task will create one for itself. I don't see `spring.cloud.task.executionid` being passed to your task application. Using the default entry point style of `exec` this property should appear in the arguments.
> It could be your container is not passing this property to the task application. In that case you will probably want to change you entry point style. More can be read here: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_entry_point_style_2

Tried giving an execution id when I launched the task from SCDF UI but did not seem to work. I am not sure if I am doing something wrong here. Attached a detailed screenshot. Can you guide me to right documentation or what i am doing wrong?
![SCDF-Debug-2](https://user-images.githubusercontent.com/14326222/105094114-648d9b80-5a69-11eb-9641-887b7ca96403.jpg)

**Comment by cppwfs** [comment]
Yeah that is my bad.  The task-execution-id is not stored in the task manifest, which is used to populate the "Applications Properties".   This is because each launch always gets a new task execution id.   You can see the task-execution-id passed in via the environment by executing the `kubectl describe pod <your task pod>`
i.e. 
```
    Environment:
...
      SPRING_CLOUD_TASK_EXECUTIONID:                         515
...
```
It looks like your container is not passing the environment or shell properties to the task.

**Comment by cppwfs** [comment]
How are you building your containers?

**Comment by robinsomarajv** [comment]
> How are you building your containers?

I use docker containers building through jenkins.

**Comment by cppwfs** [comment]
So you are providing a Dockerfile for Jenkins correct?

**Comment by robinsomarajv** [comment]
Yes, I use a basic version with just java -jar <jar>? 
![docker](https://user-images.githubusercontent.com/14326222/105567777-3377ca00-5cfa-11eb-8a7d-7f16c007d93f.jpg)
can you please help with a sample dockerfile.

**Comment by cppwfs** [comment]
You will probaby want to set the  entrypoint style propery to `shell` when launching your task.   As discussed here: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_entry_point_style_2

If that doesn't work you may want to look at how your startup.sh passes properties and arguments to your task applicaiton.

**Comment by robinsomarajv** [comment]
> You will probaby want to set the entrypoint style propery to `shell` when launching your task. As discussed here: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_entry_point_style_2
> 
> If that doesn't work you may want to look at how your startup.sh passes properties and arguments to your task application.

Thanks @cppwfs I was able to get it working changing the entrypoint style to shell and describe of POD shows the correct task_ID generated from SCDF.
