### ISSUE TITLE
Name property of `ConfigurationMetadataItem` is missing the first letter

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#433]
it looks like there might be a minor bug related to retrieving `ConfigurationMetadataItem` … when I return properties the `name` property of `ConfigurationMetadataItem` is missing the first letter. The `id` property is complete but not `name`

**Comment by ghillert** [comment]
![image](https://cloud.githubusercontent.com/assets/685363/13467789/c7639e42-e06d-11e5-8829-f73a1614a5b4.png)

**Comment by ericbottard** [comment]
Turns out this is a boot issue. see https://github.com/spring-projects/spring-boot/pull/5335
