### ISSUE TITLE
SCDF Kubernetes importing existing Kubernetes running pod

### ISSUE THREAD

**Issue by bmmule** [spring-cloud/spring-cloud-dataflow#4331]
We are working on a new deployment of SCDF in our Kubernetes environment. The new SCDF is supposed to schedule and run some Spring-batch containers.

We know that in order to do that, an application needs to be created with a path to the Docker Container, which then spins up a POD when the task is scheduled.

However, our requirement is that we need to point the application/task to an existing Kubernetes POD (containing the Spring-Batch containers).

So question is: Is this possible in SCDF? if so, how?

**Comment by sabbyanandan** [comment]
Hi, @bmmule. If the foundation for the task/batch-job isn't already established in SCDF (i.e.: a task definition in the DB), then no, any autonomous batch-job resources running in your namespace won't automatically end up being observable/manageable in SCDF.
