### ISSUE TITLE
Issue passing arguments to child tasks when launching composed tasks 

### ISSUE THREAD

**Issue by adanilev** [spring-cloud/spring-cloud-dataflow#4335]
**Description:**

* Given a composed task named `my-composed-task` with the DSL `timestamp && mytaskapp`
* Launching via the shell with this command: `task launch my-composed-task --arguments "--composed-task-arguments=--mytaskapp.some.arg=foo --composed-task-arguments=--mytaskapp.other.arg=bar --composed-task-arguments=--another.arg=baz"`
* Results in `mytaskapp` being launched with the args `some.arg`, `mytaskapp.other.arg` and `another-arg` while timestamp doesn't get any.

However, if the first argument does NOT start with the task name, then all the args are passed to all child tasks without stripping the child task's name. For example:
* `task launch my-composed-task --arguments "--composed-task-arguments=--some.arg=foo --composed-task-arguments=--mytaskapp.other.arg=bar --composed-task-arguments=--another.arg=baz"`
* Results in both child tasks being started with `some.arg`, `mytaskapp.other.arg` and `another.arg`

**Release versions:**
```json
{
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.6.0"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.6.0"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "2.5.0"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.6.0",
      "url": "https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.6.0/spring-cloud-dataflow-shell-2.6.0.jar"
    }
  },
  "featureInfo": {
    "streamsEnabled": false,
    "tasksEnabled": true,
    "schedulesEnabled": false,
    "grafanaEnabled": false
  },
  "securityInfo": {
    "isAuthenticationEnabled": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": null,
      "deployerName": null,
      "deployerSpiVersion": null,
      "javaVersion": null,
      "platformApiVersion": null,
      "platformClientVersion": null,
      "platformHostVersion": null,
      "platformType": null,
      "springBootVersion": null,
      "springVersion": null
    },
    "taskLaunchers": [
      {
        "platformSpecificInfo": {},
        "deployerImplementationVersion": "2.4.0",
        "deployerName": "LocalTaskLauncher",
        "deployerSpiVersion": "2.4.0",
        "javaVersion": "1.8.0_192",
        "platformApiVersion": "Linux 4.19.121-linuxkit",
        "platformClientVersion": "4.19.121-linuxkit",
        "platformHostVersion": "4.19.121-linuxkit",
        "platformType": "Local",
        "springBootVersion": "2.2.7.RELEASE",
        "springVersion": "5.2.6.RELEASE"
      }
    ]
  },
  "grafanaInfo": {
    "url": "",
    "token": "",
    "refreshInterval": 15
  }
}
```

**Custom apps:**
N/A

**Steps to reproduce:**
Details above. I can create a sample if required.

**Screenshots:**
N/A

**Additional context:**
I want to pass arguments to my child tasks and it took me ages of trial and error to figure it out and this issue complicated the matter. There is an example on SO [here](https://stackoverflow.com/questions/54395934/how-to-pass-arguments-to-composed-task-from-scdf-shell) which didn't work for me.

Would be great to add an example to the docs.

I'm new to Spring so there is likely some misunderstanding on my part.

**Comment by cppwfs** [comment]
Hello,
This is a known issue as discussed here: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4265.   We are in the process of updating how SCDF Composed tasks handle arguments to meet your requirements.   You can review the PR here: https://github.com/spring-cloud/spring-cloud-dataflow/pull/4314

Thanks for opening the issue.  For now I will close it and you can track its progress and make further comments on #4265.
