### ISSUE TITLE
Dates of Task Execution List are not ISO 8601

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#434]
Make sure `startTime` and  `endTime` dates are JSON serialized in ISO 8601 format. This was the case in XD and IMO is best practice to keep dates human readable.

See also: 

http://stackoverflow.com/questions/10286204/the-right-json-date-format

**Comment by cppwfs** [comment]
Verify this is still an issue.  ISO8601DateFormatWithMilliSeconds has been added to the objectMapper in the DataFlowServerConfiguration.    Via PR https://github.com/spring-cloud/spring-cloud-dataflow/pull/474

**Comment by sabbyanandan** [comment]
@ghillert: could you verify this and close the ticket, please?

**Comment by ilayaperumalg** [comment]
The task execution list now shows up start/end times in human readable format. Hence, closing this.
