### ISSUE TITLE
seccompProfile under podSecurityContext does not work

### ISSUE THREAD

**Issue by TimoSchaz** [spring-cloud/spring-cloud-dataflow#4340]
I tried to apply seccompProfile under podSecurityContext for Tasks and Streams that should be deployed via SCDF Server and Skipper ,but it seems that they are not used.
Is it possible to set the Profile there ?
I think this is an important feature that should be supportet to provide better security.

I configured it as follows but its not working:

data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    podSecurityContext:
                      seccompProfile:
                            type: Localhost
                            localhostProfile: profile.json

**Comment by ilayaperumalg** [comment]
Hi @TimoSchaz , Thanks for reporting!

Yes, `seccompProfile` is not supported and we can look at supporting in the upcoming release.
If you would like to contribute, please submit a PR and we'd happy to help you clarify any questions you may have.

I am also moving this to `spring-cloud-deployer-kubernetes` as this issue belongs there.

**Comment by ilayaperumalg** [comment]
Issue moved to [spring-cloud/spring-cloud-deployer-kubernetes #412](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/412) via [**ZenHub**](https://www.zenhub.com/)
