### ISSUE TITLE
Install SCDF toolkit on K8s using Helm v3

### ISSUE THREAD

**Issue by sunnygoel8** [spring-cloud/spring-cloud-dataflow#4345]
**Problem description:**
Unable to install SCDF on K8s using Helm v3

**Solution description:**
We're planning to install SCDF on OpenShift Container Platform soon. So wanted to know by when can we expect Helm v3 support in SCDF.

**Comment by sabbyanandan** [comment]
Hi, @sunnygoel8. Have you had a chance to review the [getting-started guide for Kubernetes](https://dataflow.spring.io/docs/installation/kubernetes/helm/)?  Our helm chart is now hosted/maintained by Bitnami, and the chart has been compatible with both Helm 2 and 3 for many months now.

If you have issues provisioning the chart on Helm 3, please open an issue against the Bitnami chart, we can have a look then.
