### ISSUE TITLE
SCDF on Kubernetes problem in Grafana dashboard

### ISSUE THREAD

**Issue by szopal** [spring-cloud/spring-cloud-dataflow#4354]
Hi, 

I have installed SCDF on GKE with CloudSQL  PostgreSQL connection. I was doing according to the instructions from https://dataflow.spring.io/docs/installation/kubernetes/kubectl/. Everything working fine without Task/Application Grafana dashboard. When I open Task or Application  dashboard I get red color pop up message:

For Task:
_Templating
Template variables could not be initialized: parse error at char 14: vector selector must contain at least one non-empty matcher_

For Application:
_Templating
Template variables could not be initialized: parse error at char 16: vector selector must contain at least one non-empty matcher

Templating
Template variables could not be initialized: parse error at char 37: vector selector must contain at least one non-empty matcher

Templating
Template variables could not be initialized: parse error at char 38: vector selector must contain at least one non-empty matcher_

When I open SCDF Server dashboard metrics are showing correctly.

**Comment by sabbyanandan** [comment]
Hi, @szopal. What version of SCDF are you using?

**Comment by szopal** [comment]
Version: 2.7.1

**Comment by sabbyanandan** [comment]
Apologies for the delayed response, @szopal. We have had a lot of optimizations in these areas in 2.7.x and the latest 2.8.2 releases. Could you please retry and report your findings?

**Comment by szopal** [comment]
Thanks for reply. I can't see 2.8.2 version - last RELEASES version I can see 2.8.1:

https://github.com/spring-cloud/spring-cloud-dataflow/releases

2.8.2 is as SNAPSHOT version.

**Comment by ilayaperumalg** [comment]
Hi, The latest release is 2.8.1. Please give it a try on that version. Thanks!

**Comment by markpollack** [comment]
Closing, seems to be ok now.  If any issues, please reopen.

**Comment by szopal** [comment]
> 2.8.1

I tried in 2.9.6 but I've got the same error.


```
Templating
Template variable service failed parse error at char 16: vector selector must contain at least one non-empty matcher

Templating [application_name]
Error updating options: parse error at char 16: vector selector must contain at least one non-empty matcher
```
