### ISSUE TITLE
(Docker-Compose) Deployed applications should be able to override the datasource configuraitons inherided from the Skipper or Dataflow servers

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow#4359]
Currently, for the local deployment, the Spring datasource configuration of thg Dataflow/Skipper server is passed to the deployed applications as part of the environment context.  

This affects only the maven/jar applications deployed in local mode.

Because the existing docker-compose configurations uses env. variables (e.g. `SPRING_DATASOURCE_URL`) instead of properties (like `--spring.datasource.url`) the deployed streaming apps are not able to configure customer per-app datasources.

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-deployer-local #202](https://github.com/spring-cloud/spring-cloud-deployer-local/issues/202) via [**ZenHub**](https://www.zenhub.com/)
