### ISSUE TITLE
ModuleController - Add option to request unprefixed properties only

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#436]
Currently a call to `/modules/{type}/{name}` may return hundreds of properties, almost none of those applicable to the module being deployed.

As a *temporary?* measure we should allow (as an option) to request unprefixed properties only.

This will make the UI more manageable for the time being.

**Comment by ghillert** [comment]
Maybe be invalid with https://github.com/spring-cloud/spring-cloud-dataflow/pull/432

**Comment by sabbyanandan** [comment]
This is a duplicate of #432, yes. This has been already addressed in the 1.0.0.RELEASE.
