### ISSUE TITLE
Dataflow-server: Ending a task flow on a certain condition results in an error on task creation

### ISSUE THREAD

**Issue by yoep** [spring-cloud/spring-cloud-dataflow#4373]
**Description:**
We're trying to create a task flow which should end when a task application ends on exit status `X`.
When adding a condition on the flow to the end, the following gets added to the task definition `'X'->$END`.
When trying to create this flow, the task definition gets rejected. 

The error message which is shown:
`The 'task:$END' application could not be found.`

**Release versions:**
2.7.0

**Custom apps:**
We use custom apps, but they're not directly related to this issue.

**Steps to reproduce:**
- Create a multi task application flow in the Dataflow Server UI
- Let one of the task application flow go to the "end" with a condition
- Try to create the task
- The following message is shown: `The 'task:$END' application could not be found.`

**Screenshots:**
![image](https://user-images.githubusercontent.com/567495/106924843-cad41880-670f-11eb-88b2-63ed4fb33572.png)

**Additional context:**
Task definition:
```
ftp-download: diverse-ftp-scheduler 'NO_FILES_FOUND'->$END && messages-messages-bulk && ftp-upload: diverse-ftp-scheduler
```

API response:
```json
{
  "_embedded": {
    "errors": [
      {
        "message": "The 'task:$END' application could not be found.",
        "logref": "NoSuchAppRegistrationException",
        "_links": {
          "self": {
            "href": "/"
          }
        }
      }
    ]
  }
}
```

**Comment by sabbyanandan** [comment]
Hi, @yoep. Thanks for the details. We will have a look.

**Comment by cppwfs** [comment]
I was able to reproduce this problem.   I've opened up the following issues to resolve this problem.
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1653
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1654
https://github.com/spring-cloud/spring-cloud-dataflow/issues/4387

Thank you for reporting.
