### ISSUE TITLE
Stayed in a running state (does not change to a completed state).

### ISSUE THREAD

**Issue by nobelbill** [spring-cloud/spring-cloud-dataflow#4379]
composite task in k8s environment"
<t1: timestamp || t2: timestamp>" never ends

Stayed in a running state (does not change to a completed state).

Log is

[main] o.s.b.c.l.support.SimpleJobLauncher: Job: [FlowJob: [name=t-main]] completed with the following parameters: [{run.id=1}] and the following status: [COMPLETED] in 10s446ms

Other logs that are normally completed are as follows.

[main] o.s.b.c.l.support.SimpleJobLauncher: Job: [FlowJob: [name=l-main]] completed with the following parameters: [{run.id=2}] and the following status: [COMPLETED] in 23s353ms
**[extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor: Shutting down ExecutorService'taskExecutor'**

i use spring-cloud-dataflow-server:2.7.1  and spring-cloud-dataflow-composed-task-runner:2.8.0-SNAPSHOT docker image.
<img width="161" alt="스크린샷 2021-02-09 오후 5 36 11" src="https://user-images.githubusercontent.com/4994989/107337176-59281000-6afd-11eb-9b39-8432d7a4265f.png">

**Comment by cppwfs** [comment]
Thank your for asking.     When using composed task splits you will need to close the spring context by adding the following property `spring.cloud.task.closecontext-enabled=true`.   You can read more about it here:  https://dataflow.spring.io/docs/feature-guides/batch/composed-task/#arguments-and-properties

**Comment by nobelbill** [comment]
@cppwfs  
Thank you!!
