### ISSUE TITLE
Shell: UX issue - standardize app type/name order

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#438]
Currently the following commands exist:

`app unregister timestamp:task`
`app info task:timestamp`

We should standardize the order of the module type/name combo.

**Comment by ericbottard** [comment]
Agreed. Note that for completion purposes, it may be better to use `<type>:<name>`

**Comment by ghillert** [comment]
+1 should be `<type>:<name>`
