### ISSUE TITLE
Update pivotal cloud services

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#4380]
Looking at versions for `io.pivotal.cfenv` and `io.pivotal.spring.cloud:spring-cloud-services-starter-config-client`. That latter is wrongly synched to central and not promoted to `libs-release-local` for versions we use.

i.e.

https://repo.maven.apache.org/maven2/io/pivotal/spring/cloud/spring-cloud-services-config-client-autoconfigure/3.1.3.RELEASE/
https://repo.spring.io/libs-milestone-local/io/pivotal/spring/cloud/spring-cloud-services-config-client-autoconfigure/

**Comment by sabbyanandan** [comment]
@jvalkeal: Is this still a problem?

**Comment by sabbyanandan** [comment]
These were updated to the latest in 2.8.x.
