### ISSUE TITLE
Debug Log level

### ISSUE THREAD

**Issue by umutcann** [spring-cloud/spring-cloud-dataflow#4393]
Hi there,

We are using 2.7.0-RC1 Spring Cloud Data Flow on kubernetes. Although we pass an argument --logging.level.org.springframework.cloud.deployer.spi.local=DEBUG to SCDF run command, We are still viewing INFO level bug.

How can we change log level to DEBUG?

Thanks.

**Comment by sabbyanandan** [comment]
Hi, @umutcann. Please use StackOverflow for questions.
