### ISSUE TITLE
Support for all deployer properties via helm templates

### ISSUE THREAD

**Issue by ashishreddyv** [spring-cloud/spring-cloud-dataflow#4402]
**Problem description:**
The SCDF helm charts skipper/configmap.yaml provides a finite set of [deployer properties](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#configuration-kubernetes-deployer) like "environmentVariables", "resources.limits", "resources.requests" etc in the helm charts, but there are other deployment properties that are not supported by the helm charts like "secretRefs", "configMapRefs" etc. SCDF helm charts should be flexible enough to accommodate any existing/future new properties to be added to skipper/server. This would help manage all global deployer properties from a single helm values file.

**Solution description:**
- A simple and elegant solution would be to just let the user define all the deployer properties in the helm values file and not hard-code them in skipper or server configmaps, giving the user flexibility to add other deployer properties if needed.

PS: I'd be more than happy to contribute to this issue if needed.

**Comment by sabbyanandan** [comment]
Hi, @ashishreddyv. The source code for the chart is in the Bitnami repo. Feel free to add the issue in the Bitnami Helm chart repo proper. It'd be great if you can contribute to the chart directly also.
