### ISSUE TITLE
Support multiple platforms via helm charts

### ISSUE THREAD

**Issue by ashishreddyv** [spring-cloud/spring-cloud-dataflow#4403]
**Problem description:**
Although SCDF server/skipper support [multi-platform deployments](https://dataflow.spring.io/docs/recipes/multi-platform-deployment/), the helm charts do not support these currently. This leaves us to duplicate the binder properties and other environment variables if we have to read these from a custom configmap.

**Solution description:**
A flexible solution would be to allow users to specify the required platforms, their namespaces and other related deployer properties per platform. This would eliminate quite a lot of duplication when adding multiple platforms.
After implementing a solution like the one proposed above, we should be able to easily specify that our scdf server/skipper can be deployed with additional platform accounts via a flag similar to the snippet below:

```
deployer:
    platforms:
      multiple: true
      accounts:
        account1:
        namespace: account1-ns
```

If the property `deployer.platforms.multiple` is set to `false`, the `default` platform account will be deployed as it is being done currently.

**Comment by sabbyanandan** [comment]
This could be another good addition to the chart proper. As highlighted at https://github.com/spring-cloud/spring-cloud-dataflow/issues/4402, feel free to open it in the right repo.
