### ISSUE TITLE
[Local mode] FileAlreadyExistsException if workingDirectoriesRoot is symbolic link

### ISSUE THREAD

**Issue by MariusKl** [spring-cloud/spring-cloud-dataflow#4404]
**Description:**
In our usecase we have a local deployment. The log folder is a symbolic link. 

`LocalTaskLauncher`s
```	
private Path createWorkingDir(Map<String, String> deploymentProperties, String taskLaunchId) throws IOException {
  LocalDeployerProperties localDeployerPropertiesToUse = bindDeploymentProperties(deploymentProperties);
  Path workingDirectoryRoot = Files.createDirectories(localDeployerPropertiesToUse.getWorkingDirectoriesRoot());
```
fails with a `java.nio.file.FileAlreadyExistsException` because it ends up in the catch of `File`s
```
try {
      createDirectory(dir, attrs);
} catch (FileAlreadyExistsException x) {
      if (!isDirectory(dir, LinkOption.NOFOLLOW_LINKS))
          throw x;
}
```
which does not follow links (for a reason I do not get)

I suggest to extend the first code example with 
```	
private Path createWorkingDir(Map<String, String> deploymentProperties, String taskLaunchId) throws IOException {
    LocalDeployerProperties localDeployerPropertiesToUse = bindDeploymentProperties(deploymentProperties);
    if (!Files.isDirectory(localDeployerPropertiesToUse.getWorkingDirectoriesRoot()) {
        Path workingDirectoryRoot = Files.createDirectories(localDeployerPropertiesToUse.getWorkingDirectoriesRoot());
    }
````
because `isDirectory()` takes symbolic links into account.

**Release versions:**
2.7.1

**Comment by sabbyanandan** [comment]
Hi, @MariusKl. It sounds like the adjustment would likely end up at the [Local-deployer](https://github.com/spring-cloud/spring-cloud-deployer-local). Feel free to propose the suggested change as a PR, we can collaborate.

**Comment by onobc** [comment]
Thanks for the contribution @ben-enfuse-io
