### ISSUE TITLE
Azure Container Registry fails with 400 Bad Request

### ISSUE THREAD

**Issue by aphethean1** [spring-cloud/spring-cloud-dataflow#4412]
**Description:**

According to the [documentation](https://dataflow.spring.io/docs/2.6.x/feature-guides/general/application-metadata/#using-metadata-container-image-labels), ```basicauth``` authorization type can be used to lookup the metadata from Azure Container Registry.

This configuration results in the following error:

```
HTTP/1.1 400 Authentication information is not given in the correct format. Check the value of Authorization header.
```

```
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>InvalidAuthenticationInfo</Code><Message>Authentication information is not given in the correct format. Check the value of Authorization header.
...
</Message></Error>
```

This problem occurs because the second request, for image blob metadata, is redirected with the http authorization headers and Azure does not expect this as described here in the FAQs:

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-faq#authentication-information-is-not-given-in-the-correct-format-on-direct-rest-api-calls

**Release versions:**
2.7.0-RC1
2.6.x
https://stackoverflow.com/questions/65238028/applicationconfigurationmetadataresolver-failed-to-retrieve-properties-for-res

```
{
  "versions": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.7.0-RC1"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.7.0-RC1"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "3.0.0-RC1"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.7.0-RC1",
      "url": "https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.7.0-RC1/spring-cloud-dataflow-shell-2.7.0-RC1.jar"
    }
  },
  "features": {
    "streams": true,
    "tasks": true,
    "schedules": false,
    "monitoringDashboardType": "NONE"
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "deployerImplementationVersion": null,
      "deployerName": null,
      "deployerSpiVersion": null,
      "javaVersion": null,
      "platformApiVersion": null,
      "platformClientVersion": null,
      "platformHostVersion": null,
      "platformSpecificInfo": {},
      "platformType": null,
      "springBootVersion": null,
      "springVersion": null
    },
    "taskLaunchers": [
      {
        "deployerImplementationVersion": "2.5.0-RC1",
        "deployerName": "LocalTaskLauncher",
        "deployerSpiVersion": "2.5.0-RC1",
        "javaVersion": "11.0.8",
        "platformApiVersion": "Linux 5.8.0-43-generic",
        "platformClientVersion": "5.8.0-43-generic",
        "platformHostVersion": "5.8.0-43-generic",
        "platformSpecificInfo": {},
        "platformType": "Local",
        "springBootVersion": "2.3.5.RELEASE",
        "springVersion": "5.2.10.RELEASE"
      }
    ]
  },
  "monitoringDashboardInfo": {
    "url": "",
    "source": "default-scdf-source",
    "refreshInterval": 15
  },
  "security": {
    "isAuthentication": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  }
}```


**Custom apps:**

Any docker based app deployed from Azure Container Registry has this issue.


**Steps to reproduce:**

1.  Deploy your task to azure container registry
2. Configure spring cloud dataflow to use that task
3. BOOM the application metadata error as reported will be seen in the log.

The configuration as follows:

```
spring.cloud.dataflow.container.registry-configurations[azurecr].registry-host={your registry}.azurecr.io
spring.cloud.dataflow.container.registry-configurations[azurecr].authorization-type=basicauth
spring.cloud.dataflow.container.registry-configurations[azurecr].user={same as your registry name}
spring.cloud.dataflow.container.registry-configurations[azurecr].secret={your secret}
```

Or  with environment variables

```
export SPRING_CLOUD_DATAFLOW_CONTAINER_REGISTRY-CONFIGURATIONS_AZURECR__REGISTRYHOST={your registry}.azurecr.io
export SPRING_CLOUD_DATAFLOW_CONTAINER_REGISTRY-CONFIGURATIONS_AZURECR__AUTHORIZATION-TYPE=basicauth
Export SPRING_CLOUD_DATAFLOW_CONTAINER_REGISTRY-CONFIGURATIONS_AZURECR__USER={same as your registry name}
export SPRING_CLOUD_DATAFLOW_CONTAINER_REGISTRY-CONFIGURATIONS_AZURECR__SECRET={your secret}
```


**Screenshots:**
None.


**Additional context:**
None.

**Comment by sabbyanandan** [comment]
@aphethean1: Apologies for the delayed response. When you get a chance, could you update to 2.7.1 and retry it on your environment? If it continues to be a problem @tzolov can collaborate with you to get this sorted out.

**Comment by aphethean1** [comment]
Retried on 2.7.1 and I can confirm it is still an issue.

```
2021-04-12 11:05:07.627  WARN 3315355 --- [nio-8080-exec-2] ApplicationConfigurationMetadataResolver : Failed to retrieve properties for resource Docker Resource [{redacted}] because of HttpClientErrorException.BadRequest: 400 Authentication information is not given in the correct format. Check the value of Authorization header.: [﻿<?xml version="1.0" encoding="utf-8"?>
<Error><Code>InvalidAuthenticationInfo</Code><Message>Authentication information is not given in the correct format. Check the value of Authorization header.
RequestId: {redacted}
Time:2021-04-12T10:05:07.5503470Z</Message></Error>]
```

In case it wasn't clear in my initial defect description.  On azure the redirect to get image metadata should not pass the Authorization header.  Azure redirects to a blob storage with the token in the url, and this Authorization header should not be passed.  The http client (RestTemplate) in ```org.springframework.cloud.dataflow.container.registry.ContainerRegistryService``` needs to be configured to not pass Authorization on redirect.

**Comment by sabbyanandan** [comment]
@tzolov: Can you have a look and share your findings?

**Comment by jvalkeal** [comment]
Finally got to try this and removing headers for redirected target gets past error mentioned in this issue. Then I'm hitting secondary issue as I still can't get metadata to work as there's an issue with double slash in a redirect.

There's a redirect starting with something like `https://eusmanaged137.blob.core.windows.net/52d5a568dbdf4a288a785d1c798d24dc-he2hkdz3v9//docker/registry/v2/blobs/sha256/....`

After this goes via apache httpclient, that double slash is replaced with single slash happening here https://github.com/apache/httpcomponents-client/blob/4.5.x/httpclient/src/main/java/org/apache/http/client/utils/URIUtils.java#L225

There's a few SO threads about this like https://stackoverflow.com/questions/12413030/how-to-prevent-apache-from-reducing-double-slashes-with-single-slash-in-a-url-pa. Not sure who to blame here as theoretically double slashes are illegal but some http clients remove it, some don't

**Comment by jvalkeal** [comment]
There was a hook to disable url normalization so I got things working. Gonna push a PR.
