### ISSUE TITLE
Seamless reusing of the k8s Docker Hub registry secrets for as SCDF metadata client credentials

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow#4428]
The `kubectl create secret docker-registry ...` command is used for creating `secrets` that via the `imagePullSecret` allow pulling images from private/protected container registries. Those secrets are used implicitly from the SCDF k8s deployers.  

In parallel, the SCDF server uses the [Docker Registry HTTP V2](https://docs.docker.com/registry/spec/api/) to interact with the Container registries and retrieve the applications metadata. To authenticate the access you can explicitly use the `spring.cloud.dataflow.container.registry-configurations.<reg-name>.xxx` properties to pass the registry credentials. 
**To prevent repetition though the SCDF allows you to reuse the same K8s `secrets` configured for image pulling**. You only need to mount the secrets to your SCDF deployment configuration: [SCDF Metadata Container Registry access](https://dataflow.spring.io/docs/installation/kubernetes/helm/#volume-mounted-secretes).

For this to work though it is required that the `docker-server`  value used by the `kubectl create secret docker-registry` matches exactly the `spring.cloud.dataflow.container.registry-configurations.<reg-name>.registry-host` property configured in SCDF metadata. This is the only way for SCDF configuration to know that given k8s secret can be used to authenticate the SCDF metadata access. 

But the `docker-server` parameter is optional. If a `kubectl create secret docker-registry` is executed without an explicit `docker-server` parameter then later will default to: `https://index.docker.io/v1/` (or in some cases to `docker.io`). This is used as a reference to the `Docker Hub` container registry. 

But neither `https://index.docker.io/v1/` nor `docker.io`  can be used to access the Docker Hub registry with the [Docker Registry HTTP V2 API](https://docs.docker.com/registry/spec/api/)! Instead the `registry-1.docker.io` entry point. 

Therefore for SCDF to be able to seamlessly reuse k8s secrets configured for accessing private Docker Hub repositories it needs to internally map the `https://index.docker.io/v1/` or `domain.io` docker-server values to `registry-1.docker.io`.

**Comment by kumarprashant2103** [comment]
Is this fix available on the latest tag. We have been seeing multiple issues to pull images from the private docker repository.

**Comment by CEDDM** [comment]
Hi @tzolov 
I'm very interested in this feature but I don't understand how to use it.
We use Harbor in our company and today I have this configuration :
```
container:
  registry-configurations:
    harbor:
      authorization-type: dockeroauth2
      registry-host: myhost
      user: myuser
      secret: myusertoken
      extra:
	registryAuthUri: https://myhost/service/token?service=harbor-registry&scope=repository:{repository}:pull
```

I already have a K8S secret 'harbor-credentials' to pull images.

What shoud I change in the configuration to use my K8S secret instead ?
Thanks for your help
