### ISSUE TITLE
Inconsistent document / settings about maximumConcurrentTasks in different platform

### ISSUE THREAD

**Issue by guoyiang** [spring-cloud/spring-cloud-dataflow#4440]
**Description:**
In spring cloud dataflow docs, there's a section about how to set maximumConcurrentTasks. I followed the doc but the customized concurrent limit doesn't apply. 

After a bit of digging, I noticed there's some misleading info for users not on CloudFoundary platform.

In this [doc](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#spring-cloud-dataflow-task-limit-concurrent-executions), it's said to use `spring.cloud.dataflow.task.platform.<platform-type>.accounts[<account-name>].deployment.maximumConcurrentTasks`

>  You can configure this limit for a platform instance by setting the corresponding deployer property, `spring.cloud.dataflow.task.platform.<platform-type>.accounts[<account-name>].deployment.maximumConcurrentTasks`, where `<account-name>` is the name of a configured platform account (`default` if no accounts are explicitly configured). The `<platform-type>` refers to one of the currently supported deployers: local, cloudfoundry, or kubernetes.

But on Kubernetes platform, the property is actually `spring.cloud.dataflow.task.platform.<platform-type>.accounts[<account-name>].maximumConcurrentTasks`. Note `deployment` key is not in the hierarchy. Kubernetes deployer properties confirms this as in this [doc](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#configuration-kubernetes-deployer).

Initially I thought it's an issue with docs, but with more investigation it seems to come from inconsistencies in configuration properties on those 3 platform:

[KubernetesPlatformProperties](https://github.com/spring-cloud/spring-cloud-dataflow/blob/cf2cd1a15fc487e0b9711f01268b81a0204714e2/spring-cloud-dataflow-platform-kubernetes/src/main/java/org/springframework/cloud/dataflow/server/config/kubernetes/KubernetesPlatformProperties.java#L28) / [KubernetesDeployerProperties](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/dfa000d73bf539ef7423ce342356c1423c4d53d3/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java#L56) doesn't have `deployment` layer.
[LocalPlatformProperties](https://github.com/spring-cloud/spring-cloud-dataflow/blob/cf2cd1a15fc487e0b9711f01268b81a0204714e2/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/features/LocalPlatformProperties.java#L26) / [LocalDeployerProperties](https://github.com/spring-cloud/spring-cloud-deployer-local/blob/11143082e0563893c1b2357ae568dac7f702ae19/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerProperties.java#L146) doesn't have `deployment` layer.
[CloudFoundryPlatformProperties](https://github.com/spring-cloud/spring-cloud-dataflow/blob/cf2cd1a15fc487e0b9711f01268b81a0204714e2/spring-cloud-dataflow-platform-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryPlatformProperties.java#L41) / [CloudFoundryDeploymentProperties](https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/blob/0a23473efe28fb432ef84fe31e6dcdaeca1c992d/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java#L198) has `deployment` layer in platform configuration.

Should the docs to be changed to make the difference clear, or should the configurations for those 3 platform be aligned?

**Release versions:**
Spring cloud dataflow 2.7.0

Thank you!

**Comment by sabbyanandan** [comment]
@dturanski: Do we have to update the docs in the ref. guide or Microsite?

**Comment by cppwfs** [comment]
Resolved with PR #4475
