### ISSUE TITLE
Move tasklauncher sink to dataflow repo

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-dataflow#4443]
**Problem description:**
Version incompatibilities are a concern with the current tasklauncher sink stream app. Releasing as part of dataflow, similar to how we do composed task runner ensures users can use the same client/server version.

**Comment by sabbyanandan** [comment]
@dturanski: Are we still targeting this in 2.8 RC1?

**Comment by dturanski** [comment]
> @dturanski: Are we still targeting this in 2.8 RC1?

@sabbyanandan - Likely will not make the deadline

**Comment by sabbyanandan** [comment]
Based on the internal sync with @dturanski and @sobychacko, here's the decision and the next steps.

1- Name the new module in SCDF repo as tasklauncher (retain taskluancher-dataflow for users who have this already in the registry and are using it)
2- Add a deprecation WARNING message to taskluancher-dataflow app, so folks know they need to switch over to the new app eventually.
3- Update taskluancher-dataflow's README with the deprecation and the steps and instructions on how to register/use the tasklauncher app shipped in SCDF.
4- In SCDF, when bulk importing, intercept the POST, see if the POST has "rabbit" or "kafka" as the string literal, and automatically register and rabbit/kafka variant of the new tasklauncher app to the registry.
5- Retain tasklauncher with the same version as SCDF's and SCDF client's version. i.e: Don't start with 1.0.

**Comment by jvalkeal** [comment]
I think we should not intercept and silently change things as that will just create new problems. User is anyway free to register using any name.

Until we somehow come up with a working concept of how a dataflow managed app would work, best we can do is to build an app and its binder flavours and images. Who owns the registration is a big question as there is no easy answer to it. Biggest benefit of building with dataflow is that api would be up-to-date but dataflow would then always need to use same version as dataflow. Problem with registration is that once you upgrade dataflow, you again have old version of an app.

**Comment by dturanski** [comment]
We're not silently changing anything, only adding an app if there is not one already. If they register something under a different name, or register a custom app with the canonical name, fine with me. Upgrading dataflow is a good point. I don't see a good way to manage that. Also, in pro, a new version notification may be an incompatible version, so...

**Comment by dturanski** [comment]
Currently, the app is named `tasklauncher` in v3, e.g., `sink.tasklauncher=docker:springcloudstream/tasklauncher-sink-kafka:3.0.2` so maybe change it to `dataflow-tasklauncher`.
