### ISSUE TITLE
Unable to bind comma separated multiple services in deployed stream apps

### ISSUE THREAD

**Issue by suresh-chidham** [spring-cloud/spring-cloud-dataflow#4444]
Hi,

We are using spring data flow server 2.4.1 version.  We tried to bind 2 services kafka and monitoring. Kafka service is binded but monitoring service is unable to bind with our deployed stream apps.  What is wrong in our data flow server configuration 
applications:
  - name: dataflow-server-sf
    memory: 4G
    disk_quota: 4G
    routes:
      - route: dataflow-server.acp..com
    path: spring-cloud-dataflow-server-2.4.1.RELEASE.jar
    buildpack: java_buildpack_offline
    health-check-type: http
    health-check-http-endpoint: /management/health
    services:
      - kafka
      - monitoring.service
    env:
      JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'
      SPRING_CLOUD_SKIPPER_CLIENT_SERVER_URI: https://skipper-server.acp.com/api
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL: https://api.system.acp.com
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG: SCDF-acceptance
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE: streams
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN: local.acp.com
      **SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_SERVICES: kafka,monitoring.service**
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME: test
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD: test
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIPSSLVALIDATION: true
      SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_ENABLERANDOMAPPNAMEPREFIX: false
      SPRING_CLOUD_DATAFLOW_FEATURES_ANALYTICS_ENABLED: false
      STREAM_SPRING_CLOUD_STREAM_OVERRIDECLOUDCONNECTORS: true
      SPRING_MVC_ASYNC_REQUESTTIMEOUT: 120000

**Comment by jvalkeal** [comment]
`spring.cloud.deployer.cloudfroundry.stream-services` is a very old option and was used when we have dedicated servers for each platform. It's `spring.cloud.deployer.cloudfroundry.services` in a deployer now.

Other thing is that setting should be in a skipper server and more preferred way is to define those with platform configuration(as you can have multiple ones).

**Comment by suresh-chidham** [comment]
Thanks.
After adding below line in skipper-server. Its reflecting in all deployed stream apps.
SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[dev]_DEPLOYMENT_SERVICES=kafka,monitoring.service
