### ISSUE TITLE
Keycloak RBAC

### ISSUE THREAD

**Issue by nicholasmhughes** [spring-cloud/spring-cloud-dataflow#4449]
I don't see a way to accomplish RBAC using Keycloak and Spring Cloud Data Flow 2.7.1

I (more or less) followed the instructions found here:

https://github.com/jvalkeal/randomstuff/tree/master/dataflow-keycloak

This does result in a deployment which prompts for user login with Keycloak. However, I cannot tell how to assign different roles to different users. Every user that logs in via Keycloak is assigned the scopes of the client.

Any help is aprpeciated.

**Comment by sabbyanandan** [comment]
Hi, @nicholasmhughes. We don't have in-depth knowledge of Keycloak. Though, that is one of the identity providers that we see many in the community using it, however. If Keycloak has the concept of groups, you should be able to mount users to those groups and have that group assigned to the desired role (eg: `ROLE_VIEW`)

**Comment by nicholasmhughes** [comment]
Thanks for the response @sabbyanandan 

Keycloak definitely has the concept of groups, but I'm not sure how to configure the group mapping in spring cloud data flow. All of the examples show a mapping of _scopes_ to SCDF roles. How can I map to groups in the token?

**Comment by nicholasmhughes** [comment]
Thank you @sabbyanandan . That link pointed me at a missing step from the other repo I was using. I was able to get Keycloak working properly, and documented my steps and configuration [here](https://eitr.tech/blog/2021/04/12/keycloak-oauth-for-spring-cloud-dataflow.html). I appreciate the help!

**Comment by sabbyanandan** [comment]
💥 ; really nicely done, @nicholasmhughes! Glad you have got that up and running. I will have someone in the team add your [detailed write-up](https://eitr.tech/blog/2021/04/12/keycloak-oauth-for-spring-cloud-dataflow.html) to the SCDF Microsite's [blog section](https://dataflow.spring.io/news/). 

cc: @ilayaperumalg @oodamien @jvalkeal
