### ISSUE TITLE
Add support of the parameter `propertiesFile` to the scdf shell `task schedule create` 

### ISSUE THREAD

**Issue by nithril** [spring-cloud/spring-cloud-dataflow#4471]
SCDF shell currently only support the parameters `properties`. Unlike `stream deploy` it is not currently possible to schedule a task by using a file as a properties

**Comment by nithril** [comment]
I will try to submit a PR. Adding the parameter seems straightforward

**Comment by sabbyanandan** [comment]
Hi, @nithril. That sounds like a reasonable enhancement to the scheduling workflow. Please feel free to take a stab at it and submit a PR; once we have this supported in the API/Shell, we can also extend it to the UI.
