### ISSUE TITLE
Python with rabbitmq as stream processor

### ISSUE THREAD

**Issue by Sharukdeen-SA** [spring-cloud/spring-cloud-dataflow#4474]
Hello all, I'm trying to implement a python polyglot sample using rabbitmq as queue binder instead of Kafka. But my application is always in deploying state, kindly share implementation or sample of python as stream processor using rabbitmq. Kindly help me in solving this issue.

**Comment by sabbyanandan** [comment]
Hi, @Sharukdeen-SA. Please post questions like this in StackOverflow. GitHub issues are preferred for bug-reports or feature enhancements.
