### ISSUE TITLE
Not able to deploy stream

### ISSUE THREAD

**Issue by rhishirajnema** [spring-cloud/spring-cloud-dataflow#4481]
**Description:**
I have a stream with source as : custom-source-app and sink as custom-sink-app.
This is the error while deploying stream: (Note: it doesn't happen always)

**App with deploymentId [source-app] is already deployed with state [deployed]**

However the state of stream is undeployed in dashboard:
<img width="1211" alt="Screen Shot 2021-04-20 at 7 12 16 PM" src="https://user-images.githubusercontent.com/1910845/115475003-b7afef80-a20c-11eb-8b5b-8a95ccc0be21.png">

It looks like that source was deployed but due to some reasons sink was not deployed but the stream is not in partial or deployed status. When I manually try to undeploy is stream it is successful but when I try to deploy it again it throws above error.

**Release versions:**
`
{
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-starter-dataflow-server",
      "version": "2.2.1.RELEASE"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.2.1.RELEASE"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "2.2.2.RELEASE"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.2.1.RELEASE",
      "url": "https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/2.2.1.RELEASE/spring-cloud-dataflow-shell-2.2.1.RELEASE.jar"
    }
  },
  "featureInfo": {
    "streamsEnabled": true,
    "tasksEnabled": true,
    "schedulesEnabled": true,
    "grafanaEnabled": false
  },
  "securityInfo": {
    "isAuthenticationEnabled": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "2.1.2.RELEASE",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.1.2.RELEASE",
      "javaVersion": "11.0.10",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformType": "Skipper Managed",
      "springBootVersion": "2.1.6.RELEASE",
      "springVersion": "5.1.8.RELEASE"
    },
    "taskLaunchers": [
      {
        "platformSpecificInfo": {},
        "deployerImplementationVersion": "2.0.5.RELEASE",
        "deployerName": "LocalTaskLauncher",
        "deployerSpiVersion": "2.0.4.RELEASE",
        "javaVersion": "11.0.10",
        "platformApiVersion": "Linux 4.14.225-121.362.amzn1.x86_64",
        "platformClientVersion": "4.14.225-121.362.amzn1.x86_64",
        "platformHostVersion": "4.14.225-121.362.amzn1.x86_64",
        "platformType": "Local",
        "springBootVersion": "2.1.6.RELEASE",
        "springVersion": "5.1.8.RELEASE"
      }
    ]
  },
  "grafanaInfo": {
    "url": "",
    "token": "",
    "refreshInterval": 15
  }
}
`
**Custom apps:**
We have custom apps but the problem is not with app as 98% of times it works. Also, we are running two containers for dataflow and the stream was deployed properly in one but not in other.

**Steps to reproduce:**
- Deploy stream - fails with error
- Undeploy stream - deploy again - fail with same error
Error Message = [App with deploymentId [stream.transporter-source-v1] is already deployed with state [deployed]]"

**Comment by sabbyanandan** [comment]
Hi, @rhishirajnema. Seeing `Error Message = [App with deploymentId [stream.transporter-source-v1] is already deployed with state [deployed]]"` tells me that you're either restarting SCDF or Skipper independently and are **not** using a persistent RDBMS. 

By default, in SCDF/Skipper, an H2 DB instance is auto-started for quick sandbox/dev experimentation, and you cannot rely on that setup for production deployments.

If you have a more detailed use-case description, stack trace(s) of SCDF/Skipper/Apps, and a sample app, please open a StackOverflow post.
