### ISSUE TITLE
Docker network deployment property appears to not work

### ISSUE THREAD

**Issue by kristopax** [spring-cloud/spring-cloud-dataflow#4491]
**Description:**
spring.cloud.deployer.local.docker.network property (in the Deployment properties for platform page in the SCDF dashboard) does not seem to work.  The default value is "bridge"; however, when I change the value to "host", it appears that when SCDF launches the docker container (for my processor app within my stream application), the docker command that executes specifies the network to be bridge (i.e. "docker run --network bridge --rm -e ...").  I expected this deployer property to change the value used to set the docker --network parameter.  Is this a bug, or am I not understanding what this property does?

**Release versions:**
SCDF server 2.7.1 (running natively via jar file)
spring cloud skipper server 2.6.1 (running natively via jar file)

**Comment by sabbyanandan** [comment]
Hi, @kristopax. Please post questions on StackOverflow; one of the team members will respond. We use GH for bugs and feature requests.
