### ISSUE TITLE
SCDF UI - getting error 500 at the UI when trying to open Tasks definition window (related to Issue #4358)

### ISSUE THREAD

**Issue by shalomyasap** [spring-cloud/spring-cloud-dataflow#4505]
Hello,

We are getting error 500 when trying to open the UI at task definitions window.
This error raise when task attribute value containing a pipe character - " | ".
The task defines successfully via REST API with all attributes and their values, including quotes, e.g. /tasks/definitions/TASK_NAME --data-urlencode "definition=--param-name='abcd|efg'"

This issue solved backed than at master release (I verified it a ~2 month ago) but seems to reproduce again now **with new scdf version 2.7.2.** .
Please see details at https://github.com/spring-cloud/spring-cloud-dataflow/issues/4358

Best regards,
Shalom

**Comment by jvalkeal** [comment]
Those commits ^^^ are referencing wrong issue.

**Comment by cppwfs** [comment]
Yeah this issue #4358 should have been marked for backport to the 2.7.x branch.   It will be available for the 2.8.x. release.   I will add backport to labels

**Comment by cppwfs** [comment]
Backported to 2.7.x branch.   will be available in 2.8.x and 2.7.3.   Sorry for the inconvenience.
