### ISSUE TITLE
Wrong status for started steps, if the pod is deleted while batch is running

### ISSUE THREAD

**Issue by canerkoseren** [spring-cloud/spring-cloud-dataflow#4511]
**Description:**
If the pod is deleted while batch is running, the task status changes to 'Completed' even though the steps are started.

**Release versions:**
spring-cloud-data-flow:    2.8.0-SNAPSHOT
spring-cloud-starter-task:  2.2.2.RELEASE
spring-boot-starter-batch: 2.1.6.RELEASE

**Screenshots:**
![shot](https://user-images.githubusercontent.com/4264155/117636160-369fa480-b189-11eb-8ff4-03dbd9664c3d.png)

**Comment by canerkoseren** [comment]
Hi all,

I got the same result when I set `spring.cloud.task.batch.failOnJobFailure=true`

**Comment by cppwfs** [comment]
Hello @canerkoseren ,
When you kill a pod it sends a SIGTERM to the application.    The default behavior of a task/boot app is to terminate with a zero exit code as discussed here: https://docs.spring.io/spring-cloud-task/docs/current/reference/html/#features-lifecycle-exit-codes.
Here is a blog written by Mahmoud on how to handle this scenario: https://spring.io/blog/2021/01/27/spring-batch-on-kubernetes-efficient-batch-processing-at-scale
