### ISSUE TITLE
SCDF Tasks NPE when launching on Cloud Foundry if previous task_executions have not been populated

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#4516]
When SCDF launches tasks on CF it checks to see if the task is executing before launching.
It does this by looking for task executions that are running from the task_execution table.
From that it obtains the external_execution_id.    It then uses this external_execution_id to determine if the task is still running CF.
The issue is that if the task_execution has been created by SCDF but the task did not launch, and thus leaving a stubbed entry for that task definition in the task execution table.   Such that when the task is relaunched it will retrieve this stub entry and will pass the `null` external_execution_id to CF.  
https://github.com/spring-cloud/spring-cloud-dataflow/blob/fd381d8d340aaf62ecf539f05797d8a2b5b4a903/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java#L509-L534
Specifically Line 525.

The resolution is to check for a null external_execution_id.  If so, throw IllegalStateException.

**Comment by sabbyanandan** [comment]
@cppwfs: Another item seems like a duplicate of to a whole bunch of new exception handling and validation that we pushed in 2.8.x. Do we still need this?

**Comment by cppwfs** [comment]
Yes it was handled here: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4587
