### ISSUE TITLE
Local admin server fails to deploy under Windows 7 - java.io.tmpDir wrong

### ISSUE THREAD

**Issue by styjdt** [spring-cloud/spring-cloud-dataflow#453]
Hi,

I was trying to get quick start example for Spring Cloud Dataflow running on local admin server under Windows 7.

I've followed the steps here: http://cloud.spring.io/spring-cloud-dataflow/ to start the local implementation of the server. Then I tried to create the "ticktock" stream:

dataflow:>stream create ticktock --definition "time | log" --deploy

Finally I end up in the status "failed" for the stream. Following the runtime modules into the temp folder and checking the logs there I can see, that both modules ticktock-time and ticktock-log are trying to start, but fail finally. In the logs we find:

Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to create tempDir. java.io.tmpdir is set to C:\WINDOWS\

which eventually is caused by

Caused by: java.io.IOException: Zugriff verweigert
at java.io.WinNTFileSystem.createFileExclusively(Native Method) ~[na:1.8.0_71]

So it seems that the temp folder is set to a path where java has no access to.

I already set the _JAVA_OPTIONS environment variable to force each newly started JVM to pick up java.io.tmpdir pointing to standard user temp folder. But still this behaviour. Probably the deploy tooling in the local server manipulates the java.io.tmpdir property in some mystic way.

Am I missing some configuration step in between?

Btw. I'm running also into issue  #421, which is eventually caused by this issue here. This can be verified by checking the logs of the module which is tried to be started during the tests.

Alexander

**Comment by styjdt** [comment]
I spent the complete day to figure out, where the wrong temp folder comes from.
Finally I found it in `org.springframework.cloud.dataflow.deployer.local.OutOfProcessModuleDeployer.deploy(..)`
Here in Line 127 a `ProcessBuilder `is created. One line later the standard environment variables are retrieved from the system by the call of `environment()`, but immediately thrown away by the call of `clear()`.
This way each hint how to set the temp folder to a reasonable path is gone and the JVM has to choose the best of it's knowledge which on Windows obviously defaults to C:\Windows.
When commenting out the `clear()` call, everything works as expected.

Now you guys can figure out, if throwing away the default environment variables was by intention and if so, if perhaps keeping some basic environment variables like "TMP" or similar makes sense...

Hoping for a fix in the near future...
Alexander

**Comment by ericbottard** [comment]
Hey Alexander,

indeed throwing the environment was intentional (we don't want to inherit some boot configuration that pertains to the server for example) but obviously that has unforeseen consequences. I think the best solution is to selectively carry over some of the properties, `java.io.tmpDir` being one of them

**Comment by styjdt** [comment]
Unfortunately java.io.tmpdir is a system property for java and not an environment variable. But probably that is derived from some environment variable, so you probably won't find java.io.tmpdir directly.
Just checked the environment variables which are available just before the call of `clear()` and which are likely to be used to construct java.io.tmpdir:
TEMP - pointing directly to my user temp folder
TMP - the same
other environment variables which are candidates, because pointing somehow to user folder:
LOCALAPPDATA - points to parent folder of user temp folder
APPDATA - some sibling folder to the former one
HOME, HOMEPATH, USERNAME - all self explanatory

Hope that helps.

**Comment by ericbottard** [comment]
Alexander,

Thanks again for your report and analysis. We'll consider all of those.

**Comment by styjdt** [comment]
I can confirm that this issue is solved.
Tried on the last master, everything works as expected, even on the "somewhat special" Windows :smiley: 
Probably due to #459 ?
