### ISSUE TITLE
kubectl script server-rolebinding uses v1beta1 which is no longer supported in v22

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#4535]
In v17 v1beta1 was deprecated.    In v22+ it is no longer supported.   We need to update to v1.   
https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/src/kubernetes/server/server-rolebinding.yaml#L2

**Comment by mwiede** [comment]
I am on v1.25 and the dashboard shows errors like 

`Failure executing: GET at: https://100.64.0.1/apis/batch/v1beta1/namespaces/abc/cronjobs. Message: the server could not find the requested resource`

I am using helm chart 15.0.5

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125

**Comment by mwiede** [comment]
@satyajitbaral no did not solve it. Thanks for opening a Ticket
