### ISSUE TITLE
Typo in Scheduler configuration YAML sample

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4540]
Under the scheduler config section, the `manifest.yaml` points to:

> SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[default]_SCHEDULER_SCHEDULER_URL: https://scheduler.local.pcfdev.io

... SCHEDULER 2x.

**Comment by jvalkeal** [comment]
Well, it's actually correct per `scheduler.scheduler-url`.
