### ISSUE TITLE
Destroying tasks on TAS leaves the droplet around, causing Task CD conflicts

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4548]
Steps to reproduce:
1- Schedule to launch `timestamp` every 1 minute (task name = `foo`).
2- Launches working great.
3- `cf apps` shows the task droplet.
4- Destroy task definition in SCDF (task destroy ..).
5- Definition in SCDF is gone; the schedule is also deleted. However, the cf apps still show the OLD droplet - why?

---

6- Now, register a new version of the `timestamp` and make that the new default version in the app registry.
7- Create a new definition with the same name as the previous (ie: `foo`).
8- Schedule the launch of this new definition again.
9- Notice that the OLD droplet is reused as opposed to a NEW droplet with the latest version of the `timestamp.

Also, based on the quick digging, we see this in the logs: https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/spring-cloud-dataf[…]loud/dataflow/server/service/impl/DefaultTaskDeleteService.java

Maybe a scheduled launch (external launch) will not create “task deployment” entry in SCDF’s DB, and hence it goes to the else block? That’s why the definition and schedule get deleted, but the droplet actually remains?

**Comment by sabbyanandan** [comment]
The destroy function doesn't take the platform account into account also. The following method in its entirety needs to be reviewed.

https://github.com/spring-cloud/spring-cloud-dataflow/blob/6b84e5e8dd0ce0c2e90ac98c32fc0c0f1f7883b6/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskDeleteService.java#L389-L404

**Comment by sabbyanandan** [comment]
@jvalkeal @ilayaperumalg: if we can find a way to get this in 2.8.0, it'd be great. Otherwise, we can continue to keep it in 2.8.1.

**Comment by cppwfs** [comment]
This will be resolved with #4574 .   It is left present because no deployment record was created, so DataFlow had no knowledge of the deployment.   In short, with the merge of this  PR, dataflow searches all platforms for that artifact and deletes it up on task definition deletion. 
Kubernetes on the other hand deletes the pods when the cronjob is deleted.

**Comment by sabbyanandan** [comment]
Awesome!

**Comment by cppwfs** [comment]
Now for note.  Deleting a schedule will not delete the droplet.   Only the deletion of definition.
