### ISSUE TITLE
2.7 -> 2.8 properties not can not be added to migrated ctr task

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#4553]
Follow instructions enumerated in this doc for creating test case in 2.7->2.8:
https://docs.google.com/document/d/1SQh9gm1GjMVdewDaY5D21ytMmS8QWQXxmMZ49jAMAQM
Launch ctr1 and ctr2 and update one of the changed properties and verify they are launched properly.
I was able to change properties that existed from the first ctr launch.   But when I tried to add a property to the second app in ctr1 it didn’t work.

**Comment by sabbyanandan** [comment]
@cppwfs: This is addressed in the recent fix from @jvalkeal, perhaps?

**Comment by cppwfs** [comment]
Retested against latest fix.   LGTM.
