### ISSUE TITLE
SCDF-SCSt-Kafka - Scaling doesn't increase/create the kafka partitions hence idle consumers

### ISSUE THREAD

**Issue by pari205** [spring-cloud/spring-cloud-dataflow#4560]
I am referring the solution provided here...https://dataflow.spring.io/docs/recipes/scaling/autoscaling/

We used SCALE API to increase the number of instances of a customer ( Processor App), however the number of partitions remains unchanged even if the number of instances is more than the currently available partitions. I have even tried removing PartitionKeyExpression from producer.

Could you help us in understanding what I am missing here to achieve auto Add Partitions based on the consumer load? Why kafka binder is not creating the partitions?

Just to add, I am able to create partitions manually directly in kafka, so not an issue on the kafka configuration side

The issue which i am facing exactly from this issue:
https://github.com/spring-cloud/spring-cloud-dataflow/issues/3706

**Comment by sabbyanandan** [comment]
It is a common practice to over-partition the Kafka topics, so any downstream scale-out requirements can participate and take advantage of the extra partitions. Just by invoking the scaling-API in SCDF, you cannot expect the Kafka partitions to also increase/decrease. That's outside the scope of this operation in SCDF.

For questions like this, please use StackOverflow going forward.

**Comment by pari205** [comment]
Thanks for the quick explanation Sabby Anandan. We can assume to go with over partitions for scaling options.

However I have few clarifications based on the documentation and SCDF support in creating kafka partitions.

1) As per the below documentation, can we assume that below scenario of adding new partitions only works during deployment stage in SCDF? 

https://dataflow.spring.io/docs/recipes/scaling/autoscaling
"The producer.partitionKeyExpression=payload property configures time’s output binding for partitioning. The partition key expression uses the message payload (e.g. the toString() value of the current timestamp) to compute how the data needs to be partitioned to the downstream output channels. **The spring.cloud.stream.kafka.binder.autoAddPartitions deployment property instructs the Kafka binder to create new partitions when required.** This is required if the topic is not already over-partitioned. The spring.cloud.stream.kafka.binder.minPartitionCount property sets the minimum number of partitions that the Kafka binder configures on the topic, which is where the transform-processor is subscribing for new data."

2) As you have clearly called out the steps in other issue ( link given below #3706) ,SCDF does create new topics/partitions based on those parameters during deployment but not during scaling. Since SCDF internally invokes SCSt, how is it working in case of first scenario with only SCSt but not with SCDF. Shouldn't be consistent in both the cases as you have called out. Please clarify.

https://github.com/spring-cloud/spring-cloud-dataflow/issues/3706

3) With respect to scaling of stream apps in SCDF, are there any mechanism to increase the number of instances based on the Kafka topic messages(or any messaging framework) counts? It would be really helpful to have this feature within SCDF if possible?

Thanks
