### ISSUE TITLE
Batch and CTR apps fail when launched en-masse.

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#4562]
Batch and CTR (based on batch) will fail when launched en-masse. 
This is caused by a database deadlock on the batch sequence tables i.e. `BATCH_JOB_SEQ` etc.
This will require an update to SCDF DDL and migration scripts after the bug is resolved in Spring Batch.   
The batch issue is enumerated here: https://github.com/spring-projects/spring-batch/issues/3927

**Comment by sabbyanandan** [comment]
Depends on #4567.
