### ISSUE TITLE
Re-registering apps skips the default version assignment

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4569]
As a user, I unregistered all the apps from the registry, and after re-bulk importing the apps, I don't see the automatic "default" version assignment. Now, the apps without the "default" version assignment, I am unable to create streams.

Creating `foo = time | log` from the dashboard fails with the following error.

> : Caught exception while handling a request: Application name 'time' with type 'source' does not exist in the app registry.
   2021-06-08T10:04:37.03-0700 [APP/PROC/WEB/0] OUT Application name 'log' with type 'sink' does not exist in the app registry.

Version:
SCDF 1.3 PRO SNAP (2.8 SNAP)

Platform:
TAS

**Comment by ilayaperumalg** [comment]
@sabbyanandan At the time of bulk import we assign the default version for the app. The default version wouldn't be assigned only when the app got a different default version associated with it at the time re-importing the app which is likely the case in this issue (I could repeat the issue only this way).  Do you remember unregistering the default versions of the app after the re-import? This way, there won't be default versions at all. 

Let's discuss to see if you have any other flow which could help repeat this issue.

**Comment by sabbyanandan** [comment]
@ilayaperumalg: Some details here: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1745#issuecomment-857828521.

**Comment by jvalkeal** [comment]
I don't see this happening. If you unregister all apps, then re-register will add default version as it would be a first one. Most likely you didn't unregister all apps as I think we only add it as default app if it's first one.
