### ISSUE TITLE
SCDF Shell does not allow backslash character '\'

### ISSUE THREAD

**Issue by styjdt** [spring-cloud/spring-cloud-dataflow#457]
For whatever reason I cannot enter backslash character in the shell. Pressing the backslash key is a no-op, also pasting some text containing backslashes into the shell ends up in all backslashes being discarded.
This way I've no way to define some properties in a definition as e.g. here: http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#_create_a_task_definition.

My operating system is Windows 7.

**Comment by Nyamiou** [comment]
I can confirm, this is a big problem because then it's impossible to set properties such as regexes. Also something strange happens with the characters '[' which disappear, this character is needed when you want to set a list.

**Comment by ericbottard** [comment]
@Nyamiou Are you on Windows as well?

This works without issues on Mac OS for example (and I assume on *nix as well), as demonstrated for example using the Spring Cloud Data Flow shell, which is based on Spring Shell.
Could you try using cygwin?

```
dataflow:>stream create foo --definition "time --regex=\.[A-Z] | log"
Created new stream 'foo'
dataflow:>stream list
╔═══════════╤══════════════════════════╤══════════╗
║Stream Name│    Stream Definition     │  Status  ║
╠═══════════╪══════════════════════════╪══════════╣
║foo        │time --regex=\.[A-Z] | log│undeployed║
╚═══════════╧══════════════════════════╧══════════╝
```

**Comment by Nyamiou** [comment]
@ericbottard Yes I'm on Windows (not by choice). 

With Babun it was not responding (don't know why) and so I used the Windows prompt but as you recommended I installed standard cygwin and it's working and I don't have the problems anymore. Thanks.

**Comment by sabbyanandan** [comment]
Thanks for confirming, @Nyamiou.
