### ISSUE TITLE
AzureAD OAuth not working on Cloud Foundry

### ISSUE THREAD

**Issue by tommparekh** [spring-cloud/spring-cloud-dataflow#4572]
Hi,
I have deployed SCDF on Cloud Foundry (Open Source implementation). I got my dataflow server dashboard setup as a client application in Azure AD and got client secret and other required end points. When I am trying to setup data flow server with Azure AD OAuth configuration per below link, I am seeing my application not starting in CF.

https://github.com/spring-cloud/spring-cloud-dataflow/blob/b6d094924d86fff3530cf83aefe6530f8ce10a55/spring-cloud-dataflow-docs/src/main/asciidoc/appendix-identity-provider-azure.adoc

My goal is to authenticate (& authorize) enterprise users while accessing data flow dashboard to ensure only authorized users can access dashboard functionalities.

Here is my application.properties for data flow server:

```
info:
  app:
    name: "spring-cloud-dataflow-server"
    description: "Spring Cloud Data Flow Server"
    version: "2.7.1"
server:
#  port: 8443
  ssl:
    enabled: true
    key-alias: dataflow.company.net
    key-store: /home/vcap/app/BOOT-INF/classes/dataflow-keystore.jks
    key-store-type: jks
    key-store-password: test
    key-password: test
    trust-store: /home/vcap/app/BOOT-INF/classes/dataflow-keystore.jks                 
    trust-store-password: test
# Security (Oauth 2):

spring:
  cloud:
    dataflow:
      security:
        authorization:
          provider-role-mappings:
            dataflow-server:
              map-oauth-scopes: true
              role-mappings:
                ROLE_VIEW: dataflow.view
                ROLE_CREATE: dataflow.create
                ROLE_MANAGE: dataflow.manage
                ROLE_DEPLOY: dataflow.deploy
                ROLE_DESTROY: dataflow.destroy
                ROLE_MODIFY: dataflow.modify
                ROLE_SCHEDULE: dataflow.schedule
  security:
    oauth2:
      client:
        registration:
          dataflow-server:
            provider: azure
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'  # (should this be this exact URL or not?)
            client-id: 49266f4f-7sdfd-4977-95sfdsf-fdsfd77f43
            client-secret: sdf23gq3~02K-fdg3-x-PWn
#            authorization-grant-type: authorization_code
            scope:
            - openid
            - profile
            - email
            - offline_access
            - api://dataflow-server/dataflow.view
            - api://dataflow-server/dataflow.deploy
            - api://dataflow-server/dataflow.destroy
            - api://dataflow-server/dataflow.manage
            - api://dataflow-server/dataflow.modify
            - api://dataflow-server/dataflow.schedule
            - api://dataflow-server/dataflow.create
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/jfiee84k-ereer-4f65-bretet2d-ertertw/v2.0
            user-name-attribute: name
      resourceserver:
        jwt:
          jwk-set-uri: https://azuread-proxy.company.com/jfiee84k-ereer-4f65-bretet2d-ertertw/discovery/v2.0/keys
```
      

Any help is appreciated.

**Comment by sabbyanandan** [comment]
@tommparekh: Any reason why you're not using the SCDF tile? The Tile internally integrates with UAA/SSO, so they have a cleaner integration with Azure AD, perhaps, and it is automated as opposed to manual configuration.

**Comment by tommparekh** [comment]
@sabbyanandan SCDF tile is not available in open source cloud foundry implementation at my site.

**Comment by sabbyanandan** [comment]
Okay, it is hard to tell what is missing, the version in use, or the errors you're getting. If you have a reproducible case with errors/logs, and the exact `manifest.yml` files in use, we can review it. Otherwise, we will be assuming too much.

**Comment by tommparekh** [comment]
I am able to setup OAuth on CF now. We can close this issue. Thank you for your support.

As a solution, I am using OAuth setup from Spring security module.
