### ISSUE TITLE
Task cleanup should clean slate any and all footprint in TAS

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4574]
> By design the task destroy expects the task deployment entry to be available for the associated task launch. The task deployment entry would only be created if the task is launched with the associated platform resources and in this case, the entry for the task deployment is missing. 

The log:

```
“TaskLauncher.destroy not invoked for task bmytask. Did not find a previously launched task to destroy”
```

> suggests that the corresponding task deployment wasn’t created because of the failed task launch much before in the lifecycle. But, when the same task is tried to be destroyed it expects the task deployment to exist to cleanup the associated task launch resources. 

In conclusion, a task "cleanup" should clean things up entirely, and not leave any residue behind regardless of whether a task was launches previously successfully or not.

Maybe relates to https://github.com/spring-cloud/spring-cloud-dataflow/issues/4548.

**Comment by cppwfs** [comment]
We have two options here:
1) If we get an exception from CF deployer on a failed launch, we can then attempt a delete of the application.    
2) When deleting a task definition, we check if there is a deployment.  If so, we delete the the application from just that platform (It should be only on one platform) .    If there is no deployment record then we check all platforms for the application.  If present then delete.

**Comment by ilayaperumalg** [comment]
> We have two options here:
> 
> 1. If we get an exception from CF deployer on a failed launch, we can then attempt a delete of the application.
> 2. When deleting a task definition, we check if there is a deployment.  If so, we delete the the application from just that platform (It should be only on one platform) .    If there is no deployment record then we check all platforms for the application.  If present then delete.

I vote for option (2) as it gives the users a chance to see what went wrong with the failed deployment etc.,
