### ISSUE TITLE
Remove graph property from available CTR property list on task exec page

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#4582]
![image](https://user-images.githubusercontent.com/695673/120370887-217ae900-c2e3-11eb-81e2-aa247108ef2c.png)

As shown above user can update the graph that is launched via this property.   This property should not be displayed, as this is handled by the SCDF definition itself.

**Comment by jvalkeal** [comment]
Two options:

1. Move away from automatic metadata generation and craft those files manually by taking existing generated files as base and then remove options which we don't want to expose. Boot annotation processor was never designed for cases where we have options, which are there, but are "transitive", in terms of what's gets shown in UI.

2. Separate `ComposedTaskProperties` into public and internal classes and then filter based on those as we expose options via controller.

As a side note, we can also clean ctr pom and remove `spring-cloud-dataflow-apps-metadata-plugin` and `properties-maven-plugin` as those really were used when image were build via maven(we use pack now).

**Comment by jvalkeal** [comment]
Option 3, try to see if our extension for app metadata "visible" options can be used for this.
