### ISSUE TITLE
K8s data pipeline using the geode starter required an undocumented property

### ISSUE THREAD

**Issue by wlund-pivotal** [spring-cloud/spring-cloud-dataflow#4596]
**Description:**
I was unable to get a simple data pipeline http | geode to work without adding a custom geode property.  My platform is minikube.

**Release versions:**
Version is 2.7.2

**Custom apps:**
If your Stream or Task data pipeline includes custom apps and there is a problem associated with it, please share the sample-app (add a link to the GitHub repo) and the release versions in use. Also, please be sure to share the register, create, and deploy/launch DSL commands for completeness.

**Steps to reproduce:**

The example was taken from [Http to Gemfire Demo](https://docs.spring.io/spring-cloud-dataflow-samples/docs/current/reference/htmlsingle/#_http_to_gemfire_demo).  I ran the app using the list of properties provided by stream app stocks info and added --host-addresses in the creation of the steam because the app was not connecting to the service. 
`stream create --name stocks --definition "http --port=8080 | geode stream create --name stocks --definition "http --port=8080 | geode  --host-addresses=gemfire-cluster-locator:10334 --json=true --regionName=Stocks --keyExpression=payload.getField('symbol') **--spring.data.gemfire.pool.locators=gemfire-cluster-locator[10334]"** --deploy --json=true --regionName=Stocks --keyExpression=payload.getField('symbol')\ --deploy`

This didn't work so we added a geode specific property as listed below:

stream create --name stocks --definition "http --port=8080 | geode  --host-addresses=gemfire-cluster-locator:10334 --json=true --regionName=Stocks --keyExpression=payload.getField('symbol') **--spring.data.gemfire.pool.locators=gemfire-cluster-locator[10334]"** --deploy

**Screenshots:**

**Additional context:**
It might just be an update to the app-starter docs but would probably be exposed as an app-starter property through something like "gemfire-pool-locators".

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/stream-applications #176](https://github.com/spring-cloud/stream-applications/issues/176) via [**ZenHub**](https://www.zenhub.com/)
