### ISSUE TITLE
Create CI plans for 2.8.x

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#4604]
This will include the 2.8.x GH repo along with the IT CI plans as well.

**Comment by tzolov** [comment]
- Add  new [Spring Cloud Data Flow - 2.8.x ITs plan](https://build.spring.io/browse/SCD-SCDF2I28X) buy setting the Git repository branch to `2.8.x` and relaying on the [DATAFLOW_VERSION](https://github.com/spring-cloud/spring-cloud-dataflow/blob/19e8d3467d76867ee310fb52a7408fc8f185779a/src/docker-compose/docker-compose.yml#L57) and [SKIPPER_VERSION](https://github.com/spring-cloud/spring-cloud-dataflow/blob/19e8d3467d76867ee310fb52a7408fc8f185779a/src/docker-compose/docker-compose.yml#L110) as generated by the [template](https://github.com/spring-cloud/spring-cloud-dataflow/blob/2.8.x/src/templates/docker-compose/docker-compose.yml)
- Update the [Spring Cloud Data Flow - Main ITs plan](https://build.spring.io/browse/SCD-BMASTERITS). Remove the explicit `DATAFLOW_VERSION` and `SKIPPER_VERSION` environment variables and use the values generated by the template. 
- Update the [Spring Cloud Data Flow - Main Backward Compatibility ITs](https://build.spring.io/browse/SCD-SCDFMBCI). Remove the explicit `DATAFLOW_VERSION` and `SKIPPER_VERSION` environment variables and use the values generated by the template.
