### ISSUE TITLE
Read environment variables of initContainer from configmap !

### ISSUE THREAD

**Issue by umutcann** [spring-cloud/spring-cloud-dataflow#4606]
Hi,

We need to set environment variables of initContainer from configmap.

As far as I investigate the implementation of initContainer Environment variable, It is expecting like ['KEY1=VAL1', 'KEY2=VAL2'].

I tried like below. But It does not work.

{name: 'KEY, valueFrom: {configMapKeyRef: {key: 'value', name: 'configmapname'}}}

Do you have any workaround solution?

Or do you have any plan for this feature?

Thanks.

**Comment by sabbyanandan** [comment]
If this is an enhancement, we will have to explore in k8s-deployer, and not in SCDF itself.

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-deployer-kubernetes #455](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/455) via [**ZenHub**](https://www.zenhub.com/)
