### ISSUE TITLE
Field-value-counters not working?

### ISSUE THREAD

**Issue by styjdt** [spring-cloud/spring-cloud-dataflow#462]
Hi,
I wanted to play with field-value-counter sink. Unfortunately I cannot see any created field-value-counter.
I've tried with local dataflow server from current master (under Windows) and created a stream

    stream create test --definition "http | field-value-counter --field-name=bla --name=mycounter" --deploy

Then I'd expect when posting some JSON content to http module should somehow affect the field value counter. E.g. JSON snippets like this: `{"bli":"bla", "bla":"blubber"}` or that `{bla: "test"}`

But checking from the shell shows that no field-value-counters are available:

    dataflow:>field-value-counter list
    ╔════════════════════════╗
    ║Field Value Counter name║
    ╚════════════════════════╝

I've tried with a normal `counter` to check, if I'm doing anything wrong, but that seems to work (of course with `counter` commands instead of `field-value-counter` here...
I've also checked the admin ui and respective output of the rest call. There is no field-value-counter available.

Am I doing anything wrong?

Additionally: What I wanted to check in the first place is the possibility of processing POJOs as mentioned in the documentation of field-value-counter: http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#spring-cloud-stream-modules-field-value-counter. Because I've tested a custom POJO with log sink and got an error about "could not deserialize, class not found...", which is of course true: the standard log sink does not know about my custom class. So I wonder how field-value-counter could process such stuff?
Unfortunately I cannot work with that module as described.

**Comment by ilayaperumalg** [comment]
Hi,

Is this on the latest master of `spring-cloud-stream-modules` (that uses `redis` store by default) ? if not, you need to use `--store` option that uses `redis` as the repository.

**Comment by ilayaperumalg** [comment]
For the message type conversion, you need to specify the option `--inputType` for the FVC app with the value `application/x-java-object;type=my.package.myPOJO`.

For example,
```
stream create test --definition "http | field-value-counter --field-name=bla --name=mycounter --store=redis --inputType='application/x-java-object;type=my.package.myPOJO'" --deploy
```

**Comment by styjdt** [comment]
Hi, thanks, the `--store` option I didn't try, because it is mentioned in the documentation only for the `counter` module and not for the `field-value-counter`. Of course it is obvious :smiley: 
Perhaps the documentation should be updated here?

Regarding the message type conversion: I've tried your suggestion with the `--inputType`. But as expected, also here finally one ends up in ClassNotFoundException. In my test I used a custom http source module which emits a custom POJO.
[stdout_0.log.txt](https://github.com/spring-cloud/spring-cloud-dataflow/files/182413/stdout_0.log.txt)

The question here is obviously: How to tell the `field-value-counter` where to find my POJO class? My custom source module knows it, but should it "expose" such types somehow to the dataflow server? Because otherwise I cannot imagine how a standard module like `log` or `field-value-counter` can access objects of custom type?

**Comment by styjdt** [comment]
Just found #166. Is this such a thing we would need here?
I've tried, but `--includes` seems not to be supported at the `stream create` command...

**Comment by sabbyanandan** [comment]
Hi, @styjdt: We recently addressed the default option for `--store` as `redis` via spring-cloud/spring-cloud-stream-modules#214. There's a gap with docs, yes - we will address it [spring-cloud/spring-cloud-stream-modules#237]. Here's an [example](https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/analytics/twitter-analytics) of FVC for your reference. 

For the type-conversion question, could you please create a separate issue and update with sample (custom) code and stream definition? 

Thanks.
