### ISSUE TITLE
SCDF OAuth2 Integration- Unable to Access resources after integration

### ISSUE THREAD

**Issue by Gayathri-91** [spring-cloud/spring-cloud-dataflow#4632]
I am able to integrate SCDF with OAuth2 and authenticate the user successfully when they try to access SCDF dashboard. I am using my own custom provider for this. When I try to access any other resources say scale api provided by SCDF from postman or backend, I get 401 unauthorized error.  The dataflow server throws the following error 

org.springframework.security.authentication.ProviderNotFoundException: No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:227) 

I got access token from OAuth server and used it as bearer token while doing the scale api call.

**Comment by Gayathri-91** [comment]
Could anyone please take a look and respond . We are blocked by this issue.

**Comment by jvalkeal** [comment]
You'd need to show your configuration and tell more about your identity provider.

**Comment by Gayathri-91** [comment]
@jvalkeal 
I am using Spring OAuth2 and below is my yaml contents
debug: true
server:
  port: 8075
spring:
  cloud:
    dataflow:
      security:
        authorization:
         provider-role-mappings:
          okta:
           map-oauth-scopes: false
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: clientid
            client-secret: clientsecret
            redirect-uri: http://ip:port/login/oauth2/code/okta
            authorization-grant-type: authorization_code
            provider: okta
            scope: access,openid
        provider:
          okta:
            token-uri: https://dev-xxx.okta.com/oauth2/default/v1/token
            authorization-uri: https://dev-xxx.okta.com/oauth2/default/v1/authorize
            user-info-uri: https://dev-xxx.okta.com/oauth2/default/v1/userinfo
            user-name-attribute: name
      authorization:
            check-token-access: isAuthenticated()

**Comment by jvalkeal** [comment]
Could you look if one of my keycloak testing samples gives you a working config for your env https://github.com/jvalkeal/randomstuff/tree/master/dataflow-keycloak-basic

**Comment by markpollack** [comment]
closing for lack of feedback.
