### ISSUE TITLE
'count' property is ignored for modules

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-dataflow#464]
Trying to deploy something like:

    stream create ticktock --definition "time | log"

    stream deploy ticktock --properties module.log.count=2

Does not result in multiple instances (on local), e.g.

```
2016-03-22 03:58:16.621  INFO 4335 --- [nio-9393-exec-3] o.s.c.d.spi.local.LocalAppDeployer       : deploying app ticktock.log instance 0
   Logs will be in /var/folders/cl/hcgfw4bn35d9p9y8r7v2v9bc0000gn/T/spring-cloud-dataflow-7877035418133898245/ticktock-1458633410430/ticktock.log
2016-03-22 03:58:16.627  INFO 4335 --- [nio-9393-exec-3] o.s.c.d.spi.local.LocalAppDeployer       : deploying app ticktock.time instance 0
   Logs will be in /var/folders/cl/hcgfw4bn35d9p9y8r7v2v9bc0000gn/T/spring-cloud-dataflow-7877035418133898245/ticktock-1458633410430/ticktock.time
````

**Comment by ilayaperumalg** [comment]
It looks like the deployment property key `count` needs to be mapped to the Spring Cloud Deployer's count [key] ( https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/app/AppDeployer.java#L37)  `spring.cloud.deployer.count` as the Add deployer expects that key [here] (https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployer.java#L137).

**Comment by styjdt** [comment]
True, just tested with

    stream create ticktock --definition "time --spring.cloud.deployer.count=2 | log --spring.cloud.deployer.count=3" --deploy

which works perfectly fine.
Alexander

**Comment by ilayaperumalg** [comment]
It is tricky that the LocalAppDeployer expects the property `spring.cloud.deployer.count` as an app definition property while we want to support `count` as a app deployment property.

Since the AppDefinition is updated with unmodifiable map of app parameters, it might be better to fix this in the LocalAppDeployer that can expect the property `spring.cloud.deployer.count` from the environment (which can be set via deployment property).
