### ISSUE TITLE
Outdated documentation on how to use the SCDF shell

### ISSUE THREAD

**Issue by hpoettker** [spring-cloud/spring-cloud-dataflow#4647]
In version 2.8.1, the documentation on how to use the SCDF shell in the docker compose setup for the local machine is not correct: https://dataflow.spring.io/docs/installation/local/docker/#using-the-shell

Executing the given command yields:
```
$ docker exec -it dataflow-server java -jar shell.jar
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "java": executable file not found in $PATH: unknown
```

As the error message indicates, no JRE is on the `$PATH`. More severely, there seems to be no `shell.jar` or `spring-cloud-dataflow-shell.jar` contained in the docker container since the image is being built with paketo.

**Comment by sabbyanandan** [comment]
Hi, thanks for reporting. I will close this, and let's continue the dialog on the Microsite issue.
