### ISSUE TITLE
Issue with configuring split sizing for composed task runner

### ISSUE THREAD

**Issue by RaickyDerwent** [spring-cloud/spring-cloud-dataflow#4648]
**Description:**
Issues trying to configure split sizing for Composed Task RUnner

**Release versions:**
SCDF - 2.8.1
Composed Task runner - 2.8.1

**Additional context:**
I have about 16 tasks configured in parallel like <AAA && BBB|| CCC && DDD || EEE && FFF || GGG && ......>.

My intention is to only have 3 tasks running at one time. I don't mind which tasks run first as long as the order of the sequential tasks are maintanined (BBB is always run after AAA, DDD after CCC etc.)

As per the documentation here - https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_configuration_options, I tried setting `--split-thread-core-pool-size=3`, but it gave me this error - 

`Split thread core pool size 3 should be equal or greater than the depth of split flows 17. Try setting the composed task property splitThreadCorePoolSize`

What do I do here ?

**Comment by RaickyDerwent** [comment]
Any updates on this ? 

The behavior I'm seeing is directly contradictory to what's defined here :

`. So, for example, a definition such as <AAA || BBB || CCC> && <DDD || EEE> would require a split-thread-core-pool-size of 3. This is because the largest split contains three child tasks. A count of 2 would mean that AAA and BBB would run in parallel, but CCC would wait until either AAA or BBB finish in order to run. Then DDD and EEE would run in parallel.`

**Comment by cppwfs** [comment]
Hello @RaickyDerwent.  Sorry for the delay in the response.    In this case we need to update the documentation to state that the thread-pool size must be 1 greater than the larges split.  This is to support nested splits.   https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/33

**Comment by RaickyDerwent** [comment]
Thanks for the response @cppwfs! 

I was able to find the root of the issue with the help of this answer - https://stackoverflow.com/a/68657559/2427453

**Comment by RaickyDerwent** [comment]
@s
