### ISSUE TITLE
Spring Cloud Task - DS

### ISSUE THREAD

**Issue by kitkars** [spring-cloud/spring-cloud-dataflow#4657]
Hi Guys,

I am trying to understand the design decision behind every Spring Cloud Task should have same the datasource properties as SCDF. 

As SCDF is a framework why does it expect the **_task_** to point to the same DS. Can SCDF NOT log the details on behalf of Task? 

If I have 10 different tasks for different purposes, should each task implementation include the same DS dependency?

**Comment by jvalkeal** [comment]
This is mostly because scdf can be used to view task information from a DB and generally handles and manages tasks lifecycle, somebody needs to own those tables needed by Spring Cloud Task. If you have custom tasks, yes those should be able to connect to a same DB where scdf created task tables.

**Comment by kitkars** [comment]
_(I might have a completely wrong understanding of this SCDF usage. Please feel free to close this in that case. I do NOT want to waste your valuable time. I thought Spring simplifies everything except this SCDF)_

Basically I relate the SCDF with Kubernetes Job Controller.

If SCDF manages task life cycle (something like k8s job), then it should just log the information itself. It does not need to pass the DS information to the task and expect the task to have the dependency.

I would like to keep the individual tasks just to focus on the business functionality. SCDF can log the information of when it starts, when it ends. The tasks themselves do not need SCDF DS information. They might want to talk to their own DB for doing the task. Otherwise we need to handle 2 different DS in the individual tasks.

**Comment by edudar** [comment]
@kitkars this datasource dependency comes from `Spring Cloud Task` project. In its point of view, tasks can be created once and then run on whatever runtime you want (like AWS Lambda) so you provide those datasource properties where it stores its state essentially. Although I do think that SCDF could simplify that for its users and provide implicit datasource configured at the server level by wrapping up user's tasks or something similar maybe. After all, SCDF tasks do run in the context of SCDF as a platform.

**Comment by cppwfs** [comment]
@edudar could you create an issue with your suggestion .   Thank you!
