### ISSUE TITLE
Kafka source?

### ISSUE THREAD

**Issue by spoon99** [spring-cloud/spring-cloud-dataflow#4663]
Hi, I'm new to SCDF and playing with it a little bit.
I found that I can't find kafka source or sink.  I want consume from external (outside of SCDF) kafka and produce to external kafka.

I already saw this question (https://stackoverflow.com/questions/38548384/kafka-source-in-spring-cloud-data-flow) but I think it is useful only inside of SCDF.

Is there any reason that kafka source/sink is missing? (I can see source/sink for rabbit)

**Comment by sabbyanandan** [comment]
Hi, @spoon99. Please understand that SCDF _does not_ use/rely on Kafka internally. It is the applications that are deployed by SCDF that use/rely on Kafka-like messaging systems at runtime for pub/sub-style communication.  

For Kafka as a source, you can follow [this post](https://stackoverflow.com/questions/38548384/kafka-source-in-spring-cloud-data-flow/38553043#38553043) for steps. AFA SCDF is configured to point to the external Kafka cluster, when using the [named-destination](https://dataflow.spring.io/docs/feature-guides/streams/named-destinations/) feature in SCDF, at runtime, the inbound or the outbound position destinations are piped-in and out respectively from that Kafka cluster.
