### ISSUE TITLE
Custom composed-task-runner

### ISSUE THREAD

**Issue by pfilaretov** [spring-cloud/spring-cloud-dataflow#4667]
Hello,
I'm new to SCDF and I'm looking for a way to use a custom Composed Task Runner (CTR). I found the [documentation](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_launching_a_composed_task_by_using_a_custom_composed_task_runner) says

> In some cases, you need to launch a composed task by using a custom version of a composed task runner other than the default application that is shipped out-of-the-box. To do this, you need to register the custom version of the composed task runner and then specify the composedTaskRunnerName property to point to the custom application at task launch

However, when I try to launch my composed task with `composedTaskRunnerName` property, I get an error:

```
dataflow:>task launch --name MyTask --composedTaskRunnerName my-composed-task-runner
Option 'composedTaskRunnerName' is not available for this command. Use tab assist or the "help" command to see the legal options
```

I had a look at the code and found the following [feature request](https://github.com/spring-cloud/spring-cloud-dataflow/issues/2290) that was resolved by [that commit](https://github.com/spring-cloud/spring-cloud-dataflow/commit/80562b90a11c73e9a4686904f9c4d2b0ae5906ad). However, some time later in [another commit](https://github.com/spring-cloud/spring-cloud-dataflow/commit/7c14121ccc2040bb4bf0eacdba232ce352b1ffd9) this functionality was removed, e.g. see `TaskExecutionController.launch()` method.

So could someone please give me an idea why it was removed? And is it possible to bring it back?

**Additional context:**
The original problem I'm trying to solve with custom CTR is as follows. I want to run a pipeline of tasks and I want each task NOT to start automatically one after another. So, here is an example flow I want:
1. Create composed task which consists of three tasks: `task-a && task-b && task-c`
2. Start composed task
3. No tasks have started at this point yet, i.e. pipeline is paused. 
4. Once I'm ready to run my first task, I send REST call (or message) to CTR to trigger the first task
5. `task-a` is executed and the pipeline is paused again
6. Once I'm ready to run the second task, I send another REST call (or message) to CTR to trigger the task
7. `task-b` is executed and the pipeline is paused again
8. Once I'm ready to run the third task, I send another REST call (or message) to CTR to trigger the task
9. `task-c` is executed and the pipeline is finished

So, maybe there is a better way to achieve this, without a custom CTR? I just haven't found it yet.

**Comment by cppwfs** [comment]
You can specify your own composed task runner by setting the `spring.cloud.dataflow.task.composedtaskrunner.uri` to uri of your composed task runner.   Thus dataflow will call your instance instead of the default.   More can be read [here](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_configuring_the_composed_task_runner_2).

This section was to be removed when that feature was removed.   I've created an issue to discuss this: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4690
