### ISSUE TITLE
MongoDB Source || Query || Not executing new Date() constructor or the ISODate() function

### ISSUE THREAD

**Issue by MathanmohanT** [spring-cloud/spring-cloud-dataflow#4672]
**Description:**
MongoDB Source (3.0.2) Query is not executing new Date() constructor or the ISODate() function

**Release versions:**
3.0.2

**Steps to reproduce:**

**Stream Info:**

Stream 1:
mongodb --query={createdOn : { $gte : new Date(ISODate().getTime() - 1000 * 60 * 62), $lt : new Date(ISODate().getTime() - 1000 * 60 * 2)}} 
--collection=vendor_attribute --spring.data.mongodb.database=sourcedb --spring.data.mongodb.host=localhost --spring.data.mongodb.port=27017 | log

**Error:**
Caused by: org.bson.json.JsonParseException: JSON reader expected an integer or a string but found 'ISODate'.

Hence, I have also tried with the other two below options:

Stream 2:
mongodb --query={createdOn : { $gte : new Date('ISODate().getTime() - 1000 * 60 * 62'), $lt : new Date('ISODate().getTime() - 1000 * 60 * 2')}}
--collection=vendor_attribute --spring.data.mongodb.database=sourcedb --spring.data.mongodb.host=localhost --spring.data.mongodb.port=27017 | log

**Error**
Caused by: org.bson.json.JsonParseException: JSON reader expected a date in 'EEE MMM dd yyyy HH:mm:ss z' format but found 'ISODate().getTime() - 1000 * 60 * 182'.

Stream 3:
mongodb --query={createdOn : { $gte : 'new Date(ISODate().getTime() - 1000 * 60 * 62)', $lt : 'new Date(ISODate().getTime() - 1000 * 60 * 2)'}}
--collection=vendor_attribute --spring.data.mongodb.database=sourcedb --spring.data.mongodb.host=localhost --spring.data.mongodb.port=27017 | log

**No Errors also no results for the above stream**

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/stream-applications #189](https://github.com/spring-cloud/stream-applications/issues/189) via [**ZenHub**](https://www.zenhub.com/)
