### ISSUE TITLE
Allow RestTemplate configure with DataFlowClientAutoConfiguration

### ISSUE THREAD

**Issue by nightswimmings** [spring-cloud/spring-cloud-dataflow#4682]
Ideally logic should be extracted into public methods that accept a restTemplate

At least make the dependencies autowired by constructor or @Bean method arguments so we can compose the behavior from outside.

Or a setter for restTemplate

**Comment by nightswimmings** [comment]
FYI https://github.com/spring-projects/spring-boot/issues/27991

**Comment by jvalkeal** [comment]
It would not be a bad idea to do an attempt to hook into boot's `RestTemplateBuilderConfigurer` and `RestTemplateBuilder` allowing easier way to add additional ways to configure things.

**Comment by nightswimmings** [comment]
Mmh I think the cleanest way would be either autoinjecting resttemplatebuilder and build a resttemplate that is managed privately within the domain, or in case you want it configurable by the user, create a wrapper bean as explained in the comment of the link I attached.  But what is critical for me, and the most objectively thing to correct, IMO,  is that the dependency should be passed by constructor for proper composition
