### ISSUE TITLE
Dataflow Server returns error on /management/prometheus

### ISSUE THREAD

**Issue by reisners** [spring-cloud/spring-cloud-dataflow#4689]
**Description:**
A GET request to /management/prometheus endpoint (when enabled) results in the following response:
```
{
  "_embedded": {
    "errors": [
      {
        "message": "No converter for [class java.lang.String] with preset Content-Type 'null'",
        "logref": "HttpMessageNotWritableException",
        "_links": {
          "self": {
            "href": "/"
          }
        }
      }
    ]
  }
}
```
On the console the following exception is logged:
```
org.springframework.http.converter.HttpMessageNotWritableException: No converter for [class java.lang.String] with preset Content-Type 'null'
    at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:312)
    at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:181)
    at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78)
    at org.springframework.hateoas.server.mvc.RepresentationModelProcessorHandlerMethodReturnValueHandler.handleReturnValue(RepresentationModelProcessorHandlerMethodReturnValueHandler.java:108)
    at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:124)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
...

```

**Release versions:**
```
{
   "featureInfo": {
      "analyticsEnabled": true,
      "streamsEnabled": true,
      "tasksEnabled": true,
      "schedulesEnabled": false,
      "monitoringDashboardType": "NONE"
   },
   "versionInfo": {
      "implementation": {
         "name": "spring-cloud-dataflow-server",
         "version": "2.7.0"
      },
      "core": {
         "name": "Spring Cloud Data Flow Core",
         "version": "2.7.0"
      },
      "dashboard": {
         "name": "Spring Cloud Dataflow UI",
         "version": "3.0.0"
      },
      "shell": {
         "name": "Spring Cloud Data Flow Shell",
         "version": "2.7.0",
         "url": "https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.7.0/spring-cloud-dataflow-shell-2.7.0.jar"
      }
   },
   "securityInfo": {
      "authenticationEnabled": false,
      "authenticated": false,
      "username": null,
      "roles": []
   },
   "runtimeEnvironment": {
      "appDeployer": {
         "deployerImplementationVersion": "2.6.0",
         "deployerName": "Spring Cloud Skipper Server",
         "deployerSpiVersion": "2.6.0",
         "javaVersion": "1.8.0_222",
         "platformApiVersion": "",
         "platformClientVersion": "",
         "platformHostVersion": "",
         "platformSpecificInfo": {
            "common-live": "cloudfoundry",
            "common-dev": "cloudfoundry"
         },
         "platformType": "Skipper Managed",
         "springBootVersion": "2.3.5.RELEASE",
         "springVersion": "5.2.10.RELEASE"
      },
      "taskLaunchers": [
         {
            "deployerImplementationVersion": "2.5.0",
            "deployerName": "CloudFoundryAppDeployer",
            "deployerSpiVersion": "2.5.0",
            "javaVersion": "1.8.0_222",
            "platformApiVersion": "2.167.0",
            "platformClientVersion": "unknown",
            "platformHostVersion": "unknown",
            "platformSpecificInfo": {
               "Space": "common-dev",
               "API Endpoint": "https://api.snpaas.eu",
               "Organization": "database-research-group"
            },
            "platformType": "Cloud Foundry",
            "springBootVersion": "2.3.5.RELEASE",
            "springVersion": "5.2.10.RELEASE"
         },
         {
            "deployerImplementationVersion": "2.5.0",
            "deployerName": "CloudFoundryAppDeployer",
            "deployerSpiVersion": "2.5.0",
            "javaVersion": "1.8.0_222",
            "platformApiVersion": "2.167.0",
            "platformClientVersion": "unknown",
            "platformHostVersion": "unknown",
            "platformSpecificInfo": {
               "Space": "common-live",
               "API Endpoint": "https://api.snpaas.eu",
               "Organization": "database-research-group"
            },
            "platformType": "Cloud Foundry",
            "springBootVersion": "2.3.5.RELEASE",
            "springVersion": "5.2.10.RELEASE"
         }
      ]
   },
   "monitoringDashboardInfo": {
      "url": "",
      "refreshInterval": 15,
      "dashboardType": "NONE",
      "source": "default-scdf-source"
   },
   "_links": {
      "self": {
         "href": "https://dataflow-server.bypass.springernature.app/about"
      }
   }
}
(I've checked that the behavior is the same in release 2.8.1 as well)
```

**Steps to reproduce:**
I've enabled export of actuator metrics in prometheus format by setting these properties:
```
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
```

**Additional context:**
I was able to track this down to this bean factory being present in Dataflow Server's `WebConfiguration`:
```
    @Bean
    public HttpMessageConverters messageConverters(ObjectMapper objectMapper) {
        return new HttpMessageConverters(
                // Prevent default converters
                false,
                Arrays.<HttpMessageConverter<?>>asList(new MappingJackson2HttpMessageConverter(objectMapper),
                        new ResourceHttpMessageConverter()));
    }
```
which prevents a `StringHttpMessageConverter` from being available.
When I add an instance of `StringHttpMessageConverter` to the list that is passed to the `HttpMessageConverters` constructor in the bean factory above, the error goes away. I've checked a few of the server's REST endpoints and did not notice any errors.

**Comment by tzolov** [comment]
Hi @reisners, 
Thank you for catching this issue! The problem points to the WebConfiguration indeed and should be trivial to fix. 

But I would like to point out that **we strongly advise against using the Prometheus pull model** the way you have approached it above! The [Prometheus RSocket Proxy](https://github.com/micrometer-metrics/prometheus-rsocket-proxy) should be used instead! 

The DataFlow and Skipper servers as well as all (60+) OOTB streaming apps are provisioned with prometheus-rsocket-proxy support that can be enabled declaratively: https://dataflow.spring.io/docs/installation/kubernetes/kubectl/#enable-monitoring

- Using the Prometheus RSocket Proxy allows to unify the Prometheus metrics management for servers, streaming pipelines and batch/task pipelines (note that task are long-living jobs and the Prometheus pull model will not work without a proxy) using the same configuration and infrastructure. 
- Another important point is that the prometheus-rsocket-proxy resolves an important security issue. You don't have to open the access to your server (e.g. /management/prometheus) as now the server pushes (over rsocket) its metrics to the proxy. 
- For some cloud platforms such as Cloud Foundry you can not configure Prometheus to scrap directly the apps /management/prometheus but have to deploy a [Promregator](https://github.com/promregator/promregator) in between. Again the rsocket-proxy fixes this.
- For some dynamic applications (like the tasks or streaming apps) that scrap the randomly coming and going apps you have to implement and run your own Prometheus service discovery service such as [file_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config). With the rsocket-proxy this is not necessary anymore.
- and last but not least you can scale the prometheus-rsocket-proxy instance independently from the apps form which the metrics originate. 
- ...

This diagram illustrates the rsocke-proxy approach (the dataflow and skipper server can be configured to use exactly the same entry point as the streaming and task apps):
<img width="941" alt="scdf-pometheus-monitoring" src="https://user-images.githubusercontent.com/1351573/134342434-7c8bead8-ae6a-453b-9413-2b7266c8b543.png">

Some documentation links:

* https://dataflow.spring.io/docs/feature-guides/general/server-monitoring/
* https://dataflow.spring.io/docs/feature-guides/streams/monitoring/

**Comment by reisners** [comment]
Hi @tzolov, many thanks for looking into this and for your advice. I was aware of the rsocket-proxy but discounted it because the push architecture does not seem to support the monitoring of apps (how does Prometheus know that an app has crashed if that app has not explicitly been registered with it to begin with?). On the other hand the CloudFoundry infrastructure that my company operates provides integration of apps with Prometheus via a CF service that apps can bind to when they are deployed. This way even streams and other apps (we don't use it for tasks though) can automatically register themselves with Prometheus and are subsequently monitored throughout their lifetime.

**Comment by tzolov** [comment]
> the push architecture does not seem to support the monitoring of apps (how does Prometheus know that an app has crashed if that app has not explicitly been registered with it to begin with?)

I don't completely understand the this statement but I tend to disagree with the bits it I get.

IMO, it is the opposite! With the pull model if an application start and complete (common for many task/batch apps) **before** the Prometheus had scraped its metrics, how would Prometheus know that this application had ever done anything or show any metrics for it? Even if the application doesn't disappear before the Prometheus scraped some metrics, how would you get the metrics produced by the app between it exit and the next scrape pull.  
The proxy provides [short-lived or serverless applications support]( 
https://github.com/micrometer-metrics/prometheus-rsocket-proxy#support-for-short-lived-or-serverless-applications) to handle those cases. And it does it better than the faulty Prometheus Pushgateway (mind that the rsocket proxy keeps a bidirectional persistent connection with every application). 

The proxy itself exposes separate scrape entry point to report its own metrics. Among those metrics one can monitor how many (and witch applications) were registered with the proxy. So if a known app (like SCDF server) didn't register with the proxy, then this behavior can be treated as if Prometheus failed to pull/scrape metrics from it? 

The prometheus/rproxy configuration, we advise and support,  offers monitoring not only static servers (e.g. skipper and dataflow) but also all streaming and task applications deployed by them. We provide OOTB Grafana and Wavefront dashboards.... 

Anyway, it is your call at the end of the day! Just wanted to make sure you are aware of the tradeoffs ;) Good luck!
