### ISSUE TITLE
How to support different binder than Redis?

### ISSUE THREAD

**Issue by styjdt** [spring-cloud/spring-cloud-dataflow#469]
Hi,
I'm currently playing with the idea to run SCDF on different binder than Redis, e.g. on RabbitMQ.

I tested currently with custom modules built with multi-binder support. I managed to deploy a stream on Rabbit once with 

    stream create test --definition "mysource --spring.cloud.stream.default-binder=rabbit --spring.rabbitmq.host=<the_rabbit_host>  | mysink --spring.cloud.stream.default-binder=rabbit --spring.rabbitmq.host=<the_rabbit_host>" --deploy

or alternatively with that one

    stream create test --definition "mysource | mysink"
    stream deploy mms --properties "module.*.spring.cloud.stream.default-binder=rabbit, module.*.spring.rabbitmq.host=<the_rabbit_host>"

So in principle this can work.
But this way of course we cannot use standard Spring Cloud Stream modules: They are built by silently assuming Redis.
Furthermore it would be nice to tell the SCDF admin somehow to use a certain binder by default and propagate this to the deployed modules.

So what would be the necessary changes?
- Standard SCS modules had to be built with according addition of `spring-cloud-starter-stream-rabbit` in their pom.xml. For standalone usage they would need to be enhanced with application.yml file containing `spring.cloud.stream.default-binder` property, which can still point to Redis, I think.
- SCDF deployer would have to set/propagate binder-related properties to the deployed modules
- SCDF admin should have a notion of `default-binder` which is always used if not overridden during stream deployment
- probably some environment variables have to be introduced to tell the admin about the default binder
- SCDF shell would have to support this via DSL, I guess

Did I forget something important?

Would something like that be on your roadmap in the next time?
Alexander

**Comment by sabbyanandan** [comment]
Hi, @styjdt: Though it is temporary, it is possible to switch the binder at the stream deploy time. This is done with `includes` and `excludes` token combination in the deployment properties. 

For example, you'd be able to switch the binders for all applications associated in the stream via:

```
stream create foo --definition "time | log"
stream deploy foo --properties "module.*.includes=org.springframework.cloud:spring-cloud-stream-binder-rabbit:1.0.0.BUILD-SNAPSHOT,module.*.excludes=:*-redis"
```

However, we are currently in the process of converting all stream and task applications as [starters](https://github.com/spring-cloud/spring-cloud-stream-app-starters) and the respective starters are [generated](https://github.com/spring-cloud/spring-cloud-stream-app-starters/blob/master/spring-cloud-stream-app-generator/pom.xml#L31) for both rabbit and kafka binders. Eventually, these app combinations would roll into dataflow-server's artifact registry. We are thinking about properties/yaml file for the initial set of app combinations to load (in the registry) at the bootstrap time. This is all very much active w-i-p.

**Comment by styjdt** [comment]
Sabby, thanks for the info. The `--includes`/`--excludes` thing does not work for me, don't know why. Tried exactly your code snippet. The stream is deployed but the modules still talk via redis with each other.
I also tried the `--includes` option in another context (#166, #475), but also there it is ignored or does not work as I'm expecting it.

However, I understand that this is work in progress and it is good to know that you have stuff like that on your agenda.

**Comment by sabbyanandan** [comment]
Hi, @styjdt: The `--includes/--excludes` tokens are gone and in the latest [1.0.0.RELEASE](https://spring.io/blog/2016/07/12/spring-cloud-data-flow-1-0-ga-released) of SCDF, we provide the ability to register binder specific apps through the bit.ly links as explained in the [reference guide](http://docs.spring.io/spring-cloud-dataflow/docs/1.0.0.RELEASE/reference/htmlsingle/#spring-cloud-dataflow-register-apps). 

Let's say you've had kafka apps in the registry and you would like to overwrite from kafka -> rabbit, you can use the `--force` flag. 

For example,

> dataflow:>app import --uri http://bit.ly/stream-applications-rabbit-maven --force

overwrites all the existing coordinates in the app-registry with rabbit binder based apps. 

If you've a custom app that includes multiple binders in the classpath, you can point to a specific binder by passing the app properties via `--properties` at the time of stream deployment. More details [here](http://docs.spring.io/spring-cloud-stream/docs/1.0.2.RELEASE/reference/htmlsingle/#multiple-binders) and [here](http://docs.spring.io/spring-cloud-dataflow/docs/1.0.0.RELEASE/reference/htmlsingle/#spring-cloud-dataflow-global-properties).

For example,

> stream deploy foo --properties "app.APP_NAME.spring.cloud.stream.defaultBinder=rabbit"

where `foo` is the stream name and `APP_NAME` is your custom application name.
