### ISSUE TITLE
Use kebab-case format for ssbj options

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#4692]
In `spring-cloud-dataflow-single-step-batch-job/src/main/resources/META-INF/dataflow-configuration-option-groups.properties` all options refs should be with `kebab-case` as that's the boot's way to give out id's for options.

Like `spring.rabbitmq.virtualHost` should be `spring.rabbitmq.virtual-host`.

**Comment by cppwfs** [comment]
It is a Spring Cloud Task issue as it pertains to the `spring.batch.job.jobName` for the kabob issue.   
https://github.com/spring-cloud/spring-cloud-task/pull/795

**Comment by cppwfs** [comment]
Closed by mistake
