### ISSUE TITLE
ssbj option groups missing from metadata jar

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#4693]
Groups not shown:
```
task.ssbj=maven://org.springframework.cloud:spring-cloud-dataflow-single-step-batch-job:2.9.0-SNAPSHOT
task.ssbj.metadata=maven://org.springframework.cloud:spring-cloud-dataflow-single-step-batch-job:jar:metadata:2.9.0-SNAPSHOT
```

Works with just main fatjar:
```
task.ssbj=maven://org.springframework.cloud:spring-cloud-dataflow-single-step-batch-job:2.9.0-SNAPSHOT
```

**Comment by cppwfs** [comment]
In this case it looks like the plugin that creates the metadata jar is not adding the `dataflow-configuration-option-groups.properties`
We need this for SSBJ integration.

**Comment by tzolov** [comment]
What are SSBJ groups :) ? and where are those configurations added/created?

**Comment by cppwfs** [comment]
Hmmm.... Context does help :-D
In the spring-cloud-dataflow-single-step-batch-job we are creating a new task app to allow users to configure a batch  job via properties.
The UI needs extra metadata to know how to organize the available properties for the single step batch job.   
The option-groups file is located here: https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/spring-cloud-dataflow-single-step-batch-job/src/main/resources/META-INF/dataflow-configuration-option-groups.properties

At build time the properties file is included in the jar of the application.  But the metadata jar does not have this properties file.

**Comment by jvalkeal** [comment]
So hopefully this issue is just version change for https://github.com/spring-cloud/spring-cloud-dataflow/blob/69f1700c2afadaac8d334f7690360ee318206b0b/pom.xml#L92 when things are fixed in apps plugin.
