### ISSUE TITLE
Documentation on configuring other monitoring systems than pre-configured ones

### ISSUE THREAD

**Issue by edudar** [spring-cloud/spring-cloud-dataflow#4706]
Considering that SCDF uses Spring Boot and Micrometer internally, it should be possible to configure any monitoring system that Micrometer supports. My company uses a statsd-based one, for example, that works totally fine with all our Spring Boot applications. SCDF documentation goes into detail on how to manage with pre-configured monitoring systems and dashboards but totally misses how to configure any other monitoring system. I'd assume that one can use externalized properties support from Spring Boot and pass properties from a file or CLI when starting the SCDF server. It'd be good to have a section in "Server Monitoring" devoted to that.

**Comment by sabbyanandan** [comment]
Thanks, @edudar. Moved it to the Microsite - we will have a look.
