### ISSUE TITLE
Problem with default version of Task 

### ISSUE THREAD

**Issue by szopal** [spring-cloud/spring-cloud-dataflow#4724]
Hi,

I have problem with deploy Task on k8s - below details:

1. I deployed task with default version (no change version deployment properties parameter) ex. 1.0.2
2. I wanted again run task with different version ex. 1.0.1
3. I wanted again run task with default version (choose Default version 1.0.2) in Task properties

But after run step 3 Task was run again with version from step 2 (1.0.1). I can see that in table TASK_EXECUTION_METADATA in column TASK_EXECUTION_MANIFEST that was passed parameters:

"deploymentProperties":{"version.task-name":"1.0.1"}

And in task details I can see:

Platform Properties
version.task-name: 1.0.1

though I choose Default version (1.0.2).

**Comment by szopal** [comment]
> Hi, @szopal. Your description appears to be incomplete. Could you please update it with the version of SCDF and APIs in use, and the reproducible steps with a sample? We can have a look at it then.

We use SCDF in version 2.8.1.

**Comment by cppwfs** [comment]
Moving this issue to SCDF UI :  https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1779
