### ISSUE TITLE
Experiment with App SSO (for K8s) + Spring Authorization Server

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4744]

**Comment by jvalkeal** [comment]
I got `Spring Cloud Gateway for Kubernetes` with SSO via azure working fine with some loose ends `Spring authz server` don't yet work as some missing features makes oauth flow to blow up, though I have a feeling that minimum things may start to work relatively soon.

I'll think a little where to put docs/instructions how this integration can be setup.
