### ISSUE TITLE
Task running in k8s scdf failed to configure the DataSource

### ISSUE THREAD

**Issue by jianfengyuan** [spring-cloud/spring-cloud-dataflow#4747]
![task console log](https://user-images.githubusercontent.com/28891046/140295221-8ed89bb7-4c69-42e2-a66b-9461f6d81393.png)
![scdf arguements](https://user-images.githubusercontent.com/28891046/140295351-eb4364f2-f9b7-4fc6-9491-0cac24746275.png)
it works in local scdf, but failed in k8s.

**Comment by cppwfs** [comment]
Hello.
I was unable to reproduce the issue you specified using a fresh Spring Cloud Task created from start.spring.io.
Launching the application from SCDF to the K8's platform.    
Can you provide the following:
1: Version of SCDF that you are using
2: A sample application repository on github that replicates the behavior .

Thanks

**Comment by jianfengyuan** [comment]
Hi.

1. The version of SCDF is 2.8.3

2. My MySQL database is running on aws and the spring cloud task demo(timestamp) imported from dockerhub is work, but when I  downloaded the source code and build it without h2 dependency, it goes failed. 

3. If I build the task with h2 dependency, the SCDF can not track any task info, like start time, end time or exit code etc. 

Could you have any strategied to help me to debug it?

Thank.

**Comment by cppwfs** [comment]
What repository are you obtaining the timestamp sample?

**Comment by jianfengyuan** [comment]
Yes. I have used dockerfile to build the image. Could it be a problem? Here is the dockerfile. 
![3078608F-CE04-46FE-9BDB-C684AA9FF738](https://user-images.githubusercontent.com/28891046/140519337-b940b06f-d67b-47aa-9fb4-98882f8002a1.png)

**Comment by cppwfs** [comment]
Try the timestamp sample from the Spring Cloud Task project located here: https://github.com/spring-cloud/spring-cloud-task/tree/main/spring-cloud-task-samples/timestamp
```
#Build the app
  mvn clean install 
#Build the docker container
  mvn spring-boot:build-image
  ```

**Comment by markpollack** [comment]
Closing for lack of feedback.  If there are any additional problems, please create a new issue.
