### ISSUE TITLE
Trailing spaces on task arguments cause NullPointerException

### ISSUE THREAD

**Issue by adrianriley** [spring-cloud/spring-cloud-dataflow#4748]
**Description:**
When entering task arguments on the launch task page of the UI, in the freetext tab, if you enter name=value, 1 per line, with a line having trailing spaces after the value, then once the run has started, trying to view the task execution page in the UI fails with NullPointerException. I'm guessing this is caused by having rows the task_execution_params table with task_param null. Deleting these rows fixes the issue.

**Release versions:**
Implementation Version: 2.8.2 (spring-cloud-starter-dataflow-server)
Core: 2.8.2 (Spring Cloud Data Flow Core)
Dashboard: 3.1.2 (Spring Cloud Dataflow UI)
Shell: 2.8.2 (Spring Cloud Data Flow Shell)

**Steps to reproduce:**
As above. 

- Go to task launch page
- Select freetext tab
- In task arguments text area, enter argumenst one-per-line, with trailing spaces on some lines
- Launch the task
- Refresh the task execution page a few times until the task starts running
- NullPointerException error popup appears
[scdf.log](https://github.com/spring-cloud/spring-cloud-dataflow/files/7475899/scdf.log)

**Comment by sabbyanandan** [comment]
@adrianriley: Thanks for reporting, we will have a look.

**Comment by cppwfs** [comment]
I was unable to reproduce the problem using SCDF on an H2 database.

1. Created task `ts1104` using the `timestamp` application
2. Launched the task using the following:
> Properties:

- app.timestamp.bar=cdf     
- app.timestamp.boo=123    
- app.timestamp.foo=abc

Where the first 2 properties have 5 trailing blanks.

> Arguments:

- foo=cdf   
- --baz=abc    
- --doo=efg

Where the first 2 arguments  have 5 trailing blanks.

Can you provide us any additional detail as to what my test scenario is missing?

**Comment by adrianriley** [comment]
Very strange. My task has  6 arguments:

- command=XXX
- agreementIds=XXX
- caseHandler=XXX
- reason=XXX
- caseOpen=XXX
- createEvent=XXX

If I put a trailing space at the end of the 4th one, the issue occurs. It doesn't seem to matter what the values are, I've done it exactly like that, with XXX as the value of each, and it fails.

Here's the content of the task_execution_params table:

```
select * from task_execution_params e
where e.task_execution_id >= 21387;

```

```
21387	agreementIds=XXX
21387	caseHandler=XXX
21387	caseOpen=XXX
21387	command=XXX
21387	createEvent=XXX
21387	reason=XXX
21387	
21387	--spring.cloud.task.executionid=21387
```

**Comment by adrianriley** [comment]
Doesn't have to be that task, I launched a different task with the same set of arguments, The same thing happened.

**Comment by cppwfs** [comment]
Here are the arguments I entered using Safari: ![image](https://user-images.githubusercontent.com/695673/140527911-6b408725-72a2-4311-a537-0699b203a654.png)
I launched this using the following version of SCDF
![image](https://user-images.githubusercontent.com/695673/140528242-9e7a50bb-9414-4067-be31-0c2d30d2fcb9.png)

By chance are you using the shell or the restful api directly?

**Comment by adrianriley** [comment]
With a single trailing space added to 'reason=XXX ' (because it's last in alpha order?), this is logged by TaskAppDeploymentRequestCreator.createRequest():

`TaskAppDeploymentRequestCreator : Created AppDeploymentRequest = [AppDeploymentRequest@529b2ec commandlineArguments = list['agreementIds=XXX', 'caseHandler=XXX', 'caseOpen=XXX', 'command=XXX', 'createEvent=XXX', 'reason=XXX', '', '--spring.cloud.task.executionid=21488'], deploymentProperties =...`

That empty command line argument becomes, I think, the null entry in task_execution_params.task_param, because Oracle stores empty string as null. I don't see the insert sql statement logged, but that's the result.

Then ArgumentSanitiser.sanitise() throws a NullPointerException at the first line:

`int indexOfFirstEqual = argument.indexOf("=");`

because argument is null.

**Comment by cppwfs** [comment]
I was able to reproduce using Oracle as a DB.
