### ISSUE TITLE
Set proper boot actuator endpoint configuration when deploying apps.

### ISSUE THREAD

**Issue by CEDDM** [spring-cloud/spring-cloud-dataflow#4753]
**Description:**
The info endpoint is no more enabled by default with Spring Boot 2.5 https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#secure-info-endpoint
This causes the app to be stucked in "Deploying" state in Kubernetes with this error : `Readiness probe failed: HTTP Probe failed with statuscode: 404`

**Release versions:**
Tested with SCDF 2.9.1 and Spring Boot 2.5.5 under microk8s 1.18.20

**Steps to reproduce:**
Create a dummy processor and deploy it in Kubernetes with a simple stream like `time | my-processor | log`

**Additional context:**
A simple workaround is to add `management.endpoints.web.exposure.include=health,info` in application.properties to enable info endpoint.
But wouldn't it be nice if Skipper does that for us ?

**Comment by jvalkeal** [comment]
We've been trying not to tweak setting too much as we don't know what user is running. On our normal apps we chose to re-enable those endpoints in apps itself.

There is a config setting [Common Application Properties](https://docs.spring.io/spring-cloud-dataflow/docs/2.9.1/reference/htmlsingle/#spring-cloud-dataflow-global-properties) where you could do this, would it work for you?

**Comment by CEDDM** [comment]
Yes sure ! That would work.
But I'm afraid it might be complicated for SCDF beginners to understand why their app is not in 'Deployed' status

**Comment by markpollack** [comment]
I agree, we already set many boot properties so that the user doesn't have to, this one sounds quite important.

**Comment by corneil** [comment]
My suggestion would be to make sure the samples have these properties added and that we document the need for adding `management.endpoints.web.exposure.include=health,info,bindings`

**Comment by markpollack** [comment]
This is a larger more important issue than documentation in my opinion, these are the type of properties that we should be setting automatically when deploying.

**Comment by onobc** [comment]
All OOTB stream applications have the property set:
```properties
management.endpoints.web.exposure.include=health,info,bindings
```

Custom apps will not have it though. It would be easy enough to add but are there any cases where the user would **NOT** want these set? I believe in that case an `management.endpoints.web.exposure.exclude` may work to negate the default. 

I will give this approach a try.

**Comment by onobc** [comment]
I verified that the `management.endpoints.web.exposure.exclude` does in fact do what it says it does.

Given an app w/
```properties
management.endpoints.web.exposure.include=health,info,bindings
```
setting the property:
```
management.endpoints.web.exposure.exclude=health,info
```
results in only 2 endpoints (as expected): `health, info`.

**Comment by onobc** [comment]
Hi @nstaeger ,
Thank you for posting the instructions on how to set the property. We will take a look at why setting on the command line did not work and follow up from the results of that.
