### ISSUE TITLE
Http source connection refused 

### ISSUE THREAD

**Issue by glokta-san** [spring-cloud/spring-cloud-dataflow#4770]
![Capture](https://user-images.githubusercontent.com/94870559/142934492-c42662a0-6093-4aaa-97c1-5c3c2cc06cb5.JPG)

I have this nagging issue that has appeared only in the newest version

**Comment by jvalkeal** [comment]
Did I miss something you're trying to do as you defined port `9000` but trying to connect to `9001`?
