### ISSUE TITLE
Shell breaks with circular dependency

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#4783]
Boot from `2.6.x` is now enforcing not to have circular deps.
```
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

   scriptCommands (field private org.springframework.shell.core.JLineShellComponent org.springframework.shell.commands.ScriptCommands.shell)
      ↓
   shell defined in class path resource [org/springframework/cloud/dataflow/shell/autoconfigure/BaseShellAutoConfiguration.class]
┌─────┐
|  configCommands (field private org.springframework.web.client.RestTemplate org.springframework.cloud.dataflow.shell.command.ConfigCommands.restTemplate)

```

Need to think how to fix this in `spring-shell` or optionally use `spring.main.allow-circular-references` in shell app itself.

**Comment by dreamworkerln** [comment]
Same for Spring boot 2.6.x

`
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

   configFileCopy (field private ru.dreamworkerln.spring.shell_lib.shell.InputReader ru.dreamworkerln.spring.config.manager.commands.ConfigFileCopy.inputReader)
      ↓
   inputReader defined in class path resource [ru/dreamworkerln/spring/shell_lib/configuration/SpringShellLibConfig.class]
      ↓
   org.springframework.shell.jline.JLineShellAutoConfiguration (field private org.springframework.shell.Shell org.springframework.shell.jline.JLineShellAutoConfiguration.shell)
      ↓
   shell defined in class path resource [org/springframework/shell/SpringShellAutoConfiguration.class]
┌─────┐
|  org.springframework.shell.result.ResultHandlerConfig
└─────┘


Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.


Process finished with exit code 1
`

**Comment by jeffreycrump01880** [comment]
For the record, this "fix" is just to enable circular references for now, right?  I don't need an update to spring-shell for that.
