### ISSUE TITLE
https://dataflow.spring.io is down

### ISSUE THREAD

**Issue by burlaka** [spring-cloud/spring-cloud-dataflow#4787]
Hello,
Site https://dataflow.spring.io is down. 522 error
![Снимок экрана от 2021-12-14 16-31-28](https://user-images.githubusercontent.com/2881089/146008883-d8520ff5-aac9-4c85-b8c9-0d899f013df7.png)
![Снимок экрана от 2021-12-14 16-35-31](https://user-images.githubusercontent.com/2881089/146008888-927fe58a-dc44-4b3c-888d-865e012ad558.png)

**Comment by jvalkeal** [comment]
Closing old issue. Sorry that it took time to bring it back due to down time in a hosting system.
