### ISSUE TITLE
Update K8s compatibility in test-plan and docs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4792]
As we continue to increase the ATs on different K8s versions, let's attempt to keep the K8s compatibility versions published in the docs and the CI plans correctly. Perhaps (re)use the same docs (same source) across the board. A few links are below.

- [x] Update to run against 1.21.x and later versions (see: [tmc-ci.yml](https://github.com/pivotal/scdf-pro/blob/master/.github/workflows/tmc-ci.yml))
- [x] Update [README](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes#kubernetes-compatibility)
- [x] Update PRO [docs](https://docs.vmware.com/en/VMware-Spring-Cloud-Data-Flow-for-Kubernetes/1.4/scdf-k8s/GUID-index.html#general-limitations)
- [x] Update Microsite [docs](https://dataflow.spring.io/docs/installation/kubernetes/compatibility/)

**Comment by bono007** [comment]
### [tmc-ci.yml](https://github.com/pivotal/scdf-pro/blob/master/.github/workflows/tmc-ci.yml)
Currently the TMC matrix has the most tested permutations for the latest version and then a few variations tested for the earlier versions. 

**Plan:** We will update the current `1.20` entries to point to `1.21` and then keep a few entries for `1.20`. 

> ℹ️ We are still not able to see 1.21 in the k8s version drop-down in TMC but it should be available/visible soon. 

> ℹ️ 1.21 is the latest available version in TMC. Once 1.22 is available, we will repeat this exercise for 1.22.

**Comment by bono007** [comment]
### [README](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes#kubernetes-compatibility)
**Plan:** Expand grid to `1.21.x`.

**Question:** Is the intention that the k8s version in the [SCDK](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes#kubernetes-compatibility) matrix be the same as the k8s version in the [SCDF](https://dataflow.spring.io/docs/installation/kubernetes/compatibility/) matrix? I would assume so. Do we have any compat matrix tests directly for SCDK or do we imply its coverage via the results of the SCDF TMC matrix tests? I am guessing the latter, but want to verify.

**Comment by bono007** [comment]
### [Microsite docs](https://dataflow.spring.io/docs/installation/kubernetes/compatibility/) 
**Plan:** Expand grid to `1.21.x`

**Comment by bono007** [comment]
### [PRO docs](https://docs.vmware.com/en/VMware-Spring-Cloud-Data-Flow-for-Kubernetes/1.4/scdf-k8s/GUID-index.html#general-limitations)
**Question:** The Pro docs tout support up to `v1.22.x` - does this need updating? Is the intention to pare it back down to what we are currently testing against (up to `v1.21.x`)? Or is the intention to bump it up to `v1.23.x` (latest k8s) based on the following comment in the docs :

> This product is intended to be used with any Kubernetes distribution. However, given the number of Kubernetes vendors and configurations, not all of them have been tested with SCDF for Kubernetes.

If we do bump to `v1.23.x` should we manually verify?

**Comment by bono007** [comment]
I have left a separate comment (easier to reply to) on each of the "targeted" files in the original description. 

@sabbyanandan @jvalkeal @ilayaperumalg (or other team members) please advise. Thx.

**Comment by onobc** [comment]
> ### [PRO docs](https://docs.vmware.com/en/VMware-Spring-Cloud-Data-Flow-for-Kubernetes/1.4/scdf-k8s/GUID-index.html#general-limitations)
> **Question:** The Pro docs tout support up to `v1.22.x` - does this need updating? Is the intention to pare it back down to what we are currently testing against (up to `v1.21.x`)? Or is the intention to bump it up to `v1.23.x` (latest k8s) based on the following comment in the docs :
> 
> > This product is intended to be used with any Kubernetes distribution. However, given the number of Kubernetes vendors and configurations, not all of them have been tested with SCDF for Kubernetes.
> 
> If we do bump to `v1.23.x` should we manually verify?

During IPM today we discussed the following:
1. pare the matrix down to N and N-2 (which is 1.23, 1.22, 1.21) and we will also add 1.20 as its recent (so really N-3)
2. add some verbage around the fact that it can run w/ earlier versions but we do not actively test/support them and point to legacy matrix in a wiki (which is this current matrix up to the 1.20 column).

@sabbyanandan one outstanding question though, the 1.23 testing. Did we decide on manually testing this?

**Comment by sabbyanandan** [comment]
Yeah, let's do it using Minikube/Kind, and we can close it then.

**Comment by sabbyanandan** [comment]
Something like:

> minikube start  --memory=8000 --cpus=6  --vm-driver=docker --kubernetes-version v1.23.0

**Comment by corneil** [comment]
> ### [PRO docs](https://docs.vmware.com/en/VMware-Spring-Cloud-Data-Flow-for-Kubernetes/1.4/scdf-k8s/GUID-index.html#general-limitations)
> **Question:** The Pro docs tout support up to `v1.22.x` - does this need updating? Is the intention to pare it back down to what we are currently testing against (up to `v1.21.x`)? Or is the intention to bump it up to `v1.23.x` (latest k8s) based on the following comment in the docs :
> 
> > This product is intended to be used with any Kubernetes distribution. However, given the number of Kubernetes vendors and configurations, not all of them have been tested with SCDF for Kubernetes.
> 
> If we do bump to `v1.23.x` should we manually verify?

Who / How do we update the pro docs?

**Comment by corneil** [comment]
Create PR for Microsite.
https://github.com/spring-io/dataflow.spring.io/pull/454

**Comment by corneil** [comment]
Created PR for Kubernetes deployer.
https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/504

**Comment by onobc** [comment]
> > ### [PRO docs](https://docs.vmware.com/en/VMware-Spring-Cloud-Data-Flow-for-Kubernetes/1.4/scdf-k8s/GUID-index.html#general-limitations)
> > **Question:** The Pro docs tout support up to `v1.22.x` - does this need updating? Is the intention to pare it back down to what we are currently testing against (up to `v1.21.x`)? Or is the intention to bump it up to `v1.23.x` (latest k8s) based on the following comment in the docs :
> > > This product is intended to be used with any Kubernetes distribution. However, given the number of Kubernetes vendors and configurations, not all of them have been tested with SCDF for Kubernetes.
> > 
> > 
> > If we do bump to `v1.23.x` should we manually verify?
> 
> Who / How do we update the pro docs?

Yeh, this was not obvious. The process is to create an issue in the https://github.com/pivotal-cf/docs-spring-cloud-dataflow-k8s repo.  Here is an example issue where I requested k8s release docs https://github.com/pivotal-cf/docs-spring-cloud-dataflow-k8s/issues/48.

I would include the..
- location you want updated
- exact content you want updated (from -> to)
- ping Ben Klein in the issue 
- reach out to Ben Klein on Slack and give him a heads up about the issue and see if he can take a peek and to ping us if he has any questions. He has been super responsive and helpful.

**Comment by klopfdreh** [comment]
Because those to doc updates are not in SCDF repository - do they block the release?

**Comment by onobc** [comment]
Not at all. It has been updated in the main locations and we will get it updated in the last place asap. But it will not block the release.

**Comment by onobc** [comment]
Moving to post M2 as this really has no functional impact and is still gated on the updating of the Tanzu docs.

**Comment by corneil** [comment]
Create https://github.com/pivotal-cf/docs-spring-cloud-dataflow-k8s/issues/51

**Comment by corneil** [comment]
Pro docs was updated
