### ISSUE TITLE
Composed task runner not exiting in split execution

### ISSUE THREAD

**Issue by zjsun** [spring-cloud/spring-cloud-dataflow#4799]
**Description:**
In split execution, the composed task runner keeps running even after the task is fully completed. It results in resource leak after many times launch(eg. in a scheduled job).

**Release versions:**
2.9.1

**Steps to reproduce:**
1. Create a task with: `<step1: timestamp || step2: timestamp>`.
2. Launch the task and wait to complete.
3. In Local platform, use `jps` tool to monitor the ctr process, and in k8s platform, the ctr pod is always in running state.

**Additional context:**
I tested in Local and K8s.

**Comment by cppwfs** [comment]
Hello @zjsun,
You will need to set `closecontext-enabled=true` when using splits.
More can be read on using splits in composed tasks [here](https://dataflow.spring.io/docs/feature-guides/batch/composed-task/).

**Comment by zjsun** [comment]
Tks @cppwfs ,
It works after setting `closecontext-enabled=true`. 

And I think that it will be better if you set this option with default `true`.

**Comment by cppwfs** [comment]
I'll discuss the suggestion with the team.  Thank you for opening the issue.
