### ISSUE TITLE
Issue with Mysql 5.6

### ISSUE THREAD

**Issue by evertoschneider** [spring-cloud/spring-cloud-dataflow#4809]
Using the following command to start a SCDF server connected to a mysql database (version 5.6):
`java -jar spring-cloud-dataflow-server-2.9.0-RC1.jar --spring.datasource.url=jdbc:mysql://localhost:3306/database --spring.datasource.username= --spring.datasource.password= --spring.datasource.driver-class-name=org.mariadb.jdbc.Driver`

I get this error trying to start the server: Caused by: `org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException: Flyway Teams Edition or MySQL upgrade required: MySQL 5.6 is no longer supported by Flyway Community Edition`

Looking for solutions online I tried to use this command: 
`java -jar spring-cloud-dataflow-server-2.9.0-RC1.jar --spring.datasource.url=jdbc:mysql://localhost:3306/jacad31_database --spring.datasource.username= --spring.datasource.password= --spring.datasource.driver-class-name=org.mariadb.jdbc.Driver --spring.flyway.enabled=false  --spring.datasource.initialization-mode=always`

After that the server starts but then this error happens when I try to open the dashboard: `Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Table 'database.app_registration' doesn't exist`

I tried to add the startup command: `--spring.datasource.schema=classpath*:/org/springframework/cloud/dataflow/server/db/migration/mysql/V1__INITIAL_SETUP.sql` but the error continues.

I think this happens because flyway is responsible for creating server configuration files on startup but since I'm not using flyway the config tables are not created. My question is: how can I create this tables on my database without flyway?

**Comment by markpollack** [comment]
Flyway supports version 5.6 only with their commercial license, which we are in the process of testing out for the commercial version of spring cloud data flow.  For OSS users, you will need to upgrade to MySQL 8 when the next OSS release of scdf is made.  See https://github.com/spring-cloud/spring-cloud-dataflow/issues/4887 for progress/status.
