### ISSUE TITLE
UI - Add OAuth Authentication Support

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#483]
This issue depends on https://github.com/spring-cloud/spring-cloud-dataflow/issues/482

In order to provide a better single-sign-on experience, the UI-login process should be OAuth based, so that when the user is already logged into the OAuth server, (s)he shall not be required to re-enter the username and password.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#49
