### ISSUE TITLE
Documentation seems inconsistent on explaining differences of args and props for scdf composed-task (perhaps contradictory even)

### ISSUE THREAD

**Issue by nightswimmings** [spring-cloud/spring-cloud-dataflow#4847]
The documentation here defines a series of options for the composed task: https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc#configuration-options
We can find things like composed-task-arguments, max-wait-time, dataflow-server-uri etc.. in the list
At the end of the section it says literally: 
  "To set a property for Composed Task Runner you will need to prefix the property with app.composed-task-runner.. 
  For example to set the dataflow-server-uri property the property will look like app.composed-task-runner.dataflow-server-uri."
But a bit later, there's a section: https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc#passing-arguments-to-the-composed-task-runner
that explains how you can pass both arguments and properties through the shell, and these time, some of the options for the original list are passed as arguments

So my question is, is every SCDF composed-task option, in the background, expected to be either a arg or a param specifically? if so, how do we know which is which?
Otherwise, if options can be used as both, is the impact different depending on where it is placed or is it just that --argument=x and --property=app.composed-task-runner.x are simply interchangeable alias?
I know, if I recall correctly, that at least in SCDF 2.7 looked like the exampled used above, app.composed-task-runner.dataflow-server-uri, was honoured if passed as argument --dataflow-server-uri

**Comment by cppwfs** [comment]
Composed Task Runner is a boot application and thus it follows Spring Boot's [External Configuration order of precedence](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config).   In the case above arguments take precedence over parameters(properties).   
SCDF also honors the use of `--dataflow-server-uri` .

**Comment by nightswimmings** [comment]
Hi @cppwfs, thanks for the answer! So if we always use tasks developed with Spring-Boot theres no need for app.X. properties, we can just use arguments right?

**Comment by cppwfs** [comment]
Yes.

**Comment by nightswimmings** [comment]
Thanks @cppwfs !!

**Comment by cppwfs** [comment]
I will close this issue.   We can reopen if there are future issues.
