### ISSUE TITLE
Removal of deployment properties between task executions

### ISSUE THREAD

**Issue by tomgeraghty3** [spring-cloud/spring-cloud-dataflow#4850]
**Description:**
Once a deployment property is set during a Task execution there doesn't seem to be a way to **remove** that property in future executions due to the retention of values between executions - the only option is to override it. So if you omit that property because e.g. you want it to fall to a default value, you would think it wouldn't be passed to the new execution, but it gets passed with the previous value.
For example if `kubernetes.entry-point-style` is not provided then it defaults to `exec`. But if this is provided as `shell` in one execution, then omitted it in a future execution, the expectation would be that it would not be passed (and will default to `exec`) but instead it is passed with `shell` value from the previous run.
Another, more UI focused example: If I run a task and specifically select a version, then a property is added: `version.my-task=[version]` which can be seen in the "Freetext" section when launching the task or the task execution screen after it's launched (under "Platform properties").
On a future run of the same task, if I select version to be "Default version" from the drop down then the `version.my-task=[version]` property is **omitted** (and does not appear in the "Freetext" when launching) but, instead of the default version being used, it will always use whatever version was selected in the previous execution.
The previous version can always be overridden by specifying `version.my-task=[version]` but the omission of this - as is the case when you select "default version" in the UI - causes it to default to previous values and causes confusion as that does not necessarily align with the "default version".

There is no stacktrace here as this is not does not produce any exception.

**Release versions:**
```
{
    "featureInfo": {
        "analyticsEnabled": true,
        "streamsEnabled": true,
        "tasksEnabled": true,
        "schedulesEnabled": true,
        "monitoringDashboardType": "GRAFANA"
    },
    "versionInfo": {
        "implementation": {
            "name": "spring-cloud-dataflow-server",
            "version": "2.9.1"
        },
        "core": {
            "name": "Spring Cloud Data Flow Core",
            "version": "2.9.1"
        },
        "dashboard": {
            "name": "Spring Cloud Dataflow UI",
            "version": "3.2.1"
        },
        "shell": {
            "name": "Spring Cloud Data Flow Shell",
            "version": "2.9.1",
            "url": "https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.9.1/spring-cloud-dataflow-shell-2.9.1.jar"
        }
    },
    "securityInfo": {
        "authenticationEnabled": false,
        "authenticated": false,
        "username": null,
        "roles": []
    },
    "runtimeEnvironment": {
        "appDeployer": {
            "deployerImplementationVersion": "2.8.0",
            "deployerName": "Spring Cloud Skipper Server",
            "deployerSpiVersion": "2.8.1",
            "javaVersion": "1.8.0_312",
            "platformApiVersion": "",
            "platformClientVersion": "",
            "platformHostVersion": "",
            "platformSpecificInfo": {
                "default": "kubernetes"
            },
            "platformType": "Skipper Managed",
            "springBootVersion": "2.5.5",
            "springVersion": "5.3.10"
        },
        "taskLaunchers": [
            {
                "deployerImplementationVersion": "2.7.1",
                "deployerName": "KubernetesTaskLauncher",
                "deployerSpiVersion": "2.7.1",
                "javaVersion": "1.8.0_312",
                "platformApiVersion": "v1",
                "platformClientVersion": "unknown",
                "platformHostVersion": "unknown",
                "platformSpecificInfo": {
                    "namespace": "spring-cloud-dataflow",
                    "master-url": [omitted]
                },
                "platformType": "Kubernetes",
                "springBootVersion": "2.5.5",
                "springVersion": "5.3.10"
            }
        ]
    },
    "monitoringDashboardInfo": {
        "url": [omitted]
        "refreshInterval": 15,
        "dashboardType": "GRAFANA",
        "source": "default-scdf-source"
    },
    "_links": {
        "self": {
            "href": "http://localhost:8080/about"
        }
    }
}
```

**Custom apps:**
This problem affects any task

**Steps to reproduce:**
Consider the scenario where I have version 0.0.1 right the way through to version 0.0.11 of a task and I set 0.0.11 to be the default. The task is named `scdf-task-test`

1) Run the task for the first time with version 0.0.5 and set `kubernetes.entry-point-style` to `shell`
<img width="561" alt="image" src="https://user-images.githubusercontent.com/47372735/157487484-65e3adbf-d624-4534-b38e-749a36a8f5fa.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/47372735/157487563-fa385218-937d-4ab9-8f0d-931b1867ef57.png">

2) The task launches and completes. The execution page shows the properties
<img width="680" alt="image" src="https://user-images.githubusercontent.com/47372735/157488072-cbbaed25-90cd-434b-a83d-ca68fceb0f89.png">

3) Relaunch the task and change the version to be default and remove the `kubernetes.entry-point-style`
<img width="511" alt="image" src="https://user-images.githubusercontent.com/47372735/157488522-a5f7d26b-c2a8-4e9b-8e29-ba0796091bb9.png">
<img width="702" alt="image" src="https://user-images.githubusercontent.com/47372735/157488557-a1e92f98-f00c-4a05-be93-38ff3385237c.png">

4) The Task is launched but the previous properties remain. The version is 0.0.5 even though I selected the default (which is 0.0.11) 
<img width="693" alt="image" src="https://user-images.githubusercontent.com/47372735/157488745-a506909a-7c4c-4ede-8c1c-d60a8047a118.png">

**Additional context:**
I understand the design is to persist between executions for deployment properties and that's useful in that case, but what if I want to remove a previously supplied property from my next run of the task? 

There is also another scenario where this causes a problem. If I have a stream that uses the Task Launcher and does **not** provide a version, then I would assume it would always use the "default version" but if someone comes along and manually launches that task with a specific version then the next time the Task Launcher from the stream launches the task it is going to use the manual version that the previous person selected. The only way around this is to always specify a version in the stream definition but that means that any new versions of the task also need an update to the stream definition thereby eliminating the purpose of the "Default version" in the Apps section.

If I have misunderstood a core design principal then apologies and please point me in the right direction (e.g. Docs)

**Comment by markpollack** [comment]
Hi.  I think that we may have this functionality.  @cppwfs will investigate.

**Comment by cppwfs** [comment]
@tomgeraghty3 set the value to null if you want to remove the value.   For example: When launching timestamp we use `app.timestamp.format=YYYY` for the first launch.   To remove this from the next launch set the format to null (empty) as show here: `app.timestamp.format=`.    If this answer does not solve your issue feel free to add an additional comment.
