### ISSUE TITLE
Proposal for documenting client-server compatibility on documentation

### ISSUE THREAD

**Issue by nightswimmings** [spring-cloud/spring-cloud-dataflow#4854]
I am trying to find any official statement on what SCDF client versions work with which server SCDF versions and I cannot find it.
Would it be worthwhile to add it to documentation or is there any general rule?

My apologies if this can be found somewhere, I tried searching terms like compatibility and the like with no luck on both github and scdf documentation

**Comment by cppwfs** [comment]
SCDF currently uses Restful API revision 14 which was introduced SCDF 1.7.   This can be reviewed by curling the dataflow URL and at the bottom of the result you will see:
![image](https://user-images.githubusercontent.com/695673/167950438-fc2130d5-52f9-4dd3-9cc7-07e9513224f2.png)
This is also discussed here: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-index-response-structure.  
With that being said we probably want to add a table to the reference guide mapping DataFlow version to the revision number.

**Comment by nightswimmings** [comment]
thanks mates!!!!
