### ISSUE TITLE
Deprecate use of Gitter

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#4860]
- [x] List Gitter channel as deprecated/inactive (follow what spring-cloud-task did)
- [x] Remove references in docs (SCDF ref guide, Sagan pages, anywhere else??)
   - [x] SCDF ref guide (["2. Getting started"](https://docs.spring.io/spring-cloud-dataflow/docs/2.10.0-SNAPSHOT/reference/htmlsingle/) section)

**Comment by markpollack** [comment]
Added mention to closing the channel in the gitter channels

**Comment by onobc** [comment]
Re-opening as we still need to remove Gitter from ref guide (and any other docs it is in).
