### ISSUE TITLE
spring boot 2.5.12 does not work with SCDF 2.9.4

### ISSUE THREAD

**Issue by nvengatesan** [spring-cloud/spring-cloud-dataflow#4895]
**Description:**
I have created a simple spring boot project with 2.5.12 boot version and  created a stream project on scdf which is running on version 2.9.4 and skipper version 2.8.4

Can you please let me know which spring boot version compatibility with SCDF 2.9.4 and skipper 2.8.4

**Comment by nvengatesan** [comment]
The spring boot project on stream shows failure and it keeps restarting on scdf and the same project boot version downgraded  to 2.4.13 and it started working.

**Comment by markpollack** [comment]
Run the stream application based on boot 2.5.12 as a standalone application - outside of data flow.  You can verify this by running `java -jar myapp.jar`  Also follow the guide here to debug - https://dataflow.spring.io/docs/stream-developer-guides/troubleshooting/debugging-stream-apps/ as guidance for debugging.  Stack traces would help.  Note, that SCDF/Skipper do not care what version of Spring Boot is being used in the deployed applications.  There is likely a difference between the versions of spring boot you are using that you need to address outside of versions used in scdf/skipper itself.

**Comment by nvengatesan** [comment]
Thanks Mark. As you mentioned, the problem is with spring boot version.
