### ISSUE TITLE
Standardize Shell Commands - Display versus View

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#490]
Several shell commands are overlapping in meaning: 

* counter display
* field-value-counter display

but 

* task view
* job execution step view

Should we go with display for all of them?

**Comment by sabbyanandan** [comment]
@mminella / @cppwfs: Any specific reason as to why `task` commands have different [syntax](https://github.com/spring-cloud/spring-cloud-dataflow/blob/5f0110cf0845540c1477c29534f0bd05e46d36cc/spring-cloud-dataflow-shell/src/main/java/org/springframework/cloud/dataflow/shell/command/TaskCommands.java#L64) for listing task details? It'd be ideal to have consistent experience. What are your thoughts?
