### ISSUE TITLE
Add validation for app registration command

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#491]
As a user, I'm trying to upload a new application to dataflow-server. Though the feedback states `Successfully registered module 'app-name'`, I'm unable to use the newly registered application in stream definition. 

**Acceptance:**
- I'd like to see dataflow-server validate my registration request; if the `--uri` format is incorrect, I'd like to get alerted about the same
- I'm able to see the error message with hints to what went wrong (_eg: show an example registration command and `--uri` format_)
- I'm able to see different errors depending on `maven`, `docker`, `file`, or other URI variants

**Comment by styjdt** [comment]
I don't know if it's intended, but imho during validation also resolution of the `--uri` target should be done so that not only the format is checked, but also if the app is indeed available and valid for the intended use.

**Comment by sabbyanandan** [comment]
Addressed via spring-cloud/spring-cloud-dataflow#600
