### ISSUE TITLE
Please don't update ubuntu packages within the docker-compose

### ISSUE THREAD

**Issue by alexanderankin** [spring-cloud/spring-cloud-dataflow#4915]
**Problem description:**
The problem I'm seeing is very high cpu usage when i reboot my pc, htop says it is the containers from the getting started guide of this project.

**Solution description:**
I think the solution here is to simply not run `apt-get update` in the docker-compose file. I can submit a PR which fixes this and simply waits for the port instead of downloading a dependency to do it

**Description of alternatives:**
An alternative is to add this to the images used:

https://github.com/spring-cloud/spring-cloud-dataflow/blob/0b9ff6024c2983f63e16ab5709c697af31a0203f/src/docker-compose/docker-compose.yml#L57

https://github.com/spring-cloud/spring-cloud-dataflow/blob/0b9ff6024c2983f63e16ab5709c697af31a0203f/src/docker-compose/docker-compose.yml#L124

it seems like somehow this script already exists in this image, for instance:

https://github.com/spring-cloud/spring-cloud-dataflow/blob/0b9ff6024c2983f63e16ab5709c697af31a0203f/src/docker-compose/docker-compose.yml#L111-L120

**Additional context:**
seems like updating ubuntu packages on multiple containers detracts from the overall introductory experience

**Comment by alexanderankin** [comment]
@markpollack - i should submit a pr for this right? I could get to it within the coming week

**Comment by markpollack** [comment]
sure, basically we just need to remove `apt-get update` in the docker compose file as it is already performed when creating the base image.

**Comment by corneil** [comment]
See PR [https://github.com/spring-cloud/spring-cloud-dataflow/pull/5069](https://github.com/spring-cloud/spring-cloud-dataflow/pull/5069)

**Comment by onobc** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-dataflow/commit/50c59379d16525a1bbcb0a0058938788dd178d03
