### ISSUE TITLE
Hide sensitive data from audit dashboard after updating a stream

### ISSUE THREAD

**Issue by Hassen-BENNOUR** [spring-cloud/spring-cloud-dataflow#4947]
**Description:**
When i update a stream, local platform, sensitives data are not hidden from stream properties on the audit dashboard and displayed.
Only on update audit type.

**Release versions:**
Version: 2.9.3

**Steps to reproduce:**
Any update Stream from REST API or UI causes the passwords  from stream properties are not hidden in the audit dashboard.

**Screenshots:**
![image](https://user-images.githubusercontent.com/5323093/174032017-5847a22c-6afb-4d16-a744-e3701aba7bf3.png)

**Additional context:**
[convertPropertiesToSkipperYaml ](https://github.com/spring-cloud/spring-cloud-dataflow/blob/d9cffa39ccc6352b2ae0a31a9aa1b2287c57fccc/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamService.java#L312) must hide sensitive data

**Comment by markpollack** [comment]
thanks for pointing this out, we will address this shortly in the next point release

**Comment by markpollack** [comment]
See current usage of ArgumentSanitizer.java

**Comment by Hassen-BENNOUR** [comment]
Hi guys,
Today I've seen another service who's exposing credentials or secrets.
From the dashboard on the stream deployment page, when a stream is deployed the dashboard retrieve stream history and manifests... informations are not hidden from services responses and displayed as is.
Get Deployment History i think, I'll check, https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-stream-deployment-history
So i think that is more secure to create a http filter or a HandlerInterceptor to intercept all responses and sanitize them apart from the audit ?

**Comment by corneil** [comment]
@Hassen-BENNOUR is this the logging of the dataflow or skipper apps?

**Comment by Hassen-BENNOUR** [comment]
@corneil 
Logging of Dataflow, retrieved from skipper i think.
I've dont checked yet skipper services.

**Comment by markpollack** [comment]
fixed in https://github.com/spring-cloud/spring-cloud-dataflow/pull/4955

**Comment by Hassen-BENNOUR** [comment]
@markpollack @corneil 
The issue is not resolved in Core: 2.10.3 (Spring Cloud Data Flow Core) as you can see in screenshots below

The update stream operation still show secrets on the UI ans services

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/5323093/6b4164e3-f1d9-4581-b4c3-2872c2939352)

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/5323093/089f7b11-76ab-48fb-9625-7c765186672e)

**Comment by onobc** [comment]
Hi @Hassen-BENNOUR , thanks for the heads up. We re-opened this issue for visibility and then will now track this under https://github.com/spring-cloud/spring-cloud-dataflow/issues/5452.
