### ISSUE TITLE
SCDF not allow to create Composed Task with custom exit status for more than 2 app

### ISSUE THREAD

**Issue by szopal** [spring-cloud/spring-cloud-dataflow#4995]
Hi, 

I would like to create flow like this:

![image](https://user-images.githubusercontent.com/57896357/178689423-eaba5b69-7504-4332-b10a-338f5a2329d1.png)

But SCDF complain about duplicate application name but I have unique application in this flow:
![image](https://user-images.githubusercontent.com/57896357/178689713-e27e1fe2-0daf-44e5-aa9d-a39226180ffd.png)

And seems that SCDF not correct build flow.

**Comment by cppwfs** [comment]
Composed graph and Composed Task Runner needs to support a $END tag so that users have the ability to have a transition flow target that ends the flow.   
Something like :
app1 'mystatus' ->app2  'mystatus2' ->app 3 -> $END -> $END

**Comment by cppwfs** [comment]
This is similar to #4932 .    The solution would be the same.   So for now I'll close this as a duplicate.
