### ISSUE TITLE
Composed Task Runner does not use clientId and clientSecret in client credentials request

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow#4997]
**Description:**

Currently we are trying to get the composed task runner to work with client credentials flow to authenticated against our OAuth2 server and use this bearer token to start two described task in the compose task DSL at our SCDF server. (e.g. `task-a && task-b`) We are setting the required properties as environment variables like described here: https://dataflow.spring.io/docs/feature-guides/batch/composed-task/#client-credentials

Also we applied the environment variable "DEBUG" and set it to "ALL" in the composed task runner to get some information about the OAuth2 request

The composed task runner is also starting like expected, but the clientId and clientSecret are not in the post body of the request against the token endpoint. The TokenUri and the Scopes are used correctly as they are placed into the post request.

Because of the relaxed binding the spring application of the composed task runner should take the following properties as environment variables under consideration.

***properties as environment variables***
oauth2ClientCredentialsTokenUri > OAUTH2_CLIENT_CREDENTIALS_TOKEN_URI
oauth2ClientCredentialsScopes > OAUTH2_CLIENT_CREDENTIALS_SCOPES_0 up to OAUTH2_CLIENT_CREDENTIALS_SCOPES_5
oauth2ClientCredentialsClientId > OAUTH2_CLIENT_CREDENTIALS_CLIENT_ID
oauth2ClientCredentialsClientSecret > OAUTH2_CLIENT_CREDENTIALS_CLIENT_SECRET

***log of the composed task runner***
{"timestamp":"2022-07-13T15:36:18.321+0200","level":"DEBUG","thread":"main","logger":"org.springframework.web.client.RestTemplate","message":"HTTP POST https://tokenuri/token/","context":"default"}
{"timestamp":"2022-07-13T15:36:18.322+0200","level":"DEBUG","thread":"main","logger":"org.springframework.web.client.RestTemplate","message":"Accept=[application/json, application/*+json]","context":"default"}
{"timestamp":"2022-07-13T15:36:18.323+0200","level":"DEBUG","thread":"main","logger":"org.springframework.web.client.RestTemplate","message":"Writing [{grant_type=[client_credentials], scope=[scope1 scope2]}] as \"application/x-www-form-urlencoded;charset=UTF-8\"","context":"default"}
{"timestamp":"2022-07-13T15:36:18.484+0200","level":"DEBUG","thread":"main","logger":"org.springframework.web.client.RestTemplate","message":"Response 400 BAD_REQUEST","context":"default"}

What we would expected is in the application/x-www-form-urlencoded post body `clientId=[myCliendId]` and `clientSecret=[myClientSecret]` 

**Release versions:**
xxxxx = information cropped out
[about.txt](https://github.com/spring-cloud/spring-cloud-dataflow/files/9108600/about.txt)

The Composed Task Runner is also at version 2.9.4

**Custom apps:**
The custom apps are not required, because the composed task launcher is causing this issue before a task can be started.

**Steps to reproduce:**
Register a composed task launcher and apply the oauth2 client credentials flow properties as environment variables

**Screenshots:**
See Description

**Additional context:**
No further additional context information required.

**Comment by klopfdreh** [comment]
I think I know our issue! 😁

It is a lack of missing configuration for the ClientRegistration: https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/DataFlowConfiguration.java#L44

We need a way to configure ClientAuthenticationMethod: https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistration.java#L430

So it would be good to extend https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/properties/ComposedTaskProperties.java for a property `oauth2ClientCredentialsClientAuthenticationMethod` which can be configured with CLIENT_SECRET_POST so that the clientId / clientSecret is placed into the body.

**Comment by klopfdreh** [comment]
I am going to create a PR this afternoon.

**Comment by klopfdreh** [comment]
@jvalkeal I saw that you contributed last time to CTR - maybe you can help me out with a review? 😁

**Comment by GhaithKhmili** [comment]
Hello @jvalkeal, 
Do the clientid/secret credentials get auto refreshed ? as I am having a major issue working with CTR + Azure AD oAuth,
given that the token expires in a maximum delay of 90 mins the next CTR step execution exits on launch with a 401 unauthorized code.

**Comment by klopfdreh** [comment]
Hey @GhaithKhmili - because this is a complete different issue, I would suggest to open a new one.
