### ISSUE TITLE
SCDF depl

### ISSUE THREAD

**Issue by rgkrishnas** [spring-cloud/spring-cloud-dataflow#5027]
When i try to create pipeline and deploy i am getting the below error:
Cloud you please tell what is wrong in my setup

java --version
openjdk 11.0.15 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)

spring-cloud-dataflow-server-2.9.2.jar
spring-cloud-skipper-server-2.8.2.jar

Messaging I have RabbitMQ and running in my local

running command
ava -jar spring-cloud-dataflow-server-2.9.2.jar --spring.rabbitmq.host=127.0.0.1 --spring.rabbitmq.port=5672 --spring.rabbitmq.username=XXXXXXX --spring.rabbitmq.password=XXXXXX

Dashboard is working and streams are creating, but while deploying i am getting the below error

An error occurred
```
Could not install AppDeployRequest [[AppDeploymentRequest@d7aa850 commandlineArguments = list[[empty]], 
deploymentProperties = map['spring.cloud.deployer.appName' -> 'localfile', 'spring.cloud.deployer.group' -> 'mqttscdf'], 
definition = [AppDefinition@be59350 name = 'localfile-v1', properties = map['management.metrics.tags.application.type' -> 
'${spring.cloud.dataflow.stream.app.type:unknown}', 'spring.cloud.dataflow.stream.app.label' -> 'localfile', 
'management.metrics.tags.stream.name' -> '${spring.cloud.dataflow.stream.name:unknown}', 
'management.metrics.tags.application' -> '${spring.cloud.dataflow.stream.name:unknown}-${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}', 
'file.consumer.name' -> 'mqtt1', 'spring.cloud.dataflow.stream.name' -> 'mqttscdf', 
'management.metrics.tags.instance.index' -> '${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}}', 
'wavefront.application.service' -> '${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}-${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}}', 
'spring.cloud.stream.bindings.input.group' -> 'mqttscdf', 'file.consumer.directory' -> 'c:/temp/scdf/output', 'management.metrics.tags.application.guid' ->
```

![scdf_deploy_error](https://user-images.githubusercontent.com/5357267/180446979-c95d6c2c-1f34-424a-acb9-5d7398397527.JPG)

**Comment by jvalkeal** [comment]
We'd need to show logs from dataflow and skipper servers when you get this error.

**Comment by markpollack** [comment]
This issue is also a useful example regarding improving client error logging.  See #4839 

Closing issue now.  If you can provide the requested information, please open up a new issue with that informaiton.
