### ISSUE TITLE
Add command line args support for tasks

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#503]
When work for https://github.com/spring-cloud/spring-cloud-deployer/issues/20 is done, its wingman here needs to similar things in a shell and controllers.

**Comment by jvalkeal** [comment]
Right need to think this more for stream vs. tasks. Did some hacking locally with tasks:
```
dataflow:>task launch --name footask --arguments "--format=yyyy-MM-dd"
```
But arguments option as is doesn't really fit well with stream modules.

**Comment by cppwfs** [comment]
--params possibly (would match what we did for XD).

**Comment by jvalkeal** [comment]
Reason I went with `--arguments` is that java command as documented is:
```
java [ options ] -jar file.jar [ arguments ]
```
and this option would only add `arguments` and passing in `-D`, `-X` and other would not work.

**Comment by jvalkeal** [comment]
Anyway, I'm fine with `--params` if that's what we want. Additionally if we keep this only for tasks now and skip finding common ground for keeping things same(ish) for streams vs. task, it easy PR.

**Comment by mminella** [comment]
Given ho vital this is for tasks, are there any objections to getting this in for the task side now and address streams later?

**Comment by jvalkeal** [comment]
Common ground was just brought in by @markpollack. As task is fundamentally different than stream, I personally don't see no problem having `--params` for tasks. With streams we'd just need to have a different format as you'd need to be able to pass unique params for all modules.

**Comment by jvalkeal** [comment]
I had some trouble to rebasing PR for this issue as there was bigger changes in tasks.  We should probably do this post release as a new PR.
