### ISSUE TITLE
Move application.properties to spring-cloud-dataflow-server-local

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#504]
As a developer, I'd like to move [`application.properties`](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/resources/META-INF/applications.properties) to `spring-cloud-dataflow-server-local` project, so each deployer implementation can provide its own set of apps (_with URIs_) to bootstrap.

**Acceptance:**
Existing unit-tests run successfully

**Comment by jvalkeal** [comment]
@markfisher maybe fixing #517 at a same time?
