### ISSUE TITLE
OCI runtime exec failed: exec failed: unable to start container process: exec: "java": executable file not found in $PATH: unknown  error when i try to run spring cloud dataflow shell

### ISSUE THREAD

**Issue by tusharnitharwal** [spring-cloud/spring-cloud-dataflow#5045]
**Description:**
I tried following the dataflow install tutorial  [(https://dataflow.spring.io/docs/installation/local/docker/#using-the-shell)] and got the error "OCI runtime exec failed: exec failed: unable to start container process: exec: "java": executable file not found in $PATH: unknown". I tried this by appending bash and /bin/sh still doesn't work.

**Release versions:**
Following the tutorial for 2.9.4(latest) [https://dataflow.spring.io/docs/installation/local/docker/] which uses dataflow version 2.9.2.

**Steps to reproduce:**
[https://dataflow.spring.io/docs/installation/local/docker/]

**Screenshots:**
![image](https://user-images.githubusercontent.com/56412760/183392112-b1945bba-400f-4ffc-8135-768ed89edeb6.png)

**Additional context:**
I can't find java even when i navigate into the image using bash. Can't even find shell.jar inside the image using "find . -name shell.jar"

**Comment by gmolteni-navent** [comment]
Are you using sdkman ?

**Comment by tusharnitharwal** [comment]
> Are you using sdkman ?

no

**Comment by corneil** [comment]
https://github.com/spring-io/dataflow.spring.io/pull/459

**Comment by markpollack** [comment]
Ooops, at some point we didn't package the shell in the container.  For now we just updated the instructions where you download the uberjar and run it.  No plans to put the shell in the container image.  If incorrect, let me know @corneil

**Comment by corneil** [comment]
@markpollack no specific plans.
