### ISSUE TITLE
Update Spring Boot 2.7.3 + Spring Cloud 2021.0.3

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow#5052]
**Problem description:**
Because we require SCDF to be updated to the newest Spring Boot Version 2.7.0 due to the implementation of generating the key store based on certificates: https://github.com/spring-projects/spring-boot/commit/d387b3fa81b36f2bcc4fe0da9f3e60eceec59f22 - I wanted to ask if there is the chance to get a milestone release (M2), soon?

**Comment by onobc** [comment]
@klopfdreh we will discuss in team meeting tomorrow. I believe this is something we will want to do.

**Comment by klopfdreh** [comment]
@onobc thanks a lot! Just wanted to mention that I also raised a ticket for prometheus proxy so that the proxy server is also using Spring Boot 2.7.x: https://github.com/micrometer-metrics/prometheus-rsocket-proxy/issues/55

Just wanted to link it because SCDF uses it for task metric collection.

**Comment by markpollack** [comment]
I've been going through the issues for the general next release, but need to really trim it down for a more tactical 2.10-M2 release with only a few critical issues to get the ball rolling again.  Thanks for the comments.

**Comment by klopfdreh** [comment]
Thanks! Makes sense to me! 👍

**Comment by klopfdreh** [comment]
Hey @onobc - thanks for the Updates! 👍 

Any timeline when the M2 is going to be released?

**Comment by onobc** [comment]
No problem @klopfdreh - you are welcome. We should have that timeline locked down in the next couple of days. I will bring it up at team meeting today.

**Comment by klopfdreh** [comment]
Thank you a lot! I try to find a work around for creating a keystore as long as M2 is not released. (maybe over init containers)

**Comment by onobc** [comment]
Np @klopfdreh . If you find a workaround let us know about it. As for M2 target date... shooting for end of next week. 09/15.

**Comment by klopfdreh** [comment]
@onobc of course - I let you know if I find any.

**Comment by klopfdreh** [comment]
The only way I found is to build an image with a jdk and aws client and to store a newly created keystore as secret and to mount it inside the container.

Anyway this is a lot of overhead which makes the change of Spring Boot really nice and I am going to test M2 as soon as it is released! 👍

**Comment by onobc** [comment]
@klopfdreh you probably noticed we bumped the M2 date to next Monday. I was hoping to get it out today as I know you are looking for it. 😞  Should be good for Monday though.

**Comment by klopfdreh** [comment]
Hey @onobc - this is absolutely fine! I just expected a short delay and was surprised that it were only some days. 😃 Great to see the project in such a good spot!

**Comment by klopfdreh** [comment]
Hey @onobc - I saw all the things which are related to the scdf release - SCDF UI release, Spring Cloud Skipper release, etc. etc. thanks that you take care about that!

**Comment by klopfdreh** [comment]
Hey - thanks a lot for the release - I noticed that milestones of spring cloud are only published into `repo.spring.io` and not to `maven central repository`. We need some time to make the repo and the set of artifacts available for us, but will edit this message to tell if all is working well with `server.ssl.certificate`of Spring Boot 2.7.x
