### ISSUE TITLE
Upgrade mariadb driver to the 3.0.x series

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#5054]
https://mariadb.com/kb/en/about-mariadb-connector-j/#server-compatibility says “MariaDB Connector/J is compatible with all MariaDB and MySQL server versions 5.5.3 and later.”   This will also clear up a reported issue regarding connectivity to mysql 5.5 and sha2 based authentication

**Comment by markpollack** [comment]
looks like latest version is pulled in with boot 2.7.3.  composed task runner needs this as well as skipper

**Comment by onobc** [comment]
So 2.10 has been using the 3.x series for quite a while as it was in SB 2.6.8. I will close that as fixed and updated by the update to the latest #5056.

**Comment by onobc** [comment]
I will do the mysql/mariadb matrix verification in the scope of the other #4887
