### ISSUE TITLE
Investigate reports of slow task tab switching

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#5055]
### Description
Recently an issue was reported around a customer having slow response times when switching tabs on the task UI. We made some obvious improvements which improved the load time but customer was still seeing 1-2 minute load times. 

We need to create a test environment to attempt to reproduce this issue. If we can reproduce, then fix it. 

### TODO 
Add details around customer use case.

**Comment by FunAtWork** [comment]
Thanks for confirmation. I was wondering last few days on this issue

**Comment by onobc** [comment]
This turned out to be an issue w/ the customer's DB.
