### ISSUE TITLE
Can scdf work with spark?

### ISSUE THREAD

**Issue by xgxizz** [spring-cloud/spring-cloud-dataflow#5065]
Can this tool work with spark? If so, can you provide a simple example as a reference.

**Comment by markpollack** [comment]
Hi.  That is a pretty general question, what use-case did you have in mind?  The precursor to Spring Cloud Data Flow, Spring XD, has some integration but it was not used much so we did not continue to maintain that functionality.  See https://docs.spring.io/spring-xd/docs/current/reference/html/#spark-app    Other common use-cases that I can think of off the top of my head would be to use SCDF to store data in some format/database/system from which a Spark Job can load it up into a dataframe and do the processing in Spark.
