### ISSUE TITLE
A Task Executed with Error at Startup is never recorded

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#507]
The following task executes successfully and is `recorded` - it is eventually listed under:

`task execution list`

```
task launch scdf-batch-simple4 --properties sample.jobParams={"myStringParameter":"foobar","-secondParam(long)":"123456"}
```

But by leaving out the quote in the parameters Boot blows up during startup: 

```
task launch scdf-batch-simple4 --properties sample.jobParams={myStringParameter:"foobar","-secondParam(long)":"123456"}
```

As a result, the task is never recorded.

**Comment by sabbyanandan** [comment]
Let's retest this on Boot 2.x foundation.

**Comment by sabbyanandan** [comment]
We are recording every task execution regardless of whether or not the task starts successfully.
