### ISSUE TITLE
Support for launching Boot 3.0 apps

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#5077]
Need to look at various changes in the Boot 3.0 line

* Task/Batch schema changes [stretch-goal]
   * Use of timestamp in batch steps is a breaking change.   UI Dataflow and schema changes
   * Task and batch use sequences for mariadb and sqlserver
   * Task 3.0 & Batch 5.0 now use LocalDateTime to record start & end dates.
   * A definitive guide to breaking changes can be found here:
     * [Batch](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide)
     * [Task](https://github.com/spring-cloud/spring-cloud-task/wiki/Spring-Cloud-Task-3.0-Migration-Guide)
* Observability
   * Tracing
      * Use of prefixes will impact dataflow trace visibility
      * Other name changes could cause impact..
   * Metrics
       * Use of prefixes will affect current dataflow metrics visibility
 * Support for launching native images  [stretch-goal]
    * Docker images with native images
    * Running native images locally (Is this something we want to do)

**Comment by cppwfs** [comment]
Discuss adding ability to launch native apps.

**Comment by onobc** [comment]
The scope of this ticket was to allow SCDF to launch custom SB3 apps. It does that. The limitations have been documented https://github.com/spring-cloud/spring-cloud-dataflow/wiki/Spring-Boot-3.x-support
