### ISSUE TITLE
support for shareProcessNamespace in the Kubernetes Pod Spec

### ISSUE THREAD

**Issue by priyansms** [spring-cloud/spring-cloud-dataflow#5081]
Enhance the SCDF to launch pods with shareProcessNamespace parameter , this can help in killing the sidecar container when the task has finished execution.

**Comment by priyansms** [comment]
The changes will be needed in https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/main/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/AbstractKubernetesDeployer.java

**Comment by markpollack** [comment]
Thanks for reporting this, there is a larger story to allow for arbitrary declarative yaml to be specified vs. having to fight this long tail of container spec properties.  Will add this as an issue to fix in the next k8s deployer release.  Any interest in writing a PR for this feature?  The issue in the k8s deployer is here - https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/505
