### ISSUE TITLE
Improve test coverage for LocalDataFlowServer

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#509]
As a developer, I'd like to improve test coverage for `LocalDataFlowServer`.

**Comment by sabbyanandan** [comment]
This depends on spring-cloud/spring-cloud-dataflow#514

**Comment by ilayaperumalg** [comment]
Marking this as `invalid` as [this] (https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-local/src/test/java/org/springframework/cloud/dataflow/server/local/LocalConfigurationTests.java) test is sufficient to cover `LocalDataFlowServer`. Also, fixed the name in Javadoc with this commit https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-local/src/test/java/org/springframework/cloud/dataflow/server/local/LocalConfigurationTests.java
