### ISSUE TITLE
Improve test coverage for ModuleArgumentQualifier

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#510]
As a developer, I'd like to improve test coverage for `ModuleArgumentQualifier`.

**Comment by sabbyanandan** [comment]
This depends on spring-cloud/spring-cloud-dataflow#514

**Comment by ericbottard** [comment]
If I'm not mistaken, `ModuleArgumentQualifier` will be rendered useless once all implementations use the new deployer and we don't use the ModuleLauncher anymore.

**Comment by sabbyanandan** [comment]
If it is indeed associated with the ModuleLauncher bit, I agree it doesn't make sense. @ilayaperumalg and I discussed this. Let's see if he has other opinions.

**Comment by ilayaperumalg** [comment]
Yeah, this can be closed.
