### ISSUE TITLE
Scdf 2.9.4 jar scan

### ISSUE THREAD

**Issue by snskr** [spring-cloud/spring-cloud-dataflow#5147]
**Description:**
We noticed vulnerability for the below transitive  dependent jars with scdf 2.9.4. Can you please let us know if these jar vulnerability will be addressed in future releases? 

Apache tomcat 9.0.60
Apache commons compress 1.20
Bouncy castle 1.68
Postgresssql jdbc driver 42.2.25
Spring frameowrk 5.3.18
Spring security 5.5.5

**Release version**
2.9.4

**Custom apps:**
If your Stream or Task data pipeline includes custom apps and there is a problem associated with it, please share the sample-app (add a link to the GitHub repo) and the release versions in use. Also, please be sure to share the register, create, and deploy/launch DSL commands for completeness.

**Steps to reproduce:**
Include the steps to reproduce the behavior. Better yet, if you have a reproducible sample, please attach it in the issue. It can help us to relate to the problem more easily.

**Screenshots:**
Where applicable, add screenshots to help explain your problem.

**Additional context:**

**Comment by corneil** [comment]
@snskr Does the vulnerability also occur in 2.9.6?

**Comment by markpollack** [comment]
Out of curiosity, what software do you use for security vulnerability scanning?
