### ISSUE TITLE
scdf running locally with Podman container engine

### ISSUE THREAD

**Issue by ck-trigfb** [spring-cloud/spring-cloud-dataflow#5165]
**Problem description:**
The available system supports only Podman instead of Docker as container engine. Neither docker-compose nor podman-compose can run scdf in a way, that streams can be deployed successfully.

**Solution description:**
On suchs system without Docker often there ist an alias podman=docker available and also activated socket equivalent to the docker daemon to emulate Docker. Based on that it should be possible to run scdf with podman.

**Description of alternatives:**
No real alternative on a system without docker.

**Additional context:**
I tried different ways with docker-compose, podman-compose and also some podman play kube  scenarios but i only get scdf running to the point, where i want to deploy a stream. Dashboard hanging with the "Deploying stream" dialog. In the logfile i see some timeout.

Has anyone had any experience with podman and gotten it to work successfully with scfd? Will it be a good idea to support Podman or in generall other container engine then docker?

**Comment by onobc** [comment]
HI @ck-trigfb 

You might want to ask on StackOverflow if anyone has had success with Podman. This is not something we support or plan on supporting in the future. 

Thanks
