### ISSUE TITLE
Is SCDF supported for deployment in production on the  on-premises physical servers/vms? Could someone please provide details on this .

### ISSUE THREAD

**Issue by rupskamath** [spring-cloud/spring-cloud-dataflow#5182]

**Comment by corneil** [comment]
SCDF supports 3 deployment models.
* CloudFoundry / TAS 
* Kubernetes
* Local - Docker
* Local - Applications

All of these can run on-premises. 

CloudFoundry/TAS and Kubernetes can scale very easily as required.

The local model can use docker-compose to launch containers or execute Data Flow Server and Skipper as java daemons that will launch the stream/task applications. The message broker and database server can be hosted on a different machine if required. The local model is limited to a single machine and is only supported for batch tasks. It will not be advisable for streams, complex or cricital flows.

**Comment by rupskamath** [comment]
Thank you Corneil for the  response.                                                                                                                                                              we want to deploy batch jobs as tasks in production on the on-prem servers. Could you please answer couple of our questions below : 

1. We have requirement to deploy tasks as batch jobs in prod? Who would provide the technical or infra support for it - VmWare or OSS?

2. We have some critical batch jobs to be run on multiple machines. Is it possible to deploy an instance of Data flow server and register/run jobs from multiple machines

3. We have all the batch jobs to be launched as task applications. Do we still need Skipper to be running and , if there  is any relation/need of the Message brokers ? Could you please explain.

**Comment by corneil** [comment]
For running Batch jobs only you use DataFlow Server as the Batch Admin Console.
Setting the following will disable streams and the need for Skipper or a Message Bus.

`spring.cloud.dataflow.features.streams-enabled=false`

If you want to manage jobs on multiple servers you will need to consider CloudFoundry or Kubernetes. 
The local option is limited to operating on one machine. 
If you schedule batch tasks using cron on different machines sharing the same database then data flow server will provide visibility on the jobs but restarting will not be possible/predictable.

**Comment by rupskamath** [comment]
Thanks again Corneil for the quick response. Will take a look at this   and get back .
