### ISSUE TITLE
Task execustion view report wrong status

### ISSUE THREAD

**Issue by michael-wirth** [spring-cloud/spring-cloud-dataflow#5183]
**Description:**
The "Task executions" view shows the wrong status for RUNNING tasks. They are reported as "ERROR"/
The detail view shows the correct status as "RUNNING". The tasks run fine. No, errors in the logs.

**Release versions:**
Fails in 2.10.0 
Was ok in 2.9.6

**Screenshots:**
![2023-01-13_13-17](https://user-images.githubusercontent.com/3389626/212319709-8176dd81-581c-41c7-992a-7df85aeace22.png)

![image](https://user-images.githubusercontent.com/3389626/212320078-81c6db8f-8a1c-457c-991a-ed58cf34801d.png)

**Comment by cppwfs** [comment]
@claudiahub  Will verify that the UI is refreshing the state of the task execution list first.

**Comment by claudiahub** [comment]
On the UI we're reading the `status` property which seems to be not aligned to the model defined to the task execution list which should be `TaskExecutionStatus` as I dig into TaskDefinitionResource class. 
@cppwfs Can you please confirm this property `TaskExecutionStatus` is the correct one for the list in this page ?
Probably on UI the `status` which we're getting is inherited from the other task list view I guess.

**Comment by cppwfs** [comment]
@michael-wirth Has paymentorderloader been launched multiple times?  If so has any of the executions errored?

**Comment by michael-wirth** [comment]
@cppwfs 
Yes, the loader was started twice (because it reported the status as ERROR). Both tasks were running in parallel and succeeded without error.

The same behavior is observed with only 1 task running. I wonder where the ERROR status is coming from. It doesn't come from the backend, but status is set to ERROR in the frontend model.

![2023-01-19_09-03](https://user-images.githubusercontent.com/3389626/213388190-4222d4d0-f27c-4bc1-81ee-f6d6277e4be2.png)

![2023-01-19_09-05](https://user-images.githubusercontent.com/3389626/213388236-e96c927d-cb01-4cec-b403-bc45e69568ec.png)

**Comment by michael-wirth** [comment]
The UI seems to set status code to **ERROR** if the `exitCode` is not 0, but the task is running and the `exitCode` is not  yet set.

![2023-01-19_09-17](https://user-images.githubusercontent.com/3389626/213390008-17f94f63-4178-468b-b488-4a2f8b783265.png)
