### ISSUE TITLE
Connection is not available, request timed out after 30000ms.

### ISSUE THREAD

**Issue by Flooze-IT** [spring-cloud/spring-cloud-dataflow#5186]
**Description:**
Hi everyone,

After multiple hours on the problem, i need some help to resolve it.

We are facing on issues during our performance testing. We want to run 100 tasks in parallel through the API.

Some tasks passes (100) but the other return an error:
Unable to acquire JDBC Connection
Connection is not available, request timed out after 30000ms.

I already set a max_connections to 100 conccurent tasks but no results.

**Release versions:**
docker.io/bitnami/spring-cloud-dataflow:2.9.4-debian-11-r3

Thanks

**Comment by onobc** [comment]
Hi @Flooze-IT ,
What happens if you adjust `max_connections` a bit higher, say 110?

**Comment by Flooze-IT** [comment]
Hi @onobc 

This post résolve my issue : https://stackoverflow.com/questions/56569495/connection-timeouts-with-hikaricp

Please review your hikari setup, 100 connections per sec is a Classic use case during performance testing

**Comment by onobc** [comment]
Thanks @Flooze-IT , 
Glad you got squared away. We will leave this ticket open so that we can decide what we want to do w/ the Hikari properties we are using.

**Comment by corneil** [comment]
I believe that connectional pool and database configuration is well documented in Spring Framework documentation.
