### ISSUE TITLE
Flyway error migrating from SCDF 2.9.5 to 2.10.0

### ISSUE THREAD

**Issue by fgapito** [spring-cloud/spring-cloud-dataflow#5188]
Hi,

I'm migrating from SCDF 2.9.5 to 2.10.0.

- > Environment: Kubernetes (Openshift)
- > DB: MS SqlServer 2019 (version  15.0.42.61.1)

After the docker image version change, I'm receving this error on flywayInitializer:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: **Unsupported Database: Microsoft SQL Server 15.0**

Thank You

f.

**Comment by onobc** [comment]
Hi @fgapito 

In the version of Flyway that Boot and Dataflow use, Flyway split out their jars into separate ones for each DB (eg. [flyway-sqlserver](https://flywaydb.org/documentation/database/sqlserver#maven)). 


We accounted for this fact w/ MySQL ([here](https://github.com/spring-cloud/spring-cloud-dataflow-common/commit/9b7659a268e57465b1f627484588999cbadf8ef6)), but we missed it for SQLServer. 

We will get it added in for `2.10.1`.

In the meantime, you can follow one of these guides to add the dependency in:

* https://docs.spring.io/spring-cloud-dataflow/docs/2.10.0/reference/htmlsingle/#add-custom-driver
* https://docs.spring.io/spring-cloud-dataflow/docs/2.10.0/reference/htmlsingle/#extend-classpath

**Comment by fgapito** [comment]
Is there a way to inject the good driver without doing a maven rebuild? I would prefer to rebuild my own docker image. It could be feasible?

**Comment by onobc** [comment]
See the 2nd link above (https://docs.spring.io/spring-cloud-dataflow/docs/2.10.0/reference/htmlsingle/#_containers)

**Comment by fgapito** [comment]
> See the 2nd link above (https://docs.spring.io/spring-cloud-dataflow/docs/2.10.0/reference/htmlsingle/#_containers)

Hi,

I still didn't get how to rebuild the image starting from the already existing official image. Can you provide the official Dockerfile in order to add the missing jar? 

Thank you.

**Comment by onobc** [comment]
@fgapito 
I see where the disconnect is. That section of the ref docs is taken from the README in the source tree, and it does not mention that the example script is to be executed from `/spring-cloud-dataflow/src/templates/add-deps` directory - as that directory contains the missing `Dockerfile`.  Sorry for the confusion and back and forth.

We will get the docs update, but in the meantime, you can download https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/src/templates/add-deps/Dockerfile and put it in directory `<YOUR_WORK_DIR>`. 

Then from `<YOUR_WORK_DIR>` you should be able to do the following:

```bash
export CONTAINER_REPO="springcloud/spring-cloud-dataflow-server"
export CONTAINER_TAG="2.10.0-jdk17"
export PRIVATE_REGISTRY="our.private.registry"
export DEPS_FOLDER="./extra-libs/"
docker build -t "$PRIVATE_REGISTRY/$CONTAINER_REPO:$CONTAINER_TAG"
docker push "$PRIVATE_REGISTRY/$CONTAINER_REPO:$CONTAINER_TAG"
```

Update the above container tag and other env vars to match your reality. 

### The JAR Info
Not that you are interested in the "update the jar" approach, but If you end up looking at the "JAR" section of the https://docs.spring.io/spring-cloud-dataflow/docs/2.10.0/reference/htmlsingle/#_jar_file - it will be a bit confusing too as it also expects you reader to be in the `/spring-cloud-dataflow/src/templates/add-deps` directory. It has the `build.gradle` that does the magic etc..

**Comment by fgapito** [comment]
thank you.

At the end the thing to do is to copy missing jars here:

![image](https://user-images.githubusercontent.com/70958010/213926381-8e96b6e5-18e2-4d1c-a8a0-f12aa3c7eb62.png)

Bye

f
