### ISSUE TITLE
Add option to override binder type at application level

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#519]
As a developer, I'd like add the option to override binder type associated with stream and task application, so I can easily switch between the binders.

**Acceptance:**
- Apps with multiple binders in CP can be switched at runtime
- Includes inline property to switch binder type; _maybe: `spring.cloud.stream.bindings.<name>.binder` as the overridable property at each app level

**Comment by sabbyanandan** [comment]
This is now supported through `--binder` option while bootstrapping the Local server. For all other servers, users would have to register binder specific apps either individually or in bulk; hence, this capability is not relevant anymore.

**Comment by ilayaperumalg** [comment]
Is there any reason why this is still scoped? I think this can be closed.

**Comment by sabbyanandan** [comment]
Apart from supporting at the Local server level, we wanted to also support the application having multiple binder implementations in the CP and the ability to switch between them.

**Comment by sabbyanandan** [comment]
This can be done via application properties at the time of stream deployment. 

something like,

> stream deploy foo --properties "app.APP_NAME.spring.cloud.stream.defaultBinder=rabbit"

would deploy the app `APP_NAME` with `rabbit` as the default binder.
