### ISSUE TITLE
Replace OOTB redis with kafka apps

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#520]
As a developer, I'd like to replace OOTB `redis` with `kafka` apps as the defaults. 

**Acceptance:**
- Default OOTB [registry](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/resources/META-INF/applications.properties) include references to published `kafka` app bundle {_ex: counter-sink-kafka, http-source-kafka, .._]

This depends on spring-cloud/spring-cloud-dataflow#517

**Comment by markpollack** [comment]
I think having dataflow server startup with no applications as a default is a better option.  We need to tell the dataflow server what default binding to use when deploying apps and require passing in a location for an application catalog.  We would likely reference our 'list of all apps' for demos, but for users installing dataflow they can curate their own list.

**Comment by sabbyanandan** [comment]
We are bootstrapping servers with empty registry by default now. This is not applicable anymore.
