### ISSUE TITLE
[CI] Next dev version worker does not update parent

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#5222]
Our recent 2.10.1 release revealed an issue w/ the "Next Dev Version" CI not updating parent version properly.

See https://github.com/spring-cloud/spring-cloud-skipper/commit/f8b73611c488620b9e0e05b3970434222fb36d96

The theory is the ["allowsSnapshots=true"](https://github.com/spring-cloud/spring-cloud-skipper/blob/f8b73611c488620b9e0e05b3970434222fb36d96/.github/workflows/next-dev-version-worker.yml#L66) option is telling JFrog to look for snapshots in the resolve-release repo (`libs-milestone` rather than `libs-snapshot`).

**Comment by corneil** [comment]
Fixed when doing 2.11.0
