### ISSUE TITLE
Spring Cloud Task launch properties are not persisted

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#523]
When launching a task, launch properties are not persisted to the database. 

```
task launch scdf-batch-simple --properties sample.jobParams={"throwError":"true","-secondParam(long)":"99999999"}
```

**Comment by cppwfs** [comment]
I guess we should consider adding --params to the task launch.  Thoughts?

**Comment by cppwfs** [comment]
This is being handled by github.com/spring-cloud/spring-cloud-dataflow/issues/503.   i.e. the use of command line args via the --params.
