### ISSUE TITLE
Misalignment of spring-security-oauth2-client versions in spring-cloud-dataflow-server module

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow#5248]
**Description:**
Follow up issue of: https://github.com/spring-cloud/spring-cloud-dataflow/issues/5171

**Release versions:**
2.10.1

**Steps to reproduce:**
1. Check out spring-cloud-dataflow
2. Open the pom.xml in the subfolder spring-cloud-dataflow-server
3. Check effective-pom

**Screenshots:**
See in linked issue.

**Additional context:**
I guess the issue comes with `spring-cloud-common-security-config-core` and `spring-cloud-services-starter-config-client`. Those projects needs to be updated to use the new `spring-security` version.

**Comment by corneil** [comment]
Tracked it down to old version of `pring-cloud-services-starter-config-client` that was specified in `spring-cloud-dataflow-build`
Will be in the next release.
