### ISSUE TITLE
Simplify Carvel packages

### ISSUE THREAD

**Issue by corneil** [spring-cloud/spring-cloud-dataflow#5252]
**Problem description:**
The current carvel package contains database and message brokers that will not be used in production.

**Solution description:**
* Modify carvel package for dataflow and skipper only
* Create separate scripts to deploy database, broker and prometheus while also updating the scdf-values.yaml file.

**Comment by onobc** [comment]
Part 1 of this has been done...
The DB and broker has been removed. 

Part2 is continuing post 2.10.3 to make running this locally a good experience. 

Splitting this ticket into 2 parts so we can proceed w/ release.
