### ISSUE TITLE
JSON parse error in POST tools/parseTaskTextToGraph

### ISSUE THREAD

**Issue by Asinrus** [spring-cloud/spring-cloud-dataflow#5255]
Hello, everyone 

I created by UI a task definiton :`a: http-experiment --body='{"params": {"val1": ${val2}}'` ,where http-experiment is an application with metadata, where `--body` is setted in `org.springframework.cloud.dataflow.spring-configuration-metadata.json`.

I have an issue with a endpoint: POST tools/parseTaskTextToGraph 
I get a error:
```json
{
  "_embedded": {
    "errors": [
      {
        "message": "JSON parse error: Unexpected character ('p' (code 112)): was expecting comma to separate Object entries; nested exception is com.fasterxml.jackson.core.JsonParseException: Unexpected character ('p' (code 112)): was expecting comma to separate Object entries\n at [Source: (PushbackInputStream); line: 1, column: 39]",
        "logref": "HttpMessageNotReadableException",
        "_links": {
          "self": {
            "href": "/"
          }
        }
      }
    ]
  }
}
```
Could you say, please, it is correct behaviour?

**Additional context:**
Spring Cloud DataFlow version: 2.9.1

**Comment by corneil** [comment]
Try using `--body="{\"params\": {\"val1\": ${val2}}"

**Comment by Asinrus** [comment]
So, I didn't get a result 
I made next definition `a: http-experiment --body="{\"params\": {\"val_1\": $(val_1}}"`
I get 
```json 
{
  "_embedded": {
    "errors": [
      {
        "message": "JSON parse error: Unexpected character ('{' (code 123)): was expecting comma to separate Object entries; nested exception is com.fasterxml.jackson.core.JsonParseException: Unexpected character ('{' (code 123)): was expecting comma to separate Object entries\n at [Source: (PushbackInputStream); line: 1, column: 38]",
        "logref": "HttpMessageNotReadableException",
        "_links": {
          "self": {
            "href": "/"
          }
        }
      }
    ]
  }
}
```
Moreover, my definition was rewritten to `a: http-experiment --body='"{\"params\": {\"val_1\": ${val_1}}"'`.

**Comment by corneil** [comment]
`a: http-experiment --body="{\"params\": {\"val_1\": ${val_1}}"`
${val_1} is recursive and that is going to cause problems.
What happens with `a: http-experiment --body="{\"params\": {\"val_1\": \"value_1\"}}"`?
