### ISSUE TITLE
Failure to run cronjobs : batch/v1beta1 removed from K8s >= 1.25

### ISSUE THREAD

**Issue by satyajitbaral** [spring-cloud/spring-cloud-dataflow#5264]
**Description:**
 "The batch/v1beta1 API version of CronJob is no longer served as of v1.25."
(https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125)
So when clicking on the schedules link on the UI, it fails in the backend 

`io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.233.0.1/apis/batch/v1beta1/namespaces/development/cronjobs. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).`

**Release versions:**
image: springcloud/spring-cloud-dataflow-server:2.10.2
k8s : v1.25

**Custom apps:**
NA

**Steps to reproduce:**
Include the steps to reproduce the behavior. Better yet, if you have a reproducible sample, please attach it in the issue. It can help us to relate to the problem more easily.

**Screenshots:**
The loader on the schedules page, keeps loading perpetually 
![image](https://user-images.githubusercontent.com/23051227/227208742-4816a417-fb5c-42ca-81ad-e74a4dd3aac9.png)

**Additional context:**
Error Log

2023-03-23 11:50:16.342  WARN 1 --- [nio-9393-exec-5] i.f.k.client.internal.VersionUsageUtils  : The client is using resource type 'cronjobs' with unstable version 'v1beta1'
2023-03-23 11:50:16.452 ERROR 1 --- [nio-9393-exec-5] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

`io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.233.0.1/apis/batch/v1beta1/namespaces/development/cronjobs. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).`

**Comment by onobc** [comment]
Hi all,

This is similar to https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/529 and we are in the process of determining a course of action. Thanks for your patience.

**Comment by onobc** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/529

**Comment by satyajitbaral** [comment]
@onobc Thanks for your reply. Glad that it is being worked upon.
