### ISSUE TITLE
`springdoc.swagger-ui.config-url` displays invalid JSON

### ISSUE THREAD

**Issue by juanpablo-santos** [spring-cloud/spring-cloud-dataflow#5281]
**Description:**
which prevents it from loading SCDF's openapi contract, when swagger ui's default url is disabled. Workaround is to manually provide `springdoc.api-docs.path` to swagger UI

**Release versions:**
```json
{
  "versions": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.10.2"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.10.2"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "3.3.2"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.10.2",
      "url": "https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.10.2/spring-cloud-dataflow-shell-2.10.2.jar"
    }
  },
  "features": {
    "streams": true,
    "tasks": true,
    "schedules": true,
    "monitoringDashboardType": "NONE"
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "deployerImplementationVersion": "2.9.1",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.9.2",
      "javaVersion": "1.8.0_362",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformSpecificInfo": {
        "default": "kubernetes"
      },
      "platformType": "Skipper Managed",
      "springBootVersion": "2.7.9",
      "springVersion": "5.3.25"
    },
    "taskLaunchers": [
      {
        "deployerImplementationVersion": "2.8.2",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.8.2",
        "javaVersion": "1.8.0_362",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformSpecificInfo": {
          "namespace": "scdf",
          "master-url": "https://10.7.251.143:6443"
        },
        "platformType": "Kubernetes",
        "springBootVersion": "2.7.9",
        "springVersion": "5.3.25"
      },
      {
        "deployerImplementationVersion": "2.8.2",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.8.2",
        "javaVersion": "1.8.0_362",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformSpecificInfo": {
          "namespace": "scdf",
          "master-url": "https://10.96.0.1:443/"
        },
        "platformType": "Kubernetes",
        "springBootVersion": "2.7.9",
        "springVersion": "5.3.25"
      }
    ]
  },
  "monitoringDashboardInfo": {
    "url": "",
    "source": "default-scdf-source",
    "refreshInterval": 15
  },
  "security": {
    "isAuthentication": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  }
}
```

**Custom apps:**
N/A

**Steps to reproduce:**
given the following config:
```json
springdoc:
  api-docs:
    enabled: true
  cache:
    disabled: true
  swagger-ui:
    disable-swagger-default-url: true
```
then SCDF's `springdoc.swagger-ui.config-url` displays invalid JSON, preventing swagger-ui to load `springdoc.api-docs.path`.

**Screenshots:**
N/A

**Additional context:**
N/A

**Comment by corneil** [comment]
Shouldn't you be providing a new url when setting `disable-swagger-default-url: true`?

**Comment by juanpablo-santos** [comment]
Hi!

if not set, Springdoc provides `/v3/api-docs` as the default value for `springdoc.api-docs.path`, so that's the value that should be picked. As for your question, yes, we're providing `springdoc.api-docs.path`, our full springdoc config is something like 

```yaml
springdoc:
  api-docs:
    enabled: true
    path: /internal/openapi/v3/api-docs
  cache:
    disabled: true
  swagger-ui:
    config-url: /internal/openapi/v3/api-docs/swagger-config
    disable-swagger-default-url: true
    display-request-duration: true
    enabled: true
    path: /internal/openapi/swagger-ui.html
    show-common-extensions: true
    show-extensions: true
    url: ${springdoc.api-docs.path}
  writer-with-default-pretty-printer: true
```
Is just that setting `disable-swagger-default-url: true` is enough to trigger the issue. In our case,

* `/internal/openapi/swagger-ui.html` -> 302 to `/internal/openapi/swagger-ui/index.html`
* swagger-ui loads some js and imgs
* `/internal/openapi/swagger-ui/index.html` requests `/internal/openapi/v3/api-docs/swagger-config` which yields something like

```json
"configUrl":"/internal/openapi/v3/api-docs/swagger-config","displayRequestDuration":"true","oauth2RedirectUrl":"http://XXX.YYYY.ZZZ/internal/openapi/swagger-ui/oauth2-redirect.html","showCommonExtensions":"true","showExtensions":"true","url":"/internal/openapi/v3/api-docs","validatorUrl":"https://validator.swagger.io/validator"
```

that's an unvalid JSON, so I suspect that makes `configURL` unreadable for Swagger UI, hence `/internal/openapi/swagger-ui/index.html` remains blank, without contract. If I provide `/internal/openapi/v3/api-docs` to Swagger UI's explore bar, then I get the SCDF openapi contract and can work with it as normal.

**Comment by onobc** [comment]
I remember some special JSON handling was done in https://github.com/spring-cloud/spring-cloud-dataflow/blob/4c080be6c3f0974780520941f1365a6d16fff393/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/SpringDocAutoConfiguration.java#L94-L110 . 

Could be related.

**Comment by klopfdreh** [comment]
The SCDF backend is configured that JSON content is sent in an escaped way to the UI. All double quotes were escaped and the whole JSON was surrounded with double quotes.

The `SpringDocJsonDecodeFilter` was used to 1. unescape this content by using `StringEscapeUtils.unescapeJson(content)` and then remove the surrounding quotes with `content = content.substring(1, content.length() - 1);`

If this causes any problems please enable tracing for `SpringDocJsonDecodeFilter` and search for `Using decoded JSON for serving api-docs: ...` - if the JSON is wrong it is an issue regarding this filter, otherwise it is something else.

**Comment by klopfdreh** [comment]
I did some more investigations.

@onobc - found the issue why swagger-ui did not show the api definition when accessing /swagger-ui/index.html 😁

we have to change:
```java
if (StringUtils.hasText(content)) {
	content = content.substring(1, content.length() - 1);
}
```
to 
```java
if (StringUtils.hasText(content) && content.startsWith("\"") && content.endsWith("\"")) {
    content = content.substring(1, content.length() - 1);
}
```
if you then change the default configs to 
```yml
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    url: ${springdoc.api-docs.path}
```
the Swagger UI shows the api definition directly:

![image](https://user-images.githubusercontent.com/980773/231174744-f69bedd1-e663-4348-8b07-7270daf14954.png)

The swagger-config is then shipped correctly from the server:

![image](https://user-images.githubusercontent.com/980773/231175431-ff141c98-df91-4a97-b2c3-f5c0d0fe9bba.png)
