### ISSUE TITLE
More information about "Pre-packaged Applications" 

### ISSUE THREAD

**Issue by seonwoo960000** [spring-cloud/spring-cloud-dataflow#5285]
**Problem description:**
I wonder if there is any way we can view the "Pre-packaged Applications" source code which is decribed [here](https://dataflow.spring.io/docs/applications/pre-packaged/). It has some [documentation](https://docs.spring.io/stream-applications/docs/2021.0.1/reference/html/#spring-cloud-stream-modules-cdc-debezium-source) but it's still hard to get insight how the applications really work.  

**Solution description:**
I wonder if spring cloud data flow team can provide the source code of "Pre-packaged applications". It's a bit hard for newbies to use "Pre-packaged Applications" just by looking at the documentation. For example, I tried to use "http" stream application but I had hard time finding which endpoint I should sent request(it was by default `/` and I found it by referencing `actuator/mappings`).  

**Description of alternatives:**
If source code can not be disclosed, may be more documentation on how to use each application. 

**Additional context:**
Thank you for the great software. I enjoy using spring cloud data flow so much. Sorry if there the source code for "Pre-packaged Applications" is already open.

**Comment by corneil** [comment]
The repository for the pre-packaged stream applications can be found here: [https://github.com/spring-cloud/stream-applications](https://github.com/spring-cloud/stream-applications)
