### ISSUE TITLE
Additional Testing for launching Batch5 applications

### ISSUE THREAD

**Issue by corneil** [spring-cloud/spring-cloud-dataflow#5289]
**Problem description:**
In order to manage Batch 5 applications a separate schema is required denoted by a prefix.

**Solution description:**
Launching the application has to provide the correct prefix properties. A Batch 5 application need to properly consume the properties.
The task execution and job execution must be available in the query for jobs and tasks

**Comment by markpollack** [comment]
Base case of 1 batch job and 1 task will be covered, need more extensive tests.

**Comment by markpollack** [comment]
Corneil working on acceptance tests.

**Comment by markpollack** [comment]
When the light is green, the trap is clean!  All done.
