### ISSUE TITLE
Task Execution Builder form disappearing on the UI after first succesful execution

### ISSUE THREAD

**Issue by juanpablo-santos** [spring-cloud/spring-cloud-dataflow#5291]
**Description:**
We have an SCDF 2.10.2 instance running on a K8s cluster, with two k8s platforms defined for tasks, default (where SCDF is running) and onp (another k8s cluster). We define several custom tasks (nothing special, hello world spring cloud tasks). When we execute any task for the first time from the UI, we get the Builder/Freetext tabs with their associated forms. The tasks get executed, they finish ok, the times are registered, etc. 

Next time we try to execute the task from the UI, the Builder form has dissapeared:
![image](https://user-images.githubusercontent.com/1218530/231112948-4955317c-8421-41b8-9f1c-845aa88b81cc.png)

This only happens if the previous execution has been started on the target platform, no matter if it has ended right or not; the important bit is that this error seems to be triggered only if the task could be started on the platform on the previous execution. 

The developer console shows this up:
```
ERROR TypeError: o.builderDeploymentProperties.apps[b] is undefined
    populate http://scdf.dev.sanitas.dom/dashboard/main.beb961fc13ae703c.js:1
    populate http://scdf.dev.sanitas.dom/dashboard/main.beb961fc13ae703c.js:1
    ngOnInit/this.builder$< http://scdf.dev.sanitas.dom/dashboard/main.beb961fc13ae703c.js:1
    _next http://scdf.dev.sanitas.dom/dashboard/main.beb961fc13ae703c.js:1
    next http://scdf.dev.sanitas.dom/dashboard/main.beb961fc13ae703c.js:1
    _next http://scdf.dev.sanitas.dom/dashboard/main.beb961fc13ae703c.js:1
    next http://scdf.dev.sanitas.dom/dashboard/main.beb961fc13ae703c.js:1
    _next http://scdf.dev.sanitas.dom/dashboard/main.beb961fc13ae703c.js:1
    next http://scdf.dev.sanitas.dom/dashboard/main.beb961fc13ae703c.js:1
    notifyNext http://scdf.dev.sanitas.dom/dashboard/main.beb961fc13ae703c.js:1
    _next http://scdf.dev.sanitas.dom/dashboard/main.beb961fc13ae703c.js:1
    next http://scdf.dev.sanitas.dom/dashboard/main.beb961fc13ae703c.js:1
main.beb961fc13ae703c.js:1:48577
```
There are no related logs on the backend.

As we have to set the platform to be able to execute the task, our workaround is to select Freetext, set the `spring.cloud.dataflow.task.platformName` property manually, and then we can select the Builder tab again and we get the form back 

**Release versions:**
```json
{
  "versions": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.10.2"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.10.2"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "3.3.2"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.10.2",
      "url": "https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.10.2/spring-cloud-dataflow-shell-2.10.2.jar"
    }
  },
  "features": {
    "streams": true,
    "tasks": true,
    "schedules": true,
    "monitoringDashboardType": "NONE"
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "deployerImplementationVersion": "2.9.1",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.9.2",
      "javaVersion": "1.8.0_362",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformSpecificInfo": {
        "default": "kubernetes"
      },
      "platformType": "Skipper Managed",
      "springBootVersion": "2.7.9",
      "springVersion": "5.3.25"
    },
    "taskLaunchers": [
      {
        "deployerImplementationVersion": "2.8.2",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.8.2",
        "javaVersion": "1.8.0_362",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformSpecificInfo": {
          "namespace": "scdf",
          "master-url": "https://10.96.0.1:443/"
        },
        "platformType": "Kubernetes",
        "springBootVersion": "2.7.9",
        "springVersion": "5.3.25"
      },
      {
        "deployerImplementationVersion": "2.8.2",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.8.2",
        "javaVersion": "1.8.0_362",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformSpecificInfo": {
          "namespace": "scdf",
          "master-url": "https://10.7.251.143:6443"
        },
        "platformType": "Kubernetes",
        "springBootVersion": "2.7.9",
        "springVersion": "5.3.25"
      }
    ]
  },
  "monitoringDashboardInfo": {
    "url": "",
    "source": "default-scdf-source",
    "refreshInterval": 15
  },
  "security": {
    "isAuthentication": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  }
}
```

**Custom apps:**
Our pipelines consist of only executing a task, on the screenshot above, the associated pipeline is just `ctbl-deve-ctde0001-feature-value-2-onp`. We've been able to reproduce the issue with some `@EnableTask` and a simple bean like
```java
@Bean
public CommandLineRunner executeBatch() {
    return args -> {
        System.out.println( "HI FROM SCDF" );
    };
}
```
so it doesn't seem to be related to tasks being spring cloud tasks, happens consistently with all of our tasks after first succesful execution.

**Steps to reproduce:**
* Define at least two platforms for tasks
* Register, create and run a simple spring cloud task on the not-default platform
* Upon succesful execution on the target platform, on the next execution from the UI, the Builder section is missing (see screenshots section below)

**Screenshots:**
![image](https://user-images.githubusercontent.com/1218530/231112948-4955317c-8421-41b8-9f1c-845aa88b81cc.png)

**Additional context:**
N/A

**Comment by corneil** [comment]
This look like it belongs in `spring-cloud-dataflow-ui`

**Comment by onobc** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1915
