### ISSUE TITLE
Unable to view execution logs for tasks executing on platform != default

### ISSUE THREAD

**Issue by juanpablo-santos** [spring-cloud/spring-cloud-dataflow#5292]
**Description:**
As noted on other reports, we've an SCDF server running on a k8s cluster with 2 platforms defined for tasks, default (where SCDF is running) and onp (another k8s cluster). When we execute a task on the default cluster, we're able to see its log via UI. However, when we execute a task on the onp platform, and we request logs we get an empty screen (server logs don't show nothing):
![image](https://user-images.githubusercontent.com/1218530/231144973-3878d294-454b-444f-b026-d2f9f970cb4f.png)

To connect to the second platform we've tried to use as `clientCertData` and `clientKeyData` k8s admin credentials, but the error persists. We've also tried to create role bindings and service accounts on the target platform as noted in [here](https://dataflow.spring.io/docs/installation/kubernetes/kubectl/#create-data-flow-role-bindings-and-service-account), but that didn't help either.

**Release versions:**
```json
{
  "versions": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.10.2"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.10.2"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "3.3.2"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.10.2",
      "url": "https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.10.2/spring-cloud-dataflow-shell-2.10.2.jar"
    }
  },
  "features": {
    "streams": true,
    "tasks": true,
    "schedules": true,
    "monitoringDashboardType": "NONE"
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "deployerImplementationVersion": "2.9.1",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.9.2",
      "javaVersion": "1.8.0_362",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformSpecificInfo": {
        "default": "kubernetes"
      },
      "platformType": "Skipper Managed",
      "springBootVersion": "2.7.9",
      "springVersion": "5.3.25"
    },
    "taskLaunchers": [
      {
        "deployerImplementationVersion": "2.8.2",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.8.2",
        "javaVersion": "1.8.0_362",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformSpecificInfo": {
          "namespace": "scdf",
          "master-url": "https://10.96.0.1:443/"
        },
        "platformType": "Kubernetes",
        "springBootVersion": "2.7.9",
        "springVersion": "5.3.25"
      },
      {
        "deployerImplementationVersion": "2.8.2",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.8.2",
        "javaVersion": "1.8.0_362",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformSpecificInfo": {
          "namespace": "scdf",
          "master-url": "https://10.7.251.143:6443"
        },
        "platformType": "Kubernetes",
        "springBootVersion": "2.7.9",
        "springVersion": "5.3.25"
      }
    ]
  },
  "monitoringDashboardInfo": {
    "url": "",
    "source": "default-scdf-source",
    "refreshInterval": 15
  },
  "security": {
    "isAuthentication": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  }
}
```

**Custom apps:**
N/A

**Steps to reproduce:**
* run a simple task on k8s platform that is different to where scdf is running and, on task execution screen, press the View Log button, we come up with an empty screen (see screenshot below)

**Screenshots:**
![image](https://user-images.githubusercontent.com/1218530/231144973-3878d294-454b-444f-b026-d2f9f970cb4f.png)

**Additional context:**
N/A

**Comment by cppwfs** [comment]
The UI utilizes the current restful API that accepts an externalExecutionID and platform.   The UI does not know the platform and thus relies on the API's default which uses `default` for the platform.  The proper solution here would be to provide a new restful API that accepts the task-execution-id (something like) `/tasks/logs/?executionid=<id>`.  From this, we can obtain the external execution id and the platform from which the task was launched.  Then the proper log can be obtained.   This will require an update to the UI so that it will use the new API
