### ISSUE TITLE
Filter for task descriptions and dslText

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow#5294]
**Problem description:**

In the description we add important detailed explanations for our tasks. Sadly it is currently not possible to filter or search in this description.

![image](https://user-images.githubusercontent.com/980773/231452881-dc5622bc-f3a5-41de-a020-aecad2c25417.png)

**Solution description:**

1. Extend the "/tasks/definitions" REST endpoint.
    + Query parameter `search` should be renamed to `nameSearch`
    + New parameter `descriptionSearch` should be added

    Each time one of the filter is changed all values are collected and send to the backend.

    Example:
    + You search for name `foo` the query is changed to `/tasks/definitions?nameSearch=foo`
    + You in addition search for description `bar` the query is changed to `/tasks/definitions?nameSearch=foo&descriptionSearch=bar`

2. The UI needs to be changed and the filter icon should be added to the description column. Each time you apply a filter the query parameter should be applied as mentioned before.

**Comment by klopfdreh** [comment]
Just wanted to follow up on this ticket. Is there any way to implement it?

**Comment by klopfdreh** [comment]
Sure - I am going to have a look when I am able to provide it. It may take some time.

**Comment by klopfdreh** [comment]
Done - I create PRs.

**Comment by klopfdreh** [comment]
Can you please down port it to 2.10.4? 😁

**Comment by markpollack** [comment]
closed via https://github.com/spring-cloud/spring-cloud-dataflow/commit/b49e466cde5c90aa5110c6b8e33365513a81804f
