### ISSUE TITLE
Openshift 4.12.X (K8s 1.25), not supported by Dataflow 2.10.2 because library "Spring cloud deployer kubernetes" has v2.8.2, 2.9.X is required.

### ISSUE THREAD

**Issue by ricky-riccardo** [spring-cloud/spring-cloud-dataflow#5296]
The batch/v1beta1 API was deprecated https://docs.openshift.com/container-platform/4.12/release_notes/ocp-4-12-release-notes.html#ocp-4-12-removed-kube-1-25-apis . The latest Dataflow version no longer works because k8s > 1.24 is not supported by spring cloud deployer kubernetes in version 2.8.2.

**Comment by PSurajSharma** [comment]
Spring cloud deployer supports k8s v.125 and above from 2.9 (although this is still a snapshot). Does the team have plans on upgrading the deployers in 2.10.3 ?

**Comment by corneil** [comment]
The CronJob and BatchJob v1beta support ends with 1.25 and v1 support was introduced in 1.21
2.10.x will support k8s 1.19 to 1.24 
2.11.x will support k8s 1.21 and later
