### ISSUE TITLE
Scdf docker image from local after building scdf jar

### ISSUE THREAD

**Issue by snskr** [spring-cloud/spring-cloud-dataflow#5315]
**Problem description:**
I want to build scdf image after building scdf jar locally. Is there any dockerfile available for this?
In the dockerhub image provided , all the layered steps are jot visible any specific reason?

Thanks,
Snskr

**Comment by onobc** [comment]
Hi @snskr 
Please take a look at https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#create-containers .

**Comment by snskr** [comment]
Thanks for documentation details

**Comment by corneil** [comment]
Hi @snskr use [Paketo Buildpacks](https://paketo.io/)  to build the container images just like Spring Boot does.
You can install the `pack` cli and use:

```shell
JVM_VER=11
pack build \
          --path <path-to-jar> \
          --builder gcr.io/paketo-buildpacks/builder:base \
          --env BP_JVM_VERSION=$JVM_VER <container image repository:name:tag>
```          

Set JVM_VER to the version you require. We build containers with JDK8, 11 and 17 and tag v11 as the default for Spring Cloud Dataflow.
