### ISSUE TITLE
Unregistering multiple applications doesn't work while unregistering single application works. 

### ISSUE THREAD

**Issue by seonwoo960000** [spring-cloud/spring-cloud-dataflow#5317]
**Description:**
When I try to unregister multiple applications using group actions, it throws NPE occasionally. I looked into the stack trace and found the code which was throwing the error. 
```java
if (streamDeploymentPropertiesMap.containsKey(appName)) {
	Map<String, String> appDeploymentProperties = streamDeploymentPropertiesMap.get(streamAppName);
	if (appDeploymentProperties.containsKey(SkipperStream.SKIPPER_SPEC_VERSION)) {
		String version = appDeploymentProperties.get(SkipperStream.SKIPPER_SPEC_VERSION);
		if (version != null && version.equals(appVersion)) {
			return streamDefinition.getName();
		}
	}
}
```
`NullPointerException` is being thrown by `AppRegistryController` at line 342
- line 342: `if (appDeploymentProperties.containsKey(SkipperStream.SKIPPER_SPEC_VERSION))`

I don't have deep understanding in this code but I think `NullPointerException` is being thrown because `streamDeploymentPropertiesMap.containsKey(appName)` is not checking appropriate key(`appName`). You can see that on the next line `streamDeploymentPropertiesMap.get(streamAppName)`, `streamDeploymentPropertiesMap` is retrieving a value from different key(`streamAppName`). I wonder if this is a bug or something that should work properly. 

**Release versions:**
The version is 2.10.0 

**Custom apps:**
Not related to custom apps. 

**Steps to reproduce:**
Use dataflow version 2.10.0. 
Register multiple applications. Then unregister applications using group action. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/69591622/234592797-7d0f9cb6-2797-4a1a-8b71-b8e984fca172.png)
![image](https://user-images.githubusercontent.com/69591622/234593000-28d9bad0-7b2e-4123-a2d6-79885e4d40a6.png)
![image](https://user-images.githubusercontent.com/69591622/234593162-b62904cd-84c9-4577-8d4e-f0b29e6e80a7.png)
![image](https://user-images.githubusercontent.com/69591622/234597517-5a4aced7-04ce-4eff-83ad-bd917be5bffa.png)

**Additional context:**

**Comment by onobc** [comment]
Hi @seonwoo960000 ,

After digging in a bit further, the `appName` and `streamAppName` will always be the same as the `streamAppName` is the registered app name. It does read inconsistent though and I will make them the same variable. 

I am having trouble reproducing this. Could you give me any details about the stream app definitions you are attempting to delete in a group as well as the streams definitions that contains those apps?

**Comment by seonwoo960000** [comment]
@onobc Sure ! 😄 
I reproduced by following below steps. 
1. Import stream application starters for Kafka/Docker
![image](https://user-images.githubusercontent.com/69591622/235021795-e5be5f12-a3e8-4605-8a34-c58f31da2d23.png)
2. Apps are registered. 
3. It seems that when trying to remove `http` or `log` module by using group delete action, it returned `NPE` 

Hmm weird things is when I'm trying to reproduce this, it seems to work fine again. I'm now able to delete `http` or `log` using group actions 🤔
