### ISSUE TITLE
Snakyaml upgrade to 2.0 version

### ISSUE THREAD

**Issue by snskr** [spring-cloud/spring-cloud-dataflow#5328]
Hi Team,
We are using 2.10.0 version of scdf and we had jigh security finding  for snakyaml 1.33 version. Do you have plans to upgrade scdf to snakeyaml 2.0 version?

Thanks,
Snskr

**Comment by corneil** [comment]
Spring Boot 3 is depends on 1.33, 2.0 is not binary compatible with 2.0
We have updated our code to mitigate the specific CVE by using the safe constructors when it was first reported.
