### ISSUE TITLE
[Documentation] OOTB task / batch links are broken 

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#5336]
Need to fix all links in the following docs:

### Task App Starters project page 
On https://spring.io/projects/spring-cloud-task-app-starters many links are invalid or outdated. 

Scan the entire page and make sure all is good and up-to-date w/ latest versions. 

Here are some glaring things to fix:

```
Step 1 - Download the latest timestamp application from here [eg: /2.1.1.RELEASE/timestamp-task-2.1.1.RELEASE.jar]
```

```
Maven | https://repo.maven.apache.org/maven2/org/springframework/cloud/task/app/spring-cloud-task-app-descriptor/Elston.SR3/spring-cloud-task-app-descriptor-Elston.SR3.task-apps-maven
-- | --
Docker | https://repo.maven.apache.org/maven2/org/springframework/cloud/task/app/spring-cloud-task-app-descriptor/Elston.SR3/spring-cloud-task-app-descriptor-Elston.SR3.task-apps-docker
```
```
[Stable Release](https://repo.maven.apache.org/maven2/org/springframework/cloud/task/app/spring-cloud-task-app-descriptor/Elston.SR3/spring-cloud-task-app-descriptor-Elston.SR3.task-apps-maven-repo-url.properties)
```

### Spring Cloud Dataflow project page 

On https://spring.io/projects/spring-cloud-dataflow, the section :
```
A selection of pre-built stream and **task/batch**....
```
The link for "task/batch" needs to be adjusted to point to https://spring.io/projects/spring-cloud-task-app-starters once it has been updated and is valid (item above).

### SCDF reference guide

Fix ALL links in https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_out_of_the_box_task_applications section

**Comment by cppwfs** [comment]
The Spring Cloud Task Starters project has been archived and is no longer an active project.  In this case please use the [samples](https://github.com/spring-cloud/spring-cloud-task/tree/main/spring-cloud-task-samples) provided by Spring Cloud Task as primers on creating your own tasks.   
The Spring Cloud Task Starters project has been archived on the Spirng.io site.
