### ISSUE TITLE
[skipper] - Update statemachine to a version that is under current OSS support

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#5343]
2.5.x seems to be a simple upgrade, 3.0.x series requires more more for a future date.  2.5.x brings us up to 2023-11-11

**Comment by onobc** [comment]
Closing via https://github.com/spring-cloud/spring-cloud-dataflow/commit/d39c2220f8322b4cbb1686ad4f4d3aae2bc606ac
