### ISSUE TITLE
Batch 5 and Task 3 support - Aggregate executions

### ISSUE THREAD

**Issue by corneil** [spring-cloud/spring-cloud-dataflow#5347]
By using SQL triggers for each task execution and job execution table we can aggregate a subset of the table data along with schema target identifier. 
This will allow for browsing and paging of executions without requiring a selection of the schema target.
The aggregate resource will contain a link to retrieve task execution resource when navigating to the detail. The schema target will be an optional query parameter to task exectuion resource request in order to be backwards compatible.

**Comment by markpollack** [comment]
check wrt to lifecycle, deletion should be included.

**Comment by onobc** [comment]
Main work has been done here. There are other fine-grained issues to cover the remaining work.
