### ISSUE TITLE
Document Spring Boot 3 property differences

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#5348]
Start a separate adoc for boo3-configuration w/ initial content showing the difference between the metrics props in Boot2/3.

**Comment by markpollack** [comment]
as the server creates the properties for launch, it can look up if it is a boot 2 or 3 app based on the app registration table and filter out the properties that don't apply.

**Comment by onobc** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-dataflow/commit/184e3e236c3fe5c05c06010481055d4f07bf304b
