### ISSUE TITLE
Rename all module references with app

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#535]
As  a developer, I'd like to rename all the references of module/modules with app/application, so the use of terminology is consistent across the board.

**Acceptance:**
- shell commands should be app info, app list, app register etc.
- code references refactored 
- relevant javadocs/docs updated
- ui/flo references refactored
- rest-api's updated

**Comment by markfisher** [comment]
The current `ModuleController`, `ModuleCommands`, and `ModuleTemplate` should be renamed to `AppRegistryController`, etc.
