### ISSUE TITLE
spring-cloud-dataflow-rest-client fails to process scdf server answer on java 17/spring-boot3

### ISSUE THREAD

**Issue by GodPlsStopMe** [spring-cloud/spring-cloud-dataflow#5389]
**Description:**
After migrating to java 17/spring-boot 3 application fails with unclear error if scdf server is not available (in our case problem was with k8s ingress so attempt to access scdf server resulted with 503 code). 

logs:

> 2023-06-20T12:34:22.546+03:00  WARN 7841 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'calculationPrimaryController' defined in file [/Users/user1/IdeaProjects/test-app-application — copy/test-app/target/classes/ru/r1/r2/i1/controllers/CalculationPrimaryController.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'calculationPrimaryService' defined in file [/Users/user1/IdeaProjects/test-app-application — copy/test-app/target/classes/ru/r1/r2/i1/service/CalculationPrimaryService.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'dataFlowRequestService' defined in file [/Users/user1/IdeaProjects/test-app-application — copy/test-app/target/classes/ru/r1/r2/dataflow/client/service/DataFlowRequestService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'dataFlowTemplate' defined in class path resource [ru/r1/r2/dataflow/client/configuration/DataFlowConfiguration.class]: Failed to instantiate [org.springframework.cloud.dataflow.rest.client.DataFlowTemplate]: Factory method 'dataFlowTemplate' threw exception with message: 'org.springframework.http.HttpStatus org.springframework.http.client.ClientHttpResponse.getStatusCode()'
2023-06-20T12:34:22.547+03:00  INFO 7841 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2023-06-20T12:34:22.552+03:00  INFO 7841 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2023-06-20T12:34:22.558+03:00  INFO 7841 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2023-06-20T12:34:22.560+03:00  INFO 7841 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-06-20T12:34:22.583+03:00  INFO 7841 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger :
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-06-20T12:34:22.609+03:00 ERROR 7841 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :
***************************APPLICATION FAILED TO START***************************
Description:
An attempt was made to call a method that does not exist. The attempt was made from the following location:
    org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:54)
The following method did not exist:
    'org.springframework.http.HttpStatus org.springframework.http.client.ClientHttpResponse.getStatusCode()'
The calling method's class, org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler, was loaded from the following location:
    jar:file:/Users/user1/.m2/repository/org/springframework/cloud/spring-cloud-dataflow-rest-client/2.10.2/spring-cloud-dataflow-rest-client-2.10.2.jar!/org/springframework/cloud/dataflow/rest/client/VndErrorResponseErrorHandler.class
The called method's class, org.springframework.http.client.ClientHttpResponse, is available from the following locations:
    jar:file:/Users/user1/.m2/repository/org/springframework/spring-web/6.0.7/spring-web-6.0.7.jar!/org/springframework/http/client/ClientHttpResponse.class
The called method's class hierarchy was loaded from the following locations:
    org.springframework.http.client.ClientHttpResponse: file:/Users/user1/.m2/repository/org/springframework/spring-web/6.0.7/spring-web-6.0.7.jar
Action:
Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler and org.springframework.http.client.ClientHttpResponse
Disconnected from the target VM, address: '127.0.0.1:60992', transport: 'socket'
Process finished with exit code 1

**Release versions:**
i think error affects following rest client version spring-cloud-dataflow-rest-client-2.10.

**Steps to reproduce:**
Add spring-cloud-dataflow-rest-client-2.10.2 to your class path
create org.springframework.cloud.dataflow.rest.client.DataFlowTemplate bean
make sure yor scdf server is unavailable
try to start applucation

**Comment by markpollack** [comment]
The SCDF code base has *not* yet been upgraded to support Boot 3.  That is next on our roadmap after the 2.11.0 release.

**Comment by cppwfs** [comment]
We have begun the work on releasing SCDF 3.0 built using Spring Boot 3.3.x.   Release estimates will be coming out soon.   Stay Tuned!

**Comment by f-lopes** [comment]
Thank you!

**Comment by cppwfs** [comment]
Closing this issue.   The scheduled release date will be published on calendar.spring.io

**Comment by ArnauAregall** [comment]
Hello @cppwfs , apparently still there are no dates for a SCDF 3.x release on [calendar.spring.io](https://calendar.spring.io).

Is there any plan for it?

Thank you!

**Comment by cppwfs** [comment]
Hello @ArnauAregall, 
Stay tuned we'll be announcing something soon!
