### ISSUE TITLE
Log task never displayed due to frontend error

### ISSUE THREAD

**Issue by savra57** [spring-cloud/spring-cloud-dataflow#5396]
**Description:**
While VIEW LOG on task, the popup shows up but no log is displayed.
Noticed that there is a console error : " ERROR TypeError: Cannot read properties of undefined (reading '0') ".
Looks like the GET http://localhost:50011/tasks/logs/Task1-xyz return a string instead of a json structure.

**Steps to reproduce:**
Proceed as indicated in here : https://dataflow.spring.io/docs/batch-developer-guides/getting-started/task/
with springcloud/spring-cloud-dataflow-server: 2.11.0-SNAPSHOT

**Screenshots:**
<img width="727" alt="Screenshot 2023-07-05 at 09 49 25" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/7248977/cff568e5-e8eb-43cc-9c7d-2d63a869552a">
<img width="884" alt="Screenshot 2023-07-05 at 09 52 15" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/7248977/67a2cf00-faa8-41e9-88a4-58eef218613f">

**Comment by Grip-Jinsu** [comment]
@cppwfs Do you know if the issue is in the process of being fixed and if so, when will it be reflected?
