### ISSUE TITLE
Out of Memory Exception while clicking on "Job Execution Ids" in a task

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow#5409]
**Description:**
With those 7000 task / job executions we had a Task and when I clicked on the number beside "Job Execution Ids" an "java.lang.OutOfMemoryError" occurred.

`{"timestamp":"2023-07-21T07:00:31.855+0200","level":"INFO","thread":"https-jsse-nio-8443-exec-1","logger":"org.hibernate.engine.internal.StatisticalLoggingSessionEventListener","message":"Session Metrics {\n    17814 nanoseconds spent acquiring 1 JDBC connections;\n    0 nanoseconds spent releasing 0 JDBC connections;\n    76242 nanoseconds spent preparing 1 JDBC statements;\n    2300334 nanoseconds spent executing 1 JDBC statements;\n    0 nanoseconds spent executing 0 JDBC batches;\n    0 nanoseconds spent performing 0 L2C puts;\n    0 nanoseconds spent performing 0 L2C hits;\n    0 nanoseconds spent performing 0 L2C misses;\n    73172 nanoseconds spent executing 1 flushes (flushing a total of 1 entities and 0 collections);\n    6864 nanoseconds spent executing 1 partial-flushes (flushing a total of 0 entities and 0 collections)\n}","context":"default"}
Terminating due to java.lang.OutOfMemoryError: Java heap space`

The server is configured with 4000MiB RAM and 1500m cores.

**Release versions:**
Spring Cloud Data Flow Server 2.10.3
Spring Cloud Skipper 2.9.3

**Custom apps:**
N/A

**Steps to reproduce:**
Create a lot of task / job executions and click on the number beside "Job Execution Ids" in a Task.

**Screenshots:**
N/A

**Additional context:**
N/A

**Comment by cppwfs** [comment]
Not repeatable in 2.11.x.  Thank you @klopfdreh for verifying.

**Comment by klopfdreh** [comment]
@cppwfs - sorry that I did not close this ticket. The error is indeed not reproducible. Thanks! 👍
