### ISSUE TITLE
Kubernetes 1.21.x: CronJob API moved from v1beta1 to v1

### ISSUE THREAD

**Issue by jankeigen** [spring-cloud/spring-cloud-dataflow#5416]
**Description:**
On Kubernetes 1.21.x or OpenShift 4.12 the CronJob API moved from v1beta1 to v1. This results in an HTTP 404 when selecting the "Schedules" menu item.

Failure executing: GET at: https://172.30.0.1/apis/batch/v1beta1/namespaces/my-namespace/cronjobs. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).

**Release versions:**
2.10.3

**Steps to reproduce:**
Install SCDF on Kubernetes 1.21.x or OpenShift 4.12 and select the "Schedules" menu item.

**Screenshots:**
![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/21035840/71dfd82b-3c86-4f7b-bbec-963e39d2f311)

**Comment by onobc** [comment]
Hi @jankeigen ,

This is fixed in the upcoming `2.11.0` release. We are aiming for an RC candidate w/in the next week. Feel free to try `2.11.0-SNAPSHOT` from repo.spring.io until then. 

Thanks

Closing in favor of https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/529

**Comment by sampathsri** [comment]
We tried to upgrade the scdf version to solve the above issue, but its not working. I build the latest scdf version with oracle dependency. I am using oracle db and the application is not able to load data from the custom datasource. Rather it tries to get from default schema. See the error below. 

2023-10-05 14:49:50.496 DEBUG 1 --- [nio-8080-exec-9] org.hibernate.SQL : select appregistr0_.id as id1_0_, appregistr0_.object_version as object_version2_0_, appregistr0_.boot_version as boot_version3_0_, appregistr0_.default_version as default_version4_0_, appregistr0_.metadata_uri as metadata_uri5_0_, appregistr0_.name as name6_0_, appregistr0_.type as type7_0_, appregistr0_.uri as uri8_0_, appregistr0_.version as version9_0_ from app_registration appregistr0_ where appregistr0_.default_version=1 order by appregistr0_.name asc fetch first ? rows only

2023-10-05 14:49:50.527 DEBUG 1 --- [nio-8080-exec-9] o.h.engine.jdbc.spi.SqlExceptionHelper : could not extract ResultSet [n/a]
java.sql.SQLSyntaxErrorException: ORA-00904: "APPREGISTR0_"."BOOT_VERSION": invalid identifier

**Comment by onobc** [comment]
HI @sampathsri thanks for the report. We will prioritize looking into this. Let's track this under the other ticket you created  https://github.com/spring-cloud/spring-cloud-dataflow/issues/5497

**Comment by onobc** [comment]
Thanks for the follow up @sampathsri . I created a new issue based on your feedback. We will investigate.
