### ISSUE TITLE
Minimal docs for users to try out boot2/boot3 deployments for RC1

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#5420]
More expansive docs will come in the 2.11 GA release.

Add a section in the reference guide and for the release we put that in the docs on dataflow.spring.io

**Comment by guillaumesmo** [comment]
Would be very nice indeed to have a pointer on how to launch boot3 tasks!

 I've been trying to play with properties like `spring.cloud.task.schemaTarget=boot3` and table prefixes, but they always get overridden and always appear as boot2 executions.

However, running the batch outside of SCDF against the SCDF database with the following properties worked:
```
spring.batch.jdbc.table-prefix=BOOT3_BATCH_
spring.cloud.task.initialize-enabled=false
spring.cloud.task.table-prefix=BOOT3_TASK_
```

**Comment by onobc** [comment]
We have added this in the "Getting Started" section https://docs.spring.io/spring-cloud-dataflow/docs/2.11.0-SNAPSHOT/reference/htmlsingle/#getting-started that links to the SB3 page here https://docs.spring.io/spring-cloud-dataflow/docs/2.11.0-SNAPSHOT/reference/htmlsingle/#appendix-boot3
