### ISSUE TITLE
Could not resolve dependencies  io.spring.docresources:spring-doc-resources:zip:0.2.5 was not found in https://repo.maven.apache.org/maven2 

### ISSUE THREAD

**Issue by mudduvenkatesh** [spring-cloud/spring-cloud-dataflow#5430]
**Description:**
 Failed to execute goal on project spring-cloud-dataflow-docs: Could not resolve dependencies for project org.springframework.cloud:spring-cloud-dataflow-docs:jar:2.10.3: io.spring.docresources:spring-doc-resources:zip:0.2.5 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Release versions:**
10.3

**Custom apps:**

**Steps to reproduce:**
mvn package -DskipTests

**Screenshots:**
Where applicable, add screenshots to help explain your problem.

**Additional context:**

**Comment by mudduvenkatesh** [comment]
Thank you for the information. Do you want me to update the pom with the below?
Regards


From: Corneil du Plessis ***@***.***>
Date: Monday, August 7, 2023 at 12:01 PM
To: spring-cloud/spring-cloud-dataflow ***@***.***>
Cc: Venkatesh Muddu ***@***.***>, Author ***@***.***>
Subject: Re: [spring-cloud/spring-cloud-dataflow] Failed to execute goal on project spring-cloud-dataflow-docs: Could not resolve dependencies for project org.springframework.cloud:spring-cloud-dataflow-docs:jar:2.10.3: io.spring.docresources:spring-doc-resour...

After the time of the release there were changes to the permissions on repo.spring.io
The spring-cloud-dataflow-docs module has the following section for asciidoc:

<plugin>

    <groupId>org.asciidoctor</groupId>

    <artifactId>asciidoctor-maven-plugin</artifactId>

    <version>2.2.4</version>

    <dependencies>

        <dependency>

            <groupId>io.spring.asciidoctor.backends</groupId>

            <artifactId>spring-asciidoctor-backends</artifactId>

            <version>0.0.5</version>

        </dependency>

    </dependencies>

    <configuration>

        <sourceDirectory>${project.build.directory}/refdocs/</sourceDirectory>

        <outputDirectory>${project.build.directory}/generated-docs</outputDirectory>

        <sourceDocumentName>index.adoc</sourceDocumentName>

        <imagesDir>.</imagesDir>

        <doctype>book</doctype>

        <attributes>

            <icons>font</icons>

            <allow-uri-read>true</allow-uri-read>

            <attribute-missing>warn</attribute-missing>

            <project-version>${project.version}</project-version>

            <project-artifactId>${project.artifactId}</project-artifactId>

            <version-type-lowercase>${version-type-lowercase}</version-type-lowercase>

            <snippets>${basedir}/../spring-cloud-dataflow-classic-docs/target/generated-snippets</snippets>

            <skipper-version>${spring-cloud-skipper.version}</skipper-version>

            <skipper-version-type-lowercase>${skipper-version-type-lowercase}</skipper-version-type-lowercase>

            <skipper-branch-or-tag>${skipper-branch-or-tag}</skipper-branch-or-tag>

            <github-tag>${github-tag}</github-tag>

            <local-server-image-tag>${local-server-image-tag}</local-server-image-tag>

            <scdf-core-version>${org.springframework.cloud:spring-cloud-dataflow-core:jar.version}</scdf-core-version>

            <cf-deployer-branch-or-tag>${cf-deployer-branch-or-tag}</cf-deployer-branch-or-tag>

        </attributes>

    </configuration>

    <executions>

        <execution>

            <id>generate-html5</id>

            <phase>prepare-package</phase>

            <goals>

                <goal>process-asciidoc</goal>

            </goals>

            <configuration>

                <backend>spring-html</backend>

                <sourceHighlighter>highlight.js</sourceHighlighter>

                <doctype>book</doctype>

                <attributes>

                    <docinfo>shared</docinfo>

                    <stylesdir>css/</stylesdir>

                    <stylesheet>spring.css</stylesheet>

                    <linkcss>true</linkcss>

                    <icons>font</icons>

                    <highlightjsdir>js/highlight</highlightjsdir>

                    <highlightjs-theme>github</highlightjs-theme>

                </attributes>

            </configuration>

        </execution>

    </executions>

</plugin>

**Comment by onobc** [comment]
Hi @mudduvenkatesh ,
Sorry it took us a while to get back w/ you - we were all busy w/ Spring One. 

To follow up, the changes @corneil listed above were made in [main](https://github.com/spring-cloud/spring-cloud-dataflow/blob/0bfe5525ce0b249ac6642b0c8408f2a7c74847d0/spring-cloud-dataflow-docs/pom.xml#L123) but not in [2.10.x](https://github.com/spring-cloud/spring-cloud-dataflow/blob/d1b86118763b536910010b38039b114bf591a51e/spring-cloud-dataflow-docs/pom.xml#L138). 

> Thank you for the information. Do you want me to update the pom with the below?

I believe that is the workaround for now if you want to build/run the repo locally. We will likely add this to the `2.10.x` branch but am not sure where we will release a `2.10.4`.

**Comment by onobc** [comment]
Backported to 2.10.x in https://github.com/spring-cloud/spring-cloud-dataflow/pull/5448.
