### ISSUE TITLE
Why do I get the error: Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.spring:timestamp-task:jar:2.0.2 from/to springRepo (https://repo.spring.io/libs-snapshot): status code: 401

### ISSUE THREAD

**Issue by djangofan** [spring-cloud/spring-cloud-dataflow#5432]
I get this error: **Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.spring:timestamp-task:jar:2.0.2 from/to springRepo (https://repo.spring.io/libs-snapshot): status code: 401**

Here is my configuration.   Not sure why this happens:
https://github.com/djangofan/spring-cloud-data-example-0

Why is it trying to download a (non-accessible) SNAPSHOT instead of a publicly available release file?

**Comment by djangofan** [comment]
Thanks, that fixed the dependency error!  

BUT, when i create a task, such as a simple timestamp task , in the GUI,  I get this:
Caused by: java.lang.IllegalArgumentException: Invalid TaskExecution, ID 3 not found
	at org.springframework.util.Assert.notNull(Assert.java:201) ~[spring-core-5.3.23.jar!/:5.3.23]
	at org.springframework.cloud.task.listener.TaskLifecycleListener.doTaskStart(TaskLifecycleListener.java:276) 

Maybe it's possible i have a database config issue.  I'll look into it after work today.

**Comment by onobc** [comment]
Hi @djangofan ,

Glad the bump got you past the dependency error. 

In your example repo, I see you are starting H2 manually and configuring it in (`application.properties`). By default, when running SCDF / Skipper locally - they will auto-configure and start the H2 embedded DB. I am guessing you know this and are using H2 as an actual DB. If so, we do not claim to support using H2 as a standalone DB (although it should work fine if configured properly). Most likely this is a DB config issue at this point. I am not sure exactly what you are doing in the example w/ the `*.lock.db` and `*.mov.db`. 

I did the following and all worked well:
```
curl -LO https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-server/2.10.3/spring-cloud-dataflow-server-2.10.3.jar

curl -LO https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-skipper-server/2.9.3/spring-cloud-skipper-server-2.9.3.jar

rabbit-start='docker run -d --hostname rabbitmq --name rabbitmq -p 15672:15672 -p 5672:5672 rabbitmq:3.12.2-management '

java -jar spring-cloud-dataflow-server-2.10.3.jar

java -jar spring-cloud-skipper-server-2.9.3.jar
```
I then registered the Maven task apps and created and launched the timestamp task. 

> Did you test it, booted from scratch?

Yes, we have integration tests for this scenario.


### Other Notes
I am curious why you are using H2 as an external DB. Any reason not to use MariaDB (or MySQL)?

Its as simple as - start MariaDB:
```
docker run --name test-mariadb -d -p 3306:3306 -e MARIADB_ROOT_PASSWORD=pass -e MARIADB_USER=user -e MARIADB_PASSWORD=user -e MARIADB_DATABASE=dataflow mariadb:10.4.22'
```
and then one of the following to run the server:
```
java -jar spring-cloud-dataflow-server/target/spring-cloud-dataflow-server-2.10.3.jar \
    --spring.datasource.url=jdbc:mariadb://localhost:3306/dataflow \
    --spring.datasource.username=user \
    --spring.datasource.password=pass \
    --spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
```
OR
```
SPRING_DATASOURCE_URL=jdbc:mariadb://localhost:3306/dataflow
SPRING_DATASOURCE_USERNAME=user
SPRING_DATASOURCE_PASSWORD=pass
SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver

java -jar spring-cloud-dataflow-server/target/spring-cloud-dataflow-server-2.10.3.jar
```
OR put the props in your application.properties as you are doing currently but w/ the above values.

See [here](https://docs.spring.io/spring-cloud-dataflow/docs/2.10.3/reference/htmlsingle/#configuration-local-rdbms) for more info on configuring the local DBs.

**Comment by djangofan** [comment]
Ah, that might explain why H2 was sorta working for me.  Right before I defined my H2 db as being in file mode, I had it in `mem` mode and i had different results.    I can see what you mean, by it workig embedded.    I bet your support for "embedded mode" is why i was seeing it trying to connect, by default, to H2 `mem`.

**Comment by onobc** [comment]
> Ah, that might explain why H2 was sorta working for me. Right before I defined my H2 db as being in file mode, I had it in `mem` mode and i had different results. I can see what you mean, by it workig embedded. I bet your support for "embedded mode" is why i was seeing it trying to connect, by default, to H2 `mem`.

Yeh, that looks like what it was doing.

> 
> It might help to clarify this stuff in your documentation?

Its in there at https://docs.spring.io/spring-cloud-dataflow/docs/2.10.3/reference/htmlsingle/#_h2

**Comment by djangofan** [comment]
Finally got it working.   Here is my updated repo:  https://github.com/djangofan/spring-cloud-data-example-0

THANKS!

**Comment by djangofan** [comment]
Done

**Comment by onobc** [comment]
> Not sure why, but each task I run, gets run twice, as if there are 2 threads?

So far I see you have created a stream - when you say task, do you mean a task (short-lived application) such as timestamp-task? If not, can you explain "each task I run" and also paste the log output at the time would be helpful.
