### ISSUE TITLE
SCDF 2.11.0-RC1 composed task runner documentation

### ISSUE THREAD

**Issue by vauvenal5** [spring-cloud/spring-cloud-dataflow#5441]
**Problem description:**
When I start a composed task containing boot 3 / batch 5 tasks. The composed task is stuck after the first task. I believe this is due to the composed task runner itself being started with schema-target boot2. However, I was not able to find any documentation on how to configure the composed task runner properly.

**Solution description:**
Can you provide an example or better documentation on how the composed task runner is to be user in context of boot 3 / batch 5 tasks?

**Comment by klopfdreh** [comment]
You can see the schema when ever a task is launched - in the intended column for this.

We had issues with a stuck CTR when we switched to entry point boot instead of entry point shell.

can you have a look if you have two entries for the CTR in the UI?

**Comment by cppwfs** [comment]
There are no doc changes required for the creation or execution of CTR.   However, for app registration, you must choose the correct boot version for the application.   I'll add a note mentioning this.   

One question, did the first task start and complete successfully?

**Comment by vauvenal5** [comment]
Hi! So, here are a few additional inputs from our side.

We imported the timestamp-batch-task:3.0.0.
![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/1935503/23d7f6b8-7ed5-4f9b-aee6-3e22270ae651)

Composed it as two tasks one after the other:
![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/1935503/2d147302-df6a-42e1-b86b-9fb2af165779)

Entrypoint exec works out well but entrypoint shell does not:
![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/1935503/fc8d5747-2e0f-48e1-979c-bcc953b18ef9)

Behavior of the shell-entrypoint execution is that the CTR just blocks:
![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/1935503/144c3b66-49ac-4890-aeb1-a98e27462b03)

If you need some more information we will try to provide it.

**Comment by radish172521** [comment]
Hi, I would like to know how to decide to use Schema Target? Why I am registering with springboot3, and when I run it, it still shows Schema Target= boot2
![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/12545332/11f6102b-ae73-4199-9633-0d389366f232)
