### ISSUE TITLE
feat: task cleanup before end time in days

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow#5442]
**Problem description:**
Because we have a high throughput of tasks we need to clean task applications that are older than n days to preserve only the last executions.

**Solution description:**
See: https://github.com/spring-cloud/spring-cloud-dataflow/pull/5422

**Description of alternatives:**
N/A

**Additional context:**
N/A

**Comment by onobc** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-dataflow/commit/af60a25693e9c7d302cdc9c6fcd2e6297cbb0a34
