### ISSUE TITLE
Add tests to the spring-cloud-dataflow-aggregate-task module

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#5446]
We need to add tests as there are none in place in the newly added module `spring-cloud-dataflow-aggregate-task`.

**Comment by corneil** [comment]
The tests for this is part of spring-cloud-dataflow-server-core since some of the components needed are added by the consumer of this module.

**Comment by onobc** [comment]
Got it. Let's add this to a README.md in this module or put a placeholder test that simply says "See xyz for tests".
