### ISSUE TITLE
OOTB sftp app goes into unrecoverable state w/ bad SpEL property.

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#5461]
See SO thread for details: https://stackoverflow.com/questions/77089509/stream-deployment-properties-are-being-locked-after-a-deployment-with-errors

Figure out if this is a SCDF issue or just an issue w/ the particular app.

**Comment by ilayaperumalg** [comment]
Closing this as the potential fix is at the app configuration level based on the response to the SO question.
