### ISSUE TITLE
Shell: Display Job Instannce Id

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#547]
When listing job executions, we should also display the `job instance id`. Otherwise how would users be able to use the shell command?:

`job instance view --id <job-instance-id>`

**Comment by ilayaperumalg** [comment]
The job command `job execution display --id <job-execution-id>` displays the job instance id and that can help user navigate the instance id. Hence, this can be closed as `invalid`.
