### ISSUE TITLE
TaskOperations launch API is not backwards compatible

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#5492]
Currently the TaskOperations has a single launch API that calls to the (new in 2.11) `task/executions/launch` which ultimately implies you must be running SCDF 2.11.x. 

As such, users can not use a 2.11 client (TaskOperations.launch) against a 2.10 server. 

See sample changes in https://github.com/spring-cloud/spring-cloud-dataflow/compare/main...onobc:spring-cloud-dataflow:cbono-WIP-tasklaunch?expand=1

**IMPORTANT**: Also, are there any other APIs that have the same problem?

**Comment by cppwfs** [comment]
We can use the dataFlowServerVersion in the TaskTemplate to determine which API call to use.

**Comment by onobc** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-dataflow/commit/ea0157afb7a665c5db7ea0bc5fe03cbb8ad9d3ef
