### ISSUE TITLE
Relaunch of a Spring Boot 3/Spring Batch 5 batch doesn't work properly.

### ISSUE THREAD

**Issue by khaeghar** [spring-cloud/spring-cloud-dataflow#5518]
**Description:**
When relaunching a failed execution of a Spring Boot 3/Spring Batch 5 batch, it doesn't relaunch properly. Instead, it creates a new JobInstance and starts all over again. It also sends some weird JobExecutionParams that we are not entirely understanding, where the run.id appears multiple times with different type of values and many of our arguments are also duplicated.

Note that we are using an RunIncrementerId in our jobs.

**Release versions:**

2.11.X

**Steps to reproduce:**

The steps are:

1. Create a job that fails in a chunk step.
2. Try to restart it.

**Screenshots:**

The Job_Executions. The one we are launching first and making it fail is the number 54.

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/21831496/ec9de3a0-a68d-4af7-a251-7470249881e8)

These are the arguments sent and recorded in the database:

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/21831496/f31cbf79-0e55-475a-a357-ba60a3d312ea)

After it fails, we relaunch, and we see these arguments:

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/21831496/2fe6be29-cec4-4394-9a41-41c92e699ec6)

And the new created JobInstance:

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/21831496/3faabeba-4bf1-4c8b-909e-8c5b916d7694)

Which makes the newly restarted job not being able to pick up the execution where it left it.

**Additional context:**

Relaunch in Spring Boot 2 version works, our jobs didn't have any problem with that, saving the arguments correctly for the future relaunches:

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/21831496/5fa104a2-d46a-43f1-b0a5-ef147293fa24)

It stays the same throughout the executions, while with Spring Boot 3 doesn't.

----

While debugging and trying to relaunch a SB3 job, we see that in this method

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/21831496/d54a8fee-39bd-4cb3-af9c-4bafb60a178b)

When mixing up the task params and the job params, it gets the run.id as a long:

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/21831496/54afffc8-2522-4c39-b556-b17cb3b973b8)

But then it appears as a double in the database:

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/21831496/baa952bb-fb82-4821-adbc-308ac484890c)

In case this helps identifying why this happens.

**Comment by khaeghar** [comment]
Sure.

The main point would be the Customer Collector step, with the processor that receives the parameter in order to fail when it is necessary.

We set that to 12, so when the chunk size is set to 11, it fails at the first chunk, then stops the execution, and then the restart kicks and finish correctly.

It has some config issues because I wasn't able to get it up with the JobRepository configuration. Hope that with this sample helps to see the picture.

[demo.zip](https://github.com/spring-cloud/spring-cloud-dataflow/files/13069281/demo.zip)

**Comment by khaeghar** [comment]
Yes, both, launched from SCDF and yes, we do use Spring Task. Forgive me for not giving this information earlier.

**Comment by cppwfs** [comment]
Just verifying, because the sample does not contain a task dependency

**Comment by khaeghar** [comment]
We use the dependency just to register the info in the Tasks database and be able to launch the task via SCDF. Shouldn't impact the sample, but I can add it if necessary.

Thanks for taking a look into this!

**Comment by DeividasJakovlevas42** [comment]
I also have the same issue and would like to know how to solve it. Long and Integer parameters are changed to double and it ruins job restarts.

**Comment by khaeghar** [comment]
Did you take a look into this?

**Comment by cppwfs** [comment]
Resolved with https://github.com/spring-cloud/spring-cloud-dataflow/commit/3c8d6c07f26bcf50d412333698f3861e962f7ffe

Thank you for reporting!
