### ISSUE TITLE
About using SCDF 2.11.x, How to make boot3 as Default?

### ISSUE THREAD

**Issue by DolphaGo** [spring-cloud/spring-cloud-dataflow#5519]
Before I ask, I apologize for asking this question without a deep understanding. but it would be helpful if you could answer it.

When i installed scdf 2.11.0 by using helm with flyway, 39 tables were created.

And I could see BOOT3_ prefixed 16 tables (Batch 5.x) / Batch tables 16 tables (Batch 4.x) 

<img width="1703" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/37108728/3559051f-4e24-4427-8e5b-e4c3ebe3bd45">

The 2.11.0 version is for the Batch 5 version, but I'm wondering why you divided it into Boot3_. It doesn't default to boot3, and it doesn't seem to work well even though I've specified the table-prefix separately in the application as follows. How do I set it to default to boot3?

<img width="1033" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/37108728/1962cf11-0181-44c7-8661-791f1593483f">

- https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_spring_cloud_task_batch_applications

> My Application Setting

Default is TASK_, BATCH_ Prefix, So i changed prefix like 

```yaml
spring:
  cloud:
    task:
      table-prefix: BOOT3_TASK_
  batch:
    jdbc:
      table-prefix: BOOT3_BATCH_
```

<img width="1164" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/37108728/c7dc2135-f737-4cb2-a715-009b9519bd10">

I know I should set boot3 as the default, but where can I set it?

**Comment by onobc** [comment]
Hi @DolphaGo ,
In the next one or two patch releases we will be setting Boot3 apps as the default, but for now you can go into each registered app and choose manage versions

The application registration is what controls the boot version. If you only have a boot2 based task app registered - it will always use boot2. If you instead registerd a boot3 based task app - it will always use boot3. When there are 2 versions of the task/app (one boot2 and one boot3) then you can select the app in the "Applications" view and then choose "Manage versions" and it will allow you to set the default. Also, when launching the task you have an option to pick the version of the task app that is boot2/3 (when there are > 1 versions).

Try this to experiment: 
1. Install SCDF w/ default boot2 based apps
2. Navigate to the Applications view and add apps via properties file, pasting the following into the text area (screenshot below). At this point you will notice there is a little superscript "2" on the version column. 
3. Select the app and choose "Manage Versions"
    ```
    task.timestamp=maven://io.spring:timestamp-task:3.0.0
    task.timestamp.bootVersion=3
    task.timestamp-batch=maven://io.spring:timestamp-batch-task:3.0.0
    task.timestamp-batch.bootVersion=3
    ```
4. Select the boot3 app as the default.
5. Create and launch the task - you will see that you can select the version of the app at this point as well.

I hope this helps. Let us know. 

<img width="1236" alt="Screen Shot 2023-10-19 at 08 50 37" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/28907971/facf6f86-3df9-48ef-beaa-723e064f867b">

<img width="1484" alt="Screen Shot 2023-10-19 at 08 54 01" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/28907971/a4f35f52-85a5-4561-8894-56efe7b347f7">

<img width="1199" alt="Screen Shot 2023-10-19 at 08 54 12" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/28907971/3076a390-ded5-417e-a1a3-04bc7db45ae5">

**Comment by DolphaGo** [comment]
@onobc 

Thank you for your kind response.

I see you meant to register for the application.

<img width="1909" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/37108728/7d54f8c3-7a54-428c-868d-b553a2f6fc05">

My Application is SpringBoot3(SpringBatch5), but Task scheme target indicates boot2.

<img width="1909" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/37108728/1b91b8b1-582a-4817-8456-94a339caa76c">

Do you know why it looks like this?

**Comment by cppwfs** [comment]
When your registered that application, did you specify Boot3?  For example:
<img width="1507" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/695673/c7c9d8e3-d48c-4bcd-8925-94b03b758a7a">

**Comment by DolphaGo** [comment]
@cppwfs 

<img width="866" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/37108728/3b12fad1-867c-4e40-b50b-dffd7750467d">

Umm, Yes.

The problem seems to be in `Application -> Batch DB`. Not `Batch DB <- SCDF`

Because application is not running properly.

<img width="1535" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/37108728/18952bc5-7aa1-4166-bf38-e33ec5a50482">

Let me check more. Thanks.

**Comment by DolphaGo** [comment]
When I install the application as dataflow.spring.io, boot 2 seems to be the default, will this be reflected as boot 3 in the next release?

<img width="1346" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/37108728/50001895-7b78-44f2-a4e4-89bcd77e424f">


<img width="1452" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/37108728/1d3529de-4a49-4a2c-a83a-abf17053a748">

**Comment by onobc** [comment]
Hi @DolphaGo,
We are working on the release of the stream applications version `4.0.0 / 2022.0.0` (based on boot3x) in order to make the apps the default. The timing should line up so that we can make 3.x the default in the next release - that is the goal.

**Comment by Gunthervg** [comment]
We have a weird issue with this. 
Registered application as Spring Boot 3.x, when launching the task it is using the BOOT3_TASK_SEQ to determine the next number but it uses the task_execution (boot2) table which has an overlap:

`Caused by: java.lang.IllegalArgumentException: Invalid TaskExecution, ID 210 task is already complete
	at org.springframework.util.Assert.isNull(Assert.java:164) ~[spring-core-6.0.12.jar:6.0.12]
	at org.springframework.cloud.task.listener.TaskLifecycleListener.doTaskStart(TaskLifecycleListener.java:277) ~[spring-cloud-task-core-3.0.3.jar:3.0.3]
	at org.springframework.cloud.task.listener.TaskLifecycleListener.start(TaskLifecycleListener.java:411) ~[spring-cloud-task-core-3.0.3.jar:3.0.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179) ~[spring-context-6.0.12.jar:6.0.12]
	... 12 more`

We can fix this by setting the boot3_seq 10000 higher but that is just a quickfix.

**Comment by cppwfs** [comment]
This could indicate that the `BOOT3_TASK_EXECUTION` may have the 210 entry there already.  Could you verify?  
If not, can you share the properties (cleansed of sensitive information) used to launch the task?

**Comment by Gunthervg** [comment]
@cppwfs  so I set the BOOT3_TASK_SEQ to + 100 000, now we receive this error:

```
Caused by: java.lang.IllegalArgumentException: Invalid TaskExecution, ID 100219 not found
	at org.springframework.util.Assert.notNull(Assert.java:204) ~[spring-core-6.0.12.jar:6.0.12]
	at org.springframework.cloud.task.listener.TaskLifecycleListener.doTaskStart(TaskLifecycleListener.java:275) ~[spring-cloud-task-core-3.0.3.jar:3.0.3]
	at org.springframework.cloud.task.listener.TaskLifecycleListener.start(TaskLifecycleListener.java:411) ~[spring-cloud-task-core-3.0.3.jar:3.0.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179) ~[spring-context-6.0.12.jar:6.0.12]
	... 12 more
```

In BOOT3_TASK_EXECUTION we see this record:
![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/4334012/2c056e1c-cdfd-437d-a5d0-9d7385270d3e)

Here are the properties we set in SCDF before run:

```
pring.cloud.dataflow.task.platformName=
app.devops-patient-topic-populate2.spring.profiles.active=qa
deployer.devops-patient-topic-populate2.kubernetes.volumeMounts
deployer.devops-patient-topic-populate2.kubernetes.volumes=
deployer.devops-patient-topic-populate2.kubernetes.init-container=
```

**Comment by Gunthervg** [comment]
@cppwfs we managed to find a temporary workaround:

```
public class PlatformTaskConfigurer extends DefaultTaskConfigurer {

    public PlatformTaskConfigurer(final DataSource dataSource) {
        super(dataSource,"BOOT3_TASK_", null);
    }

}
```

**Comment by Gunthervg** [comment]
@cppwfs  did you find a solution yet?

**Comment by cppwfs** [comment]
Hello @Gunthervg Thank you for checking in.  Could you create a new issue with the information you provided?   It would be useful if you could provide a sample task app that reproduces the problem.

**Comment by younsl** [comment]
I am also experiencing a similar problem when running composed-task.

When I ran an individual task, it runs normally as `boot3`, but when a composed-task consisting of two `boot3` tasks, there is a problem where it runs as the `boot2` version.

Opened issue #5538 regarding this problem.

**Comment by DolphaGo** [comment]
Hello, I'll try to answer the questions I asked. (about boot3 applications)

> When I import the application as dataflow.spring.io, boot 2 seems to be the default, will this be reflected as boot 3 in the next release?
> 
> <img alt="image" width="1346" src="https://user-images.githubusercontent.com/37108728/276699748-50001895-7b78-44f2-a4e4-89bcd77e424f.png"> <img alt="image" width="1452" src="https://user-images.githubusercontent.com/37108728/276699642-1d3529de-4a49-4a2c-a83a-abf17053a748.png">


First, Look at this [docs](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_pre_packaged_stream_applications)

it says to register as **Manual** to use the boot3 version. (For now.)

For example, I will download kafka + docker applications.

<img width="752" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/37108728/4439cc8f-69bb-4c23-952c-af5fb16f6840">

And then, You can import these profiles on the scdf front ui.
<img width="1289" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/37108728/55da412c-5d68-4a95-a6d8-5ab9f3426483">

**You can't do too many imports at once, so split them up.**

And then, you can see the springboot version 3.x applications.

<img width="1011" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/37108728/654c1a2d-d433-43f0-93b6-a771c3fb77c9">

**Comment by corneil** [comment]
For backwards compatibility the default it going to remain boot2 for a while.

**Comment by hi-rullah** [comment]
> Invalid TaskExecution, ID 100219 not found

I got the same issue also, "Invalid TaskExecution, ID not found". Per my checking, cloud-task is still using the boot2 table task_execution but SCDF checks the boot3_task_execution table. There is no manual configuration to manage this.

**Comment by corneil** [comment]
> > Invalid TaskExecution, ID 100219 not found
> 
> I got the same issue also, "Invalid TaskExecution, ID not found". Per my checking, cloud-task is still using the boot2 table task_execution but SCDF checks the boot3_task_execution table. There is no manual configuration to manage this.

You need to ensure the registered applications have the correct Spring Boot version configured. If you are using Boot 2 and Boot 3 versions of an application it is safer to register the Boot 3 version with a new name so that you can separate them.
