### ISSUE TITLE
Spring Cloud Data Flow datasources overrides spring batch app datasource

### ISSUE THREAD

**Issue by nvengatesan** [spring-cloud/spring-cloud-dataflow#5523]
**Description:**
I am using scdf 2.6.0. My spring boot application is deployed via scdf. 

I am using the same DB in scdf and spring boot application. My use case is, I want to use one datasource in scdf and another datasource in spring boot application. when I launch spring boot application, it always takes scdf datasource. How do I use my spring boot appplication datasource?

SCDF datasource:

spring:
    datasource:
      url: jdbc:mysql://localhost:5432/app_db?useSSL=false
      username: user1
      password: pass1

Spring boot application datasource:

  datasource:
    url: jdbc:mysql://localhost:5432/app_db?useSSL=true
      username: user2
      password: pass2

username and password and usessl will be different. spring boot application uses difference credential with ssl enabled, SCDF uses different credentials with ssl disabled. When I run spring boot application, it should run with ssl enabled, but it currently running scdf datasource properties. 

Could you please provide how do I override scdf datasource?

**Comment by klopfdreh** [comment]
If you want to configure a datasource beside the Spring Batch datasource within your task applications you can provide a bean like the following - with this you tell the batch framework to use this one. The other one can be use to fit your requirements:

```java
    @Bean
    public DefaultBatchConfigurer batchConfigurer(@Qualifier("dataSource") DataSource dataSource, .....) {
        return new DefaultBatchConfigurer(dataSource) {
        ....
        }
    }
```

**Comment by onobc** [comment]
We agree w/ the workaround above (thanks @klopfdreh) and are closing this based on that.
