### ISSUE TITLE
Step Context section is not populated on the UI

### ISSUE THREAD

**Issue by sandeepbal1989** [spring-cloud/spring-cloud-dataflow#5557]
**Description:**
When Something is added to the step context, it should appear in the STEP CONTEXT section within step execution details(Used to work on 2.10.3). But after upgrading to 2.11.1, this is not happening, however the BATCH_STEP_EXECUTION_CONTEXT already holds the data. So may be something in the SCDF-UI application is broken? Are we expecting a fix for this anytime soon?

**Release versions:**
[Spring Cloud Data Flow 2.11.1](https://github.com/spring-cloud/spring-cloud-dataflow/releases/tag/v2.11.1)

**Custom apps:**

    public Job job() {
        return jobBuilderFactory.get("job")
              .flow(stepBuilderFactory.get("jobStep1")
              .tasklet(new Tasklet() { 
              @Override
              public RepeatStatus execute(StepContribution contribution, 
                ChunkContext chunkContext) throws Exception {
                  contribution.getStepExecution().getExecutionContext().put("akshay", "step context");
                logger.info("Job was run");
                return RepeatStatus.FINISHED;
              }
        }).listener(new StepExecutionListener() {
            
            @Override
            public void beforeStep(StepExecution stepExecution) {
                // TODO Auto-generated method stub
                
            }
            
            @Override
            public ExitStatus afterStep(StepExecution stepExecution) {
                stepExecution.getExecutionContext().put("akshay2", "exec listener");
                return stepExecution.getExitStatus();
            }
        }).build()).build().build();
    }

**Steps to reproduce:**
Used the target jar for the attached zip to register on scdf-2.11.1. 
[scdf-task-app.zip](https://github.com/spring-cloud/spring-cloud-dataflow/files/13427763/scdf-task-app.zip)

**Screenshots:**
![No Step Execution-Context SCDF-UI](https://github.com/spring-cloud/spring-cloud-dataflow/assets/27290782/ddfe67f8-e4c8-4500-8f62-6fcdb3c423b6)

**Additional context:**
tried by setting the attributed to step context by using JobBuilderfactory and  also using execution Listener. Both of them didn't work.

**Comment by akshaylad26** [comment]
+1
Facing same issue after upgrading to 2.11.1 version. Can't go back to 2.10 as it has vulnerabilities. After scratching head for a week, we didn't find any issue in implementation, is anything broken related to step execution context in 2.11.1 release?

**Comment by corneil** [comment]
2.11.2 is due mid December and this is fixed. #5484

**Comment by corneil** [comment]
@akshaylad26 @sandeepbal1989 you can test with 2.11.2-SNAPSHOT to confirm the fix.

**Comment by corneil** [comment]
The data is saved as JSON for Batch4 and Serialized Java for Batch 5.
Neither the StepContext or the JobExecutionContext is not being retrieved for boot2 or boot3 jobs.

**Comment by corneil** [comment]
Batch5 serializes using Java serialization by default.
Batch4 seems to serialize using JacksonSerializer by default.
Dataflow only has access to Batch4 code and fails in deserialize Batch5 context.

**Comment by corneil** [comment]
With 2.10.x `/jobs/executions/1/steps` and `/jobs/executions/1/steps/1/progress` did result in the step execution context being added to the result.
