### ISSUE TITLE
Check dependencies for Spring Boot 2.7.18

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#5564]
As part of Spring Boot update to `2.7.18`, we also need to check other dependencies we have explicitly configured/overrode in our build configuration [here](https://github.com/spring-cloud/spring-cloud-dataflow/tree/main/spring-cloud-dataflow-build).

**Comment by corneil** [comment]
None of the dependencies we override for CVEs have higher versions as a result of Spring Boot 2.7.18. Some are still lower.
We should leave the override versions as is.

**Comment by onobc** [comment]
I think it is a better practice to stay in sync w/ Boot to avoid having multiple versions where possible.
