### ISSUE TITLE
Schedule Task with Arguments and Properties does not work

### ISSUE THREAD

**Issue by GangHun-Jo** [spring-cloud/spring-cloud-dataflow#5568]
When I schedule the task in spring cloud data flow, it doesn't seem to work well even if I put in the version properties. My task consists of only one task application. The version properties I put in are as follows. It appears to be applied as the default version of the application, not as the desired version.

`version.{app}={app-version}`

**Comment by GangHun-Jo** [comment]
FYI, SCDF Server version is 2.11.0

**Comment by corneil** [comment]
When using `version.<label-name>=<version>` is works as expected. Unfortunately Creating a schedule via the UI prevents the input of `version.<label-name>`

**label-name** should be the name of the task definition and not the registered name of the task application.

**Comment by claudiahub** [comment]
Resolved in #1974

**Comment by cppwfs** [comment]
This issue was resolved here: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1974
