### ISSUE TITLE
Ensure docker-compose scripts are up-to-date and working 

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#5582]
A possible issue was reported in https://github.com/spring-io/dataflow.spring.io/issues/502

> The docker-compose-dood.yml configuration is not installing the Docker CLI as expected. This deviation from the expected behavior is hindering the intended functionality of the Docker Compose setup.

- [x] check the above report and fix if it is broken
- [x] check the other docker compose scripts and make sure they are all up-to-date and working

**Comment by corneil** [comment]
Seems like deployer is trying to read a stdout that isn't where it is expected.
