### ISSUE TITLE
The BOOT3 batch schema has old columns in table

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#5591]
The [BOOT3_BATCH_JOB_EXECUTION.JOB_CONFIGURATION_LOCATION](https://github.com/spring-cloud/spring-cloud-dataflow/blob/d6241df429d37275e3154d7433bcb299652aeec2/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/sqlserver/V7__Boot3_Add_Task3_Batch5_Schema.java#L109) column is from previous Batch4 schema. This column needs to be removed in a new schema file for all DBs except MySQL and DB2 that do not have this issue.

Remove batch4 column from batch5 schema

**Comment by cppwfs** [comment]
Is this a duplicate of #5555?

**Comment by onobc** [comment]
Closing as duplicate of #5555
