### ISSUE TITLE
when launch boot3 composed task the main job execution is recorded to the old table

### ISSUE THREAD

**Issue by Setxand** [spring-cloud/spring-cloud-dataflow#5627]
when launch boot3 composed task, the job execution of the main job running the internal tasks recorded to the batch_job_execution table, not to the boot3_batch_job_execution, it looks like a bug, not critical, but looks after the update of the shcemaTarget to boot3 the main job executions should be in the boot3_batch_job_execution table

**Comment by cppwfs** [comment]
In this case Composed Task Runner  is still a Boot 2.7.x application so it will record its Job Execution information to the `batch_job_execution` table.   We will be moving SCDF and CTR to Boot 3 in the SCDF 3.x release.    
Thank you for reporting

**Comment by Setxand** [comment]
Thanks
