### ISSUE TITLE
Application properties not working in task launch

### ISSUE THREAD

**Issue by nvengatesan** [spring-cloud/spring-cloud-dataflow#5632]
**Description:**

Application properties are not working in task launch. 

application properties:

app.dashboard-daily-initializer.dashboard.daily.test=1

arguments:
--test=1

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/40352303/bacc2d69-da17-4e58-b583-299ab53eacae)

in Task Executions, I could see the application properties as below

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/40352303/22a7dd33-bb80-4cc6-bc98-c88969e888ab)

I read the same in spring batch project as below

@Getter
@Setter
@ConfigurationProperties(prefix = "dashboard.daily")
@NoArgsConstructor
public class DashboardInitializerProperties {

    private String test;
}

when job executions launches from task executions, I don't see the properties

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/40352303/efbb9b8e-8cde-44c8-96da-34efa3db4a95)

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/40352303/be4c2f4a-653d-4bce-940e-1031bd498de8)

SCDF version : 2.11.0

**Comment by nvengatesan** [comment]
I am using 
SPRING_APPLICATION_JSON:                                      { "maven": { "local-repository": null, "remote-repositories": { "repo1": { "url": "https://repo.spring.io/libs-snapshot"} } } } 

SCDF version : 2.11.0
Java : 11
Sprint boot 2.7.13


The same code works in SCDF 2.6, after migrating it to 2.11.0, it does not work.. Any lights on this pls.

**Comment by nvengatesan** [comment]
When I launch task from SCDF UI/scheduler with application properties, I dont see the arguments in the logs

SimpleTaskRepository[0;39m: Creating: TaskExecution{executionId=0, parentExecutionId=null, exitCode=null, taskName='dashboard.daily.initializer-1', startTime=Thu Jan 04 16:03:05 UTC 2024, endTime=null, exitMessage='null', externalExecutionId='null', errorMessage='null', arguments=[]}
Running default command line with: []

**Comment by cppwfs** [comment]
I was unable to reproduce your issue using the local deployer.   The only thing that I can see from the samples you provided are as follows:
1) the command line argument should look something like `app.proptask.0=--dashboard.daily.test=mytest`
2) Did you create a bean for your  or add `@Configuration` annotation to your `DashboardInitializerProperties` in your application? 

What platform are you deploying to?
Can you provide a sample app that reproduces the issue?
