### ISSUE TITLE
metrics property name of wavefront  can not  be matched

### ISSUE THREAD

**Issue by wczhang1986** [spring-cloud/spring-cloud-dataflow#5654]
**Description:**
In the dashboard, when I view stream definition, I see additional properties getting added for metrics like  `management.wavefront.metrics.export.uri`.
but in [wavefront for boot3](https://docs.wavefront.com/wavefront_springboot3.html),we set uri of wavefront by using `management.wavefront.uri`.
I think it is the bug in [MetricsReplicationEnvironmentPostProcessor.java](https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/MetricsReplicationEnvironmentPostProcessor.java):metricsPropertyNameInBoot3
the `METRIC_PROP_NAME_PATTERN` can not match `management.wavefront.uri`.

**Release versions:**
2.11.0

**Steps to reproduce:**
- use wavefront
- deploy stream with [kafka-sink](https://github.com/spring-cloud/stream-applications/tree/main/applications/sink/kafka-sink)

**Screenshots:**
![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/37999427/a5cfc869-c7e5-47e5-845d-1528b3a793a0)

**Comment by corneil** [comment]
@wczhang1986 
If you use `app.kafka.management.wavefront.uri` it will be applied as expected.

**Comment by wczhang1986** [comment]
> If you add app.kafka.management.wavefront.uri it will be applied as expected.
Thanks ,
But ,If I want to use stream application after version 4.0.0 with wavefront, I need to set this properties every application.
It doesn't feel good by this way.

**Comment by corneil** [comment]
I have created #5689

**Comment by corneil** [comment]
@wczhang1986 The management properties configured for Spring Cloud DataFlow Server and Skipper server are also used as defaults when launching applications.
