### ISSUE TITLE
Handle DefaultRelProvider appropriately

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#567]
Currently, a BeanPostProcessor is set to override any `DefaultRelProvider` that is already registered as a bean so as to use `..List` collection as HATEOAS response.

We need to handle this appropriately to either override the bean via auto configuration or fix the UI to be flexible enough to work with any `RelProvider`.

**Comment by ghillert** [comment]
For reference see: https://github.com/spring-projects/spring-hateoas/issues/175

**Comment by ilayaperumalg** [comment]
Closing this issue as we don't want to fix this in UI and already provide overridden bean to use `DefaultRelProvider`.
