### ISSUE TITLE
Revisit metric exports

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#5675]
This is a short recap when going through various issues:

- `spring-cloud-dataflow-parent/pom.xml` manages `wavefront-spring-boot-bom.version` as `2.3.4`. Bit nasty as boot doesn't manage wavefront but depends something which then pulls specific wavefront sdk version. Should use `3.2.0` and keep that aligned.
- Our server configs currently use `influx`, `prometheus` and `wavefront` and export is disabled on default. Boot changed property format in https://github.com/spring-projects/spring-boot/commit/be3523b1cda41f178df25fdfe8f8f27199259530, we need to change property names. In short `management.metrics.export.prometheus.enabled` vs. `management.prometheus.metrics.export.enabled`.
- However there's `micrometer-metrics/prometheus-rsocket-proxy` which still uses `management.metrics.export.prometheus.rsocket.enabled`, they never migrated to new property structure.
- Thought there's no "release" in `prometheus-rsocket-proxy` claiming boot 3.x support so wondering if we should just remove this dependency.

**Comment by onobc** [comment]
Thanks for the details @jvalkeal, 

> Our server configs currently use influx, prometheus and wavefront and export is disabled on default. Boot changed property format in https://github.com/spring-projects/spring-boot/commit/be3523b1cda41f178df25fdfe8f8f27199259530, we need to change property names. In short management.metrics.export.prometheus.enabled vs. management.prometheus.metrics.export.enabled.

We already account for this in the `MetricsReplicationEnvironmentPostProcessor`. Take a look. This technique allowed us to support both Boot2 and Boot3 apps. However, we are not supporting Boot2 apps going forward in SCDF3.x so this could be refactored/removed/adjusted if needed but it may be easier to leave it as is and move onto the next item in the above list.

**Comment by jvalkeal** [comment]
Folks from micrometer were open to do some further polish in `prometheus-rsocket-proxy` and release it having boot3 support. So we can temporarily keep it in current state as they probably overhaul their properties for enable state.

**Comment by onobc** [comment]
Adding note here to remove the `@Disabled` from `org.springframework.cloud.dataflow.server.config.MetricsReplicationEnvironmentPostProcessorTests#prometheusPropertiesReplication` when this is complete.

**Comment by onobc** [comment]
Adding note here to move back to the newer client rather than the simpleclient once this issue is complete:
* https://github.com/spring-cloud/spring-cloud-dataflow/pull/5835/commits/7eec502962f7ca2dec4a8dda8babc1abfcab8643
