### ISSUE TITLE
Oracle tables for Spring Batch require SEGMENT CREATION IMMEDIATE

### ISSUE THREAD

**Issue by corneil** [spring-cloud/spring-cloud-dataflow#5735]
**Description:**
When using jobRepository to create test data you encounter an exception when using Oracle database.

**Solution**
The solution is to add `SEGMENT CREATION IMMEDIATE` to the create table statements for Oracle.

**Comment by cppwfs** [comment]
@corneil I think we can close this one.   WDYT?

**Comment by corneil** [comment]
Not required.
