### ISSUE TITLE
Review stream/task parser validation

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#574]
As a user, I'm able to create a stream without `sink` application in it. I should be prevented from creating this bogus stream definition. 

**example:**
```
dataflow:>stream create streama --definition "time | filter"
Created new stream 'streama'
```

**Comment by markfisher** [comment]
This is a much more general issue. Currently there is no validation at stream creation time, e.g.:

```
dataflow:>stream create wow --definition "even | worse"
Created new stream 'wow'
```
