### ISSUE TITLE
Supports for limit / request of ephemeral storage (k8s)

### ISSUE THREAD

**Issue by Kim-menu** [spring-cloud/spring-cloud-dataflow#5743]
**Problem description:**
Is there no support for limits of ephemeral storage?

I can find and use for limits of memory or cpu.

But in docs, I cannot find 'limits of ephemeral storage'

I also put property `deployer.{app}.kubernetes.limits.ephemeral-storage`.
but it doesn't work.

Anything that I missed?

**Solution description:**
Support for ephemeral spec like memory, cpu...

**Comment by cppwfs** [comment]
Closing duplicate for https://github.com/spring-cloud/spring-cloud-deployer/issues/441
