### ISSUE TITLE
Question: Is it possible to disable the Spring Cloud Data Flow GUI?

### ISSUE THREAD

**Issue by r-heimann** [spring-cloud/spring-cloud-dataflow#5755]
See title, i sadly couldn't find anything regarding that in the documentation. Is it currently possible to run Spring Cloud Data Flow in a sort-of headless mode?

**Comment by corneil** [comment]
You can interact with API only. This is what our acceptance tests do. The UI is still available but not used.

**Comment by r-heimann** [comment]
> You can interact with API only. This is what our acceptance tests do. The UI is still available but not used.

I see, completely disabling the UI is not possible?

**Comment by cppwfs** [comment]
Not at this time.   Can open an issue requesting this feature?   Thank you!
