### ISSUE TITLE
2 scdf servers are deployed in one k8s namespace are fetching all the schedules

### ISSUE THREAD

**Issue by Setxand** [spring-cloud/spring-cloud-dataflow#5758]
I have 2 SCDF deployed on the same k8s ns, and there are 2 schedules created on different scdf's but both are getting all the scheduled no matter which one is the owner of the schedule, I've seen the database, there is no schedule table, so looks it tries to get all the schedules from the k8s cronjobs, is it normal things? Can it be fixed by defining a different platform or something like this?

**Comment by cppwfs** [comment]
Thank you for asking!  
You are correct, SCDF utilizes K8's cronjobs to manage the scheduling and listing of tasks.    And you are correct,  a solution is to create a new K8's namespace then define a new platform in SCDF to point to that namespace if you are wanting to view unique schedules.

**Comment by Setxand** [comment]
@cppwfs can it be in 1 namespace but with the different platforms?

**Comment by cppwfs** [comment]
It would have the same effect that you are currently experiencing.

**Comment by Setxand** [comment]
Got it, thanks isn't it gonna be fixed? Unless it's expected behavior?

**Comment by cppwfs** [comment]
This is the expected behavior, but please create a issue on Github making a request for the feature as you described above.   We need feedback.  Thanks!!!

**Comment by Setxand** [comment]
Cool, thanks
