### ISSUE TITLE
Multiple SCDF's in one k8s namespace

### ISSUE THREAD

**Issue by Setxand** [spring-cloud/spring-cloud-dataflow#5759]
Hey, I have on the k8s cluster 2 SCDF servers, one for the real scheduled executions, one for the automated tests with the small amount of data, it works well, but if you have 2 SCDF servers on one k8s namespace you'll have all the schedules created in both servers, because the schedules data is got from the k8s cronjobs with no filters by the platform or some tags. it would be great to add the possibility to differentiate the schedules between the different SCDF servers in one k8s cluster.

**Comment by corneil** [comment]
It is not advisable to have more than one SCDF installation in a namespace. You want to use namespaces to separate them and can have one SCDF installation contoller jobs / streams in multiple namespaces.
