### ISSUE TITLE
SCDF composed task execution for the automated tests

### ISSUE THREAD

**Issue by Setxand** [spring-cloud/spring-cloud-dataflow#5761]
Hi, we have the automated tests project which is gonna run the composed task with up to 25 tasks inside. we're preparing very small amount of data and then run the SCDF's composed task, it works, but the creation of the up to 25 pods takes 20 mins, can I somehow decrease the execution time for the test purposes? Or it would be great to create the feature which executes every task in the composed one in one container to decrease the execution time

**Comment by cppwfs** [comment]
Thank you for the question.  
I assume you are running things sequentially `a  && b && c && d` 
You could run tasks in parallel via a split execution `<a || b> && <c || d>` thus pods `a` and `b` are created  and run at the same time and once both have successfully completed `c` and `d` would be created and run at the same time.   
Just make sure you set the `split-thread-core-pool-size` property to the size of the largest number of tasks in the split execution.

**Comment by Setxand** [comment]
Thanks for the answer, i know i can do it, but unfortunately the tasks are dependent on each other that's why the execution order is important, so i guess there is no some kind of test mode, then It would be a cool feature to run the composed tasks in one container with the test mode flag

**Comment by cppwfs** [comment]
Thank you for the suggestion!    We are closing this issue for now.   If you would like to reopen please leave a comment.
