### ISSUE TITLE
SCDF 2.10.x. and 2.11.x doesn't allow define schedule with Cron Expression CRON_TZ=CET 37 04 * * *

### ISSUE THREAD

**Issue by szopal** [spring-cloud/spring-cloud-dataflow#5774]
From kubernetes 1.29 it doesn't support CRON_TZ expression. 

[https://www.yuribacciarini.com/k8s-setup-timezone-on-cronjob/](https://www.yuribacciarini.com/k8s-setup-timezone-on-cronjob/)

It seem's that SCDF has old library from fabric8 because I can't see propertise withTimeZone in KubernetesScheduler in library 

		<dependency>
			<groupId>io.fabric8</groupId>
			<artifactId>kubernetes-client</artifactId>
			<version>${kubernetes-fabric8-client.version}</version>
		</dependency>

at version

<kubernetes-fabric8-client.version>5.12.4</kubernetes-fabric8-client.version>

This property I can see in 6.10.0

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/57896357/0fadf0d6-0f18-41af-9ab8-44e3af1589f4)

So after upgrade kubernetes to 1.29 we don't have possibility to create scheduler in our time zone.

**Comment by corneil** [comment]
Create issue in [spring-cloud-deployer#445](https://github.com/spring-cloud/spring-cloud-deployer/issues/445)

**Comment by corneil** [comment]
According to k8s specification timezone isn't supported:

> CronJob limitations 
> Unsupported TimeZone specification
> Specifying a timezone using CRON_TZ or TZ variables inside .spec.schedule is not officially supported (and never has been).

> Starting with Kubernetes 1.29 if you try to set a schedule that includes TZ or CRON_TZ timezone specification, Kubernetes will fail to create the resource with a validation error. Updates to CronJobs already using TZ or CRON_TZ will continue to report a [warning](https://kubernetes.io/blog/2020/09/03/warnings/) to the client.

**Comment by cppwfs** [comment]
Closing this issue.  If this issue was closed incorrectly please add a comment.   Thank you for raising the issue!

**Comment by szopal** [comment]
Why not add a custom parameter to enable support for the timeZone parameter in an earlier version of SCDF and the Fabric8 library?
KubernetesScheduler.class:

```
    	if (properties.getTimeZone() != null) {
	      	if (cronJob.getSpec().getAdditionalProperties() == null) {
		    	cronJob.getSpec().setAdditionalProperties(new HashMap<>());
	      	}
	      	cronJob.getSpec().getAdditionalProperties().put("timeZone", properties.getTimeZone());
	    }
```
