### ISSUE TITLE
Publish Skipper 2.11.x reference docs

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#5778]
The `2.11.x` skipper docs are not available but referenced from spring.io at https://docs.spring.io/spring-cloud-skipper/docs/2.11.0/reference/htmlsingle/#getting-started. 

## Work Items
- [ ] Need to start publishing the `2.11.x` reference docs again. This broke when we moved into the Dataflow monorepo. 
- [ ] Fix above link that was temporarily pointed to the `2.9.x` (cc: @oodamien)

**Comment by corneil** [comment]
This change involves using jfrog cli to tag the published docs artifacts with properties same as skipper project did to trigger to update of docs.spring.io
