### ISSUE TITLE
Update SCDF to Spring Boot 3.2.x / Spring Batch 5.x / Spring Cloud Task 3.1.x

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow#5784]
**Problem description:**
As there are a lot of new improvements in Spring Boot 3.2.x like `reload-on-update` and `ssl bundles` for example, a lot of security fixes like in snake-yml `2.2` and a lot of bug fixes, it would be really great to upgrade to the newest versions.

**Solution description:**
N/A

**Description of alternatives:**
N/A

**Additional context:**
I couldn't see any feature request regarding those updates. Hope this is no duplication.

**Comment by cppwfs** [comment]
@klopfdreh Thanks for bringing this up and your comments are always welcome!  We have started work on the 3.x migration of SCDF.  
I'm going to close this issue, but keep bringing up your great ideas and comments!
