### ISSUE TITLE
Spring Cloud Data flow is not working with spark

### ISSUE THREAD

**Issue by rejurs** [spring-cloud/spring-cloud-dataflow#579]
Hi Team,

I have created an issue in stackoverflow for spring cloud data flow when working with spark in hortonworks cluster. This is the url for the same. http://stackoverflow.com/questions/37035250/spring-cloud-dataflow-is-not-working-with-spark. Could you please check and let me know

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-server-yarn#131
