### ISSUE TITLE
Add "stream-update" REST API

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#583]
As a developer, I'd like to add ~~`app-scale`~~ `stream-update` REST-API, so I can use it to scale application instances up/down.

This depends on spring-cloud/spring-cloud-deployer#62

**Comment by markfisher** [comment]
We might want to consider this more broadly as a `stream update` command, e.g. to scale the log sink:

```
stream update ticktock --properties "module.log.count=3"
```

That way we could support other property updates.

**Comment by sabbyanandan** [comment]
Makes sense! I'll update the description.

**Comment by sabbyanandan** [comment]
This is addressed via: https://github.com/spring-cloud/spring-cloud-dataflow/commit/e116e82dd63a324d621373f34c0df76e1791b3e4.
