### ISSUE TITLE
Add support to trigger a Task

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#584]
As a developer, I'd like to add support to trigger a task from the shell, REST-API or the UI. 

**Acceptance:**
- `trigger` source can be used to trigger a Task application
- DSL, REST-API, and UI support available
- Unit tests included
- Docs updated

**Comment by cppwfs** [comment]
Since this is handled by the TriggerTask Source https://github.com/spring-cloud/spring-cloud-stream-app-starters/issues/98 do we want to close this?
If we do, do we want story for writing docs in SCDF describing how to setup a scheduled task using the TriggerTask source |tasklaunchersink?

**Comment by sabbyanandan** [comment]
Yep; let's close it. We already have spring-cloud/spring-cloud-dataflow#619 to cover the documentation.
