### ISSUE TITLE
Batch-job with parameters insert through REST -> shell&http

### ISSUE THREAD

**Issue by pentchomakov** [spring-cloud/spring-cloud-dataflow#585]
Hi guys,

[SpringXD] - Perhaps this is already possible, but I'm having trouble executing a batch job with new params through the shell. I'm trying to do: http post --target http://localhost:9393/jobs/executions?jobname=my-job-name --data {"key1":"value1", "key2":"value2",...,"keyn":"valuen"}. I can launch the job if I send dummy data, but it won't map to the params that the job is set to accept. That being said, if I manually launch the job through the admin-ui and add params one-by-one, there is no problem.

Thank you in advance for your help!

**Comment by sabbyanandan** [comment]
Hi, @pentchomakov:

This repo is specific to Spring Cloud Data Flow and the Spring XD backlog/issues are managed in [JIRA](https://jira.spring.io/secure/RapidBoard.jspa?rapidView=6&view=planning). Perhaps you could move this to JIRA or ask in XD's github [repo](https://github.com/spring-projects/spring-xd/issues).

Thanks for your interest!
