### ISSUE TITLE
Update version of stream/task apps used by Dataflow

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#5897]
- [x] update code references to apps
- [x] update version picked up from Dataflow UI when user registers apps
- [x] update ATs to use new apps (this may be later though)

Stream apps version goes from `3.2.1 -> 5.0.0`
Task apps version goes from `2.0.2 -> 3.0.0`

**Comment by corneil** [comment]
ATs already use 5.0.0 stream apps.
