### ISSUE TITLE
Support for all official binders via a configurable list of profiles

### ISSUE THREAD

**Issue by corneil** [spring-cloud/spring-cloud-dataflow#5922]
**Problem description:**
SCDF currently only support RabbitMQ and Kafka as binders. There is a long list of official and partner maintained binders:

- [RabbitMQ](https://github.com/spring-cloud/spring-cloud-stream/tree/main/binders/rabbit-binder)
- [Apache Kafka](https://github.com/spring-cloud/spring-cloud-stream/tree/main/binders/kafka-binder)
- [Kafka Streams](https://github.com/spring-cloud/spring-cloud-stream/tree/main/binders/kafka-binder/spring-cloud-stream-binder-kafka-streams)
- [Apache Pulsar](https://github.com/spring-cloud/spring-cloud-stream/tree/main/binders/pulsar-binder)
- [Amazon Kinesis](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis)
- [Google PubSub (partner maintained)](https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-pubsub-stream-binder)
- [Solace PubSub+ (partner maintained)](https://github.com/SolaceProducts/spring-cloud-stream-binder-solace)
- [Oracle TxEventQ_(partner maintained)_](https://github.com/oracle/spring-cloud-oracle/tree/main/database/spring-cloud-stream-binder-oracle-txeventq)
- [Azure Event Hubs (partner maintained)](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring/spring-cloud-azure-stream-binder-eventhubs)
- [Azure Service Bus (partner maintained)](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring/spring-cloud-azure-stream-binder-servicebus)
- [AWS SNS (partner maintained)](https://github.com/idealo/spring-cloud-stream-binder-sns)
- [Apache RocketMQ (partner maintained)](https://github.com/alibaba/spring-cloud-alibaba/wiki/RocketMQ-en)
 
We should support all official binders and provide for using profiles or specific properties during deployment of Dataflow and Skipper servers to enable support for specific binders.

**Solution description:**
Include all the binder dependencies in skipper and required configuration dependencies in Dataflow Server.
Provide configuration that will enable / disable the binders based on profiles / properties present during deployment and the relevant configuration properties to Dataflow UI.

Provide for extra modules for partner maintained stream binders to be added as dependencies and managed via a profile entry/properties.

**Comment by onobc** [comment]
Closing this as Won't Fix.
