### ISSUE TITLE
Update dependencies to latest version in main-3

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#5923]
- [ ] spring-cloud-dataflow
- [ ] spring-cloud-dataflow-u
- [ ] spring-cloud-deployer
- [ ] scdf-pro
- [ ] scdf-pro-ui
- [ ] scs-dataflow
- [ ] k8s-packaging (??)

**Comment by onobc** [comment]
No longer valid.
