### ISSUE TITLE
CTR Verify security configuration manually

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#5926]
As part of [this](https://github.com/spring-cloud/spring-cloud-dataflow/pull/5901/files#r1728280707) discussion from https://github.com/spring-cloud/spring-cloud-dataflow/pull/5901, we need to verify the CTR security configuration changes as a result of removing some of the auto configurations.

**Comment by cppwfs** [comment]
This issue is resolved via manual testing.
