### ISSUE TITLE
Shell: On Startup - Command Line Parameters try to execute Shell Command

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#594]
When I start the shell with command-line parameters `--username user --password secret7` it exits with 

```
2016-05-13T09:44:53-0400 WARN main o.s.s.c.SimpleParser:443 - Command '--username user --password secret7' not found (for assistance press TAB)
```

**Comment by markpollack** [comment]
For better or worse, the standard Spring Shell behavior is to assume that anything after well known spring shell options are commands to execute and then exit.  Spring Cloud Dataflow Shell mimics the main shell application via the class `BootstrapConfiguration` and then uses boot to kick everything off.   We should probably remove the 'execute command and exit' behavior and look to use `@ConfigurationProperties` in the `@ConfigCommands` class to that we can rely on spring boot to process the command line options.

**Comment by markpollack** [comment]
Also of note, the standard behavior/feature to load arbitrary commands via `classpath*:/META-INF/spring/spring-shell-plugin.xml` has not been caried over to this new configuration style.
