### ISSUE TITLE
Add Schedule Configuration for clean up task execution

### ISSUE THREAD

**Issue by GangHun-Jo** [spring-cloud/spring-cloud-dataflow#5943]
**Problem description:**
As task execution data volume(DB) grows, There would be a significant impact on API performance.
In my experience, GET /tasks/definitions API's respose time was 40.97s. (TASK_EXECUTION row count : 175,506)
Therefore, I think periodic cleanup of data is essential for users.
It seems scdf provides cleanup API (DELETE /tasks/executions).
But in order to use this api, users have to create another batch.

**Solution description:**
It seems scdf can help user to periodically cleanup task executions with spring schedule.
What scdf users have to do is set up related properties.
If the properties are set up, scdf server enables scheduling for cleanup.
Also users can customize other properties for cleanup. (cleanup days, taskName, cron expression...)

**Comment by GangHun-Jo** [comment]
@cppwfs any updates here?

**Comment by cppwfs** [comment]
@GangHun-Jo    Thank you for opening the issue.   
After some team discussions, it was determined the best way to handle this would be to have an external scheduler submit a restful request to dataflow to clean up the desired task executions.
