### ISSUE TITLE
feat: Add `suspend` API to safely delete scheduled tasks after execution is complete

### ISSUE THREAD

**Issue by injae-kim** [spring-cloud/spring-cloud-dataflow#5948]
### **Problem description:**
Hi! currently we migrate batch system to spring-cloud-dataflow.

> SCDF doesn't support to update cronjob, workaround is to `delete&re-create` schedule ([issue](https://github.com/spring-cloud/spring-cloud-dataflow/issues/4996#issuecomment-1262295042))

We use many `scheduled tasks` on spring-cloud-dataflow and I found that `scheduled task` doesn't support `update`.
And I found that `update cronJob` is not recommended by k8s side too ([issue](https://github.com/kubernetes/kubernetes/issues/63371), [issue2](https://github.com/kubernetes/kubernetes/issues/65457))

But, we need some way to update (or, at least `suspend`) scheduled tasks on below case.
1. Register scheduled task with `app v1`
2. ✅ After we deploy new `app v2`, need to `suspend`(not delete immediately, wait until complete) scheduled tasks v1 and re-create with v2

We want to safe-delete scheduled task v1 **after complete to run cronJob** that currently running, so need `suspend` instead of delete (which immediately delete cronJob)

### **Solution description:**

```java
// SCDF SchdulerService
public void suspend(..) {
  ..
}       
```
Add `suspend` API on [DefaultSchedulerService](https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSchedulerService.java#L206) and [KubernetesScheduler](https://github.com/spring-cloud/spring-cloud-deployer/blob/main/spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesScheduler.java#L274-L275).

```java
// CronJobSpec
    public void setSuspend(Boolean suspend) {
        this.suspend = suspend;
    }
```
Then we can suspend v1 scheduled task by setSuspend on [CronJobSpec](https://github.com/fabric8io/kubernetes-client/blob/main/kubernetes-model-generator/kubernetes-model-batch/src/generated/java/io/fabric8/kubernetes/api/model/batch/v1beta1/CronJobSpec.java#L164-L165).

### **Description of alternatives:**

We want to safe-delete(delete after complete to run cronJob that currently running), so we can't use delete and need suspend or update.

But update is not recommended on k8s side so suspend API is proper solution I think!

### **Additional context:**
X

**Comment by injae-kim** [comment]
We need this `suspend` API now for our service! PTAL 🙇

If you think this issue is not resolved soon, please tell me~ I'll create PR!

**Comment by corneil** [comment]
The suggested solution is specific to Kubernetes. 
Initially non-k8s deployment target will produce a not supported error when trying to suspend a schedule.
If we build/embed a sophisticated scheduler for other platforms we could address this on those as well.

**Comment by injae-kim** [comment]
1. Add suspend API for k8s at first
2. Support suspend API for other platforms too

@corneil , what do you think about above solution?
I think adding `suspend` API is easier than adding `safe-delete` or `update` API for other platforms.

> But, we need some way to update (or, at least `suspend`) scheduled tasks on below case.
> 1. Register scheduled task with `app v1`
> 2. ✅ After we deploy new `app v2`, need to `safe-delete`(not delete immediately, wait until complete) scheduled tasks v1 and re-create with v2

Anyway, we want to solve above problem and maybe there's another solution. any ideas are welcome :)

thank you!

**Comment by injae-kim** [comment]
> If we build/embed a sophisticated scheduler for other platforms we could address this on those as well.

@corneil can you simply explain more about this idea? (sophisticated scheduler for other platforms)

Maybe I can make PR 🙇

**Comment by corona10** [comment]
FYI, in @line (I am working at the same company as @injae-kim), many teams try to adopt SCDF projects as much as possible, but the main requirement of scheduled batch jobs is it should be possible to manage version changes seamlessly changes.
However, the current workaround is not suitable for such cases. It would be good to support this option even if it is only available at Kubernetes. (Even if we use the delete & register approach, existing tasks should be deleted after the task is completed) I have no opinion on how to support this requirement, but it would be great if there is a better solution than currently suggested.

We just want to provide real-world requirements where projects try to adopt SCDF to replace their legacy batch projects.
Thank you for understanding :)

**Comment by cppwfs** [comment]
In this case it is recommended that a advanced scheduler be use to send restful requests to SCDF to launch and delete the tasks.   A issue was opened on SCDF Samples to provide a demonstration of what this would look like using Quartz.  https://github.com/spring-cloud/spring-cloud-dataflow-samples/issues/204
