### ISSUE TITLE
SqlServer 2017 tests failing

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#5952]
Determine why the following tests are failing and re-enable the disabled tests.

> Annotations
> 4 errors and 6 warnings
> org.springframework.cloud.dataflow.server.db.migration.SqlServer_2017_SmokeTest ► : spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/arm64/SqlServerArm64ContainerSupport.java#L51
> Failed test found in:
>   spring-cloud-dataflow-server/target/surefire-reports/TEST-org.springframework.cloud.dataflow.server.db.migration.SqlServer_2017_SmokeTest.xml
> Error:
>   org.testcontainers.containers.ContainerLaunchException: Container startup failed for image mcr.microsoft.com/mssql/server:2017-latest
> org.springframework.cloud.dataflow.server.db.support.DatabaseTypeTests$SqlServer_2017_DatabaseTypeTests ► : spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/arm64/SqlServerArm64ContainerSupport.java#L51
> Failed test found in:
>   spring-cloud-dataflow-server/target/surefire-reports/TEST-org.springframework.cloud.dataflow.server.db.support.DatabaseTypeTests$SqlServer_2017_DatabaseTypeTests.xml
> Error:
>   org.testcontainers.containers.ContainerLaunchException: Container startup failed for image mcr.microsoft.com/mssql/server:2017-latest

main:
https://github.com/spring-cloud/spring-cloud-dataflow/actions/runs/10994471927

**Comment by corneil** [comment]
There was a recent update to `latest` but there is no other 2017 tag with the same date.
`2017-CU31-GDR2-ubuntu-18.04` also gives errors. There may be a breaking change to `org.testcontainers:mssqlserver`.
Either way I don't believe we need to try and support a 7 year old commercial database version in the OSS project.

**Comment by cppwfs** [comment]
Are there other tests we need to drop as well because of the age of the DB version?

**Comment by corneil** [comment]
Removed Tests related to mssqlserver:2017

**Comment by corneil** [comment]
> Are there other tests we need to drop as well because of the age of the DB version?

Maybe we could consider removing MySQL 5.7 when VMware MySQL is only based on 8.x or later.

**Comment by cppwfs** [comment]
I agree.   We just need to make sure we include our supported databases in the 3.0.x release notes.
