### ISSUE TITLE
[For discussion] Remove app-starters-common-analytics dependency

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#598]
SCDF has the dependency on `app-starters-common-analytics` especially to refer metric repositories for the REST operations from server side.

Creating this issue to discuss possible approaches to remove this dependency.

**Comment by markpollack** [comment]
After a chat with @mbogoevici and @ilayaperumalg about the relationship between SCDF and the metrics libraries the following propsoal was made

* Create a new repository `spring-projects/spring-analytics`  (name TBD) that would contain the code that is currently in `app-starters-common-analytics` and also the `@Controller` code that is in SCDF.
* The new code base can be structured to use autoconfiguration to include a specific implementation via use of an annotation.  For example adding `@EnableRedisAnalytics` would bring in the redis impls.  This allows users to create a SCDF server that does not use redis, which is useful for those who are only doing batch workloads and have no need for redis.

Other (generic) benefits of this approach are 
* It is easier to contribute to as it is more self contained and visible.  
* Applications that do no use SCDF but would like to use counters etc would benefit from having @Controller endpoints available.  
* It keeps all the code in one place vs. the current situation where @Controller methods are in on project and CRUD methods in another which results in having to always have pairs of commits on two projects to expose new functionality.
* Use of autoconfiguration allows for servers that don't have any analytics or can use other implementations, for example one that uses Geode maybe interesting to have.  See https://cwiki.apache.org/confluence/display/GEODE/Geode+Redis+Adapter

@sabbyanandan @markfisher - Thoughts?

**Comment by sabbyanandan** [comment]
> @EnableRedisAnalytics

> This allows users to create a SCDF server that does not use redis, which is useful for those who are only doing batch workloads and have no need for redis

👍 : one less (_mandatory_) peripheral and it could simplify deployment requirements; especially, for batch/task only users.

**Comment by sabbyanandan** [comment]
@ilayaperumalg @markpollack - since we have removed the app-starters dependency from core, could we close this?

**Comment by ilayaperumalg** [comment]
Yes, given we already have enable/disable `analytics` features and we only depend on `spring-analytics` for analytics infra, this can now be closed.
