### ISSUE TITLE
Cannot load driver class: com.mysql.cj.jdbc.Driver

### ISSUE THREAD

**Issue by VikasMGowda05** [spring-cloud/spring-cloud-dataflow#6053]
**Description:**
While we are installing Spring cloud dataflow using Helm Installation(helm version 30.0.2) we are facing issue with Mysql driver class. It says "Cannot load driver class:com.mysql.cj.jdbc.Driver". could anyone let us know what is the issue here.

**Release versions:**
we are installing "bitnami/spring-cloud-dataflow:2.11.5-debian-12-r2"

**Additional context:**
Below is our values.yaml file

server:
  image:
    registry: docker.io
    repository: bitnami/spring-cloud-dataflow
    tag: 2.11.5-debian-12-r2
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false
  composedTaskRunner:
    image:
      registry: docker.io
      repository: bitnami/spring-cloud-dataflow-composed-task-runner
      tag: 2.11.5-debian-12-r2
      digest: ""
  configuration:
    streamingEnabled: false
    batchEnabled: true
    accountName: default
    trustK8sCerts: false
  containerPorts:
    http: 8080
    jdwp: 5005
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
  startupProbe:
    enabled: false
    initialDelaySeconds: 120
    timeoutSeconds: 1
    periodSeconds: 20
    failureThreshold: 6
    successThreshold: 1
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 1
    periodSeconds: 20
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 1
    periodSeconds: 20
    failureThreshold: 6
    successThreshold: 1
  networkPolicy:
    enabled: false
    allowExternal: false
    allowExternalEgress: false
  service:
    type: ClusterIP
    ports:
      http: 8080
  ingress:
    enabled: true
    path: /
    pathType: ImplementationSpecific
    hostname: "xyz.com"
  pdb:
    create: false
    minAvailable: ""
    maxUnavailable: ""
  pdb:
    create: false
skipper:
  enabled: false
rabbitmq:
  enabled: false
mariadb:
  enabled: false
metrics:
  enabled: false
  pdb:
    create: false
externalDatabase:
  host: "{{RDS-endpoint}}.rds.amazonaws.com
  driver: com.mysql.cj.jdbc.Driver
  dataflow:
    url: "{Database url}"
    username: 
    password:

**Comment by corneil** [comment]
@VikasMGowda05 
We do not package the MySQL Driver because it's license doesn't allow redisrtibution.

You can use `org.mariadb.jdbc.Driver` and add `?permitMysqlScheme` to URL for MySQL 5.7 
and `?allowPublicKeyRetrieval=true&autoReconnect=true&permitMysqlScheme` for MySQL 8 or later.

**Comment by VikasMGowda05** [comment]
Thanks Corneil!, it worked for us.
