### ISSUE TITLE
Deploying an already deployed stream returns "deployed stream"

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#621]
Should it indicate the stream has already been deployed?

**Comment by sabbyanandan** [comment]
I thought we addressed it via: spring-cloud/spring-cloud-dataflow#600? 

cc:/ @ilayaperumalg

**Comment by ilayaperumalg** [comment]
@sabbyanandan #600 is different (validation for app names against app registry). Do you mean a different story?
