### ISSUE TITLE
Enabling Kerberos authentication in Admin and Container.

### ISSUE THREAD

**Issue by bjalonmontanes** [spring-cloud/spring-cloud-dataflow#624]
Some users would require Kerberos authentication for Admin and Container components.

**Comment by bjalonmontanes** [comment]
Some users would require Kerberos authentication for Admin and Container components.

**Comment by sabbyanandan** [comment]
This is Spring Cloud Data Flow backlog. If you'd like to report a bug in Spring XD, please open a JIRA ticket [here](https://jira.spring.io/secure/RapidBoard.jspa?rapidView=6&view=planning.nodetail).
