### ISSUE TITLE
Inconsistent deployment/undeployment behavior

### ISSUE THREAD

**Issue by cpage-pivotal** [spring-cloud/spring-cloud-dataflow#625]
Using the latest milestone release of PCF, deployment sporadically fails. I will get the "Stream deployed" message on the command line, and the AIs appear in CF, but they remain in the "stopped" state and never start. The stream does not show up in the stream list, and I have to manually remove the instances.

If a stream fails to deploy (e.g. because one of the apps did not start up successfully), undeploying or destroying the stream sporadically fails. Sometimes doing so will remove the stream from the stream list, but the AIs remain and I have to manually remove them.

**Comment by ilayaperumalg** [comment]
Hi,

Do you see this issue when using Dataflow `CF` server or with the local dataflow server?
If it happens only with CF, then may be we can move this issue to https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry

Thanks!

**Comment by cpage-pivotal** [comment]
Only on CF.We can move the issue.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-server-cloudfoundry#120
