### ISSUE TITLE
Improve getting started experience with local server

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#628]
After switching to Kafka as the transport the getting started experience is broken. Can't run a simple stream with local server without Kafka running. There is nothing in the docs for starting up Kafka. Can we add an embedded service?

**Comment by mbogoevici** [comment]
> After switching to Kafka as the transport.

How is that different from running with Rabbit (or the requirement for running Redis) ?

**Comment by sabbyanandan** [comment]
There's an open PR to address the getting-started guide: spring-cloud/spring-cloud-dataflow#596
