### ISSUE TITLE
Add AUTH support for the shell

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#631]
As a developer, I'd like to add auth support for shell, so I can authenticate using user/pass credentials. This was originally addressed via spring-cloud/spring-cloud-dataflow#483, but it needs reworked and added back in.

**Comment by markpollack** [comment]
Will be appending https://github.com/spring-cloud/spring-cloud-dataflow/pull/605 to merge in the functionality that was introduced on master via the OAuth Pr.
