### ISSUE TITLE
Improved Error Handling when Setting Target from Command Line

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#635]
Error handling needs to be improved:
- wrong command line argument does not return an error on the console

e.g.:

```
java -jar spring-cloud-dataflow-shell/target/spring-cloud-dataflow-shell-1.0.0.BUILD-SNAPSHOT.jar --dataflow.user=user --dataflow.password=secret9

```

You just end up with the shell prompt (unknown). But “dataflow config info” produces:

```
server-unknown:>dataflow config info
Command failed java.lang.NullPointerException
java.lang.NullPointerException
    at org.springframework.cloud.dataflow.shell.command.ConfigCommands.info(ConfigCommands.java:230)
...
```

**Comment by ilayaperumalg** [comment]
This can be closed as `invalid` with the recent security changes in 2.x along with the validation at the shell side via https://github.com/spring-cloud/spring-cloud-dataflow/issues/2964,  https://github.com/spring-cloud/spring-cloud-dataflow/issues/781, https://github.com/spring-cloud/spring-cloud-dataflow/issues/2789 and https://github.com/spring-cloud/spring-cloud-dataflow/issues/2580
