### ISSUE TITLE
Skip SSL cert verification by default

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#638]
As a user, while testing OAUTH feature in SCDF, I'm running into an error accessing UAA due to SSL verification. I'd like to skip verification of SSL cert, so I can authenticate and gain access to the server when running in non-PROD environments. Perhaps the change needs to be addressed at  SCDF's [RestTemplate](http://blog.codeleak.pl/2016/02/skip-ssl-certificate-verification-in.html) layer.

If we don't have the option to skip verification, I see the following error:

```
While authenticating user 'foo': Unable to access accessTokenUri 'https://login.foo.springapps.io/oauth/token'. Error message: I/O error on POST request for "https://login.foo.springapps.io/oauth/token": sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
```

**Acceptance:**
- I'm able to successfully authenticate against an UAA instance running in PCF 
- I can successfully gain access both in the shell/ui

**Comment by ericbottard** [comment]
I don't think having anything dealing with security being turned off by default is a good idea

**Comment by sabbyanandan** [comment]
It is not the default expectation, but rather an option to turn it off at will. This is specifically helpful when you're on DEV mode where you wouldn't always have valid certs. The same way how CF provides an option to skip the validation on demand.

**Comment by ericbottard** [comment]
Then the description of this issue needs to change :) Are you saying there is no way to skip it (via a property or something equivalent)?

**Comment by sabbyanandan** [comment]
Ah, yeah, fixed the description. And, yes, there isn't any property atm to skip it.

**Comment by kumarprashant2103** [comment]
Did we get this issue resolved. We are getting the SSLException error.
 We are getting the below error when we try to execute our applications from private docker registry : Failed to retrieve properties for resource Docker Resource [docker:dtrprod.kbm1.loc/pdev/pdev:test-interactionref-382-46196] because of SunCertPathBuilderException: unable to find valid certification path to requested target
