### ISSUE TITLE
Include spring-boot-admin server to core Data Flow server

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#639]
As a developer, I'd like to add the sprig-boot-admin-server to the core Data Flow server to help manage and monitor Data Flow.

**Comment by sabbyanandan** [comment]
We have been suggesting this as an optional addition - docs [here](http://docs.spring.io/spring-cloud-dataflow/docs/1.2.0.RELEASE/reference/htmlsingle/#_spring_boot_admin).
