### ISSUE TITLE
Since commit 1bcbefad33 the quickstart on cloud.spring.io is outdated

### ISSUE THREAD

**Issue by helt** [spring-cloud/spring-cloud-dataflow#652]
On http://cloud.spring.io/spring-cloud-dataflow/#quick-start  you advise ppl to clone the code, and then in Step 7 - Launch Admin UI at: http://localhost:9393/admin-ui

However, since 1bcbefad33  it should read:
Step 7 - Launch Admin Dashboard at: http://localhost:9393/dashboard

**Comment by sabbyanandan** [comment]
Thanks for catching that! 

The project site is now updated: http://cloud.spring.io/spring-cloud-dataflow/ 😄
