### ISSUE TITLE
the Spring Cloud Data Flow shell shows the banner twice when using `@EnableDataFlowShell`

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-dataflow#656]
Hi, 

the Spring Shell-based Data Flow shell displays a _very_ well done ASCII banner art for Data Flow _and_ it displays the default Spring Boot ASCII banner. It's simple enough to expressly set  `spring.main.banner-mode=off` but it's confusing to see two banners and it doesn't need to happen. You could set the property for the user and default to not showing the Boot banner (deferring to the Data Flow one).

Yes, it sometimes _is_ possible to have too much of a good thing. I sure love me some ASCII banner art...

**Comment by sabbyanandan** [comment]
Thanks for reporting, Josh. This has been [addressed](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-shell/src/main/java/org/springframework/cloud/dataflow/shell/app/ShellApplication.java#L38).
