### ISSUE TITLE
Support individual application memory and disk requirements as deployment properties

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#658]
Much like we support instance count on a per-app basis when deploying, we should support disk and memory requirements as well.

That is, to support 

```
dataflow:> stream deploy --name ticktock --properties "app.time.memory=2048"
```

much like we support 

```
dataflow:> stream deploy --name ticktock --properties "app.time.count=3"
```

See https://github.com/spring-cloud/spring-cloud-deployer/issues/69

**Comment by sabbyanandan** [comment]
We support this as:

>stream create --name ticktock --definition "time | log"
>stream deploy --name ticktock --properties "deployer.time.memory=2g"
