### ISSUE TITLE
Support individual application env-vars as deployment properties 

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#662]
Much like we support instance count on a per-app basis when deploying, we should support passing in environment variables 

That is, to support 

```
dataflow:> stream deploy --name ticktock --properties "app.time.environmentVariables=SPRING_CLOUD_CONFIG_URI=http://localhost:8888,SOME_OTHER_ENV=foobar"
```

**Comment by sabbyanandan** [comment]
Hi, @markpollack. We support the ability to override app properties when deploying the stream/task/app by following the `app.<app-name>.<property>=` semantics. Is that not enough?

**Comment by sabbyanandan** [comment]
We support this in cf/k8s via an explicit deployer property, and that can be tagged to each of the deployed applications.
