### ISSUE TITLE
Variable {project-artifactId} doesn't resolve when appendix-building.adoc is included in other projects

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#664]

**Comment by ericbottard** [comment]
That's because it's not properly set by the including project I believe.
see https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/blob/master/spring-cloud-dataflow-server-kubernetes-docs/pom.xml#L74 (which has outdated, copied over from boot properties)

**Comment by ericbottard** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-dataflow-server-mesos/issues/64 and https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/issues/90
