### ISSUE TITLE
Quick Start doc bugs

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-dataflow#679]
http://cloud.spring.io/spring-cloud-dataflow/ shall also describe that someone shall set the profile spring to build. IT dind't work for me with no profile set and failed to locate/download deps.

**Comment by sabbyanandan** [comment]
Thanks for reporting! The quick-start guide has been recently updated - please check it out and let us know if you still see any gaps in it.

**Comment by markpollack** [comment]
The doc should say `./mvnw` instead of `mvn`
