### ISSUE TITLE
Assemble app registry with M1 and SNAPSHOT app-starters

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#701]
As a developer, I'd like to assemble app-registry with M1 and SNAPSHOT releases of app-starters, so the improvements with the refactored apps are readily consumable at the local-server level. 

**Acceptance:**
- 1.0.0.BUILD-SNAPSHOT  is the [default version](https://github.com/spring-cloud/spring-cloud-dataflow/blob/ec49eb7cc07ce5251a13fcbdb0f91c09a8e8e898/spring-cloud-dataflow-server-local/pom.xml#L15)
- refactored kafka and rabbit apps default to `1.0.0.BUILD-SNAPSHOT` 
- remaining kafka and rabbit apps fallback to `1.0.0.M1`
- task apps default to `1.0.0.BUILD-SNAPSHOT`

**Comment by markpollack** [comment]
Assuming the current PRs for app-starters get merged, I believe the list of apps that have not had the prefix added to them are

```
cassandra
gemfire
gpfdist
hdfs
jms (in progress?)
redis
tasklauncher has empty TaskLauncherLocalSinkProperties?
trigger
triggertask
```

**Comment by sobychacko** [comment]
hdfs sink has prefix added. So we can remove that from the above list.

**Comment by cppwfs** [comment]
I submitted https://github.com/spring-cloud/spring-cloud-stream-app-starters/pull/134 to remove properties from tasklauncherlocal.
