### ISSUE TITLE
Persisting stream definitions

### ISSUE THREAD

**Issue by sachkk76** [spring-cloud/spring-cloud-dataflow#745]
When I restart spring cloud data server, Module definitions are there as they are getting persisted (in redis store) but I loose the stream definitions.. Is there a way to make streams durable?

**Comment by ilayaperumalg** [comment]
Hi @sachkk76, which version SCDF are you using? Since RC1, we use RDBMS to persist stream definitions, app definitions etc.,

**Comment by sabbyanandan** [comment]
As of [RC1](https://spring.io/blog/2016/06/21/spring-cloud-data-flow-1-0-rc1-released), the servers persist the stream definitions (_among others_) in an RDBMS. If none is [provided](http://docs.spring.io/spring-cloud-dataflow/docs/1.0.0.RC1/reference/htmlsingle/#getting-started-system-requirements), they are stored in the default `h2` database.

**Comment by sachkk76** [comment]
I am using 1.0.0.M2. I will try with RC1. thanks.

**Comment by sachkk76** [comment]
So I see RC1 is for local version for cloud foundry its M3

**Comment by sabbyanandan** [comment]
M3 release of CF-server builds upon RC1 release of SCDF-core, so yes, it is still applicable.

**Comment by sabbyanandan** [comment]
@sachkk76: As it stands, CF-server is at 1.0.0.M4 release and the core (Local-server) is at 1.0.GA. Are you able to persist the stream definitions now? Please confirm.
