### ISSUE TITLE
Investigate Spring Boot 1.4.x upgrade issues

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#748]
Based on this [change] (https://github.com/spring-projects/spring-boot/commit/87fe0b2adeef85c842c009bfeebac1c84af8a5d7) the nested archives inside the app artifact aren't loaded [here] (https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-configuration-metadata/src/main/java/org/springframework/cloud/dataflow/configuration/metadata/ApplicationConfigurationMetadataResolver.java#L210) when getting whitelist properties for the app.

We need to investigate how to handle loading of nested archives when using `1.4.x` version of `spring-boot-maven-plugin`.

**Comment by sabbyanandan** [comment]
We will continue remaining efforts through #851 and #852.
