### ISSUE TITLE
Document how to set an application property for an app when deploying stream?

### ISSUE THREAD

**Issue by sandip0018** [spring-cloud/spring-cloud-dataflow#750]
@ilayaperumalg , @sabbyanandan is there a way by which i can pass and set environment variable in cloud foundry spring cloud dataflow server?
for example in one of my stream sink module depend on environment variable and for that i have to restage the application after setting env variable.
is there any way by which we can pass those details at stream creation time?

Thanks.

**Comment by markpollack** [comment]
We need to document this... hold on a bit.

**Comment by markpollack** [comment]
BTW, for CF we don't support setting env-vars but pass properties in under the SPRING_APPLICATION_JSON env-var that boot apps recognize.  There is an ugly underlying reason for this, but we should address specific env-var setting as well in a future release.  for k8s, i believe we do actually set env-vars.

**Comment by sandip0018** [comment]
Thanks @markpollack for taking time.

**Comment by ilayaperumalg** [comment]
@sandip0018 Could you please ask your *questions* on SO [here] (http://stackoverflow.com/questions/tagged/spring-cloud-dataflow) instead of creating issues at Github.

Thanks!

**Comment by markpollack** [comment]
We also need to document app.* sytnax

**Comment by markpollack** [comment]
Depending on the impl, it may or may not be a proper env-var...but it will be respected by the boot app.

**Comment by sabbyanandan** [comment]
Let's also document the limitation with Boot's "map of maps" and the use of `SPRING_APPLICATION_JSON` as the placeholder to get around it.
