### ISSUE TITLE
Error in docs

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#753]
The text on http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#spring-cloud-dataflow-global-properties says:

This will cause the properties `stream.spring.cloud.stream.kafka.binder.brokers` and `spring.cloud.stream.kafka.binder.zkNodes` to be passed to all the launched applications.

shouldn't that be

This will cause the properties `spring.cloud.stream.kafka.binder.brokers` and `spring.cloud.stream.kafka.binder.zkNodes` to be passed to all the launched applications.

without the `stream` prefix?

**Comment by mbogoevici** [comment]
Yeah that's a copy and paste error :(.
