### ISSUE TITLE
Apps Uris - Fully support rfc1738

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#762]
Currently, you cannot specify fully **rfc1738** compliant **file://** URIs for Apps. E.g. the following will fail:

```
file://localhost/Users/path/to/demo13-0.0.1-SNAPSHOT.jar
```

You can actually create the app registration but when browsing the details the server fails with a message that it cannot find the file. 

Not sure if we should also support Network Shares via that construct, but specifying localhost should be possible. This may also entail additional documentation specifying what is possible and what is not.

For more details see also: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/95

**Comment by sabbyanandan** [comment]
No one requested this in a few years, closing it.
