### ISSUE TITLE
spring cloud dataflow

### ISSUE THREAD

**Issue by sampatkhatri-hexaview** [spring-cloud/spring-cloud-dataflow#763]
Hi,

I want to use spring-cloud-dataflow for my project but i am not able to gather the info about its stability and support for current version. Anyone can let me know if we can use spring-cloud-dataflow in Enterprise level application for production. 

thanks in advance...

**Comment by sabbyanandan** [comment]
Hi, @sampatkhatri-hexaview: As of today, Spring Cloud Data Flow is at [1.0.0.RC1](https://spring.io/blog/2016/06/21/spring-cloud-data-flow-1-0-rc1-released) milestone and we are in the middle of 1.0.0.GA release. In other words, we are very close to the production release. For more details about features and capabilities, please review the [reference guide](http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/). 

Also, questions like this are better preferred to be discussed in stackoverflow. GitHub is for reporting bugs, pull requests, and feature requests.
