### ISSUE TITLE
Docs: Provide OAuth Configuration Example for GitHub

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#770]
- Provide OAuth Configuration Example for GitHub
- Provide link to https://github.com/ghillert/oauth-test-server in order to show a quick example of how to use Spring Security OAuth's authentication server

**Comment by sabbyanandan** [comment]
Perhaps can we also include spring-cloud/spring-cloud-dataflow#767 as part of this PR?
