### ISSUE TITLE
access-token-uri doesn't work with camelCase

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#775]
If I start server with `--security.oauth2.client.accessTokenUri=xxx` it errors with

```
IllegalArgumentException: Could not resolve placeholder 'security.oauth2.client.access-token-uri' in string value "${security.oauth2.client.access-token-uri}"
```

I think `@Value("${security.oauth2.client.access-token-uri}")` in `ManualOAuthAuthenticationProvider` is the root cause of this.

**Comment by ericbottard** [comment]
Yes, I believe at **consumption** point (_e.g._ `@Value`), we should always use camelCase, whereas when passing the value, dash-form is ok. The reverse is not true

**Comment by ghillert** [comment]
Maybe it is better to use *@ConfigurationProperties* generally (?).

I tried changing it to camelCase `@Value("${security.oauth2.client.accessTokenUri}")` but then I get 

```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'security.oauth2.client.accessTokenUri' in string value "${security.oauth2.client.accessTokenUri}"
```

For:

![image](https://cloud.githubusercontent.com/assets/685363/16699873/81277dc4-44f2-11e6-915c-9c2e7ad7fff7.png)

**Comment by jvalkeal** [comment]
I think this is a limitation when using `@Value`. Using a real `@ConfigurationProperties` is probably only way to make this work.

**Comment by sabbyanandan** [comment]
Closing this in favor of https://github.com/spring-cloud/spring-cloud-dataflow/issues/2580.
