### ISSUE TITLE
Split shell project

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#793]
As a user I'd like to create a new shell project, as is happening in https://github.com/spring-cloud/spring-cloud-dataflow-server-yarn/issues/118. Trouble is that `spring-cloud-dataflow-shell` is a fatjar and while it works as a jar artifact, size is large and effectively separate project ends up having fatjar inside a fatjar.

I propose moving core classes into `spring-cloud-dataflow-shell-core` and keeping `spring-cloud-dataflow-shell` as a farjar generation project.

**Comment by ghillert** [comment]
As follow-up I created: https://github.com/spring-cloud/spring-cloud-dataflow/issues/906
