### ISSUE TITLE
Integration test for streams.

### ISSUE THREAD

**Issue by Mwea** [spring-cloud/spring-cloud-dataflow#794]
I wonder how users are supposed to test streams without having to launch the Dataflow server, a shell, registers two applications then launch the streams.. ? 
These operations are pretty long, is there any way to code unit test for streams ?

**Comment by sabbyanandan** [comment]
The existing unit-tests (with mocks) for [streams](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamControllerTests.java) could be useful. Alternatively, you could use the [DataflowTemplate](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-rest-client/src/test/java/org/springframework/cloud/dataflow/rest/client/DataflowTemplateTests.java) to perform similar operations. For e2e integration tests, please refer to [spring-cloud-dataflow-acceptance-tests](https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests).
