### ISSUE TITLE
Deploy error shows successful deployment

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#802]
In short I made sure deploy on yarn will eventually throw `TimeoutException`. I think we should notify user that error happened as it's impossible for a user to get further info because there's no deployment id and `stream list` will just show `undeployed`.

```
2016-07-20 06:50:42.418  WARN 20756 --- [nio-9393-exec-5] o.s.c.d.s.c.StreamDeploymentController   : Exception when deploying the app StreamAppDefinition [streamName=foostream, name=time, registeredAppName=time, properties={spring.cloud.stream.bindings.output.producer.requiredGroups=foostream, spring.cloud.stream.bindings.output.destination=foostream.time}]: java.util.concurrent.TimeoutException

dataflow:>stream create --name foostream --definition "time|hdfs --rollover=100" --deploy 
Created and deployed new stream 'foostream'

dataflow:>stream list
╔═══════════╤════════════════════════╤══════════╗
║Stream Name│   Stream Definition    │  Status  ║
╠═══════════╪════════════════════════╪══════════╣
║foostream  │time|hdfs --rollover=100│undeployed║
╚═══════════╧════════════════════════╧══════════╝
```

**Comment by sabbyanandan** [comment]
We have improved this area with more granular statuses and relying on actual outcome and error messages. Let's double check this on the 2.x foundation.

**Comment by sabbyanandan** [comment]
Since 1.4.x, we have a redesigned and reimplemented the status aggregation for Streams and Tasks. This also includes several improvements to runtime and deployment statuses. Marking this as done.
