### ISSUE TITLE
Hard-coded Spring boot version in reference manual

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-dataflow#803]
I was reading [this section](http://docs.spring.io/spring-cloud-stream/docs/1.0.2.RELEASE/reference/htmlsingle/index.html#_getting_started) of the doc and stumbled upon the following:

> To get started with creating Spring Cloud Stream applications, visit the Spring Initializr and create a new Maven project named "GreetingSource". Select Spring Boot version 1.3.4 SNAPSHOT

`start.spring.io` offers the latest and greatest so that version isn't available anymore. Maybe that section should be rephrased along the lines of "select at least Spring Boot 1.3"?

**Comment by markpollack** [comment]
Good point , will fix

**Comment by ilayaperumalg** [comment]
We can add more description on this based on the outcome of [this] (https://github.com/spring-cloud/spring-cloud-dataflow/issues/748)

**Comment by ilayaperumalg** [comment]
Since this depends on #748, may be we can address this in next sprint (after #748 is complete).

**Comment by ilayaperumalg** [comment]
This doc actually came from `spring-cloud-stream-overview.adoc` from [here] (https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-core-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc). We no longer use this doc in SCDF. Is that ok? In any case, we will update the description in `spring-cloud-stream`.  If so, we can move this to SCSt. @sabbyanandan what do you think?

**Comment by markpollack** [comment]
Sounds good to me (taking off my sabby hat now) :)

**Comment by ilayaperumalg** [comment]
This issue was moved to spring-cloud/spring-cloud-stream#673
