### ISSUE TITLE
Links (bit.ly) to the Spring Cloud Stream Apps starter properties are not version dependent

### ISSUE THREAD

**Issue by hvandenb** [spring-cloud/spring-cloud-dataflow#806]
All the bit.ly links are always resolve to the SNAPSHOT links. The links in the documentation are not dependent on the version of the documentation, which causes deployment issues, such as:

> dataflow:>app info source:tcp
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: failed to resolve MavenResource: org.springframework.cloud.stream.app:tcp-source-rabbit:jar:1.0.0.BUILD-SNAPSHOT

Here is an example of the incorrect links for the RELEASE page.

> Maven based Stream Applications with RabbitMQ Binder: bit.ly/stream-applications-rabbit-maven
> Maven based Stream Applications with Kafka Binder: bit.ly/stream-applications-kafka-maven
> Docker based Stream Applications with RabbitMQ Binder: bit.ly/stream-applications-rabbit-docker
> Docker based Stream Applications with Kafka Binder: bit.ly/stream-applications-kafka-docker

Should have a release specific link for app import.

**Comment by sabbyanandan** [comment]
We generate release specific bit.ly links and the default as you listed resolves to SNAPSHOT bits. The table listed in [stream](http://cloud.spring.io/spring-cloud-stream-app-starters/#stream-app-starters-and-spring-cloud-data-flow-) and [task](http://cloud.spring.io/spring-cloud-task-app-starters/#task-app-starters-and-spring-cloud-data-flow-) app-starters project page should be helpful and yes, we will clarify this in the reference guide.

**Comment by sabbyanandan** [comment]
This is resolved via https://github.com/spring-cloud/spring-cloud-dataflow/pull/944.
