### ISSUE TITLE
Add support to delete *all* tasks

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#812]
As a developer, I'd like to add  `task all destroy` commands, so I can either individually or in bulk destroy all the tasks.

**Acceptance:**
- new REST-APIs to support "task destroy" commands are available
- shell and dashboard can adapt to the REST-APIs
- similar to streams, the relevant validations are included at the task controller
- unit tests included
- docs updated

child of #2720

**Comment by cppwfs** [comment]
Just to clarify.  We do support "task destroy" (including tab support)  but not "task all destroy" .
