### ISSUE TITLE
Add docs section for creating custom source, processor, sink and task applications

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#815]

**Comment by markpollack** [comment]
one section for task one for stream components.

**Comment by sabbyanandan** [comment]
This is addressed https://github.com/spring-cloud/spring-cloud-dataflow/commit/dc5199ac88f5a3a152a1dbd0de2801a53e39f080 and via https://github.com/spring-cloud/spring-cloud-dataflow/commit/6be4ff1ded2f72f51d26b0beab1eb4197bad5eec.
