### ISSUE TITLE
Ensure all Rest Endpoints are wired up for tests

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#825]
For RestDocs to work its magic, need the entire REST api to be live for the tests. This includes for example the `RootController`.

**Comment by sabbyanandan** [comment]
We will have to review the following controllers for RestDocs coverage, compatibility, and completeness. 

**infra**
 - [ ] AboutController.java
 - [ ] ToolsController.java
 - [ ] FeaturesController.java
 - [ ] RootController.java
 - [ ] MetricsController.java

**apps**
 - [ ] RuntimeAppsController.java
 - [ ] AppRegistryController.java

**jobs**
 - [ ] JobExecutionController.java
 - [ ] JobInstanceController.java
 - [ ] JobStepExecutionController.java
 - [ ] JobStepExecutionProgressController.java

**streams**
 - [ ] StreamDefinitionController.java
 - [ ] StreamDeploymentController.java

**tasks**
 - [ ] TaskDefinitionController.java
 - [ ] TaskExecutionController.java

**Comment by sabbyanandan** [comment]
All the stories associated with this epic is complete; hence, the scope of this story is complete as well.
