### ISSUE TITLE
Create a Java DSL for Streams

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#827]
For integration testing (and possibly as general purpose option), create a Java DSL in order to create Streams.
- Analyze Spring XD DSL
- Look at alternatives e.g.:
  - Google Dataflow
  - Apache Beam (http://beam.incubator.apache.org/)

**Comment by jvmlet** [comment]
Let me I add few more points :
 - It also would be great if the stream definition could be deployed from java artifact the same way as app.
 - The IDE extension (for IntelliJ/Eclipse) to provide the same user experience of stream development as Flo is another suggestion for spring-cloud-dataflow portfolio. (Microsoft .NET Workflow designer in Visual Studio  might be used a  a reference  of this feature request- they provide API, Visual Workflow Designer and XAML editor to define the workflow)

Thanks

**Comment by sabbyanandan** [comment]
The Java DSL support is now available (and evolving) in [spring-cloud-dataflow-acceptance-tests](https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests).
