### ISSUE TITLE
Double-check consistent usage of HTTP Verbs and Statuses

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#831]
Verify that all REST Api Controllers use the same HTTP verbs and HTTP Status codes consistently. 

I believe we should be good for HTTP verbs but there might be still some odd HTTP Status codes being used.

Also, verify that the usages throughout the API follow best practices.

**Comment by ghillert** [comment]
## Spring Cloud Data Flow Usage of Status Codes and Verbs:

`DELETE` -- >HttpStatus.OK
`POST` --> HttpStatus.CREATED
`PUT` for Restart --> HttpStatus.OK

Exceptions may lead to:

* HttpStatus.CONFLICT - 409
* HttpStatus.UNPROCESSABLE_ENTITY -422
* HttpStatus.NOT_FOUND 404
* HttpStatus.INTERNAL_SERVER_ERROR 500 Internal Server Error (should be a bug, if it occurs)

## Rest Doc Sample Usage of HTTP Status Codes:
 
| Status code | Usage

| `200 OK`
| The request completed successfully

| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's `Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information

| `404 Not Found`
| The requested resource did not exist

*One of the question, for example, is:*

| When deleting a resources should we return *OK (200)* or better *NN CONTENT (204)* 

Lastly, we should also reconcile the following 3 status codes:

* 400 Bad Request
* 409 Conflict
* 422 Unprocessable Entity

**Comment by sabbyanandan** [comment]
This has been open for a while, and I don't see us revising them anymore.
