### ISSUE TITLE
Spring Cloud Dataflow Shell: Jackson2Hal module registered twice

### ISSUE THREAD

**Issue by FrontierPsychiatrist** [spring-cloud/spring-cloud-dataflow#840]
In the shell project, file `ConfigCommands.java` the `Jackson2HalModule` is registered twice in the Jackson object mapper. I think this is not necessary.

https://github.com/spring-cloud/spring-cloud-dataflow/blob/e898a04225e834f12b85c75f466537b848d34ffb/spring-cloud-dataflow-shell/src/main/java/org/springframework/cloud/dataflow/shell/command/ConfigCommands.java#L284

https://github.com/spring-cloud/spring-cloud-dataflow/blob/e898a04225e834f12b85c75f466537b848d34ffb/spring-cloud-dataflow-shell/src/main/java/org/springframework/cloud/dataflow/shell/command/ConfigCommands.java#L293

**Comment by ilayaperumalg** [comment]
Hi @FrontierPsychiatrist 

Thanks for reporting this. We'll address this. Also, please feel free to submit a PR if possible.
