### ISSUE TITLE
Correct documentation on property whitelisting

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#842]
As a user, while developing a custom application and adding support for property whitelisting, the property key `configuration-properties.classes` is defined one-way in the [docs](http://docs.spring.io/spring-cloud-dataflow/docs/1.0.0.RELEASE/reference/htmlsingle/#spring-cloud-dataflow-stream-app-whitelisting), but in the example the token `-properties` is missing.

**Comment by ilayaperumalg** [comment]
@sabbyanandan Good catch. It was a mistake. The key should be 'configuration-properties.classes'

**Comment by ilayaperumalg** [comment]
I don't find a branch to issue the PR for `1.1.0.M1`. Hence, submitted this PR for 1.0.1. What am I missing?
