### ISSUE TITLE
Intermittent failure to deploy stream on local server

### ISSUE THREAD

**Issue by RemonSinnema** [spring-cloud/spring-cloud-dataflow#847]
Every so often I get this message when deploying my stream on a local SCDF server:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Embedded servlet container failed to start. Port 39902 was already in use.
```
The actual port displayed varies.

**Comment by RemonSinnema** [comment]
Note that I assign all stream apps a unique `server.port` property, and this still happens.

**Comment by sabbyanandan** [comment]
@RemonSinnema: Thanks for reporting! Is this repeatable? If yes, could you share the steps? Also, it'd be great if you can share the server/app versions and as well, the stream definitions, so we could try and replicate it.

**Comment by RemonSinnema** [comment]
It's not 100% repeatable. As I reported originally, I get this "Every so often".

I'm using version `1.0.0.RELEASE`.

Our stream consists of all custom apps, which I unfortunately can't share. I've seen this problem both with embedded Tomcat and with Jetty.

BTW, I'm still unclear on where this port number comes from. The duplicate port that is reported is always over 10000, while I assign `server.port` properties under 10000.

**Comment by RemonSinnema** [comment]
The port seems to be the one that communicates with Kafka rather than the actual `server.port`. Could this be a race condition when multiple apps in the stream are started in parallel and are configured to talk to Kafka?

**Comment by RemonSinnema** [comment]
Looks like `server.port` is not picked up from the app's `application.properties`. Specifying it as part of the stream definition using `--server.port=` works fine.

**Comment by ericbottard** [comment]
When using the local deployer, there are two cases:
1) either you don't specify a `--server.port` in the stream definition for your app, and one will be [dynamically allocated](https://github.com/spring-cloud/spring-cloud-deployer/blob/b2e0a2eb8736fdbd6b07b67fee1b977aaef53093/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployer.java#L117-L118) and passed as an application property (thus overriding what you put in `application.properties`, as you state)
2) or you did pass one as an application property yourself, and it will be honored (but then you're responsible for making sure it's available).

In case 1), we try to find an available port, but if you're *very* unlucky, it could indeed be taken in the interim. Would be nice to make sure this is indeed your issue...

**Comment by RemonSinnema** [comment]
I think we make ourselves unlucky by using an overloaded machine for CI; the condition happened quite frequently. However, since we've put `--server.port` into the stream definition, the problem hasn't resurfaced.

I have to say that it's not intuitive that the `server.port` property from `application.properties` is ignored for a local deployment with a single instance. Would be good to clearly document that.

**Comment by ericbottard** [comment]
Closing this issue, and created a different one to address documenting the `server.port` behavior.

Thanks!
