### ISSUE TITLE
Remove InMemory and Redis repository implementation from SCDF code-base

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#848]

**Comment by ilayaperumalg** [comment]
The idea was to keep these repository implementations inside `tests` as various implementation flavours as well as test using them.

**Comment by ilayaperumalg** [comment]
I am not sure if we really want to remove these implementations. I think one of the reasons we want to keep these repository implementations is to have these as references for any users who want to create their own repo.
