### ISSUE TITLE
Test server-side paging and sorting capabilities

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#853]
As a developer, I'd like to test whether server-side paging and sorting capabilities are functional today. 

**Findings:**
It looks like we are using `org.springframework.data.domain.Pageable` for all our repository calls. THEORETICALLY it should all work. Did we ever test this though in practicality? Several of our calls do explicitly call other services, augment the returned objects etc.

**Acceptance:**
Verify whether paging and sorting truly work today.

This is related to spring-cloud/spring-cloud-dataflow#257.

**Comment by ghillert** [comment]
The following list the current state of **paging** and **sorting** in _Spring Cloud Data Flow_. 

## /apps

**Paging**:  NOT IMPLEMENTED
**Sorting**: NOT IMPLEMENTED

```java
List<AppRegistration> list = new ArrayList<>(appRegistry.findAll());
for (Iterator<AppRegistration> iterator = list.iterator(); iterator.hasNext(); ) {
	ApplicationType applicationType = iterator.next().getType();
	if (type != null && applicationType != type) {
		iterator.remove();
	}
}
```
## /streams/definitions

**Paging**:  Working
**Sorting**: NOT IMPLEMENTED

```
http://localhost:9393/streams/definitions?size=5&sort=name,desc
```

Issue is in `AbstractRdbmsKeyValueRepository`.

## /tasks/definitions 

**Paging**:  Working
**Sorting**: NOT IMPLEMENTED

Same issue as above as using `repository.findAll(pageable)`, which will rely on `AbstractRdbmsKeyValueRepository`.

## /runtime/apps

**Paging**:  NOT IMPLEMENTED
**Sorting**: NOT IMPLEMENTED

Cannot be implemented at present time. The necessary logic is inverted at present time. Starts with `this.streamDefinitionRepository.findAll()` and uses then `appDeployer.status(id))` to get the `AppStatus`. 

In order for paging and sorting to work, the relevant logic (first call) should be provided by the `AppDeployer`. We need some form to query the deployer for run-time-statuses - Right now, all the deployer has is:

```
AppStatus status(String id);
```

## /runtime/apps/{appId}/instances

**Paging**:  NOT IMPLEMENTED
**Sorting**: NOT IMPLEMENTED

May not be necessary for this endpoint and In-memory sorting/search might be okay.

## /tasks/executions

**Paging**:  Working
**Sorting**: NOT IMPLEMENTED

The sort parameter of `Pageable` is Ignored.

`http://localhost:9393/tasks/executions?page=0&size=3&sort=executionId,asc`

## /jobs/executions
