### ISSUE TITLE
Introduce strategy for retrieving metadata

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#855]
As a developer, I'd like to introduce a strategy for retrieving application metadata. 

**Acceptance:**
- strategy takes both maven and docker artifacts into account

**Comment by ilayaperumalg** [comment]
@sabbyanandan I missed the context for this story. Could you give an example of what kind of metadata we try to retrieve from the application? Is it different from what we currently do via `app info`?

**Comment by ericbottard** [comment]
Nope, this is what we have for `app info`, but introducing a dynamic Strategy for boot apps for which we have access to the file vs Docker (impl TBD). Also, this could have been a way to support boot 1.3 vs 1.4, although the direction I'm heading towards uses dynamic selection a level below (once we know it's boot, selecting the layout as a second level strategy)
