### ISSUE TITLE
Add a REST endpoint to stop parent and child Task executions

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#858]
As a developer, I'd like to add support to stop all the parent and child the task executions. 

**Acceptance:**
- New API to stop an already running Task is added and exposed in the Root Controller
- New API is included in the default security/role mapping 
- Include new RESTdocs tests
- Integrate with RESTdocs auto-docs generation process

**Comment by Rostish** [comment]
@sabbyanandan 
Good day.
Could you give some information about this issue if you are going to start implement it in close future?
