### ISSUE TITLE
Document deployment property support for Tasks

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#859]
_From @sabbyanandan on December 9, 2015 18:36_

As a user, I'd like to launch tasks with *deployment properties*, so I can define how the deployment will be orchestrated.

**Acceptance:**
* Following task definition accepts deployment manifest to override certain behavior of the `sampleJob` application
```
task create myjob --definition "sampleJob"

task launch myjob --properties "app.sampleJob.foo=bar"
```
* Deployment manifest is an optional DSL attribute for `task` launches.

_Copied from original issue: spring-cloud/spring-cloud-task#29_

--------------------

**UPDATE:** [9/9/2016]
This is already supported for tasks at the event of launching; however, there aren't any docs around this feature in the reference guide, so I'm converting this to a doc story.

**Comment by markfisher** [comment]
shouldn't that be `task launch` instead of `task deploy`?

**Comment by cppwfs** [comment]
Yes.  This  story goes back to December.

**Comment by ilayaperumalg** [comment]
How does this different from what we currently have as `--properties` and `--propertiesFile` options for `task launch` command?

Also, are we expecting to see more task applications chained in the task `definition` to distinguish the properties using the prefix `--app.` inside the `--properties` values? If so, Is that the scope of this story?

**Comment by sabbyanandan** [comment]
The original scope of this story is to provide `--properties` and `--propertiesFile` options at the time of task launch event and given that is already supported, this story is not relevant anymore.

**Comment by ilayaperumalg** [comment]
But, we converted this story to update `documentation`. didn't we?

**Comment by sabbyanandan** [comment]
You're correct! I did update the story and then I lost my mind.

**Comment by ilayaperumalg** [comment]
After some investigation, it looks like we don't require any `deployment` properties for the task being launched (may be in future we might need - for partition properties may be?) while we still need the properties to be passed as `command-line` arguments for the task app.

Also, I notice that the task launcher implementations don't use the `deployment` properties passed via task.launch() operation.

**Comment by cppwfs** [comment]
We do support the ability to allow users to set the deployment properties for partitions.   I can't see why we would need it per se'.   @mminella may disagree.

**Comment by ilayaperumalg** [comment]
But at least the passing of `deployment` properties doesn't seem to work as of now. Only the `command-line args` properties passing works.

**Comment by cppwfs** [comment]
After some thought, there could be cases for deployment properties to increase the memory size for the task for example.  So sounds like there may be another story that would enable deployment properties for tasks.
