### ISSUE TITLE
DataflowTemplate - Assert that passed-in RestTemplate fulfills requirements

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#871]
As described in https://github.com/spring-cloud/spring-cloud-dataflow/issues/870, a `RestTemplate` with specific requirement is needed when creating a new `DataflowTemplate`. 

When a `RestTemplate` is passed into a `DataflowTemplate`, we should make assertion whether the passed in `RestTemplate` fulfills the requirements. Currently, when someone passes naïvely a `new RestTemplate()`, the user will end up with `NullPointer` exceptions.

**Comment by ericbottard** [comment]
This is no longer an issue given the way we took care of #870
