### ISSUE TITLE
Tasks don't always get the correct driver-class-name passed in

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#879]
Seems like the default driver `org.h2.Driver` gets passed in even when the SCDF server is started using `--spring.datasource.driver-class-name=org.mariadb.jdbc.Driver`.  This doesn't happen when the SCDF server is started with `--spring.datasource.driverClassName=org.mariadb.jdbc.Driver`. 

Something is off the way these properties are handled.

**Comment by ilayaperumalg** [comment]
@trisberg I think we also need to pass `--spring.datasource.url` and other required `datasource` properties when we override the `driverClassName` as well. 

In the case you mentioned, the database gets initialized with mariadb driver while the datasource URL still points to the default `H2`. I think that causes the issue.

**Comment by cppwfs** [comment]
To resolve this issue we need to add spring.datasource.driver-class-name to the `DefaultTaskService` .
For example: https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskService.java#L82 
and 
https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskService.java#L141

**Comment by ilayaperumalg** [comment]
IMHO, I don't see this as an issue as one has to override all the datasource properties if we want to override (given we have defaults for the datasource properties for local server).

**Comment by trisberg** [comment]
IMHO if I use `spring.datasource.driver-class-name` or `spring.datasource.driverClassName` as the property name shouldn't make a difference - it does today.

**Comment by cppwfs** [comment]
Right now we check for the datasource properties specifically to pass on to
the tasks.  Should we search for spring.* and pass them all to the task.
It would work but there could be side effects.

**Comment by ilayaperumalg** [comment]
> IMHO if I use spring.datasource.driver-class-name or spring.datasource.driverClassName as the property name shouldn't make a difference - it does today.

I meant having the properties `spring.datasource.url`, `spring.datasource.driver-class-name` and all the required properties not both the different relaxed names of driver class name itself. 

> I think we also need to pass --spring.datasource.url and other required datasource properties when we override the driverClassName as well.

**Comment by ilayaperumalg** [comment]
> IMHO if I use spring.datasource.driver-class-name or spring.datasource.driverClassName as the property name shouldn't make a difference - it does today.

ok, I see it. Having just the driver class name as cmdline arg mislead me to look at different issue.  Now I see you mean :-) Yeah, we shouldn't probably use direct matching of the properties using `driverClassName`. will fix it.
