### ISSUE TITLE
Explore options to simplify stream binding deployment properties

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#889]
As a developer, I'd like to study approaches to simplify the use of stream binding properties at the time of stream deployment.

**Comment by ilayaperumalg** [comment]
The simplification strategy is to provide support for both `.properties` and `.yml/.yaml` files as `--propertiesFile` option during stream `deployment`.

**Comment by ilayaperumalg** [comment]
This comes down to fixing https://github.com/spring-cloud/spring-cloud-dataflow/issues/288
