### ISSUE TITLE
Discuss supporting separate databases for stream and task/batch data. 

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#893]
While discussing what to set the config property SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_SERVICES with @ericbottard the idea of supporting two databases, one for streams and one for tasks/batch was raised.

**Comment by cppwfs** [comment]
What is the use case?  Security?

**Comment by ericbottard** [comment]
No use case in particular, but those two databases have no reason to be the same.

**Comment by cppwfs** [comment]
or separated for that matter.  They are used by the same app.

**Comment by trisberg** [comment]
well, stream repo and app registry used to be in Redis, so if we don't enable tasks we could use another type or another sql db for the stream and app defs, if tasks are enabled I don't see much need for separating them, but I guess we could if we wanted to

**Comment by mminella** [comment]
One question about this...can you bind the same service to a CF app twice?  AKA if I wanted both my repositories to live in the same service instance (a common use case I'd imagine), can you do that?

**Comment by trisberg** [comment]
AFAIK you would have to configure your repos to use the same instance, so with two datasources you wouldn't be able to rely on auto-configuration, if I remember correctly

**Comment by cppwfs** [comment]
That is correct.

**Comment by sabbyanandan** [comment]
This has been open for a while, and I don't see us separating the stream vs. task DB footprint as independent instances.
