### ISSUE TITLE
where can i find the dockerfiles of the provided sources and sinks

### ISSUE THREAD

**Issue by Jaware** [spring-cloud/spring-cloud-dataflow#896]
like springcloudstream/log-sink-kafka,where is the dockerfile? i have met with a problem and have to write the file myself

**Comment by ilayaperumalg** [comment]
Hi,

This [page] (https://github.com/spring-cloud/spring-cloud-stream-app-starters/blob/master/spring-cloud-stream-app-starters-docs/src/main/asciidoc/overview.adoc) has some detail about it.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-app-starters#227
