### ISSUE TITLE
how to custom my dataflow without using this project 

### ISSUE THREAD

**Issue by Jaware** [spring-cloud/spring-cloud-dataflow#902]
i have followed the guide from dataflow 1.0.1 doc,however the custom properties can not show on the page,only using app-starters like @Import(org.springframework.cloud.stream.app.file.sink.FileSinkConfiguration.class) can show the custom properties on the ui page.

**Comment by Jaware** [comment]
image
configuration-properties.classes=com.example.FileSinkProperties

@SpringBootApplication
@EnableBinding(Channel.class)
@EnableConfigurationProperties(FileSinkProperties.class)
public class Application {

public static void main(String[] args) {
    SpringApplication.run(Application.class, args);
}
}

image

**Comment by ilayaperumalg** [comment]
I think this has got something to do with white-listing of properties. You can refer more detail [here] (https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc#whitelisting-application-properties)

**Comment by ilayaperumalg** [comment]
or, do you mean you followed the same content but still those properties are not visible?

**Comment by ilayaperumalg** [comment]
Also, make sure you have this dependency:
```
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
```
in your app to make sure configuration metadata is generated.

**Comment by Jaware** [comment]
thanks,the dependency works,but docs do not show this very important point,which is very bad!
