### ISSUE TITLE
Polish whitespace issues in SCDF Shell

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#906]
As a follow-up to #793 - https://github.com/spring-cloud/spring-cloud-dataflow/issues/793

As #793 only moved files, without changing their contents this was not addressed then. 

However, there are quite a few white-space issues in the Shell-core module.

**Comment by sabbyanandan** [comment]
This is not a pressing item from a technical debt pov. Closing it for now.
