### ISSUE TITLE
[proposal] Support for 'standalone' and 'application group' support

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-dataflow#915]
Currently there are four different [types](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/ApplicationType.java) of applications:
- source
- processor
- sink
- task

This issue is to track the proposal of adding an additional application type, `standalone`.
A standalone application defines how a potentially non Spring Cloud Stream/Task Spring Boot app (no binder needed) can be deployed in a Data Flow context.

The standalone application type could be useful for:
- Apps that supplement Streams/Tasks and could be deployed using the same tooling. For instance deploying a custom Spring Cloud Config Server, etc.
- Avoids having to implement and potentially deploy a separate "deployer server" for deploying standalone apps using the Spring Cloud Deployer abstraction
- Completes what it says on the [box](http://cloud.spring.io/spring-cloud-dataflow/), "cloud-native orchestration service for composable microservice applications on modern runtimes" 😁

I have taken a stab at a basic implementation on my fork (`standalone` branch): https://github.com/donovanmuller/spring-cloud-dataflow/commit/64da383ce053abee5055bd8444305fca0c5c3dc5. In addition, I've written a [blog post](https://blog.switchbit.io/introducing-standalone-applications-to-spring-cloud-data-flow/) demonstrating how the new standalone application type could work.

As mentioned in the [post](https://blog.switchbit.io/introducing-standalone-applications-to-spring-cloud-data-flow/), we are going to use this internally to faciliate a consistent way of deploying both streams, tasks and current Spring Boot apps from the same tooling.

However, I'm not sure if this proposed new application type fits into the grander scheme of things for Data Flow? This issue is to open a conversation around whether or not it has merit.
Given the above, I've not opened a PR for my basic implementation, although would be more than happy to contribute as much as possible.

**Comment by sabbyanandan** [comment]
Hi, @donovanmuller - Thanks for this proposal. 😄 

There's a spike in-progress in the `spring-cloud-deployer` project [[#99](https://github.com/spring-cloud/spring-cloud-deployer/issues/99)] with the scope to deploy any arbitrary application and as well, the support for application-grouping. This deployment option would eventually bubble up to SCDF's DSL/GUI, too. 

@markfisher has been experimenting with the design and it'd be great to collaborate with you on this feature.

**Comment by geoand** [comment]
:+1: for this feature!

**Comment by donovanmuller** [comment]
To add to the standalone application type, I have also drafted a take on the Application Group feature tracked by https://github.com/spring-cloud/spring-cloud-deployer/issues/99 (albeit with slightly different requirements). This was added because we needed the ability to push a single artifact through our CI/CD pipeline (facilitated by the [spring-cloud-dataflow-maven-plugin](https://github.com/donovanmuller/spring-cloud-dataflow-maven-plugin)) that would enable the deployment of multiple streams/standalone apps/ etc. related to a logical solution.

There is a detailed write up about it [in this blog post](https://blog.switchbit.io/a-take-on-application-groups-with-spring-cloud-data-flow/).

Having added these features and with the need for possibly more extension in the future, I'd like to get feedback on working on a plugin architecture that would allow extensions like this to be externally bolted on to the core data flow project, thereby not relying on the core project to adopt new features that might not make sense for the roadmap of the project and additionally, community [forks](https://github.com/donovanmuller/spring-cloud-dataflow/tree/application-group) need not be constantly rebased with upstream changes.

The plugin architecture could possibly provide lifecycle hooks. 
So hooks into things like [parsing the (with possible extensions) DSL](https://github.com/donovanmuller/spring-cloud-dataflow/blob/application-group/spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/ApplicationGroupParser.java), additional [application types](https://github.com/donovanmuller/spring-cloud-dataflow/blob/application-group/spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/ApplicationType.java#L51), [custom definition types](https://github.com/donovanmuller/spring-cloud-dataflow/blob/application-group/spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/StandaloneDefinition.java), [registration](https://github.com/donovanmuller/spring-cloud-dataflow/blob/application-group/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/ApplicationGroupDefinitionController.java), [deployment](https://github.com/donovanmuller/spring-cloud-dataflow/blob/application-group/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/ApplicationGroupDeploymentController.java) and so forth.

With this capability added to the core data flow project, composing a new data flow server project with additional custom functionality, would simply require a dependency on data flow core and additional plugins. The configuration could be achieved through the usual Spring (auto) configuration mechanisms.

@sabbyanandan Would this be something that the team would be interested in supporting, if contributed?

**Comment by sabbyanandan** [comment]
The finalized design proposal is [here for review](https://docs.google.com/document/d/1-zN2j6dBD3HTzvowL7XceiNvDVm1Rk8mK84N3lJH2RI/edit). We will be addressing the feature capabilities in incremental chunks and the first step in the process will be tackled via #1122 and #1123. For any other open items that need to be discussed, let's continue the conversation either in the open issues or google doc. I will close this issue for now.
