### ISSUE TITLE
Bulk import URI is mouldy

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-dataflow#917]
The user guide uses this URI: http://bit.ly/stream-applications-kafka-maven, which is for 1.0.0 snaphots. I guess that's old and should be replaced?

**Comment by sabbyanandan** [comment]
Until we breakdown the app-starters project into separate repos and simplify the associated (monolith) release cycles, let's at least update the docs to use the latest app-starter releases. Perhaps the best interim solution would be to add the [table](http://cloud.spring.io/spring-cloud-stream-app-starters/#stream-app-starters-and-spring-cloud-data-flow-) that we list in the project page.
