### ISSUE TITLE
Tokenize local.deployer.javaCmd

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-dataflow#920]
If the user wants to set JVM args for the local deployer, right now it's not easy (or possible). It seems like `local.deployer.javaCmd` could be used, but it has to be a valid executable the way it is now. If we just tokenized it (split on spaces) and put the result at the start of the process builder command it would work I think.

**Comment by sabbyanandan** [comment]
We are to standardize the JVM option settings via https://github.com/spring-cloud/spring-cloud-deployer/issues/116; once this is done, we will revisit the propagation of those arguments at the deployer implementation(s) and at each application level.

**Comment by sabbyanandan** [comment]
Hi, @dsyer. Here's the [latest](http://docs.spring.io/spring-cloud-dataflow/docs/1.2.2.RELEASE/reference/htmlsingle/#getting-started-application-configuration) on how you can override the JVM settings at each application level. Please let us know if you see any other concerns with it.

**Comment by dsyer** [comment]
The docs are clear, I the sense that they tell me precisely that I can't do what I asked, at least in the cases that are implicitly covered by that one paragraph. It's not very clear if these docs apply to all deployers, or maybe I need to read it more than twice that understand it. Is that what you mean? Is it part of the deployer contract (seems unlikely)? The property names imply that it is just for the "local" deployer, but it's important to know what is general, and what is specific.

Also, a tiny niggle, but maybe a little able would be easier to read than a code snippet? It's basically tabular information (list of property names for lus descriptions).

**Comment by sabbyanandan** [comment]
You're correct, it is not an SPI contract. What we tried is to consolidate the usage of _javaopts_ in the local-deployer and the docs linked above is specifically for the local-server. Likewise, we have similar reference guides (and project sites) for each of the server implementations - we try not to mix the docs content.

There are also differences in how the override can be setup in each server variant. In k8s, we use the `spring.cloud.deployer.kubernetes.environmentVariable` key and the value of this property can include options like: `JAVA_OPTIONS=-Xmx64m`. For CF, we wrap the command line arguments of each application via [JBP_CONFIG_JAVA_MAIN](https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/blob/master/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java#L241) property.

I agree it could be confusing given the different usage patterns. To be consistent, it might be better to have a separate section in each guide that goes into the details of JVM args and the usage patterns.

**Comment by sabbyanandan** [comment]
@jvalkeal: This issue has been open for a long time (I am attempting to clean things up). Could you review the requirement and see how better or alternatively we can address this using the local-deployer?

**Comment by sabbyanandan** [comment]
Super old; closing.
