### ISSUE TITLE
DataSource and H2 server configuration looks wrong

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-dataflow#926]
There are 2 alternative configurations for the data source transaction manager and initialization configuration. One sets up an H2 embedded server as well, and the server has an extra (different) condiftion. Both have identical bean definitions (with different names) for the transaction manager and data source initializer, so the duplication is confusing. Also the two configurations and guarded by conditions that are not the inverse of each other.

All of this might be intentional, but it's hard to reason about because the conditions are long:

In `DataFlowServerConfiguration` in the H2 server bean:

```
@ConditionalOnExpression("#{'${spring.datasource.url:}'.startsWith('jdbc:h2:tcp://localhost:') && '${spring.datasource.url:}'.contains('/mem:')}")
```

On the config class surrounding it:

```
@ConditionalOnExpression("#{'${spring.datasource.url:}'.startsWith('jdbc:h2:tcp://localhost:') && '${spring.datasource.url:}'.contains('/mem:')}")
```

(these look identical, so one is either redundant or wrong).

And on the other configuration class, where there is a transaction manager, and an initializer:

```
@ConditionalOnExpression("#{!'${spring.datasource.url:}'.startsWith('jdbc:h2:tcp://localhost:') && !'${spring.datasource.url:}'.contains('/mem:')}")
```

So if there is an H2 database with TCP but not in memory, then I think this means the database is never initialized (it's tricky to know what was intended, but maybe it is better to always initialize and ignore errors in that case?).

There is also a `TaskConfiguration` with the same pair of conditions:

```
@ConditionalOnExpression("#{'${spring.datasource.url:}'.startsWith('jdbc:h2:tcp://localhost:') && '${spring.datasource.url:}'.contains('/mem:')}")
```

and

```
@ConditionalOnExpression("#{!'${spring.datasource.url:}'.startsWith('jdbc:h2:tcp://localhost:') && !'${spring.datasource.url:}'.contains('/mem:')}")
```

So if there is an H2 database with TCP but not in memory, then there is no `JobRepository`. This seems like a mistake (and it causes the app to barf on start up).

I think make some custom annotations for the conditions could be used to make their intention clearer. Also some javadocs might help. And there should always be a `JobRepository` right?

**Comment by markpollack** [comment]
Ideally should be a `JobRepository` only if the property `spring.cloud.dataflow.features.tasks-enabled` is true (which it is by default)

**Comment by dsyer** [comment]
Ideally, what I'd like to be able to do is set up an H2 database in a separate process (with in-memory data or without), and have everything work. So far I can't see a way to do that without duplicating large sections of dataflow config.

**Comment by dsyer** [comment]
Also, these two beans have a `@DependsOn` for a conditional bean, so when the condition isn't satisfied Spring barfs trying to create them (the dependency doesn't exist):

```
		@Bean
		@DependsOn("initH2TCPServer")
		public DataSourceTransactionManager transactionManagerForServer(DataSource dataSource) {
			return new DataSourceTransactionManager(dataSource);
		}

		@Bean
		@DependsOn("initH2TCPServer")
		public DataflowRdbmsInitializer dataflowRdbmsInitializer(DataSource dataSource, FeaturesProperties featuresProperties) {
			DataflowRdbmsInitializer dataflowRdbmsInitializer = new DataflowRdbmsInitializer(featuresProperties);
			dataflowRdbmsInitializer.setDataSource(dataSource);
			return dataflowRdbmsInitializer;
		}
```

**Comment by trisberg** [comment]
H2 is a pain to configure as a TCP listening embedded database, it was much easier when we used HSQLDB, not sure why we switched, is going back to HSQLDB an option?

**Comment by markpollack** [comment]
I don't remember, usually we just let you decide these things Thomas ;)

**Comment by cppwfs** [comment]
Hello All,
Starting with what @trisberg said.  There were several discussions at the time on using HSQLDB and H2, but the overall consensus was to move forward with H2.  With that being said, I agree with it being a pain to configure and wouldn't be heart broken if we moved to HSQLDB ;-).  (I was hoping @markpollack remembered the reasons ;-) )

To @dsyer questions:
The use of the H2ServerConfiguration in the DataFlowServerConfiguration was to start the embedded H2 server and then create the transactionManager and the DataflowRdbmsInitializer once the h2 server was started.  The use of @DependsOn was to prevent the creation of the DataflowRdmbsInitializer and transactionManager till after the H2 server was started.  
Now as to why the initH2TCPServer has its own ConditionalExpression, looks to be superfluous and can be removed.  

The use of the NoH2ServerConfiguration in the DataFlowServerConfiguration was to handle external datasources.    

The length of the conditionals was to isolate whether DataFlow should create the H2 server or not, and thus needed to be as specific as possible.   But as you discovered it looks like there is a case that it does not work.  

So the 3 stories I'd recommend:
* Add Javadocs to the DataSource Configuration and remove @ConditionalOnExpression on the initH2TCPServer
* Add property that allows users to prevent the embedded H2 from being started, even though h2 has been selected as a datasource
-or-
* Replace h2 with HSQLDB .

**Comment by dsyer** [comment]
It's not so difficult - it's just a bean definition that starts the server. I would think if we were more careful and explicit about the conditions it should be possible to get it right. And I would stick with H2 because the transaction semantics are stricter (or they were last time I looked).

**Comment by cppwfs** [comment]
The primary issue is how to identify if SCDF should start an embedded database.  At this point the Configuration looks at the datasource url property and if it contains `'jdbc:h2:tcp://localhost:' && contains('/mem:'`  it starts the embedded db and uses this as the datasource.  And if it doesn't meet the requirement then it uses the datasource identified by boot.  

With the use case that a user wants to use an external h2 database connection instead of the embedded one.  We will want to add a property like spring.cloud.dataflow.embedded.database.enabled=true.  If set to false SCDF would not start the embedded database.   Also simplify the condition above to just `'jdbc:h2:tcp://localhost`

At this point I can't see another way to identify whether it should start the embedded service unless we add the property above or something like it.   
   

Thoughts?

**Comment by cppwfs** [comment]
One question did come to mind as well:  
Why do we need the embedded datasource especially if we have dropped the embedded metrics repo and require an external binder (Kafka, Rabbit).  Is this just an artifact of XD that we need to drop as well?
