### ISSUE TITLE
app import --uri http://bit.ly/stream-applications-kafka-maven is not working

### ISSUE THREAD

**Issue by hawkwang** [spring-cloud/spring-cloud-dataflow#935]
When I use "app import --uri http://bit.ly/stream-applications-kafka-maven",
I got:
Command failed java.lang.IllegalArgumentException: java.net.SocketException: Connection reset

I'm wondering if you guys put file to another place, and did not update the document.
And I really want to try with kafka :-)

Regards,
Hawk

**Comment by sabbyanandan** [comment]
Hi, @hawkwang: The latest release of stream-app-starters is at 1.0.4 and this [table](https://github.com/spring-cloud/spring-cloud-dataflow/issues/917) in the project site could be useful. We will update the reference guide to include this table via https://github.com/spring-cloud/spring-cloud-dataflow/issues/917.

That said, the error message doesn't include enough details - could you please share the stacktrace from the server logs? Also, what implementation of SCDF server are you using?

**Comment by hawkwang** [comment]
I use the latest source from github.
And there is no any message displayed in server console.
But I got messages in dataflow console as follows:
----------------------------------------------------------------------------
dataflow:>app import --uri http://bit.ly/stream-applications-kafka-maven
Command failed java.lang.IllegalArgumentException: java.net.SocketException: Connection reset by peer
----------------------------------------------------------------------------
What should I do to make simple "stream create ticktock --definition "time | log" --deploy" work?

**Comment by hawkwang** [comment]
Hi @sabbyanandan,
Ok, I try the http://bit.ly/1-0-4-GA-stream-applications-kafka-maven.
It works, thanks.

Regards,
Hawk

**Comment by sabbyanandan** [comment]
Thanks for the update! We will update the docs with recent release bit.ly's. For questions like this, please consider starting the conversation in [StackOverflow](http://stackoverflow.com/questions/tagged/spring-cloud-dataflow) next time.

**Comment by vishukadam** [comment]
I get error "Command failed java.lang.IllegalArgumentException: java.net.ConnectException: Connection timed out: connect"a
I am using Dataflow shell(Spring boot 1.4.5 and dependency 1.1.0)
