### ISSUE TITLE
Review commented out optionContext property in shell api

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#956]
There are many commands that have the `optionContext` property of `@CliOption` commented out or referenced as a TODO.

**Comment by ericbottard** [comment]
These were there in XD to provide completion of e.g. stream names. I always wanted to take time to re-install that but never got to it. It's not a big hassle, but needs to be done

**Comment by sabbyanandan** [comment]
I looked for commented out `optionContext` in this [search result](https://github.com/spring-cloud/spring-cloud-dataflow/search?q=optionContext&unscoped_q=optionContext), and it appears to have been cleaned up.
