### ISSUE TITLE
LDAP Integration - Add support for StartTLS

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#963]
While SSL over LDAP (LDAPs) is supported, we don't currently support StartTLS out of the box.

In order to use StartTLS we have to configure Spring LDAP with a `DirContextAuthenticationStrategy`, e.g. `DefaultTlsDirContextAuthenticationStrategy`.

As such we have to add an additional YAML property:

`dataflow.security.authentication.ldap.starttls-enabled`

We probably also need to support the ability to switch between the relevant `DirContextAuthenticationStrategy`:
- DefaultTlsDirContextAuthenticationStrategy
- ExternalTlsDirContextAuthenticationStrategy

Testing is a bit of an issue as ApacheDS `1.5` has some iffy support for StartTLS in regards to configuring certificates.

**Comment by ghillert** [comment]
See also:

* https://github.com/spring-projects/spring-security/issues/3176
* https://github.com/spring-projects/spring-security/issues/4096

**Comment by sabbyanandan** [comment]
In 2.x, we will revisit this in the context of OAuth's integration model with LDAP.

**Comment by sabbyanandan** [comment]
Closing this in favor of the UAA's OAuth + LDAP possibilities.
