### ISSUE TITLE
Properties for stream

### ISSUE THREAD

**Issue by bpenergy** [spring-cloud/spring-cloud-dataflow#966]
Hello,

Based on this sample:

dataflow:>stream create --name ticktock --definition "time | log"

i'm wondering if there is quick way or workaround to set Xms and Xmx for time and log applications.

We are migrating from Spring-XD to spring-cloud-dataflow-server-local and each stream takes more than 1GB.

Thanks,

B.

**Comment by sabbyanandan** [comment]
Hi, @bpenergy: There are platform specific configurations you could override at each application level. Just so that we are in the same page, could you clarify which implementation (_eg: cf, yarn, k8s, mesos_) of SCDF are you using?

**Comment by bpenergy** [comment]
Hello @sabbyanandan,

I'm using https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/spring-cloud-dataflow-server-local version 1.0.1.

**Comment by sabbyanandan** [comment]
@bpenergy: There's a glitch with the existing `JAVA_OPTS` and `javaCmd` properties. @donovanmuller captured the problem description very well in #616. Today, we have support to override it in platform specific implementations. For example, you can override the default memory in [cf](http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/current-SNAPSHOT/reference/htmlsingle/#configuring-defaults), [yarn](http://docs.spring.io/spring-cloud-dataflow-server-yarn/docs/current-SNAPSHOT/reference/htmlsingle/#_configuring_application_resources) and others. That said, we are in the process of standardizing how these properties get (consistently) translated across different implementations via: spring-cloud/spring-cloud-deployer/issues/116.

**Comment by sabbyanandan** [comment]
Hi, @bpenergy. Apologies for the delayed response. This is supported since the 1.1.x release - here's an [example](http://docs.spring.io/spring-cloud-dataflow/docs/1.2.2.RELEASE/reference/htmlsingle/#getting-started-application-configuration) how you can override the settings via DSL.
