### ISSUE TITLE
Filter out of the box counters at the REST response

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#970]
_From @sabbyanandan on October 21, 2016 14:42_

As a user, I deployed a stream (`time | counter`) to Kubernetes and while reviewing the charts under "Counters" tab, I also see `status.200.health` and `status.200.info` endpoints - see image below. These endpoints are Kubernetes specific and they're used to keep track of running app pods. 

![image](https://cloud.githubusercontent.com/assets/1562654/19602294/981e6814-9761-11e6-8da1-ec5c66a6c3ed.png)

_Copied from original issue: spring-cloud/spring-cloud-dataflow-ui#135_

**Comment by ilayaperumalg** [comment]
_From @BoykoAlex on October 25, 2016 20:53_

@ghillert @ilayaperumalg shall we filter `health` and `info` counters on the SCDF REST endpoint side perhaps? This just looks more of a server side issue rather than UI...

**Comment by ilayaperumalg** [comment]
@BoykoAlex yeah, if these counters are some of the built-in out of the box counters, then we would need to filter them at the server side.

**Comment by sabbyanandan** [comment]
"Analytics" tab is removed in v2.0. This is not relevant anymore.
