### ISSUE TITLE
Field-value-counter name is not getting set

### ISSUE THREAD

**Issue by naheedmk** [spring-cloud/spring-cloud-dataflow#972]
Hi,
I am trying twitter sample project (https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/analytics/twitter-analytics).  Everthing works except the field-value-counter for hashtag and languages are not getting set despite proving --name option.  The counter name is getting set to "field-value-counter" and both hashtag and language are using same counter. Wondering how to set the field value counter name explicitly.

Thanks
Naheed

**Comment by sabbyanandan** [comment]
Hi, @naheedmk: If you're following the sample in entirety, you should be able to see two separate key collection in redis and as well in the SCDF. The property `--name=` defines the collection key explicitly and in this case, you'd see the following. 

in redis:
```
127.0.0.1:6379> KEYS *fieldvalue*
1) "fieldvaluecounters.language"
2) "fieldvaluecounters.hashtags"
```

in scdf shell:
```
dataflow:>field-value-counter list
╔════════════════════════╗
║Field Value Counter name║
╠════════════════════════╣
║hashtags                ║
║language                ║
╚════════════════════════╝
```

This should be functional [both](http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#spring-cloud-dataflow-register-apps) in SNAPSHOT and 1.0.4 release of stream-app-starters. Make sure there aren't any errors in the server or in individual app logs. If you're seeing anything abnormal, please reopen this issue with more details/logs.

**Comment by naheedmk** [comment]
App starters are registerd using following URL as per doc :

app import --uri http://bit.ly/stream-applications-kafka-maven

Stream is registed as follows :

stream create tweetlang  --definition ":tweets.twitterstream > field-value-counter --field-value-counter.fieldName=lang --name=language" --deploy  (Note : I have to provide "field-valuepconter.fieldName" to get that property read)



Field Value counters are as shown below

dataflow:>field-value-counter list
╔════════════════════════╗
║Field Value Counter name║
╠════════════════════════╣
║field-value-counter     ║
╚════════════════════════


It seems app import URL may be outdated not referring 1.0.4 or snapshot version.

**Comment by naheedmk** [comment]
Issue is the property "name" needs prefix
stream create tagcount --definition ":tweets.twitterstream > field-value-counter --field-value-counter.fieldName=entities.hashtags.text **--field-value-counter.name**=hashtags" --deploy

The document has following command, which does not use prefix
stream create tagcount --definition ":tweets.twitterstream > field-value-counter --fieldName=entities.hashtags.text **--name=hashtags"** --deploy

It worked and created field-counter-value when I used the property with prefix.

Thanks
Naheed

**Comment by sabbyanandan** [comment]
Thanks for the update.

The problem in this case could be the use of older (1.0.0) SNAPSHOTs. As indicated previously, you could use the latest bit.ly links provided in the [docs](http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#spring-cloud-dataflow-register-apps). With this setup, you wouldn't have to use the prefix and it will be handled by SCDF automatically. The sample should reflect the latest bit.ly link now.

**Comment by naheedmk** [comment]
Thanks. I followed the document https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/analytics/twitter-analytics
It may be good if that document is updated as people trying this will confused otherwise.

Thanks
Naheed
