### ISSUE TITLE
Is Spring XD really scheduled for EOL in 2107? or 2017?

### ISSUE THREAD

**Issue by Nyamiou** [spring-cloud/spring-cloud-dataflow#977]
Hello,

The documentation [here ](http://projects.spring.io/spring-xd/) say "Spring XD's 1.3 GA will be the last release in the 1.x line and with this release, 1.x will be officially in maintenance mode, addressing only bug fixes. Spring XD is scheduled for EOL/EOA by Q2 **2107**." But it's a little strange, can you confirm the date?

Thank you.

**Comment by ilayaperumalg** [comment]
Hi @Nyamiou,

Thanks for reporting this. That is indeed a typo :-) we will get this fixed soon.

**Comment by ilayaperumalg** [comment]
This issue was moved to spring-projects/spring-xd#1922
