### ISSUE TITLE
Configure Dataflow Server to use custom maven location

### ISSUE THREAD

**Issue by ashwgupt** [spring-cloud/spring-cloud-dataflow#982]
I am working with Dataflow Server Local and wish to use my locally hosted URIs for registering a module or app. Based upon suggestions from other issue, I've  used the file:// descriptor to register my apps with local jar files from Dataflow Shell. 

However when I create the stream, the data flow server still goes out to the external repo (which is not desired due to our proxy requirements) and that cause it to fail with below exception at dataflow server shell logs: 
```Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: failed to resolve MavenResource:...```
and at Dataflow server level with: ```Caused by: java.net.UnknownHostException: repo.spring.io```

Is there a way to start the Dataflow server with configuration such that it uses a custom Maven repository location e.g. local or our enterprise maven repo, instead of its default one?

Apologies if this is already documented but I failed to find so.

FYI: The command used are:
```
> app register --name task-processor --type processor --uri file:///Users/ABC/apache-maven-3.3.9/.m2/repository/io/spring/cloud/taskprocessor/1.1.0.BUILD-SNAPSHOT/taskprocessor-1.1.0.BUILD-SNAPSHOT.jar
> app register --name task-launcher-local --type sink --uri file:///Users/ABC/apache-maven-3.3.9/.m2/repository/org/springframework/cloud/stream/app/spring-cloud-starter-stream-sink-task-launcher-local/1.1.0.BUILD-SNAPSHOT/spring-cloud-starter-stream-sink-task-launcher-local-1.1.0.BUILD-SNAPSHOT.jar
> stream create foo --definition "rabbit --rabbit.queues=cloud-stream-source --rabbit.requeue=true --spring.rabbitmq.host=localhost --spring.rabbitmq.port=5672 --spring.cloud.stream.bindings.output.contentType='text/plain' | task-processor --uri=file:///Users/ABC/apache-maven-3.3.9/.m2/repository/com/example/thumbnail-generator/0.0.1-SNAPSHOT/thumbnail-generator-0.0.1-SNAPSHOT.jar | task-launcher-local" --deploy
```

**Comment by ilayaperumalg** [comment]
Hi @ashwgupt,

You can install your apps locally into local maven repository. The `local` deployer would resolve the `maven` resource from there. You need to use maven resource URI (ex: `maven://com.mypackage:myapp:1.0.0.BUILD-SNAPSHOT`).
You can find more info [here] (http://docs.spring.io/spring-cloud-dataflow/docs/1.1.0.BUILD-SNAPSHOT/reference/html/getting-started-deploying-spring-cloud-dataflow.html)

**Comment by ashwgupt** [comment]
Hi @ilayaperumalg

Unfortunately that doesn't work. If I use maven uri, data flow server attempts to download even the task processor and task launcher from external repo.

After many trials and search I could solve those by using file uri in my registration command. However I don have any control on data flow server downloading rabbit dependencies and that is where it still goes to remote Repo.

Any inputs?

**Comment by ilayaperumalg** [comment]
> Unfortunately that doesn't work. If I use maven uri, data flow server attempts to download even the task processor and task launcher from external repo.

The `local` repo uses the `https://repo.spring.io/libs-snapshot` maven repo by default. But if you don't want to connect to `spring` repo, you can still use your enterprise maven repo by setting this property:
```
maven:
  remoteRepositories:
    myRepo:
      url: https://my-custom-repo
```
The other way around is to download the apps is via `docker` but it is not yet supported in `local` deployer: https://github.com/spring-cloud/spring-cloud-dataflow/issues/695

**Comment by ashwgupt** [comment]
Great! this solved my problem and helped me use our enterprise repository.

Thanks

**Comment by rajaramkushwaha** [comment]
We can point local maven repository by setting the file based URL:
Below is complete example:
java -jar spring-cloud-dataflow-server-local-1.3.0.BUILD-SNAPSHOT.jar
--maven.localRepository=mylocal --maven.remote-repositories.repo1.url=file:///C:/Users/<yourusername>/.m2/repository/

**Comment by hendisantika** [comment]
> > Unfortunately that doesn't work. If I use maven uri, data flow server attempts to download even the task processor and task launcher from external repo.
> 
> The `local` repo uses the `https://repo.spring.io/libs-snapshot` maven repo by default. But if you don't want to connect to `spring` repo, you can still use your enterprise maven repo by setting this property:
> 
> ```
> maven:
>   remoteRepositories:
>     myRepo:
>       url: https://my-custom-repo
> ```
> 
> The other way around is to download the apps is via `docker` but it is not yet supported in `local` deployer: #695

Where we can setting this config @ilayaperumalg ?
Thanks

**Comment by ilayaperumalg** [comment]
@hendisantika  You can set this as server level property and doc for this is available [here](http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#configuration-maven)

**Comment by MariusKl** [comment]
> > Unfortunately that doesn't work. If I use maven uri, data flow server attempts to download even the task processor and task launcher from external repo.
> 
> The `local` repo uses the `https://repo.spring.io/libs-snapshot` maven repo by default. But if you don't want to connect to `spring` repo, you can still use your enterprise maven repo by setting this property:
> 
> ```
> maven:
>   remoteRepositories:
>     myRepo:
>       url: https://my-custom-repo
> ```
> 
> The other way around is to download the apps is via `docker` but it is not yet supported in `local` deployer: #695

Hi @ilayaperumalg,

you wrote that an own repo will replace the spring repo. I added this
```
maven:
  remoteRepositories:
    myRepo:
      url: xxx
      auth:
        username: xxx
        password: xxx
```
but end up with two remote repositores, both "myRepo" and "springRepo" in `MavenProperties.setRemoteRepositories`. I could not find any option to remove the springRepo. Is it possible?
