### ISSUE TITLE
Adopt dependencies to versions in Camden.SR2

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#983]
To go along with the version changes in the deployer - https://github.com/spring-cloud/spring-cloud-deployer/issues/138

**Comment by trisberg** [comment]
These changes need to be coordinated with #976

**Comment by markpollack** [comment]
Closed as duplicate of https://github.com/spring-cloud/spring-cloud-dataflow/pull/994
